const num=value=>{const raw=String(value??'').trim().replace(/%/g,'');if(!raw)return 0;let normalized=raw;if(raw.includes(',')&&raw.includes('.'))normalized=raw.lastIndexOf(',')>raw.lastIndexOf('.')?raw.replace(/\./g,'').replace(',','.'):raw.replace(/,/g,'');else if(raw.includes(','))normalized=raw.replace(',','.');const n=Number(normalized);return Number.isFinite(n)?n:0};
const round2=n=>Math.round((Number(n||0)+Number.EPSILON)*100)/100;
const norm=value=>String(value||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLocaleUpperCase('el-GR').replace(/[^A-ZΑ-Ω0-9]/g,'');

const deriveCode=line=>{const raw=String(line?.rawText||'').trim();const fromRaw=raw.match(/^\s*(\d{5,14})\b/);if(fromRaw)return fromRaw[1];return String(line?.code||'').trim()};
function rawColumns(raw){const text=String(raw||'').replace(/\s+/g,' ').trim();const unitMatch=text.match(/\b(TEM|ΤΕΜ|ΤΜΧ|PCS|PC|KG|KGR|LT|L)\b/i);if(!unitMatch)return null;const unit=unitMatch[0],tail=text.slice(unitMatch.index+unit.length).trim();let parts=[];if(tail.includes('|'))parts=tail.split('|').map(x=>x.trim()).filter(Boolean);else parts=(tail.match(/\d+(?:[.,]\d+)?%?/g)||[]);return {unit,numeric:parts.map(p=>num(p)).filter(Number.isFinite)}}
function parseCommercial(raw,line){let quantity=Math.max(0,Number(line?.quantity||0)),price=Math.max(0,Number(line?.unitCost||0)),initial=0,d1=0,d1a=0,d2=0,d2a=0,d3=0,d3a=0,netAmount=Math.max(0,Number(line?.netAmount||0)),vatRate=Math.max(0,Number(line?.vatRate||0)),grossAmount=Math.max(0,Number(line?.grossAmount||0));const rc=rawColumns(raw);if(rc&&rc.numeric.length>=3){const a=rc.numeric;quantity=a[0]>0?a[0]:quantity;price=a[1]>0?a[1]:price;initial=a[2]>0?a[2]:quantity*price;if(a.length>=4){netAmount=a[a.length-1]>0?a[a.length-1]:netAmount;const mid=a.slice(3,-1);d1=mid[0]||0;d1a=mid[1]||0;d2=mid[2]||0;d2a=mid[3]||0;d3=mid[4]||0;d3a=mid[5]||0}}if(!initial&&quantity>0&&price>0)initial=quantity*price;if(initial>0&&netAmount>0&&initial>netAmount){const diff=round2(initial-netAmount);if(d1a<=0)d1a=diff;if(d1<=0&&diff>0)d1=round2(diff/initial*100)}if(!netAmount&&initial>0){let calc=initial;if(d1a>0)calc-=d1a;else if(d1>0)calc*=1-d1/100;if(d2a>0)calc-=d2a;else if(d2>0)calc*=1-d2/100;if(d3a>0)calc-=d3a;else if(d3>0)calc*=1-d3/100;netAmount=Math.max(0,calc)}if(!grossAmount&&netAmount>0)grossAmount=netAmount*(1+vatRate/100);return {quantity,unitCost:price,initialAmount:initial,discount1:d1,discount1Amount:d1a,discount2:d2,discount2Amount:d2a,discount3:d3,discount3Amount:d3a,netAmount,vatRate,grossAmount}}
const canonicalText=value=>{let s=String(value||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toUpperCase();s=s.replace(/ΚΟΚΑ\s*ΚΟΛΑ/g,'COCA COLA').replace(/ΣΠΡΑΙΤ/g,'SPRITE').replace(/ΦΑΝΤΑ/g,'FANTA').replace(/ΡΕΝΤ\s*ΜΠΟΥΛ/g,'RED BULL');s=s.replace(/\b(1PACK|1\s*POD|C20U|C12U|C14U|C38U|1X6PACK|1X24|12X0[.,]?75LT?|12PACK|24PACK|6PACK)\b/ig,' ');return norm(s.replace(/\s+/g,' ').trim())};
const enrich=line=>{const code=deriveCode(line),description=String(line?.description||'').replace(/^\s*\d{5,14}\s+/,'').replace(/\s+/g,' ').trim();return {...line,code,description,...parseCommercial(line?.rawText,line)}};
function score(line){const e=enrich(line);let s=0;if(e.code)s+=25;if(e.quantity>0)s+=20;if(e.unitCost>0)s+=20;if(e.netAmount>0)s+=20;s+=Math.min(15,String(e.rawText||'').length/30);return s}
function dedupe(lines){const out=[];for(const source of lines||[]){const row=enrich(source),key=canonicalText(row.description||row.rawText);if(!row.code&&!key)continue;let index=-1;for(let i=0;i<out.length;i++){const other=enrich(out[i]),otherKey=canonicalText(other.description||other.rawText),sameCode=row.code&&other.code&&row.code===other.code,close=key&&otherKey&&(key===otherKey||key.includes(otherKey)||otherKey.includes(key));if(sameCode||close){index=i;break}}if(index<0){out.push(row);continue}const current=out[index],better=score(row)>score(current)?row:current,worse=better===row?current:row,merged={...better};for(const k of ['code','barcode','description','unit'])if(!String(merged[k]||'').trim()&&String(worse[k]||'').trim())merged[k]=worse[k];for(const k of ['quantity','unitCost','initialAmount','discount1','discount1Amount','discount2','discount2Amount','discount3','discount3Amount','netAmount','vatRate','grossAmount','confidence'])if(Number(merged[k]||0)<=0&&Number(worse[k]||0)>0)merged[k]=worse[k];out[index]=merged}return out}
function packRule(line){const d=String(line?.description||line?.rawText||'').toLocaleUpperCase('el-GR').replace(/,/g,'.'),u=String(line?.unit||'').toLocaleUpperCase('el-GR');if(!/(ΚΙΒ|ΚΒ|CASE|BOX)/.test(u+' '+d))return null;if(/MONSTER|RED\s*BULL|REDBULL/.test(d))return {pcs:24,rule:'Monster / Red Bull'};if(/(1\.5\s*(L|LT)\b|1500\s*ML\b)/.test(d))return {pcs:6,rule:'1,5L'};if(/(330\s*ML\b|0\.33\s*L\b|33\s*CL\b)/.test(d))return {pcs:24,rule:'330ml'};if(/(500\s*ML\b|0\.5\s*L\b|50\s*CL\b)/.test(d))return {pcs:24,rule:'500ml'};if(/ΦΙΑΛ|BOTTLE/.test(d))return {pcs:20,rule:'Φιάλες'};if(/ΝΕΡΟ|WATER|ΖΑΓΟΡΙ|ΘΕΩΝΗ/.test(d)&&/(750\s*ML|0\.75\s*L)/.test(d))return {pcs:12,rule:'Νερό 750ml'};return null}
export function finalizeV244ProductLines(lines){return dedupe(lines).map(line=>{const e=enrich(line),pack=packRule(e);return {...e,rawText:String(e.rawText||e.description||''),code:String(e.code||''),barcode:String(e.barcode||''),description:String(e.description||'').trim(),quantity:Number(e.quantity||0),unit:String(e.unit||'ΤΜΧ'),unitsPerPackage:Number(e.unitsPerPackage||pack?.pcs||0),unitCost:Number(e.unitCost||0),initialAmount:Number(e.initialAmount||0),discount1:Number(e.discount1||0),discount1Amount:Number(e.discount1Amount||0),discount2:Number(e.discount2||0),discount2Amount:Number(e.discount2Amount||0),discount3:Number(e.discount3||0),discount3Amount:Number(e.discount3Amount||0),netAmount:Number(e.netAmount||0),vatRate:Number(e.vatRate||0),grossAmount:Number(e.grossAmount||0),confidence:Number(e.confidence||0),packRule:pack?.rule||''}}).filter(line=>line.description&&line.quantity>0&&line.unitCost>0)}
