param([string]$PairingCode,[string]$ApiBase="https://myworkstation-app.onrender.com",[string]$NvrEndpoint="",[ValidateSet("DAHUA_CGI","ONVIF")][string]$Protocol="DAHUA_CGI",[string]$FfmpegPath="")
$ErrorActionPreference="Stop";Add-Type -AssemblyName System.Security
$principal=New-Object Security.Principal.WindowsPrincipal([Security.Principal.WindowsIdentity]::GetCurrent());if(!$principal.IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)){throw "Run INSTALL_VIDEO_CONNECTOR_KAT.cmd as Administrator."}
if([string]::IsNullOrWhiteSpace($PairingCode)){$PairingCode=Read-Host "Pairing code from MyWorkStation"};$source=Split-Path -Parent $MyInvocation.MyCommand.Path;if([string]::IsNullOrWhiteSpace($NvrEndpoint)){$found=@(& (Join-Path $source "Discover-VideoDevices.ps1"));$suggested=if($found.Count){$found[0].endpoint}else{"http://192.168.1.108"};$entered=Read-Host ("Local Dahua NVR endpoint [{0}]" -f $suggested);$NvrEndpoint=if([string]::IsNullOrWhiteSpace($entered)){$suggested}else{$entered}};if([string]::IsNullOrWhiteSpace($FfmpegPath)){$ffmpeg=Get-Command ffmpeg.exe -ErrorAction SilentlyContinue;if($ffmpeg){$FfmpegPath=$ffmpeg.Source}else{$FfmpegPath=Read-Host "Full path to ffmpeg.exe (required for Audit clips)"}};if(!(Test-Path -LiteralPath $FfmpegPath)){throw "ffmpeg.exe is required for secure browser-compatible clip preview."};$username=Read-Host "Dahua read-only username";$password=Read-Host "Dahua read-only password" -AsSecureString
$plainPassword=[Runtime.InteropServices.Marshal]::PtrToStringBSTR([Runtime.InteropServices.Marshal]::SecureStringToBSTR($password));try{
  & (Join-Path $source "Preflight-VideoConnector.ps1") -ApiBase $ApiBase -NvrEndpoint $NvrEndpoint
  if($LASTEXITCODE -ne 0){throw "Preflight failed."};$root="C:\ProgramData\MyWorkStation\VideoConnector";New-Item -ItemType Directory -Path $root -Force|Out-Null
  foreach($file in @("VideoConnector.ps1","Status-VideoConnector.ps1","Discover-VideoDevices.ps1")){Copy-Item (Join-Path $source $file) $root -Force}
  $pairBody=@{code=$PairingCode;deviceName=("KAT Video Connector - "+$env:COMPUTERNAME);deviceKey=("video-connector:"+$env:COMPUTERNAME.ToLowerInvariant());platform="Windows Dahua Read-Only Connector";metadata=@{connectorType="VIDEO_DAHUA_READONLY";outboundOnly=$true;readOnly=$true}}|ConvertTo-Json -Depth 5 -Compress
  $pair=Invoke-RestMethod -Uri ($ApiBase.TrimEnd("/")+"/api/cloud/v1/pair") -Method Post -ContentType "application/json; charset=utf-8" -Body $pairBody -TimeoutSec 30
  function Protect([string]$Value){return [Convert]::ToBase64String([Security.Cryptography.ProtectedData]::Protect([Text.Encoding]::UTF8.GetBytes($Value),$null,[Security.Cryptography.DataProtectionScope]::LocalMachine))}
  $credential=@{username=$username;password=$plainPassword}|ConvertTo-Json -Compress
  @{apiBase=$ApiBase.TrimEnd("/");nvrEndpoint=$NvrEndpoint.TrimEnd("/");protocol=$Protocol;ffmpegPath=$FfmpegPath;protectedToken=(Protect $pair.token);protectedNvrCredential=(Protect $credential);deviceId=$pair.device.id;storeId=$pair.device.storeId;installedAt=[DateTime]::UtcNow.ToString("o");outboundOnly=$true;readOnly=$true}|ConvertTo-Json|Set-Content -LiteralPath (Join-Path $root "video-connector.config.json") -Encoding UTF8
  $taskName="MyWorkStation Dahua Video Connector";$taskCommand="powershell.exe -NoProfile -ExecutionPolicy Bypass -WindowStyle Hidden -File `"$root\VideoConnector.ps1`"";& schtasks.exe /Create /TN $taskName /SC ONSTART /RU SYSTEM /RL HIGHEST /TR $taskCommand /F|Out-Null;if($LASTEXITCODE -ne 0){throw "Could not create startup task."};& schtasks.exe /Run /TN $taskName|Out-Null
  Write-Host "VIDEO CONNECTOR INSTALLED - OUTBOUND ONLY / READ ONLY" -ForegroundColor Green;Write-Host "Credentials are protected with Windows DPAPI LocalMachine."
}finally{$plainPassword=$null;$password=$null};Read-Host "Press Enter to close"
