import React,{useEffect,useMemo,useRef,useState} from "react";
import {Barcode,Camera,CheckCircle2,LogIn,RefreshCw,Search,Wifi,WifiOff,X} from "lucide-react";
import {matchesGreekSearch} from "../../utils/greek-search.js";
import "./inventory-mobile.css";
import "./inventory-mobile-fast.css";

const deviceId=()=>{let value=localStorage.getItem("mws:inventory:device");if(!value){value=crypto.randomUUID();localStorage.setItem("mws:inventory:device",value)}return value};
const eventId=()=>crypto.randomUUID();
const n=value=>Number(value||0);
export default function InventoryMobileApp({stocktakeId}){
  const grant=new URLSearchParams(location.search).get("grant")||"",[token,setToken]=useState(()=>sessionStorage.getItem(`inventory:${stocktakeId}`)||""),[pin,setPin]=useState(""),[data,setData]=useState(null),[q,setQ]=useState(""),[selected,setSelected]=useState(null),[quantity,setQuantity]=useState(""),[matches,setMatches]=useState([]),[showAll,setShowAll]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(""),[message,setMessage]=useState(""),[online,setOnline]=useState(navigator.onLine),[scannerOpen,setScannerOpen]=useState(false),[cameraStream,setCameraStream]=useState(null);
  const searchRef=useRef(null),quantityRef=useRef(null),videoRef=useRef(null),scanFrameRef=useRef(0),scanLockedRef=useRef(false);
  const request=async(path,options={})=>{const response=await fetch(path,{...options,headers:{"Content-Type":"application/json",...(token?{Authorization:`Bearer ${token}`}:{})}}),body=await response.json().catch(()=>({}));if(!response.ok)throw new Error(body.error||`Σφάλμα ${response.status}`);return body};
  const load=async()=>{if(!token)return;setBusy(true);setError("");try{setData(await request(`/api/inventory-v2/stocktakes/${encodeURIComponent(stocktakeId)}`))}catch(e){setError(e.message)}finally{setBusy(false)}};
  useEffect(()=>{load()},[token]);useEffect(()=>{const update=()=>setOnline(navigator.onLine);addEventListener("online",update);addEventListener("offline",update);if("serviceWorker" in navigator)navigator.serviceWorker.register("/inventory-sw.js").catch(()=>{});return()=>{removeEventListener("online",update);removeEventListener("offline",update)}},[]);
  const redeem=async event=>{event.preventDefault();setBusy(true);setError("");try{const response=await fetch("/api/public/inventory-v2/redeem",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({stocktakeId,grantToken:grant,pin})}),body=await response.json().catch(()=>({}));if(!response.ok)throw new Error(body.error||"Η πρόσβαση απέτυχε.");sessionStorage.setItem(`inventory:${stocktakeId}`,body.token);setToken(body.token)}catch(e){setError(e.message)}finally{setBusy(false)}};
  const counted=useMemo(()=>(data?.lines||[]).filter(row=>row.countedQuantity!==null).sort((a,b)=>new Date(b.countedAt||0)-new Date(a.countedAt||0)),[data]);
  const visible=showAll?[...(data?.lines||[])].sort((a,b)=>new Date(b.countedAt||0)-new Date(a.countedAt||0)):counted;
  const choose=row=>{setSelected(row);setMatches([]);setQ(row.barcode||row.sku||row.name);setQuantity("1");setTimeout(()=>{quantityRef.current?.focus();quantityRef.current?.select()})};
  const resolveTerm=value=>{const term=value.trim();if(!term)return searchRef.current?.focus();setError("");const found=(data?.lines||[]).filter(row=>matchesGreekSearch(term,[row.name,row.sku,row.barcode]));const exact=found.find(row=>row.barcode===term||String(row.sku||"")===term);if(exact||found.length===1)return choose(exact||found[0]);setSelected(null);setMatches(found.slice(0,10));if(!found.length)setError(`Δεν βρέθηκε το barcode «${term}». Ενημέρωσε τον διαχειριστή για νέο είδος.`)};
  const find=event=>{event?.preventDefault();resolveTerm(q)};
  const stopScanner=()=>{cancelAnimationFrame(scanFrameRef.current);scanFrameRef.current=0;scanLockedRef.current=false;cameraStream?.getTracks().forEach(track=>track.stop());setCameraStream(null);setScannerOpen(false)};
  const startScanner=async()=>{setError("");if(!window.BarcodeDetector)return setError("Η αυτόματη σάρωση δεν υποστηρίζεται από αυτόν τον browser. Άνοιξε τη σελίδα με το Chrome ή πληκτρολόγησε το barcode.");if(!navigator.mediaDevices?.getUserMedia)return setError("Η κάμερα δεν υποστηρίζεται από αυτόν τον browser.");try{const stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:"environment"},width:{ideal:1280},height:{ideal:720}},audio:false});setCameraStream(stream);setScannerOpen(true)}catch{setError("Δεν άνοιξε η κάμερα. Επίτρεψε την πρόσβαση στην κάμερα από τις ρυθμίσεις του browser.")}};
  useEffect(()=>{if(!scannerOpen||!cameraStream||!videoRef.current)return;const video=videoRef.current;video.srcObject=cameraStream;const detector=new window.BarcodeDetector({formats:["ean_13","ean_8","upc_a","upc_e","code_128","code_39","itf","codabar","qr_code"]});let stopped=false;const scan=async()=>{if(stopped||scanLockedRef.current)return;if(video.readyState>=2)try{const codes=await detector.detect(video);const value=String(codes?.[0]?.rawValue||"").trim();if(value){scanLockedRef.current=true;navigator.vibrate?.(120);setQ(value);setMessage(`Σκαναρίστηκε: ${value}`);stopScanner();resolveTerm(value);return}}catch{}scanFrameRef.current=requestAnimationFrame(scan)};video.play().then(scan).catch(()=>setError("Η προεπισκόπηση της κάμερας δεν ξεκίνησε."));return()=>{stopped=true;cancelAnimationFrame(scanFrameRef.current)}},[scannerOpen,cameraStream,data]);
  useEffect(()=>()=>{cameraStream?.getTracks().forEach(track=>track.stop())},[cameraStream]);
  const save=async event=>{event?.preventDefault();if(!selected||quantity===""||!Number.isFinite(Number(quantity)))return;if(!online)return setError("Δεν υπάρχει σύνδεση. Η καταχώρηση δεν αποθηκεύτηκε.");setBusy(true);setError("");try{const total=n(selected.countedQuantity)+Number(quantity);await request(`/api/inventory-v2/stocktakes/${encodeURIComponent(stocktakeId)}/count`,{method:"POST",body:JSON.stringify({lineId:selected.id,quantity:total,expectedVersion:selected.countVersion,clientEventId:eventId(),deviceId:deviceId(),source:"QR_PIN"})});setMessage(`${selected.name}: σύνολο ${total}`);await load();setQ("");setSelected(null);setQuantity("");setMatches([]);setTimeout(()=>searchRef.current?.focus())}catch(e){setError(e.message);await load()}finally{setBusy(false)}};
  if(!token)return <main className="inventory-mobile login"><form onSubmit={redeem}><Barcode size={42}/><h1>MyWorkStation Inventory</h1><p>Προσωρινή πρόσβαση μόνο στη συγκεκριμένη απογραφή και ζώνη.</p><label>PIN 6 ψηφίων<input inputMode="numeric" pattern="[0-9]{6}" maxLength="6" value={pin} onChange={e=>setPin(e.target.value.replace(/\D/g,""))} autoFocus required/></label>{error&&<div className="inv-error">{error}</div>}<button disabled={busy||pin.length!==6}><LogIn/> {busy?"Έλεγχος…":"Είσοδος στην απογραφή"}</button></form></main>;
  const total=(data?.lines||[]).length;
  return <main className="inventory-mobile"><header><div><small>INVENTORY 2.0 · {data?.storeName}</small><h1>{data?.name||"Απογραφή"}</h1><p>{counted.length}/{total} μετρήθηκαν</p></div><span className={online?"online":"offline"}>{online?<Wifi/>:<WifiOff/>}{online?"Online":"Offline"}</span></header><section className="inv-progress"><i style={{width:`${total?counted.length/total*100:0}%`}}/></section><section className="inv-mobile-fast"><form onSubmit={find}><label><b>1. Σκάναρε barcode ή αναζήτησε είδος</b><span><Search/><input ref={searchRef} value={q} onChange={e=>{setQ(e.target.value);setSelected(null);setMatches([])}} placeholder="Barcode, SKU ή προϊόν" autoFocus/><button>Αναζήτηση</button><button type="button" className="inv-camera-button" onClick={startScanner}><Camera/> Σάρωση με κάμερα</button></span></label><label><b>2. Νέα ποσότητα που βρήκες</b><span><input ref={quantityRef} type="number" min="0" step="0.001" value={quantity} disabled={!selected} onChange={e=>setQuantity(e.target.value)}/><button type="button" disabled={!selected||busy} onClick={save}>Καταχώρηση & επόμενο</button></span></label></form>{selected&&<div className="inv-mobile-selected"><b>{selected.name}</b><span>Απόθεμα {selected.expectedQuantity}</span>{selected.countedQuantity!==null&&<strong>Προηγούμενα {selected.countedQuantity} + νέα {n(quantity)} = σύνολο {n(selected.countedQuantity)+n(quantity)}</strong>}</div>}{matches.length>1&&<div className="inv-mobile-matches">{matches.map(row=><button key={row.id} onClick={()=>choose(row)}><b>{row.name}</b><small>{row.barcode||row.sku}</small></button>)}</div>}</section>{scannerOpen&&<div className="inv-scanner" role="dialog" aria-modal="true" aria-label="Σάρωση barcode"><section><header><b>Σάρωση barcode</b><button type="button" onClick={stopScanner} aria-label="Κλείσιμο κάμερας"><X/></button></header><div className="inv-scanner-view"><video ref={videoRef} autoPlay playsInline muted/><i/><span>Τοποθέτησε το barcode μέσα στο πλαίσιο</span></div><button type="button" onClick={stopScanner}>Ακύρωση</button></section></div>}{error&&<div className="inv-error">{error}</div>}{message&&<div className="inv-message">{message}</div>}<div className="inv-mobile-tools"><b>{showAll?"Όλα τα είδη":"Πρόσφατες καταμετρήσεις"}</b><button onClick={()=>setShowAll(v=>!v)}>{showAll?"Μόνο καταμετρημένα":"Εμφάνιση όλων"}</button><button onClick={load} aria-label="Ανανέωση"><RefreshCw/></button></div><section className="inv-list">{visible.map(row=><article key={row.id} className={row.recountRequired?"recount":""}><div><b>{row.name}</b><small>{row.barcode||row.sku||"Χωρίς κωδικό"} · {row.zoneName||"Χωρίς ζώνη"}</small>{row.recountRequired&&<em>ΑΠΑΙΤΕΙΤΑΙ ΕΠΑΝΑΚΑΤΑΜΕΤΡΗΣΗ</em>}</div><label>Σύνολο<input readOnly value={row.countedQuantity??""}/>{row.countedQuantity!==null&&<CheckCircle2/>}</label></article>)}</section>{busy&&<div className="inv-busy">Συγχρονισμός…</div>}</main>;
}
