import React,{useEffect,useMemo,useState} from "react";
import {Barcode,CheckCircle2,LogIn,RefreshCw,Search,Wifi,WifiOff} from "lucide-react";
import "./inventory-mobile.css";

const deviceId=()=>{let value=localStorage.getItem("mws:inventory:device");if(!value){value=crypto.randomUUID();localStorage.setItem("mws:inventory:device",value)}return value};
const eventId=()=>crypto.randomUUID();
export default function InventoryMobileApp({stocktakeId}){
  const grant=new URLSearchParams(location.search).get("grant")||"",[token,setToken]=useState(()=>sessionStorage.getItem(`inventory:${stocktakeId}`)||""),[pin,setPin]=useState(""),[data,setData]=useState(null),[q,setQ]=useState(""),[busy,setBusy]=useState(false),[error,setError]=useState(""),[message,setMessage]=useState(""),[online,setOnline]=useState(navigator.onLine);
  const request=async(path,options={})=>{const response=await fetch(path,{...options,headers:{"Content-Type":"application/json",...(token?{Authorization:`Bearer ${token}`}:{})}}),body=await response.json().catch(()=>({}));if(!response.ok)throw new Error(body.error||`Σφάλμα ${response.status}`);return body};
  const load=async()=>{if(!token)return;setBusy(true);setError("");try{setData(await request(`/api/inventory-v2/stocktakes/${encodeURIComponent(stocktakeId)}`))}catch(e){setError(e.message)}finally{setBusy(false)}};
  useEffect(()=>{load()},[token]);useEffect(()=>{const update=()=>setOnline(navigator.onLine);addEventListener("online",update);addEventListener("offline",update);if("serviceWorker" in navigator)navigator.serviceWorker.register("/inventory-sw.js").catch(()=>{});let manifest=document.querySelector('link[rel="manifest"]');if(!manifest){manifest=document.createElement("link");manifest.rel="manifest";manifest.href="/inventory-manifest.webmanifest";document.head.appendChild(manifest)}return()=>{removeEventListener("online",update);removeEventListener("offline",update)}},[]);
  const redeem=async event=>{event.preventDefault();setBusy(true);setError("");try{const response=await fetch("/api/public/inventory-v2/redeem",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({stocktakeId,grantToken:grant,pin})}),body=await response.json().catch(()=>({}));if(!response.ok)throw new Error(body.error||"Η πρόσβαση απέτυχε.");sessionStorage.setItem(`inventory:${stocktakeId}`,body.token);setToken(body.token)}catch(e){setError(e.message)}finally{setBusy(false)}};
  const rows=useMemo(()=>{const needle=q.trim().toLocaleUpperCase("el-GR");return (data?.lines||[]).filter(row=>!needle||[row.name,row.sku,row.barcode].some(x=>String(x||"").toLocaleUpperCase("el-GR").includes(needle)))},[data,q]);
  const save=async(row,value)=>{if(!online)return setError("Offline: η μέτρηση μένει στην οθόνη αλλά δεν οριστικοποιείται χωρίς σύνδεση.");setBusy(true);setError("");try{await request(`/api/inventory-v2/stocktakes/${encodeURIComponent(stocktakeId)}/count`,{method:"POST",body:JSON.stringify({lineId:row.id,quantity:Number(value),expectedVersion:row.countVersion,clientEventId:eventId(),deviceId:deviceId(),source:"QR_PIN"})});setMessage(`${row.name}: καταχωρίστηκε ${value}`);await load()}catch(e){setError(e.message);await load()}finally{setBusy(false)}};
  if(!token)return <main className="inventory-mobile login"><form onSubmit={redeem}><Barcode size={42}/><h1>MyWorkStation Inventory</h1><p>Προσωρινή πρόσβαση μόνο στη συγκεκριμένη απογραφή και ζώνη.</p><label>PIN 6 ψηφίων<input inputMode="numeric" pattern="[0-9]{6}" maxLength="6" value={pin} onChange={e=>setPin(e.target.value.replace(/\D/g,""))} autoFocus required/></label>{error&&<div className="inv-error">{error}</div>}<button disabled={busy||pin.length!==6}><LogIn/> {busy?"Έλεγχος…":"Είσοδος στην απογραφή"}</button></form></main>;
  const counted=(data?.lines||[]).filter(x=>x.countedQuantity!==null).length,total=(data?.lines||[]).length;
  return <main className="inventory-mobile"><header><div><small>INVENTORY 2.0 · {data?.storeName}</small><h1>{data?.name||"Απογραφή"}</h1><p>{counted}/{total} μετρήθηκαν · {data?.liveDuringTrading?"LIVE με ανοικτό κατάστημα":"Κλειδωμένη περίοδος"}</p></div><span className={online?"online":"offline"}>{online?<Wifi/>:<WifiOff/>}{online?"Online":"Offline"}</span></header><section className="inv-progress"><i style={{width:`${total?counted/total*100:0}%`}}/></section><div className="inv-search"><Search/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Barcode, SKU ή προϊόν"/><button onClick={load}><RefreshCw/></button></div>{error&&<div className="inv-error">{error}</div>}{message&&<div className="inv-message">{message}</div>}<section className="inv-list">{rows.map(row=><article key={row.id} className={row.recountRequired?"recount":""}><div><b>{row.name}</b><small>{row.barcode||row.sku||"Χωρίς κωδικό"} · {row.zoneName||"Χωρίς ζώνη"}</small>{row.recountRequired&&<em>ΑΠΑΙΤΕΙΤΑΙ ΕΠΑΝΑΚΑΤΑΜΕΤΡΗΣΗ</em>}</div><label>Φυσικό<input type="number" min="0" step="0.001" defaultValue={row.countedQuantity??""} onBlur={e=>e.target.value!==""&&save(row,e.target.value)}/>{row.countedQuantity!==null&&<CheckCircle2/>}</label></article>)}</section>{busy&&<div className="inv-busy">Συγχρονισμός…</div>}</main>;
}
