import React,{useEffect,useState} from "react";
import {FileSpreadsheet,Plus,RefreshCw,Search,X} from "lucide-react";
import "./supplier-management.css";

const money=v=>Number(v||0).toLocaleString("el-GR",{style:"currency",currency:"EUR"});
const date=v=>v?new Date(v).toLocaleDateString("el-GR"):"—";
const readBase64=file=>new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(String(r.result||"").split(",").pop()||"");r.onerror=()=>reject(new Error("Δεν διαβάστηκε το αρχείο."));r.readAsDataURL(file)});

export default function BankPaymentImportPanel({api,fixedStore=null}){
  const [stores,setStores]=useState([]),[storeId,setStoreId]=useState(fixedStore?.id||""),[file,setFile]=useState(null),[data,setData]=useState(null),[busy,setBusy]=useState(false),[error,setError]=useState("");
  const [supplierDraft,setSupplierDraft]=useState(null),[supplierBusy,setSupplierBusy]=useState(false),[supplierError,setSupplierError]=useState("");
  useEffect(()=>{if(fixedStore?.id){setStoreId(fixedStore.id);return}api("/api/stores").then(rows=>{setStores(rows||[]);if(rows?.[0])setStoreId(rows[0].id)}).catch(e=>setError(e.message))},[fixedStore?.id]);
  const preview=async()=>{if(!file||!storeId)return;setBusy(true);setError("");setData(null);try{const dataBase64=await readBase64(file);setData(await api("/api/owner-payments/preview-bank",{method:"POST",body:JSON.stringify({storeId,filename:file.name,dataBase64})}))}catch(e){setError(e.message)}finally{setBusy(false)}};
  const openSupplier=row=>{setSupplierError("");setSupplierDraft({name:row.beneficiary||row.description||"",taxId:"",email:"",phone:"",address:"",city:"",iban:row.iban||""})};
  const createSupplier=async event=>{event.preventDefault();if(!supplierDraft?.name?.trim())return setSupplierError("Η επωνυμία είναι υποχρεωτική.");setSupplierBusy(true);setSupplierError("");try{await api("/api/commerce/suppliers",{method:"POST",body:JSON.stringify({name:supplierDraft.name.trim(),taxId:supplierDraft.taxId||null,email:supplierDraft.email||null,phone:supplierDraft.phone||null,address:supplierDraft.address||null,city:supplierDraft.city||null})});setSupplierDraft(null);await preview()}catch(e){setSupplierError(e.message)}finally{setSupplierBusy(false)}};
  return <section className="commerce-box" style={{marginTop:fixedStore?0:18}}>
    <div className="supplier-section-title"><div><h4><FileSpreadsheet/> Εισαγωγή αρχείου τράπεζας</h4><p style={{margin:"4px 0 0",color:"#64748b"}}>Excel / CSV → τραπεζική κίνηση → προτεινόμενος προμηθευτής → προτεινόμενο ανεξόφλητο τιμολόγιο. Προεπισκόπηση μόνο.</p></div>{data&&<button type="button" onClick={preview} disabled={busy}><RefreshCw/>Ανανέωση preview</button>}</div>
    <div className="commerce-form" style={{gridTemplateColumns:fixedStore?"1fr auto":"1fr 1fr auto",alignItems:"end"}}>
      {!fixedStore&&<label>Κατάστημα<select value={storeId} onChange={e=>setStoreId(e.target.value)}><option value="">Επιλογή</option>{stores.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label>}
      {fixedStore&&<div className="commerce-notice"><b>Κατάστημα:</b> {fixedStore.name}</div>}
      <label>Αρχείο Excel / CSV<input type="file" accept=".xlsx,.xls,.csv" onChange={e=>{setFile(e.target.files?.[0]||null);setData(null)}}/></label>
      <button type="button" onClick={preview} disabled={!file||!storeId||busy}><Search/>{busy?"Ανάγνωση…":"Προεπισκόπηση"}</button>
    </div>
    {error&&<div className="commerce-error">{error}</div>}
    {data&&<><div className="commerce-notice" style={{marginTop:10}}><b>{data.message}</b><br/>Βρέθηκαν {data.count} κινήσεις · {data.matched} πλήρεις προτάσεις · {data.pending} σε εκκρεμότητα.</div>
      <div className="supplier-table" style={{marginTop:10,overflowX:"auto"}}><div className="supplier-row head" style={{gridTemplateColumns:"120px 110px 220px 240px 170px 220px 130px"}}><span>Ημερομηνία</span><span>Ποσό</span><span>Δικαιούχος / Αιτιολογία</span><span>Προτεινόμενος προμηθευτής</span><span>Τιμολόγιο</span><span>Reference / IBAN</span><span>Κατάσταση</span></div>{data.rows.map((r,i)=><div className="supplier-row" key={`${r.reference}-${i}`} style={{gridTemplateColumns:"120px 110px 220px 240px 170px 220px 130px"}}><span>{date(r.date)}</span><b>{money(r.amount)}</b><span><b>{r.beneficiary||"—"}</b><small>{r.description||""}</small></span><span>{r.supplier?<><b>{r.supplier.name}</b><small>{r.supplier.reasons?.join(" + ")||"matching"}</small></>:<button type="button" onClick={()=>openSupplier(r)} style={{display:"inline-flex",alignItems:"center",gap:6,border:"1px solid #0f766e",background:"#ecfdf5",color:"#065f46",borderRadius:9,padding:"8px 10px",fontWeight:800,cursor:"pointer"}}><Plus size={15}/>Νέα εγγραφή προμηθευτή</button>}</span><span>{r.invoice?<><b>{r.invoice.documentNumber||"Χωρίς αριθμό"}</b><small>{money(r.invoice.totalGross)} · {date(r.invoice.documentDate)}</small></>:"—"}</span><span><b>{r.reference||"—"}</b><small>{r.iban||""}</small></span><span className={r.status==="MATCHED"?"pill":""}>{r.status==="MATCHED"?"ΠΡΟΤΑΣΗ":"ΕΚΚΡΕΜΟΤΗΤΑ"}</span></div>)}</div>
      <div className="commerce-notice">Δεν έχει γίνει καμία τελική καταχώριση. Η επιβεβαίωση πληρωμής θα ενεργοποιηθεί μόνο μετά το πραγματικό test του preview.</div></>}
    {supplierDraft&&<div onMouseDown={e=>e.target===e.currentTarget&&!supplierBusy&&setSupplierDraft(null)} style={{position:"fixed",inset:0,zIndex:6200,background:"rgba(10,24,43,.52)",display:"grid",placeItems:"center",padding:20}}><form onSubmit={createSupplier} style={{width:"min(620px,96vw)",background:"white",borderRadius:18,boxShadow:"0 24px 80px rgba(0,0,0,.25)",overflow:"hidden"}}><header style={{padding:"16px 18px",display:"flex",justifyContent:"space-between",alignItems:"center",background:"#123b5d",color:"white"}}><div><b>Νέα εγγραφή προμηθευτή</b><small style={{display:"block",opacity:.82,marginTop:3}}>Η τραπεζική κίνηση παραμένει ανοιχτή και μετά την αποθήκευση γίνεται νέο matching.</small></div><button type="button" onClick={()=>!supplierBusy&&setSupplierDraft(null)} style={{border:0,background:"transparent",color:"white",cursor:"pointer"}}><X/></button></header><div style={{padding:18,display:"grid",gridTemplateColumns:"1fr 1fr",gap:12}}><label style={{gridColumn:"1/-1"}}>Επωνυμία<input required value={supplierDraft.name} onChange={e=>setSupplierDraft({...supplierDraft,name:e.target.value})}/></label><label>ΑΦΜ<input value={supplierDraft.taxId} onChange={e=>setSupplierDraft({...supplierDraft,taxId:e.target.value})}/></label><label>IBAN από κίνηση<input value={supplierDraft.iban} readOnly title="Χρησιμοποιείται ως στοιχείο της τρέχουσας τραπεζικής κίνησης. Η βασική καρτέλα Supplier δεν αποθηκεύει ακόμη IBAN."/></label><label>Email<input type="email" value={supplierDraft.email} onChange={e=>setSupplierDraft({...supplierDraft,email:e.target.value})}/></label><label>Τηλέφωνο<input value={supplierDraft.phone} onChange={e=>setSupplierDraft({...supplierDraft,phone:e.target.value})}/></label><label>Διεύθυνση<input value={supplierDraft.address} onChange={e=>setSupplierDraft({...supplierDraft,address:e.target.value})}/></label><label>Πόλη<input value={supplierDraft.city} onChange={e=>setSupplierDraft({...supplierDraft,city:e.target.value})}/></label>{supplierError&&<div className="commerce-error" style={{gridColumn:"1/-1"}}>{supplierError}</div>}</div><footer style={{padding:"12px 18px",display:"flex",justifyContent:"flex-end",gap:10,borderTop:"1px solid #e2e8f0"}}><button type="button" onClick={()=>!supplierBusy&&setSupplierDraft(null)}>Άκυρο</button><button disabled={supplierBusy}>{supplierBusy?"Αποθήκευση…":"Αποθήκευση & νέο matching"}</button></footer></form></div>}
  </section>;
}
