import React,{useEffect,useMemo,useRef,useState} from "react";
import {LogOut,RefreshCw,ShoppingCart,WalletCards} from "lucide-react";
import "./commerce-hub.css";
import "./pos-customer.css";
import NetlinkPosPanel from "./NetlinkPosPanel";
import "./netlink-button.css";

const money=value=>Number(value||0).toLocaleString("el-GR",{style:"currency",currency:"EUR"});
const num=value=>Number(String(value??0).replace(",","."))||0;
const normalizeProductKey=value=>String(value??"").normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLocaleUpperCase("el-GR").replace(/[^A-ZΑ-Ω0-9]/g,"");
const fallbackLayout={title:"OPERATOR POS",productColumns:6,showSku:true,theme:{headerColor:"#033d2f",accentColor:"#087a52",surfaceColor:"#ffffff"},quickKeys:[],categories:[],buttons:[{id:"cash",label:"ΜΕΤΡΗΤΑ",action:"CASH",color:"#078a4d",visible:true},{id:"card",label:"ΚΑΡΤΑ",action:"CARD",color:"#3979cc",visible:true}]};
const parseStored=key=>{try{return JSON.parse(localStorage.getItem(key)||"null")}catch{return null}};
const priceBadge=source=>source==="WHOLESALE"?"Χονδρική":source==="LEAFLET"?"Φυλλάδιο":source==="GIFT"?"Δώρο":"";

export default function CommercialPosApp({api,storeId}){
  const [session,setSession]=useState(()=>{const s=parseStored("storeOperatorSession"),u=parseStored("user");return u?.operator===true&&s?.store?.id===storeId?s:null});
  const [directory,setDirectory]=useState(null),[employeeId,setEmployeeId]=useState(""),[pin,setPin]=useState("");
  const [layout,setLayout]=useState(fallbackLayout),[products,setProducts]=useState([]),[category,setCategory]=useState(""),[cart,setCart]=useState([]);
  const [cashOverview,setCashOverview]=useState(null),[opening,setOpening]=useState({drawer:"",custody:"",coins:"",safe:""});
  const [query,setQuery]=useState(""),[selectedId,setSelectedId]=useState(null),[amountInput,setAmountInput]=useState("");
  const [paymentPanel,setPaymentPanel]=useState(false),[mixed,setMixed]=useState({cash:"",card:"",iris:""}),[holds,setHolds]=useState([]);
  // POS_EMPLOYEE_TRANSFER_AMOUNT_V1
  const [transferPanel,setTransferPanel]=useState(false),[transferForm,setTransferForm]=useState({amount:"",description:"Μεταφορά ποσού",recipient:"Υπεύθυνος βάρδιας"}),[posAccess,setPosAccess]=useState({});
  const [netlinkPanel,setNetlinkPanel]=useState(false),[netlinkAvailable,setNetlinkAvailable]=useState(false);
  const [customer,setCustomer]=useState(null),[customerPanel,setCustomerPanel]=useState(false),[customerQuery,setCustomerQuery]=useState(""),[customerResults,setCustomerResults]=useState([]),[customerBusy,setCustomerBusy]=useState(false),[wholesalePrices,setWholesalePrices]=useState({});
  const [quote,setQuote]=useState({signature:"",items:[],subtotal:0,discount:0,total:0}),[quoteBusy,setQuoteBusy]=useState(false);
  const quoteSeq=useRef(0);
  const [loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState(""),[message,setMessage]=useState("");

  const loadDirectory=async()=>{setLoading(true);setError("");try{const d=await api(`/api/operators/stores/${storeId}/directory`);setDirectory(d);const first=d.operators?.find(x=>x.hasPin);if(first)setEmployeeId(first.employeeId)}catch(e){setError(e.message)}finally{setLoading(false)}};
  useEffect(()=>{if(!session)loadDirectory()},[storeId,session]);

  const login=async e=>{e.preventDefault();setBusy(true);setError("");try{const currentUser=parseStored("user");if(currentUser&&!currentUser.operator&&localStorage.getItem("token"))localStorage.setItem("posReturnAuth",JSON.stringify({token:localStorage.getItem("token"),user:currentUser}));const r=await api("/api/operators/login/pin",{method:"POST",body:JSON.stringify({storeId,employeeId,pin})});const next={user:r.user,store:r.store,company:r.company};localStorage.setItem("token",r.token);localStorage.setItem("storeOperatorSession",JSON.stringify(next));localStorage.setItem("user",JSON.stringify(r.user));setSession(next);setPin("")}catch(err){setError(err.message)}finally{setBusy(false)}};
  const logout=async()=>{try{await api("/api/operators/logout",{method:"POST"})}catch{}finally{localStorage.removeItem("storeOperatorSession");const back=parseStored("posReturnAuth");if(back?.token){localStorage.setItem("token",back.token);localStorage.setItem("user",JSON.stringify(back.user||{}))}else{localStorage.removeItem("token");localStorage.removeItem("user")}localStorage.removeItem("posReturnAuth");window.location.assign("/platform-admin")}};

  const loadHolds=async()=>{try{const h=await api(`/api/store-pos/stores/${encodeURIComponent(storeId)}/holds`);setHolds(h.rows||[])}catch{setHolds([])}};
  const loadPos=async()=>{if(!session)return;setLoading(true);setError("");try{const cash=await api(`/api/cash-control/stores/${storeId}/overview`);setCashOverview(cash);if(!cash.openSession){const s=cash.suggestedOpening||{};setOpening({drawer:String(s.drawer||""),custody:String(s.custody||""),coins:String(s.coins||""),safe:String(s.safe||"")});setProducts([]);setHolds([]);return}const [result,h]=await Promise.all([api(`/api/store-pos/stores/${encodeURIComponent(storeId)}`),api(`/api/store-pos/stores/${encodeURIComponent(storeId)}/holds`).catch(()=>({rows:[]}))]);const next=result.layout||{};setLayout({...fallbackLayout,...next,theme:{...fallbackLayout.theme,...(next.theme||{})},quickKeys:next.quickKeys||[],categories:next.categories||[],buttons:next.buttons||fallbackLayout.buttons});setProducts(result.products||[]);setHolds(h.rows||[]);setPosAccess(result.access||{});setCategory("")}catch(e){setError(e.message)}finally{setLoading(false)}};
  useEffect(()=>{if(session)loadPos()},[session,storeId]);
  useEffect(()=>{if(!session){setNetlinkAvailable(false);return}api("/api/netlink/status").then(()=>setNetlinkAvailable(true)).catch(()=>setNetlinkAvailable(false))},[session,storeId]);

  const openCash=async e=>{e.preventDefault();setBusy(true);setError("");try{await api(`/api/cash-control/stores/${storeId}/sessions/open`,{method:"POST",body:JSON.stringify({shiftLabel:"Βάρδια POS",drawer:num(opening.drawer),custody:num(opening.custody),coins:num(opening.coins),safe:num(opening.safe)})});setMessage("Το ταμείο άνοιξε. Το POS είναι έτοιμο.");await loadPos()}catch(err){setError(err.message)}finally{setBusy(false)}};

  const effectiveProductPrice=product=>Number(wholesalePrices[product.id]??product.salePrice??0);
  const add=product=>{const basePrice=Number(product.salePrice||0),price=effectiveProductPrice(product),priceSource=wholesalePrices[product.id]!==undefined?"WHOLESALE":"RETAIL";setSelectedId(product.id);setCart(rows=>{const found=rows.find(x=>x.id===product.id);return found?rows.map(x=>x.id===product.id?{...x,qty:x.qty+1}:x):[...rows,{id:product.id,name:product.name,sku:product.sku,qty:1,basePrice,price,priceSource,stock:Number(product.currentStock||0)}]})};
  const changeQty=(id,delta)=>setCart(rows=>rows.map(x=>x.id===id?{...x,qty:Math.max(0,x.qty+delta)}:x).filter(x=>x.qty>0));
  const setSelectedQty=()=>{if(!selectedId)return;const q=Math.max(1,Math.floor(num(amountInput)));setCart(rows=>rows.map(x=>x.id===selectedId?{...x,qty:q}:x));setAmountInput("")};
  const deleteSelected=()=>{if(!selectedId)return;setCart(rows=>rows.filter(x=>x.id!==selectedId));setSelectedId(null)};
  const quoteSignature=useMemo(()=>`${customer?.id||""}|${cart.map(x=>`${x.id}:${x.qty}`).join("|")}`,[cart,customer?.id]);
  useEffect(()=>{
    if(!cart.length){quoteSeq.current++;setQuote({signature:quoteSignature,items:[],subtotal:0,discount:0,total:0});setQuoteBusy(false);return}
    const seq=++quoteSeq.current,signature=quoteSignature;setQuoteBusy(true);
    api(`/api/store-pos/stores/${encodeURIComponent(storeId)}/quote`,{method:"POST",body:JSON.stringify({items:cart.map(x=>({productId:x.id,quantity:x.qty})),customerId:customer?.id||null})})
      .then(result=>{if(seq!==quoteSeq.current)return;setQuote({...result,signature})})
      .catch(err=>{if(seq!==quoteSeq.current)return;setError(err.message)})
      .finally(()=>{if(seq===quoteSeq.current)setQuoteBusy(false)});
  },[quoteSignature,storeId]);
  const quoteCurrent=quote.signature===quoteSignature,quotedById=useMemo(()=>new Map((quoteCurrent?quote.items:[]).map(item=>[item.productId,item])),[quote,quoteCurrent]);
  const fallbackTotal=cart.reduce((sum,x)=>sum+x.qty*x.price,0),total=quoteCurrent?Number(quote.total||0):fallbackTotal,discount=quoteCurrent?Number(quote.discount||0):0,received=num(amountInput),change=Math.max(0,received-total);
  const visible=useMemo(()=>category?products.filter(x=>String(x.categoryName||"").toLocaleLowerCase("el-GR")===category.toLocaleLowerCase("el-GR")):products,[products,category]);
  const findProduct=text=>{
    const raw=String(text||"").trim(),key=normalizeProductKey(raw);if(!key)return null;
    return products.find(x=>(x.barcodes||[]).some(b=>String(b).trim()===raw))||products.find(x=>normalizeProductKey(x.sku)===key)||products.find(x=>normalizeProductKey(x.name)===key)||products.find(x=>(x.barcodes||[]).some(b=>normalizeProductKey(b)===key))||products.find(x=>normalizeProductKey(x.name).includes(key)||key.includes(normalizeProductKey(x.name)));
  };
  const searchProduct=e=>{e?.preventDefault();const p=findProduct(query);if(p){setError("");add(p);setQuery("")}else setError(`Δεν βρέθηκε προϊόν για «${query}».`)};
  const quick=q=>{const p=findProduct(q);if(p){setError("");add(p)}else setError(`Δεν βρέθηκε προϊόν για «${q}».`)};
  const keypad=v=>{if(v==="⌫")return setAmountInput(x=>x.slice(0,-1));setAmountInput(x=>`${x}${v===","?".":v}`)};

  const searchCustomers=async e=>{e?.preventDefault();const q=customerQuery.trim();if(q.length<2){setCustomerResults([]);return setError("Γράψε τουλάχιστον 2 χαρακτήρες για αναζήτηση πελάτη.")}setCustomerBusy(true);setError("");try{const r=await api(`/api/store-pos/stores/${encodeURIComponent(storeId)}/customers?q=${encodeURIComponent(q)}`);setCustomerResults(r.items||[])}catch(err){setError(err.message)}finally{setCustomerBusy(false)}};
  const applyCustomerPricing=async(value,sourceRows=null)=>{setCustomerBusy(true);setError("");try{let map={};if(value?.id){const r=await api(`/api/store-pos/stores/${encodeURIComponent(storeId)}/customers/${encodeURIComponent(value.id)}/prices`);map=Object.fromEntries((r.items||[]).map(item=>[item.productId,Number(item.wholesalePrice||0)]))}setWholesalePrices(map);const reprice=rows=>rows.map(row=>{const basePrice=Number(row.basePrice??row.retailPrice??row.price??0),hasWholesale=map[row.id]!==undefined;return {...row,basePrice,price:hasWholesale?Number(map[row.id]):basePrice,priceSource:hasWholesale?"WHOLESALE":"RETAIL"}});if(sourceRows)setCart(reprice(sourceRows));else setCart(reprice);setCustomer(value);setCustomerPanel(false);setCustomerQuery("");setCustomerResults([])}catch(err){setError(err.message)}finally{setCustomerBusy(false)}};
  const chooseCustomer=value=>applyCustomerPricing(value);

  const pay=async(method,payments)=>{if(!cart.length||quoteBusy)return;setBusy(true);setError("");setMessage("");try{const body={items:cart.map(x=>({productId:x.id,quantity:x.qty})),paymentMethod:method,customerId:customer?.id||null};if(payments)body.payments=payments;const r=await api(`/api/store-pos/stores/${encodeURIComponent(storeId)}/checkout`,{method:"POST",body:JSON.stringify(body)});setCart([]);setSelectedId(null);setCustomer(null);setWholesalePrices({});setAmountInput("");setPaymentPanel(false);setMixed({cash:"",card:"",iris:""});setMessage(`Δοκιμαστική πώληση ${money(r.total)}${r.customer?.name?` · ${r.customer.name}`:""}${r.wholesaleLines?` · ${r.wholesaleLines} χονδρική${r.wholesaleLines===1?"":"ές"} γραμμή${r.wholesaleLines===1?"":"ές"}`:""}${r.promotionLines?` · ${r.promotionLines} προσφορά${r.promotionLines===1?"":"ές"}`:""} καταγράφηκε ως ΜΗ ΦΟΡΟΛΟΓΙΚΗ.`);await loadPos()}catch(e){setError(e.message)}finally{setBusy(false)}};
  const payMixed=()=>{if(quoteBusy)return setError("Περίμενε να ολοκληρωθεί η τιμολόγηση του καλαθιού.");const payments=[["CASH",mixed.cash],["CARD",mixed.card],["IRIS",mixed.iris]].map(([method,amount])=>({method,amount:num(amount)})).filter(x=>x.amount>0);const sum=payments.reduce((s,x)=>s+x.amount,0);if(Math.abs(sum-total)>.009)return setError(`Η μικτή πληρωμή πρέπει να είναι ακριβώς ${money(total)}.`);pay("MIXED",payments)};
  const hold=async()=>{if(!cart.length||quoteBusy)return;setBusy(true);setError("");try{const r=await api(`/api/store-pos/stores/${encodeURIComponent(storeId)}/holds`,{method:"POST",body:JSON.stringify({items:cart.map(x=>({productId:x.id,quantity:x.qty})),customerId:customer?.id||null})});setCart([]);setSelectedId(null);setCustomer(null);setWholesalePrices({});setAmountInput("");setMessage(`Η συναλλαγή ${money(r.total)}${r.customer?.name?` · ${r.customer.name}`:""} μπήκε σε μόνιμη αναμονή.`);await loadHolds()}catch(e){setError(e.message)}finally{setBusy(false)}};
  const restoreHold=async()=>{const h=holds[0];if(!h)return setMessage("Δεν υπάρχει συναλλαγή σε αναμονή.");setBusy(true);setError("");try{const r=await api(`/api/store-pos/stores/${encodeURIComponent(storeId)}/holds/${encodeURIComponent(h.id)}/restore`,{method:"POST",body:"{}"});const rows=(r.items||[]).map(item=>({id:item.productId||item.id,name:item.name,sku:item.sku,qty:Number(item.quantity||item.qty||1),basePrice:Number(item.retailPrice??item.unitPrice??item.price??0),price:Number(item.effectiveUnitPrice??item.unitPrice??item.price??0),priceSource:item.priceSource||"RETAIL",stock:Number(item.stock||0)}));await applyCustomerPricing(r.customer||null,rows);setSelectedId(null);setMessage(`Επανήλθε συναλλαγή αναμονής ${money(r.total)}${r.customer?.name?` · ${r.customer.name}`:""}. Οι ενεργές τιμές θα επανελεγχθούν τώρα.`);await loadHolds()}catch(e){setError(e.message)}finally{setBusy(false)}};
  const submitTransferAmount=async e=>{
    e.preventDefault();
    const amount=num(transferForm.amount);
    if(amount<=0)return setError("Βάλε ποσό μεγαλύτερο από 0 για τη μεταφορά.");
    if(!cashOverview?.openSession)return setError("Δεν υπάρχει ενεργή βάρδια για μεταφορά ποσού.");
    setBusy(true);setError("");setMessage("");
    try{
      await api(`/api/transactions/stores/${encodeURIComponent(storeId)}`,{method:"POST",body:JSON.stringify({type:"TRANSFER_AMOUNT",amount,description:`Παραλήπτης: ${transferForm.recipient} • ${transferForm.description||"Μεταφορά ποσού"}`,subtractFromShift:false})});
      setMessage(`Μεταφορά ποσού ${money(amount)} καταχωρίστηκε στη βάρδια και στο BackOffice.`);
      setTransferPanel(false);setTransferForm({amount:"",description:"Μεταφορά ποσού",recipient:"Υπεύθυνος βάρδιας"});
      await loadPos();
    }catch(err){setError(err.message)}finally{setBusy(false)}
  };
  const action=a=>{if(a==="CASH")return pay("CASH");if(a==="CARD")return pay("CARD");if(a==="IRIS")return pay("IRIS");if(a==="MIXED")return setPaymentPanel(true);if(a==="PAYMENTS")return setPaymentPanel(v=>!v);if(a==="TRANSFER_AMOUNT")return setTransferPanel(true);if(a==="HOLD")return hold();if(a==="CLEAR_CART"){setCart([]);setSelectedId(null);setCustomer(null);setWholesalePrices({});return}setMessage(`Η ενέργεια ${a} είναι καταγεγραμμένη στο TEST POS και θα συνδεθεί με το αντίστοιχο workflow.`)};

  if(!session)return <div className="operator-login-shell"><div className="operator-login-main"><div className="operator-login-card"><div className="operator-login-icon"><ShoppingCart/></div><h2>TEST — POS</h2><p>Είσοδος πωλητή με προσωπικό PIN.</p>{error&&<div className="operator-login-error">{error}</div>}{loading?<div className="operator-login-loading">Φόρτωση…</div>:<form onSubmit={login}><label>Πωλητής<select value={employeeId} onChange={e=>setEmployeeId(e.target.value)}>{(directory?.operators||[]).filter(x=>x.hasPin).map(x=><option key={x.employeeId} value={x.employeeId}>{x.displayName}</option>)}</select></label><label>PIN<input type="password" inputMode="numeric" maxLength="8" value={pin} onChange={e=>setPin(e.target.value.replace(/\D/g,""))} required/></label><button disabled={busy||pin.length<4}>{busy?"Έλεγχος…":"Είσοδος στο POS"}</button></form>}</div></div></div>;
  if(cashOverview&&!cashOverview.openSession)return <div className="operator-login-shell"><div className="operator-login-main"><div className="operator-login-card" style={{maxWidth:620}}><div className="operator-login-icon"><WalletCards/></div><h2>Άνοιγμα Ταμείου</h2><p>Πριν εμφανιστεί το POS ανοίγεις πρώτα τη βάρδια.</p>{error&&<div className="operator-login-error">{error}</div>}<form onSubmit={openCash}><label>Συρτάρι<input inputMode="decimal" value={opening.drawer} onChange={e=>setOpening(v=>({...v,drawer:e.target.value}))} placeholder="0,00"/></label><label>Φύλαξη<input inputMode="decimal" value={opening.custody} onChange={e=>setOpening(v=>({...v,custody:e.target.value}))} placeholder="0,00"/></label><label>Κέρματα<input inputMode="decimal" value={opening.coins} onChange={e=>setOpening(v=>({...v,coins:e.target.value}))} placeholder="0,00"/></label><label>Χρηματοκιβώτιο<input inputMode="decimal" value={opening.safe} onChange={e=>setOpening(v=>({...v,safe:e.target.value}))} placeholder="0,00"/></label><button disabled={busy}>{busy?"Άνοιγμα…":"Άνοιγμα Ταμείου & POS"}</button></form><button onClick={logout} style={{marginTop:10}}>Έξοδος</button></div></div></div>;

  return <div className="commercial-pos-runtime" style={{minHeight:"100vh",background:"#eef3f2",padding:12}}><div className="kat-pos-topbar"><div><b>MyWorkStation · {session.store?.name}</b><small>TEST POS · ΜΗ ΦΟΡΟΛΟΓΙΚΟ · Αναμονές: {holds.length}</small></div><div>{netlinkAvailable&&<button className="store-pos-netlink" onClick={()=>setNetlinkPanel(true)}>NETLINK</button>}<button onClick={loadPos}><RefreshCw/> Ανανέωση</button><button onClick={logout}><LogOut/> Έξοδος</button></div></div>{error&&<div className="commerce-error">{error}</div>}{message&&<div className="commerce-success">{message}</div>}
    <div className="store-operator-pos kat-test-real-pos" style={{"--store-pos-head":layout.theme?.headerColor||"#033d2f","--store-pos-accent":layout.theme?.accentColor||"#087a52","--store-pos-surface":layout.theme?.surfaceColor||"#ffffff"}}>
      <header><div className="store-pos-logo">MW</div><div className="store-pos-brand"><small>MyWorkStation · TEST</small><b>{layout.title||"OPERATOR POS"}</b></div><form className="store-pos-search" onSubmit={searchProduct}><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Barcode ή αναζήτηση προϊόντος" autoFocus/><button>Αναζήτηση</button></form><div className="store-pos-user"><b>{session.user?.fullName}</b><small>Ταμείο ανοικτό</small></div></header>
      <aside className="store-pos-quick"><div><b>ΓΡΗΓΟΡΑ</b><small>{layout.quickKeys.filter(x=>x.visible).length} θέσεις</small></div>{layout.quickKeys.filter(x=>x.visible).slice(0,24).map((b,i)=><button key={b.id} style={{background:b.color}} onClick={()=>quick(b.productQuery||b.label)}><i>{i+1}</i>{b.label}</button>)}</aside>
      <main className="store-pos-main"><div className="store-pos-table-head"><span>ΠΟΣ.</span><span>ΕΙΔΟΣ</span><span>STOCK</span><span>ΤΙΜΗ</span><span>ΣΥΝΟΛΟ</span></div><div className="store-pos-sale-lines">{cart.length?cart.map(line=>{const quoted=quotedById.get(line.id),source=quoted?.priceSource||line.priceSource,unitPrice=Number(quoted?.effectiveUnitPrice??line.price),lineTotal=Number(quoted?.lineTotal??line.qty*unitPrice),badge=priceBadge(source);return <article className={selectedId===line.id?"selected":""} key={line.id} onClick={()=>setSelectedId(line.id)}><span><button onClick={e=>{e.stopPropagation();changeQty(line.id,-1)}}>−</button> {line.qty} <button onClick={e=>{e.stopPropagation();changeQty(line.id,1)}}>+</button></span><b>{line.name}{badge&&<small className={`pos-price-badge ${source.toLowerCase()}`}>{badge}</small>}</b><span>{line.stock}</span><span className={source!=="RETAIL"?"pos-special-price":""}>{money(unitPrice)}</span><strong>{money(lineTotal)}</strong></article>}):<div className="store-pos-empty"><b>Νέα συναλλαγή</b><span>Πάτησε προϊόν ή σκάναρε barcode</span></div>}</div><div className="store-pos-category-title"><b>ΚΑΤΗΓΟΡΙΕΣ</b><button className={!category?"active":""} onClick={()=>setCategory("")}>ΑΡΧΙΚΗ</button><span>{category||"ΒΑΣΙΚΗ ΟΘΟΝΗ"}</span></div><div className="store-pos-categories" style={{gridTemplateColumns:`repeat(${layout.productColumns||6},minmax(0,1fr))`}}>{layout.categories.filter(x=>x.visible).map((b,i)=><button className={category===(b.categoryName||b.label)?"active":""} key={b.id} style={{background:b.color}} onClick={()=>setCategory(b.categoryName||b.label)}><i>{i+1}</i>{b.label}</button>)}</div><div className="store-pos-products" style={{gridTemplateColumns:`repeat(${layout.productColumns||6},minmax(0,1fr))`}}>{visible.map(p=><button key={p.id} onClick={()=>add(p)}><b>{p.name}</b>{layout.showSku&&<small>{p.sku||p.categoryName||""}</small>}{wholesalePrices[p.id]!==undefined&&<small className="pos-price-badge wholesale">Χονδρική</small>}<strong>{money(effectiveProductPrice(p))}</strong></button>)}</div></main>
      <aside className="store-pos-right"><button className="store-pos-customer-button" onClick={()=>setCustomerPanel(true)}><small>ΠΕΛΑΤΗΣ</small><b>{customer?.name||"Χωρίς πελάτη"}</b>{customer?.taxId&&<span>ΑΦΜ {customer.taxId}</span>}{customer&&Object.keys(wholesalePrices).length>0&&<span>Ειδικές χονδρικές: {Object.keys(wholesalePrices).length}</span>}</button><div className="store-pos-money"><span>ΕΛΑΒΑ<b>{money(received)}</b></span><span>ΡΕΣΤΑ<b>{money(change)}</b></span></div><div className="store-pos-keypad">{[7,8,9,4,5,6,1,2,3,0,",","⌫"].map(v=><button key={v} onClick={()=>keypad(v)}>{v}</button>)}</div><button className="store-pos-clear" onClick={()=>setAmountInput("")}>ΚΑΘΑΡΙΣΜΟΣ ΠΟΣΟΥ</button><div className="store-pos-cart-tools"><button disabled={!selectedId} onClick={setSelectedQty}>ΠΟΣ.</button><button disabled={quoteBusy} onClick={restoreHold}>ΑΝΑΜΟΝΗ {holds.length?`(${holds.length})`:""}</button><button disabled={!selectedId} onClick={deleteSelected}>ΣΒΗΣΙΜΟ</button></div></aside>
      <footer>{layout.buttons.filter(b=>b.visible).map(b=><button key={b.id} style={{background:b.color,color:String(b.color).toLowerCase()==="#ffffff"?"#173f34":"#fff"}} onClick={()=>action(b.action)} disabled={busy||quoteBusy||(["CASH","CARD","IRIS","MIXED"].includes(b.action)&&!cart.length)}>{b.label}</button>)}{posAccess?.transferAmount&& !layout.buttons.some(b=>b.visible&&b.action==="TRANSFER_AMOUNT")&&<button style={{background:"#b7791f",color:"#fff"}} onClick={()=>setTransferPanel(true)} disabled={busy}>ΜΕΤΑΦΟΡΑ ΠΟΣΟΥ</button>}<div className="store-pos-total">{discount>0&&<small>Έκπτωση {money(discount)}</small>}<span>{quoteBusy?"ΤΙΜΟΛΟΓΗΣΗ…":"ΣΥΝΟΛΟ"}</span><b>{money(total)}</b></div></footer>
    </div>
    {netlinkPanel&&<NetlinkPosPanel api={api} storeId={storeId} onClose={()=>setNetlinkPanel(false)}/>}
    {transferPanel&&<div className="pos-payment-panel"><form onSubmit={submitTransferAmount}><h3>Μεταφορά ποσού</h3><p>Η κίνηση θα καταγραφεί στον χειριστή, στη βάρδια και στο BackOffice. Δεν καταχωρίζεται ως έξοδο.</p><label>Ποσό<input autoFocus inputMode="decimal" value={transferForm.amount} onChange={e=>setTransferForm(v=>({...v,amount:e.target.value}))} placeholder="0,00"/></label><label>Παραλήπτης<select value={transferForm.recipient} onChange={e=>setTransferForm(v=>({...v,recipient:e.target.value}))}><option>Υπεύθυνος βάρδιας</option><option>Ιδιοκτήτης</option><option>Άλλος ενεργός εργαζόμενος</option></select></label><label>Αιτιολογία<input value={transferForm.description} onChange={e=>setTransferForm(v=>({...v,description:e.target.value}))}/></label><button disabled={busy}>{busy?"Καταχώριση…":"ΚΑΤΑΧΩΡΙΣΗ ΜΕΤΑΦΟΡΑΣ"}</button><button type="button" className="secondary" onClick={()=>setTransferPanel(false)} disabled={busy}>ΚΛΕΙΣΙΜΟ</button></form></div>}
    {paymentPanel&&<div className="pos-payment-panel"><div><h3>Πληρωμές</h3><p>Σύνολο: <b>{money(total)}</b>{discount>0&&<small className="pos-quote-discount"> · Έκπτωση {money(discount)}</small>}</p><button disabled={quoteBusy} onClick={()=>pay("CASH")}>ΜΕΤΡΗΤΑ</button><button disabled={quoteBusy} onClick={()=>pay("CARD")}>ΚΑΡΤΑ</button><button disabled={quoteBusy} onClick={()=>pay("IRIS")}>IRIS</button><div className="mixed-grid"><label>Μετρητά<input value={mixed.cash} onChange={e=>setMixed(v=>({...v,cash:e.target.value}))}/></label><label>Κάρτα<input value={mixed.card} onChange={e=>setMixed(v=>({...v,card:e.target.value}))}/></label><label>IRIS<input value={mixed.iris} onChange={e=>setMixed(v=>({...v,iris:e.target.value}))}/></label></div><button disabled={quoteBusy} onClick={payMixed}>ΟΛΟΚΛΗΡΩΣΗ ΜΙΚΤΗΣ</button><button className="secondary" onClick={()=>setPaymentPanel(false)}>ΚΛΕΙΣΙΜΟ</button></div></div>}
    {customerPanel&&<div className="pos-customer-panel"><section><header><div><small>ΠΕΛΑΤΗΣ ΣΥΝΑΛΛΑΓΗΣ</small><h3>Αναζήτηση πελάτη</h3></div><button onClick={()=>setCustomerPanel(false)}>✕</button></header><form onSubmit={searchCustomers}><input autoFocus value={customerQuery} onChange={e=>setCustomerQuery(e.target.value)} placeholder="Όνομα, ΑΦΜ, τηλέφωνο ή email"/><button disabled={customerBusy}>{customerBusy?"Αναζήτηση…":"Αναζήτηση"}</button></form><button className="pos-customer-none" disabled={customerBusy} onClick={()=>chooseCustomer(null)}>Χωρίς πελάτη</button><div className="pos-customer-results">{customerResults.map(item=><button key={item.id} disabled={customerBusy} onClick={()=>chooseCustomer(item)}><b>{item.name}</b><span>{[item.taxId&&`ΑΦΜ ${item.taxId}`,item.phone,item.email].filter(Boolean).join(" · ")||"Χωρίς επιπλέον στοιχεία"}</span><small>Υπόλοιπο: {money(item.balance)}{item.hasMemberCard?" · Κάρτα loyalty":""}</small></button>)}{customerQuery.trim().length>=2&&!customerBusy&&!customerResults.length&&<div className="pos-customer-empty">Δεν βρέθηκαν ενεργοί πελάτες.</div>}</div></section></div>}
  </div>;
}
