const euro=text=>{const raw=String(text||"").replace(/[^0-9,.-]/g,"").replace(/\./g,"").replace(",",".");const n=Number(raw);return Number.isFinite(n)?n:0};
const eur=n=>Number(n||0).toLocaleString("el-GR",{style:"currency",currency:"EUR"});
const rows=()=>[...document.querySelectorAll('.shift-table .shift-row:not(.head)')];
const extract=()=>rows().map(row=>{const c=[...row.children];const when=c[0]?.querySelector('small')?.textContent?.trim()||'';return{date:when.slice(0,10)||'—',cash:euro(c[2]?.textContent),card:euro(c[3]?.querySelector('b')?.textContent||c[3]?.textContent),total:euro(c[4]?.textContent),average:euro(c[7]?.textContent)}});
const panel=()=>{let el=document.querySelector('.mws-analytics-tab-content');if(!el){el=document.createElement('section');el.className='mws-analytics-tab-content';const anchor=document.querySelector('.shift-panel');anchor?.parentNode?.insertBefore(el,anchor)}return el};
const toggleMain=show=>{document.querySelectorAll('.shift-panel,.kiosk-lower-grid').forEach(el=>el.style.display=show?'':'none');const p=document.querySelector('.mws-analytics-tab-content');if(p)p.style.display=show?'none':''};
const indicators=data=>{const total=data.reduce((s,r)=>s+r.total,0),cash=data.reduce((s,r)=>s+r.cash,0),card=data.reduce((s,r)=>s+r.card,0),avg=data.length?data.reduce((s,r)=>s+r.average,0)/data.length:0;return `<h3>Δείκτες απόδοσης</h3><div class="mws-metric-grid"><div class="mws-metric-card"><span>Συνολικός τζίρος βαρδιών</span><strong>${eur(total)}</strong><em>${data.length} καταγεγραμμένες βάρδιες</em></div><div class="mws-metric-card"><span>Μετρητά</span><strong>${eur(cash)}</strong><em>Πραγματικές καταγραφές MyWorkStation</em></div><div class="mws-metric-card"><span>Κάρτες / IRIS / POS</span><strong>${eur(card)}</strong><em>Πραγματικές καταγραφές MyWorkStation</em></div><div class="mws-metric-card"><span>Μέσος όρος πώλησης</span><strong>${eur(avg)}</strong><em>Μέσος όρος των εμφανιζόμενων βαρδιών</em></div></div>`};
const daily=data=>{const map=new Map();data.forEach(r=>{const x=map.get(r.date)||{count:0,total:0};x.count++;x.total+=r.total;map.set(r.date,x)});const body=[...map].map(([date,x])=>`<div class="mws-day-row"><span>${date}</span><span>${x.count}</span><strong>${eur(x.total)}</strong></div>`).join('');return `<h3>Απόδοση ανά ημέρα</h3><div class="mws-day-table"><div class="mws-day-row head"><span>Ημερομηνία</span><span>Βάρδιες</span><span>Τζίρος</span></div>${body||'<div class="mws-empty-state"><b>Δεν υπάρχουν δεδομένα</b>Δεν έχουν καταγραφεί ακόμη βάρδιες για ημερήσια ανάλυση.</div>'}</div>`};
const passages=()=>`<h3>Διελεύσεις πελατών</h3><div class="mws-empty-state"><b>Δεν υπάρχουν ακόμη πραγματικές καταγραφές διελεύσεων.</b>Η ενότητα θα εμφανίζει μόνο δεδομένα που καταγράφονται πραγματικά από το MyWorkStation ή από μελλοντική συνδεδεμένη πηγή. Δεν δημιουργούνται εικονικοί αριθμοί.</div>`;
export function installAnalyticsTabs(){if(window.__mwsAnalyticsTabsInstalled)return;window.__mwsAnalyticsTabsInstalled=true;document.addEventListener('click',e=>{const btn=e.target.closest('.kiosk-subtabs button');if(!btn)return;const tabs=[...btn.parentElement.querySelectorAll('button')],i=tabs.indexOf(btn);if(i<0)return;tabs.forEach((b,n)=>b.classList.toggle('active',n===i));if(i===0){toggleMain(true);return}const p=panel();if(!p)return;toggleMain(false);p.style.display='';const data=extract();p.innerHTML=i===1?indicators(data):i===2?daily(data):passages()});}
