const money=value=>value===null||value===undefined?"—":Number(value||0).toLocaleString("el-GR",{style:"currency",currency:"EUR"});
const num=value=>Number(value||0);
const pad=value=>String(value).padStart(2,"0");
const localDate=date=>`${date.getFullYear()}-${pad(date.getMonth()+1)}-${pad(date.getDate())}`;
const today=()=>localDate(new Date());
const monthStart=()=>{const d=new Date();return localDate(new Date(d.getFullYear(),d.getMonth(),1))};
const yearStart=()=>`${new Date().getFullYear()}-01-01`;
const esc=value=>String(value??"").replace(/[&<>"']/g,ch=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[ch]));
const fmt=value=>value?new Date(value).toLocaleString("el-GR",{day:"2-digit",month:"2-digit",year:"numeric",hour:"2-digit",minute:"2-digit"}):"—";
const duration=value=>{if(value===null||value===undefined)return"—";const mins=Math.max(0,Math.round(Number(value)));return `${String(Math.floor(mins/60)).padStart(2,"0")}:${String(mins%60).padStart(2,"0")}`};
const roleAllowed=()=>{try{return ["SUPER_ADMIN","OWNER","ADMIN","MANAGER"].includes(JSON.parse(localStorage.getItem("user")||"{}").role)}catch{return false}};
const txLabel=type=>({SALE_CASH:"Πώληση μετρητών",SALE_CARD:"Πώληση κάρτας",SUPPLIER_PAYMENT:"Πληρωμή προμηθευτή",OTHER_EXPENSE:"Λοιπό έξοδο",PERCENTAGES:"Ποσοστά"}[type]||String(type||"Κίνηση"));
const state={from:monthStart(),to:today(),storeId:"",status:"ALL",q:"",report:null,loading:false,error:"",detail:null,detailLoading:false,detailTab:"ledger"};

async function api(path){const token=localStorage.getItem("token");const r=await fetch(path,{headers:{...(token?{Authorization:`Bearer ${token}`}:{})}});const data=await r.json().catch(()=>({}));if(!r.ok)throw new Error(data.error||`Σφάλμα ${r.status}`);return data}
function query(){const q=new URLSearchParams({from:new Date(`${state.from}T00:00:00`).toISOString(),to:new Date(`${state.to}T23:59:59.999`).toISOString(),status:state.status});if(state.storeId)q.set("storeId",state.storeId);if(state.q.trim())q.set("q",state.q.trim());return q}
const varianceClass=value=>Math.abs(num(value))>.009?(num(value)<0?"negative":"positive"):"zero";
const signedMoney=value=>value===null||value===undefined?"—":`${num(value)>0?"+":""}${money(value)}`;

function filters(report){const stores=report?.stores||[];return `<section class="osc-filter"><div class="osc-filter-title"><b>Κριτήρια αναζήτησης</b><small>Πλήρης διαχείριση βαρδιών, ταμείου και διαφορών από πραγματικές καταγραφές MyWorkStation.</small></div><div class="osc-filter-grid">
<label>Από<input type="date" data-osc-from value="${esc(state.from)}"></label><label>Έως<input type="date" data-osc-to value="${esc(state.to)}"></label>
<label>Κατάστημα<select data-osc-store><option value="">Όλα τα καταστήματα</option>${stores.map(s=>`<option value="${esc(s.id)}" ${state.storeId===s.id?"selected":""}>${esc(s.name)}</option>`).join("")}</select></label>
<label>Κατάσταση<select data-osc-status><option value="ALL" ${state.status==="ALL"?"selected":""}>Όλες</option><option value="OPEN" ${state.status==="OPEN"?"selected":""}>Ανοιχτές</option><option value="CLOSED" ${state.status==="CLOSED"?"selected":""}>Κλειστές</option></select></label>
<label class="wide">Χειριστής / βάρδια<input data-osc-q value="${esc(state.q)}" placeholder="Όνομα χειριστή, βάρδια ή κατάστημα"></label><button class="osc-search" data-osc-search>⌕</button></div>
<div class="osc-filter-actions"><span></span><button data-osc-range="year">Τρέχον έτος</button><button data-osc-range="month">Τρέχων μήνας</button><button data-osc-range="today">Σήμερα</button><button data-osc-export>Excel / CSV</button><button data-osc-print>Εκτύπωση / PDF</button></div></section>`}
function cards(report){const s=report?.summary||{};return `<div class="osc-cards"><article><small>Βάρδιες</small><strong>${s.count||0}</strong><span>${s.open||0} ανοιχτές · ${s.closed||0} κλειστές</span></article><article><small>Πωλήσεις</small><strong>${money(num(s.cashSales)+num(s.cardSales))}</strong><span>Μετρητά + κάρτες</span></article><article><small>Μετρητά</small><strong>${money(s.cashSales)}</strong><span>Καταγεγραμμένες βάρδιες</span></article><article><small>Κάρτες</small><strong>${money(s.cardSales)}</strong><span>EFTPOS ${money(s.eftpos)}</span></article><article><small>Έξοδα βάρδιας</small><strong>${money(s.expenses)}</strong><span>Μόνο όσα αφαιρέθηκαν ρητά</span></article><article class="${varianceClass(s.variance)}"><small>Σύνολο διαφορών</small><strong>${signedMoney(s.variance)}</strong><span>Έναρξη ${signedMoney(s.openingVariance)}</span></article><article class="${s.alerts?"warn":"good"}"><small>Σήματα ελέγχου</small><strong>${s.alerts||0}</strong><span>Διαφορές / αντιλογισμοί / EFTPOS</span></article></div>`}
function table(report){const rows=report?.shifts||[];return `<section class="osc-panel"><div class="osc-panel-head"><div><h3>Βάρδιες & Ταμεία</h3><small>${rows.length} αποτελέσματα · πάτησε Α/Α ή τη Διαφορά για πλήρη ανάλυση</small></div><button data-osc-refresh>↻ Ανανέωση</button></div><div class="osc-table-wrap"><div class="osc-table"><div class="osc-row head"><span>Α/Α</span><span>Κατάστημα</span><span>Χειριστής</span><span>Έναρξη</span><span>Λήξη</span><span>Διάρκεια</span><span>Έναρξη ταμείου</span><span>Μετρητά</span><span>Κάρτες</span><span>EFTPOS</span><span>Έξοδα</span><span>Αναμενόμενο</span><span>Παρέδωσα</span><span>Διαφορά</span><span>Κατάσταση</span></div>${rows.map((row,index)=>`<div class="osc-row ${row.status==="OPEN"?"open":""}"><span><button class="osc-aa" data-osc-detail="${esc(row.id)}">${index+1}</button></span><span><b>${esc(row.storeName)}</b></span><span>${esc(row.openedByName||row.shiftLabel||"—")}<small>${row.closedByName?`Κλείσιμο: ${esc(row.closedByName)}`:""}</small></span><span>${fmt(row.openedAt)}</span><span>${fmt(row.closedAt)}</span><span>${duration(row.durationMinutes)}</span><strong>${money(row.openingOperational)}</strong><strong>${money(row.cashSales)}</strong><span>${money(row.cardSales)}</span><span>${row.status==="CLOSED"?money(row.eftposTotal):"—"}</span><span>${money(row.expenses)}</span><span>${row.status==="CLOSED"?money(row.expectedOperational):"—"}</span><strong>${row.status==="CLOSED"?money(row.actualOperational):"—"}</strong><span>${row.status==="CLOSED"?`<button class="osc-difference ${varianceClass(row.variance)}" data-osc-difference="${esc(row.id)}">${signedMoney(row.variance)}</button>`:"—"}</span><span><b class="osc-status ${row.status==="OPEN"?"open":"closed"}">${row.status==="OPEN"?"ΑΝΟΙΧΤΗ":"ΚΛΕΙΣΤΗ"}</b>${row.reversedCount?`<small>${row.reversedCount} αντιλογ.</small>`:""}</span></div>`).join("")||'<div class="osc-empty">Δεν υπάρχουν βάρδιες για τα επιλεγμένα κριτήρια.</div>'}</div></div></section>`}

function detailNav(){const items=[["ledger","Ημερολόγιο κινήσεων"],["categories","ανά κατηγορία"],["vat","ανά Τμήμα ΦΠΑ"],["summary","Συγκεντρωτικά"],["money","Ανάλυση χρηματικού"],["difference","Διαφορά"]];return `<div class="osc-detail-tabs">${items.map(([id,label])=>`<button data-osc-detail-tab="${id}" class="${state.detailTab===id?"active":""}">${label}</button>`).join("")}</div>`}
function ledgerDetail(d){const rows=d.transactions||[];return `<div class="osc-detail-table ledger"><div class="row head"><span>Κωδ.</span><span>Ημερομηνία</span><span>Περιγραφή</span><span>Χειριστής</span><span>Ποσό</span><span>Βάρδια</span><span>Παραστατικό</span><span>Κατάσταση</span></div>${rows.map(row=>`<div class="row ${row.reversedAt?"reversed":""}"><span>#${esc(String(row.id).slice(0,7))}</span><span>${fmt(row.occurredAt)}</span><span><b>${esc(row.description||txLabel(row.type))}</b><small>${esc(row.supplierName||txLabel(row.type))}</small></span><span>${esc(row.actorName||"—")}</span><strong>${money(row.amount)}</strong><span>${["SUPPLIER_PAYMENT","OTHER_EXPENSE"].includes(row.type)?(row.subtractFromShift?"Αφαιρέθηκε":"Δεν αφαιρέθηκε"):"—"}</span><span>${row.hasAttachment?"Υπάρχει":"—"}</span><span class="${row.reversedAt?"bad":"ok"}">${row.reversedAt?`ΑΝΤΙΛΟΓΙΣΜΟΣ${row.reversalReason?`<small>${esc(row.reversalReason)}</small>`:""}`:"ΕΝΕΡΓΗ"}</span></div>`).join("")||'<div class="osc-empty">Δεν υπάρχουν συνδεδεμένες κινήσεις στη βάρδια.</div>'}</div>`}
function categoryDetail(d){return `<div class="osc-detail-table categories"><div class="row head"><span>Κατηγορία</span><span>Ποσότητα</span><span>Πωλήσεις</span><span>Τζίρος</span></div>${(d.categories||[]).map(row=>`<div class="row"><span><b>${esc(row.category)}</b></span><span>${Number(row.quantity||0).toLocaleString("el-GR")}</span><span>${row.sales||0}</span><strong>${money(row.revenue)}</strong></div>`).join("")||'<div class="osc-empty">Δεν υπάρχουν πραγματικές κατηγορίες πωλήσεων για αυτή τη βάρδια.</div>'}</div>`}
function vatDetail(d){return `<div class="osc-locked"><b>Ανάλυση ανά Τμήμα ΦΠΑ</b><strong>—</strong><p>${esc(d.sourceStatus?.note||"Δεν υπάρχει ακόμη πραγματική φορολογική πηγή.")}</p><small>Δεν εμφανίζονται εικονικές τιμές ΦΠΑ.</small></div>`}
function summaryDetail(d){const s=d.shift,ds=d.difference,sales=d.sales||{};return `<div class="osc-summary-grid"><article><span>Χειριστής</span><b>${esc(s.openedByName||s.shiftLabel||"—")}</b><small>${fmt(s.openedAt)} → ${fmt(s.closedAt)}</small></article><article><span>Πωλήσεις βάρδιας</span><b>${money(sales.total)}</b><small>${sales.count||0} πωλήσεις · Μ.Ο. ${money(sales.average)}</small></article><article><span>Μετρητά</span><b>${money(ds.cashSales)}</b><small>Λειτουργικό κλείσιμο ${money(ds.actualOperational)}</small></article><article><span>Κάρτες</span><b>${money(ds.cardSales)}</b><small>EFTPOS ${money(ds.eftposTotal)}</small></article><article><span>Έξοδα που αφαιρέθηκαν</span><b>${money(num(ds.deductedSupplierPayments)+num(ds.deductedOtherExpenses))}</b><small>Καταγεγραμμένα ${money(num(ds.recordedSupplierPayments)+num(ds.recordedOtherExpenses))}</small></article><article class="${varianceClass(ds.variance)}"><span>Διαφορά</span><b>${signedMoney(ds.variance)}</b><small>Αναμενόμενο ${money(ds.expectedOperational)}</small></article></div>`}
function moneyDetail(d){const x=d.difference,methods=d.paymentMethods||[];return `<div class="osc-money-sections"><section><h3>Έναρξη</h3><div class="osc-money-grid"><span>Συρτάρι<b>${money(x.openingDrawer)}</b></span><span>Φύλαξη<b>${money(x.openingCustody)}</b></span><span>Κέρματα<b>${money(x.openingCoins)}</b></span><span>Χρηματοκιβώτιο<b>${money(x.openingSafe)}</b></span><span>Λειτουργική έναρξη<b>${money(x.declaredOpening)}</b></span></div></section><section><h3>Πωλήσεις / πληρωμές</h3><div class="osc-money-grid"><span>Μετρητά<b>${money(x.cashSales)}</b></span><span>Κάρτες<b>${money(x.cardSales)}</b></span><span>EFTPOS<b>${money(x.eftposTotal)}</b></span>${methods.map(row=>`<span>${esc(row.method)}<b>${money(row.amount)}</b><small>${row.count} κινήσεις</small></span>`).join("")}</div></section><section><h3>Κλείσιμο</h3><div class="osc-money-grid"><span>Συρτάρι<b>${money(x.closingDrawer)}</b></span><span>Φύλαξη<b>${money(x.closingCustody)}</b></span><span>Κέρματα<b>${money(x.closingCoins)}</b></span><span>Χρηματοκιβώτιο<b>${money(x.closingSafe)}</b></span><span>Παρέδωσα<b>${money(x.actualOperational)}</b></span><span>Επόμενη έναρξη<b>${money(x.nextOpeningTotal)}</b></span></div></section></div>`}
function differenceDetail(d){const x=d.difference,alerts=d.alerts||[],shift=d.shift;const deducted=num(x.deductedSupplierPayments)+num(x.deductedOtherExpenses),recorded=num(x.recordedSupplierPayments)+num(x.recordedOtherExpenses);return `<div class="osc-difference-page"><section class="osc-difference-hero ${varianceClass(x.variance)}"><div><small>Τελική Διαφορά Βάρδιας</small><strong>${signedMoney(x.variance)}</strong><span>${esc(x.formula)}</span></div><div><span>Αναμενόμενο<b>${money(x.expectedOperational)}</b></span><span>Παρέδωσα<b>${money(x.actualOperational)}</b></span></div></section><div class="osc-difference-grid"><section><h3>1. Συνέχεια έναρξης</h3><div><span>Αναμενόμενη έναρξη<b>${money(x.expectedOpening)}</b></span><span>Δηλωμένη έναρξη<b>${money(x.declaredOpening)}</b></span><span class="${varianceClass(x.openingVariance)}">Διαφορά έναρξης<b>${signedMoney(x.openingVariance)}</b></span></div><small>${shift.openingNote?`Σημείωση: ${esc(shift.openingNote)}`:"Χωρίς σημείωση έναρξης"}</small></section><section><h3>2. Πωλήσεις & EFTPOS</h3><div><span>Μετρητά<b>${money(x.cashSales)}</b></span><span>Κάρτες<b>${money(x.cardSales)}</b></span><span>EFTPOS<b>${money(x.eftposTotal)}</b></span><span class="${varianceClass(x.cardVariance)}">Κάρτες − EFTPOS<b>${signedMoney(x.cardVariance)}</b></span></div></section><section><h3>3. Έξοδα</h3><div><span>Καταγεγραμμένα έξοδα<b>${money(recorded)}</b></span><span>Αφαιρέθηκαν από βάρδια<b>${money(deducted)}</b></span><span>Πληρωμές προμηθευτών<b>${money(x.deductedSupplierPayments)}</b></span><span>Λοιπά έξοδα<b>${money(x.deductedOtherExpenses)}</b></span><span>Ποσοστά<b>${money(x.percentages)}</b></span></div><small>Μόνο οι κινήσεις με ρητή «Αφαίρεση από τη βάρδια» μειώνουν το αναμενόμενο ταμείο.</small></section><section><h3>4. Κλείσιμο</h3><div><span>Συρτάρι<b>${money(x.closingDrawer)}</b></span><span>Φύλαξη<b>${money(x.closingCustody)}</b></span><span>Κέρματα<b>${money(x.closingCoins)}</b></span><span>Χρηματοκιβώτιο<b>${money(x.closingSafe)}</b></span><span>Πραγματικό λειτουργικό<b>${money(x.actualOperational)}</b></span><span>Επόμενη έναρξη<b>${money(x.nextOpeningTotal)}</b></span></div><small>${shift.closingNote?`Σημείωση: ${esc(shift.closingNote)}`:"Χωρίς σημείωση κλεισίματος"}</small></section></div><section class="osc-alert-section"><div class="osc-panel-head"><div><h3>Συνέχεια ελέγχου διαφοράς</h3><small>Όλα τα πραγματικά συμβάντα που χρειάζονται προσοχή</small></div></div>${alerts.map(a=>`<article class="${varianceClass(a.amount)}"><b>${esc(a.label)}</b><strong>${a.amount!==undefined?signedMoney(a.amount):""}</strong><small>${a.transactionId?`Κίνηση #${esc(String(a.transactionId).slice(0,8))}`:a.kind==="DUPLICATE_REVIEW"?"Έλεγχος πιθανής διαδοχικής ίδιας πώλησης":""}</small></article>`).join("")||'<div class="osc-empty good">Δεν υπάρχουν πρόσθετα σήματα ελέγχου για τη βάρδια.</div>'}</section>${ledgerDetail(d)}`}
function detailBody(d){if(state.detailTab==="categories")return categoryDetail(d);if(state.detailTab==="vat")return vatDetail(d);if(state.detailTab==="summary")return summaryDetail(d);if(state.detailTab==="money")return moneyDetail(d);if(state.detailTab==="difference")return differenceDetail(d);return ledgerDetail(d)}
function detailModal(){if(state.detailLoading)return `<div class="osc-modal"><div class="osc-dialog"><div class="osc-loading">Φόρτωση πλήρους βάρδιας…</div></div></div>`;const d=state.detail;if(!d)return"";const s=d.shift;return `<div class="osc-modal" data-osc-modal><div class="osc-dialog"><div class="osc-dialog-title"><div><h2>Βάρδια <small>#${esc(String(s.id).slice(0,8))}</small></h2><p>${esc(s.storeName)} · ${esc(s.openedByName||s.shiftLabel||"Χειριστής")} · ${fmt(s.openedAt)} → ${fmt(s.closedAt)}</p></div><button data-osc-close>✕</button></div>${detailNav()}<div class="osc-detail-content">${detailBody(d)}</div><div class="osc-dialog-actions"><button data-osc-back>← Επιστροφή</button><span></span><button data-osc-detail-print>Εκτύπωση / PDF</button></div></div></div>`}
function render(root){root.innerHTML=`<div class="osc-title"><div><h2>Βάρδιες & Διαφορές</h2><p>Κεντρική διαχείριση ιδιοκτήτη: Α/Α → πλήρης βάρδια · Διαφορά → αναλυτικός έλεγχος.</p></div><span>ΠΡΑΓΜΑΤΙΚΑ ΔΕΔΟΜΕΝΑ</span></div>${filters(state.report)}${state.error?`<div class="osc-error">${esc(state.error)}</div>`:""}${state.loading?'<div class="osc-loading">Φόρτωση βαρδιών…</div>':`${cards(state.report)}${table(state.report)}`}${detailModal()}`;bind(root)}
async function load(root){state.loading=true;state.error="";render(root);try{state.report=await api(`/api/owner-shifts/report?${query()}`)}catch(e){state.error=e.message}finally{state.loading=false;render(root)}}
async function openDetail(root,id,tab="ledger"){state.detail=null;state.detailTab=tab;state.detailLoading=true;render(root);try{state.detail=await api(`/api/owner-shifts/${encodeURIComponent(id)}/detail`)}catch(e){state.error=e.message}finally{state.detailLoading=false;render(root)}}
function closeDetail(root){state.detail=null;state.detailLoading=false;render(root)}
function setRange(id){if(id==="today"){state.from=today();state.to=today()}else if(id==="month"){state.from=monthStart();state.to=today()}else{state.from=yearStart();state.to=today()}}
function exportCsv(){const rows=state.report?.shifts||[],lines=[["Α/Α","Κατάστημα","Χειριστής","Έναρξη","Λήξη","Διάρκεια λεπτά","Έναρξη ταμείου","Μετρητά","Κάρτες","EFTPOS","Έξοδα","Αναμενόμενο","Παρέδωσα","Διαφορά","Κατάσταση"]];rows.forEach((r,i)=>lines.push([i+1,r.storeName,r.openedByName||r.shiftLabel,fmt(r.openedAt),fmt(r.closedAt),r.durationMinutes??"",r.openingOperational,r.cashSales,r.cardSales,r.eftposTotal??"",r.expenses,r.expectedOperational??"",r.actualOperational??"",r.variance??"",r.status]));const csv="\ufeff"+lines.map(row=>row.map(v=>`"${String(v??"").replace(/"/g,'""')}"`).join(";")).join("\n"),blob=new Blob([csv],{type:"text/csv;charset=utf-8"}),url=URL.createObjectURL(blob),a=document.createElement("a");a.href=url;a.download=`myworkstation-shifts-${state.from}-${state.to}.csv`;a.click();URL.revokeObjectURL(url)}
function bind(root){root.querySelector("[data-osc-search]")?.addEventListener("click",()=>{state.from=root.querySelector("[data-osc-from]")?.value||state.from;state.to=root.querySelector("[data-osc-to]")?.value||state.to;state.storeId=root.querySelector("[data-osc-store]")?.value||"";state.status=root.querySelector("[data-osc-status]")?.value||"ALL";state.q=root.querySelector("[data-osc-q]")?.value||"";load(root)});root.querySelector("[data-osc-q]")?.addEventListener("keydown",e=>{if(e.key==="Enter")root.querySelector("[data-osc-search]")?.click()});root.querySelectorAll("[data-osc-range]").forEach(b=>b.addEventListener("click",()=>{setRange(b.dataset.oscRange);load(root)}));root.querySelector("[data-osc-refresh]")?.addEventListener("click",()=>load(root));root.querySelector("[data-osc-export]")?.addEventListener("click",exportCsv);root.querySelector("[data-osc-print]")?.addEventListener("click",()=>window.print());root.querySelectorAll("[data-osc-detail]").forEach(b=>b.addEventListener("click",()=>openDetail(root,b.dataset.oscDetail,"ledger")));root.querySelectorAll("[data-osc-difference]").forEach(b=>b.addEventListener("click",()=>openDetail(root,b.dataset.oscDifference,"difference")));root.querySelectorAll("[data-osc-detail-tab]").forEach(b=>b.addEventListener("click",()=>{state.detailTab=b.dataset.oscDetailTab;render(root)}));root.querySelector("[data-osc-close]")?.addEventListener("click",()=>closeDetail(root));root.querySelector("[data-osc-back]")?.addEventListener("click",()=>closeDetail(root));root.querySelector("[data-osc-detail-print]")?.addEventListener("click",()=>window.print())}
function activate(hub,tab,root){hub.classList.add("owner-shifts-active");hub.querySelectorAll(".commerce-module-strip button").forEach(button=>button.classList.toggle("active",button===tab));root.style.display="block";if(!state.storeId){const selected=hub.querySelector(":scope > .panel > label select")?.value||"";if(selected)state.storeId=selected}if(!state.report)load(root);else render(root)}
function deactivate(hub,tab,root){hub.classList.remove("owner-shifts-active");tab.classList.remove("active");root.style.display="none"}
function installHub(hub){if(!roleAllowed())return;const strip=hub.querySelector(".commerce-module-strip");if(!strip)return;let root=hub.querySelector(":scope > .owner-shifts-suite");if(!root){root=document.createElement("section");root.className="owner-shifts-suite";root.style.display="none";hub.appendChild(root)}let tab=strip.querySelector(".owner-shifts-tab");if(!tab){tab=document.createElement("button");tab.type="button";tab.className="owner-shifts-tab";tab.textContent="📋 Βάρδιες & Διαφορές";tab.addEventListener("click",()=>activate(hub,tab,root));strip.appendChild(tab)}strip.querySelectorAll("button:not(.owner-shifts-tab)").forEach(button=>{if(button.dataset.ownerShiftsBound)return;button.dataset.ownerShiftsBound="1";button.addEventListener("click",()=>deactivate(hub,tab,root))})}
export function installOwnerShiftControlCenter(){const run=()=>document.querySelectorAll(".commerce-hub").forEach(installHub);run();const observer=new MutationObserver(run);observer.observe(document.documentElement,{childList:true,subtree:true});window.addEventListener("keydown",e=>{if(e.key==="Escape"&&state.detail){const root=document.querySelector(".owner-shifts-suite");if(root)closeDetail(root)}})}
