const esc=value=>String(value??"").replace(/[&<>"']/g,char=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[char]));
const money=value=>Number(value||0).toLocaleString("el-GR",{style:"currency",currency:"EUR"});
const fmt=value=>value?new Date(value).toLocaleString("el-GR"):"—";
const token=()=>localStorage.getItem("token");
async function api(path,options={}){const response=await fetch(path,{...options,headers:{"Content-Type":"application/json",...(token()?{Authorization:`Bearer ${token()}`}:{}) ,...(options.headers||{})}});const data=await response.json().catch(()=>({}));if(!response.ok){const error=new Error(data.error||`Σφάλμα ${response.status}`);error.code=data.code;error.data=data;throw error}return data}
const fileBase64=file=>new Promise((resolve,reject)=>{const reader=new FileReader();reader.onerror=()=>reject(new Error("Δεν διαβάστηκε το αρχείο."));reader.onload=()=>{const value=String(reader.result||"");resolve(value.includes(",")?value.split(",").pop():value)};reader.readAsDataURL(file)});

function shell(){const overlay=document.createElement("div");overlay.className="leaflet-import-overlay";overlay.innerHTML=`<section class="leaflet-import-modal"><header><div><small>ΤΙΜΟΚΑΤΑΛΟΓΟΣ · ΠΡΟΣΦΟΡΕΣ ΦΥΛΛΑΔΙΟΥ</small><h2>Εισαγωγή από αρχείο</h2></div><button data-li-close>✕</button></header><div data-li-body><div class="li-loading">Φόρτωση καταστημάτων…</div></div></section>`;document.body.appendChild(overlay);overlay.addEventListener("click",event=>{if(event.target===overlay||event.target.closest("[data-li-close]"))overlay.remove()});return overlay}
function statusText(status){return ({READY:"Έτοιμη",UNRESOLVED:"Δεν βρέθηκε είδος",INVALID:"Μη έγκυρη",OVERLAP:"Επικάλυψη"})[status]||status}
function rowHtml(row){return `<div class="li-row ${String(row.status||"").toLowerCase()}"><span>${row.rowNumber}</span><strong>${esc(statusText(row.status))}</strong><span>${esc(row.product?.name||row.description||"—")}</span><span>${esc(row.matchedBy||"—")}</span><span>${row.status==="READY"?money(row.offerPrice):"—"}</span><span>${row.validFrom?fmt(row.validFrom):"—"}</span><span>${row.validUntil?fmt(row.validUntil):"—"}</span><small>${esc(row.error||row.warnings?.join(" · ")||"")}</small></div>`}

async function openImport(root){
  const overlay=shell(),body=overlay.querySelector("[data-li-body]");let stores=[],file=null,fileData="",preview=null,filter="ALL";
  const lookups=await api("/api/price-catalog/lookups").catch(error=>{body.innerHTML=`<div class="li-error">${esc(error.message)}</div>`;return null});if(!lookups)return;stores=lookups.stores||[];
  const renderSetup=()=>{body.innerHTML=`<div class="li-grid"><label>Αρχείο XLSX / XLS / CSV<input type="file" data-li-file accept=".xlsx,.xls,.csv"></label><fieldset><legend>Καταστήματα POS</legend><div class="li-store-actions"><button type="button" data-li-all>Όλα</button><button type="button" data-li-none>Κανένα</button></div><div class="li-stores">${stores.map(store=>`<label><input type="checkbox" data-li-store value="${esc(store.id)}"> ${esc(store.name)}</label>`).join("")||"Δεν υπάρχουν ενεργά καταστήματα."}</div></fieldset></div><div class="li-help"><b>Αντιστοίχιση:</b> Barcode → SKU / εσωτερικός κωδικός → ακριβής Περιγραφή. Δεν δημιουργούνται νέα προϊόντα από το Excel.</div><footer><button class="secondary" data-li-close>Κλείσιμο</button><button class="primary" data-li-preview>Προεπισκόπηση</button></footer>`;
    body.querySelector("[data-li-file]")?.addEventListener("change",e=>{file=e.target.files?.[0]||null;preview=null});body.querySelector("[data-li-all]")?.addEventListener("click",()=>body.querySelectorAll("[data-li-store]").forEach(x=>x.checked=true));body.querySelector("[data-li-none]")?.addEventListener("click",()=>body.querySelectorAll("[data-li-store]").forEach(x=>x.checked=false));body.querySelector("[data-li-preview]")?.addEventListener("click",runPreview)};
  const selectedStores=()=>[...body.querySelectorAll("[data-li-store]:checked")].map(x=>x.value);
  const setBusy=(busy,label="Προεπισκόπηση")=>{const button=body.querySelector("[data-li-preview]");if(button){button.disabled=busy;button.textContent=busy?"Έλεγχος…":label}};
  const runPreview=async()=>{try{if(!file)throw new Error("Επίλεξε αρχείο.");const storeIds=selectedStores();if(!storeIds.length)throw new Error("Επίλεξε τουλάχιστον ένα κατάστημα.");setBusy(true);fileData=await fileBase64(file);preview=await api("/api/price-catalog/promotions/import/preview",{method:"POST",body:JSON.stringify({filename:file.name,base64:fileData,storeIds})});renderPreview()}catch(error){alert(error.message)}finally{setBusy(false)}};
  const renderPreview=()=>{if(!preview)return;const counts=preview.counts||{},rows=preview.rows||[],visible=(filter==="ALL"?rows:rows.filter(row=>row.status===filter)).slice(0,300),hasSkipped=Number(preview.skipped||0)>0;body.innerHTML=`<div class="li-summary"><span><b>${counts.total||0}</b> γραμμές</span><span class="ready"><b>${counts.ready||0}</b> έτοιμες</span><span><b>${counts.unresolved||0}</b> unresolved</span><span><b>${counts.invalid||0}</b> μη έγκυρες</span><span><b>${counts.overlap||0}</b> overlap</span></div><div class="li-targets"><b>Καταστήματα:</b> ${(preview.stores||[]).map(s=>esc(s.name)).join(" · ")}</div><div class="li-filter"><label>Εμφάνιση<select data-li-filter><option value="ALL">Όλες</option><option value="READY">Έτοιμες</option><option value="UNRESOLVED">Δεν βρέθηκε είδος</option><option value="INVALID">Μη έγκυρες</option><option value="OVERLAP">Επικάλυψη</option></select></label><small>Εμφανίζονται έως 300 γραμμές για προστασία από κόλλημα.</small></div><div class="li-table"><div class="li-head"><span>#</span><span>Κατάσταση</span><span>Είδος</span><span>Match</span><span>Νέα τιμή</span><span>Από</span><span>Έως</span><span>Παρατήρηση</span></div>${visible.map(rowHtml).join("")||'<div class="li-empty">Δεν υπάρχουν γραμμές σε αυτό το φίλτρο.</div>'}</div>${hasSkipped?`<label class="li-accept"><input type="checkbox" data-li-accept> Αποδέχομαι ότι <b>${preview.skipped}</b> unresolved / invalid / overlap γραμμές θα παραλειφθούν και δεν θα δημιουργηθούν προϊόντα ή διπλές προσφορές.</label>`:""}<footer><button class="secondary" data-li-back>Πίσω</button><button class="primary" data-li-commit ${preview.canCommit?"":"disabled"}>Τελική εισαγωγή ${counts.ready||0} προσφορών</button></footer>`;
    const select=body.querySelector("[data-li-filter]");if(select){select.value=filter;select.addEventListener("change",e=>{filter=e.target.value;renderPreview()})}body.querySelector("[data-li-back]")?.addEventListener("click",renderSetup);body.querySelector("[data-li-commit]")?.addEventListener("click",commit)};
  const commit=async()=>{try{const acceptSkipped=Boolean(body.querySelector("[data-li-accept]")?.checked);if(preview.skipped>0&&!acceptSkipped)throw new Error("Επιβεβαίωσε ότι αποδέχεσαι τις γραμμές που θα παραλειφθούν.");if(!confirm(`Να εισαχθούν οριστικά ${preview.counts.ready} προσφορές στα επιλεγμένα καταστήματα;`))return;const button=body.querySelector("[data-li-commit]");if(button){button.disabled=true;button.textContent="Καταχώρηση…"}const result=await api("/api/price-catalog/promotions/import/commit",{method:"POST",body:JSON.stringify({filename:file.name,base64:fileData,storeIds:preview.stores.map(s=>s.id),previewHash:preview.previewHash,confirm:true,acceptSkipped})});overlay.remove();alert(`Ολοκληρώθηκε: ${result.imported} προσφορές. Παραλείφθηκαν: ${result.skipped}.`);root.querySelector("[data-pc-refresh]")?.click()}catch(error){alert(error.message);const button=body.querySelector("[data-li-commit]");if(button){button.disabled=false;button.textContent=`Τελική εισαγωγή ${preview?.counts?.ready||0} προσφορών`}}};
  renderSetup();
}

export function installLeafletImport(){
  const root=document.querySelector(".price-catalog-suite");if(!root)return;
  const leaflet=root.querySelector('[data-pc-tab="leaflet"].active');if(!leaflet)return;
  const newButton=root.querySelector('[data-pc-new-promo="LEAFLET"]');if(!newButton||root.querySelector("[data-li-launch]"))return;
  const button=document.createElement("button");button.type="button";button.dataset.liLaunch="1";button.textContent="📥 Εισαγωγή από αρχείο";button.addEventListener("click",()=>openImport(root).catch(error=>alert(error.message)));newButton.insertAdjacentElement("afterend",button);
}
