const esc=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]));
const n=v=>Number(v||0),money=v=>n(v).toLocaleString("el-GR",{style:"currency",currency:"EUR",minimumFractionDigits:2}),num=v=>n(v).toLocaleString("el-GR",{maximumFractionDigits:3}),pct=v=>`${n(v).toLocaleString("el-GR",{minimumFractionDigits:2,maximumFractionDigits:2})}%`,fmt=v=>v?new Date(v).toLocaleString("el-GR"):"—";
let currentItems=[];
async function api(path){const t=localStorage.getItem("token"),r=await fetch(path,{headers:{...(t?{Authorization:`Bearer ${t}`}:{})}}),d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||`Σφάλμα ${r.status}`);return d}
function params(root){return new URLSearchParams({from:root.querySelector("[data-kr-from]")?.value||"",to:root.querySelector("[data-kr-to]")?.value||"",...(root.querySelector("[data-kr-store]")?.value?{storeId:root.querySelector("[data-kr-store]").value}:{}),...(root.querySelector("[data-kr-q]")?.value?.trim()?{q:root.querySelector("[data-kr-q]").value.trim()}:{})})}
const head=c=>`<div class="kr-row kr-head">${c.map(x=>`<span>${x}</span>`).join("")}</div>`,row=c=>`<div class="kr-row">${c.map(x=>`<span>${x}</span>`).join("")}</div>`;
function removeContent(root){root.querySelector(".kr-panel")?.remove();root.querySelector(".kr-unavailable")?.remove();root.querySelector(".kr-error")?.remove()}
function view(data){const items=data.items||[];currentItems=items;return `<section class="kr-panel kr-stock-v3"><h3>Στατιστικά / Ανάλυση αποθήκης</h3><div class="kr-stock-cards"><article><span>Απόθεμα</span><b>${num(data.totalStockQuantity)}</b></article><article><span>Αξία αγοράς</span><b>${money(data.totalPurchaseValue)}</b></article><article><span>Αξία λιανικής</span><b>${money(data.totalRetailValue)}</b></article><article><span>Πωλήσεις περιόδου</span><b>${num(data.totalSalesQuantity)}</b></article></div><div class="kr-info">Οι αξίες αποθήκης βασίζονται στο τρέχον stock, στη store-specific λιανική και στην τελευταία εγκεκριμένη πραγματική αγορά του ίδιου καταστήματος.</div><div class="kr-table stock-v3">${head(["","Κατηγορία","Υποκατηγορία","Περιγραφή είδους","Κωδικός","Απόθεμα","Τιμή αγοράς","Αξία αγοράς","Λιανική","Αξία λιανικής","Margin","Πωλήσεις περιόδου","Τελευταία πώληση","Τελευταία αγορά","Προμηθευτής","Κατάστημα"])}${items.map(r=>row([`<button class="kr-expand" data-stock-detail="${esc(r.productId)}" data-stock-store="${esc(r.storeId)}">＋</button>`,esc(r.categoryName||"—"),esc(r.subcategoryName||"—"),`<b>${esc(r.name)}</b>`,esc(r.sku||"—"),num(r.currentStock),money(r.purchasePrice),`<strong>${money(r.purchaseValue)}</strong>`,money(r.salePrice),`<strong>${money(r.retailValue)}</strong>`,pct(r.margin),num(r.salesQuantity),fmt(r.lastSaleAt),fmt(r.lastPurchaseAt),esc(r.supplierName||"—"),esc(r.storeName||"—")])).join("")||'<div class="kr-empty">Δεν βρέθηκαν εγγραφές.</div>'}</div><div class="kr-summary"><span>${items.length} είδη</span><strong>Αγορά: ${money(data.totalPurchaseValue)}</strong><strong>Λιανική: ${money(data.totalRetailValue)}</strong></div></section>`}
async function load(root){root.dataset.stockV3="1";root.querySelectorAll("[data-kr-tab]").forEach(b=>b.classList.toggle("active",b.dataset.krTab==="stock-stats"));removeContent(root);const toolbar=root.querySelector(".kr-toolbar"),holder=document.createElement("div");holder.className="kr-error";holder.textContent="Φόρτωση…";toolbar?.before(holder);try{const data=await api(`/api/reports/stock-analysis?${params(root)}`);holder.outerHTML=view(data)}catch(e){holder.textContent=e.message}}
function closeModal(){document.querySelector(".kr-stock-modal")?.remove()}
async function detail(root,button){const productId=button.dataset.stockDetail,storeId=button.dataset.stockStore,query=params(root);if(storeId)query.set("storeId",storeId);let modal=document.querySelector(".kr-stock-modal");if(!modal){modal=document.createElement("div");modal.className="kr-stock-modal";document.body.appendChild(modal)}modal.innerHTML='<div class="kr-stock-dialog"><button class="kr-stock-x" data-stock-close>✕</button><h3>Κινήσεις είδους</h3><p>Φόρτωση…</p></div>';try{const data=await api(`/api/reports/stock-analysis/${encodeURIComponent(productId)}/movements?${query}`),items=data.items||[];modal.innerHTML=`<div class="kr-stock-dialog"><button class="kr-stock-x" data-stock-close>✕</button><h3>${esc(data.product?.name||"Κινήσεις είδους")}</h3><div class="kr-info">${esc(data.product?.sku||"")} · ${items.length} κινήσεις στο επιλεγμένο διάστημα</div><div class="kr-stock-detail-table"><div class="detail-head"><span>Ημερομηνία</span><span>Κίνηση</span><span>Ποσότητα</span><span>Κόστος</span><span>Αξία</span><span>Πηγή</span><span>Χειριστής</span><span>Κατάστημα</span><span>Σημείωση</span></div>${items.map(r=>`<div><span>${fmt(r.createdAt)}</span><span>${esc(r.movementType)}</span><span>${num(r.quantity)}</span><span>${money(r.unitCost)}</span><span>${money(r.value)}</span><span>${esc(r.sourceType||"—")}</span><span>${esc(r.operatorName||"—")}</span><span>${esc(r.storeName||"—")}</span><span>${esc(r.note||"—")}</span></div>`).join("")||'<p>Δεν βρέθηκαν κινήσεις.</p>'}</div></div>`}catch(e){modal.querySelector("p").textContent=e.message}}
function exportCsv(){if(!currentItems.length)return alert("Δεν υπάρχουν δεδομένα για εξαγωγή.");const keys=["categoryName","subcategoryName","name","sku","currentStock","purchasePrice","purchaseValue","salePrice","retailValue","margin","salesQuantity","lastSaleAt","lastPurchaseAt","supplierName","storeName"],csv="\ufeff"+[keys.join(";"),...currentItems.map(r=>keys.map(k=>`"${String(r[k]??"").replace(/"/g,'""')}"`).join(";"))].join("\r\n"),a=document.createElement("a");a.href=URL.createObjectURL(new Blob([csv],{type:"text/csv;charset=utf-8"}));a.download="analysi-apothikis.csv";a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
export function installKioskReportsStockV3(){if(window.__mwsKioskReportsStockV3)return;window.__mwsKioskReportsStockV3=true;document.addEventListener("click",event=>{const close=event.target.closest("[data-stock-close]");if(close){event.preventDefault();closeModal();return}const root=event.target.closest(".kiosk-reports-suite");if(!root)return;const tab=event.target.closest("[data-kr-tab]");if(tab){if(tab.dataset.krTab==="stock-stats"){event.preventDefault();event.stopImmediatePropagation();load(root);return}delete root.dataset.stockV3;currentItems=[];return}const detailButton=event.target.closest("[data-stock-detail]");if(detailButton){event.preventDefault();event.stopImmediatePropagation();detail(root,detailButton);return}if(root.dataset.stockV3!=="1")return;if(event.target.closest("[data-kr-search]")||event.target.closest("[data-kr-refresh]")){event.preventDefault();event.stopImmediatePropagation();load(root);return}if(event.target.closest("[data-kr-export]")){event.preventDefault();event.stopImmediatePropagation();exportCsv()}},true)}
