const esc=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]));
const n=v=>Number(v||0),money=v=>n(v).toLocaleString("el-GR",{style:"currency",currency:"EUR"}),num=v=>n(v).toLocaleString("el-GR",{maximumFractionDigits:3}),fmt=v=>v?new Date(v).toLocaleString("el-GR"):"—";
let currentItems=[];
async function api(path,options={}){const t=localStorage.getItem("token"),r=await fetch(path,{...options,headers:{"Content-Type":"application/json",...(t?{Authorization:`Bearer ${t}`}:{}) ,...(options.headers||{})}}),d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||`Σφάλμα ${r.status}`);return d}
function params(root){const value=name=>root.querySelector(`[data-video-filter="${name}"]`)?.value||"";return new URLSearchParams({from:root.querySelector("[data-kr-from]")?.value||"",to:root.querySelector("[data-kr-to]")?.value||"",...(root.querySelector("[data-kr-store]")?.value?{storeId:root.querySelector("[data-kr-store]").value}:{}),...(root.querySelector("[data-kr-q]")?.value?.trim()?{q:root.querySelector("[data-kr-q]").value.trim()}:{}),timeFrom:value("timeFrom"),timeTo:value("timeTo"),operatorId:value("operatorId"),terminalPos:value("terminalPos"),eventType:value("eventType"),amountMin:value("amountMin"),amountMax:value("amountMax")})}
const head=c=>`<div class="kr-row kr-head">${c.map(x=>`<span>${x}</span>`).join("")}</div>`,row=c=>`<div class="kr-row">${c.map(x=>`<span>${x}</span>`).join("")}</div>`;
function removeOld(root){root.querySelector(".kr-panel")?.remove();root.querySelector(".kr-unavailable")?.remove();root.querySelector(".kr-error")?.remove()}
function deletionView(data){const items=data.items||[];currentItems=items;return `<section class="kr-panel"><h3>Διαγραφές λίστας πώλησης</h3><div class="kr-info">Το audit ξεκινά από την ενεργοποίηση αυτής της λειτουργίας. Δεν δημιουργούνται αναδρομικές εγγραφές.</div><div class="kr-table audit-deletions">${head(["Ημερομηνία","Περιγραφή","Ποσότητα","Τιμή μονάδος","Σύνολο","Χειριστής","Αιτιολογία","Βάρδια","Κατάστημα"])}${items.map(r=>row([fmt(r.createdAt),`<b>${esc(r.productName||"—")}</b>`,num(r.quantity),money(r.unitPrice),`<strong>${money(r.lineTotal)}</strong>`,esc(r.actorName||"—"),esc(r.reason||r.eventType||"—"),esc(r.shiftId||"—"),esc(r.storeName||"—")])).join("")||'<div class="kr-empty">Δεν βρέθηκαν εγγραφές.</div>'}</div><div class="kr-summary"><span>${items.length} εγγραφές</span><strong>Σύνολο: ${money(data.totalValue)}</strong></div></section>`}
function deactivationView(data){const items=data.items||[];currentItems=items;return `<section class="kr-panel"><h3>Απενεργοποιήσεις ειδών</h3><div class="kr-info">Εμφανίζονται πραγματικές αλλαγές Ενεργό → Ανενεργό που καταγράφηκαν μετά την ενεργοποίηση audit.</div><div class="kr-table audit-deactivations">${head(["Ημερομηνία","Περιγραφή","Εσωτ. κωδικός","Λιανική","Απόθεμα","Χειριστής","Πηγή","Κατάστημα"])}${items.map(r=>row([fmt(r.createdAt),`<b>${esc(r.productName||"—")}</b>`,esc(r.sku||"—"),money(r.salePrice),num(r.currentStock),esc(r.actorName||"—"),esc(r.sourceType||"—"),esc(r.storeName||"Όλα")])).join("")||'<div class="kr-empty">Δεν βρέθηκαν εγγραφές.</div>'}</div><div class="kr-summary"><span>${items.length} απενεργοποιήσεις</span></div></section>`}
const isPosCancel=r=>r?.eventType==="POS_CANCEL"||/^POS\s+ΑΚΥΡΩΣΗ\b/i.test(String(r?.description||""));
const eventLabel=r=>isPosCancel(r)?"Ακύρωση πώλησης":({SUPPLIER_PAYMENT:"Πληρωμή προμηθευτή",OTHER_EXPENSE:"Λοιπά έξοδα",SALE_CASH:"Πώληση μετρητών",SALE_CARD:"Πώληση με κάρτα",PERCENTAGES:"Ποσοστά",TRANSFER_AMOUNT:"Μεταφορά ποσού",POS_RETURN:"Ολική επιστροφή",POS_RETURN_ITEMS:"Μερική επιστροφή",POS_SELF_CONSUMPTION:"Προσωπική κατανάλωση",POS_PRODUCT_DESTRUCTION:"Καταστροφή προϊόντων",POS_CANCEL:"Ακύρωση πώλησης",ONLINE_ORDER:"Online Παραγγελίες"})[r?.eventType]||r?.eventType||"—";
const paymentLabel=r=>r.sourceType==="ONLINE_ORDERS"?"Online Παραγγελίες":r.paymentSource==="CASH_SHIFT"?"Μετρητά βάρδιας":r.paymentSource==="AUDIT_EVENT"?"Συμβάν":"Εξωτερικά";
const onlineAction=event=>{if(event.note==="ORDER_RECEIVED")return"Λήψη παραγγελίας";if(event.note==="AUTO_PRINT_REQUESTED")return"Αυτόματη εκτύπωση";if(event.note==="PRINT_REQUESTED")return"Εκτύπωση / επανεκτύπωση";const to=String(event.toStatus||"");if(to==="ACCEPTED")return"Αποδοχή παραγγελίας";if(to==="PREPARING")return"Έναρξη προετοιμασίας";if(to==="READY")return"Η παραγγελία είναι έτοιμη";if(to==="OUT_FOR_DELIVERY")return"Παράδοση σε delivery";if(to==="DELIVERED")return"Η παραγγελία παραδόθηκε";if(to==="CANCELLED")return"Ακύρωση παραγγελίας";return event.note||`${event.fromStatus||""}${event.fromStatus?" → ":""}${to||"Ενημέρωση παραγγελίας"}`};
function onlineStoreOptions(root){const select=root.querySelector("[data-kr-store]");if(!select)return[];const selected=select.value;return [...select.options].map(option=>({id:option.value,name:String(option.textContent||"").trim()})).filter(store=>store.id&&(store.id==="kat-test-store"||/ΚΥΛΙΚΕΙΟ\s*ΚΑΤ/i.test(store.name))).filter(store=>!selected||store.id===selected)}
function auditRange(root){const from=root.querySelector("[data-kr-from]")?.value,to=root.querySelector("[data-kr-to]")?.value;const start=from?new Date(`${from}T00:00:00`).getTime():-Infinity,end=to?new Date(`${to}T23:59:59.999`).getTime():Infinity;return{start,end,q:String(root.querySelector("[data-kr-q]")?.value||"").trim().toLocaleLowerCase("el-GR")}}
async function mergeOnlineOrderEvents(root,data){const stores=onlineStoreOptions(root);if(!stores.length)return data;const {start,end,q}=auditRange(root),online=[];await Promise.all(stores.map(async store=>{try{const result=await api(`/api/public/kat/backoffice/stores/${encodeURIComponent(store.id)}/orders?limit=300`);for(const order of result.rows||[])for(const event of order.events||[]){const ts=new Date(event.createdAt||0).getTime();if(ts<start||ts>end)continue;const action=onlineAction(event),description=`#${order.orderNumber} · ${action}${order.customerName?` · ${order.customerName}`:""}`;if(q&&!`${description} ${order.customerPhone||""} ${store.name}`.toLocaleLowerCase("el-GR").includes(q))continue;online.push({id:`online-${event.id}`,createdAt:event.createdAt,eventType:"ONLINE_ORDER",amount:0,description,supplierId:null,supplierName:null,shiftId:null,actorId:event.userId||event.employeeId||null,actorName:event.employeeId?`Εργαζόμενος ${event.employeeId}`:"Online",subtractFromShift:false,reversedAt:null,reversedByName:null,reversalReason:null,storeName:store.name,sourceType:"ONLINE_ORDERS",paymentSource:"ONLINE_ORDERS",orderNumber:order.orderNumber,onlineStatus:event.toStatus})}}catch{}}));const items=[...(data.items||[]),...online].sort((a,b)=>new Date(b.createdAt||0)-new Date(a.createdAt||0)).slice(0,10000);return{...data,items,count:items.length,sourceOfTruth:`${data.sourceOfTruth||"StoreTransaction + PosSaleActionAudit"} + OnlineOrderStatusEvent`}}
function auditView(data){const items=data.items||[],canVideo=data.videoAccessAllowed===true;currentItems=items;return `<section class="kr-panel"><h3>Συμβάντα / Audit</h3><div class="kr-info">Πηγή αλήθειας: <b>${esc(data.sourceOfTruth||"StoreTransaction")}</b>. ${canVideo?"Η πρόσβαση Video είναι ενεργή για τον λογαριασμό σου.":"Δεν έχεις εξουσιοδότηση προβολής Video."}</div><div class="kr-table audit-events">${head(["Ημερομηνία","Τύπος","Transaction ID","Περιγραφή / Τιμολόγιο","Ποσό","Προμηθευτής","Χειριστής","Βάρδια","Τρόπος","Κατάστημα","Video"])}${items.map(r=>row([fmt(r.createdAt),`<b>${esc(eventLabel(r))}</b>`,`<small>${esc(r.id||"—")}</small>`,esc(r.description||"—"),r.sourceType==="ONLINE_ORDERS"?"—":`<strong>${money(r.amount)}</strong>`,esc(r.supplierName||"—"),esc(r.actorName||"—"),esc(r.shiftId||"—"),paymentLabel(r),esc(r.storeName||"—"),canVideo?`<button type="button" class="kr-video-button" data-video-source="${esc(r.sourceType||"StoreTransaction")}" data-video-id="${esc(r.id||"")}">Προβολή βίντεο</button>`:"🔒"])).join("")||'<div class="kr-empty">Δεν βρέθηκαν εγγραφές.</div>'}</div><div class="kr-summary"><span>${items.length} συμβάντα</span><strong>Source of truth: ${esc(data.sourceOfTruth||"StoreTransaction")}</strong></div></section>`}
const accessPath=button=>`/api/reports/audit-events/${encodeURIComponent(button.dataset.videoSource)}/${encodeURIComponent(button.dataset.videoId)}/video-access`;
async function auditVideoAccess(button,action,outcome){return api(accessPath(button),{method:"POST",body:JSON.stringify({action,outcome})})}
async function openVideoContext(button){document.querySelector(".kr-video-modal")?.remove();const modal=document.createElement("div");modal.className="kr-video-modal";modal.innerHTML='<section><h3>Video συμβάντος</h3><p>Φόρτωση ασφαλούς πλαισίου…</p><button type="button" data-video-close>Κλείσιμο</button></section>';document.body.appendChild(modal);try{const data=await api(`/api/reports/audit-events/${encodeURIComponent(button.dataset.videoSource)}/${encodeURIComponent(button.dataset.videoId)}/video-context`),item=data.event||{},window=data.clipWindow||{};if(item.id)await auditVideoAccess(button,"VIEW",data.realVideoOpened?"OPENED":"CONTEXT_ONLY");modal.querySelector("section").innerHTML=`<h3>Video συμβάντος</h3>${data.available?`<dl><dt>Κατάστημα</dt><dd>${esc(item.storeName)}</dd><dt>POS</dt><dd>${esc(item.terminalPos)}</dd><dt>Χειριστής</dt><dd>${esc(item.operatorName||"—")}</dd><dt>Ώρα NVR</dt><dd>${fmt(item.nvrEventAt)}</dd><dt>Κάμερα</dt><dd>${esc(item.cameraName||item.cameraKey)}</dd><dt>Παράθυρο clip</dt><dd>30″ πριν · 60″ μετά<br><small>${fmt(window.startAt)} — ${fmt(window.endAt)}</small></dd></dl>${data.clipSupported?'<div class="kr-video-ready">Ο adapter δηλώνει δυνατότητα clip.</div>':`<div class="kr-video-unavailable">${esc(data.clipReason)}</div>`}`:`<div class="kr-video-unavailable">${esc(data.reason)}</div>`}<p>Δεν άνοιξε πραγματικό video και δεν δημιουργήθηκε clip σε αυτό το στάδιο.</p>${data.vendorClientFallback?.launchUrl?`<a class="kr-video-ready" href="${esc(data.vendorClientFallback.launchUrl)}" target="_blank" rel="noopener noreferrer">Άνοιγμα vendor client στη σωστή κάμερα και ώρα</a>`:""}${item.id?`<button type="button" class="kr-video-export" data-video-export data-video-source="${esc(button.dataset.videoSource)}" data-video-id="${esc(button.dataset.videoId)}">Καταγραφή αιτήματος εξαγωγής</button>`:""}<button type="button" data-video-close>Κλείσιμο</button>`}catch(error){modal.querySelector("p").textContent=error.message}}
function endpoint(mode){if(mode==="sale-deletions")return"sale-deletions";if(mode==="deactivations")return"deactivations";return"audit-events"}
async function load(root,mode){root.dataset.auditTab=mode;root.querySelectorAll("[data-kr-tab]").forEach(b=>b.classList.toggle("active",b.dataset.krTab===mode));removeOld(root);const toolbar=root.querySelector(".kr-toolbar");const holder=document.createElement("div");holder.className="kr-error";holder.textContent="Φόρτωση…";toolbar?.before(holder);try{let data=await api(`/api/reports/${endpoint(mode)}?${params(root)}`);if(mode==="audit-events")data=await mergeOnlineOrderEvents(root,data);holder.outerHTML=mode==='sale-deletions'?deletionView(data):mode==='deactivations'?deactivationView(data):auditView(data)}catch(e){holder.textContent=e.message}}
function exportCsv(mode){if(!currentItems.length)return alert("Δεν υπάρχουν δεδομένα για εξαγωγή.");const keys=Object.keys(currentItems[0]).filter(k=>typeof currentItems[0][k]!=="object"),csv="\ufeff"+[keys.join(";"),...currentItems.map(r=>keys.map(k=>`"${String(r[k]??"").replace(/"/g,'""')}"`).join(";"))].join("\r\n"),a=document.createElement("a");a.href=URL.createObjectURL(new Blob([csv],{type:"text/csv;charset=utf-8"}));a.download=`anafores-${mode}.csv`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
function ensureAuditTab(root){if(!root||root.querySelector('[data-kr-tab="audit-events"]'))return;const groups=root.querySelectorAll(".kr-tabs");const target=groups[groups.length-1]||groups[0];if(!target)return;const button=document.createElement("button");button.type="button";button.dataset.krTab="audit-events";button.textContent="🛡 Συμβάντα / Audit";target.appendChild(button)}
function ensureVideoFilters(root){const filter=root.querySelector(".kr-filter>div");if(!filter||filter.querySelector("[data-video-filter]"))return;const options=[['timeFrom','Ώρα από','time'],['timeTo','Ώρα έως','time'],['operatorId','Χειριστής / ID','text'],['terminalPos','POS','text'],['eventType','Συμβάν','text'],['amountMin','Ποσό από','number'],['amountMax','Ποσό έως','number']];for(const [name,label,type] of options){const field=document.createElement("label");field.className="video-audit-filter";field.innerHTML=`${label}<input type="${type}" data-video-filter="${name}" ${type==='number'?'step="0.01"':''}/>`;filter.appendChild(field)}}
function scan(){document.querySelectorAll(".kiosk-reports-suite").forEach(ensureAuditTab)}
export function installKioskReportsAuditV2(){
  if(window.__mwsKioskReportsAuditV2)return;window.__mwsKioskReportsAuditV2=true;
  if(document.readyState==="loading")window.addEventListener("DOMContentLoaded",scan,{once:true});
  else scan();
  document.addEventListener("click",event=>{
    const root=event.target.closest(".kiosk-reports-suite");if(!root)return;ensureAuditTab(root);
    const tab=event.target.closest("[data-kr-tab]");
    if(tab){const mode=tab.dataset.krTab;if(mode==="sale-deletions"||mode==="deactivations"||mode==="audit-events"){event.preventDefault();event.stopImmediatePropagation();if(mode==="audit-events")ensureVideoFilters(root);load(root,mode);return}delete root.dataset.auditTab;currentItems=[];return}
    const mode=root.dataset.auditTab;if(!mode)return;
    const videoButton=event.target.closest("[data-video-id]");if(videoButton){event.preventDefault();event.stopImmediatePropagation();openVideoContext(videoButton);return}
    if(event.target.closest("[data-kr-search]")||event.target.closest("[data-kr-refresh]")){event.preventDefault();event.stopImmediatePropagation();load(root,mode);return}
    if(event.target.closest("[data-kr-export]")){event.preventDefault();event.stopImmediatePropagation();exportCsv(mode);return}
  },true);
  document.addEventListener("click",async event=>{const exportButton=event.target.closest("[data-video-export]");if(exportButton){exportButton.disabled=true;try{await auditVideoAccess(exportButton,"EXPORT","UNAVAILABLE");alert("Το αίτημα εξαγωγής καταγράφηκε στο Audit. Δεν δημιουργήθηκε αρχείο χωρίς πραγματικό adapter NVR.")}catch(error){alert(error.message)}finally{exportButton.disabled=false}return}if(event.target.closest("[data-video-close]")||event.target.classList.contains("kr-video-modal"))event.target.closest(".kr-video-modal")?.remove()});
}
