const allowed=()=>{try{return ["SUPER_ADMIN","OWNER","ADMIN","MANAGER"].includes(JSON.parse(localStorage.getItem("user")||"{}").role)}catch{return false}};
const esc=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]));
const n=v=>Number(v||0),money=v=>n(v).toLocaleString("el-GR",{style:"currency",currency:"EUR",minimumFractionDigits:2}),num=v=>n(v).toLocaleString("el-GR",{minimumFractionDigits:0,maximumFractionDigits:3}),pct=v=>`${n(v).toLocaleString("el-GR",{minimumFractionDigits:2,maximumFractionDigits:2})}%`;
const pad=v=>String(v).padStart(2,"0"),dateOnly=d=>`${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}`,fmt=v=>v?new Date(v).toLocaleString("el-GR"):"—";
const today=()=>dateOnly(new Date()),monthAgo=()=>{const d=new Date();d.setDate(d.getDate()-30);return dateOnly(d)};
const movementLabel=value=>({RECIPE_CONSUMPTION:"Ανάλωση συνταγής",MANUAL_ADJUSTMENT:"Χειροκίνητη διόρθωση αποθέματος",PURCHASE:"Αγορά",SALE:"Πώληση",RETURN:"Επιστροφή",WASTE:"Φύρα",STOCKTAKE:"Απογραφή"}[String(value||"").toUpperCase()]||String(value||"—"));
const documentLabel=value=>({SALE:"Πώληση",NON_FISCAL_SALE:"Μη φορολογική πώληση",PURCHASE:"Αγορά",RETURN:"Επιστροφή"}[String(value||"").toUpperCase()]||String(value||"—"));
const statusLabel=value=>({COMPLETED:"Ολοκληρωμένο",ACTIVE:"Ενεργό",CANCELLED:"Ακυρωμένο",DRAFT:"Πρόχειρο",APPROVED:"Εγκεκριμένο",FINALIZED:"Οριστικοποιημένο"}[String(value||"").toUpperCase()]||String(value||"—"));
const state={active:false,tab:"destructions",from:monthAgo(),to:today(),storeId:"",q:"",stores:[],data:{items:[]},availability:null};
const tabs1=[["sale-deletions","🗑 Διαγραφές λίστας πώλησης"],["price-changes","▣ Αλλαγές τιμών"],["deactivations","⛔ Απενεργοποιήσεις ειδών"],["fiscal-z","◴ Ζ Ταμειακής"],["movements","☷ Χρονολόγιο κινήσεων ειδών"],["departments","▤ Αναφορά τμημάτων"],["delivery","▣ Διανομή"]];
const tabs2=[["documents","▤ Παραστατικά"],["stocktakes","⚑ Απογραφές"],["destructions","✖ Καταστροφές"],["stock-snapshot","▣ Στιγμιότυπα αποθήκης"],["item-snapshot","▣ Στιγμιότυπα αποθήκης ανά είδος"],["stock-stats","▥ Στατιστικά αποθήκης"],["sales-stats","▧ Στατιστικά πωλήσεων"],["z","▣ Ζ"],["logins","⌂ Συνδέσεις"],["audit-events","🛡 Συμβάντα / Audit"]];
const realEndpoint={"price-changes":"price-changes",movements:"movements",departments:"departments",documents:"documents",stocktakes:"stocktakes",destructions:"destructions","stock-snapshot":"stock-snapshot","item-snapshot":"stock-snapshot","stock-stats":"stock-stats",logins:"logins"};
async function api(path){const token=localStorage.getItem("token"),r=await fetch(path,{headers:{...(token?{Authorization:`Bearer ${token}`}:{})}}),d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||`Σφάλμα ${r.status}`);return d}
function nativeVisibility(hub,hide){[...hub.children].forEach((child,index)=>{if(index===0||child.classList.contains("kiosk-reports-suite"))return;child.classList.toggle("reports-native-hidden",hide)})}
function qs(){return new URLSearchParams({from:state.from,to:state.to,...(state.storeId?{storeId:state.storeId}:{}),...(state.q?{q:state.q}:{})})}
function buttons(rows){return `<div class="kr-tabs">${rows.map(([id,label])=>`<button type="button" data-kr-tab="${id}" class="${state.tab===id?"active":""}">${label}</button>`).join("")}</div>`}
function filters(){return `<section class="kr-filter"><b>Κριτήρια αναζήτησης</b><div><label>Από<input type="date" data-kr-from value="${state.from}"></label><label>Έως και<input type="date" data-kr-to value="${state.to}"></label><label>Είδος / Περιγραφή / SKU<input data-kr-q value="${esc(state.q)}"></label><label>Κατάστημα<select data-kr-store><option value="">Όλα τα καταστήματα</option>${state.stores.map(s=>`<option value="${esc(s.id)}" ${state.storeId===s.id?"selected":""}>${esc(s.name)}</option>`).join("")}</select></label><button data-kr-search>🔍 Αναζήτηση</button></div></section>`}
const head=cells=>`<div class="kr-row kr-head">${cells.map(x=>`<span>${x}</span>`).join("")}</div>`;
const row=cells=>`<div class="kr-row">${cells.map(x=>`<span>${x}</span>`).join("")}</div>`;
function empty(text="Δεν βρέθηκαν εγγραφές."){return `<div class="kr-empty">${esc(text)}</div>`}
function unavailable(reason){return `<section class="kr-unavailable"><strong>Δεν υπάρχει ακόμη πραγματική πηγή για αυτή την αναφορά.</strong><p>${esc(reason||"Η λειτουργία θα ενεργοποιηθεί όταν υπάρχει ασφαλή δεδομένα καταγραφής συμβάντων.")}</p></section>`}
function destructionTable(){const d=state.data,items=d.items||[];return `<section class="kr-panel"><h3>Καταστροφές</h3><div class="kr-table destructions">${head(["Ημερομηνία","Εσωτ. κωδικός","Περιγραφή είδους","Ποσότητα","Τιμή αγοράς","Σύνολο αγοράς","Λιανική","Χειριστής","Κατηγορία","Υποκατηγορία","Προμηθευτής","Κατάστημα"])}${items.map(r=>row([fmt(r.createdAt),esc(r.sku||"—"),`<b>${esc(r.name)}</b>`,num(r.quantity),`<b>${money(r.purchasePrice)}</b>`,`<strong class="kr-total">${money(r.purchaseTotal)}</strong>`,money(r.salePrice),esc(r.operatorName||"—"),esc(r.categoryName||"—"),esc(r.subcategoryName||"—"),esc(r.supplierName||"—"),esc(r.storeName||"—")])).join("")||empty()}</div><div class="kr-summary"><span>${items.length} εγγραφές</span><strong>Ποσότητα: ${num(d.totalQuantity)}</strong><strong>Σύνολο αγοράς: ${money(d.totalPurchase)}</strong></div></section>`}
function priceChanges(){const items=state.data.items||[];return `<section class="kr-panel"><h3>Αλλαγές τιμών</h3><div class="kr-table changes">${head(["Ημερομηνία","Περιγραφή είδους","Εσωτ. κωδικός","BARCODE","Παλαιά λιανική","Νέα λιανική","Διαφορά €","Διαφορά %","Υποκατηγορία","Χειριστής","Κατάστημα"])}${items.map(r=>row([fmt(r.createdAt),`<b>${esc(r.name)}</b>`,esc(r.sku||"—"),esc(r.barcode||"—"),money(r.oldPrice),`<strong>${money(r.newPrice)}</strong>`,`<strong class="${n(r.difference)>=0?"kr-price-up":"kr-price-down"}">${n(r.difference)>=0?"+":""}${money(r.difference)}</strong>`,r.differencePercent===null?"—":`<strong class="${n(r.difference)>=0?"kr-price-up":"kr-price-down"}">${n(r.differencePercent)>=0?"+":""}${pct(r.differencePercent)}</strong>`,esc(r.subcategoryName||"—"),esc(r.operatorName||"—"),esc(r.storeName||"Όλα")])).join("")||empty()}</div><div class="kr-summary"><span>${items.length} αλλαγές</span><em>Οι αλλαγές τιμής αγοράς εμφανίζονται μόνο όταν υπάρχει πραγματικό purchase-cost audit.</em></div></section>`}
function movements(){const items=state.data.items||[];return `<section class="kr-panel"><h3>Χρονολόγιο κινήσεων ειδών</h3><div class="kr-table movements">${head(["Ημερομηνία","Κίνηση","Περιγραφή είδους","Εσωτ. κωδικός","IN","OUT","Αγορά","Λιανική","Χειριστής","Κατάστημα"])}${items.map(r=>row([fmt(r.createdAt),esc(movementLabel(r.movementType)),`<b>${esc(r.name)}</b>`,esc(r.sku||"—"),num(r.inQty),num(r.outQty),money(r.unitCost),money(r.salePrice),esc(r.operatorName||"—"),esc(r.storeName||"—")])).join("")||empty()}</div><div class="kr-summary"><span>${items.length} κινήσεις</span></div></section>`}
function stocktakes(){const d=state.data,items=d.items||[];return `<section class="kr-panel"><h3>Απογραφές</h3><div class="kr-table stocktakes">${head(["Ημερομηνία","Απογραφή","Ενεργό","Κατηγορία","Περιγραφή","Διαφορά (Τμχ)","Διαφορά (€)","Παλαιά Ποσότητα","Νέα Ποσότητα","Λιανική","Τιμή αγοράς","Χειριστής","Κατάστημα"])}${items.map(r=>row([fmt(r.countedAt||r.finalizedAt||r.startedAt),esc(r.stocktakeName),r.status==="FINALIZED"?"✓":"…",esc(r.categoryName||"—"),`<b>${esc(r.name)}</b>`,r.difference===null?"—":num(r.difference),r.differenceValue===null?"—":money(r.differenceValue),num(r.expectedQuantity),r.countedQuantity===null?"—":num(r.countedQuantity),money(r.salePrice),money(r.unitCost),esc(r.operatorName||"—"),esc(r.storeName||"—")])).join("")||empty()}</div><div class="kr-summary"><span>${items.length} γραμμές</span><strong>Συνολική διαφορά αξίας: ${money(d.totalDifferenceValue)}</strong></div></section>`}
function snapshot(){const d=state.data,items=d.items||[];return `<section class="kr-panel"><h3>${state.tab==="item-snapshot"?"Στιγμιότυπο αποθήκης ανά είδος":"Στιγμιότυπο αποθήκης"}</h3><div class="kr-info">Υπολογισμός από το πραγματικό StockMovement ledger έως ${fmt(d.snapshotAt)}.</div><div class="kr-table snapshot">${head(["Κατηγορία","Υποκατηγορία","Περιγραφή","Αποθήκη","Λιανική","Τιμή αγοράς","Αξία λιανικής","Κόστος","Margin","Προμηθευτής","Κατάστημα"])}${items.map(r=>row([esc(r.categoryName||"—"),esc(r.subcategoryName||"—"),`<b>${esc(r.name)}</b>`,num(r.quantity),money(r.salePrice),money(r.purchasePrice),money(r.saleValue),money(r.costValue),pct(r.marginNet),esc(r.supplierName||"—"),esc(r.storeName||"—")])).join("")||empty()}</div><div class="kr-summary"><span>${items.length} γραμμές</span><strong>Αξία λιανικής: ${money(d.totalSaleValue)}</strong><strong>Κόστος: ${money(d.totalCostValue)}</strong></div></section>`}
function stockStats(){const items=state.data.items||[];return `<section class="kr-panel"><h3>Στατιστικά αποθήκης</h3><div class="kr-table stats">${head(["Κατηγορία","Υποκατηγορία","Περιγραφή είδους","Λιανική","Αποθήκη","Πωλήσεις διαστήματος","Τελευταία πώληση","Τελευταία αγορά","Τιμή αγοράς","Αξία αγοράς","Βασικός προμηθευτής","Κατάστημα"])}${items.map(r=>row([esc(r.categoryName||"—"),esc(r.subcategoryName||"—"),`<b>${esc(r.name)}</b>`,money(r.salePrice),num(r.currentStock),num(r.salesQuantity),fmt(r.lastSaleAt),fmt(r.lastPurchaseAt),money(r.purchasePrice),money(r.currentCostValue),esc(r.supplierName||"—"),esc(r.storeName||"—")])).join("")||empty()}</div><div class="kr-summary"><span>${items.length} είδη</span></div></section>`}
function departments(){const d=state.data,items=d.items||[];return `<section class="kr-panel"><h3>Αναφορά τμημάτων</h3><div class="kr-info">${esc(d.note||"")}</div><div class="kr-table departments">${head(["Τμήμα ΦΠΑ","Κατηγορία","Ποσότητα","Αξία χωρίς ΦΠΑ","ΦΠΑ","Σύνολο","% ΦΠΑ"])}${items.map(r=>row([num(r.vatRate),esc(r.categoryName),num(r.quantity),money(r.netValue),money(r.vatValue),money(r.grossValue),pct(r.vatRate)])).join("")||empty()}</div><div class="kr-summary"><strong>Σύνολο: ${money(items.reduce((a,r)=>a+n(r.grossValue),0))}</strong></div></section>`}
function documents(){const d=state.data,items=d.items||[];return `<section class="kr-panel"><h3>Παραστατικά</h3>${d.fiscalSales===false?'<div class="kr-info">Οι πωλήσεις MyWorkStation εδώ είναι διοικητικές / μη φορολογικές μέχρι πραγματική σύνδεση Connector.</div>':''}<div class="kr-table docs">${head(["Ημερομηνία","Τύπος","Παραστατικό","Αριθμός","Συναλλασσόμενος","ΑΦΜ","Καθαρή αξία","ΦΠΑ","Σύνολο","Κατάσταση","Κατάστημα"])}${items.map(r=>row([fmt(r.date),esc(documentLabel(r.kind)),esc(documentLabel(r.documentType)),esc(r.documentNumber||"—"),esc(r.partyName||"—"),esc(r.taxId||"—"),money(r.totalNet),money(r.totalVat),money(r.totalGross),esc(statusLabel(r.status)),esc(r.storeName||"—")])).join("")||empty()}</div><div class="kr-summary"><span>${items.length} παραστατικά</span></div></section>`}
function logins(){const items=state.data.items||[];return `<section class="kr-panel"><h3>Συνδέσεις</h3><div class="kr-table logins">${head(["Ημερομηνία","Χρήστης","Email","Ρόλος","Συμβάν","Επιτυχία","Συσκευή","IP"])}${items.map(r=>row([fmt(r.createdAt),esc(r.fullName||"—"),esc(r.email),esc(r.role||"—"),esc(r.event),r.success?"ΝΑΙ":"ΟΧΙ",esc(r.deviceName||"—"),esc(r.ipAddress||"—")])).join("")||empty()}</div><div class="kr-summary"><span>${items.length} συμβάντα</span></div></section>`}
function tableContent(){if(state.tab==="destructions")return destructionTable();if(state.tab==="price-changes")return priceChanges();if(state.tab==="movements")return movements();if(state.tab==="stocktakes")return stocktakes();if(state.tab==="stock-snapshot"||state.tab==="item-snapshot")return snapshot();if(state.tab==="stock-stats")return stockStats();if(state.tab==="departments")return departments();if(state.tab==="documents")return documents();if(state.tab==="logins")return logins();if(state.tab==="sales-stats")return unavailable("Χρησιμοποίησε την υπάρχουσα Ανάλυση Πωλήσεων, η οποία διαβάζει τα πραγματικά δεδομένα πωλήσεων χωρίς διπλό report engine.");if(state.tab==="delivery")return unavailable("Η αναφορά delivery θα συνδεθεί μόνο με πραγματικά delivery/provider events.");const a=state.availability||{};if(state.tab==="sale-deletions")return unavailable(a.saleListDeletions?.reason);if(state.tab==="deactivations")return unavailable(a.productDeactivations?.reason);return unavailable(a.fiscalZ?.reason)}
function toolbar(){return `<div class="kr-toolbar"><button data-kr-close>✕ Κλείσιμο</button><button data-kr-refresh>↻ Ανανέωση</button><button data-kr-export>Excel / CSV</button><button data-kr-print>PDF / Εκτύπωση</button></div>`}
function render(root){root.innerHTML=`${buttons(tabs1)}${buttons(tabs2)}${filters()}${tableContent()}${toolbar()}`;bind(root)}
async function load(root){try{const endpoint=realEndpoint[state.tab];if(!endpoint){if(!state.availability)state.availability=await api("/api/reports/availability");state.data={items:[]};return render(root)}const query=qs();state.data=await api(`/api/reports/${endpoint}?${query}`);render(root)}catch(e){root.innerHTML=`${buttons(tabs1)}${buttons(tabs2)}${filters()}<div class="kr-error">${esc(e.message)}</div>${toolbar()}`;bind(root)}}
function csvRows(){return state.data?.items||[]}
function exportCsv(){const rows=csvRows();if(!rows.length)return alert("Δεν υπάρχουν δεδομένα για εξαγωγή.");const keys=Object.keys(rows[0]).filter(k=>typeof rows[0][k]!=="object"),csv="\ufeff"+[keys.join(";"),...rows.map(r=>keys.map(k=>`"${String(r[k]??"").replace(/"/g,'""')}"`).join(";"))].join("\r\n"),a=document.createElement("a");a.href=URL.createObjectURL(new Blob([csv],{type:"text/csv;charset=utf-8"}));a.download=`anafores-${state.tab}-${today()}.csv`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
function bind(root){root.querySelectorAll("[data-kr-tab]").forEach(b=>b.onclick=()=>{state.tab=b.dataset.krTab;if(state.tab==="item-snapshot"&&!state.q)state.q="";load(root)});root.querySelector("[data-kr-search]")?.addEventListener("click",()=>{state.from=root.querySelector("[data-kr-from]").value;state.to=root.querySelector("[data-kr-to]").value;state.q=root.querySelector("[data-kr-q]").value.trim();state.storeId=root.querySelector("[data-kr-store]").value;load(root)});root.querySelector("[data-kr-refresh]")?.addEventListener("click",()=>load(root));root.querySelector("[data-kr-export]")?.addEventListener("click",exportCsv);root.querySelector("[data-kr-print]")?.addEventListener("click",()=>window.print());root.querySelector("[data-kr-close]")?.addEventListener("click",()=>{const hub=root.closest(".commerce-hub"),btn=hub?.querySelector("[data-kiosk-reports-launch]");if(hub&&btn)deactivate(hub,btn)})}
async function activate(hub,button){state.active=true;nativeVisibility(hub,true);button.classList.add("active");let root=hub.querySelector(".kiosk-reports-suite");if(!root){root=document.createElement("section");root.className="kiosk-reports-suite";hub.firstElementChild?.after(root)}root.hidden=false;try{const l=await api("/api/reports/lookups");state.stores=l.stores||[]}catch{}render(root);load(root)}
function deactivate(hub,button){state.active=false;button.classList.remove("active");hub.querySelector(".kiosk-reports-suite")?.setAttribute("hidden","");nativeVisibility(hub,false)}
export function installKioskReportsSuite(){if(!allowed())return;document.querySelectorAll(".commerce-hub").forEach(hub=>{const strip=hub.querySelector(".commerce-module-strip");if(!strip)return;let btn=strip.querySelector("[data-kiosk-reports-launch]");if(!btn){btn=document.createElement("button");btn.type="button";btn.dataset.kioskReportsLaunch="1";btn.textContent="📊 Αναφορές";strip.appendChild(btn);btn.addEventListener("click",()=>activate(hub,btn));[...strip.querySelectorAll("button")].filter(x=>x!==btn).forEach(other=>other.addEventListener("click",()=>deactivate(hub,btn)))}if(state.active&&!hub.querySelector(".kiosk-reports-suite:not([hidden])"))activate(hub,btn)})}
