const canUse=()=>{try{return ["SUPER_ADMIN","OWNER","ADMIN","MANAGER"].includes(JSON.parse(localStorage.getItem("user")||"{}").role)}catch{return false}};
const pending=new WeakMap();
const esc=value=>String(value??"").replace(/[&<>"']/g,ch=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[ch]));
const eur=value=>Number(value||0).toLocaleString("el-GR",{style:"currency",currency:"EUR"});
const day=value=>new Date(value).toLocaleDateString("el-GR",{day:"2-digit",month:"2-digit",year:"numeric"});
const style=()=>{if(document.getElementById("kiosk-payments-import-style"))return;const el=document.createElement("style");el.id="kiosk-payments-import-style";el.textContent=`.owner-kiosk-import{border:1px solid #0ea5e9!important;background:#e9f8ff!important;color:#075985!important;font-weight:900!important}.owner-kiosk-import:hover{background:#d8f3ff!important}.owner-kiosk-import-status,.owner-kiosk-preview{margin:8px 0;padding:10px 12px;border:1px solid #bfe5f5;background:#f2fbff;border-radius:9px;color:#17445b;font-size:12px}.owner-kiosk-import-status.error{border-color:#f2b8b5;background:#fff5f5;color:#9d1c1c}.owner-kiosk-import-status b{display:block;margin-bottom:3px}.owner-kiosk-preview h3{margin:0 0 8px;color:#0f3654}.owner-kiosk-preview-summary{display:grid;grid-template-columns:repeat(5,minmax(120px,1fr));gap:7px}.owner-kiosk-preview-summary span{background:#fff;border:1px solid #d6e7f1;border-radius:7px;padding:7px}.owner-kiosk-preview-summary b{display:block;font-size:14px}.owner-kiosk-preview-table{margin-top:8px;overflow:auto;max-height:240px;background:#fff;border:1px solid #d6e7f1;border-radius:7px}.owner-kiosk-preview-row{display:grid;grid-template-columns:105px 120px 130px 1fr 115px;min-width:760px;border-bottom:1px solid #e5edf3}.owner-kiosk-preview-row>*{padding:6px 8px}.owner-kiosk-preview-row.head{background:#176fc6;color:#fff;font-weight:900;position:sticky;top:0}.owner-kiosk-preview-actions{display:flex;justify-content:flex-end;gap:8px;margin-top:9px}.owner-kiosk-preview-actions button{padding:8px 12px;border-radius:7px;border:1px solid #cbd9e5;background:#fff;font-weight:900;cursor:pointer}.owner-kiosk-preview-actions .confirm{background:#0b7a4b;color:#fff;border-color:#0b7a4b}@media(max-width:900px){.owner-kiosk-preview-summary{grid-template-columns:1fr 1fr}}`;document.head.appendChild(el)};
const readBase64=file=>new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result||"").split(",")[1]||"");reader.onerror=()=>reject(new Error("Δεν διαβάστηκε το αρχείο."));reader.readAsDataURL(file)});
async function post(path,body){const token=localStorage.getItem("token");const response=await fetch(path,{method:"POST",headers:{"Content-Type":"application/json",...(token?{Authorization:`Bearer ${token}`}:{})},body:JSON.stringify(body)});const data=await response.json().catch(()=>({}));if(!response.ok)throw new Error(data.error||`Σφάλμα ${response.status}`);return data}
function status(root,message,error=false){let box=root.querySelector(".owner-kiosk-import-status");if(!box){box=document.createElement("div");box.className="owner-kiosk-import-status";root.querySelector(".owner-payments-filter")?.after(box)}box.classList.toggle("error",error);box.innerHTML=message}
function clearStatus(root){root.querySelector(".owner-kiosk-import-status")?.remove();root.querySelector(".owner-kiosk-preview")?.remove()}
function showPreview(root,result){
  clearStatus(root);const box=document.createElement("section");box.className="owner-kiosk-preview";const s=result.summary||{};
  box.innerHTML=`<h3>Προεπισκόπηση Kiosk — καμία εγγραφή δεν έχει αποθηκευτεί</h3><div class="owner-kiosk-preview-summary"><span>Κινήσεις<b>${s.count||0}</b></span><span>Σύνολο<b>${eur(s.total)}</b></span><span>Προμηθευτές<b>${eur(s.supplierTotal)}</b><small>${s.supplierCount||0} κινήσεις</small></span><span>Λοιπά έξοδα<b>${eur(s.otherTotal)}</b><small>${s.otherCount||0} κινήσεις</small></span><span>Περίοδος<b>${day(s.dateFrom)} – ${day(s.dateTo)}</b><small>${result.skipped||0} γραμμές αγνοούνται</small></span></div><div class="owner-kiosk-preview-table"><div class="owner-kiosk-preview-row head"><span>Ημερομηνία</span><span>Τύπος</span><span>Ποσό</span><span>Προμηθευτής / περιγραφή</span><span>Παραστατικό</span></div>${(result.sample||[]).map(row=>`<div class="owner-kiosk-preview-row"><span>${day(row.occurredAt)}</span><span>${row.type==="SUPPLIER_PAYMENT"?"Προμηθευτής":"Λοιπό έξοδο"}</span><strong>${eur(row.amount)}</strong><span>${esc(row.supplierName||row.description||"—")}</span><span>${esc(row.sourceRef||"—")}</span></div>`).join("")}</div><div class="owner-kiosk-preview-actions"><button data-kiosk-cancel>Ακύρωση</button><button class="confirm" data-kiosk-confirm>✓ Οριστική εισαγωγή ${s.count||0} κινήσεων</button></div>`;
  root.querySelector(".owner-payments-filter")?.after(box);
  box.querySelector("[data-kiosk-cancel]")?.addEventListener("click",()=>{pending.delete(root);box.remove()});
  box.querySelector("[data-kiosk-confirm]")?.addEventListener("click",()=>commit(root,box.querySelector("[data-kiosk-confirm]")));
}
async function commit(root,button){const data=pending.get(root);if(!data)return;button.disabled=true;button.textContent="Οριστική εισαγωγή…";try{const result=await post("/api/owner-payments/import-kiosk",data);pending.delete(root);root.querySelector(".owner-kiosk-preview")?.remove();status(root,`<b>${esc(result.message)}</b>Βρέθηκαν ${result.found} · εισήχθησαν ${result.inserted} · διπλές ${result.duplicates} · αγνοήθηκαν ${result.skipped}. Οι κινήσεις σημειώνονται ως «Kiosk · …», δεν αφαιρούνται από καμία βάρδια και δεν επηρεάζουν το ταμείο.`);root.querySelector("[data-op-search]")?.click()}catch(error){status(root,`<b>Η οριστική εισαγωγή δεν ολοκληρώθηκε.</b>${esc(error.message||error)}`,true);button.disabled=false;button.textContent="✓ Οριστική εισαγωγή"}}
function install(root){
  if(!canUse())return;const actions=root.querySelector(".owner-payments-filter-actions");if(!actions||actions.dataset.kioskImportBound)return;actions.dataset.kioskImportBound="1";style();
  const button=document.createElement("button");button.type="button";button.className="owner-kiosk-import";button.textContent="⬆ Εισαγωγή Kiosk Excel / CSV";const input=document.createElement("input");input.type="file";input.accept=".xlsx,.xls,.csv";input.hidden=true;actions.append(button,input);button.addEventListener("click",()=>input.click());
  input.addEventListener("change",async()=>{const file=input.files?.[0];if(!file)return;const storeId=root.querySelector("[data-op-store]")?.value||"";if(!storeId){status(root,"<b>Επίλεξε πρώτα συγκεκριμένο κατάστημα.</b>Η εισαγωγή δεν γίνεται με «Όλα τα καταστήματα».",true);input.value="";return}if(!/\.(xlsx|xls|csv)$/i.test(file.name)){status(root,"<b>Μη υποστηριζόμενο αρχείο.</b>Χρησιμοποίησε Excel .xlsx/.xls ή CSV export από Kiosk Manager.",true);input.value="";return}if(file.size>8*1024*1024){status(root,"<b>Το αρχείο είναι πολύ μεγάλο.</b>Το όριο είναι 8 MB.",true);input.value="";return}button.disabled=true;button.textContent="Προεπισκόπηση…";clearStatus(root);status(root,"<b>Διαβάζω το export Kiosk χωρίς αποθήκευση.</b>Θα ζητηθεί επιβεβαίωση πριν γραφτεί οποιαδήποτε κίνηση.");try{const dataBase64=await readBase64(file),payload={storeId,filename:file.name,dataBase64},result=await post("/api/owner-payments/preview-kiosk",payload);pending.set(root,payload);showPreview(root,result)}catch(error){status(root,`<b>Η προεπισκόπηση δεν ολοκληρώθηκε.</b>${esc(error.message||error)}`,true)}finally{button.disabled=false;button.textContent="⬆ Εισαγωγή Kiosk Excel / CSV";input.value=""}});
}
export function installKioskPaymentsImport(){const run=()=>document.querySelectorAll(".owner-payments-suite").forEach(install);run();const observer=new MutationObserver(run);observer.observe(document.documentElement,{childList:true,subtree:true})}
