const allowed=()=>{try{return ["SUPER_ADMIN","OWNER","ADMIN","MANAGER"].includes(JSON.parse(localStorage.getItem("user")||"{}").role)}catch{return false}};
const esc=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]));
const money=v=>Number(v||0).toLocaleString("el-GR",{style:"currency",currency:"EUR"});
const num=v=>Number(v||0),pad=n=>String(n).padStart(2,"0"),dateValue=d=>`${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}`,today=()=>dateValue(new Date()),monthStart=()=>{const d=new Date();return dateValue(new Date(d.getFullYear(),d.getMonth(),1))},yearStart=()=>`${new Date().getFullYear()}-01-01`,fmt=v=>v?new Date(v).toLocaleString("el-GR",{day:"2-digit",month:"2-digit",year:"numeric",hour:"2-digit",minute:"2-digit"}):"—";
const state={tab:"",from:monthStart(),to:today(),supplierId:"",q:"",data:null,busy:false,expanded:"",detail:null};
let bound=false;
async function api(path){const token=localStorage.getItem("token");const r=await fetch(path,{headers:{...(token?{Authorization:`Bearer ${token}`}:{})}});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||`Σφάλμα ${r.status}`);return d}
const tabLabel={invoices:"▤ Τιμολόγια",payments:"💰 Πληρωμές",purchases:"▱ Αγορές",sales:"◉ Πωλήσεις"};
const criteriaTitle={invoices:"Κριτήρια αναζήτησης τιμολογίων",payments:"Κριτήρια αναζήτησης (Ημερομηνία πληρωμής)",purchases:"Κριτήρια αναζήτησης (Ημερομηνία τιμολόγησης)",sales:"Κριτήρια αναζήτησης (Ημερομηνία πωλήσεων)"};
function tabs(){return `<div class="sc-tabs sgr-tabs"><button data-sgr-tab="catalog">▣ Κατάλογος προμηθευτών</button>${["invoices","payments","purchases","sales"].map(id=>`<button data-sgr-tab="${id}" class="${state.tab===id?"active":""}">${tabLabel[id]}</button>`).join("")}</div>`}
function criteria(){const suppliers=state.data?.suppliers||[];return `<section class="sc-filter sgr-filter"><b>${criteriaTitle[state.tab]}</b><div><label>Από<input type="date" data-sgr-from value="${state.from}"></label><label>Έως<input type="date" data-sgr-to value="${state.to}"></label><label>Προμηθευτής<select data-sgr-supplier><option value="">Όλοι οι προμηθευτές</option>${suppliers.map(s=>`<option value="${esc(s.id)}" ${state.supplierId===s.id?"selected":""}>${esc(s.name)}${s.taxId?` · ${esc(s.taxId)}`:""}</option>`).join("")}</select></label>${["invoices","payments"].includes(state.tab)?`<label class="sgr-q">Παρατηρήσεις / παραστατικό<input data-sgr-q value="${esc(state.q)}"></label>`:""}<button data-sgr-search>⌕ Αναζήτηση</button><button data-sgr-month>Τρέχων μήνας</button><button data-sgr-year>Τρέχον έτος</button><button data-sgr-excel>Excel</button></div></section>`}
function invoices(){const d=state.data||{},s=d.summary||{};return `${criteria()}<section class="sc-panel"><div class="sgr-summary"><span>Εγγραφές <b>${s.count||0}</b></span><span>Αξία χωρίς ΦΠΑ <b>${money(s.net)}</b></span><span>ΦΠΑ <b>${money(s.vat)}</b></span><span>Σύνολο <b>${money(s.gross)}</b></span></div><div class="sgr-table invoices"><div class="row head"><span>Ετικέτα</span><span>Τύπος τιμολογίου</span><span>Παραστατικό</span><span>Ημερομηνία</span><span>Επωνυμία</span><span>Κατάστημα</span><span>Χαρακτηρισμός</span><span>Κατηγορία</span><span>Αξία χωρίς ΦΠΑ</span><span>ΦΠΑ</span><span>Σύνολο</span></div>${(d.items||[]).map(r=>`<div class="row"><span>${esc(r.status||"—")}</span><span>${esc(r.documentType||"—")}</span><span><b>${esc(r.documentNumber||"—")}</b></span><span>${fmt(r.documentDate)}</span><span>${esc(r.supplierName||"—")}</span><span>${esc(r.storeName||"—")}</span><span>${esc(r.sourceType||"—")}</span><span>${esc(r.supplierCategory||"—")}</span><strong>${money(r.totalNet)}</strong><strong>${money(r.totalVat)}</strong><strong>${money(r.totalGross)}</strong></div>`).join("")||'<div class="sgr-empty">Δεν υπάρχουν τιμολόγια για τα κριτήρια.</div>'}<div class="row totals"><span>${s.count||0}</span><span></span><span></span><span></span><span></span><span></span><span></span><span></span><strong>${money(s.net)}</strong><strong>${money(s.vat)}</strong><strong>${money(s.gross)}</strong></div></div></section>`}
function payments(){const d=state.data||{},s=d.summary||{};return `${criteria()}<section class="sc-panel"><div class="sgr-summary"><span>Εγγραφές <b>${s.count||0}</b></span><span>Ενεργές πληρωμές <b>${money(s.total)}</b></span><span>Αντιλογισμοί <b>${s.reversed||0}</b></span></div><div class="sgr-table payments"><div class="row head"><span>Ημερομηνία</span><span>ΑΦΜ</span><span>Επωνυμία</span><span>Κατάστημα</span><span>Ποσό</span><span>Απόδειξη</span><span>Παρατηρήσεις</span><span>Καταχωρήθηκε</span><span>Κατάσταση</span></div>${(d.items||[]).map(r=>`<div class="row ${r.reversedAt?"reversed":""}"><span>${fmt(r.occurredAt)}</span><span>${esc(r.taxId||"—")}</span><span><b>${esc(r.supplierName||"—")}</b></span><span>${esc(r.storeName||"—")}</span><strong>${money(r.amount)}</strong><span>${esc(r.attachmentFilename||"—")}</span><span>${esc(r.description||"")}</span><span>${esc(r.actorName||"—")}</span><span>${r.reversedAt?"ΑΝΤΙΛΟΓΙΣΜΟΣ":"ΕΝΕΡΓΗ"}</span></div>`).join("")||'<div class="sgr-empty">Δεν υπάρχουν πληρωμές για τα κριτήρια.</div>'}<div class="row totals"><span></span><span></span><span>${s.count||0}</span><span></span><strong>${money(s.total)}</strong></div></div></section>`}
function purchases(){const d=state.data||{},s=d.summary||{};return `${criteria()}<section class="sc-panel"><div class="sgr-table purchases"><div class="row head"><span>Επωνυμία</span><span>% Συνόλου</span><span>Έκπτωση Τιμ.</span><span>Αξία χωρίς ΦΠΑ</span><span>ΦΠΑ</span><span>Σύνολο με ΦΠΑ</span><span>Παραστατικά</span></div>${(d.items||[]).map(r=>`<div class="row"><span><b>${esc(r.supplierName)}</b></span><strong>${num(r.percentOfTotal).toFixed(2)}%</strong><span>—</span><strong>${money(r.net)}</strong><strong>${money(r.vat)}</strong><strong>${money(r.gross)}</strong><span>${r.documents}</span></div>`).join("")||'<div class="sgr-empty">Δεν υπάρχουν εγκεκριμένες αγορές για τα κριτήρια.</div>'}<div class="row totals"><span>${d.items?.length||0}</span><span>100%</span><span>—</span><strong>${money(s.net)}</strong><strong>${money(s.vat)}</strong><strong>${money(s.gross)}</strong><span>${s.documents||0}</span></div></div></section>`}
function salesDetail(){if(!state.expanded)return"";if(!state.detail)return `<div class="sgr-loading">Φόρτωση ανάλυσης ειδών…</div>`;const rows=state.detail.items||[];return `<div class="sgr-detail"><div class="sgr-detail-head">Ανάλυση ειδών προμηθευτή</div><div class="sgr-detail-table"><div class="row head"><span>Συναλλαγή</span><span>κωδ. τιμολογίου</span><span>εσωτ. κωδικός</span><span>Περιγραφή</span><span>Ποσότητα</span><span>Πωλήσεις</span><span>Μέση πώληση</span><span>Τρέχον Stock</span><span>Τελ. αγορά</span><span>Μέση αγορά</span><span>Κέρδος (τελ.)</span><span>Κέρδος (μέση)</span><span>Margin</span></div>${rows.map(r=>`<div class="row"><span>Πώληση</span><span>${esc(r.supplierCode||"—")}</span><span>${esc(r.sku||"—")}</span><span><b>${esc(r.name)}</b></span><span>${num(r.quantity).toFixed(2)}</span><strong>${money(r.sales)}</strong><span>${money(r.averageSale)}</span><span>${num(r.currentStock).toFixed(2)}</span><span>${money(r.lastCost)}</span><span>${money(r.avgCost)}</span><strong>${money(r.profitWithLast)}</strong><strong>${money(r.profitWithAverage)}</strong><b>${num(r.margin).toFixed(2)}%</b></div>`).join("")||'<div class="sgr-empty">Δεν υπάρχουν είδη για το διάστημα.</div>'}</div></div>`}
function sales(){const d=state.data||{},s=d.summary||{};return `${criteria()}<section class="sc-panel"><div class="sgr-table sales"><div class="row head"><span></span><span>Επωνυμία</span><span>MARGIN</span><span>Πωλήσεις</span><span>Κόστος</span><span>Κέρδος</span><span>% Τζίρου</span><span>ΦΠΑ Πωλήσεων</span><span>Είδη</span></div>${(d.items||[]).map(r=>`<div class="row ${state.expanded===r.supplierId?"selected":""}"><button class="sgr-expand" data-sgr-expand="${esc(r.supplierId)}">${state.expanded===r.supplierId?"−":"＋"}</button><span><b>${esc(r.supplierName)}</b></span><strong>${num(r.margin).toFixed(3)}%</strong><strong>${money(r.sales)}</strong><strong>${money(r.cost)}</strong><strong>${money(r.profit)}</strong><span>${num(r.percentOfSales).toFixed(2)}%</span><strong>${money(r.vatSales)}</strong><span>${r.items}</span></div>${state.expanded===r.supplierId?salesDetail():""}`).join("")||'<div class="sgr-empty">Δεν υπάρχουν πωλήσεις αντιστοιχισμένων ειδών.</div>'}<div class="row totals"><span></span><span>${s.suppliers||0}</span><strong>${num(s.margin).toFixed(3)}%</strong><strong>${money(s.sales)}</strong><strong>${money(s.cost)}</strong><strong>${money(s.profit)}</strong><span>100%</span><strong>${money(s.vatSales)}</strong><span>${s.items||0}</span></div></div></section>`}
function body(){return state.tab==="invoices"?invoices():state.tab==="payments"?payments():state.tab==="purchases"?purchases():sales()}
function render(root){root.innerHTML=tabs()+body();bindRoot(root)}
function params(){const q=new URLSearchParams({from:new Date(`${state.from}T00:00:00`).toISOString(),to:new Date(`${state.to}T23:59:59.999`).toISOString()});if(state.supplierId)q.set("supplierId",state.supplierId);if(state.q&&["invoices","payments"].includes(state.tab))q.set("q",state.q);return q}
async function load(root){state.busy=true;try{state.data=await api(`/api/supplier-control/reports/${state.tab}?${params()}`);render(root)}catch(error){alert(error.message)}finally{state.busy=false}}
async function expand(root,id){if(state.expanded===id){state.expanded="";state.detail=null;render(root);return}state.expanded=id;state.detail=null;render(root);try{state.detail=await api(`/api/supplier-control/reports/sales/${encodeURIComponent(id)}/items?${params()}`);render(root)}catch(error){alert(error.message);state.expanded="";state.detail=null;render(root)}}
function readCriteria(root){state.from=root.querySelector("[data-sgr-from]")?.value||state.from;state.to=root.querySelector("[data-sgr-to]")?.value||state.to;state.supplierId=root.querySelector("[data-sgr-supplier]")?.value||"";state.q=root.querySelector("[data-sgr-q]")?.value||"";state.expanded="";state.detail=null}
function csvRows(){const d=state.data||{};if(state.tab==="invoices")return [["Ημερομηνία","Παραστατικό","Επωνυμία","Κατάστημα","Χωρίς ΦΠΑ","ΦΠΑ","Σύνολο"],...(d.items||[]).map(r=>[fmt(r.documentDate),r.documentNumber,r.supplierName,r.storeName,r.totalNet,r.totalVat,r.totalGross])];if(state.tab==="payments")return [["Ημερομηνία","Επωνυμία","Κατάστημα","Ποσό","Παρατηρήσεις","Χειριστής"],...(d.items||[]).map(r=>[fmt(r.occurredAt),r.supplierName,r.storeName,r.amount,r.description,r.actorName])];if(state.tab==="purchases")return [["Επωνυμία","% Συνόλου","Χωρίς ΦΠΑ","ΦΠΑ","Σύνολο"],...(d.items||[]).map(r=>[r.supplierName,r.percentOfTotal,r.net,r.vat,r.gross])];return [["Επωνυμία","Margin","Πωλήσεις","Κόστος","Κέρδος","% Τζίρου","ΦΠΑ Πωλήσεων","Είδη"],...(d.items||[]).map(r=>[r.supplierName,r.margin,r.sales,r.cost,r.profit,r.percentOfSales,r.vatSales,r.items])]}
function exportCsv(){const csv="\ufeff"+csvRows().map(r=>r.map(v=>`"${String(v??"").replace(/"/g,'""')}"`).join(";")).join("\r\n"),a=document.createElement("a");a.href=URL.createObjectURL(new Blob([csv],{type:"text/csv;charset=utf-8"}));a.download=`promitheftes_${state.tab}_${state.from}_${state.to}.csv`;a.click();URL.revokeObjectURL(a.href)}
function bindRoot(root){root.querySelectorAll("[data-sgr-tab]").forEach(b=>b.onclick=()=>{if(b.dataset.sgrTab==="catalog"){document.querySelector("[data-supplier-control-launch]")?.click();return}state.tab=b.dataset.sgrTab;state.expanded="";state.detail=null;load(root)});root.querySelector("[data-sgr-search]")?.addEventListener("click",()=>{readCriteria(root);load(root)});root.querySelector("[data-sgr-month]")?.addEventListener("click",()=>{state.from=monthStart();state.to=today();state.expanded="";load(root)});root.querySelector("[data-sgr-year]")?.addEventListener("click",()=>{state.from=yearStart();state.to=today();state.expanded="";load(root)});root.querySelector("[data-sgr-excel]")?.addEventListener("click",exportCsv);root.querySelectorAll("[data-sgr-expand]").forEach(b=>b.onclick=()=>expand(root,b.dataset.sgrExpand))}
function intercept(event){const button=event.target.closest?.(".supplier-control-suite .sc-tabs [data-sc-tab]");if(!button||button.dataset.scTab==="catalog")return;event.preventDefault();event.stopImmediatePropagation();event.stopPropagation();const root=button.closest(".supplier-control-suite");state.tab=button.dataset.scTab;state.from=monthStart();state.to=today();state.supplierId="";state.q="";state.expanded="";state.detail=null;root.innerHTML=`${tabs()}<div class="sgr-loading">Φόρτωση…</div>`;load(root)}
export function installSupplierGlobalReports(){if(bound||!allowed())return;bound=true;document.addEventListener("click",intercept,true)}
