const euro=text=>{const raw=String(text||'').replace(/[^0-9,.-]/g,'').replace(/\./g,'').replace(',','.');const n=Number(raw);return Number.isFinite(n)?n:0};
const eur=n=>Number(n||0).toLocaleString('el-GR',{style:'currency',currency:'EUR'});
const dash='<span class="sas-na">—</span>';
const visibleShiftRows=()=>[...document.querySelectorAll('.shift-table .shift-row:not(.head)')].filter(r=>r.style.display!=='none');
const categoryRows=()=>[...document.querySelectorAll('.category-table .category-row:not(.head)')].filter(r=>!r.classList.contains('kiosk-empty'));
const extractCategories=()=>categoryRows().map(row=>{const c=[...row.children];return{name:(c[0]?.textContent||'Χωρίς κατηγορία').trim(),qty:Number((c[1]?.textContent||'0').replace(',','.'))||0,revenue:euro(c[2]?.textContent),profit:euro(c[4]?.textContent),margin:Number((c[5]?.textContent||'0').replace('%','').replace(',','.'))||0}});
const extractShifts=()=>visibleShiftRows().map(row=>{const c=[...row.children];return{operator:(c[0]?.querySelector('b')?.textContent||'Χειριστής').trim(),date:(c[0]?.querySelector('small')?.textContent||'—').trim(),cash:euro(c[2]?.textContent),card:euro(c[3]?.textContent),total:euro(c[4]?.textContent),expenses:euro(c[5]?.textContent),last:(c[6]?.textContent||'—').trim(),average:euro(c[7]?.textContent)}});
const criteria=()=>`<div class="sas-criteria"><div><b>Κριτήρια αναζήτησης</b><small>Τα αποτελέσματα βασίζονται αποκλειστικά στις πραγματικές εγγραφές MyWorkStation που είναι διαθέσιμες τώρα.</small></div><div class="sas-quick"><button data-range="today">Σήμερα</button><button data-range="month">Τρέχων μήνας</button><button data-export>Excel / CSV</button><button onclick="window.print()">Εκτύπωση</button></div></div>`;
const totals=(rows,key)=>rows.reduce((s,r)=>s+Number(r[key]||0),0);
const categoriesPanel=()=>{const rows=extractCategories(),rev=totals(rows,'revenue'),profit=totals(rows,'profit');return `${criteria()}<div class="sas-summary"><span><small>Κατηγορίες</small><b>${rows.length}</b></span><span><small>Πωλήσεις με ΦΠΑ</small><b>${eur(rev)}</b></span><span><small>Κέρδος</small><b>${eur(profit)}</b></span><span><small>Margin</small><b>${rev?(profit/rev*100).toFixed(2):'0.00'}%</b></span></div><div class="sas-table categories"><div class="sas-row head"><span>Περιγραφή</span><span>Πωλήσεις με ΦΠΑ</span><span>Κόστος πωλ.</span><span>Κέρδος</span><span>Margin</span><span>Αγορές με ΦΠΑ</span><span>Ποσότητα</span></div>${rows.map(r=>`<div class="sas-row"><span><b>⊕ ${r.name}</b></span><span>${eur(r.revenue)}</span>${dash}<span>${eur(r.profit)}</span><span>${r.margin.toFixed(2)}%</span>${dash}<span>${r.qty.toLocaleString('el-GR')}</span></div>`).join('')||'<div class="sas-empty">Δεν υπάρχουν ακόμη πραγματικές κατηγορίες πωλήσεων.</div>'}<div class="sas-row total"><span>Σύνολα</span><b>${eur(rev)}</b>${dash}<b>${eur(profit)}</b><b>${rev?(profit/rev*100).toFixed(2):'0.00'}%</b>${dash}<b>${totals(rows,'qty').toLocaleString('el-GR')}</b></div></div><p class="sas-rule">Οι στήλες Κόστος πωληθέντων και Αγορές παραμένουν ορατές και θα γεμίσουν μόλις υπάρχει πραγματική συνδεδεμένη πηγή.</p>`};
const itemsPanel=()=>`${criteria()}<div class="sas-table items"><div class="sas-row head"><span>Κατηγορία</span><span>Υποκατηγορία</span><span>Εταιρεία</span><span>Περιγραφή</span><span>Ποσότητα</span><span>Πωλήσεις με ΦΠΑ</span><span>Κόστος πωλ.</span><span>Κέρδος</span><span>Margin</span><span>Τρέχουσα λιανική</span></div><div class="sas-empty"><b>Η πλήρης ανάλυση ανά είδος είναι έτοιμη ως δομή.</b> Οι γραμμές θα εμφανιστούν μόλις το report endpoint επιστρέφει πραγματικές γραμμές προϊόντων. Δεν δημιουργούνται εικονικές πωλήσεις.</div></div>`;
const journalPanel=()=>{const rows=extractShifts();return `${criteria()}<div class="sas-table journal"><div class="sas-row head"><span>Ημερομηνία</span><span>Χειριστής</span><span>Περιγραφή</span><span>Μετρητά</span><span>Κάρτα / POS</span><span>IRIS</span><span>Προμήθεια POS</span><span>Σύνολο</span><span>Κωδ. βάρδιας</span><span>Κωδ. συναλλαγής</span><span>Πελάτης</span><span>Modifiers</span><span>Τύπος κίνησης</span></div>${rows.map(r=>`<div class="sas-row"><span>${r.date}</span><span><b>${r.operator}</b></span><span>Σύνοψη βάρδιας</span><span>${eur(r.cash)}</span><span>${eur(r.card)}</span>${dash}${dash}<b>${eur(r.total)}</b>${dash}${dash}${dash}${dash}<span>ΠΩΛΗΣΕΙΣ</span></div>`).join('')||'<div class="sas-empty">Δεν υπάρχουν πραγματικές εγγραφές για το ημερολόγιο.</div>'}</div><p class="sas-rule">Το πλήρες ημερολόγιο θα εμπλουτίζεται με transaction id, πελάτη, modifiers, IRIS και προμήθεια POS όταν οι αντίστοιχες πηγές υπάρχουν στην εγγραφή.</p>`};
const resultsPanel=()=>{const cats=extractCategories(),rev=totals(cats,'revenue'),profit=totals(cats,'profit'),qty=totals(cats,'qty');return `${criteria()}<div class="sas-summary"><span><small>Είδη / κατηγορίες</small><b>${cats.length}</b></span><span><small>Ποσότητα</small><b>${qty.toLocaleString('el-GR')}</b></span><span><small>Πωλήσεις με ΦΠΑ</small><b>${eur(rev)}</b></span><span><small>Κέρδος</small><b>${eur(profit)}</b></span><span><small>Margin</small><b>${rev?(profit/rev*100).toFixed(2):'0.00'}%</b></span></div><div class="sas-table results"><div class="sas-row head"><span>Κατηγορία</span><span>Υποκατηγορία</span><span>Κωδικός</span><span>Περιγραφή</span><span>Ποσότητα</span><span>Μέση λιανική</span><span>Πωλήσεις χωρίς ΦΠΑ</span><span>Πωλήσεις με ΦΠΑ</span><span>Αγορά μονάδος</span><span>Συν. αγορών</span><span>Κέρδος</span><span>Margin</span><span>Προμηθευτής</span><span>ΜΜ</span></div>${cats.map(r=>`<div class="sas-row"><span>${r.name}</span>${dash}${dash}<span><b>${r.name}</b></span><span>${r.qty.toLocaleString('el-GR')}</span>${dash}${dash}<span>${eur(r.revenue)}</span>${dash}${dash}<span>${eur(r.profit)}</span><span>${r.margin.toFixed(2)}%</span>${dash}${dash}</div>`).join('')||'<div class="sas-empty">Δεν υπάρχουν ακόμη πραγματικά αποτελέσματα πωλήσεων.</div>'}</div>`};
const render=(root,tab)=>{root.innerHTML=tab==='categories'?categoriesPanel():tab==='items'?itemsPanel():tab==='journal'?journalPanel():resultsPanel();root.querySelector('[data-export]')?.addEventListener('click',()=>exportCsv(tab));};
const exportCsv=tab=>{const panel=document.querySelector('.sas-content');if(!panel)return;const lines=[...panel.querySelectorAll('.sas-row')].map(row=>[...row.children].map(c=>'"'+c.textContent.trim().replace(/"/g,'""')+'"').join(';'));if(!lines.length)return;const blob=new Blob(['\ufeff'+lines.join('\n')],{type:'text/csv;charset=utf-8'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`myworkstation-sales-${tab}.csv`;a.click();URL.revokeObjectURL(a.href)};
const install=()=>{const main=document.querySelector('.kiosk-sales .kiosk-main');if(!main||main.querySelector('.sas-tabs'))return;const subtabs=main.querySelector('.kiosk-subtabs');if(!subtabs)return;const nav=document.createElement('div');nav.className='sas-tabs';nav.innerHTML='<button data-tab="categories">Πωλήσεις, αγορές / κατηγορία</button><button data-tab="items">Πωλήσεις / είδος</button><button data-tab="journal">Ημερολόγιο πωλήσεων</button><button data-tab="results">Αποτελέσματα πωλήσεων</button>';subtabs.parentNode.insertBefore(nav,subtabs);const content=document.createElement('section');content.className='sas-content';content.style.display='none';subtabs.parentNode.insertBefore(content,subtabs.nextSibling);let refreshScheduled=false;const refreshActive=()=>{if(content.style.display==='none')return;const active=nav.querySelector('button.active');if(active)render(content,active.dataset.tab)};nav.addEventListener('click',e=>{const b=e.target.closest('button[data-tab]');if(!b)return;nav.querySelectorAll('button').forEach(x=>x.classList.toggle('active',x===b));subtabs.style.display='none';document.querySelectorAll('.shift-panel,.kiosk-lower-grid,.mws-analytics-tab-content').forEach(x=>x.style.display='none');content.style.display='block';refreshActive()});const observer=new MutationObserver(mutations=>{if(content.style.display==='none')return;const external=mutations.some(m=>!(m.target instanceof Element&&m.target.closest('.sas-content,.sas-tabs')));if(!external||refreshScheduled)return;refreshScheduled=true;requestAnimationFrame(()=>{refreshScheduled=false;refreshActive()})});observer.observe(main,{childList:true,subtree:true});};
export function installSalesAnalysisSuite(){const run=()=>install();run();const obs=new MutationObserver(run);obs.observe(document.documentElement,{childList:true,subtree:true});}
