const allowed=()=>{try{return ["SUPER_ADMIN","OWNER","ADMIN","MANAGER"].includes(JSON.parse(localStorage.getItem("user")||"{}").role)}catch{return false}};
const esc=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]));
const money=v=>Number(v||0).toLocaleString("el-GR",{style:"currency",currency:"EUR"});
const num=v=>Number(v||0),pad=n=>String(n).padStart(2,"0"),dateValue=d=>`${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}`,today=()=>dateValue(new Date()),monthStart=()=>{const d=new Date();return dateValue(new Date(d.getFullYear(),d.getMonth(),1))},yearStart=()=>`${new Date().getFullYear()}-01-01`,fmt=v=>v?new Date(v).toLocaleString("el-GR"):"—";
const typeLabel=v=>v==="WHOLESALE"?"Χονδρική":v==="BUSINESS"?"Επιχείρηση":"Λιανική";
const state={active:false,tab:"catalog",q:"",activeOnly:true,nonZeroOnly:false,report:null,selectedId:"",from:monthStart(),to:today(),rows:[],fiscal:null};
async function api(path,options={}){const token=localStorage.getItem("token");const r=await fetch(path,{...options,headers:{"Content-Type":"application/json",...(token?{Authorization:`Bearer ${token}`}:{}) ,...(options.headers||{})}});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||`Σφάλμα ${r.status}`);return d}
function modal(html){const w=document.createElement("div");w.className="cc-modal-overlay";w.innerHTML=`<section class="cc-modal">${html}</section>`;document.body.appendChild(w);w.addEventListener("click",e=>{if(e.target===w||e.target.closest("[data-cc-close-modal]"))w.remove()});return w}
function notice(root,text,error=false){let n=root.querySelector(".cc-notice");if(!n){n=document.createElement("div");n.className="cc-notice";root.prepend(n)}n.classList.toggle("error",error);n.textContent=text;setTimeout(()=>n?.remove(),6000)}
function nativeVisibility(hub,hide){[...hub.children].forEach((child,index)=>{if(index===0||child.classList.contains("customer-control-suite"))return;child.classList.toggle("cc-native-hidden",hide)})}
function activate(hub,button){state.active=true;nativeVisibility(hub,true);button.classList.add("active");let suite=hub.querySelector(".customer-control-suite");if(!suite){suite=document.createElement("section");suite.className="customer-control-suite";hub.firstElementChild?.after(suite)}suite.hidden=false;render(suite);loadCurrent(suite)}
function deactivate(hub,button){state.active=false;button.classList.remove("active");hub.querySelector(".customer-control-suite")?.setAttribute("hidden","");nativeVisibility(hub,false)}
const customerOptions=(all=true)=>`${all?'<option value="">Όλοι οι πελάτες</option>':'<option value="">Επιλογή πελάτη</option>'}${(state.report?.customers||[]).map(c=>`<option value="${esc(c.id)}" ${state.selectedId===c.id?"selected":""}>${esc(c.name)}${c.taxId?` · ${esc(c.taxId)}`:""}</option>`).join("")}`;
function header(){const tabs=[["catalog","👤 Πελατολόγιο"],["receipts","💰 Εισπράξεις"],["turnover","◉ Τζίρος"],["mydata","myDATA"],["provider","Πάροχος"]];return `<div class="cc-tabs">${tabs.map(([id,l])=>`<button data-cc-tab="${id}" class="${state.tab===id?"active":""}">${l}</button>`).join("")}</div>`}
function catalog(){const r=state.report||{},rows=r.customers||[];return `<section class="cc-filter"><b>Κριτήρια αναζήτησης</b><div><button class="cc-clear" data-cc-clear title="Καθαρισμός">×</button><label>Επωνυμία ή ΑΦΜ<input data-cc-q value="${esc(state.q)}"></label><label class="check"><input type="checkbox" data-cc-active ${state.activeOnly?"checked":""}> Μόνο οι ενεργοί πελάτες</label><button data-cc-search>🔍 Αναζήτηση</button></div></section><section class="cc-panel"><div class="cc-table catalog"><div class="row head"><span>Κωδικός</span><span>Επωνυμία</span><span>Υπόλοιπο</span><span>Επισκέψεις (Β)</span><span>Τζίρος έτους</span><span>Τζίρος προηγ. έτους</span><span>Τύπος</span><span>ΑΦΜ</span><span>Πόντοι</span><span>Κάρτα μέλους</span></div>${rows.map(c=>`<div class="row"><span><button class="cc-pencil" data-cc-edit="${c.id}">✎</button>${esc(c.legacyCode||String(c.id).slice(0,6))}</span><span><b>${esc(c.name)}</b></span><strong class="${c.balance>0?"warn":""}">${money(c.balance)}</strong><span>${num(c.visits).toLocaleString("el-GR")}</span><strong>${money(c.currentYear)}</strong><span>${money(c.previousYear)}</span><span>${typeLabel(c.customerType)}</span><span>${esc(c.taxId||"")}</span><span>${num(c.points).toLocaleString("el-GR",{maximumFractionDigits:2})}</span><span>${esc(c.memberCard||"")}</span></div>`).join("")||'<div class="cc-empty">Δεν υπάρχουν πελάτες.</div>'}<div class="row totals"><span></span><strong>${r.summary?.count||0}</strong><strong>${money(r.summary?.balance)}</strong><strong>${num(r.summary?.visits).toLocaleString("el-GR")}</strong><strong>${money(r.summary?.currentYear)}</strong></div></div></section><div class="cc-actions"><button data-cc-exit>✖<small>Κλείσιμο</small></button><button data-cc-new>＋<small>Νέος πελάτης</small></button><button data-cc-balances class="${state.nonZeroOnly?"active":""}">▰<small>Υπόλοιπα</small></button><button data-cc-export>✕<small>Excel</small></button><button data-cc-print>PDF<small>PDF</small></button></div>`}
function criteria(title){return `<section class="cc-filter"><b>${title}</b><div><label>Από<input type="date" data-cc-from value="${state.from}"></label><label>Έως<input type="date" data-cc-to value="${state.to}"></label><label>Πελάτης<select data-cc-customer>${customerOptions(true)}</select></label><button data-cc-load>🔍 Αναζήτηση</button><button data-cc-month>Τρέχων μήνας</button><button data-cc-year>Τρέχον έτος</button><button data-cc-export>Excel</button></div></section>`}
function receipts(){const d=state.rows||{},s=d.summary||{};return `${criteria("Κριτήρια αναζήτησης εισπράξεων")}<section class="cc-panel"><div class="cc-summary"><article><small>Εισπράξεις</small><b>${money(s.total)}</b></article><article><small>Κινήσεις</small><b>${s.count||0}</b></article><button data-cc-new-receipt>＋ Νέα είσπραξη</button></div><div class="cc-table receipts"><div class="row head"><span>Ημερομηνία</span><span>Πελάτης</span><span>ΑΦΜ</span><span>Κατάστημα</span><span>Ποσό</span><span>Παρατηρήσεις</span></div>${(d.items||[]).map(r=>`<div class="row"><span>${fmt(r.createdAt)}</span><span><b>${esc(r.customerName)}</b></span><span>${esc(r.taxId||"")}</span><span>${esc(r.storeName||"—")}</span><strong>${money(r.amount)}</strong><span>${esc(r.note||"")}</span></div>`).join("")||'<div class="cc-empty">Δεν υπάρχουν εισπράξεις.</div>'}</div></section>`}
function turnover(){const d=state.rows||{},s=d.summary||{};return `${criteria("Κριτήρια αναζήτησης τζίρου")}<section class="cc-panel"><div class="cc-summary"><article><small>Τζίρος</small><b>${money(s.turnover)}</b></article><article><small>Πελάτες</small><b>${s.customers||0}</b></article><article><small>Επισκέψεις</small><b>${s.visits||0}</b></article><article><small>Εκπτώσεις</small><b>${money(s.discount)}</b></article></div><div class="cc-table turnover"><div class="row head"><span>Πελάτης</span><span>ΑΦΜ</span><span>Επισκέψεις</span><span>Αρχική αξία</span><span>Εκπτώσεις</span><span>Τζίρος</span></div>${(d.items||[]).map(r=>`<div class="row"><span><b>${esc(r.customerName)}</b></span><span>${esc(r.taxId||"")}</span><span>${r.visits}</span><span>${money(r.subtotal)}</span><span>${money(r.discount)}</span><strong>${money(r.turnover)}</strong></div>`).join("")||'<div class="cc-empty">Δεν υπάρχουν πωλήσεις πελατών στην περίοδο.</div>'}</div></section>`}
function fiscal(kind){const f=state.fiscal?.[kind]||{};return `<section class="cc-panel fiscal"><h2>${kind==="mydata"?"myDATA":"Πάροχος"}</h2><div class="cc-fiscal-status ${f.available?"ready":"locked"}"><b>${f.available?"Συνδεδεμένο":"Μη συνδεδεμένο"}</b><p>${esc(f.message||"Δεν υπάρχει διαθέσιμη σύνδεση.")}</p></div><p class="cc-source-note">Δεν εμφανίζονται πλασματικά παραστατικά, MARK ή στοιχεία παρόχου. Η καρτέλα θα ενεργοποιηθεί όταν συνδεθεί πραγματική φορολογική υπηρεσία για τους πελάτες.</p></section>`}
function render(root){root.innerHTML=header()+(state.tab==="catalog"?catalog():state.tab==="receipts"?receipts():state.tab==="turnover"?turnover():state.tab==="mydata"?fiscal("mydata"):fiscal("provider"));bind(root)}
async function loadReport(root){try{state.report=await api(`/api/customer-control/report?q=${encodeURIComponent(state.q)}&activeOnly=${state.activeOnly}&nonZeroOnly=${state.nonZeroOnly}`);render(root)}catch(e){notice(root,e.message,true)}}
function capture(root){state.from=root.querySelector("[data-cc-from]")?.value||state.from;state.to=root.querySelector("[data-cc-to]")?.value||state.to;state.selectedId=root.querySelector("[data-cc-customer]")?.value||""}
async function loadRows(root){capture(root);const q=new URLSearchParams({from:new Date(`${state.from}T00:00:00`).toISOString(),to:new Date(`${state.to}T23:59:59.999`).toISOString(),...(state.selectedId?{customerId:state.selectedId}:{})});try{state.rows=await api(`/api/customer-control/${state.tab}?${q}`);render(root)}catch(e){notice(root,e.message,true)}}
async function loadFiscal(root){try{state.fiscal=await api("/api/customer-control/fiscal-status");render(root)}catch(e){notice(root,e.message,true)}}
async function loadCurrent(root){if(state.tab==="catalog")return loadReport(root);if(state.tab==="receipts"||state.tab==="turnover"){if(!state.report)await loadReport(root);return loadRows(root)}return loadFiscal(root)}
function formHtml(c={}){return `<div class="cc-modal-title"><h2>${c.id?"Επεξεργασία πελάτη":"Νέος πελάτης"}</h2><button data-cc-close-modal>×</button></div><form class="cc-form"><label>Κωδικός<input name="legacyCode" value="${esc(c.legacyCode||"")}"></label><label class="wide">Επωνυμία<input name="name" required value="${esc(c.name||"")}"></label><label>ΑΦΜ<input name="taxId" value="${esc(c.taxId||"")}"></label><label>Τύπος<select name="customerType"><option value="RETAIL" ${c.customerType==="RETAIL"||!c.customerType?"selected":""}>Λιανική</option><option value="WHOLESALE" ${c.customerType==="WHOLESALE"?"selected":""}>Χονδρική</option><option value="BUSINESS" ${c.customerType==="BUSINESS"?"selected":""}>Επιχείρηση</option></select></label><label>Τηλέφωνο<input name="phone" value="${esc(c.phone||"")}"></label><label>Email<input name="email" type="email" value="${esc(c.email||"")}"></label><label>Διεύθυνση<input name="address" value="${esc(c.address||"")}"></label><label>Πόλη<input name="city" value="${esc(c.city||"")}"></label><label>Έκπτωση %<input name="discountPercent" type="number" step="0.01" value="${num(c.discountPercent)}"></label><label>Πιστωτικό όριο<input name="creditLimit" type="number" step="0.01" value="${num(c.creditLimit)}"></label><label>Πόντοι<input name="points" type="number" step="0.01" value="${num(c.points)}"></label><label>Κάρτα μέλους<input name="memberCard" value="${esc(c.memberCard||"")}"></label><label class="wide">Παρατηρήσεις<input name="notes" value="${esc(c.notes||"")}"></label>${c.id?`<label class="check"><input name="active" type="checkbox" ${c.active!==false?"checked":""}> Ενεργός πελάτης</label>`:""}<button class="primary">Καταχώρηση</button></form>`}
async function customerModal(root,id=""){try{const c=id?(await api(`/api/customer-control/${id}/detail`)).customer:{},m=modal(formHtml(c));m.querySelector("form").onsubmit=async e=>{e.preventDefault();const f=new FormData(e.currentTarget),body={legacyCode:f.get("legacyCode")||null,name:f.get("name"),taxId:f.get("taxId")||null,customerType:f.get("customerType"),phone:f.get("phone")||null,email:f.get("email")||null,address:f.get("address")||null,city:f.get("city")||null,discountPercent:Number(f.get("discountPercent")||0),creditLimit:Number(f.get("creditLimit")||0),points:Number(f.get("points")||0),memberCard:f.get("memberCard")||null,notes:f.get("notes")||null,...(id?{active:!!e.currentTarget.active.checked}:{})};try{await api(id?`/api/customer-control/${id}`:"/api/customer-control",{method:id?"PATCH":"POST",body:JSON.stringify(body)});m.remove();loadReport(root)}catch(err){alert(err.message)}}}catch(e){alert(e.message)}}
async function receiptModal(root){if(!state.selectedId){alert("Επίλεξε πρώτα πελάτη στην καρτέλα Εισπράξεις.");return}try{const d=await api(`/api/customer-control/${state.selectedId}/detail`),m=modal(`<div class="cc-modal-title"><h2>Νέα είσπραξη · ${esc(d.customer.name)}</h2><button data-cc-close-modal>×</button></div><form class="cc-form"><label>Ποσό<input name="amount" type="number" min="0.01" step="0.01" required></label><label>Κατάστημα<select name="storeId"><option value="">Χωρίς κατάστημα</option>${d.stores.map(s=>`<option value="${s.id}">${esc(s.name)}</option>`).join("")}</select></label><label class="wide">Παρατηρήσεις<input name="note"></label><button class="primary">Καταχώρηση είσπραξης</button></form>`);m.querySelector("form").onsubmit=async e=>{e.preventDefault();const f=new FormData(e.currentTarget);try{await api(`/api/customer-control/${state.selectedId}/receipts`,{method:"POST",body:JSON.stringify({amount:Number(f.get("amount")),storeId:f.get("storeId")||null,note:f.get("note")||null})});m.remove();loadRows(root)}catch(err){alert(err.message)}}}catch(e){alert(e.message)}}
function exportData(){let data=[];if(state.tab==="catalog")data=state.report?.customers||[];else data=state.rows?.items||[];if(!data.length)return alert("Δεν υπάρχουν δεδομένα για εξαγωγή.");const headers=Object.keys(data[0]);const csv="\ufeff"+[headers.join(";"),...data.map(r=>headers.map(h=>`"${String(r[h]??"").replace(/"/g,'""')}"`).join(";"))].join("\r\n");const a=document.createElement("a");a.href=URL.createObjectURL(new Blob([csv],{type:"text/csv;charset=utf-8"}));a.download=`pelates-${state.tab}-${today()}.csv`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
function bind(root){root.querySelectorAll("[data-cc-tab]").forEach(b=>b.onclick=()=>{state.tab=b.dataset.ccTab;state.rows=[];render(root);loadCurrent(root)});root.querySelector("[data-cc-search]")?.addEventListener("click",()=>{state.q=root.querySelector("[data-cc-q]")?.value||"";state.activeOnly=!!root.querySelector("[data-cc-active]")?.checked;loadReport(root)});root.querySelector("[data-cc-clear]")?.addEventListener("click",()=>{state.q="";loadReport(root)});root.querySelector("[data-cc-new]")?.addEventListener("click",()=>customerModal(root));root.querySelectorAll("[data-cc-edit]").forEach(b=>b.onclick=()=>customerModal(root,b.dataset.ccEdit));root.querySelector("[data-cc-balances]")?.addEventListener("click",()=>{state.nonZeroOnly=!state.nonZeroOnly;loadReport(root)});root.querySelector("[data-cc-exit]")?.addEventListener("click",()=>{const hub=root.closest(".commerce-hub"),btn=hub?.querySelector("[data-customer-control-launch]");if(hub&&btn)deactivate(hub,btn)});root.querySelectorAll("[data-cc-export]").forEach(b=>b.onclick=exportData);root.querySelector("[data-cc-print]")?.addEventListener("click",()=>window.print());root.querySelector("[data-cc-load]")?.addEventListener("click",()=>loadRows(root));root.querySelector("[data-cc-customer]")?.addEventListener("change",e=>state.selectedId=e.target.value);root.querySelector("[data-cc-month]")?.addEventListener("click",()=>{state.from=monthStart();state.to=today();loadRows(root)});root.querySelector("[data-cc-year]")?.addEventListener("click",()=>{state.from=yearStart();state.to=today();loadRows(root)});root.querySelector("[data-cc-new-receipt]")?.addEventListener("click",()=>receiptModal(root))}
function install(){if(!allowed())return;document.querySelectorAll(".commerce-hub").forEach(hub=>{const strip=hub.querySelector(".commerce-module-strip");if(!strip)return;let btn=strip.querySelector("[data-customer-control-launch]");if(!btn){btn=document.createElement("button");btn.type="button";btn.dataset.customerControlLaunch="1";btn.textContent="👥 Πελάτες";strip.appendChild(btn);btn.addEventListener("click",()=>activate(hub,btn));[...strip.querySelectorAll("button")].filter(x=>x!==btn).forEach(n=>n.addEventListener("click",()=>deactivate(hub,btn)))}if(state.active&&!hub.querySelector(".customer-control-suite:not([hidden])"))activate(hub,btn)})}
export function installCustomerControlSuite(){install()}
