const esc=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]));
const n=v=>Number(v||0),money=v=>n(v).toLocaleString("el-GR",{style:"currency",currency:"EUR",minimumFractionDigits:2}),num=v=>n(v).toLocaleString("el-GR",{maximumFractionDigits:3}),fmt=v=>v?new Date(v).toLocaleString("el-GR"):"—";
let currentItems=[];
async function api(path){const t=localStorage.getItem("token"),r=await fetch(path,{headers:{...(t?{Authorization:`Bearer ${t}`}:{})}}),d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||`Σφάλμα ${r.status}`);return d}
function params(root){return new URLSearchParams({from:root.querySelector("[data-kr-from]")?.value||"",to:root.querySelector("[data-kr-to]")?.value||"",...(root.querySelector("[data-kr-store]")?.value?{storeId:root.querySelector("[data-kr-store]").value}:{}),...(root.querySelector("[data-kr-q]")?.value?.trim()?{q:root.querySelector("[data-kr-q]").value.trim()}:{})})}
const head=c=>`<div class="kr-row kr-head">${c.map(x=>`<span>${x}</span>`).join("")}</div>`,row=(c,attrs="")=>`<div class="kr-row" ${attrs}>${c.map(x=>`<span>${x}</span>`).join("")}</div>`;
function removeOld(root){root.querySelector(".kr-panel")?.remove();root.querySelector(".kr-unavailable")?.remove();root.querySelector(".kr-error")?.remove()}
function view(data){const items=data.items||[];currentItems=items;return `<section class="kr-panel kr-delivery-v5"><h3>delivery / Δελτία διακίνησης</h3><div class="kr-info">${esc(data.note||"")}</div><div class="kr-delivery-cards"><article><span>Δελτία</span><b>${items.length}</b></article><article><span>Συνολική ποσότητα</span><b>${num(data.totalQuantity)}</b></article><article><span>Ενδεικτική λιανική αξία</span><b>${money(data.totalRetailValue)}</b></article><article><span>Φορολογική διαβίβαση</span><b>ΟΧΙ</b></article></div><div class="kr-table delivery-v5">${head(["＋","Ημερομηνία","Δελτίο","Κατεύθυνση","Παραλήπτης","ΑΦΜ","Προορισμός","Σκοπός","Γραμμές","Ποσότητα","Λιανική αξία","Κατάσταση","Φορολογική κατάσταση","Χειριστής","Κατάστημα"])}${items.map((r,i)=>row([`<button class="kr-delivery-plus" data-delivery-note="${esc(r.id)}" data-delivery-index="${i}">＋</button>`,fmt(r.dispatchedAt||r.createdAt),`<b>${esc(r.documentNumber||"—")}</b>`,esc(r.direction||"—"),esc(r.recipientName||"—"),esc(r.recipientTaxId||"—"),esc(r.destinationAddress||"—"),esc(r.purpose||"—"),num(r.lineCount),num(r.totalQuantity),money(r.retailValue),esc(r.status||"—"),esc(r.fiscalStatus||"—"),esc(r.createdByName||"—"),esc(r.storeName||"—")],`data-delivery-row="${i}"`)).join("")||'<div class="kr-empty">Δεν βρέθηκαν δελτία.</div>'}</div><div class="kr-summary"><span>${items.length} δελτία</span><strong>Ποσότητα: ${num(data.totalQuantity)}</strong><strong>Λιανική αξία: ${money(data.totalRetailValue)}</strong></div></section>`}
function drillView(data){const items=data.items||[];return `<div class="kr-delivery-drill-head">Δελτίο ${esc(data.note?.documentNumber||"—")}</div><div class="kr-delivery-drill-table">${head(["Κωδικός","Περιγραφή","Κατηγορία","Υποκατηγορία","Ποσότητα","Μονάδα","Λιανική","ΦΠΑ","Λιανική αξία"])}${items.map(r=>row([esc(r.sku||"—"),`<b>${esc(r.description||"—")}</b>`,esc(r.categoryName||"—"),esc(r.subcategoryName||"—"),num(r.quantity),esc(r.unit||"—"),money(r.salePrice),`${num(r.vatRate)}%`,money(r.retailValue)])).join("")||'<div class="kr-empty">Δεν βρέθηκαν γραμμές.</div>'}</div><div class="kr-summary"><strong>Ποσότητα: ${num(data.totalQuantity)}</strong><strong>Λιανική αξία: ${money(data.totalRetailValue)}</strong></div>`}
async function load(root){root.dataset.deliveryV5="1";root.querySelectorAll("[data-kr-tab]").forEach(b=>b.classList.toggle("active",b.dataset.krTab==="delivery"));removeOld(root);const toolbar=root.querySelector(".kr-toolbar"),holder=document.createElement("div");holder.className="kr-error";holder.textContent="Φόρτωση…";toolbar?.before(holder);try{const data=await api(`/api/reports/delivery?${params(root)}`);holder.outerHTML=view(data)}catch(e){holder.textContent=e.message}}
async function drill(root,button){const rowEl=button.closest("[data-delivery-row]");if(!rowEl)return;const existing=rowEl.nextElementSibling;if(existing?.classList.contains("kr-delivery-drill")){existing.remove();button.textContent="＋";return}root.querySelectorAll(".kr-delivery-drill").forEach(x=>x.remove());root.querySelectorAll(".kr-delivery-plus").forEach(x=>x.textContent="＋");button.textContent="−";const box=document.createElement("div");box.className="kr-delivery-drill";box.textContent="Φόρτωση γραμμών…";rowEl.after(box);try{const data=await api(`/api/reports/delivery/${encodeURIComponent(button.dataset.deliveryNote)}/lines`);box.innerHTML=drillView(data)}catch(e){box.textContent=e.message}}
function exportCsv(){if(!currentItems.length)return alert("Δεν υπάρχουν δεδομένα για εξαγωγή.");const keys=Object.keys(currentItems[0]).filter(k=>typeof currentItems[0][k]!=="object"),csv="\ufeff"+[keys.join(";"),...currentItems.map(r=>keys.map(k=>`"${String(r[k]??"").replace(/"/g,'""')}"`).join(";"))].join("\r\n"),a=document.createElement("a");a.href=URL.createObjectURL(new Blob([csv],{type:"text/csv;charset=utf-8"}));a.download="anafores-delivery.csv";a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
export function installKioskReportsDeliveryV5(){if(window.__mwsReportsDeliveryV5)return;window.__mwsReportsDeliveryV5=true;document.addEventListener("click",event=>{const root=event.target.closest(".kiosk-reports-suite");if(!root)return;const tab=event.target.closest("[data-kr-tab]");if(tab){if(tab.dataset.krTab==="delivery"){event.preventDefault();event.stopImmediatePropagation();load(root);return}delete root.dataset.deliveryV5;currentItems=[];return}if(root.dataset.deliveryV5!=="1")return;const plus=event.target.closest("[data-delivery-note]");if(plus){event.preventDefault();event.stopImmediatePropagation();drill(root,plus);return}if(event.target.closest("[data-kr-search]")||event.target.closest("[data-kr-refresh]")){event.preventDefault();event.stopImmediatePropagation();load(root);return}if(event.target.closest("[data-kr-export]")){event.preventDefault();event.stopImmediatePropagation();exportCsv()}},true)}
