const esc=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]));
const n=v=>Number(v||0),money=v=>n(v).toLocaleString("el-GR",{style:"currency",currency:"EUR",minimumFractionDigits:2}),num=v=>n(v).toLocaleString("el-GR",{maximumFractionDigits:3}),pct=v=>`${n(v).toLocaleString("el-GR",{minimumFractionDigits:2,maximumFractionDigits:2})}%`,fmt=v=>v?new Date(v).toLocaleString("el-GR"):"—";
let currentItems=[];
async function api(path){const t=localStorage.getItem("token"),r=await fetch(path,{headers:{...(t?{Authorization:`Bearer ${t}`}:{})}}),d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||`Σφάλμα ${r.status}`);return d}
function params(root){return new URLSearchParams({from:root.querySelector("[data-kr-from]")?.value||"",to:root.querySelector("[data-kr-to]")?.value||"",...(root.querySelector("[data-kr-store]")?.value?{storeId:root.querySelector("[data-kr-store]").value}:{}),...(root.querySelector("[data-kr-q]")?.value?.trim()?{q:root.querySelector("[data-kr-q]").value.trim()}:{})})}
const head=c=>`<div class="kr-row kr-head">${c.map(x=>`<span>${x}</span>`).join("")}</div>`,row=(c,attrs="")=>`<div class="kr-row" ${attrs}>${c.map(x=>`<span>${x}</span>`).join("")}</div>`;
function removeOld(root){root.querySelector(".kr-panel")?.remove();root.querySelector(".kr-unavailable")?.remove();root.querySelector(".kr-error")?.remove()}
function view(data){const items=data.items||[];currentItems=items;return `<section class="kr-panel kr-sales-v4"><h3>Στατιστικά πωλήσεων</h3><div class="kr-info">Πραγματικές ολοκληρωμένες πωλήσεις MyWorkStation. Το κόστος κάθε γραμμής βασίζεται στην τελευταία εγκεκριμένη αγορά που υπήρχε έως τη στιγμή της πώλησης.</div><div class="kr-sales-cards"><article><span>Ποσότητα</span><b>${num(data.totalQuantity)}</b></article><article><span>Τζίρος</span><b>${money(data.totalGross)}</b></article><article><span>Καθαρή αξία</span><b>${money(data.totalNet)}</b></article><article><span>ΦΠΑ</span><b>${money(data.totalVat)}</b></article><article><span>Κόστος</span><b>${money(data.totalCost)}</b></article><article><span>Κέρδος</span><b>${money(data.totalProfit)}</b></article></div><div class="kr-table sales-v4">${head(["＋","Κατηγορία","Υποκατηγορία","Περιγραφή","Ποσότητα","Τζίρος","Καθαρή","ΦΠΑ","Μέση πώληση","Κόστος","Κέρδος","Margin","Stock","Τελ. πώληση","Προμηθευτής","Κατάστημα"])}${items.map((r,i)=>row([r.productId?`<button class="kr-sales-plus" data-sales-product="${esc(r.productId)}" data-sales-store="${esc(r.storeId||"")}" data-sales-index="${i}">＋</button>`:"—",esc(r.categoryName||"—"),esc(r.subcategoryName||"—"),`<b>${esc(r.name||"—")}</b><small>${esc(r.sku||"")}</small>`,num(r.salesQuantity),money(r.grossSales),money(r.netSales),money(r.vatValue),money(r.averageGrossPrice),money(r.costValue),`<strong>${money(r.profit)}</strong>`,pct(r.margin),num(r.currentStock),fmt(r.lastSaleAt),esc(r.supplierName||"—"),esc(r.storeName||"—")],`data-sales-row="${i}"`)).join("")||'<div class="kr-empty">Δεν βρέθηκαν πωλήσεις.</div>'}</div><div class="kr-summary"><span>${items.length} είδη / καταστήματα</span><strong>Τζίρος: ${money(data.totalGross)}</strong><strong>Κέρδος: ${money(data.totalProfit)}</strong></div></section>`}
function drillView(data){const items=data.items||[];return `<div class="kr-sales-drill-head">${esc(data.product?.name||"Ανάλυση είδους")}</div><div class="kr-sales-drill-table">${head(["Ημερομηνία","Απόδειξη","Ποσότητα","Τιμή","Έκπτωση","ΦΠΑ","Σύνολο","Καθαρή","Κόστος","Κέρδος","Margin","Πληρωμή","Χειριστής","Πελάτης","Κατάστημα"])}${items.map(r=>row([fmt(r.occurredAt),esc(r.receiptNumber||r.saleId||"—"),num(r.quantity),money(r.unitPrice),money(r.discount),pct(r.vatRate),money(r.lineTotal),money(r.netValue),money(r.costValue),money(r.profit),pct(r.margin),esc(r.paymentMethods||"—"),esc(r.operatorName||"—"),esc(r.customerName||"Λιανική"),esc(r.storeName||"—")])).join("")||'<div class="kr-empty">Δεν βρέθηκαν γραμμές.</div>'}</div>`}
async function load(root){root.dataset.salesV4="1";root.querySelectorAll("[data-kr-tab]").forEach(b=>b.classList.toggle("active",b.dataset.krTab==="sales-stats"));removeOld(root);const toolbar=root.querySelector(".kr-toolbar"),holder=document.createElement("div");holder.className="kr-error";holder.textContent="Φόρτωση…";toolbar?.before(holder);try{const data=await api(`/api/reports/sales-analysis?${params(root)}`);holder.outerHTML=view(data)}catch(e){holder.textContent=e.message}}
async function drill(root,button){const rowEl=button.closest("[data-sales-row]");if(!rowEl)return;const existing=rowEl.nextElementSibling;if(existing?.classList.contains("kr-sales-drill")){existing.remove();button.textContent="＋";return}root.querySelectorAll(".kr-sales-drill").forEach(x=>x.remove());root.querySelectorAll(".kr-sales-plus").forEach(x=>x.textContent="＋");button.textContent="−";const box=document.createElement("div");box.className="kr-sales-drill";box.textContent="Φόρτωση ανάλυσης…";rowEl.after(box);try{const p=params(root);if(button.dataset.salesStore)p.set("storeId",button.dataset.salesStore);const data=await api(`/api/reports/sales-analysis/${encodeURIComponent(button.dataset.salesProduct)}?${p}`);box.innerHTML=drillView(data)}catch(e){box.textContent=e.message}}
function exportCsv(){if(!currentItems.length)return alert("Δεν υπάρχουν δεδομένα για εξαγωγή.");const keys=Object.keys(currentItems[0]).filter(k=>typeof currentItems[0][k]!=="object"),csv="\ufeff"+[keys.join(";"),...currentItems.map(r=>keys.map(k=>`"${String(r[k]??"").replace(/"/g,'""')}"`).join(";"))].join("\r\n"),a=document.createElement("a");a.href=URL.createObjectURL(new Blob([csv],{type:"text/csv;charset=utf-8"}));a.download="anafores-statistika-poliseon.csv";a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
export function installKioskReportsSalesV4(){if(window.__mwsReportsSalesV4)return;window.__mwsReportsSalesV4=true;document.addEventListener("click",event=>{const root=event.target.closest(".kiosk-reports-suite");if(!root)return;const tab=event.target.closest("[data-kr-tab]");if(tab){if(tab.dataset.krTab==="sales-stats"){event.preventDefault();event.stopImmediatePropagation();load(root);return}delete root.dataset.salesV4;currentItems=[];return}if(root.dataset.salesV4!=="1")return;const plus=event.target.closest("[data-sales-product]");if(plus){event.preventDefault();event.stopImmediatePropagation();drill(root,plus);return}if(event.target.closest("[data-kr-search]")||event.target.closest("[data-kr-refresh]")){event.preventDefault();event.stopImmediatePropagation();load(root);return}if(event.target.closest("[data-kr-export]")){event.preventDefault();event.stopImmediatePropagation();exportCsv()}},true)}
