const allowed=()=>{try{return ["SUPER_ADMIN","OWNER","ADMIN","MANAGER"].includes(JSON.parse(localStorage.getItem("user")||"{}").role)}catch{return false}};
const esc=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]));
const money=v=>Number(v||0).toLocaleString("el-GR",{style:"currency",currency:"EUR"});
const num=v=>Number(v||0),fmt=v=>v?new Date(v).toLocaleDateString("el-GR"):"—";
let lastSupplierId="",bound=false;
async function api(path){const token=localStorage.getItem("token");const r=await fetch(path,{headers:{...(token?{Authorization:`Bearer ${token}`}:{})}});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||`Σφάλμα ${r.status}`);return d}
function modal(html){const w=document.createElement("div");w.className="sc-modal-overlay wide spc-overlay";w.innerHTML=`<section class="sc-modal spc-modal">${html}</section>`;document.body.appendChild(w);w.addEventListener("click",e=>{if(e.target===w||e.target.closest("[data-spc-close]"))w.remove()});return w}
function remember(event){const row=event.target?.closest?.("[data-supplier-row]");if(row?.dataset?.supplierRow)lastSupplierId=row.dataset.supplierRow}
const barcodeText=item=>item.barcodes?.length?item.barcodes.map(b=>b.barcode).join(" · "):"—";
function itemDetails(item){const w=modal(`<div class="sc-modal-title blue"><div><h2>${esc(item.name)}</h2><b>${esc(item.sku||"Χωρίς SKU")}</b></div><button data-spc-close>×</button></div><div class="spc-detail-grid"><article><small>Κωδικός προμηθευτή</small><b>${esc(item.supplierCode||"—")}</b></article><article><small>Κατηγορία</small><b>${esc(item.categoryName||"—")}</b></article><article><small>ΦΠΑ</small><b>${num(item.vatRate).toFixed(2)}%</b></article><article><small>Λιανική</small><b>${money(item.salePrice)}</b></article><article><small>Τελευταία αγορά</small><b>${money(item.lastCost)}</b></article><article><small>Μέση αγορά</small><b>${money(item.avgCost)}</b></article><article><small>Τρέχον stock</small><b>${num(item.currentStock).toLocaleString("el-GR")}</b></article><article><small>Τελευταία ημερομηνία αγοράς</small><b>${fmt(item.lastPurchaseAt)}</b></article><article><small>Παραστατικά αγοράς</small><b>${item.purchaseCount||0}</b></article><article><small>Πηγή σύνδεσης</small><b>${esc(item.linkSource||"Ιστορικό τελευταίας αγοράς")}</b></article></div><section class="spc-barcodes"><h3>Barcodes προϊόντος</h3>${(item.barcodes||[]).map(b=>`<div><strong>${esc(b.barcode)}</strong><span>${b.salePrice==null?"—":money(b.salePrice)}</span><span>${esc(b.name||"")}</span></div>`).join("")||'<p>Δεν υπάρχουν barcodes.</p>'}</section><div class="spc-detail-actions"><button data-spc-close>← Επιστροφή</button></div>`);return w}
function csv(data){const rows=[["Κωδ. προμηθευτή","SKU","Περιγραφή","Κατηγορία","ΦΠΑ","Λιανική","Τελ. αγορά","Μέση αγορά","Απόθεμα","Τελ. ημερομηνία αγοράς","Barcodes"],...data.items.map(i=>[i.supplierCode||"",i.sku||"",i.name,i.categoryName||"",i.vatRate,i.salePrice,i.lastCost,i.avgCost,i.currentStock,fmt(i.lastPurchaseAt),barcodeText(i)])],text="\ufeff"+rows.map(r=>r.map(v=>`"${String(v??"").replace(/"/g,'""')}"`).join(";")).join("\r\n"),a=document.createElement("a");a.href=URL.createObjectURL(new Blob([text],{type:"text/csv;charset=utf-8"}));a.download=`eidi_promithefti_${data.supplier.name}.csv`;a.click();URL.revokeObjectURL(a.href)}
async function openCatalog(supplierId){
  try{
    const data=await api(`/api/supplier-control/${encodeURIComponent(supplierId)}/products`);
    const w=modal(`<div class="sc-modal-title blue"><div><h2>Προβολή ειδών</h2><b>${esc(data.supplier.name)}</b></div><button data-spc-close>×</button></div><div class="spc-summary"><span>Είδη <b>${data.summary.items||0}</b></span><span>Ενεργά <b>${data.summary.active||0}</b></span><span>Συνολικό stock <b>${num(data.summary.stock).toLocaleString("el-GR")}</b></span><span>Αξία stock με μέση αγορά <b>${money(data.summary.stockValue)}</b></span></div><div class="spc-controls"><label>Αναζήτηση<input data-spc-search placeholder="Περιγραφή / SKU / κωδικός προμηθευτή / barcode"></label><button data-spc-export>Excel / CSV</button></div><div class="spc-note">${esc(data.sourceNote||"")}</div><div class="spc-table"><div class="row head"><span></span><span>Κωδ. προμηθευτή</span><span>SKU</span><span>Περιγραφή</span><span>Κατηγορία</span><span>ΦΠΑ</span><span>Λιανική</span><span>Τελ. αγορά</span><span>Μέση αγορά</span><span>Απόθεμα</span><span>Τελ. αγορά στις</span><span>Γραμμωτοί κώδικες</span></div>${data.items.map(item=>`<div class="row" data-spc-row data-search="${esc([item.supplierCode,item.sku,item.name,item.categoryName,barcodeText(item)].filter(Boolean).join(" ").toLocaleLowerCase("el-GR"))}"><button data-spc-detail="${esc(item.id)}">🔎</button><span>${esc(item.supplierCode||"—")}</span><span>${esc(item.sku||"—")}</span><span><b>${esc(item.name)}</b>${item.active?"":"<small>ΑΝΕΝΕΡΓΟ</small>"}</span><span>${esc(item.categoryName||"—")}</span><span>${num(item.vatRate).toFixed(2)}%</span><strong>${money(item.salePrice)}</strong><span>${money(item.lastCost)}</span><span>${money(item.avgCost)}</span><strong>${num(item.currentStock).toLocaleString("el-GR")}</strong><span>${fmt(item.lastPurchaseAt)}</span><span class="spc-barcode-text">${esc(barcodeText(item))}</span></div>`).join("")||'<div class="spc-empty">Δεν υπάρχουν τρέχοντα είδη για τον προμηθευτή.</div>'}</div><div class="spc-actions"><button data-spc-close>← Επιστροφή</button></div>`);
    w.querySelector("[data-spc-search]")?.addEventListener("input",e=>{const q=String(e.target.value||"").trim().toLocaleLowerCase("el-GR");w.querySelectorAll("[data-spc-row]").forEach(row=>row.hidden=!!q&&!row.dataset.search.includes(q))});
    w.querySelector("[data-spc-export]")?.addEventListener("click",()=>csv(data));
    w.querySelectorAll("[data-spc-detail]").forEach(btn=>btn.addEventListener("click",()=>{const item=data.items.find(i=>i.id===btn.dataset.spcDetail);if(item)itemDetails(item)}));
  }catch(error){alert(error.message)}
}
export function installSupplierProductCatalog(){
  if(bound||!allowed())return;bound=true;
  document.addEventListener("contextmenu",remember,true);
  document.addEventListener("pointerdown",event=>{if(event.pointerType==="touch")remember(event)},true);
  document.addEventListener("click",event=>{
    const button=event.target.closest?.(".sc-context [data-action='view']");if(!button)return;
    event.preventDefault();event.stopImmediatePropagation();event.stopPropagation();
    if(!lastSupplierId)return alert("Δεν προσδιορίστηκε ο προμηθευτής.");
    document.querySelector(".sc-context")?.remove();openCatalog(lastSupplierId);
  },true);
}
