import React,{useEffect,useMemo,useState} from "react";
import {Barcode,ChevronLeft,ChevronRight,ClipboardList,Edit3,FileSpreadsheet,PackagePlus,Printer,RefreshCw,Search,Truck,X} from "lucide-react";
import ProductDeliveryFields,{deliveryDefaults} from "./ProductDeliveryFields.jsx";
import "./inventory-archive.css";

const money=value=>value===null||value===undefined?"—":`${Number(value).toFixed(2)} €`;
const qty=value=>value===null||value===undefined?"—":Number(value).toLocaleString("el-GR",{maximumFractionDigits:3});
const pct=value=>value===null||value===undefined?"—":`${Number(value).toFixed(2)}%`;
const when=value=>value?new Date(value).toLocaleString("el-GR"):"—";
const newBlank=()=>({name:"",sku:"",barcode:"",categoryName:"",salePrice:"",costPrice:"",vatRate:"24",openingStock:"",active:true});

function Modal({title,children,onClose,wide=false}){return <div className="ia-modal-backdrop"><section className={`ia-modal ${wide?"wide":""}`}><header><b>{title}</b><button onClick={onClose}><X/></button></header>{children}</section></div>}

export default function InventoryArchivePanel({api,storeId,stores=[],onClose}){
  const [data,setData]=useState({items:[],categories:[],subcategories:[],page:1,pages:1,total:0,totals:{}});
  const [query,setQuery]=useState(""),[category,setCategory]=useState(""),[subcategory,setSubcategory]=useState(""),[status,setStatus]=useState("ACTIVE"),[page,setPage]=useState(1),[pageSize,setPageSize]=useState(100);
  const [loading,setLoading]=useState(false),[error,setError]=useState(""),[message,setMessage]=useState("");
  const [checked,setChecked]=useState([]),[selected,setSelected]=useState(null),[modal,setModal]=useState(null);
  const [newDraft,setNewDraft]=useState(newBlank()),[bulk,setBulk]=useState({categoryName:"",vatRate:"",salePrice:"",active:"KEEP"});
  const [edit,setEdit]=useState(null),[editStock,setEditStock]=useState(""),[delivery,setDelivery]=useState(null);
  const [importFile,setImportFile]=useState(null),[importDataUrl,setImportDataUrl]=useState(""),[preview,setPreview]=useState(null),[applyStock,setApplyStock]=useState(false);

  const store=useMemo(()=>stores.find(s=>s.id===storeId),[stores,storeId]);
  const load=async(nextPage=page)=>{
    if(!storeId)return;setLoading(true);setError("");setMessage("");
    try{
      const params=new URLSearchParams({storeId,q:query,category,subcategory,status,page:String(nextPage),pageSize:String(pageSize)});
      const result=await api(`/api/inventory-archive?${params.toString()}`);setData(result);setPage(result.page);setChecked(ids=>ids.filter(id=>result.items.some(row=>row.productId===id)));setSelected(current=>current?result.items.find(r=>r.productId===current.productId)||null:null);
    }catch(e){setError(e.message)}finally{setLoading(false)}
  };
  useEffect(()=>{setPage(1);load(1)},[storeId,pageSize]);
  const search=event=>{event?.preventDefault();setPage(1);load(1)};
  const allVisible=data.items.length>0&&data.items.every(row=>checked.includes(row.productId));
  const toggleAll=()=>setChecked(allVisible?checked.filter(id=>!data.items.some(r=>r.productId===id)):[...new Set([...checked,...data.items.map(r=>r.productId)])]);
  const toggleOne=id=>setChecked(ids=>ids.includes(id)?ids.filter(x=>x!==id):[...ids,id]);

  const createNew=async()=>{
    if(!newDraft.name.trim())return setError("Συμπλήρωσε περιγραφή είδους.");
    setLoading(true);setError("");
    try{
      const created=await api("/api/owner-products/new",{method:"POST",body:JSON.stringify({name:newDraft.name.trim(),sku:newDraft.sku.trim(),barcode:newDraft.barcode.trim(),categoryName:newDraft.categoryName.trim(),unit:"PIECE",salePrice:Number(newDraft.salePrice||0),costPrice:Number(newDraft.costPrice||0),vatRate:Number(newDraft.vatRate||0),vatVerified:true,trackStock:true,active:newDraft.active,storeIds:[storeId]})});
      if(Number(newDraft.openingStock||0)>0)await api(`/api/owner-products/${created.id}/stock-adjustment`,{method:"POST",body:JSON.stringify({storeId,mode:"SET",quantity:Number(newDraft.openingStock),logMovement:true})});
      setModal(null);setNewDraft(newBlank());setMessage("Το νέο είδος δημιουργήθηκε.");await load(1);
    }catch(e){setError(e.message)}finally{setLoading(false)}
  };

  const applyBulk=async()=>{
    if(!checked.length)return setError("Επίλεξε πρώτα είδη.");
    const payload={productIds:checked};if(bulk.categoryName.trim())payload.categoryName=bulk.categoryName.trim();if(bulk.vatRate!=="")payload.vatRate=Number(bulk.vatRate);if(bulk.salePrice!=="")payload.salePrice=Number(bulk.salePrice);if(bulk.active!=="KEEP")payload.active=bulk.active==="YES";
    if(Object.keys(payload).length===1)return setError("Διάλεξε τουλάχιστον μία αλλαγή.");
    setLoading(true);setError("");try{const r=await api("/api/owner-products/bulk-card",{method:"PATCH",body:JSON.stringify(payload)});setModal(null);setBulk({categoryName:"",vatRate:"",salePrice:"",active:"KEEP"});setMessage(`Η ομαδική διόρθωση εφαρμόστηκε σε ${r.changed} είδη.`);await load()}catch(e){setError(e.message)}finally{setLoading(false)}
  };

  const openEdit=async row=>{
    setSelected(row);setLoading(true);setError("");
    try{
      const list=await api(`/api/owner-products/catalog?q=${encodeURIComponent(row.sku||row.name)}`);const product=(list||[]).find(x=>x.id===row.productId);if(!product)throw new Error("Δεν βρέθηκε η καρτέλα είδους.");
      const local=product.stores?.find(s=>s.storeId===storeId);setEdit({product,draft:{name:product.name||"",sku:product.sku||"",description:product.description||"",categoryName:product.categoryName||"",unit:product.unit||"PIECE",costPrice:String(Number(product.costPrice||0)),salePrice:String(Number(local?.salePrice??product.salePrice??0)),vatRate:String(Number(product.vatRate||0)),vatVerified:Boolean(product.vatVerified),trackStock:product.trackStock!==false,active:product.active!==false,barcodes:(product.barcodes||[]).map(x=>({barcode:x.barcode||"",unitMultiplier:Number(x.unitMultiplier||1)}))}});setEditStock(String(Number(local?.currentStock??row.currentStock??0)));setModal("edit");
    }catch(e){setError(e.message)}finally{setLoading(false)}
  };
  const editChange=(key,value)=>setEdit(x=>({...x,draft:{...x.draft,[key]:value}}));
  const saveEdit=async()=>{
    if(!edit)return;setLoading(true);setError("");try{
      const base=Number(edit.draft.salePrice||0);const product=edit.product;const storesPayload=(product.stores||[]).map(s=>({storeId:s.storeId,active:s.storeId===storeId?edit.draft.active:s.active!==false,salePrice:s.storeId===storeId?base:Number(s.salePrice??product.salePrice??0),minStock:s.minStock===null||s.minStock===undefined?null:Number(s.minStock)}));
      if(!storesPayload.some(s=>s.storeId===storeId))storesPayload.push({storeId,active:edit.draft.active,salePrice:base,minStock:null});
      await api(`/api/owner-products/${product.id}/card`,{method:"PATCH",body:JSON.stringify({...edit.draft,costPrice:Number(edit.draft.costPrice||0),salePrice:base,vatRate:Number(edit.draft.vatRate||0),barcodes:edit.draft.barcodes.filter(x=>x.barcode.trim()).map(x=>({barcode:x.barcode.trim(),unitMultiplier:Number(x.unitMultiplier||1)})),stores:storesPayload})});
      const current=data.items.find(r=>r.productId===product.id)?.currentStock??0;if(Number(editStock)!==Number(current))await api(`/api/owner-products/${product.id}/stock-adjustment`,{method:"POST",body:JSON.stringify({storeId,mode:"SET",quantity:Number(editStock||0),logMovement:true})});
      setModal(null);setEdit(null);setMessage("Η καρτέλα είδους αποθηκεύτηκε.");await load();
    }catch(e){setError(e.message)}finally{setLoading(false)}
  };

  const openDelivery=async row=>{setSelected(row);setLoading(true);setError("");try{setDelivery(deliveryDefaults(await api(`/api/owner-products/${row.productId}/delivery`)));setModal("delivery")}catch(e){setError(e.message)}finally{setLoading(false)}};
  const saveDelivery=async()=>{if(!selected||!delivery)return;setLoading(true);setError("");try{await api(`/api/owner-products/${selected.productId}/delivery`,{method:"PATCH",body:JSON.stringify({...delivery,modifierGroup:delivery.modifierGroup||null,efoodPrice:delivery.efoodPrice===""?null:Number(delivery.efoodPrice),woltPrice:delivery.woltPrice===""?null:Number(delivery.woltPrice)})});setModal(null);setDelivery(null);setMessage("Οι ρυθμίσεις e‑Delivery αποθηκεύτηκαν.");await load()}catch(e){setError(e.message)}finally{setLoading(false)}};

  const chooseImport=async file=>{setImportFile(file);setPreview(null);if(!file){setImportDataUrl("");return}try{const dataUrl=await new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(reader.result);reader.onerror=()=>reject(new Error("Δεν διαβάστηκε το αρχείο."));reader.readAsDataURL(file)});setImportDataUrl(String(dataUrl))}catch(e){setError(e.message)}};
  const previewImport=async()=>{if(!importDataUrl)return setError("Επίλεξε αρχείο Excel/CSV.");setLoading(true);setError("");try{setPreview(await api("/api/inventory-archive/import-preview",{method:"POST",body:JSON.stringify({storeId,dataUrl:importDataUrl})}))}catch(e){setError(e.message)}finally{setLoading(false)}};
  const runImport=async()=>{if(!preview||preview.summary.invalid)return setError("Η εισαγωγή δεν μπορεί να συνεχίσει όσο υπάρχουν μη έγκυρες γραμμές.");setLoading(true);setError("");try{const r=await api("/api/inventory-archive/import",{method:"POST",body:JSON.stringify({storeId,dataUrl:importDataUrl,applyStock})});setModal(null);setPreview(null);setImportFile(null);setImportDataUrl("");setMessage(`Εισαγωγή ολοκληρώθηκε: ${r.created} νέα, ${r.updated} ενημερωμένα.`);await load(1)}catch(e){setError(e.message)}finally{setLoading(false)}};

  const openOrders=()=>{const button=document.querySelector("[data-purchase-orders-launch]");if(button){button.click();return}setMessage("Άνοιξε το module «Παραγγελίες & Αγορές» από την επάνω μπάρα.")};
  const pageTotals=data.totals||{};

  return <div className="ia-shell">
    <header className="ia-titlebar"><div><b>Αρχείο ειδών (Αποθήκη)</b><small>{store?.name||data.store?.name||"Κατάστημα"}</small></div><button onClick={()=>load()} disabled={loading}><RefreshCw/>Ανανέωση</button></header>
    <section className="ia-filters"><div className="ia-filter-title">Κριτήρια αναζήτησης</div><label>Κατηγορία<select value={category} onChange={e=>{setCategory(e.target.value);setPage(1)}}><option value="">Όλες</option>{data.categories.map(x=><option key={x}>{x}</option>)}</select></label><label>Υποκατηγορία<select value={subcategory} onChange={e=>{setSubcategory(e.target.value);setPage(1)}}><option value="">Όλες</option>{data.subcategories.map(x=><option key={x}>{x}</option>)}</select></label><form onSubmit={search}><Search/><label>Περιγραφή / SKU / Barcode<input value={query} onChange={e=>setQuery(e.target.value)}/></label><button>Αναζήτηση</button></form><label className="ia-status">Εμφάνιση<select value={status} onChange={e=>{setStatus(e.target.value);setPage(1)}}><option value="ACTIVE">Μόνο ενεργά είδη</option><option value="ALL">Όλα τα είδη</option><option value="INACTIVE">Ανενεργά είδη</option></select></label></section>
    {error&&<div className="ia-alert error">{error}</div>}{message&&<div className="ia-alert success">{message}</div>}
    <section className="ia-grid-card"><div className="ia-grid-caption"><b>Αποτελέσματα αναζήτησης</b><span>{data.total.toLocaleString("el-GR")} είδη</span></div><div className="ia-table-wrap"><div className="ia-table">
      <div className="ia-row head"><span></span><span><input type="checkbox" checked={allVisible} onChange={toggleAll}/></span><span>Εσωτ. κωδικός</span><span>BARCODE</span><span>Περιγραφή</span><span>Margin</span><span>MARKUP</span><span>Λιανική</span><span>efood</span><span>Wolt</span><span>Αποθήκη</span><span>Συν. αξία λιανικής</span><span>Συν. κόστος</span><span>Τελ. αγορά</span><span>Μέση αγορά 6μ.</span><span>Ημ/νία αγοράς</span><span>Βασικός προμηθευτής</span><span>% ΦΠΑ</span><span>Κατηγορία</span><span>Υποκατηγορία</span><span>Εταιρεία</span><span>Alarm stock</span><span>Πωλήσεις 15ημ.</span><span>Τελ. πώληση</span><span>δημοσ. e‑delivery</span><span>δημοσ. stock</span><span>δημοσ. τιμών</span><span>Ενημέρωση</span><span>ΜΜ</span><span>ID</span></div>
      {data.items.map(row=><div className={`ia-row data ${selected?.productId===row.productId?"selected":""}`} key={row.productId} onClick={()=>setSelected(row)}><span className="ia-edit"><button title="Διόρθωση είδους" onClick={e=>{e.stopPropagation();openEdit(row)}}><Edit3/></button></span><span><input type="checkbox" checked={checked.includes(row.productId)} onChange={()=>toggleOne(row.productId)} onClick={e=>e.stopPropagation()}/></span><span className="link">{row.sku||"—"}</span><span><Barcode/>{row.barcode||"—"}</span><span className="name"><b>{row.name}</b></span><span className={Number(row.margin)<0?"negative":"metric"}>{pct(row.margin)}</span><span className={Number(row.markup)<0?"negative":"metric"}>{pct(row.markup)}</span><span className="metric">{money(row.salePrice)}</span><span>{money(row.efoodPrice)}</span><span>{money(row.woltPrice)}</span><span className="metric">{qty(row.currentStock)}</span><span className="metric">{money(row.retailStockValue)}</span><span>{money(row.costStockValue)}</span><span>{money(row.lastPurchasePrice)}</span><span>{money(row.averagePurchasePrice)}</span><span>{when(row.lastPurchaseAt)}</span><span className="link">{row.supplierName||"—"}</span><span>{qty(row.vatRate)}%</span><span>{row.categoryName||"ΧΩΡΙΣ ΚΑΤΗΓΟΡΙΑ"}</span><span>{row.subcategoryName||"ΧΩΡΙΣ ΥΠΟΚΑΤΗΓΟΡΙΑ"}</span><span>{row.brandName||"—"}</span><span>{qty(row.minStock)}</span><span className="metric">{qty(row.sales15Qty)}</span><span>{when(row.lastSaleAt)}</span><span><input type="checkbox" readOnly checked={Boolean(row.eDeliveryEnabled)}/></span><span><input type="checkbox" readOnly checked={Boolean(row.publishStock)}/></span><span><input type="checkbox" readOnly checked={Boolean(row.publishPrices)}/></span><span>{when(row.updatedAt)}</span><span>{row.unit||"—"}</span><span>{row.productId}</span></div>)}
      {!loading&&!data.items.length&&<div className="ia-empty">Δεν βρέθηκαν είδη με τα συγκεκριμένα κριτήρια.</div>}
    </div></div><footer className="ia-totals"><span>Σελίδα: {data.items.length} είδη</span><b>Stock {qty(pageTotals.stock)}</b><b>Λιανική {money(pageTotals.retailStockValue)}</b><b>Κόστος {money(pageTotals.costStockValue)}</b></footer></section>
    <div className="ia-pagination"><label>Γραμμές<select value={pageSize} onChange={e=>setPageSize(Number(e.target.value))}><option>50</option><option>100</option><option>200</option></select></label><button disabled={page<=1||loading} onClick={()=>load(page-1)}><ChevronLeft/></button><span>Σελίδα {page} / {data.pages}</span><button disabled={page>=data.pages||loading} onClick={()=>load(page+1)}><ChevronRight/></button></div>
    <footer className="ia-toolbar"><button onClick={onClose}><X/>Κλείσιμο</button><button onClick={()=>{setNewDraft(newBlank());setModal("new")}}><PackagePlus/>Νέο είδος</button><button disabled={!checked.length} onClick={()=>setModal("bulk")}><Edit3/>Ομαδική διόρθωση</button><button onClick={openOrders}><ClipboardList/>Παραγγελία</button><button onClick={()=>setModal("import")}><FileSpreadsheet/>Εισαγωγή από Excel</button><button onClick={()=>window.print()}><Printer/>Εκτύπωση</button><button disabled={!selected} onClick={()=>selected&&openDelivery(selected)}><Truck/>e‑Delivery</button></footer>

    {modal==="new"&&<Modal title="Νέο είδος" onClose={()=>setModal(null)}><div className="ia-form-grid"><label>Περιγραφή<input value={newDraft.name} onChange={e=>setNewDraft(d=>({...d,name:e.target.value}))}/></label><label>Κωδικός / SKU<input value={newDraft.sku} onChange={e=>setNewDraft(d=>({...d,sku:e.target.value}))}/></label><label>Barcode<input value={newDraft.barcode} onChange={e=>setNewDraft(d=>({...d,barcode:e.target.value}))}/></label><label>Κατηγορία<input value={newDraft.categoryName} onChange={e=>setNewDraft(d=>({...d,categoryName:e.target.value}))}/></label><label>Λιανική<input type="number" step="0.01" min="0" value={newDraft.salePrice} onChange={e=>setNewDraft(d=>({...d,salePrice:e.target.value}))}/></label><label>Τιμή αγοράς<input type="number" step="0.0001" min="0" value={newDraft.costPrice} onChange={e=>setNewDraft(d=>({...d,costPrice:e.target.value}))}/></label><label>% ΦΠΑ<input type="number" step="0.01" min="0" value={newDraft.vatRate} onChange={e=>setNewDraft(d=>({...d,vatRate:e.target.value}))}/></label><label>Αρχικό απόθεμα<input type="number" step="0.001" min="0" value={newDraft.openingStock} onChange={e=>setNewDraft(d=>({...d,openingStock:e.target.value}))}/></label><label className="check"><input type="checkbox" checked={newDraft.active} onChange={e=>setNewDraft(d=>({...d,active:e.target.checked}))}/>Ενεργό είδος</label></div><div className="ia-modal-actions"><button onClick={()=>setModal(null)}>Επιστροφή</button><button className="primary" onClick={createNew} disabled={loading}>Καταχώρηση</button></div></Modal>}

    {modal==="bulk"&&<Modal title={`Ομαδική διόρθωση · ${checked.length} είδη`} onClose={()=>setModal(null)}><div className="ia-form-grid"><label>Κατηγορία<input value={bulk.categoryName} onChange={e=>setBulk(x=>({...x,categoryName:e.target.value}))} placeholder="Κενό = χωρίς αλλαγή"/></label><label>% ΦΠΑ<input type="number" min="0" step="0.01" value={bulk.vatRate} onChange={e=>setBulk(x=>({...x,vatRate:e.target.value}))} placeholder="Κενό = χωρίς αλλαγή"/></label><label>Λιανική<input type="number" min="0" step="0.01" value={bulk.salePrice} onChange={e=>setBulk(x=>({...x,salePrice:e.target.value}))} placeholder="Κενό = χωρίς αλλαγή"/></label><label>Κατάσταση<select value={bulk.active} onChange={e=>setBulk(x=>({...x,active:e.target.value}))}><option value="KEEP">Χωρίς αλλαγή</option><option value="YES">Ενεργά</option><option value="NO">Ανενεργά</option></select></label></div><div className="ia-modal-actions"><button onClick={()=>setModal(null)}>Επιστροφή</button><button className="primary" onClick={applyBulk} disabled={loading}>Καταχώρηση</button></div></Modal>}

    {modal==="edit"&&edit&&<Modal wide title={`Διόρθωση είδους · ${edit.draft.name}`} onClose={()=>{setModal(null);setEdit(null)}}><div className="ia-form-grid edit"><label>Περιγραφή<input value={edit.draft.name} onChange={e=>editChange("name",e.target.value)}/></label><label>Κωδικός / SKU<input value={edit.draft.sku} onChange={e=>editChange("sku",e.target.value)}/></label><label>Κατηγορία<input value={edit.draft.categoryName} onChange={e=>editChange("categoryName",e.target.value)}/></label><label>Μονάδα<select value={edit.draft.unit} onChange={e=>editChange("unit",e.target.value)}><option value="PIECE">ΤΕΜ</option><option value="KG">KG</option><option value="LITER">L</option><option value="PACKAGE">ΣΥΣΚ.</option></select></label><label>Τιμή αγοράς<input type="number" min="0" step="0.0001" value={edit.draft.costPrice} onChange={e=>editChange("costPrice",e.target.value)}/></label><label>Λιανική καταστήματος<input type="number" min="0" step="0.01" value={edit.draft.salePrice} onChange={e=>editChange("salePrice",e.target.value)}/></label><label>% ΦΠΑ<input type="number" min="0" step="0.01" value={edit.draft.vatRate} onChange={e=>editChange("vatRate",e.target.value)}/></label><label>Stock καταστήματος<input type="number" min="0" step="0.001" value={editStock} onChange={e=>setEditStock(e.target.value)}/></label><label className="check"><input type="checkbox" checked={edit.draft.active} onChange={e=>editChange("active",e.target.checked)}/>Ενεργό</label><label className="check"><input type="checkbox" checked={edit.draft.trackStock} onChange={e=>editChange("trackStock",e.target.checked)}/>Παρακολούθηση stock</label><label className="wide">Περιγραφή / Σχόλιο<input value={edit.draft.description} onChange={e=>editChange("description",e.target.value)}/></label></div><div className="ia-modal-actions"><button onClick={()=>{setModal(null);setEdit(null)}}>Επιστροφή</button><button className="primary" onClick={saveEdit} disabled={loading}>Καταχώρηση</button></div></Modal>}

    {modal==="delivery"&&delivery&&<Modal wide title={`e‑Delivery · ${selected?.name||"Είδος"}`} onClose={()=>{setModal(null);setDelivery(null)}}><ProductDeliveryFields draft={delivery} onChange={(key,value)=>setDelivery(d=>({...d,[key]:value}))}/><div className="ia-modal-actions"><button onClick={()=>{setModal(null);setDelivery(null)}}>Επιστροφή</button><button className="primary" onClick={saveDelivery} disabled={loading}>Καταχώρηση</button></div></Modal>}

    {modal==="import"&&<Modal wide title="Εισαγωγή ειδών από Excel / CSV" onClose={()=>setModal(null)}><div className="ia-import"><label>Αρχείο<input type="file" accept=".xlsx,.xls,.csv" onChange={e=>chooseImport(e.target.files?.[0]||null)}/></label><label className="check"><input type="checkbox" checked={applyStock} onChange={e=>setApplyStock(e.target.checked)}/>Ενημέρωση stock και στα υπάρχοντα είδη</label><button onClick={previewImport} disabled={!importFile||loading}>Προεπισκόπηση χωρίς καταχώρηση</button>{preview&&<><div className="ia-preview-summary"><b>{preview.summary.total} γραμμές</b><span>Νέα: {preview.summary.create}</span><span>Ενημέρωση: {preview.summary.update}</span><span className={preview.summary.invalid?"bad":""}>Μη έγκυρες: {preview.summary.invalid}</span></div><div className="ia-preview-table"><div className="head"><span>Γραμμή</span><span>Ενέργεια</span><span>SKU</span><span>Barcode</span><span>Περιγραφή</span><span>Λιανική</span><span>Stock</span><span>Έλεγχος</span></div>{preview.rows.slice(0,80).map(r=><div key={r.row}><span>{r.row}</span><span>{r.action}</span><span>{r.sku||"—"}</span><span>{r.barcode||"—"}</span><span>{r.name||"—"}</span><span>{money(r.salePrice)}</span><span>{qty(r.stock)}</span><span>{r.errors.join(", ")||"OK"}</span></div>)}</div></>}</div><div className="ia-modal-actions"><button onClick={()=>setModal(null)}>Επιστροφή</button><button className="primary" disabled={!preview||preview.summary.invalid>0||loading} onClick={runImport}>Τελική εισαγωγή</button></div></Modal>}
  </div>;
}
