const esc=value=>String(value??'').replace(/[&<>"']/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[ch]));
const token=()=>localStorage.getItem('token')||'';
const num=value=>Number(String(value??'0').replace(',','.'))||0;
const when=value=>value?new Date(value).toLocaleString('el-GR'):'—';
const money=value=>`${Number(value||0).toFixed(2)} €`;
async function api(path,options={}){const r=await fetch(path,{...options,headers:{'Content-Type':'application/json',...(token()?{Authorization:`Bearer ${token()}`}:{}) ,...(options.headers||{})}});const text=await r.text();let data={};try{data=text?JSON.parse(text):{}}catch{data={error:text||'Μη αναμενόμενη απάντηση'}}if(!r.ok)throw new Error(data.error||`Σφάλμα ${r.status}`);return data}
function storeId(){const p=new URLSearchParams(location.search);try{return p.get('supportStore')||p.get('storeId')||JSON.parse(localStorage.getItem('supportContext')||'null')?.storeId||null}catch{return p.get('supportStore')||p.get('storeId')||null}}
function selectedRow(){return document.querySelector('.ia-row.data.selected')||[...document.querySelectorAll('.ia-row.data')].find(r=>r.matches(':hover'))||null}
function rowData(row){const c=[...row.children].map(x=>(x.textContent||'').trim());return {row,productId:c[29]||'',sku:c[2]||'',name:c[4]||'Είδος'}}
function closeMenu(){const m=document.getElementById('mws-inv-menu');if(m)m.hidden=true}
function openCorrectProductCard(d){closeMenu();const button=[...document.querySelectorAll('.commerce-mode-switch button')].find(b=>/Προϊόντα, Τιμές, Προσφορές/.test(b.textContent||''));if(!button)return alert('Δεν βρέθηκε η πλήρης καρτέλα προϊόντων.');button.click();let tries=0;const timer=setInterval(()=>{tries++;const rows=[...document.querySelectorAll('.kiosk-tr.items-v3:not(.head)')];const target=rows.find(r=>(r.children[2]?.textContent||'').trim()===d.sku);if(target){clearInterval(timer);target.click();setTimeout(()=>target.scrollIntoView({block:'center'}),50)}else if(tries>50){clearInterval(timer);alert('Δεν βρέθηκε το συγκεκριμένο είδος στην πλήρη καρτέλα.')}},100)}
function movementLabel(value){return value==='RETURN'?'ΕΠΙΣΤΡΟΦΗ':value==='CANCEL'?'ΑΚΥΡΩΣΗ':value==='SALE'?'ΠΩΛΗΣΗ':value}
function csv(filename,rows){const headers=['Ημερομηνία','Κίνηση','Χειριστής','Κόστος','Τιμή πώλησης','IN','OUT','Stock','Σημείωση'];const lines=[headers,...rows.map(x=>[when(x.createdAt),movementLabel(x.movementType),x.actorName||'',x.unitCost,x.salePrice??'',x.inQty,x.outQty,x.stockAfter,x.note||''])].map(r=>r.map(v=>`"${String(v??'').replace(/"/g,'""')}"`).join(';')).join('\n');const blob=new Blob(['\ufeff'+lines],{type:'text/csv;charset=utf-8'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=filename;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
async function openMovements(d){closeMenu();const sid=storeId();if(!sid)return alert('Δεν βρέθηκε το ενεργό κατάστημα.');const to=new Date(),from=new Date(Date.now()-30*86400000),fromS=from.toISOString().slice(0,10),toS=to.toISOString().slice(0,10);try{const data=await api(`/api/inventory-ledger/${encodeURIComponent(d.productId)}/movements?storeId=${encodeURIComponent(sid)}&from=${fromS}&to=${toS}`),rows=data.movements||[];document.querySelector('.mws-inv-ledger-bg')?.remove();const bg=document.createElement('div');bg.className='mws-inv-modal-bg mws-inv-ledger-bg';bg.innerHTML=`<section class="mws-inv-modal"><header><b>Κινήσεις είδους · ${esc(d.name)}</b><button data-close>×</button></header><div class="mws-inv-body"><div class="mws-inv-summary"><span>Από ${fromS}</span><span>Έως ${toS}</span><span>Τρέχον stock ${Number(data.product?.currentStock||0)}</span><button data-export>Excel / CSV</button></div><div class="mws-inv-table"><table><thead><tr><th>Ημερομηνία</th><th>Κίνηση</th><th>Χειριστής</th><th>Κόστος</th><th>Τιμή πώλησης</th><th>IN</th><th>OUT</th><th>Stock</th><th>Σημείωση</th></tr></thead><tbody>${rows.length?rows.map(x=>`<tr><td>${when(x.createdAt)}</td><td><b>${esc(movementLabel(x.movementType))}</b></td><td>${esc(x.actorName||'—')}</td><td>${x.movementType==='PURCHASE'?money(x.unitCost):'—'}</td><td>${x.salePrice===null||x.salePrice===undefined?'—':money(x.salePrice)}</td><td>${x.inQty||0}</td><td>${x.outQty||0}</td><td>${x.stockAfter}</td><td>${esc(x.note||'')}</td></tr>`).join(''):'<tr><td colspan="9">Δεν βρέθηκαν κινήσεις στο επιλεγμένο διάστημα.</td></tr>'}</tbody></table></div></div><div class="mws-inv-actions"><button data-close>Επιστροφή</button></div></section>`;document.body.appendChild(bg);bg.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>bg.remove());bg.querySelector('[data-export]').onclick=()=>csv(`kiniseis-${d.sku||d.productId}.csv`,rows)}catch(e){alert(e.message)}}
async function savePrice(){const root=document.querySelector('.mws-inv-modal-bg');if(!root)return;const row=selectedRow();if(!row)return alert('Δεν βρέθηκε επιλεγμένο είδος.');const d=rowData(row),sid=storeId();if(!sid)return alert('Δεν βρέθηκε το ενεργό κατάστημα.');const price=num(root.querySelector('[data-price]')?.value);if(price<0)return alert('Η τιμή δεν μπορεί να είναι αρνητική.');try{const list=await api(`/api/owner-products/catalog?q=${encodeURIComponent(d.sku||d.name)}`),p=(list||[]).find(x=>x.id===d.productId);if(!p)throw new Error('Δεν βρέθηκε η καρτέλα είδους.');const stores=(p.stores||[]).map(s=>({storeId:s.storeId,active:s.active!==false,salePrice:s.storeId===sid?price:Number(s.salePrice??price),minStock:s.minStock===null||s.minStock===undefined?null:Number(s.minStock)}));await api(`/api/owner-products/${d.productId}/card`,{method:'PATCH',body:JSON.stringify({name:p.name||d.name,sku:p.sku||d.sku||'',description:p.description||'',categoryName:p.categoryName||'',unit:p.unit||'PIECE',costPrice:Number(p.costPrice||0),salePrice:price,vatRate:Number(p.vatRate||0),vatVerified:Boolean(p.vatVerified),trackStock:p.trackStock!==false,active:p.active!==false,barcodes:(p.barcodes||[]).map(x=>({barcode:x.barcode,unitMultiplier:Number(x.unitMultiplier||1)})),stores})});root.remove();const form=document.querySelector('.ia-filters form');if(form?.requestSubmit)form.requestSubmit();else form?.querySelector('button')?.click()}catch(e){alert(e.message)}}
if(!window.__mwsInventoryContextCorrections){window.__mwsInventoryContextCorrections=true;document.addEventListener('click',event=>{const menuButton=event.target.closest?.('#mws-inv-menu button');if(menuButton){const text=String(menuButton.textContent||'');const row=selectedRow();if(!row)return;const d=rowData(row);if(text.includes('Διόρθωση είδους')){event.preventDefault();event.stopPropagation();openCorrectProductCard(d);return}if(text.includes('Κινήσεις είδους')){event.preventDefault();event.stopPropagation();openMovements(d);return}}const save=event.target.closest?.('.mws-inv-modal [data-save]');if(save){const title=document.querySelector('.mws-inv-modal header b')?.textContent||'';if(title.includes('Αλλαγή τιμής')){event.preventDefault();event.stopPropagation();savePrice()}}},true)}
