import React,{useEffect,useMemo,useRef,useState} from "react";
import {CloudDownload,Eye,Inbox,RefreshCw,RotateCw,Search,Trash2} from "lucide-react";
import "./invoice-inbox.css";


const labels={RECEIVED:"Αρχειοθετήθηκε",IN_REVIEW:"Σε έλεγχο",PROCESSED:"Ελεγμένο"};
const when=value=>value?new Date(value).toLocaleString("el-GR"):"—";
const dayKey=value=>{if(!value)return "Χωρίς ημερομηνία";const d=new Date(value);return Number.isNaN(d.getTime())?"Χωρίς ημερομηνία":d.toLocaleDateString("el-GR",{year:"numeric",month:"2-digit",day:"2-digit"})};
const isoDay=value=>{if(!value)return "";const d=new Date(value);return Number.isNaN(d.getTime())?"":d.toISOString().slice(0,10)};

export default function InvoiceInboxPanel({api,stores=[],onOpenAi}){
  const [storeId,setStoreId]=useState(stores[0]?.id||"");
  const [items,setItems]=useState([]);
  const [offset,setOffset]=useState(0);
  const [total,setTotal]=useState(0);
  const [archiveTotal,setArchiveTotal]=useState(0);
  const [supplierOptions,setSupplierOptions]=useState([]);
  const loadSequence=useRef(0);
  const [loading,setLoading]=useState(true);
  const [error,setError]=useState("");
  const [query,setQuery]=useState("");
  const [supplierFilter,setSupplierFilter]=useState("");
  const [dateFilter,setDateFilter]=useState("");
  const [workingId,setWorkingId]=useState("");
  const [message,setMessage]=useState("");
  const [myDataStatus,setMyDataStatus]=useState(null);
  useEffect(()=>{if(!storeId&&stores[0])setStoreId(stores[0].id)},[stores,storeId]);
  const archiveUrl=(extra={})=>`/api/commerce/documents/inbox/archive?${new URLSearchParams({storeId,q:query,supplier:supplierFilter,date:dateFilter,offset:String(offset),...extra})}`;
  const load=async()=>{if(!storeId)return;const sequence=++loadSequence.current;setLoading(true);setError("");try{const result=await api(archiveUrl());if(sequence===loadSequence.current){setItems(result.items);setTotal(result.total);setArchiveTotal(result.archiveTotal);setSupplierOptions(result.suppliers)}}catch(err){if(sequence===loadSequence.current)setError(err.message)}finally{if(sequence===loadSequence.current)setLoading(false)}};
  useEffect(()=>{loadSequence.current++;const timer=setTimeout(load,250);return()=>{clearTimeout(timer);loadSequence.current++}},[storeId,query,supplierFilter,dateFilter,offset]);
  const exportArchive=async(format,item)=>{const popup=format==="pdf"?window.open("","_blank"):null;if(format==="pdf"&&!popup){setError("Επιτρέψτε τα αναδυόμενα παράθυρα για την αναφορά PDF.");return}setWorkingId("EXPORT");setError("");try{if(popup)popup.document.body.textContent="Προετοιμασία αναφοράς…";const result=await api(archiveUrl({format,...(item?{id:item.id,q:"",supplier:"",date:""}:{})}));if(popup){popup.document.open();popup.document.write(result.html);popup.document.close()}else{const link=document.createElement("a");link.href=result.dataUrl;link.download=result.filename;link.click()}setMessage(`${result.count} παραστατικά στην εξαγωγή. Η αναφορά περιέχει στοιχεία και δεν είναι πρωτότυπο PDF προμηθευτή.`)}catch(err){popup?.close();setError(err.message)}finally{setWorkingId("")}};
  const loadMyDataStatus=async()=>{if(!storeId)return;try{setMyDataStatus(await api(`/api/commerce/documents/mydata/status?storeId=${encodeURIComponent(storeId)}`))}catch{setMyDataStatus(null)}};
  const syncMyData=async automatic=>{if(!storeId||workingId==="MYDATA")return;setWorkingId("MYDATA");setError("");if(!automatic)setMessage("");try{const result=await api("/api/commerce/documents/mydata/sync",{method:"POST",body:JSON.stringify({storeId})});if(!automatic||result.created)setMessage(result.message);await Promise.all([load(),loadMyDataStatus()])}catch(err){if(!automatic)setError(err.message)}finally{setWorkingId("")}};
  useEffect(()=>{loadMyDataStatus();const timer=setInterval(()=>{if(myDataStatus?.enabled&&!myDataStatus?.labLocked&&myDataStatus?.lastSyncAt)syncMyData(true)},10*60*1000);return()=>clearInterval(timer)},[storeId,myDataStatus?.enabled,myDataStatus?.labLocked,myDataStatus?.lastSyncAt]);
  const filtered=items;
  const groups=useMemo(()=>{const supplierMap=new Map();for(const item of filtered){const supplier=item.supplierName||"Χωρίς αντιστοίχιση προμηθευτή";if(!supplierMap.has(supplier))supplierMap.set(supplier,new Map());const days=supplierMap.get(supplier),day=dayKey(item.issueDate||item.receivedAt);if(!days.has(day))days.set(day,[]);days.get(day).push(item)}return [...supplierMap.entries()].sort((a,b)=>a[0].localeCompare(b[0],"el")).map(([supplier,days])=>({supplier,days:[...days.entries()].sort((a,b)=>b[0].localeCompare(a[0])).map(([day,rows])=>({day,rows:rows.sort((a,b)=>new Date(b.receivedAt||0)-new Date(a.receivedAt||0))}))}))},[filtered]);
  const view=async item=>{try{const result=await api(`/api/commerce/documents/inbox/${item.id}/file`);const popup=window.open();if(!popup)return;popup.document.write(result.mimeType==="application/pdf"?`<title>${result.filename}</title><iframe src="${result.dataUrl}" style="border:0;width:100vw;height:100vh"></iframe>`:`<title>${result.filename}</title><img src="${result.dataUrl}" style="max-width:100%;height:auto;display:block;margin:auto">`)}catch(err){setError(err.message)}};
  const receiveOriginal=async item=>{setWorkingId(item.id);setError("");try{const result=await api(`/api/commerce/documents/inbox/${item.id}/original`,{method:"POST",body:JSON.stringify({storeId})});setMessage(result.downloaded?"Το πρωτότυπο PDF επισυνάφθηκε για έλεγχο από τον βοηθό. Δεν έγινε καταχώρηση ή πληρωμή.":"Το πρωτότυπο υπάρχει ήδη.");await load()}catch(err){setError(err.message)}finally{setWorkingId("")}};
  const reprocess=async item=>{setWorkingId(item.id);setError("");setMessage("");try{const prepared=await api(`/api/commerce/documents/inbox/${item.id}/reprocess`,{method:"POST",body:"{}"});let lineCount=Number(prepared.productLineCount||0);if(prepared.needsRecheck){const ai=await api(`/api/commerce/ai-reader/jobs/${prepared.jobId}/ai-recheck`,{method:"POST",body:JSON.stringify({force:true})});lineCount=Array.isArray(ai?.result?.productLines)?ai.result.productLines.length:0}await api(`/api/commerce/documents/inbox/${item.id}`,{method:"PATCH",body:JSON.stringify({status:"IN_REVIEW",note:`✅ Αναγνώριση ολοκληρώθηκε • ${lineCount} γραμμές • AI job ${prepared.jobId} • χωρίς νέα πληρωμή`})});setMessage(`Το παλιό τιμολόγιο αναγνώστηκε ξανά με ${lineCount} γραμμές. Άνοιξε τον έλεγχο και την αντιστοίχιση προϊόντων.`);await load();onOpenAi?.(prepared.jobId)}catch(err){setError(err.message||"Η επανεπεξεργασία απέτυχε.")}finally{setWorkingId("")}};
  const remove=async item=>{if(!window.confirm("Να διαγραφεί οριστικά η φωτογραφία;"))return;setWorkingId(item.id);setError("");try{await api("/api/commerce/documents/inbox/"+item.id,{method:"DELETE"});setMessage("Η φωτογραφία διαγράφηκε. Μπορείς να την περάσεις ξανά.");await load()}catch(err){setError(err.message||"Η διαγραφή απέτυχε.")}finally{setWorkingId("")}};
  return <div className="invoice-inbox">
    <section className="invoice-inbox-head"><div><h2><Inbox/>Θυρίδα Τιμολογίων / Αρχείο</h2><p>Τα παραστατικά myDATA μπαίνουν πρώτα ως πρόχειρα. Η αποθήκη ενημερώνεται μόνο μετά τον έλεγχο του πρωτοτύπου.</p>{myDataStatus&&<small className={`mydata-state ${myDataStatus.enabled&&!myDataStatus.labLocked?"ready":"locked"}`}>myDATA: {myDataStatus.enabled?(myDataStatus.labLocked?"κλειδωμένο — μη έγκυρη ρύθμιση":myDataStatus.environment==="PRODUCTION"?"Παραγωγή — λήψη παραστατικών":"LAB/SANDBOX ενεργό"):"δεν έχει ενεργοποιηθεί"}{myDataStatus.lastSyncAt?` · τελευταίος έλεγχος ${when(myDataStatus.lastSyncAt)}`:""}</small>}</div><div><select value={storeId} onChange={e=>{setStoreId(e.target.value);setOffset(0);setItems([]);setMyDataStatus(null)}}>{stores.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select><button onClick={()=>syncMyData(false)} disabled={workingId==="MYDATA"||!myDataStatus?.enabled||myDataStatus?.labLocked}><CloudDownload/>{workingId==="MYDATA"?"Έλεγχος…":"Λήψη από myDATA"}</button><button onClick={load}><RefreshCw/>Ανανέωση</button></div></section>
    {error&&<div className="commerce-error">{error}</div>}{message&&<div className="commerce-success">{message}</div>}
    <section className="commerce-box"><h3><Search style={{width:17,verticalAlign:"middle"}}/> Αναζήτηση τιμολογίων</h3><div className="invoice-archive-filters"><label>Προμηθευτής<select value={supplierFilter} onChange={e=>{setSupplierFilter(e.target.value);setOffset(0)}}><option value="">Όλοι οι προμηθευτές</option>{supplierOptions.map(name=><option key={name} value={name}>{name}</option>)}</select></label><label>Ημερομηνία παραστατικού<input type="date" value={dateFilter} onChange={e=>{setDateFilter(e.target.value);setOffset(0)}}/></label><label>Αριθμός τιμολογίου / όνομα αρχείου / λέξη<input value={query} onChange={e=>{setQuery(e.target.value);setOffset(0)}} placeholder="π.χ. 12548 ή Coca Cola"/></label><button type="button" onClick={()=>{setSupplierFilter("");setDateFilter("");setQuery("");setOffset(0)}}>Καθαρισμός</button></div><div className="invoice-archive-tools"><small>{loading?"Αναζήτηση σε όλο το αρχείο…":`Βρέθηκαν ${total} από ${archiveTotal} παραστατικά · εμφάνιση ${items.length?offset+1:0}–${offset+items.length}.`}</small><button onClick={()=>exportArchive("xlsx")} disabled={loading||!!workingId||!total}>Εξαγωγή Excel (.xlsx)</button><button onClick={()=>exportArchive("pdf")} disabled={loading||!!workingId||!total}>Αναφορά PDF / Εκτύπωση</button><button onClick={()=>setOffset(Math.max(0,offset-100))} disabled={loading||offset===0}>Προηγούμενα</button><button onClick={()=>setOffset(offset+100)} disabled={loading||offset+items.length>=total}>Επόμενα</button></div><small>Οι εξαγωγές περιλαμβάνουν όλα τα αποτελέσματα των φίλτρων. Στην αναφορά επιλέξτε «Αποθήκευση ως PDF» από την εκτύπωση.</small></section>
    <section className="commerce-box"><h3>Ανά προμηθευτή → ανά ημέρα</h3>{loading?<div>Φόρτωση…</div>:groups.length===0?<div className="invoice-empty">Δεν βρέθηκαν τιμολόγια με αυτά τα φίλτρα.</div>:<div className="invoice-supplier-groups">{groups.map(group=><section className="invoice-supplier-group" key={group.supplier}><header><b>{group.supplier}</b><span>{group.days.reduce((n,d)=>n+d.rows.length,0)} παραστατικά</span></header>{group.days.map(day=><div className="invoice-day-group" key={day.day}><h4>{day.day}<span>{day.rows.length}</span></h4><div className="invoice-list">{day.rows.map(item=><article key={item.id}><div className="invoice-main"><b>{item.filename||(item.mark?`myDATA ${item.series||""} ${item.documentNumber||""}`:"Παραστατικό")}</b><small>{item.issueDate?`Ημερομηνία παραστατικού: ${dayKey(item.issueDate)} · `:""}Λήψη: {when(item.receivedAt)}</small>{item.responsibleName&&<small>Υπεύθυνος: {item.responsibleName}</small>}{item.supplierId&&<small>Κωδικός προμηθευτή: {item.supplierId}</small>}{item.note&&<p>{item.note}</p>}</div><div className="invoice-actions"><em className={item.status}>{item.mark&&item.status==="RECEIVED"?"Εισερχόμενο myDATA · προς έλεγχο":labels[item.status]||item.status}</em>{item.mark&&<button onClick={()=>exportArchive("pdf",item)} disabled={!!workingId}>Αναφορά στοιχείων PDF</button>}{item.mark&&!item.hasAttachment&&<small>{item.originalError||"Αναμονή πρωτοτύπου παρόχου"}</small>}{item.mark&&item.hasProviderOriginal&&!item.hasAttachment&&<button onClick={()=>receiveOriginal(item)} disabled={!!workingId}>Λήψη πρωτοτύπου για έλεγχο</button>}{item.hasAttachment&&<button onClick={()=>view(item)}><Eye/>Πρωτότυπο φωτογραφία/PDF</button>}{item.hasAttachment&&item.status!=="PROCESSED"&&<button onClick={()=>remove(item)} disabled={workingId===item.id}><Trash2/>{workingId===item.id?"Διαγραφή…":"Διαγραφή φωτογραφίας"}</button>}{item.hasAttachment&&item.status!=="PROCESSED"&&<button onClick={()=>reprocess(item)} disabled={workingId===item.id}><RotateCw/>{workingId===item.id?"Αναγνώριση γραμμών…":item.mark?"Έλεγχος από βοηθό AI":"Επανεπεξεργασία γραμμών"}</button>}</div></article>)}</div></div>)}</section>)}</div>}</section>
  </div>;
}
