import React,{useEffect,useMemo,useRef,useState} from "react";
import KioskStyleProductCenter from "./KioskStyleProductCenter.jsx";
import ProductDeliveryFields,{deliveryDefaults} from "./ProductDeliveryFields.jsx";
import ProductPreparationEditor from "./ProductPreparationEditor.jsx";

const num=value=>Number(value||0);
export default function KioskStyleProductCenterWithStock({api,stores=[]}){
 const hostRef=useRef(null),[catalog,setCatalog]=useState([]),[target,setTarget]=useState(null),[mode,setMode]=useState("SET"),[quantity,setQuantity]=useState(""),[logMovement,setLogMovement]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState(""),[reloadKey,setReloadKey]=useState(0),[deliveryTarget,setDeliveryTarget]=useState(null),[deliveryDraft,setDeliveryDraft]=useState(null),[preparationTarget,setPreparationTarget]=useState(null);
 const loadCatalog=async()=>{try{const rows=await api("/api/owner-products/catalog?q=");setCatalog(Array.isArray(rows)?rows:[])}catch{setCatalog([])}};useEffect(()=>{loadCatalog()},[reloadKey]);
 const bySku=useMemo(()=>{const m=new Map();for(const r of catalog)if(r.sku)m.set(String(r.sku).trim(),r);return m},[catalog]);
 const openDelivery=async product=>{setError("");setBusy(true);try{const data=await api(`/api/owner-products/${product.id}/delivery`);setDeliveryTarget(product);setDeliveryDraft(deliveryDefaults(data))}catch(e){setError(e.message)}finally{setBusy(false)}};
 useEffect(()=>{const root=hostRef.current;if(!root)return;const decorate=()=>{const rows=[...root.querySelectorAll(".kiosk-tr.items-v3:not(.head)")];rows.forEach(row=>{const c=[...row.children];if(c.length<9)return;const stock=c[c.length-1],sku=(c[2]?.textContent||"").trim(),product=bySku.get(sku);if(product&&!stock.dataset.stockPencilReady){stock.dataset.stockPencilReady="1";const txt=stock.textContent.trim();stock.innerHTML="";const b=document.createElement("button");b.type="button";b.className="mws-stock-pencil";b.innerHTML=`✎ <span>${txt||"0"}</span>`;b.onclick=e=>{e.preventDefault();e.stopPropagation();const sr=product.stores||[],pref=sr.find(s=>s.active!==false)||sr[0];setTarget({product,storeId:pref?.storeId||stores[0]?.id||""});setMode("SET");setQuantity("");setError("")};stock.appendChild(b)}});const tabs=root.querySelector(".kiosk-product-card .product-tabs"),sr=root.querySelector(".kiosk-tr.items-v3.selected-row");if(tabs&&sr){const p=bySku.get((sr.children[2]?.textContent||"").trim());if(p&&!tabs.querySelector(".mws-preparation-tab")){const b=document.createElement("button");b.type="button";b.className="mws-preparation-tab";b.textContent="Παρασκευή / Modifiers";b.onclick=e=>{e.preventDefault();setPreparationTarget(p)};tabs.appendChild(b)}if(p&&!tabs.querySelector(".mws-delivery-tab")){const b=document.createElement("button");b.type="button";b.className="mws-delivery-tab";b.textContent="E‑Delivery";b.onclick=e=>{e.preventDefault();openDelivery(p)};tabs.appendChild(b)}}};decorate();const o=new MutationObserver(decorate);o.observe(root,{childList:true,subtree:true});return()=>o.disconnect()},[bySku,catalog,stores]);
 const storeRows=target?.product?.stores||[],selectedStore=storeRows.find(s=>s.storeId===target?.storeId),currentStock=num(selectedStore?.currentStock),calculated=target?(mode==="SET"?num(quantity):mode==="ADD"?currentStock+num(quantity):currentStock-num(quantity)):0;
 const submit=async()=>{if(!target?.storeId)return setError("Δεν υπάρχει κατάστημα.");setBusy(true);try{await api(`/api/owner-products/${target.product.id}/stock-adjustment`,{method:"POST",body:JSON.stringify({storeId:target.storeId,mode,quantity:Number(quantity),logMovement})});setTarget(null);setReloadKey(x=>x+1)}catch(e){setError(e.message)}finally{setBusy(false)}};
 const saveDelivery=async()=>{if(!deliveryTarget||!deliveryDraft)return;setBusy(true);try{await api(`/api/owner-products/${deliveryTarget.id}/delivery`,{method:"PATCH",body:JSON.stringify(deliveryDraft)});setDeliveryTarget(null);setDeliveryDraft(null)}catch(e){setError(e.message)}finally{setBusy(false)}};
 return <div ref={hostRef}><style>{`.mws-stock-pencil{border:0;background:transparent;font-weight:800;color:#15355d;cursor:pointer}.mws-bulk-preparation-btn{font-weight:900!important;background:#0e6d5a!important;color:white!important}.mws-bulk-prep-dialog{width:min(900px,96vw)}.mws-bulk-prep-body{padding:18px}.mws-bulk-prep-body select{width:100%;padding:10px}.mws-bulk-prep-options{display:flex;gap:18px;margin:16px 0}.mws-bulk-prep-targets{max-height:230px;overflow:auto;border:1px solid #ddd;padding:10px}.mws-bulk-prep-success{padding:10px;background:#ecfbf5;color:#096346;font-weight:900}`}</style><KioskStyleProductCenter key={reloadKey} api={api} stores={stores}/>
 {target&&<div className="kiosk-modal-backdrop"><div className="kiosk-modal"><div className="kiosk-modal-title">Διόρθωση Stock <button onClick={()=>setTarget(null)}>×</button></div><p>{target.product.name} · {currentStock}</p><input value={quantity} onChange={e=>setQuantity(e.target.value)}/><div className="kiosk-modal-actions"><button onClick={()=>setTarget(null)}>Κλείσιμο</button><button onClick={submit}>Καταχώρηση</button></div></div></div>}
 {deliveryTarget&&deliveryDraft&&<div className="kiosk-modal-backdrop"><div className="kiosk-modal"><div className="kiosk-modal-title">{deliveryTarget.name} · E‑Delivery<button onClick={()=>setDeliveryTarget(null)}>×</button></div><ProductDeliveryFields draft={deliveryDraft} onChange={(k,v)=>setDeliveryDraft(d=>({...d,[k]:v}))}/><button onClick={saveDelivery}>Αποθήκευση</button></div></div>}
 {preparationTarget&&<ProductPreparationEditor api={api} product={preparationTarget} onClose={()=>setPreparationTarget(null)}/>} 
 </div>
}