import React,{useEffect,useMemo,useState} from "react";
import {Barcode,BarChart3,Boxes,Camera,ChevronRight,FileText,Filter,Image,Layers3,List,MessageSquare,MoreHorizontal,Plus,RefreshCw,Search,Settings2,ShoppingCart,Tag,Trash2} from "lucide-react";
import OwnerProductCenter from "./OwnerProductCenter.jsx";
import "./kiosk-style-backoffice.css";

const money=value=>`${Number(value||0).toFixed(2)} €`;
const text=value=>String(value??"").trim();
const sumStock=row=>(row.stores||[]).reduce((sum,s)=>sum+Number(s.currentStock||0),0);
const isPreparationMaterial=row=>text(row?.sku).toUpperCase().startsWith("MWS-PREP-");
const preparationUnit=row=>{const sku=text(row?.sku).toUpperCase();if(/(?:WATER|MILK|SYRUP)/.test(sku))return "ML";if(/(?:CUP|LID|STRAW|SWEETENER)/.test(sku))return "PCS";return "GR"};
const katStoreRow=row=>(row?.stores||[]).find(s=>/\bKAT\b|\bΚΑΤ\b|ΚΥΛΙΚΕΙΟ ΚΑΤ/i.test(text(s.storeName)))||null;
const preparationStock=row=>{const kat=katStoreRow(row);return kat?Number(kat.currentStock||0):sumStock(row)};
const stockText=value=>{const n=Number(value||0);return Number.isInteger(n)?String(n):n.toFixed(4).replace(/0+$/,"").replace(/\.$/,"")};
const TABS=[["basic","Βασικά στοιχεία",FileText],["barcodes","Barcodes",Barcode],["invoice","Κωδ. τιμολογίου",FileText],["comments","Σχόλια",MessageSquare],["stats","Στατιστικά",BarChart3],["other","Λοιπά",MoreHorizontal],["photo","ΦΩΤΟ",Image],["purchases","Αγορές",ShoppingCart]];
const blankNew=()=>({name:"",sku:"",barcode:"",categoryName:"",unit:"PIECE",costPrice:"0",salePrice:"0",vatRate:"24",vatVerified:true,trackStock:true,active:true});
const normalizeProductName=value=>text(value).normalize("NFD").replace(/[\u0300-\u036f]/g,"").toUpperCase().replace(/ESPRESO/g,"ESPRESSO").replace(/MACHIATO/g,"MACCHIATO").replace(/\s+/g," ").trim();
const canonicalBeverageKey=value=>{const name=normalizeProductName(value);if(/^FREDDO CAP(?:PUCCINO)? 4(?:ΑΠΛΟΣ|ΠΛΟΣ)$/.test(name))return "FREDDO CAPPUCCINO 4ΑΠΛΟΣ";if(/^FREDDO ESPRESSO 4ΠΛΟ$/.test(name))return "FREDDO ESPRESSO 4ΠΛΟ";return name};
const isBeverage=value=>/(ESPRESSO|FREDDO|CAPPUCCINO|LATTE|AMERICANO|MACCHIATO|FLAT WHITE|CORTADO|MOCHA|NESCAFE|ΦΡΑΠΕ|ΕΛΛΗΝ|ΦΙΛΤΡ|ΣΟΚΟΛΑΤ|ΤΣΑΙ|MATCHA)/.test(canonicalBeverageKey(value));
const canonicalRank=row=>{const sku=text(row?.sku).toUpperCase();if(sku.startsWith("MWS-KAT-BEV-"))return 0;if(sku.startsWith("MWS-"))return 1;if(/^\d+$/.test(sku))return 3;return 2};
const canonicalActiveRows=list=>{const active=list.filter(row=>row?.active!==false);const winners=new Map();const passthrough=[];for(const row of active){if(!isBeverage(row.name)){passthrough.push(row);continue}const key=canonicalBeverageKey(row.name);const current=winners.get(key);if(!current||canonicalRank(row)<canonicalRank(current))winners.set(key,row)}const keepIds=new Set([...passthrough,...winners.values()].map(row=>row.id));return active.filter(row=>keepIds.has(row.id))};

export default function KioskStyleProductCenter({api,stores=[]}){
  const [mode,setMode]=useState("items"),[tab,setTab]=useState("basic");
  const [rows,setRows]=useState([]),[query,setQuery]=useState(""),[category,setCategory]=useState("ALL"),[vat,setVat]=useState("ALL"),[status,setStatus]=useState("ALL"),[prepOnly,setPrepOnly]=useState(false);
  const [selected,setSelected]=useState(null),[draft,setDraft]=useState(null),[busy,setBusy]=useState(false),[error,setError]=useState(""),[message,setMessage]=useState("");
  const [checked,setChecked]=useState([]),[dialog,setDialog]=useState(null),[newDraft,setNewDraft]=useState(blankNew()),[bulk,setBulk]=useState({categoryName:"",vatRate:"",salePrice:"",active:"KEEP",trackStock:"KEEP"});
  const [bulkPrepSourceId,setBulkPrepSourceId]=useState(""),[bulkPrepCopyRecipe,setBulkPrepCopyRecipe]=useState(true),[bulkPrepCopyModifiers,setBulkPrepCopyModifiers]=useState(true),[bulkPrepResult,setBulkPrepResult]=useState("");
  const [splitPct,setSplitPct]=useState(52);

  const load=async(force=false)=>{setBusy(true);setError("");try{const bust=force?`&_=${Date.now()}`:"";const data=await api(`/api/owner-products/catalog?q=${encodeURIComponent(query.trim())}${bust}`);const list=canonicalActiveRows(Array.isArray(data)?data:[]);setRows(list);setChecked(ids=>ids.filter(id=>list.some(r=>r.id===id)));if(selected){const fresh=list.find(r=>r.id===selected.id);if(fresh)choose(fresh);else{setSelected(null);setDraft(null)}}if(force)setMessage("Η αποθήκη ανανεώθηκε με τις τελευταίες ποσότητες.")}catch(e){setError(e.message)}finally{setBusy(false)}};
  useEffect(()=>{load()},[]);
  const startResize=e=>{e.preventDefault();const host=e.currentTarget.parentElement;if(!host)return;const rect=host.getBoundingClientRect();const move=ev=>{const pct=((ev.clientX-rect.left)/rect.width)*100;setSplitPct(Math.max(34,Math.min(74,pct)))};const up=()=>{window.removeEventListener("pointermove",move);window.removeEventListener("pointerup",up);document.body.classList.remove("kiosk-resizing")};document.body.classList.add("kiosk-resizing");window.addEventListener("pointermove",move);window.addEventListener("pointerup",up,{once:true})};
  const categories=useMemo(()=>{const map=new Map();rows.forEach(r=>{const k=text(r.categoryName)||"ΧΩΡΙΣ ΚΑΤΗΓΟΡΙΑ";map.set(k,(map.get(k)||0)+1)});return [...map.entries()].sort((a,b)=>a[0].localeCompare(b[0],"el"))},[rows]);
  const vatOptions=useMemo(()=>[...new Set(rows.map(r=>String(Number(r.vatRate||0))))].sort((a,b)=>Number(a)-Number(b)),[rows]);
  const filtered=useMemo(()=>rows.filter(r=>{if(prepOnly&&!isPreparationMaterial(r))return false;const c=text(r.categoryName)||"ΧΩΡΙΣ ΚΑΤΗΓΟΡΙΑ";if(category!=="ALL"&&c!==category)return false;if(vat!=="ALL"&&String(Number(r.vatRate||0))!==vat)return false;if(status==="ACTIVE"&&r.active===false)return false;if(status==="INACTIVE"&&r.active!==false)return false;return true}),[rows,category,vat,status,prepOnly]);
  const preparationSources=useMemo(()=>rows.filter(p=>p?.active!==false&&!isPreparationMaterial(p)).sort((a,b)=>text(a.name).localeCompare(text(b.name),"el")),[rows]);
  const bulkPreparationTargets=useMemo(()=>rows.filter(r=>checked.includes(r.id)),[rows,checked]);
  const allVisible=filtered.length>0&&filtered.every(r=>checked.includes(r.id));
  const toggleAll=()=>setChecked(allVisible?checked.filter(id=>!filtered.some(r=>r.id===id)):[...new Set([...checked,...filtered.map(r=>r.id)])]);
  const toggleOne=(id,event)=>{event.stopPropagation();setChecked(x=>x.includes(id)?x.filter(v=>v!==id):[...x,id])};

  const choose=row=>{setSelected(row);setTab("basic");setDraft({name:row.name||"",sku:row.sku||"",description:row.description||"",categoryName:row.categoryName||"",unit:row.unit||"PIECE",costPrice:String(Number(row.costPrice||0)),salePrice:String(Number(row.salePrice||0)),vatRate:String(Number(row.vatRate||0)),vatVerified:Boolean(row.vatVerified),trackStock:row.trackStock!==false,active:row.active!==false,barcodes:(row.barcodes||[]).map(x=>({barcode:x.barcode||"",unitMultiplier:String(Number(x.unitMultiplier||1))}))})};
  const change=(key,value)=>setDraft(d=>({...d,[key]:value}));
  const save=async()=>{if(!selected||!draft)return;setBusy(true);setError("");setMessage("");try{await api(`/api/owner-products/${selected.id}/card`,{method:"PATCH",body:JSON.stringify({...draft,costPrice:Number(draft.costPrice||0),salePrice:Number(draft.salePrice||0),vatRate:Number(draft.vatRate||0),barcodes:draft.barcodes.filter(x=>x.barcode.trim()).map(x=>({barcode:x.barcode.trim(),unitMultiplier:Number(x.unitMultiplier||1)})),stores:(selected.stores||[]).map(s=>({storeId:s.storeId,active:s.active!==false,salePrice:Number(s.salePrice??draft.salePrice??0),minStock:s.minStock??null}))})});setMessage("Η καρτέλα είδους αποθηκεύτηκε.");await load()}catch(e){setError(e.message)}finally{setBusy(false)}};
  const createNew=async()=>{setBusy(true);setError("");try{const result=await api("/api/owner-products/new",{method:"POST",body:JSON.stringify({...newDraft,costPrice:Number(newDraft.costPrice||0),salePrice:Number(newDraft.salePrice||0),vatRate:Number(newDraft.vatRate||0),storeIds:stores.filter(s=>s.active!==false).map(s=>s.id)})});setDialog(null);setNewDraft(blankNew());setMessage("Το νέο είδος δημιουργήθηκε.");await load();const fresh=await api(`/api/owner-products/catalog?q=${encodeURIComponent(newDraft.sku||newDraft.name)}`);const found=(fresh||[]).find(x=>x.id===result.id);if(found)choose(found)}catch(e){setError(e.message)}finally{setBusy(false)}};
  const applyBulk=async()=>{if(!checked.length)return setError("Επίλεξε πρώτα προϊόντα από τα κουτάκια.");const payload={productIds:checked};if(bulk.categoryName!=="")payload.categoryName=bulk.categoryName;if(bulk.vatRate!=="")payload.vatRate=Number(bulk.vatRate);if(bulk.salePrice!=="")payload.salePrice=Number(bulk.salePrice);if(bulk.active!=="KEEP")payload.active=bulk.active==="YES";if(bulk.trackStock!=="KEEP")payload.trackStock=bulk.trackStock==="YES";if(Object.keys(payload).length===1)return setError("Επίλεξε τουλάχιστον μία αλλαγή.");setBusy(true);setError("");try{const r=await api("/api/owner-products/bulk-card",{method:"PATCH",body:JSON.stringify(payload)});setDialog(null);setMessage(`Η ομαδική διόρθωση εφαρμόστηκε σε ${r.changed} προϊόντα.`);await load()}catch(e){setError(e.message)}finally{setBusy(false)}};
  const openBulkPreparation=()=>{if(!bulkPreparationTargets.length)return setError("Επίλεξε πρώτα προϊόντα από τα κουτάκια.");setError("");setBulkPrepResult("");setBulkPrepSourceId("");setBulkPrepCopyRecipe(true);setBulkPrepCopyModifiers(true);setDialog("bulkPreparation")};
  const applyBulkPreparation=async()=>{if(!bulkPrepSourceId)return setError("Διάλεξε πρώτα το είδος-πηγή.");if(!bulkPrepCopyRecipe&&!bulkPrepCopyModifiers)return setError("Επίλεξε Συνταγή, Modifiers ή και τα δύο.");const targets=bulkPreparationTargets.filter(p=>String(p.id)!==String(bulkPrepSourceId));if(!targets.length)return setError("Το είδος-πηγή δεν μπορεί να είναι το μοναδικό είδος προορισμού.");setBusy(true);setError("");setBulkPrepResult("");try{const source=await api(`/api/management/preparation/products/${bulkPrepSourceId}`);let changed=0;for(const product of targets){const current=await api(`/api/management/preparation/products/${product.id}`);if(bulkPrepCopyRecipe){for(const line of current.recipe||[])await api(`/api/management/preparation/recipe/${line.id}`,{method:"DELETE"});for(const line of source.recipe||[])await api(`/api/management/preparation/products/${product.id}/recipe`,{method:"POST",body:JSON.stringify({ingredientProductId:line.ingredientProductId,quantity:Number(line.quantity),unit:line.unit,automatic:line.automatic!==false})})}if(bulkPrepCopyModifiers){for(const group of current.groups||[])await api(`/api/management/preparation/products/${product.id}/groups/${group.groupId}`,{method:"DELETE"});for(const group of source.groups||[])await api(`/api/management/preparation/products/${product.id}/groups`,{method:"POST",body:JSON.stringify({groupId:group.groupId,required:Boolean(group.required),minSelections:Number(group.minSelections||0),maxSelections:Number(group.maxSelections||1),sequence:Number(group.sequence||0)})})}changed++}setBulkPrepResult(`Ολοκληρώθηκε: ${changed} είδη.`);setMessage(`Συνταγή / Modifiers αντιγράφηκαν σε ${changed} είδη.`)}catch(e){setError(e.message)}finally{setBusy(false)}};

  if(mode==="full")return <div className="kiosk-shell"><div className="kiosk-return"><button onClick={()=>setMode("items")}><List/>Επιστροφή στα Είδη</button><span>Πλήρης εμπορική διαχείριση MyWorkStation</span></div><OwnerProductCenter api={api} stores={stores}/></div>;

  return <div className="kiosk-shell">
    <div className="kiosk-topbar"><div><strong>MyWorkStation BackOffice</strong><span>Λογική Kiosk Manager · σύγχρονη έκδοση</span></div><div className="kiosk-top-actions"><button onClick={()=>load(true)} disabled={busy}><RefreshCw/>Ανανέωση</button><button className="primary" onClick={()=>setMode("full")}><Settings2/>Πλήρης διαχείριση</button></div></div>
    <div className="kiosk-main-tabs"><button className={mode==="items"&&!prepOnly?"active":""} onClick={()=>{setMode("items");setPrepOnly(false)}}><Boxes/>Είδη αποθήκης</button><button className={mode==="items"&&prepOnly?"active":""} onClick={()=>{setMode("items");setPrepOnly(true);setCategory("ALL");setVat("ALL");setStatus("ALL");setSelected(null);setDraft(null);load(true)}}><ShoppingCart/>Υλικά Παρασκευής</button><button className={mode==="categories"?"active":""} onClick={()=>{setMode("categories");setPrepOnly(false)}}><Layers3/>Κατηγορίες / Υποκατηγορίες</button></div>
    {error&&<div className="kiosk-error">{error}</div>}{message&&<div className="kiosk-success">{message}</div>}
    {mode==="categories"?<div className="kiosk-category-workspace"><section className="kiosk-grid-panel"><div className="kiosk-grid-title"><b>Κατηγορίες ειδών</b><span>{categories.length} κατηγορίες</span></div><div className="kiosk-table kiosk-category-table"><div className="kiosk-tr head"><span>Περιγραφή</span><span>Είδη</span><span>% ειδών</span><span></span></div>{categories.map(([name,count])=><button className="kiosk-tr" key={name} onClick={()=>{setCategory(name);setPrepOnly(false);setMode("items")}}><span><Tag/>{name}</span><span>{count}</span><span>{rows.length?((count/rows.length)*100).toFixed(2):"0.00"}%</span><span><ChevronRight/></span></button>)}</div></section><section className="kiosk-grid-panel empty-panel"><Layers3/><b>Υποκατηγορίες</b><p>Θα συνδεθούν στο πραγματικό μοντέλο προϊόντων χωρίς να αλλάξει η γνωστή ροή.</p></section></div>:
    <div className="kiosk-items-v2 kiosk-resizable" style={{"--kiosk-list-pct":`${splitPct}%`}}><section className="kiosk-grid-panel product-list-panel">
      <div className="kiosk-toolbar"><div className="kiosk-filters"><select value={category} onChange={e=>setCategory(e.target.value)}><option value="ALL">Όλες οι κατηγορίες</option>{categories.map(([name])=><option key={name}>{name}</option>)}</select><select value={vat} onChange={e=>setVat(e.target.value)}><option value="ALL">Όλα τα ΦΠΑ</option>{vatOptions.map(v=><option key={v} value={v}>ΦΠΑ {v}%</option>)}</select></div><form onSubmit={e=>{e.preventDefault();load()}}><Search/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Περιγραφή, κωδικός ή barcode"/><button>Αναζήτηση</button></form><div className="kiosk-filters"><Filter/><select value={status} onChange={e=>setStatus(e.target.value)}><option value="ALL">Όλα</option><option value="ACTIVE">Ενεργά</option><option value="INACTIVE">Ανενεργά</option></select></div></div>
      <div className="kiosk-grid-title"><b>{filtered.length} {prepOnly?"υλικά":"προϊόντα"}</b><span>{checked.length?`${checked.length} επιλεγμένα · `:""}{prepOnly?"Υλικά παρασκευής · πραγματικό stock ΚΑΤ":"Αρχείο ειδών / αποθήκη"}</span></div>
      <div className="kiosk-table"><div className={`kiosk-tr head items-v3 ${prepOnly?"prep-stock-row":""}`}><span></span><span className="check-cell"><input type="checkbox" checked={allVisible} onChange={toggleAll} title="Επιλογή όλων"/></span><span>Κωδικός</span><span>Barcode</span><span>Περιγραφή</span><span>Κατηγορία</span><span>ΦΠΑ</span><span>Λιανική</span><span>{prepOnly?"Stock ΚΑΤ / Μονάδα":"Stock"}</span></div>{filtered.map(r=>{const stock=prepOnly?preparationStock(r):sumStock(r),unit=prepOnly?preparationUnit(r):"";return <div key={r.id} className={`kiosk-tr items-v3 ${prepOnly?"prep-stock-row":""} ${selected?.id===r.id?"selected-row":""}`} onClick={()=>choose(r)} role="button" tabIndex={0}><span className="edit-cell">✎</span><span className="check-cell"><input type="checkbox" checked={checked.includes(r.id)} onChange={e=>toggleOne(r.id,e)} onClick={e=>e.stopPropagation()}/></span><span>{r.sku||"—"}</span><span>{(r.barcodes||[])[0]?.barcode||"—"}</span><span><b>{r.name}</b></span><span>{r.categoryName||"ΧΩΡΙΣ ΚΑΤΗΓΟΡΙΑ"}</span><span>{Number(r.vatRate||0)}%</span><span><b>{money(r.salePrice)}</b></span><span className="prep-stock-value" title={prepOnly?`ΚΑΤ: ${stockText(stock)} ${unit}`:stockText(stock)}><b>{stockText(stock)}</b>{prepOnly?` ${unit}`:""}</span></div>})}</div>
      <div className="kiosk-list-footer"><button onClick={()=>{setNewDraft(blankNew());setDialog("new")}}><Plus/>Νέο είδος</button><button disabled={!checked.length} onClick={()=>setDialog("bulk")}>Ομαδική διόρθωση {checked.length?`(${checked.length})`:""}</button><button className="mws-bulk-preparation-btn" disabled={!checked.length} onClick={openBulkPreparation}>Συνταγές / Modifiers {checked.length?`(${checked.length})`:""}</button><button onClick={()=>setMode("full")}>Εισαγωγή από Excel</button><button onClick={()=>window.print()}>Εκτύπωση</button></div>
    </section><div className="kiosk-splitter" onPointerDown={startResize} title="Σύρε για να μεγαλώσεις ή να μικρύνεις την αποθήκη"><span/></div>
    <aside className="kiosk-product-card kiosk-product-card-v2">{selected&&draft?<><div className="kiosk-card-head"><div><h3>{selected.name}</h3><small><span className={draft.active?"status-on":"status-off"}>{draft.active?"Ενεργό":"Ανενεργό"}</span> · Κωδικός: {selected.sku||"—"}</small></div><button className="card-close" onClick={()=>{setSelected(null);setDraft(null)}}>×</button></div><div className="product-tabs">{TABS.map(([id,label,Icon])=><button key={id} className={tab===id?"active":""} onClick={()=>setTab(id)}><Icon/>{label}</button>)}</div><div className="product-tab-body">
      {tab==="basic"&&<div className="product-form-grid"><label>Περιγραφή<input value={draft.name} onChange={e=>change("name",e.target.value)}/></label><label>Εσωτερικός Κωδικός<input value={draft.sku} onChange={e=>change("sku",e.target.value)}/></label><label>Κατηγορία<input value={draft.categoryName} onChange={e=>change("categoryName",e.target.value)}/></label><label>Υποκατηγορία<input value={selected.subcategoryName||""} placeholder="Χωρίς υποκατηγορία" readOnly/></label><label>Εταιρεία<input value={selected.companyName||""} placeholder="Χωρίς εταιρεία" readOnly/></label><label>Προμηθευτής<input value={selected.supplierName||""} placeholder="Χωρίς προμηθευτή" readOnly/></label><label>Τιμή αγοράς<input type="number" step="0.01" value={draft.costPrice} onChange={e=>change("costPrice",e.target.value)}/></label><label>Τμήμα ΦΠΑ<input type="number" step="0.01" value={draft.vatRate} onChange={e=>change("vatRate",e.target.value)}/></label><label>Τιμή λιανικής<input type="number" step="0.01" value={draft.salePrice} onChange={e=>change("salePrice",e.target.value)}/></label><label>Μονάδα μέτρησης<input value={prepOnly&&isPreparationMaterial(selected)?preparationUnit(selected):draft.unit} onChange={e=>change("unit",e.target.value)} readOnly={prepOnly&&isPreparationMaterial(selected)}/></label><label>Alarm Stock<input value={(selected.stores||[])[0]?.minStock??""} readOnly/></label><label>Αποθήκη<input value={`${stockText(prepOnly&&isPreparationMaterial(selected)?preparationStock(selected):sumStock(selected))}${prepOnly&&isPreparationMaterial(selected)?` ${preparationUnit(selected)}`:""}`} readOnly/></label><div className="product-checks"><label><input type="checkbox" checked={draft.active} onChange={e=>change("active",e.target.checked)}/> Ενεργό</label><label><input type="checkbox" checked={draft.trackStock} onChange={e=>change("trackStock",e.target.checked)}/> Παρακολούθηση stock</label><label><input type="checkbox" checked={draft.vatVerified} onChange={e=>change("vatVerified",e.target.checked)}/> Επιβεβαιωμένο ΦΠΑ</label></div></div>}
      {tab==="barcodes"&&<div className="tab-table"><div className="tab-row head"><span>Barcode</span><span>Συσκευασία</span><span></span></div>{draft.barcodes.map((b,i)=><div className="tab-row" key={i}><input value={b.barcode} onChange={e=>setDraft(d=>({...d,barcodes:d.barcodes.map((x,j)=>j===i?{...x,barcode:e.target.value}:x)}))}/><input value={b.unitMultiplier} onChange={e=>setDraft(d=>({...d,barcodes:d.barcodes.map((x,j)=>j===i?{...x,unitMultiplier:e.target.value}:x)}))}/><button onClick={()=>setDraft(d=>({...d,barcodes:d.barcodes.filter((_,j)=>j!==i)}))}><Trash2/></button></div>)}<button className="add-line" onClick={()=>setDraft(d=>({...d,barcodes:[...d.barcodes,{barcode:"",unitMultiplier:"1"}]}))}><Plus/>Νέο barcode</button></div>}
      {tab==="invoice"&&<div className="empty-tab"><FileText/><b>Κωδικοί τιμολογίου / προμηθευτή</b><p>Δεν υπάρχουν αποθηκευμένες εγγραφές στο σημερινό μοντέλο.</p></div>}{tab==="comments"&&<div className="empty-tab"><MessageSquare/><b>Παρατηρήσεις / Σχόλια ετικέτας</b></div>}{tab==="stats"&&<div className="stats-grid"><div><span>Αποθήκη</span><b>{stockText(prepOnly&&isPreparationMaterial(selected)?preparationStock(selected):sumStock(selected))}{prepOnly&&isPreparationMaterial(selected)?` ${preparationUnit(selected)}`:""}</b></div><div><span>Μέση λιανική</span><b>{money(selected.salePrice)}</b></div><div><span>Μέση αγορά</span><b>{money(selected.costPrice)}</b></div><div><span>Margin</span><b>{Number(selected.salePrice)>0?(((Number(selected.salePrice)-Number(selected.costPrice||0))/Number(selected.salePrice))*100).toFixed(2):"0.00"}%</b></div><div><span>ΦΠΑ</span><b>{Number(selected.vatRate||0)}%</b></div><div><span>Barcodes</span><b>{(selected.barcodes||[]).length}</b></div></div>}{tab==="other"&&<div className="product-form-grid"><label>Ειδοποιήσεις (PoS)<input value={selected.posNotice||""} readOnly/></label><label>Θέση<input value={selected.location||""} readOnly/></label></div>}{tab==="photo"&&<div className="empty-tab"><Camera/><b>Αρχείο εικόνας προϊόντος</b></div>}{tab==="purchases"&&<div className="empty-tab"><ShoppingCart/><b>Αναζήτηση αγορών με ημερομηνία</b></div>}
      </div><div className="product-card-actions"><button onClick={()=>{setSelected(null);setDraft(null)}}>Επιστροφή</button><span/><button className="primary" onClick={save} disabled={busy}>Καταχώρηση</button><button onClick={()=>choose(selected)}>Ακύρωση</button></div></>:<div className="kiosk-empty-card"><Boxes/><b>{prepOnly?"Επίλεξε υλικό":"Επίλεξε είδος"}</b><span>Πάτησε το μολύβι ή τη γραμμή προϊόντος.</span></div>}</aside></div>}

    {dialog==="new"&&<div className="kiosk-modal-backdrop"><div className="kiosk-modal product-create-modal"><div className="kiosk-modal-title">Νέο είδος <button onClick={()=>setDialog(null)}>×</button></div><div className="product-form-grid modal-grid"><label>Περιγραφή<input autoFocus value={newDraft.name} onChange={e=>setNewDraft(d=>({...d,name:e.target.value}))}/></label><label>Εσωτερικός κωδικός<input value={newDraft.sku} onChange={e=>setNewDraft(d=>({...d,sku:e.target.value}))}/></label><label>Barcode<input value={newDraft.barcode} onChange={e=>setNewDraft(d=>({...d,barcode:e.target.value}))}/></label><label>Κατηγορία<input value={newDraft.categoryName} onChange={e=>setNewDraft(d=>({...d,categoryName:e.target.value}))}/></label><label>Τιμή αγοράς<input type="number" step="0.01" value={newDraft.costPrice} onChange={e=>setNewDraft(d=>({...d,costPrice:e.target.value}))}/></label><label>Τιμή λιανικής<input type="number" step="0.01" value={newDraft.salePrice} onChange={e=>setNewDraft(d=>({...d,salePrice:e.target.value}))}/></label><label>ΦΠΑ %<input type="number" value={newDraft.vatRate} onChange={e=>setNewDraft(d=>({...d,vatRate:e.target.value}))}/></label><label>Μονάδα μέτρησης<select value={newDraft.unit} onChange={e=>setNewDraft(d=>({...d,unit:e.target.value}))}><option value="PIECE">ΤΕΜ</option><option value="KG">KG</option><option value="LITER">LITER</option><option value="PACKAGE">PACKAGE</option></select></label><div className="product-checks"><label><input type="checkbox" checked={newDraft.active} onChange={e=>setNewDraft(d=>({...d,active:e.target.checked}))}/> Ενεργό</label><label><input type="checkbox" checked={newDraft.trackStock} onChange={e=>setNewDraft(d=>({...d,trackStock:e.target.checked}))}/> Παρακολούθηση stock</label><label><input type="checkbox" checked={newDraft.vatVerified} onChange={e=>setNewDraft(d=>({...d,vatVerified:e.target.checked}))}/> Επιβεβαιωμένο ΦΠΑ</label></div></div><div className="kiosk-modal-actions"><button onClick={()=>setDialog(null)}>Ακύρωση</button><button className="primary" onClick={createNew} disabled={busy||newDraft.name.trim().length<2}>Καταχώρηση</button></div></div></div>}
    {dialog==="bulk"&&<div className="kiosk-modal-backdrop"><div className="kiosk-modal"><div className="kiosk-modal-title">Ομαδική διόρθωση · {checked.length} είδη <button onClick={()=>setDialog(null)}>×</button></div><p className="bulk-note">Συμπλήρωσε μόνο τα πεδία που θέλεις να αλλάξουν. Τα κενά μένουν όπως είναι.</p><div className="product-form-grid modal-grid"><label>Κατηγορία<input value={bulk.categoryName} placeholder="Χωρίς αλλαγή" onChange={e=>setBulk(d=>({...d,categoryName:e.target.value}))}/></label><label>ΦΠΑ %<input type="number" value={bulk.vatRate} placeholder="Χωρίς αλλαγή" onChange={e=>setBulk(d=>({...d,vatRate:e.target.value}))}/></label><label>Τιμή λιανικής<input type="number" step="0.01" value={bulk.salePrice} placeholder="Χωρίς αλλαγή" onChange={e=>setBulk(d=>({...d,salePrice:e.target.value}))}/></label><label>Κατάσταση<select value={bulk.active} onChange={e=>setBulk(d=>({...d,active:e.target.value}))}><option value="KEEP">Χωρίς αλλαγή</option><option value="YES">Ενεργά</option><option value="NO">Ανενεργά</option></select></label><label>Παρακολούθηση stock<select value={bulk.trackStock} onChange={e=>setBulk(d=>({...d,trackStock:e.target.value}))}><option value="KEEP">Χωρίς αλλαγή</option><option value="YES">Ναι</option><option value="NO">Όχι</option></select></label></div><div className="kiosk-modal-actions"><button onClick={()=>setDialog(null)}>Ακύρωση</button><button className="primary" onClick={applyBulk} disabled={busy}>Εφαρμογή στα επιλεγμένα</button></div></div></div>}
    {dialog==="bulkPreparation"&&<div className="kiosk-modal-backdrop"><div className="kiosk-modal mws-bulk-prep-dialog"><div className="kiosk-modal-title">Ομαδική Συνταγή / Modifiers · {bulkPreparationTargets.length} είδη <button onClick={()=>setDialog(null)}>×</button></div><div className="mws-bulk-prep-body"><label>Είδος-πηγή<select value={bulkPrepSourceId} onChange={e=>setBulkPrepSourceId(e.target.value)}><option value="">Επίλεξε…</option>{preparationSources.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label><div className="mws-bulk-prep-options"><label><input type="checkbox" checked={bulkPrepCopyRecipe} onChange={e=>setBulkPrepCopyRecipe(e.target.checked)}/> ΣΥΝΤΑΓΗ</label><label><input type="checkbox" checked={bulkPrepCopyModifiers} onChange={e=>setBulkPrepCopyModifiers(e.target.checked)}/> MODIFIERS</label></div><div className="mws-bulk-prep-targets"><b>Προορισμοί: {bulkPreparationTargets.length}</b>{bulkPreparationTargets.map(p=><div key={p.id}>{p.name}</div>)}</div>{bulkPrepResult&&<div className="mws-bulk-prep-success">{bulkPrepResult}</div>}</div><div className="kiosk-modal-actions"><button onClick={()=>setDialog(null)}>Κλείσιμο</button><button className="primary" disabled={busy||!bulkPrepSourceId||(!bulkPrepCopyRecipe&&!bulkPrepCopyModifiers)} onClick={applyBulkPreparation}>Αποστολή στα επιλεγμένα</button></div></div></div>}
  </div>;
}