import React,{useEffect,useState} from "react";
import {Check,Download,Edit3,Plus,RefreshCw,Trash2,X} from "lucide-react";
import "./management-business-units.css";

const fmtDate=v=>v?new Date(v).toLocaleString("el-GR",{day:"2-digit",month:"2-digit",year:"numeric",hour:"2-digit",minute:"2-digit",second:"2-digit"}):"—";
const esc=v=>`"${String(v??"").replaceAll('"','""')}"`;
function downloadCsv(name,rows){const blob=new Blob(["\ufeff"+rows.map(r=>r.map(esc).join(";")).join("\n")],{type:"text/csv;charset=utf-8"});const a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
function Modal({title,children,onClose,wide=false}){return <div className="mbu-backdrop"><section className={`mbu-modal${wide?" wide":""}`}><header><b>{title}</b><button onClick={onClose}><X/></button></header>{children}</section></div>}
function BankEditor({item,busy,onClose,onSave}){
  const [internalCode,setInternalCode]=useState(item?.internalCode||"");const [name,setName]=useState(item?.name||"");const [accountingAccount,setAccountingAccount]=useState(item?.accountingAccount||"");const [auxiliaryName,setAuxiliaryName]=useState(item?.auxiliaryName||"");const [active,setActive]=useState(item?.active!==false);
  return <><div className="mbu-form"><label>εσωτ. κωδ<input autoFocus value={internalCode} onChange={e=>setInternalCode(e.target.value)}/></label><label>Ονομασία<input value={name} onChange={e=>setName(e.target.value)}/></label><label>Λογ. Λογιστικής<input value={accountingAccount} onChange={e=>setAccountingAccount(e.target.value)}/></label><label>Βοηθητική ονομασία<input value={auxiliaryName} onChange={e=>setAuxiliaryName(e.target.value)}/></label><label className="check"><input type="checkbox" checked={active} onChange={e=>setActive(e.target.checked)}/> ενεργό</label></div><footer><button onClick={onClose}><X/>Επιστροφή</button><button className="primary" disabled={busy||!internalCode.trim()||!name.trim()} onClick={()=>onSave({internalCode:internalCode.trim(),name:name.trim(),accountingAccount:accountingAccount.trim()||null,auxiliaryName:auxiliaryName.trim()||null,active})}><Check/>Καταχώρηση</button></footer></>
}
function ShippingEditor({item,busy,onClose,onSave}){
  const [code,setCode]=useState(item?.code||"");const [description,setDescription]=useState(item?.description||"");const [active,setActive]=useState(item?.active!==false);
  return <><div className="mbu-form shipping"><label>κωδικός:<input autoFocus value={code} onChange={e=>setCode(e.target.value)}/></label><label>Ονομασία:<input value={description} onChange={e=>setDescription(e.target.value)}/></label><label className="check"><input type="checkbox" checked={active} onChange={e=>setActive(e.target.checked)}/> ενεργό</label></div><footer><button onClick={onClose}><X/>Επιστροφή</button><button className="primary" disabled={busy||!code.trim()||!description.trim()} onClick={()=>onSave({code:code.trim(),description:description.trim(),active})}><Check/>Καταχώρηση</button></footer></>
}
function TerminalEditor({item,banks,busy,onClose,onSave}){
  const [bankId,setBankId]=useState(item?.bankId||banks[0]?.id||"");const [name,setName]=useState(item?.name||"");const [tid,setTid]=useState(item?.tid||"");const [paymentMethodCode,setPaymentMethodCode]=useState(item?.paymentMethodCode||"");const [iris,setIris]=useState(item?.iris===true);const [helperField1,setHelperField1]=useState(item?.helperField1||"");const [deferredCode,setDeferredCode]=useState(item?.deferredCode||"");const [helperField3,setHelperField3]=useState(item?.helperField3||"");const [ipAddress,setIpAddress]=useState(item?.ipAddress||"");const [port,setPort]=useState(item?.port==null?"":String(item.port));const [onlineMiddleware,setOnlineMiddleware]=useState(item?.onlineMiddleware===true);const [notes,setNotes]=useState(item?.notes||"");const [active,setActive]=useState(item?.active!==false);
  useEffect(()=>{if(!bankId&&banks[0]?.id)setBankId(banks[0].id)},[banks,bankId]);
  const valid=bankId&&name.trim()&&paymentMethodCode.trim()&&(!port||(+port>=1&&+port<=65535));
  return <><div className="mbu-form terminal"><label className="bank">τράπεζα:<select value={bankId} onChange={e=>setBankId(e.target.value)}><option value="">Επιλογή τράπεζας</option>{banks.map(b=><option key={b.id} value={b.id}>{b.name}</option>)}</select></label><label className="check"><input type="checkbox" checked={active} onChange={e=>setActive(e.target.checked)}/> ενεργό</label><label className="check"><input type="checkbox" checked={iris} onChange={e=>setIris(e.target.checked)}/> IRIS</label><label>Ονομασία:<input autoFocus value={name} onChange={e=>setName(e.target.value)}/></label><label>κωδ. τρόπου πληρωμής:<input value={paymentMethodCode} onChange={e=>setPaymentMethodCode(e.target.value)}/></label><label>TID:<input value={tid} onChange={e=>setTid(e.target.value)}/></label><label>κωδ. ετεροχρ:<input value={deferredCode} onChange={e=>setDeferredCode(e.target.value)}/></label><label>βοηθ. πεδίο 1:<input value={helperField1} onChange={e=>setHelperField1(e.target.value)}/></label><label>δ/νση IP:<input value={ipAddress} onChange={e=>setIpAddress(e.target.value)}/></label><label>port:<input type="number" min="1" max="65535" value={port} onChange={e=>setPort(e.target.value)}/></label><label>βοηθ. πεδίο 3:<input value={helperField3} onChange={e=>setHelperField3(e.target.value)}/></label><label className="check online"><input type="checkbox" checked={onlineMiddleware} onChange={e=>setOnlineMiddleware(e.target.checked)}/> On Line (1155 / middleware)</label><label className="notes">παρατηρήσεις:<textarea value={notes} onChange={e=>setNotes(e.target.value)}/></label></div><footer><button onClick={onClose}><X/>Επιστροφή</button><button className="primary" disabled={busy||!valid} onClick={()=>onSave({bankId,name:name.trim(),tid:tid.trim()||null,paymentMethodCode:paymentMethodCode.trim(),iris,helperField1:helperField1.trim()||null,deferredCode:deferredCode.trim()||null,helperField3:helperField3.trim()||null,ipAddress:ipAddress.trim()||null,port:port?Number(port):null,onlineMiddleware,notes:notes.trim()||null,active})}><Check/>Καταχώρηση</button></footer></>
}
export default function ManagementBusinessUnitsPanel({api,mode,onClose}){
  const [items,setItems]=useState([]),[banks,setBanks]=useState([]),[busy,setBusy]=useState(false),[error,setError]=useState(""),[message,setMessage]=useState(""),[dialog,setDialog]=useState(null);
  const endpoint=mode==="banks"?"/api/management/business-units/banks":mode==="shipping"?"/api/management/business-units/shipping-methods":"/api/management/business-units/pos-terminals";
  const load=async()=>{setBusy(true);setError("");try{if(mode==="terminals"){const [data,bankData]=await Promise.all([api(endpoint),api("/api/management/business-units/banks")]);setItems(data.items||[]);setBanks(bankData.items||[])}else{const data=await api(endpoint);setItems(data.items||[])}}catch(e){setError(e.message)}finally{setBusy(false)}};
  useEffect(()=>{setDialog(null);setMessage("");load()},[mode]);
  const save=async payload=>{setBusy(true);setError("");try{if(dialog?.item)await api(`${endpoint}/${dialog.item.id}`,{method:"PATCH",body:JSON.stringify(payload)});else await api(endpoint,{method:"POST",body:JSON.stringify(payload)});setDialog(null);setMessage(mode==="banks"?"Η τράπεζα αποθηκεύτηκε.":mode==="shipping"?"Ο τρόπος αποστολής αποθηκεύτηκε.":"Το PoS τερματικό αποθηκεύτηκε.");await load()}catch(e){setError(e.message)}finally{setBusy(false)}};
  const remove=async item=>{const label=mode==="banks"?item.name:mode==="shipping"?item.description:item.name;if(!window.confirm(`Να απενεργοποιηθεί «${label}»;`))return;setBusy(true);setError("");try{await api(`${endpoint}/${item.id}`,{method:"DELETE"});setMessage("Η εγγραφή απενεργοποιήθηκε χωρίς διαγραφή ιστορικού.");await load()}catch(e){setError(e.message)}finally{setBusy(false)}};
  const exportCsv=()=>mode==="banks"?downloadCsv("trapezes.csv",[["εσωτ. κωδ","Ονομασία","Λογ. Λογιστικής","Βοηθητική ονομασία"],...items.map(i=>[i.internalCode,i.name,i.accountingAccount||"",i.auxiliaryName||""])]):downloadCsv("tropoi-apostolis.csv",[["Κωδ","Περιγραφή","καταχώρηση","ενημέρωση"],...items.map(i=>[i.code,i.description,fmtDate(i.createdAt),fmtDate(i.updatedAt)])]);
  let body;
  if(mode==="banks")body=<><div className="mbu-row bank head"><span>εσωτ. κωδ</span><span>Ονομασία</span><span>Λογ. Λογιστικής</span><span>Βοηθητική ονομασία</span><span></span></div><div className="mbu-list">{items.map(item=><div className="mbu-row bank" key={item.id}><button className="code-edit" onClick={()=>setDialog({item})}><Edit3/><b>{item.internalCode}</b></button><button className="description" onClick={()=>setDialog({item})}>{item.name}</button><span>{item.accountingAccount||"—"}</span><span>{item.auxiliaryName||"—"}</span><button className="danger" onClick={()=>remove(item)}><Trash2/></button></div>)}{!items.length&&!busy&&<div className="mbu-empty">Δεν υπάρχουν ακόμη καταχωρημένες τράπεζες.</div>}</div></>;
  else if(mode==="shipping")body=<><div className="mbu-row shipping head"><span>Κωδ</span><span>Περιγραφή</span><span>καταχώρηση</span><span>ενημέρωση</span><span></span></div><div className="mbu-list">{items.map(item=><div className="mbu-row shipping" key={item.id}><span>{item.code}</span><button className="description" onClick={()=>setDialog({item})}><Edit3/>{item.description}</button><span>{fmtDate(item.createdAt)}</span><span>{fmtDate(item.updatedAt)}</span><button className="danger" onClick={()=>remove(item)}><Trash2/></button></div>)}{!items.length&&!busy&&<div className="mbu-empty">Δεν υπάρχουν ακόμη τρόποι αποστολής.</div>}</div></>;
  else body=<><div className="mbu-row terminal head"><span>Τράπεζα</span><span>Ονομασία τερματικού<br/>TID</span><span>τρόπος πληρωμής</span><span>IRIS<br/>IRIS πληρωμή</span><span>βοηθ. πεδίο 1<br/>κωδ. ετεροχρ</span><span>ενημέρωση<br/>παρατηρήσεις</span><span></span></div><div className="mbu-list">{items.map(item=><div className="mbu-row terminal" key={item.id}><b>{item.bankName||"—"}</b><button className="description stacked" onClick={()=>setDialog({item})}><span><Edit3/>{item.name}</span><small>{item.tid||"—"}</small></button><b>{item.paymentMethodCode}</b><span><input className="mbu-readonly-check" type="checkbox" checked={item.iris===true} readOnly/></span><span className="stacked-text"><b>{item.helperField1||"—"}</b><small>{item.deferredCode||"—"}</small></span><span className="stacked-text"><b>{fmtDate(item.updatedAt)}</b><small>{item.notes||"—"}</small></span><button className="danger" onClick={()=>remove(item)}><Trash2/></button></div>)}{!items.length&&!busy&&<div className="mbu-empty">Δεν υπάρχουν ακόμη καταχωρημένα PoS τερματικά.</div>}</div></>;
  const title=mode==="banks"?(dialog?.item?"Διόρθωση τράπεζας":"Νέα τράπεζα"):mode==="shipping"?(dialog?.item?"Διόρθωση τρόπου αποστολής":"Νέος τρόπος αποστολής"):(dialog?.item?"Διόρθωση PoS τερματικού":"Νέο PoS τερματικό");
  return <div className="mbu-suite">{error&&<div className="mbu-alert error">{error}</div>}{message&&<div className="mbu-alert success">{message}</div>}<section className={`mbu-card ${mode}`}>{body}</section><div className="mbu-footer"><button onClick={onClose}><X/>Κλείσιμο</button><button onClick={load} disabled={busy}><RefreshCw/>Ανανέωση</button><button className="primary" onClick={()=>setDialog({item:null})} disabled={mode==="terminals"&&!banks.length}><Plus/>Νέα εγγραφή</button>{mode!=="terminals"&&<button onClick={exportCsv}><Download/>Excel / CSV</button>}{mode==="terminals"&&!banks.length&&<span className="mbu-hint">Δημιουργήστε πρώτα Τράπεζα για να προσθέσετε PoS τερματικό.</span>}</div>{dialog&&<Modal title={title} wide={mode==="terminals"} onClose={()=>setDialog(null)}>{mode==="banks"?<BankEditor item={dialog.item} busy={busy} onClose={()=>setDialog(null)} onSave={save}/>:mode==="shipping"?<ShippingEditor item={dialog.item} busy={busy} onClose={()=>setDialog(null)} onSave={save}/>:<TerminalEditor item={dialog.item} banks={banks} busy={busy} onClose={()=>setDialog(null)} onSave={save}/>}</Modal>}</div>;
}
