import React,{useEffect,useState} from "react";
import {Check,Download,Edit3,Plus,RefreshCw,RotateCw,Trash2,X} from "lucide-react";
import "./management-professions.css";

const esc=v=>`"${String(v??"").replaceAll('"','""')}"`;
function downloadCsv(rows){const csv="\ufeff"+[["Κωδ","Περιγραφή","Ενεργό"],...rows.map(r=>[r.code||"",r.description,r.active?"ΝΑΙ":"ΟΧΙ"])].map(r=>r.map(esc).join(";")).join("\n");const a=document.createElement("a");a.href=URL.createObjectURL(new Blob([csv],{type:"text/csv;charset=utf-8"}));a.download="επαγγέλματα.csv";a.click();URL.revokeObjectURL(a.href)}
function Modal({title,onClose,children}){return <div className="mprof-backdrop"><section className="mprof-modal"><header><b>{title}</b><button onClick={onClose}><X/></button></header>{children}</section></div>}
function Editor({item,busy,onClose,onSave}){const[code,setCode]=useState(item?.code||"");const[description,setDescription]=useState(item?.description||"");const[active,setActive]=useState(item?.active!==false);return <><div className="mprof-form"><label>Κωδ<input value={code} onChange={e=>setCode(e.target.value)} maxLength={30}/></label><label>Περιγραφή<input autoFocus value={description} onChange={e=>setDescription(e.target.value)} maxLength={300}/></label><label className="check"><input type="checkbox" checked={active} onChange={e=>setActive(e.target.checked)}/> Ενεργό</label></div><footer><button onClick={onClose}><X/>Επιστροφή</button><button className="primary" disabled={busy||!description.trim()} onClick={()=>onSave({code:code.trim()||null,description:description.trim(),active})}><Check/>Καταχώρηση</button></footer></>}
export default function ManagementProfessionsPanel({api,onClose}){const[items,setItems]=useState([]),[busy,setBusy]=useState(false),[error,setError]=useState(""),[message,setMessage]=useState(""),[dialog,setDialog]=useState(null);const load=async()=>{setBusy(true);setError("");try{const data=await api("/api/management/professions");setItems(data.items||[])}catch(e){setError(e.message)}finally{setBusy(false)}};useEffect(()=>{load()},[]);const save=async payload=>{setBusy(true);setError("");try{if(dialog?.item)await api(`/api/management/professions/${dialog.item.id}`,{method:"PATCH",body:JSON.stringify(payload)});else await api("/api/management/professions",{method:"POST",body:JSON.stringify(payload)});setDialog(null);setMessage("Το επάγγελμα αποθηκεύτηκε.");await load()}catch(e){setError(e.message)}finally{setBusy(false)}};const remove=async item=>{if(!window.confirm(`Να απενεργοποιηθεί «${item.description}»;`))return;setBusy(true);setError("");try{await api(`/api/management/professions/${item.id}`,{method:"DELETE"});setMessage("Το επάγγελμα απενεργοποιήθηκε χωρίς διαγραφή ιστορικού.");await load()}catch(e){setError(e.message)}finally{setBusy(false)}};const sync=async()=>{setBusy(true);setError("");try{const data=await api("/api/management/professions/synchronize",{method:"POST",body:"{}"});const dup=data.duplicates?.length||0;setMessage(`${data.message} Ελέγχθηκαν ${data.checked||0} εγγραφές${dup?` · βρέθηκαν ${dup} πιθανές διπλοεγγραφές`:""}.`)}catch(e){setError(e.message)}finally{setBusy(false)}};return <div className="mprof-suite">{error&&<div className="mprof-alert error">{error}</div>}{message&&<div className="mprof-alert success">{message}</div>}<section className="mprof-card"><div className="mprof-row head"><span>Κωδ</span><span>Περιγραφή</span><span></span></div><div className="mprof-list">{items.map(item=><div className={`mprof-row ${!item.active?"inactive":""}`} key={item.id}><span>{item.code||"—"}</span><button className="description" onClick={()=>setDialog({item})}><Edit3/>{item.description}</button><button className="danger" onClick={()=>remove(item)}><Trash2/></button></div>)}{!items.length&&!busy&&<div className="mprof-empty">Δεν υπάρχουν ακόμη επαγγέλματα.</div>}</div><footer><b>{items.length}</b><span>εγγραφές</span></footer></section><div className="mprof-footer"><button onClick={onClose}><X/>Κλείσιμο</button><button onClick={load} disabled={busy}><RefreshCw/>Ανανέωση</button><button className="primary" onClick={()=>setDialog({item:null})}><Plus/>Νέα εγγραφή</button><button onClick={()=>downloadCsv(items)}><Download/>Excel / CSV</button><button className="sync" onClick={sync} disabled={busy}><RotateCw/>Συγχρονισμός</button></div>{dialog&&<Modal title={dialog.item?"Διόρθωση επαγγέλματος":"Νέο επάγγελμα"} onClose={()=>setDialog(null)}><Editor item={dialog.item} busy={busy} onClose={()=>setDialog(null)} onSave={save}/></Modal>}</div>}
