import React,{useEffect,useMemo,useState} from "react";
import {Barcode,Check,ChevronLeft,ChevronRight,Download,Edit3,Plus,RefreshCw,Search,Trash2,X} from "lucide-react";
import "./management-vat-departments.css";

const money=v=>`${Number(v||0).toFixed(2)} €`;
const csvCell=v=>`"${String(v??"").replaceAll('"','""')}"`;
const downloadCsv=(name,headers,rows)=>{const body=[headers.map(csvCell).join(";"),...rows.map(r=>r.map(csvCell).join(";"))].join("\n");const blob=new Blob(["\ufeff",body],{type:"text/csv;charset=utf-8"});const url=URL.createObjectURL(blob);const a=document.createElement("a");a.href=url;a.download=name;document.body.appendChild(a);a.click();a.remove();URL.revokeObjectURL(url)};
function Modal({title,children,onClose,wide=false}){return <div className="mvat-backdrop"><section className={`mvat-modal ${wide?"wide":""}`}><header><b>{title}</b><button onClick={onClose}><X/></button></header>{children}</section></div>}

function DepartmentForm({item,exemptions,onSave,onClose,busy}){
  const [draft,setDraft]=useState({description:item?.description||"",active:item?.active!==false,cashRegisterDepartment:item?.cashRegisterDepartment??"",vatRate:String(Number(item?.vatRate||0)),legacyVatCode:item?.legacyVatCode||"",commerce:item?.commerce!==false,exemptionCode:item?.exemptionCode||""});
  const ch=(k,v)=>setDraft(d=>({...d,[k]:v}));
  const exemption=exemptions.find(x=>String(x.code)===String(draft.exemptionCode));
  return <><div className="mvat-form"><div className="mvat-form-top"><label>Περιγραφή<input autoFocus value={draft.description} onChange={e=>ch("description",e.target.value)}/></label><label className="check"><input type="checkbox" checked={draft.active} onChange={e=>ch("active",e.target.checked)}/> ενεργό</label></div><div className="mvat-form-grid"><label>Τμήμα ταμειακής<input type="number" min="0" step="1" value={draft.cashRegisterDepartment} onChange={e=>ch("cashRegisterDepartment",e.target.value)}/></label><label>% ΦΠΑ<input type="number" min="0" max="100" step="0.001" value={draft.vatRate} onChange={e=>ch("vatRate",e.target.value)}/></label><label>Κωδικός<input value={draft.legacyVatCode} onChange={e=>ch("legacyVatCode",e.target.value)}/></label><label className="check"><input type="checkbox" checked={draft.commerce} onChange={e=>ch("commerce",e.target.checked)}/> Εμπορία</label></div><label className="mvat-exemption">Εξαίρεση ΦΠΑ<select value={draft.exemptionCode} onChange={e=>ch("exemptionCode",e.target.value)}><option value="">Χωρίς εξαίρεση</option>{exemptions.map(x=><option key={x.code} value={x.code}>{x.code} · {x.description}</option>)}</select></label></div><footer className="mvat-actions"><button onClick={onClose}><ChevronLeft/>Επιστροφή</button><button className="primary" disabled={busy||!draft.description.trim()} onClick={()=>onSave({description:draft.description.trim(),active:draft.active,cashRegisterDepartment:draft.cashRegisterDepartment===""?null:Number(draft.cashRegisterDepartment),vatRate:Number(draft.vatRate||0),legacyVatCode:draft.legacyVatCode.trim(),commerce:draft.commerce,exemptionCode:draft.exemptionCode||null,exemptionDescription:exemption?.description||null})}><Check/>Καταχώρηση</button></footer></>
}

function VatProducts({api,department,departments,storeId,onClose}){
  const [data,setData]=useState({items:[],total:0,page:1,pages:1,pageSize:100});const [q,setQ]=useState("");const [busy,setBusy]=useState(false);const [error,setError]=useState("");const [checked,setChecked]=useState([]);const [bulk,setBulk]=useState(false);const [targetId,setTargetId]=useState(department.id);
  const load=async(page=1)=>{setBusy(true);setError("");try{const p=new URLSearchParams({page:String(page),pageSize:"100"});if(storeId)p.set("storeId",storeId);if(q.trim())p.set("q",q.trim());const r=await api(`/api/management/vat-departments/${department.id}/products?${p}`);setData(r);setChecked(v=>v.filter(id=>r.items.some(x=>x.id===id)))}catch(e){setError(e.message)}finally{setBusy(false)}};
  useEffect(()=>{load(1)},[]);const all=data.items.length>0&&data.items.every(x=>checked.includes(x.id));
  const exportCsv=()=>downloadCsv(`τμήμα_φπα_${department.description}.csv`,["Περιγραφή είδους","Λιανική","Κατηγορία","Υποκατηγορία","Προμηθευτής","Τμήμα ΦΠΑ","Εσωτ. κωδ"],data.items.map(r=>[r.name,money(r.salePrice),r.categoryName||"—",r.subcategoryName||"—",r.supplierName||"—",department.description,r.sku||"—"]));
  const applyBulk=async()=>{if(!checked.length)return;setBusy(true);try{await api("/api/management/vat-departments/products/bulk-assign",{method:"PATCH",body:JSON.stringify({productIds:checked,vatDepartmentId:targetId})});setBulk(false);setChecked([]);await load(1)}catch(e){setError(e.message)}finally{setBusy(false)}};
  return <Modal wide title={`Είδη τμήματος ΦΠΑ · ${department.description}`} onClose={onClose}><div className="mvat-products-toolbar"><form onSubmit={e=>{e.preventDefault();load(1)}}><Search/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Περιγραφή / εσωτ. κωδικός"/><button>Αναζήτηση</button></form><b>{data.total} είδη</b></div>{error&&<div className="mvat-alert error">{error}</div>}<div className="mvat-products-table"><div className="mvat-product-row head"><span></span><span><input type="checkbox" checked={all} onChange={()=>setChecked(all?[]:data.items.map(x=>x.id))}/></span><span>Περιγραφή είδους</span><span>Λιανική</span><span>Κατηγορία</span><span>Υποκατηγορία</span><span>Προμηθευτής</span><span>Τμήμα ΦΠΑ</span><span>Εσωτ. κωδ</span></div>{data.items.map(r=><div className="mvat-product-row" key={r.id}><span className="pencil"><Edit3/></span><span><input type="checkbox" checked={checked.includes(r.id)} onChange={()=>setChecked(v=>v.includes(r.id)?v.filter(id=>id!==r.id):[...v,r.id])}/></span><span className="link">{r.name}</span><span>{money(r.salePrice)}</span><span>{r.categoryName||"—"}</span><span>{r.subcategoryName||"—"}</span><span>{r.supplierName||"—"}</span><span>{department.description}</span><span>{r.sku||"—"}</span></div>)}</div><div className="mvat-pager"><span>Σελίδα {data.page} / {data.pages}</span><button disabled={data.page<=1||busy} onClick={()=>load(data.page-1)}><ChevronLeft/></button><button disabled={data.page>=data.pages||busy} onClick={()=>load(data.page+1)}><ChevronRight/></button></div><footer className="mvat-actions product-actions"><button onClick={onClose}><ChevronLeft/>Επιστροφή</button><button onClick={()=>load(data.page)}><RefreshCw/>Ανανέωση</button><button onClick={exportCsv}><Download/>Excel / CSV</button><button disabled={!checked.length} onClick={()=>setBulk(true)}><Edit3/>Ομαδική διόρθωση</button></footer>{bulk&&<div className="mvat-nested"><div className="mvat-nested-card"><b>Μεταφορά {checked.length} ειδών σε Τμήμα ΦΠΑ</b><select value={targetId} onChange={e=>setTargetId(e.target.value)}>{departments.filter(x=>x.active).map(x=><option key={x.id} value={x.id}>{x.description} · {Number(x.vatRate).toFixed(2)}%</option>)}</select><div><button onClick={()=>setBulk(false)}>Άκυρο</button><button className="primary" onClick={applyBulk}>Καταχώρηση</button></div></div></div>}</Modal>
}

export default function ManagementVatDepartmentsPanel({api,store,onClose}){
  const [data,setData]=useState({items:[],exemptions:[]});const [dialog,setDialog]=useState(null);const [busy,setBusy]=useState(false);const [error,setError]=useState("");const [message,setMessage]=useState("");
  const items=useMemo(()=>data.items||[],[data]);
  const load=async()=>{setBusy(true);setError("");try{setData(await api("/api/management/vat-departments"))}catch(e){setError(e.message)}finally{setBusy(false)}};useEffect(()=>{load()},[]);
  const save=async payload=>{setBusy(true);setError("");try{if(dialog?.item)await api(`/api/management/vat-departments/${dialog.item.id}`,{method:"PATCH",body:JSON.stringify(payload)});else await api("/api/management/vat-departments",{method:"POST",body:JSON.stringify(payload)});setDialog(null);setMessage("Το τμήμα ΦΠΑ αποθηκεύτηκε.");await load()}catch(e){setError(e.message)}finally{setBusy(false)}};
  const deactivate=async item=>{if(!window.confirm(`Να απενεργοποιηθεί «${item.description}»;`))return;setBusy(true);try{await api(`/api/management/vat-departments/${item.id}`,{method:"DELETE"});setMessage("Το τμήμα ΦΠΑ απενεργοποιήθηκε χωρίς διαγραφή ιστορικού.");await load()}catch(e){setError(e.message)}finally{setBusy(false)}};
  const exportCsv=()=>downloadCsv("τμήματα_φπα.csv",["ΚΩΔ ΦΠΑ","Τμήμα Ταμειακής","Περιγραφή","% ΦΠΑ","Είδη","Εμπορία","ID"],items.map(r=>[r.legacyVatCode||"",r.cashRegisterDepartment??"",r.description,r.vatRate,r.productCount,r.commerce?"ΝΑΙ":"ΟΧΙ",r.id]));
  return <div className="mvat-suite">{error&&<div className="mvat-alert error">{error}</div>}{message&&<div className="mvat-alert success">{message}</div>}<section className="mvat-card"><div className="mvat-row head"><span>ΚΩΔ ΦΠΑ</span><span>Τμήμα Ταμειακής</span><span>Περιγραφή</span><span>% ΦΠΑ</span><span>Είδη</span><span>Εμπορία</span><span>ID</span><span></span></div><div className="mvat-list">{items.map(r=><div className={`mvat-row ${!r.active?"inactive":""}`} key={r.id}><span>{r.legacyVatCode||"—"}</span><strong>{r.cashRegisterDepartment??"—"}</strong><button className="description" onClick={()=>setDialog({type:"edit",item:r})}><Edit3/>{r.description}</button><strong>{Number(r.vatRate||0).toFixed(1)}</strong><button className="barcode-count" onClick={()=>setDialog({type:"products",item:r})}><Barcode/>{r.productCount}</button><span><input type="checkbox" checked={Boolean(r.commerce)} readOnly/></span><span>{r.id}</span><button className="danger" onClick={()=>deactivate(r)}><Trash2/></button></div>)}</div><footer><span>{items.length} τμήματα</span><b>{items.reduce((s,r)=>s+Number(r.productCount||0),0)} είδη</b></footer></section><div className="mvat-footer"><button onClick={onClose}><X/>Κλείσιμο</button><button onClick={load}><RefreshCw/>Ανανέωση</button><button className="primary" onClick={()=>setDialog({type:"edit",item:null})}><Plus/>Νέα εγγραφή</button><button onClick={exportCsv}><Download/>Excel / CSV</button></div>{dialog?.type==="edit"&&<Modal title={dialog.item?"Διόρθωση τμήματος ΦΠΑ":"Νέο τμήμα ΦΠΑ"} onClose={()=>setDialog(null)}><DepartmentForm item={dialog.item} exemptions={data.exemptions||[]} busy={busy} onSave={save} onClose={()=>setDialog(null)}/></Modal>}{dialog?.type==="products"&&<VatProducts api={api} department={dialog.item} departments={items} storeId={store?.id} onClose={()=>setDialog(null)}/>}</div>
}
