import React,{useEffect,useState} from "react";
import {Barcode,Check,ChevronLeft,ChevronRight,Download,Edit3,Plus,RefreshCw,Search,Trash2,X} from "lucide-react";
import "./management-product-companies.css";

const money=v=>`${Number(v||0).toFixed(2)} €`;
const pct=v=>`${Number(v||0).toFixed(2).replace(".",",")}%`;
const csvCell=value=>`"${String(value??"").replaceAll('"','""')}"`;
const downloadCsv=(name,headers,rows)=>{const body=[headers.map(csvCell).join(";"),...rows.map(row=>row.map(csvCell).join(";"))].join("\n");const blob=new Blob(["\ufeff",body],{type:"text/csv;charset=utf-8"});const url=URL.createObjectURL(blob);const a=document.createElement("a");a.href=url;a.download=name;document.body.appendChild(a);a.click();a.remove();URL.revokeObjectURL(url)};

function Editor({item,busy,onClose,onSave}){
  const [name,setName]=useState(item?.name||"");const [active,setActive]=useState(item?.active!==false);
  return <div className="mpco-backdrop"><section className="mpco-modal"><header><b>{item?"Διόρθωση Εταιρείας":"Νέα Εταιρεία"}</b><button onClick={onClose}><X/></button></header><div className="mpco-form"><label>Περιγραφή<input autoFocus value={name} onChange={e=>setName(e.target.value)}/></label><label className="check"><input type="checkbox" checked={active} onChange={e=>setActive(e.target.checked)}/> Ενεργή</label></div><footer><button onClick={onClose}><ChevronLeft/>Επιστροφή</button><button className="primary" disabled={busy||!name.trim()} onClick={()=>onSave({name:name.trim(),active})}><Check/>Καταχώρηση</button></footer></section></div>;
}

function ProductsModal({api,company,companies,storeId,onClose}){
  const [data,setData]=useState({items:[],total:0,page:1,pages:1,pageSize:100});const [q,setQ]=useState("");const [busy,setBusy]=useState(false);const [error,setError]=useState("");const [checked,setChecked]=useState([]);const [bulk,setBulk]=useState(false);const [targetId,setTargetId]=useState("");
  const load=async(page=1)=>{setBusy(true);setError("");try{const params=new URLSearchParams({page:String(page),pageSize:String(data.pageSize||100)});if(storeId)params.set("storeId",storeId);if(q.trim())params.set("q",q.trim());const result=await api(`/api/management/product-companies/${company.id}/products?${params}`);setData(result);setChecked(ids=>ids.filter(id=>result.items.some(r=>r.id===id)))}catch(e){setError(e.message)}finally{setBusy(false)}};
  useEffect(()=>{load(1)},[]);
  const all=data.items.length>0&&data.items.every(r=>checked.includes(r.id));
  const exportCsv=()=>downloadCsv(`είδη_${company.name}.csv`,["Περιγραφή είδους","Λιανική","Κατηγορία","Υποκατηγορία","Προμηθευτής","ΦΠΑ","Εσωτ. κωδ","Barcode"],data.items.map(r=>[r.name,money(r.salePrice),r.categoryName||"—",r.subcategoryName||"—",r.supplierName||"—",`${r.vatRate}%`,r.sku||"—",r.barcode||"—"]));
  const applyBulk=async()=>{if(!checked.length||!targetId)return;setBusy(true);setError("");try{await api("/api/management/product-companies/products/bulk-assign",{method:"PATCH",body:JSON.stringify({productIds:checked,productCompanyId:targetId})});setBulk(false);setChecked([]);await load(1)}catch(e){setError(e.message)}finally{setBusy(false)}};
  return <div className="mpco-backdrop"><section className="mpco-modal wide"><header><b>Προβολή ειδών · {company.name}</b><button onClick={onClose}><X/></button></header><div className="mpco-products-toolbar"><form onSubmit={e=>{e.preventDefault();load(1)}}><Search/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Περιγραφή / SKU / Barcode"/><button>Αναζήτηση</button></form><b>{data.total} είδη</b></div>{error&&<div className="mpco-alert error">{error}</div>}<div className="mpco-products"><div className="mpco-product-row head"><span></span><span><input type="checkbox" checked={all} onChange={()=>setChecked(all?[]:data.items.map(r=>r.id))}/></span><span>Περιγραφή είδους</span><span>Λιανική</span><span>Κατηγορία</span><span>Υποκατηγορία</span><span>Προμηθευτής</span><span>Τμήμα ΦΠΑ</span><span>Εσωτ. κωδ</span></div>{data.items.map(r=><div className="mpco-product-row" key={r.id}><span><Edit3/></span><span><input type="checkbox" checked={checked.includes(r.id)} onChange={()=>setChecked(v=>v.includes(r.id)?v.filter(x=>x!==r.id):[...v,r.id])}/></span><strong>{r.name}</strong><span>{money(r.salePrice)}</span><span>{r.categoryName||"—"}</span><span>{r.subcategoryName||"—"}</span><span>{r.supplierName||"—"}</span><span>{r.vatRate}%</span><span>{r.sku||"—"}</span></div>)}</div><div className="mpco-pager"><span>Σελίδα {data.page} / {data.pages}</span><button disabled={data.page<=1||busy} onClick={()=>load(data.page-1)}><ChevronLeft/></button><button disabled={data.page>=data.pages||busy} onClick={()=>load(data.page+1)}><ChevronRight/></button></div><footer className="product-actions"><button onClick={onClose}><ChevronLeft/>Επιστροφή</button><button onClick={()=>load(data.page)}><RefreshCw/>Ανανέωση</button><button onClick={exportCsv}><Download/>Excel / CSV</button><button disabled={!checked.length} onClick={()=>{setTargetId(companies.find(c=>c.active&&c.id!==company.id)?.id||"");setBulk(true)}}><Edit3/>Ομαδική διόρθωση</button></footer>{bulk&&<div className="mpco-nested"><div className="mpco-nested-card"><b>Μεταφορά {checked.length} ειδών σε άλλη εταιρεία</b><label>Νέα εταιρεία<select value={targetId} onChange={e=>setTargetId(e.target.value)}>{companies.filter(c=>c.active&&c.id!==company.id).map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><div><button onClick={()=>setBulk(false)}>Άκυρο</button><button className="primary" disabled={!targetId||busy} onClick={applyBulk}>Καταχώρηση</button></div></div></div>}</section></div>;
}

export default function ManagementProductCompaniesPanel({api,store,onClose}){
  const [items,setItems]=useState([]),[totalProducts,setTotalProducts]=useState(0),[busy,setBusy]=useState(false),[error,setError]=useState(""),[message,setMessage]=useState(""),[dialog,setDialog]=useState(null);
  const load=async()=>{setBusy(true);setError("");try{const data=await api("/api/management/product-companies");setItems(data.items||[]);setTotalProducts(Number(data.totalProducts||0))}catch(e){setError(e.message)}finally{setBusy(false)}};
  useEffect(()=>{load()},[]);
  const save=async payload=>{setBusy(true);setError("");try{if(dialog?.item)await api(`/api/management/product-companies/${dialog.item.id}`,{method:"PATCH",body:JSON.stringify(payload)});else await api("/api/management/product-companies",{method:"POST",body:JSON.stringify(payload)});setDialog(null);setMessage("Η εταιρεία αποθηκεύτηκε.");await load()}catch(e){setError(e.message)}finally{setBusy(false)}};
  const deactivate=async item=>{if(!window.confirm(`Να απενεργοποιηθεί «${item.name}»;`))return;setBusy(true);setError("");try{await api(`/api/management/product-companies/${item.id}`,{method:"DELETE"});setMessage("Η εταιρεία απενεργοποιήθηκε χωρίς διαγραφή ιστορικού.");await load()}catch(e){setError(e.message)}finally{setBusy(false)}};
  const exportCsv=()=>downloadCsv("εταιρείες_ειδών.csv",["Περιγραφή","Είδη","% ειδών","Ενεργή"],items.map(r=>[r.name,r.productCount,pct(r.percent),r.active?"ΝΑΙ":"ΟΧΙ"]));
  return <div className="mpco-suite">{error&&<div className="mpco-alert error">{error}</div>}{message&&<div className="mpco-alert success">{message}</div>}<section className="mpco-card"><div className="mpco-row head"><span>Περιγραφή</span><span>Είδη</span><span>% ειδών</span><span></span></div><div className="mpco-list">{items.map(item=><div className={`mpco-row ${!item.active?"inactive":""}`} key={item.id}><button className="description" onClick={()=>setDialog({type:"edit",item})}><Edit3/>{item.name}</button><button className="barcode-count" onClick={()=>setDialog({type:"products",item})}><Barcode/>{item.productCount}</button><strong>{pct(item.percent)}</strong><button className="danger" title="Απενεργοποίηση" onClick={()=>deactivate(item)}><Trash2/></button></div>)}{!items.length&&!busy&&<div className="mpco-empty">Δεν υπάρχουν ακόμη εταιρείες προϊόντων.</div>}</div><footer><b>{items.length}</b><span>{totalProducts} είδη</span><strong>{totalProducts?"100,00%":"0,00%"}</strong></footer></section><div className="mpco-footer"><button onClick={onClose}><X/>Κλείσιμο</button><button onClick={load} disabled={busy}><RefreshCw/>Ανανέωση</button><button className="primary" onClick={()=>setDialog({type:"edit",item:null})}><Plus/>Νέα εγγραφή</button><button onClick={exportCsv}><Download/>Excel / CSV</button></div>{dialog?.type==="edit"&&<Editor item={dialog.item} busy={busy} onClose={()=>setDialog(null)} onSave={save}/>} {dialog?.type==="products"&&<ProductsModal api={api} company={dialog.item} companies={items} storeId={store?.id} onClose={()=>{setDialog(null);load()}}/>}</div>;
}
