import React,{useEffect,useState} from "react";
import {Check,Download,Edit3,Plus,RefreshCw,Trash2,X} from "lucide-react";
import "./management-expense-categories.css";

const csvCell=value=>`"${String(value??"").replaceAll('"','""')}"`;
const downloadCsv=(rows)=>{const body=[["Περιγραφή","Ενεργή"].map(csvCell).join(";"),...rows.map(r=>[r.description,r.active?"ΝΑΙ":"ΟΧΙ"].map(csvCell).join(";"))].join("\n");const blob=new Blob(["\ufeff",body],{type:"text/csv;charset=utf-8"});const url=URL.createObjectURL(blob);const a=document.createElement("a");a.href=url;a.download="κατηγορίες_εξόδων.csv";document.body.appendChild(a);a.click();a.remove();URL.revokeObjectURL(url)};

function Editor({item,busy,onClose,onSave}){const [description,setDescription]=useState(item?.description||"");const [active,setActive]=useState(item?.active!==false);return <div className="mexp-backdrop"><section className="mexp-modal"><header><b>{item?"Διόρθωση κατηγορίας εξόδου":"Νέα κατηγορία εξόδου"}</b><button onClick={onClose}><X/></button></header><div className="mexp-form"><label>Περιγραφή<input autoFocus value={description} onChange={e=>setDescription(e.target.value)} /></label><label className="check"><input type="checkbox" checked={active} onChange={e=>setActive(e.target.checked)}/> Ενεργή</label></div><footer><button onClick={onClose}><X/>Επιστροφή</button><button className="primary" disabled={busy||!description.trim()} onClick={()=>onSave({description:description.trim(),active})}><Check/>Καταχώρηση</button></footer></section></div>}

export default function ManagementExpenseCategoriesPanel({api,onClose}){
  const [items,setItems]=useState([]),[busy,setBusy]=useState(false),[error,setError]=useState(""),[message,setMessage]=useState(""),[editor,setEditor]=useState(null);
  const load=async()=>{setBusy(true);setError("");try{const data=await api("/api/management/expense-categories");setItems(data.items||[])}catch(e){setError(e.message)}finally{setBusy(false)}};
  useEffect(()=>{load()},[]);
  const save=async payload=>{setBusy(true);setError("");try{if(editor?.item)await api(`/api/management/expense-categories/${editor.item.id}`,{method:"PATCH",body:JSON.stringify(payload)});else await api("/api/management/expense-categories",{method:"POST",body:JSON.stringify(payload)});setEditor(null);setMessage("Η κατηγορία εξόδου αποθηκεύτηκε.");await load()}catch(e){setError(e.message)}finally{setBusy(false)}};
  const deactivate=async item=>{if(!window.confirm(`Να απενεργοποιηθεί «${item.description}»;`))return;setBusy(true);setError("");try{await api(`/api/management/expense-categories/${item.id}`,{method:"DELETE"});setMessage("Η κατηγορία απενεργοποιήθηκε χωρίς διαγραφή ιστορικού.");await load()}catch(e){setError(e.message)}finally{setBusy(false)}};
  return <div className="mexp-suite">{error&&<div className="mexp-alert error">{error}</div>}{message&&<div className="mexp-alert success">{message}</div>}<section className="mexp-card"><div className="mexp-row head"><span>Περιγραφή</span><span></span></div><div className="mexp-list">{items.map(item=><div className={`mexp-row ${!item.active?"inactive":""}`} key={item.id}><button className="description" onClick={()=>setEditor({item})}><Edit3/>{item.description}</button><button className="danger" title="Απενεργοποίηση" onClick={()=>deactivate(item)}><Trash2/></button></div>)}{!items.length&&!busy&&<div className="mexp-empty">Δεν υπάρχουν ακόμη καταχωρημένες κατηγορίες εξόδων.</div>}</div><footer><b>{items.length}</b></footer></section><div className="mexp-footer"><button onClick={onClose}><X/>Κλείσιμο</button><button onClick={load} disabled={busy}><RefreshCw/>Ανανέωση</button><button className="primary" onClick={()=>setEditor({item:null})}><Plus/>Νέα εγγραφή</button><button onClick={()=>downloadCsv(items)}><Download/>Excel / CSV</button></div>{editor&&<Editor item={editor.item} busy={busy} onClose={()=>setEditor(null)} onSave={save}/>}</div>;
}
