import React,{useEffect,useState} from "react";
import {Check,Download,Edit3,Plus,RefreshCw,Trash2,X} from "lucide-react";
import "./management-customer-categories.css";

const csvCell=value=>`"${String(value??"").replaceAll('"','""')}"`;
const downloadCsv=rows=>{const body=[["Περιγραφή","Με επιλογή","Με πίστωση","Πώληση στην αγορά ή χονδρική","Ετεροχρονισμένη","Ενεργή"].map(csvCell).join(";"),...rows.map(r=>[r.description,r.selectable?"ΝΑΙ":"ΟΧΙ",r.allowCredit?"ΝΑΙ":"ΟΧΙ",r.saleAtCostOrWholesale?"ΝΑΙ":"ΟΧΙ",r.deferred?"ΝΑΙ":"ΟΧΙ",r.active?"ΝΑΙ":"ΟΧΙ"].map(csvCell).join(";"))].join("\n");const blob=new Blob(["\ufeff",body],{type:"text/csv;charset=utf-8"});const url=URL.createObjectURL(blob);const a=document.createElement("a");a.href=url;a.download="κατηγορίες_πελατών.csv";document.body.appendChild(a);a.click();a.remove();URL.revokeObjectURL(url)};

function Editor({item,busy,onClose,onSave}){
  const [draft,setDraft]=useState({description:item?.description||"",selectable:!!item?.selectable,allowCredit:!!item?.allowCredit,saleAtCostOrWholesale:!!item?.saleAtCostOrWholesale,deferred:!!item?.deferred,active:item?.active!==false});
  const ch=(key,value)=>setDraft(d=>({...d,[key]:value}));
  return <div className="mcc-backdrop"><section className="mcc-modal"><header><b>{item?"Διόρθωση κατηγορίας πελατών":"Νέα κατηγορία πελατών"}</b><button onClick={onClose}><X/></button></header><div className="mcc-form"><label>Περιγραφή<input autoFocus value={draft.description} onChange={e=>ch("description",e.target.value)}/></label><div className="mcc-options"><label><input type="checkbox" checked={draft.selectable} onChange={e=>ch("selectable",e.target.checked)}/> Με επιλογή</label><label><input type="checkbox" checked={draft.allowCredit} onChange={e=>ch("allowCredit",e.target.checked)}/> Με πίστωση</label><label><input type="checkbox" checked={draft.saleAtCostOrWholesale} onChange={e=>ch("saleAtCostOrWholesale",e.target.checked)}/> Πώληση στην αγορά ή χονδρική</label><label><input type="checkbox" checked={draft.deferred} onChange={e=>ch("deferred",e.target.checked)}/> Ετεροχρονισμένη</label><label><input type="checkbox" checked={draft.active} onChange={e=>ch("active",e.target.checked)}/> Ενεργή</label></div></div><footer><button onClick={onClose}><X/>Επιστροφή</button><button className="primary" disabled={busy||!draft.description.trim()} onClick={()=>onSave({...draft,description:draft.description.trim()})}><Check/>Καταχώρηση</button></footer></section></div>
}

const Flag=({value})=><input className="mcc-flag" type="checkbox" checked={!!value} readOnly aria-label={value?"Ναι":"Όχι"}/>;

export default function ManagementCustomerCategoriesPanel({api,onClose}){
  const [items,setItems]=useState([]),[busy,setBusy]=useState(false),[error,setError]=useState(""),[message,setMessage]=useState(""),[editor,setEditor]=useState(null);
  const load=async()=>{setBusy(true);setError("");try{const data=await api("/api/management/customer-categories");setItems(data.items||[])}catch(e){setError(e.message)}finally{setBusy(false)}};
  useEffect(()=>{load()},[]);
  const save=async payload=>{setBusy(true);setError("");try{if(editor?.item)await api(`/api/management/customer-categories/${editor.item.id}`,{method:"PATCH",body:JSON.stringify(payload)});else await api("/api/management/customer-categories",{method:"POST",body:JSON.stringify(payload)});setEditor(null);setMessage("Η κατηγορία πελατών αποθηκεύτηκε.");await load()}catch(e){setError(e.message)}finally{setBusy(false)}};
  const deactivate=async item=>{if(!window.confirm(`Να απενεργοποιηθεί «${item.description}»;`))return;setBusy(true);setError("");try{await api(`/api/management/customer-categories/${item.id}`,{method:"DELETE"});setMessage("Η κατηγορία απενεργοποιήθηκε χωρίς διαγραφή ιστορικού.");await load()}catch(e){setError(e.message)}finally{setBusy(false)}};
  return <div className="mcc-suite">{error&&<div className="mcc-alert error">{error}</div>}{message&&<div className="mcc-alert success">{message}</div>}<section className="mcc-card"><div className="mcc-row head"><span>Περιγραφή</span><span>Με επιλογή</span><span>Με πίστωση</span><span>Πώληση στην αγορά ή χονδρική</span><span>ετεροχρονισμένη</span><span></span></div><div className="mcc-list">{items.map(item=><div className={`mcc-row ${!item.active?"inactive":""}`} key={item.id}><button className="description" onClick={()=>setEditor({item})}><Edit3/>{item.description}</button><span><Flag value={item.selectable}/></span><span><Flag value={item.allowCredit}/></span><span><Flag value={item.saleAtCostOrWholesale}/></span><span><Flag value={item.deferred}/></span><button className="danger" title="Απενεργοποίηση" onClick={()=>deactivate(item)}><Trash2/></button></div>)}{!items.length&&!busy&&<div className="mcc-empty">Δεν υπάρχουν ακόμη καταχωρημένες κατηγορίες πελατών.</div>}</div><footer><b>{items.length}</b><span>{items.filter(x=>x.active).length} ενεργές</span></footer></section><div className="mcc-footer"><button onClick={onClose}><X/>Κλείσιμο</button><button onClick={load} disabled={busy}><RefreshCw/>Ανανέωση</button><button className="primary" onClick={()=>setEditor({item:null})}><Plus/>Νέα εγγραφή</button><button onClick={()=>downloadCsv(items)}><Download/>Excel / CSV</button></div>{editor&&<Editor item={editor.item} busy={busy} onClose={()=>setEditor(null)} onSave={save}/>}</div>;
}
