import React,{useEffect,useState} from "react";
import {Check,Download,Edit3,Plus,RefreshCw,Trash2,X} from "lucide-react";
import "./management-business-units.css";

const fmtDate=v=>v?new Date(v).toLocaleString("el-GR",{day:"2-digit",month:"2-digit",year:"numeric",hour:"2-digit",minute:"2-digit",second:"2-digit"}):"—";
const esc=v=>`"${String(v??"").replaceAll('"','""')}"`;
function downloadCsv(name,rows){const blob=new Blob(["\ufeff"+rows.map(r=>r.map(esc).join(";")).join("\n")],{type:"text/csv;charset=utf-8"});const a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
function Modal({title,children,onClose}){return <div className="mbu-backdrop"><section className="mbu-modal"><header><b>{title}</b><button onClick={onClose}><X/></button></header>{children}</section></div>}
function BankEditor({item,busy,onClose,onSave}){
  const [internalCode,setInternalCode]=useState(item?.internalCode||"");const [name,setName]=useState(item?.name||"");const [accountingAccount,setAccountingAccount]=useState(item?.accountingAccount||"");const [auxiliaryName,setAuxiliaryName]=useState(item?.auxiliaryName||"");const [active,setActive]=useState(item?.active!==false);
  return <><div className="mbu-form"><label>εσωτ. κωδ<input autoFocus value={internalCode} onChange={e=>setInternalCode(e.target.value)}/></label><label>Ονομασία<input value={name} onChange={e=>setName(e.target.value)}/></label><label>Λογ. Λογιστικής<input value={accountingAccount} onChange={e=>setAccountingAccount(e.target.value)}/></label><label>Βοηθητική ονομασία<input value={auxiliaryName} onChange={e=>setAuxiliaryName(e.target.value)}/></label><label className="check"><input type="checkbox" checked={active} onChange={e=>setActive(e.target.checked)}/> ενεργό</label></div><footer><button onClick={onClose}><X/>Επιστροφή</button><button className="primary" disabled={busy||!internalCode.trim()||!name.trim()} onClick={()=>onSave({internalCode:internalCode.trim(),name:name.trim(),accountingAccount:accountingAccount.trim()||null,auxiliaryName:auxiliaryName.trim()||null,active})}><Check/>Καταχώρηση</button></footer></>
}
function ShippingEditor({item,busy,onClose,onSave}){
  const [code,setCode]=useState(item?.code||"");const [description,setDescription]=useState(item?.description||"");const [active,setActive]=useState(item?.active!==false);
  return <><div className="mbu-form shipping"><label>κωδικός:<input autoFocus value={code} onChange={e=>setCode(e.target.value)}/></label><label>Ονομασία:<input value={description} onChange={e=>setDescription(e.target.value)}/></label><label className="check"><input type="checkbox" checked={active} onChange={e=>setActive(e.target.checked)}/> ενεργό</label></div><footer><button onClick={onClose}><X/>Επιστροφή</button><button className="primary" disabled={busy||!code.trim()||!description.trim()} onClick={()=>onSave({code:code.trim(),description:description.trim(),active})}><Check/>Καταχώρηση</button></footer></>
}
export default function ManagementBusinessUnitsPanel({api,mode,onClose}){
  const [items,setItems]=useState([]),[busy,setBusy]=useState(false),[error,setError]=useState(""),[message,setMessage]=useState(""),[dialog,setDialog]=useState(null);
  const endpoint=mode==="banks"?"/api/management/business-units/banks":"/api/management/business-units/shipping-methods";
  const load=async()=>{setBusy(true);setError("");try{const data=await api(endpoint);setItems(data.items||[])}catch(e){setError(e.message)}finally{setBusy(false)}};
  useEffect(()=>{setDialog(null);setMessage("");load()},[mode]);
  const save=async payload=>{setBusy(true);setError("");try{if(dialog?.item)await api(`${endpoint}/${dialog.item.id}`,{method:"PATCH",body:JSON.stringify(payload)});else await api(endpoint,{method:"POST",body:JSON.stringify(payload)});setDialog(null);setMessage(mode==="banks"?"Η τράπεζα αποθηκεύτηκε.":"Ο τρόπος αποστολής αποθηκεύτηκε.");await load()}catch(e){setError(e.message)}finally{setBusy(false)}};
  const remove=async item=>{const label=mode==="banks"?item.name:item.description;if(!window.confirm(`Να απενεργοποιηθεί «${label}»;`))return;setBusy(true);setError("");try{await api(`${endpoint}/${item.id}`,{method:"DELETE"});setMessage("Η εγγραφή απενεργοποιήθηκε χωρίς διαγραφή ιστορικού.");await load()}catch(e){setError(e.message)}finally{setBusy(false)}};
  const exportCsv=()=>mode==="banks"?downloadCsv("trapezes.csv",[["εσωτ. κωδ","Ονομασία","Λογ. Λογιστικής","Βοηθητική ονομασία"],...items.map(i=>[i.internalCode,i.name,i.accountingAccount||"",i.auxiliaryName||""])]]):downloadCsv("tropoi-apostolis.csv",[["Κωδ","Περιγραφή","καταχώρηση","ενημέρωση"],...items.map(i=>[i.code,i.description,fmtDate(i.createdAt),fmtDate(i.updatedAt)])]]);
  return <div className="mbu-suite">{error&&<div className="mbu-alert error">{error}</div>}{message&&<div className="mbu-alert success">{message}</div>}<section className={`mbu-card ${mode}`}>{mode==="banks"?<><div className="mbu-row bank head"><span>εσωτ. κωδ</span><span>Ονομασία</span><span>Λογ. Λογιστικής</span><span>Βοηθητική ονομασία</span><span></span></div><div className="mbu-list">{items.map(item=><div className="mbu-row bank" key={item.id}><button className="code-edit" onClick={()=>setDialog({item})}><Edit3/><b>{item.internalCode}</b></button><button className="description" onClick={()=>setDialog({item})}>{item.name}</button><span>{item.accountingAccount||"—"}</span><span>{item.auxiliaryName||"—"}</span><button className="danger" onClick={()=>remove(item)}><Trash2/></button></div>)}{!items.length&&!busy&&<div className="mbu-empty">Δεν υπάρχουν ακόμη καταχωρημένες τράπεζες.</div>}</div></>:<><div className="mbu-row shipping head"><span>Κωδ</span><span>Περιγραφή</span><span>καταχώρηση</span><span>ενημέρωση</span><span></span></div><div className="mbu-list">{items.map(item=><div className="mbu-row shipping" key={item.id}><span>{item.code}</span><button className="description" onClick={()=>setDialog({item})}><Edit3/>{item.description}</button><span>{fmtDate(item.createdAt)}</span><span>{fmtDate(item.updatedAt)}</span><button className="danger" onClick={()=>remove(item)}><Trash2/></button></div>)}{!items.length&&!busy&&<div className="mbu-empty">Δεν υπάρχουν ακόμη τρόποι αποστολής.</div>}</div></>}</section><div className="mbu-footer"><button onClick={onClose}><X/>Κλείσιμο</button><button onClick={load} disabled={busy}><RefreshCw/>Ανανέωση</button><button className="primary" onClick={()=>setDialog({item:null})}><Plus/>Νέα εγγραφή</button><button onClick={exportCsv}><Download/>Excel / CSV</button></div>{dialog&&<Modal title={mode==="banks"?(dialog.item?"Διόρθωση τράπεζας":"Νέα τράπεζα"):(dialog.item?"Διόρθωση τρόπου αποστολής":"Νέος τρόπος αποστολής")} onClose={()=>setDialog(null)}>{mode==="banks"?<BankEditor item={dialog.item} busy={busy} onClose={()=>setDialog(null)} onSave={save}/>:<ShippingEditor item={dialog.item} busy={busy} onClose={()=>setDialog(null)} onSave={save}/>}</Modal>}</div>;
}
