import React,{useEffect,useMemo,useState} from "react";
import {RefreshCw,X} from "lucide-react";
import "./netlink-pos.css";
const unwrap=value=>value?.data?.data||value?.data||value||{};
export default function NetlinkPosPanel({api,storeId,onClose}){
 const [status,setStatus]=useState(null),[config,setConfig]=useState(null),[groups,setGroups]=useState([]),[selected,setSelected]=useState(null),[loading,setLoading]=useState(true),[error,setError]=useState("");
 const load=async()=>{setLoading(true);setError("");try{const [s,c,m]=await Promise.all([api("/api/netlink/status"),api(`/api/netlink/stores/${encodeURIComponent(storeId)}/config`),api("/api/netlink/menu")]);setStatus(s);setConfig(c);setGroups(unwrap(m).groups||[])}catch(e){setError(e.message||"Αποτυχία φόρτωσης Netlink.")}finally{setLoading(false)}};
 useEffect(()=>{load()},[storeId]);
 const count=useMemo(()=>groups.reduce((n,g)=>n+(g.products?.length||0),0),[groups]),ready=Boolean(status?.configured&&config?.configured&&status?.executeEnabled);
 return <div className="netlink-pos-overlay" role="dialog" aria-modal="true"><section className="netlink-pos-panel"><header><div><small>ΠΡΟΠΛΗΡΩΜΕΝΕΣ ΚΑΡΤΕΣ</small><h2>NETLINK</h2></div><div><button onClick={load} disabled={loading}><RefreshCw/> Ανανέωση</button><button onClick={onClose}><X/></button></div></header><div className={`netlink-safety ${ready?"ready":"locked"}`}><b>{ready?"Έτοιμο για επιβεβαίωση":"Ασφαλής λειτουργία προβολής"}</b><span>{ready?"Η εκτέλεση απαιτεί ξεχωριστή επιβεβαίωση.":"Δεν εκδίδεται PIN και δεν γίνεται χρέωση από αυτή την οθόνη."}</span></div>{error&&<div className="netlink-error">{error}</div>}{loading?<div className="netlink-loading">Φόρτωση καταλόγου…</div>:<div className="netlink-pos-body"><nav>{groups.map(g=><a key={g.title} href={`#nl-${String(g.title).replace(/\W/g,"-")}`}>{g.title}<span>{g.products?.length||0}</span></a>)}</nav><main>{groups.map(g=><section key={g.title} id={`nl-${String(g.title).replace(/\W/g,"-")}`}><h3>{g.title}</h3><div>{(g.products||[]).map(p=><button key={`${g.title}-${p.productId}`} onClick={()=>setSelected({...p,groupTitle:g.title})} className={selected?.productId===p.productId?"selected":""}><b>{p.title}</b><small>Κωδικός {p.productId}</small><span>{p.allowCancellation?"Ακύρωση διαθέσιμη":"Χωρίς ακύρωση"}</span></button>)}</div></section>)}</main><aside>{selected?<><small>{selected.groupTitle}</small><h3>{selected.title}</h3><p>Κωδικός: <b>{selected.productId}</b></p><p>Η πραγματική υπηρεσία παραμένει πίσω από τα production safety gates.</p><button disabled={!ready}>{ready?"Συνέχεια στην επιβεβαίωση":"ΕΚΤΕΛΕΣΗ ΚΛΕΙΔΩΜΕΝΗ"}</button></>:<><h3>Επίλεξε υπηρεσία</h3><p>Διάλεξε προϊόν από τον κατάλογο.</p><small>{count} διαθέσιμες υπηρεσίες</small></>}</aside></div>}</section></div>;
}
