import React,{useEffect,useMemo,useState} from "react";
import {BarChart3,CalendarDays,FileText,RefreshCw,WalletCards,X} from "lucide-react";
import "./netlink-pos.css";
const unwrap=value=>value?.data?.data||value?.data||value||{};
const today=()=>new Date().toISOString().slice(0,10);
const weekStart=()=>{const d=new Date();d.setDate(d.getDate()-6);return d.toISOString().slice(0,10)};
const euro=value=>Number(value||0).toLocaleString("el-GR",{style:"currency",currency:"EUR"});
const displayDate=value=>new Date(value).toLocaleString("el-GR",{dateStyle:"short",timeStyle:"short"});
const Metric=({label,value})=><div className="netlink-metric"><span>{label}</span><strong>{value}</strong></div>;
const Empty=()=> <p className="netlink-empty">Δεν βρέθηκαν συναλλαγές για το επιλεγμένο διάστημα.</p>;

export default function NetlinkPosPanel({api,storeId,onClose}){
 const [status,setStatus]=useState(null),[config,setConfig]=useState(null),[groups,setGroups]=useState([]),[selected,setSelected]=useState(null),[loading,setLoading]=useState(true),[error,setError]=useState(""),[view,setView]=useState("catalog"),[reportTab,setReportTab]=useState("detail"),[from,setFrom]=useState(weekStart),[to,setTo]=useState(today),[detail,setDetail]=useState(null),[summary,setSummary]=useState(null),[settlement,setSettlement]=useState(null),[reportBusy,setReportBusy]=useState(false),[message,setMessage]=useState("");
 const load=async()=>{setLoading(true);setError("");try{const [s,c,m]=await Promise.all([api("/api/netlink/status"),api(`/api/netlink/stores/${encodeURIComponent(storeId)}/config`),api("/api/netlink/menu")]);setStatus(unwrap(s));setConfig(unwrap(c));setGroups(unwrap(m).groups||[])}catch(e){setError(e.message||"Αποτυχία φόρτωσης Netlink.")}finally{setLoading(false)}};
 const loadReports=async()=>{setReportBusy(true);setError("");try{const q=new URLSearchParams({storeId,from,to,limit:"500"});const [d,s,w]=await Promise.all([api(`/api/netlink/reports/daily?${q}`),api(`/api/netlink/reports/daily-summary?${q}`),api(`/api/netlink/reports/weekly-settlement?${q}`)]);setDetail(unwrap(d));setSummary(unwrap(s));setSettlement(unwrap(w))}catch(e){setError(e.message||"Αποτυχία φόρτωσης αναφορών Netlink.")}finally{setReportBusy(false)}};
 useEffect(()=>{load()},[storeId]);
 useEffect(()=>{if(view==="reports")loadReports()},[view,storeId,from,to]);
 const requestCancellation=async item=>{const reason=window.prompt("Αιτιολογία αιτήματος ακύρωσης προς Netlink:");if(!reason?.trim())return;setReportBusy(true);setError("");try{const result=unwrap(await api("/api/netlink/cancellation-requests",{method:"POST",body:JSON.stringify({transactionId:item.id,reason:reason.trim()})}));setMessage(result.message);await loadReports()}catch(e){setError(e.message||"Δεν καταχωρίστηκε το αίτημα ακύρωσης.")}finally{setReportBusy(false)}};
 const count=useMemo(()=>groups.reduce((n,g)=>n+(g.products?.length||0),0),[groups]),ready=Boolean(status?.configured&&config?.configured&&status?.executeEnabled),totals=detail?.totals||{},weekly=settlement?.settlement||{};
 const report=<div className="netlink-report-page"><div className="netlink-report-heading"><div><span>NETLINK REPORTS</span><h3>Συναλλαγές & εκκαθάριση</h3><p>Οι ακυρώσεις καταγράφονται ως αίτημα προς Netlink και δεν εκτελούνται αυτόματα.</p></div><div className="netlink-date-range"><label>Από<input type="date" value={from} onChange={e=>setFrom(e.target.value)}/></label><label>Έως<input type="date" value={to} onChange={e=>setTo(e.target.value)}/></label></div></div><div className="netlink-report-tabs"><button className={reportTab==="detail"?"active":""} onClick={()=>setReportTab("detail")}><FileText/>Αναλυτική ημερήσια</button><button className={reportTab==="summary"?"active":""} onClick={()=>setReportTab("summary")}><BarChart3/>Συνοπτική ημερήσια</button><button className={reportTab==="weekly"?"active":""} onClick={()=>setReportTab("weekly")}><CalendarDays/>Εβδομαδιαία εκκαθάριση</button></div>{reportBusy?<div className="netlink-report-loading">Φόρτωση αναφορών…</div>:<>{reportTab==="detail"&&<><div className="netlink-metrics"><Metric label="Ολοκληρωμένες" value={totals.completed||0}/><Metric label="Αξία καρτών" value={euro(totals.cardAmount)}/><Metric label="Σύνολο πελάτη" value={euro(totals.customerTotal)}/><Metric label="Αιτήματα ακύρωσης" value={totals.cancellationRequests||0}/></div><div className="netlink-report-table"><div className="report-row head"><span>Ημερομηνία / χειριστής</span><span>Προϊόν / αναφορά</span><span>Αξία</span><span>Κατάσταση</span><span>Ακύρωση</span></div>{(detail?.items||[]).map(item=><div className="report-row" key={item.id}><span>{displayDate(item.completedAt||item.createdAt)}<small>{item.operatorName||"—"}</small></span><span>{item.productId}<small>{item.providerReference||item.providerTransactionId||item.requestId}</small></span><strong>{euro(item.amount)}</strong><span><i className={item.status==="COMPLETED"?"ok":"pending"}>{item.status}</i></span><span>{item.cancellationStatus?<i className="pending">{item.cancellationStatus}</i>:item.status==="COMPLETED"?<button className="request-button" onClick={()=>requestCancellation(item)}>Αίτημα</button>:"—"}</span></div>)}{!detail?.items?.length&&<Empty/>}</div></>}{reportTab==="summary"&&<Summary rows={summary?.days}/>} {reportTab==="weekly"&&<><div className="netlink-settlement-card"><div><span>ΕΚΚΑΘΑΡΙΣΗ ΠΕΡΙΟΔΟΥ</span><h4>{from} — {to}</h4><p>Η τελική συμφωνία ολοκληρώνεται μόλις ληφθεί το statement της Netlink.</p></div><div className="settlement-total"><span>Αξία καρτών</span><strong>{euro(weekly.grossAmount)}</strong></div></div><div className="netlink-metrics"><Metric label="Συναλλαγές" value={weekly.transactions||0}/><Metric label="Υπηρεσία" value={euro(weekly.serviceFees)}/><Metric label="Σύνολο πελάτη" value={euro(weekly.customerTotal)}/><Metric label="Προμήθεια" value={euro(weekly.commissionAmount)}/></div><Summary rows={settlement?.dailyBreakdown}/></>}</>}</div>;
 return <div className="netlink-pos-overlay" role="dialog" aria-modal="true"><section className="netlink-pos-panel"><header><div><small>ΠΡΟΠΛΗΡΩΜΕΝΕΣ ΚΑΡΤΕΣ</small><h2>NETLINK</h2></div><div><button onClick={()=>setView(view==="catalog"?"reports":"catalog")}>{view==="catalog"?<><WalletCards/>Αναφορές</>:"Έκδοση καρτών"}</button><button onClick={view==="catalog"?load:loadReports} disabled={loading||reportBusy}><RefreshCw/> Ανανέωση</button><button onClick={onClose}><X/></button></div></header><div className={`netlink-safety ${ready?"ready":"locked"}`}><b>{ready?"Έτοιμο για επιβεβαίωση":"Ασφαλής λειτουργία προβολής"}</b><span>{ready?"Η εκτέλεση απαιτεί ξεχωριστή επιβεβαίωση.":"Δεν εκδίδεται PIN και δεν γίνεται χρέωση από αυτή την οθόνη."}</span></div>{error&&<div className="netlink-error">{error}</div>}{message&&<div className="netlink-safety ready"><b>{message}</b></div>}{view==="reports"?report:loading?<div className="netlink-loading">Φόρτωση καταλόγου…</div>:<div className="netlink-pos-body"><nav>{groups.map(g=><a key={g.title} href={`#nl-${String(g.title).replace(/\W/g,"-")}`}>{g.title}<span>{g.products?.length||0}</span></a>)}</nav><main>{groups.map(g=><section key={g.title} id={`nl-${String(g.title).replace(/\W/g,"-")}`}><h3>{g.title}</h3><div>{(g.products||[]).map(p=><button key={`${g.title}-${p.productId}`} onClick={()=>setSelected({...p,groupTitle:g.title})} className={selected?.productId===p.productId?"selected":""}><b>{p.title}</b><small>Κωδικός {p.productId}</small><span>{p.allowCancellation?"Ακύρωση διαθέσιμη":"Χωρίς ακύρωση"}</span></button>)}</div></section>)}</main><aside>{selected?<><small>{selected.groupTitle}</small><h3>{selected.title}</h3><p>Κωδικός: <b>{selected.productId}</b></p><p>Η πραγματική υπηρεσία παραμένει πίσω από τα production safety gates.</p><button disabled={!ready}>{ready?"Συνέχεια στην επιβεβαίωση":"ΕΚΤΕΛΕΣΗ ΚΛΕΙΔΩΜΕΝΗ"}</button></>:<><h3>Επίλεξε υπηρεσία</h3><p>Διάλεξε προϊόν από τον κατάλογο.</p><small>{count} διαθέσιμες υπηρεσίες</small></>}</aside></div>}</section></div>;
}
function Summary({rows}){return <div className="netlink-report-table"><div className="report-row summary head"><span>Ημέρα</span><span>Συναλλαγές</span><span>Αξία καρτών</span><span>Προμήθεια</span></div>{(rows||[]).map(day=><div className="report-row summary" key={day.date}><strong>{new Date(`${day.date}T12:00:00`).toLocaleDateString("el-GR",{weekday:"long",day:"2-digit",month:"2-digit"})}</strong><span>{day.transactions}</span><strong>{euro(day.grossAmount)}</strong><strong>{euro(day.commissionAmount)}</strong></div>)}{!rows?.length&&<Empty/>}</div>}
