import React,{useEffect,useMemo,useState} from "react";
import {ArrowLeft,Check,FileText,Filter,KeyRound,LockKeyhole,MoreHorizontal,Pencil,Plus,Printer,RefreshCw,Save,Search,ShieldCheck,Trash2,UserRound,UsersRound,X} from "lucide-react";
import "./operator-management.css";

const when=value=>value?new Date(value).toLocaleString("el-GR"):"—";
const roleLabel=role=>role==="MANAGER"?"ΔΙΑΧΕΙΡΙΣΤΗΣ (ΥΠΕΥΘΥΝΟΣ)":"ΧΡΗΣΤΗΣ (ΥΠΑΛΛΗΛΟΣ)";
const boolObject=value=>value&&typeof value==="object"?value:{};
const POS_PERMISSIONS=[
  ["stockPos","στήλη Stock (PoS)"],["stockBackoffice","στήλη Stock (Backoffice)"],["confirmDeleteSale","Επιβεβαίωση διαγραφής λίστας πώλησης (PoS)"],
  ["mixedPaymentChange","Πάντα μικτή πληρωμή και ρέστα (PoS)"],["leftKeys","Εμφάνιση αριστερής στήλης πλήκτρων (PoS)"],["deleteSaleReason","διαγραφή λίστας πώλησης (PoS) με αιτιολογία"],
  ["addBarcode","Προσθήκη barcode είδους (PoS & BackOffice)"],["editDescription","Διόρθωση περιγραφής είδους (PoS)"],["fileItems","Αρχείο ειδών (BackOffice)"],
  ["onlineBarcode","Online αναζήτηση barcode (PoS)"],["itemCard","Καρτέλα είδους (PoS & BackOffice)"],["stocktakeColumn","Εμφάνιση στήλης Stock (Απογραφή)"],
  ["stocktakePos","Απογραφή ειδών (PoS)"],["stocktakeBackoffice","Απογραφή ειδών (BackOffice)"],["transactionDiscount","Έκπτωση συναλλαγής (PoS)"],
  ["changeRetail","Αλλαγή τιμής λιανικής (PoS & BackOffice)"],["itemDiscount","Έκπτωση είδους (PoS)"],["returnItems","Επιστροφή ειδών (PoS)"],
  ["customersPos","Πελάτες (PoS)"],["customersBackoffice","Πελάτες (BackOffice)"],["returnWithCode","με κωδικό για επιστροφή ειδών (PoS)"],
  ["centralCashPos","Εμφάνιση κεντρικού Ταμείου (PoS)"],["centralCashBackoffice","Εμφάνιση κεντρικού Ταμείου (BackOffice)"],["supplierBalances","Υπόλοιπα προμηθευτών (BackOffice)"],
  ["redeemPoints","Εξαργύρωση πόντων πελάτη (PoS)"],["customerCardOnly","Αναζήτηση πελάτη μόνο με αριθμό κάρτας (PoS)"],["thirdPartyPayment","πληρωμή προς Τρίτους"],
  ["hidePrinter","Απόκρυψη εκτυπωτή (PoS)"],["supplierReturn","έκδοση Δ-Α επιστροφής σε προμηθευτή (PoS)"],["supplierPayment","πληρωμή Προμηθευτή"],
  ["sameShiftPayments","Οι πληρωμές να αφαιρούνται από την ίδια βάρδια"],["transferAmount","Μεταφορά ποσού"],["shiftTransactionsBackoffice","Συναλλαγές βάρδιας (backoffice)"],
  ["warehouseColumn","Εμφάνιση στήλης Αποθήκη (Παραγγελίες-BackOffice)"],["shiftTransactionsPos","Συναλλαγές βάρδιας (PoS)"],["allShiftTransactionsPos","Όλες οι συναλλαγές Βάρδιας (PoS)"],
  ["cash","Μετρητά"],["initialCash","με αρχικό Ταμείο"],["cards","Κάρτες"]
];
const MENU_PERMISSIONS=[
  ["management","Διαχείριση"],["purchases","Αγορές"],["priceCatalog","Τιμοκατάλογος"],["cashDesk","Ταμείο"],
  ["categoriesCompanies","Κατηγορίες & εταιρείες"],["orders","Παραγγελίες"],["priceCheck","Έλεγχος τιμών πώλησης"],["vatDepartments","Τμήματα ΦΠΑ"],
  ["orderProposal","Πρόταση Παραγγελίας"],["leafletOffers","Προσφορές φυλλαδίου / δώρα"],["wholesaleCatalog","Τιμοκατάλογος χονδρικής"],["notes","Σημειώσεις (backoffice)"],
  ["replenishment","Αναπλήρωση (άνευ παραγγελίας)"],["purchaseOnly","Καταχώρηση μόνο στις αγορές"],["orderToInvoice","Μετατροπή παραγγελίας σε τιμολόγιο"],
  ["suppliers","Προμηθευτές"],["sales","Πωλήσεις"],["reports","Αναφορές"],["documents","Παραστατικά"],["stocktakes","Απογραφές"],["inventory","Αποθήκη"],
  ["statistics","Στατιστικά"],["priceChanges","Αλλαγές τιμών"],["payments","Πληρωμές"],["operators","Χειριστές"],["systemParams","Παράμετροι συστήματος"]
];
const TAB_PERMISSIONS=[["shiftSales","Πωλήσεις βάρδιας"],["companyImage","Εικόνα επιχείρησης"],["salesAnalysis","Ανάλυση πωλήσεων"],["purchaseAnalysis","Ανάλυση αγορών"],["payments","Πληρωμές"],["shifts","Βάρδιες"],["events","Συμβάντα"]];

function CheckGrid({items,value,onChange,className=""}){
  return <div className={`om-check-grid ${className}`}>{items.map(([key,label])=><label key={key}><input type="checkbox" checked={Boolean(value?.[key])} onChange={e=>onChange({...value,[key]:e.target.checked})}/><span>{label}</span></label>)}</div>;
}
function rowDraft(row){return {
  username:row.username||row.userEmail||row.employeeEmail||"",fullName:row.displayName||"",stationPhone:row.stationPhone||"",mobilePhone:row.mobilePhone||row.employeePhone||"",hourlyRate:Number(row.hourlyRate||0),
  role:row.role||"EMPLOYEE",active:Boolean(row.active),posAccess:row.posAccess!==false,backofficeAccess:Boolean(row.backofficeAccess),powerUser:Boolean(row.powerUser),
  permissions:boolObject(row.permissions),backofficeMenu:boolObject(row.backofficeMenu),backofficeTabs:boolObject(row.backofficeTabs),customerDisplay:boolObject(row.customerDisplay),
  terminalPos:row.terminalPos||"",cashLimit:row.cashLimit==null?"":Number(row.cashLimit),notes:row.notes||"",retailSaleSeries:row.retailSaleSeries||"",retailReturnSeries:row.retailReturnSeries||"",installationAddress:row.installationAddress||"",installationPhone:row.installationPhone||""
}}

export default function OperatorManagementPanel({api,store,onClose}){
  const [data,setData]=useState(null),[loading,setLoading]=useState(true),[error,setError]=useState(""),[message,setMessage]=useState("");
  const [q,setQ]=useState(""),[onlyActive,setOnlyActive]=useState(true),[selected,setSelected]=useState("");
  const [modal,setModal]=useState(null),[tab,setTab]=useState("details"),[draft,setDraft]=useState(null),[busy,setBusy]=useState(false);
  const load=async()=>{setLoading(true);setError("");try{setData(await api(`/api/operator-management/stores/${store.id}/operators`))}catch(e){setError(e.message)}finally{setLoading(false)}};
  useEffect(()=>{load()},[store.id]);
  const rows=useMemo(()=>{
    const needle=q.trim().toLocaleLowerCase("el-GR");
    return (data?.operators||[]).filter(r=>(!onlyActive||r.active)&&(!needle||[r.username,r.userEmail,r.employeeEmail,r.displayName,r.role,r.stationPhone,r.mobilePhone,r.employeePhone].some(v=>String(v||"").toLocaleLowerCase("el-GR").includes(needle))));
  },[data,q,onlyActive]);
  const selectedRow=(data?.operators||[]).find(r=>r.employeeId===selected)||null;

  const edit=row=>{setSelected(row.employeeId);setDraft(rowDraft(row));setTab("details");setModal("edit")};
  const saveEdit=async()=>{setBusy(true);setError("");try{
    await api(`/api/operator-management/stores/${store.id}/operators/${selected}`,{method:"PATCH",body:JSON.stringify({...draft,hourlyRate:Number(draft.hourlyRate||0),cashLimit:draft.cashLimit===""?null:Number(draft.cashLimit)})});
    setMessage("Η καρτέλα χειριστή αποθηκεύτηκε.");setModal(null);await load();
  }catch(e){setError(e.message)}finally{setBusy(false)}};
  const deactivate=async row=>{if(!window.confirm(`Απενεργοποίηση χειριστή «${row.displayName}»;`))return;setError("");try{await api(`/api/operator-management/stores/${store.id}/operators/${row.employeeId}`,{method:"DELETE"});setMessage("Ο χειριστής απενεργοποιήθηκε χωρίς διαγραφή του εργαζομένου.");await load()}catch(e){setError(e.message)}};
  const openPin=row=>{setSelected(row.employeeId);setDraft({pin:"",confirm:""});setModal("pin")};
  const savePin=async()=>{if(!/^\d{4,8}$/.test(draft.pin||""))return setError("Το PIN πρέπει να έχει 4–8 ψηφία.");if(draft.pin!==draft.confirm)return setError("Η επαλήθευση PIN δεν συμφωνεί.");setBusy(true);setError("");try{await api(`/api/operator-management/stores/${store.id}/operators/${selected}/pin`,{method:"POST",body:JSON.stringify({pin:draft.pin})});setMessage("Το PIN άλλαξε και αποθηκεύτηκε με ασφαλές hash.");setModal(null);await load()}catch(e){setError(e.message)}finally{setBusy(false)}};
  const printPin=async()=>{if(!selectedRow)return setError("Επίλεξε πρώτα χειριστή για Εκτύπωση PIN.");if(!window.confirm("Η Εκτύπωση PIN θα δημιουργήσει νέο τυχαίο PIN για τον επιλεγμένο χειριστή. Συνέχεια;"))return;const win=window.open("","_blank","width=520,height=620");try{const result=await api(`/api/operator-management/stores/${store.id}/operators/${selectedRow.employeeId}/pin/random`,{method:"POST",body:"{}"});if(win){win.document.write(`<html><head><title>PIN ${selectedRow.displayName}</title><style>body{font-family:Arial;padding:40px;text-align:center}h1{font-size:22px}.pin{font-size:46px;letter-spacing:10px;border:2px solid #123b5d;padding:24px;margin:30px 0}small{color:#64748b}</style></head><body><h1>MyWorkStation — PIN Χειριστή</h1><h2>${selectedRow.displayName}</h2><div class="pin">${result.pin}</div><small>Το PIN εμφανίζεται μόνο σε αυτή την εκτύπωση.</small><script>window.print()</script></body></html>`);win.document.close()}setMessage("Δημιουργήθηκε νέο PIN και άνοιξε η εκτύπωση.");await load()}catch(e){win?.close();setError(e.message)}};
  const openNew=()=>{setDraft({username:"",fullName:"",email:"",phone:"",role:"EMPLOYEE",active:true,pin:""});setModal("new")};
  const create=async()=>{setBusy(true);setError("");try{await api(`/api/operator-management/stores/${store.id}/operators`,{method:"POST",body:JSON.stringify(draft)});setMessage("Ο νέος χειριστής δημιουργήθηκε.");setModal(null);await load()}catch(e){setError(e.message)}finally{setBusy(false)}};

  return <section className="operator-management-suite">
    <header className="om-title"><div className="om-title-icon"><UsersRound/></div><div><h2>Χειριστές</h2><p>Διαχείριση χειριστών / χρηστών του συστήματος, δικαιωμάτων και στοιχείων πρόσβασης.</p></div></header>
    <section className="om-card">
      <div className="om-card-head"><div><UsersRound/><b>Καταχωρημένοι χειριστές</b><span>{rows.length}</span></div><div className="om-search"><Search/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Αναζήτηση…"/><button><Filter/>Φίλτρα</button></div></div>
      {error&&<div className="om-alert error">{error}</div>}{message&&<div className="om-alert success">{message}</div>}
      {loading?<div className="om-empty">Φόρτωση χειριστών…</div>:<div className="om-table-wrap"><div className="om-table">
        <div className="om-row head"><span>Ενέργειες</span><span>username</span><span>όνομα</span><span>Δικαιώματα</span><span>τηλ. σταθ</span><span>τηλ. κιν</span><span>τελευταία είσοδος</span><span>ημ/νία εγγραφής</span></div>
        {rows.map(row=><button key={row.employeeId} className={`om-row data ${selected===row.employeeId?"selected":""}`} onClick={()=>setSelected(row.employeeId)}>
          <span className="om-actions" onClick={e=>e.stopPropagation()}><i onClick={()=>edit(row)} title="Διόρθωση"><Pencil/></i><i className="danger" onClick={()=>deactivate(row)} title="Απενεργοποίηση"><Trash2/></i><i onClick={()=>openPin(row)} title="Αλλαγή PIN"><LockKeyhole/></i></span>
          <span>{row.username||row.userEmail||row.employeeEmail||"—"}</span><span>{row.displayName}</span><span>{roleLabel(row.role)}</span><span>{row.stationPhone||"—"}</span><span>{row.mobilePhone||row.employeePhone||"—"}</span><span>{when(row.lastLoginAt)}</span><span>{when(row.createdAt)}</span>
        </button>)}
        {!rows.length&&<div className="om-empty">Δεν βρέθηκαν χειριστές με τα φίλτρα που επέλεξες.</div>}
      </div></div>}
      <footer className="om-footer"><button onClick={onClose}><X/>Κλείσιμο</button><button className="primary" onClick={openNew}><Plus/>Νέα εγγραφή</button><button onClick={load}><RefreshCw/>Ανανέωση</button><button onClick={printPin}><Printer/>Εκτύπωση PIN</button><span className="spacer"/><label>Μόνο οι ενεργοί χειριστές <input type="checkbox" checked={onlyActive} onChange={e=>setOnlyActive(e.target.checked)}/><i>{onlyActive?"ΝΑΙ":"ΟΧΙ"}</i></label></footer>
    </section>

    {modal==="edit"&&draft&&<div className="om-modal-overlay"><div className="om-modal wide">
      <div className="om-modal-title"><div><UserRound/><span><b>{selectedRow?.username||selectedRow?.userEmail||"ΧΕΙΡΙΣΤΗΣ"} ({draft.fullName})</b><small>Διαχείριση χειριστή / δικαιωμάτων πρόσβασης</small></span></div><button onClick={()=>setModal(null)}><X/></button></div>
      <div className="om-tabs"><button className={tab==="details"?"active":""} onClick={()=>setTab("details")}><UserRound/>Στοιχεία χειριστή</button><button className={tab==="access"?"active":""} onClick={()=>setTab("access")}><LockKeyhole/>Δικαιώματα πρόσβασης</button><button className={tab==="other"?"active":""} onClick={()=>setTab("other")}><MoreHorizontal/>Λοιπά</button><button className={tab==="docs"?"active":""} onClick={()=>setTab("docs")}><FileText/>Παραστατικά</button></div>
      <div className="om-modal-body">
        {tab==="details"&&<><div className="om-profile-top"><label className="wide">όνομα<input value={draft.fullName} onChange={e=>setDraft({...draft,fullName:e.target.value})}/></label><label>τηλ.<input value={draft.stationPhone} onChange={e=>setDraft({...draft,stationPhone:e.target.value})}/></label><label>κιν.<input value={draft.mobilePhone} onChange={e=>setDraft({...draft,mobilePhone:e.target.value})}/></label><label>μισθός<input type="number" step="0.0001" value={draft.hourlyRate} onChange={e=>setDraft({...draft,hourlyRate:e.target.value})}/></label><div className="om-top-flags"><label><input type="checkbox" checked={draft.posAccess} onChange={e=>setDraft({...draft,posAccess:e.target.checked})}/>Πρόσβαση στις Πωλήσεις (PoS)</label><label><input type="checkbox" checked={draft.backofficeAccess} onChange={e=>setDraft({...draft,backofficeAccess:e.target.checked})}/>Πρόσβαση στο BackOffice</label><label><input type="checkbox" checked={draft.active} onChange={e=>setDraft({...draft,active:e.target.checked})}/>ενεργός</label><label><input type="checkbox" checked={draft.powerUser} onChange={e=>setDraft({...draft,powerUser:e.target.checked})}/>Power User</label></div></div><div className="om-role"><label><input type="radio" checked={draft.role==="MANAGER"} onChange={()=>setDraft({...draft,role:"MANAGER"})}/>Διαχειριστής</label><label><input type="radio" checked={draft.role==="EMPLOYEE"} onChange={()=>setDraft({...draft,role:"EMPLOYEE"})}/>Πωλητής</label></div><CheckGrid items={POS_PERMISSIONS} value={draft.permissions} onChange={permissions=>setDraft({...draft,permissions})}/></>}
        {tab==="access"&&<><section className="om-group"><h3><ShieldCheck/>backoffice μενού</h3><CheckGrid items={MENU_PERMISSIONS} value={draft.backofficeMenu} onChange={backofficeMenu=>setDraft({...draft,backofficeMenu})}/></section><section className="om-group"><h3>backoffice καρτέλες</h3><CheckGrid className="tabs" items={TAB_PERMISSIONS} value={draft.backofficeTabs} onChange={backofficeTabs=>setDraft({...draft,backofficeTabs})}/></section></>}
        {tab==="other"&&<><section className="om-group"><h3>οθόνη πελάτη</h3><div className="om-form-grid"><label className="check"><input type="checkbox" checked={Boolean(draft.customerDisplay.doubleScreen)} onChange={e=>setDraft({...draft,customerDisplay:{...draft.customerDisplay,doubleScreen:e.target.checked}})}/>Χρήση διπλής οθόνης</label><label>VFD customer display port<input value={draft.customerDisplay.port||""} onChange={e=>setDraft({...draft,customerDisplay:{...draft.customerDisplay,port:e.target.value}})} placeholder="π.χ. COM2"/></label><label>τύπος VFD<select value={draft.customerDisplay.vfdType||"POS7303"} onChange={e=>setDraft({...draft,customerDisplay:{...draft.customerDisplay,vfdType:e.target.value}})}><option value="POS7303">POS 7303</option><option value="VFD850">VFD-850 Series</option></select></label><label>character/command table<select value={draft.customerDisplay.commandTable||"DEFAULT"} onChange={e=>setDraft({...draft,customerDisplay:{...draft.customerDisplay,commandTable:e.target.value}})}><option value="DEFAULT">προεπιλογή</option><option value="EPSON">EPSON Esc/POS mode</option></select></label></div></section><section className="om-group"><h3>Τερματικό PoS (παράκαμψη για χειριστή)</h3><label>τερματικό PoS<input value={draft.terminalPos} onChange={e=>setDraft({...draft,terminalPos:e.target.value})}/></label></section><section className="om-group"><h3>όριο πληρωμών</h3><label>με μετρητά όριο μέχρι:<input type="number" step="0.01" value={draft.cashLimit} onChange={e=>setDraft({...draft,cashLimit:e.target.value})}/></label></section><section className="om-group"><h3>σημειώσεις</h3><textarea value={draft.notes} onChange={e=>setDraft({...draft,notes:e.target.value})}/></section></>}
        {tab==="docs"&&<section className="om-group"><h3>Σειρά παραστατικών λιανικής</h3><div className="om-doc-form"><label>Λιανική πώληση:<input value={draft.retailSaleSeries} onChange={e=>setDraft({...draft,retailSaleSeries:e.target.value})} placeholder="Επιλέξτε σειρά παραστατικών…"/></label><label>Επιστροφή λιανικής:<input value={draft.retailReturnSeries} onChange={e=>setDraft({...draft,retailReturnSeries:e.target.value})} placeholder="Επιλέξτε σειρά παραστατικών…"/></label><label>Διεύθυνση εγκατάστασης:<input value={draft.installationAddress} onChange={e=>setDraft({...draft,installationAddress:e.target.value})}/><small>(μόνο αν είναι διαφορετική από την διεύθυνση της επιχείρησης)</small></label><label>Τηλ. εγκατάστασης:<input value={draft.installationPhone} onChange={e=>setDraft({...draft,installationPhone:e.target.value})}/><small>(μόνο αν είναι διαφορετικό από το τηλ. της επιχείρησης)</small></label></div></section>}
      </div><div className="om-modal-actions"><button onClick={()=>setModal(null)}><ArrowLeft/>Επιστροφή</button><button className="primary" onClick={saveEdit} disabled={busy}><Save/>{busy?"Αποθήκευση…":"Καταχώρηση"}</button></div>
    </div></div>}

    {modal==="pin"&&draft&&<div className="om-modal-overlay"><div className="om-modal small"><div className="om-modal-title"><div><KeyRound/><span><b>Αλλαγή κωδικού πρόσβασης</b><small>Στοιχεία εγγραφής</small></span></div><button onClick={()=>setModal(null)}><X/></button></div><div className="om-pin"><strong>{selectedRow?.username||selectedRow?.userEmail||"—"}</strong><p>Ονοματεπώνυμο: <b>{selectedRow?.displayName}</b></p><label>Νέος κωδικός:<input type="password" inputMode="numeric" maxLength="8" value={draft.pin} onChange={e=>setDraft({...draft,pin:e.target.value.replace(/\D/g,"")})}/></label><label>Επαλήθευση:<input type="password" inputMode="numeric" maxLength="8" value={draft.confirm} onChange={e=>setDraft({...draft,confirm:e.target.value.replace(/\D/g,"")})}/></label></div><div className="om-modal-actions"><button onClick={()=>setModal(null)}><ArrowLeft/>Επιστροφή</button><button className="primary" onClick={savePin} disabled={busy}><Check/>Καταχώρηση</button></div></div></div>}

    {modal==="new"&&draft&&<div className="om-modal-overlay"><div className="om-modal small"><div className="om-modal-title"><div><Plus/><span><b>Νέα εγγραφή χειριστή</b><small>{store.name}</small></span></div><button onClick={()=>setModal(null)}><X/></button></div><div className="om-new-form"><label>username<input value={draft.username} onChange={e=>setDraft({...draft,username:e.target.value})}/></label><label>Ονοματεπώνυμο<input value={draft.fullName} onChange={e=>setDraft({...draft,fullName:e.target.value})}/></label><label>Email<input type="email" value={draft.email} onChange={e=>setDraft({...draft,email:e.target.value})}/></label><label>Τηλέφωνο<input value={draft.phone} onChange={e=>setDraft({...draft,phone:e.target.value})}/></label><label>Ρόλος<select value={draft.role} onChange={e=>setDraft({...draft,role:e.target.value})}><option value="EMPLOYEE">Χρήστης / Υπάλληλος</option><option value="MANAGER">Διαχειριστής / Υπεύθυνος</option></select></label><label>Αρχικό PIN<input type="password" inputMode="numeric" maxLength="8" value={draft.pin} onChange={e=>setDraft({...draft,pin:e.target.value.replace(/\D/g,"")})} placeholder="Προαιρετικά, 4–8 ψηφία"/></label><label className="check"><input type="checkbox" checked={draft.active} onChange={e=>setDraft({...draft,active:e.target.checked})}/>Ενεργός χειριστής</label></div><div className="om-modal-actions"><button onClick={()=>setModal(null)}><ArrowLeft/>Επιστροφή</button><button className="primary" onClick={create} disabled={busy||!draft.fullName}><Save/>Καταχώρηση</button></div></div></div>}
  </section>;
}
