import React,{useEffect,useState} from "react";
import {Download,LockKeyhole,RefreshCw} from "lucide-react";
import "./payroll-period.css";

const duration=minutes=>`${Math.floor(Number(minutes||0)/60)}ω ${Number(minutes||0)%60}λ`;
const date=value=>new Date(value).toLocaleDateString("el-GR");
const inclusiveEnd=value=>date(new Date(value).getTime()-1);

export default function PayrollPeriodPanel({api,storeId,month,range}){
  const [periods,setPeriods]=useState([]),[detail,setDetail]=useState(null),[busy,setBusy]=useState(false),[error,setError]=useState(""),[message,setMessage]=useState("");
  const load=async selectedId=>{setError("");try{const rows=await api("/api/attendance/payroll-periods");setPeriods(rows);const selected=selectedId||detail?.period?.id||rows[0]?.id;if(selected)setDetail(await api(`/api/attendance/payroll-periods/${selected}`));else setDetail(null)}catch(e){setError(e.message)}};
  useEffect(()=>{load()},[]);
  const create=async()=>{setBusy(true);setError("");setMessage("");try{const created=await api("/api/attendance/payroll-periods",{method:"POST",body:JSON.stringify({name:`Ώρες ${month}`,storeId,from:range.from,to:range.to})});setMessage(created.sourceIssues?`Η περίοδος δημιουργήθηκε με ${created.sourceIssues} εκκρεμότητες.`:"Η περίοδος δημιουργήθηκε και είναι έτοιμη για έλεγχο.");await load(created.id)}catch(e){setError(e.message)}finally{setBusy(false)}};
  const saveEntry=async(event,entry)=>{event.preventDefault();setBusy(true);setError("");const form=new FormData(event.currentTarget);try{await api(`/api/attendance/payroll-periods/${detail.period.id}/entries/${entry.id}`,{method:"PATCH",body:JSON.stringify({overtimeMinutes:Math.round(Number(form.get("overtimeHours")||0)*60),absenceMinutes:Math.round(Number(form.get("absenceHours")||0)*60),note:form.get("note")||null})});setMessage(`Αποθηκεύτηκε: ${entry.employeeName}`);await load(detail.period.id)}catch(e){setError(e.message)}finally{setBusy(false)}};
  const action=async kind=>{if(kind==="refresh"&&!window.confirm("Η ανανέωση θα ξαναφέρει τις πραγματικές ώρες και θα μηδενίσει τις χειροκίνητες υπερωρίες/απουσίες της περιόδου. Συνέχεια;"))return;setBusy(true);setError("");setMessage("");try{await api(`/api/attendance/payroll-periods/${detail.period.id}/${kind}`,{method:"POST",body:"{}"});setMessage(kind==="finalize"?"Η περίοδος κλειδώθηκε.":"Οι ώρες ανανεώθηκαν από τις παρουσίες.");await load(detail.period.id)}catch(e){setError(e.message)}finally{setBusy(false)}};
  const exportExcel=async()=>{setBusy(true);setError("");try{const file=await api(`/api/attendance/payroll-periods/${detail.period.id}/export`);const link=document.createElement("a");link.href=file.dataUrl;link.download=file.filename;document.body.appendChild(link);link.click();link.remove()}catch(e){setError(e.message)}finally{setBusy(false)}};
  return <div className="payroll-panel">{error&&<div className="commerce-error">{error}</div>}{message&&<div className="commerce-success">{message}</div>}<div className="payroll-toolbar"><button onClick={create} disabled={busy}>Νέα περίοδος από {month}</button><p>Οι πραγματικές ώρες αντιγράφονται ως ελεγχόμενο στιγμιότυπο. Δεν υπολογίζεται αυτόματα μισθός.</p></div><div className="payroll-layout"><aside className="attendance-card"><h3>Περίοδοι</h3><div className="payroll-period-list">{periods.map(period=><button className={detail?.period?.id===period.id?"active":""} key={period.id} onClick={()=>load(period.id)}><b>{period.name}</b><span>{period.storeName||"Όλα τα καταστήματα"}</span><small>{date(period.startDate)} – {inclusiveEnd(period.endDate)} · {period.status}</small><em>{duration(period.workedMinutes)} · {period.sourceIssues} εκκρ.</em></button>)}</div></aside><section className="attendance-card">{detail?<><div className="payroll-head"><div><h3>{detail.period.name}</h3><p>{detail.period.storeName||"Όλα τα καταστήματα"} · {detail.period.status}</p></div><div><button onClick={exportExcel} disabled={busy}><Download/>Excel</button>{detail.period.status==="DRAFT"&&<><button onClick={()=>action("refresh")} disabled={busy}><RefreshCw/>Ανανέωση από παρουσίες</button><button onClick={()=>action("finalize")} disabled={busy}><LockKeyhole/>Κλείδωμα</button></>}</div></div><div className="payroll-entries">{detail.entries.map(entry=><form key={entry.id} onSubmit={event=>saveEntry(event,entry)}><div><b>{entry.employeeName}</b><small>{entry.storeName} · Πραγματικές: {duration(entry.workedMinutes)}</small>{entry.sourceIssues>0&&<em>{entry.sourceIssues} εκκρεμότητες παρουσίας</em>}</div><label>Υπερωρίες (ώρες)<input name="overtimeHours" type="number" min="0" step="0.25" defaultValue={(entry.overtimeMinutes/60).toFixed(2)} disabled={detail.period.status!=="DRAFT"}/></label><label>Απουσίες (ώρες)<input name="absenceHours" type="number" min="0" step="0.25" defaultValue={(entry.absenceMinutes/60).toFixed(2)} disabled={detail.period.status!=="DRAFT"}/></label><label>Σημείωση<input name="note" defaultValue={entry.note||""} disabled={detail.period.status!=="DRAFT"}/></label>{detail.period.status==="DRAFT"&&<button disabled={busy}>Αποθήκευση</button>}</form>)}</div></>:<p>Δημιούργησε ή επίλεξε περίοδο.</p>}</section></div></div>;
}
