import React,{useEffect,useState} from "react";
import "./pos-sale-actions.css";

const money=value=>Number(value||0).toLocaleString("el-GR",{style:"currency",currency:"EUR"});
const localInput=value=>{const d=value?new Date(value):new Date();if(!Number.isFinite(d.getTime()))return "";const pad=n=>String(n).padStart(2,"0");return `${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}T${pad(d.getHours())}:${pad(d.getMinutes())}`};
const globalContext=()=>globalThis.__mwsPosDelayedSaleContext||null;

export default function PosSaleActionsPanel({api,storeId}){
  const [historyOpen,setHistoryOpen]=useState(false),[delayedOpen,setDelayedOpen]=useState(false),[rows,setRows]=useState([]),[loading,setLoading]=useState(false);
  const [delayed,setDelayed]=useState(()=>globalContext()),[occurredAt,setOccurredAt]=useState(()=>localInput()),[delayedReason,setDelayedReason]=useState("");
  const [target,setTarget]=useState(null),[kind,setKind]=useState("RETURN"),[reason,setReason]=useState(""),[busy,setBusy]=useState(false),[error,setError]=useState(""),[message,setMessage]=useState("");

  useEffect(()=>{const consumed=event=>{setDelayed(null);setMessage(event.detail?.message||"Η ετεροχρονισμένη πώληση καταχωρήθηκε.")};const changed=()=>setDelayed(globalContext());window.addEventListener("mws:pos-delayed-consumed",consumed);window.addEventListener("mws:pos-delayed-changed",changed);return()=>{window.removeEventListener("mws:pos-delayed-consumed",consumed);window.removeEventListener("mws:pos-delayed-changed",changed)}},[]);

  const loadRecent=async()=>{setLoading(true);setError("");try{const result=await api(`/api/store-pos/stores/${encodeURIComponent(storeId)}/sales/recent`);setRows(result.rows||[])}catch(err){setError(err.message)}finally{setLoading(false)}};
  const openHistory=()=>{setHistoryOpen(true);loadRecent()};
  const activateDelayed=()=>{setError("");const d=new Date(occurredAt);if(!Number.isFinite(d.getTime()))return setError("Διάλεξε έγκυρη ημερομηνία και ώρα.");if(delayedReason.trim().length<3)return setError("Γράψε αιτιολογία τουλάχιστον 3 χαρακτήρων.");const context={occurredAt:d.toISOString(),reason:delayedReason.trim(),createdAt:new Date().toISOString()};globalThis.__mwsPosDelayedSaleContext=context;setDelayed(context);window.dispatchEvent(new CustomEvent("mws:pos-delayed-changed"));setDelayedOpen(false);setMessage("Η ΕΠΟΜΕΝΗ ολοκληρωμένη πώληση θα καταχωρηθεί ως ετεροχρονισμένη.")};
  const clearDelayed=()=>{delete globalThis.__mwsPosDelayedSaleContext;setDelayed(null);window.dispatchEvent(new CustomEvent("mws:pos-delayed-changed"));setMessage("Ακυρώθηκε η ετεροχρονισμένη λειτουργία για την επόμενη πώληση.")};
  const startReverse=(sale,nextKind)=>{setTarget(sale);setKind(nextKind);setReason("");setError("")};
  const submitReverse=async()=>{if(!target||reason.trim().length<3)return setError("Γράψε αιτιολογία τουλάχιστον 3 χαρακτήρων.");setBusy(true);setError("");try{const result=await api(`/api/store-pos/stores/${encodeURIComponent(storeId)}/sales/${encodeURIComponent(target.id)}/reverse`,{method:"POST",body:JSON.stringify({kind,reason:reason.trim()})});setMessage(`${kind==="CANCEL"?"Ακύρωση":"Επιστροφή"} ${money(result.total)} καταχωρήθηκε με πλήρες audit.`);setTarget(null);setReason("");await loadRecent()}catch(err){setError(err.message)}finally{setBusy(false)}};

  return <>
    <div className="pos-sale-actions-dock">
      {delayed&&<div className="pos-delayed-active"><b>ΕΤΕΡΟΧΡ. ΕΝΕΡΓΗ</b><span>{new Date(delayed.occurredAt).toLocaleString("el-GR")}</span><button onClick={clearDelayed}>Ακύρωση</button></div>}
      <button className="primary" onClick={()=>{setOccurredAt(localInput());setDelayedReason("");setDelayedOpen(true);setError("")}}>🕘 ΕΤΕΡΟΧΡ.</button>
      <button onClick={openHistory}>↩ ΠΩΛΗΣΕΙΣ / ΑΚΥΡΩΣΗ</button>
    </div>
    {(message||error)&&<div className={`pos-sale-actions-toast ${error?"error":""}`} onClick={()=>{setMessage("");setError("")}}>{error||message}</div>}

    {delayedOpen&&<div className="pos-sale-actions-overlay"><section className="pos-sale-actions-modal small"><header><div><small>TEST POS · ΜΗ ΦΟΡΟΛΟΓΙΚΟ</small><h3>Ετεροχρονισμένη επόμενη πώληση</h3></div><button onClick={()=>setDelayedOpen(false)}>✕</button></header><p>Η επόμενη ολοκληρωμένη πώληση θα γραφτεί με τον παρακάτω πραγματικό χρόνο συναλλαγής, ενώ ο χρόνος καταχώρησης θα παραμείνει στο audit.</p><label>Ημερομηνία / ώρα συναλλαγής<input type="datetime-local" value={occurredAt} onChange={e=>setOccurredAt(e.target.value)}/></label><label>Αιτιολογία<textarea value={delayedReason} onChange={e=>setDelayedReason(e.target.value)} placeholder="π.χ. συναλλαγή που καταχωρήθηκε αργότερα"/></label>{error&&<div className="pos-sale-actions-error">{error}</div>}<footer><button className="secondary" onClick={()=>setDelayedOpen(false)}>Κλείσιμο</button><button className="primary" onClick={activateDelayed}>Ενεργοποίηση για επόμενη πώληση</button></footer></section></div>}

    {historyOpen&&<div className="pos-sale-actions-overlay"><section className="pos-sale-actions-modal"><header><div><small>TEST POS · ΜΗ ΦΟΡΟΛΟΓΙΚΟ</small><h3>Πρόσφατες πωλήσεις</h3></div><button onClick={()=>setHistoryOpen(false)}>✕</button></header><div className="pos-sale-actions-toolbar"><button onClick={loadRecent} disabled={loading}>{loading?"Ανανέωση…":"Ανανέωση"}</button><span>Ακύρωση = μόνο τρέχουσα βάρδια · Επιστροφή = παλιότερη πώληση</span></div>{error&&<div className="pos-sale-actions-error">{error}</div>}<div className="pos-sale-actions-list">{rows.map(row=><article key={row.id} className={row.reversalState?"reversed":""}><div className="sale-main"><b>{money(row.total)}</b><span>{new Date(row.occurredAt).toLocaleString("el-GR")}</span><small>{row.customerName||"Χωρίς πελάτη"} · {(row.payments||[]).map(p=>`${p.method} ${money(p.amount)}`).join(" + ")}</small>{row.transactionMode==="DELAYED"&&<em>Ετεροχρονισμένη · καταχώρηση {new Date(row.createdAt).toLocaleString("el-GR")}</em>}{row.reversalState&&<strong>{row.reversalState==="CANCEL"?"ΑΚΥΡΩΜΕΝΗ":"ΕΠΙΣΤΡΑΦΗΚΕ"}</strong>}</div><div className="sale-lines">{(row.lines||[]).slice(0,4).map((line,index)=><span key={`${row.id}-${index}`}>{line.description} × {line.quantity}</span>)}</div><div className="sale-actions"><button disabled={Boolean(row.reversalState)} onClick={()=>startReverse(row,"CANCEL")}>Ακύρωση</button><button disabled={Boolean(row.reversalState)} onClick={()=>startReverse(row,"RETURN")}>Επιστροφή</button></div></article>)}{!loading&&!rows.length&&<div className="empty">Δεν υπάρχουν ακόμη ολοκληρωμένες POS πωλήσεις.</div>}</div><footer><button className="secondary" onClick={()=>setHistoryOpen(false)}>Κλείσιμο</button></footer></section></div>}

    {target&&<div className="pos-sale-actions-overlay top"><section className="pos-sale-actions-modal small"><header><div><small>{kind==="CANCEL"?"ΑΚΥΡΩΣΗ":"ΕΠΙΣΤΡΟΦΗ"}</small><h3>{money(target.total)} · {new Date(target.occurredAt).toLocaleString("el-GR")}</h3></div><button onClick={()=>setTarget(null)}>✕</button></header><p>{kind==="CANCEL"?"Η αρχική πώληση θα παραμείνει στο ιστορικό και θα δημιουργηθεί πλήρης αντίστροφη εγγραφή στην ίδια ανοιχτή βάρδια.":"Θα δημιουργηθεί νέα αρνητική εγγραφή επιστροφής στην τρέχουσα ανοιχτή βάρδια και θα συνδεθεί με την αρχική πώληση."}</p><label>Αιτιολογία<textarea autoFocus value={reason} onChange={e=>setReason(e.target.value)} placeholder="Υποχρεωτική αιτιολογία"/></label>{error&&<div className="pos-sale-actions-error">{error}</div>}<footer><button className="secondary" disabled={busy} onClick={()=>setTarget(null)}>Πίσω</button><button className="danger" disabled={busy} onClick={submitReverse}>{busy?"Καταχώρηση…":kind==="CANCEL"?"Καταχώρηση ακύρωσης":"Καταχώρηση επιστροφής"}</button></footer></section></div>}
  </>;
}
