import React,{useEffect,useMemo,useState} from "react";
import {ChefHat,Plus,Save,Trash2,X} from "lucide-react";

const num=v=>Number(v||0);
const euro=v=>`${num(v).toFixed(2)} €`;
const unitLabel=u=>u==="GR"?"gr":u==="ML"?"ml":"τεμ.";

export default function ProductPreparationEditor({api,product,onClose}){
 const [catalog,setCatalog]=useState({groups:[],ingredients:[]}),[data,setData]=useState(null),[section,setSection]=useState("recipe"),[busy,setBusy]=useState(false),[error,setError]=useState(""),[message,setMessage]=useState("");
 const [settings,setSettings]=useState({preparationEnabled:false,environmentalFee:0,productionStation:"ΠΑΡΑΓΩΓΗ",autoPrint:true});
 const [recipeDraft,setRecipeDraft]=useState({ingredientProductId:"",quantity:"1",unit:"PCS",automatic:true});
 const [groupDraft,setGroupDraft]=useState({groupId:"",required:false,minSelections:0,maxSelections:1,sequence:0});
 const load=async()=>{setBusy(true);setError("");try{const [c,p]=await Promise.all([api("/api/management/preparation/catalog"),api(`/api/management/preparation/products/${product.id}`)]);setCatalog(c||{groups:[],ingredients:[]});setData(p);setSettings({preparationEnabled:Boolean(p.settings?.preparationEnabled),environmentalFee:num(p.settings?.environmentalFee),productionStation:p.settings?.productionStation||"ΠΑΡΑΓΩΓΗ",autoPrint:p.settings?.autoPrint!==false})}catch(e){setError(e.message)}finally{setBusy(false)}};
 useEffect(()=>{load()},[product.id]);
 const assigned=new Set((data?.groups||[]).map(g=>g.groupId));
 const availableGroups=useMemo(()=>(catalog.groups||[]).filter(g=>!assigned.has(g.id)),[catalog.groups,data?.groups]);
 const saveSettings=async()=>{setBusy(true);setError("");try{await api(`/api/management/preparation/products/${product.id}/settings`,{method:"PUT",body:JSON.stringify({...settings,environmentalFee:num(settings.environmentalFee)})});setMessage("Οι ρυθμίσεις παρασκευής αποθηκεύτηκαν.");await load()}catch(e){setError(e.message)}finally{setBusy(false)}};
 const addRecipe=async()=>{if(!recipeDraft.ingredientProductId)return setError("Επίλεξε υλικό.");setBusy(true);setError("");try{await api(`/api/management/preparation/products/${product.id}/recipe`,{method:"POST",body:JSON.stringify({...recipeDraft,quantity:num(recipeDraft.quantity)})});setRecipeDraft({ingredientProductId:"",quantity:"1",unit:"PCS",automatic:true});setMessage("Το υλικό προστέθηκε στη συνταγή.");await load()}catch(e){setError(e.message)}finally{setBusy(false)}};
 const removeRecipe=async id=>{setBusy(true);try{await api(`/api/management/preparation/recipe/${id}`,{method:"DELETE"});await load()}catch(e){setError(e.message)}finally{setBusy(false)}};
 const addGroup=async()=>{if(!groupDraft.groupId)return setError("Επίλεξε ομάδα Modifier.");setBusy(true);setError("");try{await api(`/api/management/preparation/products/${product.id}/groups`,{method:"POST",body:JSON.stringify(groupDraft)});setGroupDraft({groupId:"",required:false,minSelections:0,maxSelections:1,sequence:(data?.groups||[]).length+1});setMessage("Η ομάδα Modifiers συνδέθηκε στο προϊόν.");await load()}catch(e){setError(e.message)}finally{setBusy(false)}};
 const saveGroup=async g=>{setBusy(true);setError("");try{await api(`/api/management/preparation/products/${product.id}/groups`,{method:"POST",body:JSON.stringify({groupId:g.groupId,required:Boolean(g.required),minSelections:num(g.minSelections),maxSelections:num(g.maxSelections)||1,sequence:num(g.sequence)})});setMessage("Η ομάδα ενημερώθηκε.");await load()}catch(e){setError(e.message)}finally{setBusy(false)}};
 const removeGroup=async g=>{setBusy(true);try{await api(`/api/management/preparation/products/${product.id}/groups/${g.groupId}`,{method:"DELETE"});await load()}catch(e){setError(e.message)}finally{setBusy(false)}};
 const patchGroup=(id,key,value)=>setData(d=>({...d,groups:(d.groups||[]).map(g=>g.groupId===id?{...g,[key]:value}:g)}));
 const groupInfo=id=>(catalog.groups||[]).find(g=>g.id===id);
 return <div className="prep-admin-backdrop"><section className="prep-admin-modal"><header><div><small>MYWORKSTATION · ΑΡΧΕΙΟ ΕΙΔΩΝ</small><h2><ChefHat/> {product.name}</h2><span>{product.sku||"Χωρίς κωδικό"} · Παρασκευή / Modifiers</span></div><button onClick={onClose}><X/></button></header>
  <div className="prep-admin-settings"><label className="switch"><input type="checkbox" checked={settings.preparationEnabled} onChange={e=>setSettings(s=>({...s,preparationEnabled:e.target.checked}))}/><span>ΠΡΟΪΟΝ ΠΑΡΑΣΚΕΥΗΣ</span></label><label>Εισφορά περιβάλλοντος (€)<input type="number" step="0.01" min="0" value={settings.environmentalFee} onChange={e=>setSettings(s=>({...s,environmentalFee:e.target.value}))}/></label><label>Σταθμός παραγωγής<input value={settings.productionStation} onChange={e=>setSettings(s=>({...s,productionStation:e.target.value}))}/></label><label className="switch"><input type="checkbox" checked={settings.autoPrint} onChange={e=>setSettings(s=>({...s,autoPrint:e.target.checked}))}/><span>Αυτόματη εκτύπωση</span></label><button className="primary" onClick={saveSettings} disabled={busy}><Save/> Αποθήκευση</button></div>
  <nav><button className={section==="recipe"?"active":""} onClick={()=>setSection("recipe")}>ΣΥΝΤΑΓΗ</button><button className={section==="modifiers"?"active":""} onClick={()=>setSection("modifiers")}>MODIFIERS</button><button className={section==="production"?"active":""} onClick={()=>setSection("production")}>ΠΑΡΑΓΩΓΗ</button></nav>
  {error&&<div className="prep-admin-error">{error}</div>}{message&&<div className="prep-admin-success">{message}</div>}
  <main>{busy&&!data?<div className="prep-admin-empty">Φόρτωση…</div>:section==="recipe"?<div className="prep-admin-section"><h3>ΒΑΣΙΚΗ ΣΥΝΤΑΓΗ</h3><p>Κάθε γραμμή συνδέεται με πραγματικό υλικό της Αποθήκης και αφαιρεί stock στην παρασκευή.</p><div className="recipe-head"><span>Υλικό</span><span>Ποσότητα</span><span>Μονάδα</span><span>Stock</span><span></span></div>{(data?.recipe||[]).map(r=><div className="recipe-row" key={r.id}><b>{r.ingredientName}</b><span>{num(r.quantity)}</span><span>{unitLabel(r.unit)}</span><span>{r.automatic?"Αυτόματα":"Χειροκίνητα"}</span><button onClick={()=>removeRecipe(r.id)}><Trash2/></button></div>)}{!(data?.recipe||[]).length&&<div className="prep-admin-empty">Δεν έχει οριστεί ακόμη συνταγή.</div>}<div className="recipe-add"><select value={recipeDraft.ingredientProductId} onChange={e=>setRecipeDraft(d=>({...d,ingredientProductId:e.target.value}))}><option value="">Επίλεξε υλικό…</option>{(catalog.ingredients||[]).map(i=><option key={i.id} value={i.id}>{i.name} · {i.sku}</option>)}</select><input type="number" min="0.001" step="0.001" value={recipeDraft.quantity} onChange={e=>setRecipeDraft(d=>({...d,quantity:e.target.value}))}/><select value={recipeDraft.unit} onChange={e=>setRecipeDraft(d=>({...d,unit:e.target.value}))}><option value="PCS">ΤΕΜ</option><option value="GR">GR</option><option value="ML">ML</option></select><label><input type="checkbox" checked={recipeDraft.automatic} onChange={e=>setRecipeDraft(d=>({...d,automatic:e.target.checked}))}/> Αυτόματα</label><button className="primary" onClick={addRecipe}><Plus/> Προσθήκη</button></div></div>:
  section==="modifiers"?<div className="prep-admin-section"><h3>ΟΜΑΔΕΣ MODIFIERS</h3><p>Ενεργοποίησε μόνο τις ομάδες που πρέπει να εμφανίζονται στο POS για αυτό το προϊόν.</p><div className="modifier-grid">{(data?.groups||[]).map(g=>{const info=groupInfo(g.groupId);return <article key={g.groupId}><div className="modifier-title"><b>{g.groupName}</b><button onClick={()=>removeGroup(g)}><Trash2/></button></div><div className="modifier-items">{(info?.items||[]).map(m=><span key={m.id}>{m.description}{num(m.price)!==0?` · ${euro(m.price)}`:""}</span>)}</div><div className="modifier-rules"><label><input type="checkbox" checked={Boolean(g.required)} onChange={e=>patchGroup(g.groupId,"required",e.target.checked)}/> Υποχρεωτική</label><label>Min<input type="number" min="0" value={g.minSelections} onChange={e=>patchGroup(g.groupId,"minSelections",e.target.value)}/></label><label>Max<input type="number" min="1" value={g.maxSelections} onChange={e=>patchGroup(g.groupId,"maxSelections",e.target.value)}/></label><label>Σειρά<input type="number" min="0" value={g.sequence} onChange={e=>patchGroup(g.groupId,"sequence",e.target.value)}/></label><button onClick={()=>saveGroup(g)}><Save/> Αποθήκευση</button></div></article>})}</div><div className="modifier-add"><select value={groupDraft.groupId} onChange={e=>setGroupDraft(d=>({...d,groupId:e.target.value}))}><option value="">Προσθήκη ομάδας…</option>{availableGroups.map(g=><option key={g.id} value={g.id}>{g.description}</option>)}</select><label><input type="checkbox" checked={groupDraft.required} onChange={e=>setGroupDraft(d=>({...d,required:e.target.checked}))}/> Υποχρεωτική</label><label>Min<input type="number" min="0" value={groupDraft.minSelections} onChange={e=>setGroupDraft(d=>({...d,minSelections:e.target.value}))}/></label><label>Max<input type="number" min="1" value={groupDraft.maxSelections} onChange={e=>setGroupDraft(d=>({...d,maxSelections:e.target.value}))}/></label><button className="primary" onClick={addGroup}><Plus/> Σύνδεση</button></div></div>:
  <div className="prep-admin-section production"><h3>ΠΑΡΑΓΩΓΗ / ΕΚΤΥΠΩΣΗ</h3><div className="production-card"><b>Σταθμός</b><strong>{settings.productionStation||"ΠΑΡΑΓΩΓΗ"}</strong><span>Η εντολή παραγωγής αποστέλλεται από το POS μαζί με Modifiers, ειδικές οδηγίες και προτεραιότητα.</span></div><div className="priority-preview"><b>ΠΡΟΤΕΡΑΙΟΤΗΤΕΣ ΕΚΤΥΠΩΣΗΣ</b><span className="doctor">ΙΑΤΡΟΣ</span><span className="nurse">ΝΟΣΗΛΕΥΤΗΣ / ΝΟΣΟΚΟΜΟΣ</span><span className="staff">ΠΡΟΣΩΠΙΚΟ</span><span>ΚΑΝΟΝΙΚΟΣ ΠΕΛΑΤΗΣ</span></div></div>}</main>
 </section></div>;
}
