import React,{useEffect,useState} from "react";
import {FlaskConical,Plus,Save,Trash2} from "lucide-react";
import "./recipe-management.css";

const money=value=>Number(value||0).toLocaleString("el-GR",{style:"currency",currency:"EUR"});
const blank=()=>({ingredientProductId:"",quantity:1,unit:"PIECE"});

export default function RecipeManagementPanel({api,products=[]}){
  const [recipes,setRecipes]=useState([]),[productId,setProductId]=useState(""),[yieldQuantity,setYieldQuantity]=useState(1),[items,setItems]=useState([blank()]),[error,setError]=useState(""),[message,setMessage]=useState(""),[busy,setBusy]=useState(false);
  const load=async()=>setRecipes(await api("/api/commerce/recipes"));useEffect(()=>{load().catch(e=>setError(e.message))},[]);
  const choose=id=>{setProductId(id);const recipe=recipes.find(row=>row.productId===id);setYieldQuantity(Number(recipe?.yieldQuantity||1));setItems(recipe?.items?.length?recipe.items.map(item=>({ingredientProductId:item.ingredientProductId,quantity:Number(item.quantity),unit:item.unit||"PIECE"})):[blank()]);setError("");setMessage("")};
  const change=(index,key,value)=>setItems(rows=>rows.map((row,i)=>i===index?{...row,[key]:value}:row));
  const save=async()=>{if(!productId)return setError("Επίλεξε το τελικό προϊόν.");if(items.some(item=>!item.ingredientProductId))return setError("Επίλεξε προϊόν σε κάθε συστατικό.");setBusy(true);setError("");try{await api(`/api/commerce/recipes/${productId}`,{method:"PUT",body:JSON.stringify({yieldQuantity:Number(yieldQuantity),active:true,items:items.map(item=>({...item,quantity:Number(item.quantity)}))})});setMessage("Η συνταγή αποθηκεύτηκε. Οι επόμενες πωλήσεις θα αναλώνουν τα συστατικά.");await load()}catch(e){setError(e.message)}finally{setBusy(false)}};
  const selectedRecipe=recipes.find(row=>row.productId===productId);const estimated=items.reduce((sum,item)=>sum+Number(item.quantity||0)*Number(products.find(p=>p.id===item.ingredientProductId)?.costPrice||0),0)/Number(yieldQuantity||1);
  return <section className="recipe-manager commerce-box"><div className="recipe-head"><div><h3><FlaskConical/>Συνταγές / BOM</h3><p>Ορισμός πρώτων υλών και αυτόματη ανάλωση ανά πώληση.</p></div><select value={productId} onChange={e=>choose(e.target.value)}><option value="">Τελικό προϊόν</option>{products.map(row=><option key={row.id} value={row.id}>{row.name}{recipes.some(r=>r.productId===row.id)?" · ΕΧΕΙ ΣΥΝΤΑΓΗ":""}</option>)}</select></div>{error&&<div className="commerce-error">{error}</div>}{message&&<div className="commerce-success">{message}</div>}{productId&&<><div className="recipe-yield"><label>Απόδοση συνταγής<input type="number" min="0.001" step="0.001" value={yieldQuantity} onChange={e=>setYieldQuantity(e.target.value)}/></label><article><span>Εκτιμώμενο κόστος ανά τελικό προϊόν</span><b>{money(estimated)}</b>{selectedRecipe&&<small>Αποθηκευμένο: {money(selectedRecipe.recipeCost)}</small>}</article></div><div className="recipe-items">{items.map((item,index)=><div className="recipe-item" key={index}><label>Συστατικό<select value={item.ingredientProductId} onChange={e=>change(index,"ingredientProductId",e.target.value)}><option value="">Επιλογή</option>{products.filter(p=>p.id!==productId).map(row=><option key={row.id} value={row.id}>{row.name} · {money(row.costPrice)}</option>)}</select></label><label>Ποσότητα για την απόδοση<input type="number" min="0.001" step="0.001" value={item.quantity} onChange={e=>change(index,"quantity",e.target.value)}/></label><label>Μονάδα<select value={item.unit} onChange={e=>change(index,"unit",e.target.value)}><option value="PIECE">Τεμάχιο / βασική μονάδα</option><option value="GRAM">Γραμμάρια</option><option value="ML">ml</option></select></label><button onClick={()=>setItems(rows=>rows.filter((_,i)=>i!==index))} disabled={items.length===1}><Trash2/></button></div>)}</div><button className="recipe-add" onClick={()=>setItems(rows=>[...rows,blank()])}><Plus/>Προσθήκη συστατικού</button><div className="commerce-notice">Με την ολοκλήρωση μη φορολογικής πώλησης, η αποθήκη αφαιρεί αυτόματα: ποσότητα πώλησης × ποσότητα συστατικού ÷ απόδοση συνταγής. Κάθε κίνηση γράφεται ως <b>RECIPE_SALE</b>.</div><button className="commerce-primary recipe-save" disabled={busy} onClick={save}><Save/>{busy?"Αποθήκευση…":"Αποθήκευση συνταγής"}</button></>}</section>;
}
