import React,{useEffect,useMemo,useState} from "react";
import {RefreshCw,Search,Utensils} from "lucide-react";
import "./online-orders-backoffice.css";

const money=value=>Number(value||0).toLocaleString("el-GR",{style:"currency",currency:"EUR"});
const stamp=value=>value?new Date(value).toLocaleString("el-GR",{dateStyle:"short",timeStyle:"short"}):"—";
const statusLabel={OPEN:"ΑΝΟΙΚΤΗ",SENT:"ΣΤΑΛΘΗΚΕ",READY:"ΕΤΟΙΜΗ",PAID:"ΠΛΗΡΩΘΗΚΕ",CANCELLED:"ΑΚΥΡΩΘΗΚΕ"};

export default function TableServiceBackofficePanel({api,stores=[]}){
  const [storeId,setStoreId]=useState(stores[0]?.id||""),[rows,setRows]=useState([]),[waste,setWaste]=useState([]),[queue,setQueue]=useState([]),[query,setQuery]=useState(""),[status,setStatus]=useState("ALL"),[loading,setLoading]=useState(false),[error,setError]=useState("");
  useEffect(()=>{if(!storeId&&stores[0])setStoreId(stores[0].id)},[stores]);
  const load=async()=>{if(!storeId)return;setLoading(true);setError("");try{const [result,preparation]=await Promise.all([api(`/api/store-pos/stores/${encodeURIComponent(storeId)}/table-service/history`),api(`/api/store-pos/stores/${encodeURIComponent(storeId)}/table-service/preparation-queue`)]);setRows(result.orders||[]);setWaste(result.waste||[]);setQueue(preparation.rows||[])}catch(err){setRows([]);setWaste([]);setQueue([]);setError(err.message)}finally{setLoading(false)}};
  useEffect(()=>{load();const timer=setInterval(()=>load(),10000);return()=>clearInterval(timer)},[storeId]);
  const ready=async batch=>{setLoading(true);setError("");try{await api(`/api/store-pos/stores/${encodeURIComponent(storeId)}/table-service/preparation-queue/${encodeURIComponent(batch.id)}/ready`,{method:"PATCH",body:"{}"});await load()}catch(err){setError(err.message);setLoading(false)}};
  const filtered=useMemo(()=>rows.filter(row=>(status==="ALL"||row.status===status)&&(!query.trim()||[row.tableName,row.operatorName,row.saleId,row.receiptNumber,...(row.items||[]).map(item=>item.name)].some(value=>String(value||"").toLocaleLowerCase("el-GR").includes(query.trim().toLocaleLowerCase("el-GR"))))),[rows,status,query]);
  return <section className="online-orders-backoffice"><header className="online-bo-head"><div><span className="online-bo-kicker">MYWORKSTATION BACKOFFICE · TABLE_SERVICE</span><h2>Τραπέζια και σερβιτόροι</h2><p>Παραγγελίες, παρασκευή, πληρωμές, φύρα χωρίς απόδειξη και πλήρες ιστορικό ανά τραπέζι και χειριστή.</p></div><button onClick={load} disabled={loading}><RefreshCw/>{loading?"Ανανέωση…":"Ανανέωση"}</button></header>
    <div className="online-bo-counters"><article><span>Παραγγελίες</span><strong>{rows.length}</strong></article><article><span>Σε παρασκευή</span><strong>{queue.filter(row=>row.status==="SENT").length}</strong></article><article><span>Πληρωμένες</span><strong>{rows.filter(row=>row.status==="PAID").length}</strong></article><article><span>Φύρα τραπεζιών</span><strong>{waste.length}</strong></article></div>
    <div className="online-bo-toolbar"><label>Κατάστημα<select value={storeId} onChange={event=>setStoreId(event.target.value)}>{stores.map(store=><option key={store.id} value={store.id}>{store.name}</option>)}</select></label><label>Κατάσταση<select value={status} onChange={event=>setStatus(event.target.value)}><option value="ALL">Όλες</option>{Object.entries(statusLabel).map(([key,label])=><option key={key} value={key}>{label}</option>)}</select></label><label className="online-bo-search"><Search/><input value={query} onChange={event=>setQuery(event.target.value)} placeholder="Τραπέζι, σερβιτόρος, είδος, πώληση…"/></label></div>
    {error&&<div className="online-bo-error">{error}</div>}{queue.length>0&&<><h3>Ουρά παρασκευής</h3><div className="online-bo-list">{queue.map(batch=><article className="online-bo-order open" key={batch.id}><div className="online-bo-order-main"><div><span>Θέση</span><b>{batch.productionStation}</b><small>{stamp(batch.createdAt)}</small></div><div><span>Τραπέζι</span><b>{batch.tableName}</b><small>{batch.terminalPos||"MAIN"}</small></div><div><span>Σερβιτόρος</span><b>{batch.operatorName||"—"}</b><small>{batch.operatorId}</small></div><div><span>Κατάσταση</span><b>{batch.status==="READY"?"ΕΤΟΙΜΗ":"ΣΕ ΠΑΡΑΣΚΕΥΗ"}</b>{batch.status==="SENT"&&<button onClick={()=>ready(batch)} disabled={loading}>ΕΤΟΙΜΗ</button>}</div></div><div className="online-bo-detail"><b>{(batch.items||[]).map(item=>`${item.quantity}× ${item.name||item.productId}${(item.modifiers||[]).length?` (${item.modifiers.map(modifier=>modifier.description).filter(Boolean).join(", ")})`:""}`).join(" | ")}</b><small>{batch.note}</small></div></article>)}</div></>}
    <h3>Ιστορικό τραπεζιών</h3><div className="online-bo-list">{filtered.map(order=><article className="online-bo-order open" key={order.id}><div className="online-bo-order-main"><div className="online-bo-number"><b><Utensils size={18}/> {order.tableName}</b><small>{stamp(order.createdAt)}</small></div><div><span>Σερβιτόρος</span><b>{order.operatorName||"—"}</b><small>{order.terminalPos||"MAIN"} · {order.operatorId}</small></div><div><span>Κατάσταση</span><b>{statusLabel[order.status]||order.status}</b><small>{order.saleId?`Πώληση ${order.saleId}`:"Χωρίς πώληση"}</small></div><div><span>Σύνολο</span><b>{money(order.total)}</b><small>{order.receiptNumber?`Απόδειξη ${order.receiptNumber}`:order.status==="CANCELLED"?"Ακύρωση / φύρα":"Σε εξέλιξη"}</small></div></div><div className="online-bo-detail"><b>{(order.items||[]).map(item=>`${item.quantity}× ${item.name} · ${money(item.lineTotal)}`).join(" | ")||"Χωρίς υπόλοιπα είδη"}</b></div></article>)}</div>
  </section>;
}
