import React,{useEffect,useMemo,useRef,useState} from "react";
import {Pencil,Plus,RefreshCw,Save,Search,Utensils,X} from "lucide-react";
import "./online-orders-backoffice.css";
import "./table-service-floor-plan.css";
import {matchesGreekSearch} from "../../utils/greek-search.js";

const money=value=>Number(value||0).toLocaleString("el-GR",{style:"currency",currency:"EUR"});
const stamp=value=>value?new Date(value).toLocaleString("el-GR",{dateStyle:"short",timeStyle:"short"}):"—";
const statusLabel={OPEN:"ΑΝΟΙΚΤΗ",SENT:"ΣΤΑΛΘΗΚΕ",READY:"ΕΤΟΙΜΗ",PAID:"ΠΛΗΡΩΘΗΚΕ",CANCELLED:"ΑΚΥΡΩΘΗΚΕ"};
const shapeLabel={SQUARE:"Τετράγωνο",ROUND:"Στρογγυλό",RECTANGLE:"Ορθογώνιο"};
const blankTable=()=>({name:"",areaId:"",capacity:4,shape:"SQUARE"});

export default function TableServiceBackofficePanel({api,stores=[],activeStoreId=""}){
  const [storeId,setStoreId]=useState(stores[0]?.id||""),[rows,setRows]=useState([]),[waste,setWaste]=useState([]),[queue,setQueue]=useState([]),[station,setStation]=useState("ALL"),[config,setConfig]=useState({areas:[],tables:[],canConfigure:false}),[query,setQuery]=useState(""),[status,setStatus]=useState("ALL"),[loading,setLoading]=useState(false),[saving,setSaving]=useState(false),[error,setError]=useState(""),[message,setMessage]=useState(""),[areaName,setAreaName]=useState(""),[tableDraft,setTableDraft]=useState(blankTable),[editingId,setEditingId]=useState(""),[floorArea,setFloorArea]=useState(""),[drag,setDrag]=useState(null);
  const floorRef=useRef(null);
  useEffect(()=>{const preferred=stores.find(store=>store.id===activeStoreId)?.id||stores[0]?.id||"";if(preferred&&storeId!==preferred)setStoreId(preferred)},[stores,storeId,activeStoreId]);
  const load=async()=>{if(!storeId)return;setLoading(true);setError("");try{const [result,preparation,configuration]=await Promise.all([api(`/api/store-pos/stores/${encodeURIComponent(storeId)}/table-service/history`),api(`/api/store-pos/stores/${encodeURIComponent(storeId)}/table-service/preparation-queue`),api(`/api/store-pos/stores/${encodeURIComponent(storeId)}/table-service`)]);setRows(result.orders||[]);setWaste(result.waste||[]);setQueue(preparation.rows||[]);setConfig({areas:configuration.areas||[],tables:configuration.tables||[],canConfigure:Boolean(configuration.canConfigure)})}catch(err){setRows([]);setWaste([]);setQueue([]);setConfig({areas:[],tables:[],canConfigure:false});setError(err.message)}finally{setLoading(false)}};
  useEffect(()=>{setEditingId("");setTableDraft(blankTable());setAreaName("");setMessage("");setStation("ALL");load();const timer=setInterval(()=>load(),10000);return()=>clearInterval(timer)},[storeId]);
  const mutate=async(path,options,success)=>{setSaving(true);setError("");setMessage("");try{await api(path,options);setMessage(success);await load();return true}catch(err){setError(err.message);return false}finally{setSaving(false)}};
  const addArea=async event=>{event.preventDefault();const name=areaName.trim();if(!name)return setError("Συμπλήρωσε το όνομα της σάλας.");if(await mutate(`/api/store-pos/stores/${encodeURIComponent(storeId)}/table-service/areas`,{method:"POST",body:JSON.stringify({name})},`Η σάλα «${name}» δημιουργήθηκε και καταγράφηκε στο Audit.`))setAreaName("")};
  const saveTable=async event=>{event.preventDefault();const payload={name:tableDraft.name.trim(),areaId:tableDraft.areaId||null,capacity:Number(tableDraft.capacity),shape:tableDraft.shape,...(editingId?{positionX:tableDraft.positionX||0,positionY:tableDraft.positionY||0,sortOrder:tableDraft.sortOrder||0}:{})};if(!payload.name)return setError("Συμπλήρωσε το όνομα του τραπεζιού.");const path=editingId?`/api/store-pos/stores/${encodeURIComponent(storeId)}/tables/${encodeURIComponent(editingId)}`:`/api/store-pos/stores/${encodeURIComponent(storeId)}/tables`;const ok=await mutate(path,{method:editingId?"PATCH":"POST",body:JSON.stringify(payload)},`Το τραπέζι «${payload.name}» ${editingId?"ενημερώθηκε":"δημιουργήθηκε"} και καταγράφηκε στο Audit.`);if(ok){setEditingId("");setTableDraft(blankTable())}};
  const editTable=table=>{setEditingId(table.id);setTableDraft({name:table.name,areaId:table.areaId||"",capacity:table.capacity||4,shape:table.shape||"SQUARE",positionX:table.positionX||0,positionY:table.positionY||0,sortOrder:table.sortOrder||0});setMessage("")};
  const floorTables=config.tables.filter(table=>(table.areaId||"")===floorArea);
  const floorPosition=event=>{const box=floorRef.current?.getBoundingClientRect();if(!box)return null;return {positionX:Math.max(0,Math.min(100,Math.round((event.clientX-box.left)/box.width*100))),positionY:Math.max(0,Math.min(100,Math.round((event.clientY-box.top)/box.height*100)))};};
  const beginDrag=(event,table)=>{if(saving)return;event.preventDefault();event.currentTarget.setPointerCapture(event.pointerId);setDrag({id:table.id,positionX:table.positionX||0,positionY:table.positionY||0});};
  const moveDrag=event=>{if(!drag)return;const position=floorPosition(event);if(position)setDrag({...drag,...position});};
  const endDrag=async event=>{if(!drag)return;const table=config.tables.find(row=>row.id===drag.id);const position=floorPosition(event)||drag;setDrag(null);if(!table||(Number(table.positionX)===position.positionX&&Number(table.positionY)===position.positionY))return;await mutate(`/api/store-pos/stores/${encodeURIComponent(storeId)}/tables/${encodeURIComponent(table.id)}`,{method:"PATCH",body:JSON.stringify({name:table.name,areaId:table.areaId||null,capacity:table.capacity,shape:table.shape,sortOrder:table.sortOrder||0,...position})},`Η θέση του «${table.name}» αποθηκεύτηκε στη σάλα και καταγράφηκε στο Audit.`);};
  const ready=async batch=>{setLoading(true);setError("");try{await api(`/api/store-pos/stores/${encodeURIComponent(storeId)}/table-service/preparation-queue/${encodeURIComponent(batch.id)}/ready`,{method:"PATCH",body:"{}"});await load()}catch(err){setError(err.message);setLoading(false)}};
  const filtered=useMemo(()=>rows.filter(row=>(status==="ALL"||row.status===status)&&matchesGreekSearch(query,[row.tableName,row.operatorName,row.saleId,row.receiptNumber,(row.items||[]).map(item=>item.name)])),[rows,status,query]);
  const stations=useMemo(()=>[...new Set(queue.map(batch=>String(batch.productionStation||"ΠΑΡΑΓΩΓΗ").trim()||"ΠΑΡΑΓΩΓΗ"))].sort((a,b)=>a.localeCompare(b,"el")),[queue]);
  const visibleQueue=useMemo(()=>station==="ALL"?queue:queue.filter(batch=>(batch.productionStation||"ΠΑΡΑΓΩΓΗ")===station),[queue,station]);
  const areaById=useMemo(()=>new Map(config.areas.map(area=>[area.id,area.name])),[config.areas]);
  return <section className="online-orders-backoffice"><header className="online-bo-head"><div><span className="online-bo-kicker">MYWORKSTATION BACKOFFICE · TABLE_SERVICE</span><h2>Τραπέζια και σερβιτόροι</h2><p>Κοινή διαχείριση για Owner και Super Admin. Παραγγελίες, παρασκευή, πληρωμές, φύρα χωρίς απόδειξη και πλήρες ιστορικό.</p></div><button onClick={load} disabled={loading}><RefreshCw/>{loading?"Ανανέωση…":"Ανανέωση"}</button></header>
    <div className="online-bo-toolbar"><label>Κατάστημα<select value={storeId} onChange={event=>setStoreId(event.target.value)}>{stores.map(store=><option key={store.id} value={store.id}>{store.name}</option>)}</select></label><label>Κατάσταση<select value={status} onChange={event=>setStatus(event.target.value)}><option value="ALL">Όλες</option>{Object.entries(statusLabel).map(([key,label])=><option key={key} value={key}>{label}</option>)}</select></label><label className="online-bo-search"><Search/><input value={query} onChange={event=>setQuery(event.target.value)} placeholder="Τραπέζι, σερβιτόρος, είδος, πώληση…"/></label></div>
    {config.canConfigure&&<section className="table-config-panel"><div className="table-config-title"><div><span>ΡΥΘΜΙΣΗ ΚΑΤΑΣΤΗΜΑΤΟΣ</span><h3>Σάλες και τραπέζια</h3><p>Οι αλλαγές ισχύουν αμέσως στο POS του επιλεγμένου καταστήματος και καταγράφονται στο Audit.</p></div><b>{config.areas.length} σάλες · {config.tables.length} τραπέζια</b></div>
      <div className="table-floor-section"><div className="table-floor-head"><h4>Κάτοψη τραπεζιών</h4><label>Σάλα<select value={floorArea} onChange={event=>{setFloorArea(event.target.value);setDrag(null)}}><option value="">Χωρίς σάλα</option>{config.areas.map(area=><option key={area.id} value={area.id}>{area.name}</option>)}</select></label></div><p>Σύρε ένα τραπέζι στη θέση του. Η θέση αποθηκεύεται όταν το αφήσεις.</p><div ref={floorRef} className="table-floor-canvas" aria-label={`Κάτοψη ${areaById.get(floorArea)||"χωρίς σάλα"}`}>{floorTables.map((table,index)=>{const unplaced=Number(table.positionX)===0&&Number(table.positionY)===0;const position=drag?.id===table.id?drag:unplaced?{positionX:18+(index%4)*21,positionY:20+Math.floor(index/4)*22}:table;return <button key={table.id} type="button" className={`table-floor-item ${table.shape||"SQUARE"}`} style={{left:`${Math.min(90,Math.max(10,Number(position.positionX)||10))}%`,top:`${Math.min(88,Math.max(12,Number(position.positionY)||12))}%`}} onPointerDown={event=>beginDrag(event,table)} onPointerMove={moveDrag} onPointerUp={endDrag} onPointerCancel={()=>setDrag(null)} disabled={saving} title={`${table.name} · ${table.capacity} θέσεις`}><b>{table.name}</b><small>{table.capacity} θέσεις</small></button>})}{!floorTables.length&&<span className="table-floor-empty">Δεν υπάρχουν τραπέζια σε αυτή τη σάλα.</span>}</div></div>
      <div className="table-config-forms"><form onSubmit={addArea}><h4><Plus/> Νέα σάλα</h4><label>Ονομασία<input value={areaName} onChange={event=>setAreaName(event.target.value)} maxLength="50" placeholder="π.χ. Κεντρική σάλα"/></label><button disabled={saving||!areaName.trim()}><Plus/>ΔΗΜΙΟΥΡΓΙΑ ΣΑΛΑΣ</button></form><form onSubmit={saveTable}><h4>{editingId?<><Pencil/> Επεξεργασία τραπεζιού</>:<><Plus/> Νέο τραπέζι</>}</h4><div className="table-config-fields"><label>Ονομασία<input value={tableDraft.name} onChange={event=>setTableDraft({...tableDraft,name:event.target.value})} maxLength="50" placeholder="π.χ. Τραπέζι 1"/></label><label>Σάλα<select value={tableDraft.areaId} onChange={event=>setTableDraft({...tableDraft,areaId:event.target.value})}><option value="">Χωρίς σάλα</option>{config.areas.map(area=><option key={area.id} value={area.id}>{area.name}</option>)}</select></label><label>Θέσεις<input type="number" min="1" max="100" value={tableDraft.capacity} onChange={event=>setTableDraft({...tableDraft,capacity:event.target.value})}/></label><label>Σχήμα<select value={tableDraft.shape} onChange={event=>setTableDraft({...tableDraft,shape:event.target.value})}>{Object.entries(shapeLabel).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label></div><div className="table-config-actions"><button disabled={saving||!tableDraft.name.trim()}><Save/>{editingId?"ΑΠΟΘΗΚΕΥΣΗ ΑΛΛΑΓΩΝ":"ΔΗΜΙΟΥΡΓΙΑ ΤΡΑΠΕΖΙΟΥ"}</button>{editingId&&<button type="button" className="secondary" onClick={()=>{setEditingId("");setTableDraft(blankTable())}}><X/>ΑΚΥΡΩΣΗ</button>}</div></form></div>
      <div className="table-config-list">{config.tables.length?config.tables.map(table=><article key={table.id}><Utensils/><div><b>{table.name}</b><span>{areaById.get(table.areaId)||"Χωρίς σάλα"} · {table.capacity} θέσεις · {shapeLabel[table.shape]||table.shape}</span></div><button type="button" onClick={()=>editTable(table)} disabled={saving}><Pencil/>ΕΠΕΞΕΡΓΑΣΙΑ</button></article>):<p>Δεν υπάρχουν ακόμα τραπέζια. Δημιούργησε πρώτα μία σάλα και μετά τα τραπέζια της.</p>}</div>
    </section>}
    {message&&<div className="table-config-message">{message}</div>}{error&&<div className="online-bo-error">{error}</div>}
    <div className="online-bo-counters"><article><span>Παραγγελίες</span><strong>{rows.length}</strong></article><article><span>Σε παρασκευή</span><strong>{queue.filter(row=>row.status==="SENT").length}</strong></article><article><span>Πληρωμένες</span><strong>{rows.filter(row=>row.status==="PAID").length}</strong></article><article><span>Φύρα τραπεζιών</span><strong>{waste.length}</strong></article></div>
    {queue.length>0&&<><h3>Ξεχωριστές ουρές παραγωγής</h3><div className="table-station-tabs" role="tablist" aria-label="Επιλογή πόστου παραγωγής"><button type="button" className={station==="ALL"?"active":""} onClick={()=>setStation("ALL")}>ΟΛΑ ΤΑ ΠΟΣΤΑ <b>{queue.filter(row=>row.status==="SENT").length}</b></button>{stations.map(name=><button type="button" key={name} className={station===name?"active":""} onClick={()=>setStation(name)}>{name} <b>{queue.filter(row=>row.productionStation===name&&row.status==="SENT").length}</b></button>)}</div><div className="online-bo-list">{visibleQueue.map(batch=><article className="online-bo-order open" data-production-station={batch.productionStation||"ΠΑΡΑΓΩΓΗ"} key={batch.id}><div className="online-bo-order-main"><div><span>Πόστο παραγωγής</span><b>{batch.productionStation||"ΠΑΡΑΓΩΓΗ"}</b><small>{stamp(batch.createdAt)}</small></div><div><span>Τραπέζι</span><b>{batch.tableName}</b><small>{batch.terminalPos||"MAIN"}</small></div><div><span>Σερβιτόρος</span><b>{batch.operatorName||"—"}</b><small>{batch.operatorId}</small></div><div><span>Κατάσταση πόστου</span><b>{batch.status==="READY"?"ΕΤΟΙΜΗ":"ΣΕ ΠΑΡΑΣΚΕΥΗ"}</b>{batch.status==="SENT"&&<button onClick={()=>ready(batch)} disabled={loading}>ΕΤΟΙΜΗ ΣΤΟ {batch.productionStation||"ΠΟΣΤΟ"}</button>}</div></div><div className="online-bo-detail"><b>{(batch.items||[]).map(item=>`${item.quantity}× ${item.name||item.productId}${(item.modifiers||[]).length?` (${item.modifiers.map(modifier=>modifier.description).filter(Boolean).join(", ")})`:""}${item.notes?` · ${item.notes}`:""}`).join(" | ")}</b>{(batch.items||[]).some(item=>(item.allergens||[]).length>0)&&<strong className="table-allergen-alert">ΑΛΛΕΡΓΙΟΓΟΝΑ: {(batch.items||[]).flatMap(item=>item.allergens||[]).filter((value,index,rows)=>rows.indexOf(value)===index).join(", ")}</strong>}<small>{batch.note}</small></div></article>)}</div></>}
    <h3>Ιστορικό τραπεζιών</h3><div className="online-bo-list">{filtered.map(order=><article className="online-bo-order open" key={order.id}><div className="online-bo-order-main"><div className="online-bo-number"><b><Utensils size={18}/> {order.tableName}</b><small>{stamp(order.createdAt)}</small></div><div><span>Σερβιτόρος</span><b>{order.operatorName||"—"}</b><small>{order.terminalPos||"MAIN"} · {order.operatorId}</small></div><div><span>Κατάσταση</span><b>{statusLabel[order.status]||order.status}</b><small>{order.saleId?`Πώληση ${order.saleId}`:"Χωρίς πώληση"}</small></div><div><span>Σύνολο</span><b>{money(order.total)}</b><small>{order.receiptNumber?`Απόδειξη ${order.receiptNumber}`:order.status==="CANCELLED"?"Ακύρωση / φύρα":"Σε εξέλιξη"}</small></div></div><div className="online-bo-detail"><b>{(order.items||[]).map(item=>`${item.quantity}× ${item.name} · ${money(item.lineTotal)}`).join(" | ")||"Χωρίς υπόλοιπα είδη"}</b></div></article>)}</div>
  </section>;
}
