import React,{useEffect,useState} from "react";

export default function WholesaleB2BPanel({api}){
  const [tab,setTab]=useState("customers"),[customers,setCustomers]=useState([]),[lists,setLists]=useState([]),[error,setError]=useState("");
  const load=async()=>{try{setError("");const [c,p]=await Promise.all([api("/api/wholesale/customers"),api("/api/wholesale/price-lists")]);setCustomers(c.items||[]);setLists(p.items||[])}catch(e){setError(e.message)}};
  useEffect(()=>{load()},[]);
  const addCustomer=async e=>{e.preventDefault();const f=new FormData(e.currentTarget);try{await api("/api/wholesale/customers",{method:"POST",body:JSON.stringify({name:f.get("name"),code:f.get("code")||null,taxId:f.get("taxId")||null,creditLimit:Number(f.get("creditLimit")||0),paymentTermsDays:Number(f.get("paymentTermsDays")||0),active:true})});e.currentTarget.reset();await load()}catch(x){setError(x.message)}};
  const addList=async e=>{e.preventDefault();const f=new FormData(e.currentTarget);try{await api("/api/wholesale/price-lists",{method:"POST",body:JSON.stringify({code:f.get("code"),name:f.get("name"),discountPercent:Number(f.get("discountPercent")||0),active:true})});e.currentTarget.reset();await load()}catch(x){setError(x.message)}};
  return <section className="wholesale-b2b-panel">
    <div className="wholesale-head"><div><h2>Χονδρική / B2B</h2><p>Πελάτες χονδρικής και ειδικοί τιμοκατάλογοι, χωρίς αλλαγή στις τιμές λιανικής.</p></div></div>
    <div className="wholesale-tabs"><button className={tab==="customers"?"active":""} onClick={()=>setTab("customers")}>Πελάτες</button><button className={tab==="prices"?"active":""} onClick={()=>setTab("prices")}>Τιμοκατάλογοι</button></div>
    {error&&<div className="wholesale-error">{error}</div>}
    {tab==="customers"?<><form className="wholesale-form" onSubmit={addCustomer}><input name="code" placeholder="Κωδικός πελάτη"/><input name="name" placeholder="Επωνυμία" required/><input name="taxId" placeholder="ΑΦΜ"/><input name="creditLimit" type="number" min="0" step="0.01" placeholder="Πιστωτικό όριο €"/><input name="paymentTermsDays" type="number" min="0" placeholder="Ημέρες πίστωσης"/><button>Νέος πελάτης</button></form><div className="wholesale-table"><div className="wholesale-row wholesale-th"><span>Κωδικός</span><span>Επωνυμία</span><span>ΑΦΜ</span><span>Όριο</span><span>Πίστωση</span></div>{customers.map(row=><div className="wholesale-row" key={row.id}><span>{row.code||"—"}</span><span><b>{row.name}</b></span><span>{row.taxId||"—"}</span><span>{Number(row.creditLimit||0).toLocaleString("el-GR",{style:"currency",currency:"EUR"})}</span><span>{row.paymentTermsDays||0} ημέρες</span></div>)}</div></>:<><form className="wholesale-form wholesale-list-form" onSubmit={addList}><input name="code" placeholder="Κωδικός π.χ. B2B-A" required/><input name="name" placeholder="Όνομα τιμοκαταλόγου" required/><input name="discountPercent" type="number" min="0" max="100" step="0.01" placeholder="Βασική έκπτωση %"/><button>Νέος τιμοκατάλογος</button></form><div className="wholesale-table"><div className="wholesale-row wholesale-list-row wholesale-th"><span>Κωδικός</span><span>Τιμοκατάλογος</span><span>Βασική έκπτωση</span></div>{lists.map(row=><div className="wholesale-row wholesale-list-row" key={row.id}><span>{row.code}</span><span><b>{row.name}</b></span><span>{Number(row.discountPercent||0).toLocaleString("el-GR")}%</span></div>)}</div></>}
  </section>;
}
