import {Router} from "express";
import {z} from "zod";
import crypto from "crypto";
import jwt from "jsonwebtoken";
import {prisma} from "../prisma.js";

const router=Router(),publicRouter=Router();
const id=()=>crypto.randomUUID(),n=value=>Number(value||0),hash=value=>crypto.createHash("sha256").update(String(value)).digest("hex");
const roles=new Set(["SUPER_ADMIN","OWNER","ADMIN","MANAGER"]);
const owner=(req,res,next)=>roles.has(req.user?.role)||req.user?.isSuperAdmin?next():res.status(403).json({error:"Η διαχείριση Inventory 2.0 απαιτεί δικαίωμα ιδιοκτήτη ή διαχειριστή."});
const stocktakeAccess=async(req,stocktakeId)=>{const companyId=req.user.companyId,scoped=req.user.tokenType==="INVENTORY_COUNTER"?req.user.stocktakeId:null;if(scoped&&scoped!==stocktakeId)return null;const rows=await prisma.$queryRaw`SELECT st."id",st."companyId",st."storeId",st."name",st."status",st."scopeType",st."scopeJson",st."liveDuringTrading",st."recountPolicy",st."startedAt",st."finalizedAt",s."name" AS "storeName" FROM "Stocktake" st JOIN "Store" s ON s."id"=st."storeId" WHERE st."id"=${stocktakeId} AND st."companyId"=${companyId} LIMIT 1`;return rows[0]||null};

router.get("/zones",owner,async(req,res,next)=>{try{const storeId=String(req.query.storeId||"");const rows=await prisma.$queryRaw`SELECT "id","storeId","code","name","active","createdAt" FROM "InventoryZone" WHERE "companyId"=${req.user.companyId} AND (${storeId}='' OR "storeId"=${storeId}) ORDER BY "storeId","name"`;res.json(rows)}catch(e){next(e)}});
router.post("/zones",owner,async(req,res,next)=>{try{const b=z.object({storeId:z.string().min(1),code:z.string().trim().min(1).max(30).transform(v=>v.toUpperCase()),name:z.string().trim().min(1).max(100)}).parse(req.body||{});const store=await prisma.store.findFirst({where:{id:b.storeId,companyId:req.user.companyId,active:true},select:{id:true}});if(!store)return res.status(404).json({error:"Δεν βρέθηκε το κατάστημα."});const zoneId=id();await prisma.$executeRaw`INSERT INTO "InventoryZone" ("id","companyId","storeId","code","name","createdByUserId") VALUES (${zoneId},${req.user.companyId},${b.storeId},${b.code},${b.name},${req.user.id})`;res.status(201).json({id:zoneId,...b})}catch(e){if(e?.code==="P2010")e.status=409;next(e)}});

router.get("/stocktakes",owner,async(req,res,next)=>{try{const rows=await prisma.$queryRaw`SELECT st."id",st."name",st."status",st."scopeType",st."liveDuringTrading",st."startedAt",st."finalizedAt",s."name" AS "storeName",COUNT(sl."id")::int AS "lineCount",COUNT(sl."id") FILTER (WHERE sl."countedQuantity" IS NOT NULL)::int AS "countedCount" FROM "Stocktake" st JOIN "Store" s ON s."id"=st."storeId" LEFT JOIN "StocktakeLine" sl ON sl."stocktakeId"=st."id" WHERE st."companyId"=${req.user.companyId} AND st."inventoryVersion"=2 GROUP BY st."id",s."name" ORDER BY st."startedAt" DESC LIMIT 200`;res.json(rows)}catch(e){next(e)}});

router.post("/stocktakes",owner,async(req,res,next)=>{try{const b=z.object({storeId:z.string().min(1),name:z.string().trim().min(1).max(180),scopeType:z.enum(["FULL","PARTIAL_PRODUCTS","PARTIAL_CATEGORIES"]).default("FULL"),productIds:z.array(z.string()).max(5000).optional().default([]),categoryIds:z.array(z.string()).max(500).optional().default([]),liveDuringTrading:z.boolean().optional().default(false),recountPolicy:z.enum(["NONE","DIFFERENCES","ALL"]).default("DIFFERENCES"),zoneIds:z.array(z.string()).max(100).optional().default([])}).parse(req.body||{});if(b.scopeType==="PARTIAL_PRODUCTS"&&!b.productIds.length)return res.status(400).json({error:"Επίλεξε τουλάχιστον ένα προϊόν για τη μερική απογραφή."});if(b.scopeType==="PARTIAL_CATEGORIES"&&!b.categoryIds.length)return res.status(400).json({error:"Επίλεξε τουλάχιστον μία κατηγορία για τη μερική απογραφή."});const store=await prisma.store.findFirst({where:{id:b.storeId,companyId:req.user.companyId,active:true},select:{id:true}});if(!store)return res.status(404).json({error:"Δεν βρέθηκε το κατάστημα."});const stocktakeId=id(),scopeJson=JSON.stringify({productIds:b.productIds,categoryIds:b.categoryIds});await prisma.$transaction(async tx=>{await tx.$executeRaw`INSERT INTO "Stocktake" ("id","companyId","storeId","name","inventoryVersion","scopeType","scopeJson","liveDuringTrading","recountPolicy","createdByUserId") VALUES (${stocktakeId},${req.user.companyId},${b.storeId},${b.name},2,${b.scopeType},${scopeJson}::jsonb,${b.liveDuringTrading},${b.recountPolicy},${req.user.id})`;const products=await tx.$queryRaw`SELECT p."id",sp."currentStock",p."costPrice" FROM "StoreProduct" sp JOIN "Product" p ON p."id"=sp."productId" WHERE sp."storeId"=${b.storeId} AND sp."active"=true AND p."companyId"=${req.user.companyId} AND p."active"=true AND (${b.scopeType}='FULL' OR (${b.scopeType}='PARTIAL_PRODUCTS' AND p."id"=ANY(${b.productIds}::text[])) OR (${b.scopeType}='PARTIAL_CATEGORIES' AND p."categoryId"=ANY(${b.categoryIds}::text[]))) ORDER BY p."name"`;for(let index=0;index<products.length;index++){const row=products[index],zoneId=b.zoneIds.length?b.zoneIds[index%b.zoneIds.length]:null;await tx.$executeRaw`INSERT INTO "StocktakeLine" ("id","stocktakeId","productId","expectedQuantity","unitCost","zoneId") VALUES (${id()},${stocktakeId},${row.id},${n(row.currentStock)},${n(row.costPrice)},${zoneId})`}});res.status(201).json({id:stocktakeId,scopeType:b.scopeType})}catch(e){next(e)}});

router.get("/stocktakes/:stocktakeId",async(req,res,next)=>{try{const st=await stocktakeAccess(req,req.params.stocktakeId);if(!st)return res.status(404).json({error:"Δεν βρέθηκε η απογραφή."});const zoneId=req.user.tokenType==="INVENTORY_COUNTER"?req.user.zoneId||null:String(req.query.zoneId||"")||null;const [lines,participants,events]=await Promise.all([prisma.$queryRaw`SELECT sl."id",sl."productId",sl."zoneId",z."name" AS "zoneName",p."name",p."sku",pb."barcode",sl."expectedQuantity",sl."countedQuantity",sl."unitCost",sl."countVersion",sl."recountRequired",sl."countedAt",COALESCE(u."fullName",'—') AS "countedBy" FROM "StocktakeLine" sl JOIN "Product" p ON p."id"=sl."productId" LEFT JOIN "InventoryZone" z ON z."id"=sl."zoneId" LEFT JOIN "User" u ON u."id"=sl."countedByUserId" LEFT JOIN LATERAL (SELECT "barcode" FROM "ProductBarcode" WHERE "productId"=p."id" ORDER BY "createdAt" LIMIT 1) pb ON true WHERE sl."stocktakeId"=${st.id} AND (${zoneId}::text IS NULL OR sl."zoneId"=${zoneId}) ORDER BY z."name",p."name"`,prisma.$queryRaw`SELECT "id","zoneId","displayName","role","active","createdAt" FROM "InventoryParticipant" WHERE "stocktakeId"=${st.id} ORDER BY "createdAt"`,prisma.$queryRaw`SELECT "id","lineId","zoneId","eventType","previousQuantity","countedQuantity","expectedQuantity","actorName","deviceId","source","createdAt" FROM "InventoryCountEvent" WHERE "stocktakeId"=${st.id} ORDER BY "createdAt" DESC LIMIT 300`]);res.json({...st,lines:lines.map(x=>({...x,expectedQuantity:n(x.expectedQuantity),countedQuantity:x.countedQuantity===null?null:n(x.countedQuantity),unitCost:n(x.unitCost),countVersion:n(x.countVersion),recountRequired:Boolean(x.recountRequired)})),participants,events:events.map(x=>({...x,previousQuantity:x.previousQuantity===null?null:n(x.previousQuantity),countedQuantity:n(x.countedQuantity),expectedQuantity:n(x.expectedQuantity)}))})}catch(e){next(e)}});

router.post("/stocktakes/:stocktakeId/count",async(req,res,next)=>{try{const st=await stocktakeAccess(req,req.params.stocktakeId);if(!st)return res.status(404).json({error:"Δεν βρέθηκε η απογραφή."});if(st.status!=="DRAFT")return res.status(409).json({error:"Η απογραφή δεν είναι ανοικτή."});const b=z.object({lineId:z.string(),quantity:z.coerce.number().min(0),expectedVersion:z.coerce.number().int().min(0),clientEventId:z.string().trim().min(1).max(100),deviceId:z.string().trim().max(120).optional().nullable(),source:z.enum(["BACKOFFICE","PWA","SCANNER","QR_PIN"]).default("BACKOFFICE")}).parse(req.body||{});const actor=req.user.fullName||req.user.displayName||"Καταμετρητής",actorId=req.user.id||req.user.grantId||null,zoneScope=req.user.tokenType==="INVENTORY_COUNTER"?req.user.zoneId||null:null;const result=await prisma.$transaction(async tx=>{const duplicate=await tx.$queryRaw`SELECT "id" FROM "InventoryCountEvent" WHERE "stocktakeId"=${st.id} AND "clientEventId"=${b.clientEventId} LIMIT 1`;if(duplicate[0])return {replayed:true};const rows=await tx.$queryRaw`SELECT "id","zoneId","expectedQuantity","countedQuantity","countVersion","recountRequired" FROM "StocktakeLine" WHERE "id"=${b.lineId} AND "stocktakeId"=${st.id} LIMIT 1 FOR UPDATE`;const line=rows[0];if(!line||zoneScope&&line.zoneId!==zoneScope)throw Object.assign(new Error("Η γραμμή δεν ανήκει στην επιτρεπόμενη ζώνη."),{status:403});if(n(line.countVersion)!==b.expectedVersion)throw Object.assign(new Error("Η γραμμή ενημερώθηκε από άλλο χρήστη. Ανανέωσε πριν ξαναγράψεις."),{status:409});const previous=line.countedQuantity===null?null:n(line.countedQuantity),expected=n(line.expectedQuantity),eventType=previous===null?"COUNT":"RECOUNT",recountRequired=st.recountPolicy==="ALL"?eventType==="COUNT":st.recountPolicy==="DIFFERENCES"?eventType==="COUNT"&&Math.abs(b.quantity-expected)>0.0001:false;await tx.$executeRaw`UPDATE "StocktakeLine" SET "countedQuantity"=${b.quantity},"countedByUserId"=${req.user.tokenType==="INVENTORY_COUNTER"?null:req.user.id||null},"countedAt"=NOW(),"countVersion"="countVersion"+1,"recountRequired"=${recountRequired},"countSource"=${b.source},"updatedAt"=NOW() WHERE "id"=${line.id}`;await tx.$executeRaw`INSERT INTO "InventoryCountEvent" ("id","companyId","storeId","stocktakeId","lineId","zoneId","eventType","previousQuantity","countedQuantity","expectedQuantity","actorId","actorName","deviceId","source","clientEventId") VALUES (${id()},${st.companyId},${st.storeId},${st.id},${line.id},${line.zoneId},${eventType},${previous},${b.quantity},${expected},${actorId},${actor},${b.deviceId||null},${b.source},${b.clientEventId})`;return {ok:true,countVersion:b.expectedVersion+1,recountRequired}});res.json(result)}catch(e){next(e)}});

router.post("/stocktakes/:stocktakeId/access-grants",owner,async(req,res,next)=>{try{const st=await stocktakeAccess(req,req.params.stocktakeId);if(!st)return res.status(404).json({error:"Δεν βρέθηκε η απογραφή."});const b=z.object({zoneId:z.string().optional().nullable(),displayName:z.string().trim().min(1).max(100),expiresMinutes:z.coerce.number().int().min(5).max(1440).default(240),maxUses:z.coerce.number().int().min(1).max(20).default(1)}).parse(req.body||{}),rawToken=crypto.randomBytes(24).toString("base64url"),pin=String(crypto.randomInt(0,1000000)).padStart(6,"0"),grantId=id(),expiresAt=new Date(Date.now()+b.expiresMinutes*60000);await prisma.$executeRaw`INSERT INTO "InventoryAccessGrant" ("id","stocktakeId","zoneId","tokenHash","pinHash","displayName","expiresAt","maxUses","createdByUserId") VALUES (${grantId},${st.id},${b.zoneId||null},${hash(rawToken)},${hash(pin)},${b.displayName},${expiresAt},${b.maxUses},${req.user.id})`;res.status(201).json({id:grantId,pin,expiresAt,accessUrl:`/inventory/${encodeURIComponent(st.id)}?grant=${encodeURIComponent(rawToken)}`})}catch(e){next(e)}});

router.post("/stocktakes/:stocktakeId/finalize",owner,async(req,res,next)=>{try{const st=await stocktakeAccess(req,req.params.stocktakeId);if(!st)return res.status(404).json({error:"Δεν βρέθηκε η απογραφή."});if(st.status!=="DRAFT")return res.status(409).json({error:"Η απογραφή έχει ήδη κλείσει."});const unresolved=await prisma.$queryRaw`SELECT COUNT(*)::int AS count FROM "StocktakeLine" WHERE "stocktakeId"=${st.id} AND ("countedQuantity" IS NULL OR "recountRequired"=true)`;if(n(unresolved[0]?.count)>0)return res.status(409).json({error:`Υπάρχουν ${n(unresolved[0].count)} γραμμές χωρίς μέτρηση ή επανακαταμέτρηση.`});await prisma.$transaction(async tx=>{const lines=await tx.$queryRaw`SELECT "productId","expectedQuantity","countedQuantity","unitCost" FROM "StocktakeLine" WHERE "stocktakeId"=${st.id} FOR UPDATE`;for(const line of lines){const diff=n(line.countedQuantity)-n(line.expectedQuantity);await tx.$executeRaw`UPDATE "StoreProduct" SET "currentStock"=${n(line.countedQuantity)},"updatedAt"=NOW() WHERE "storeId"=${st.storeId} AND "productId"=${line.productId}`;if(Math.abs(diff)>0.0001)await tx.$executeRaw`INSERT INTO "StockMovement" ("id","storeId","productId","movementType","quantity","unitCost","sourceType","sourceId","note","createdByUserId") VALUES (${id()},${st.storeId},${line.productId},'STOCKTAKE_ADJUSTMENT',${diff},${n(line.unitCost)},'INVENTORY_V2',${st.id},${st.scopeType==='FULL'?'Οριστικοποίηση πλήρους Inventory 2.0':'Οριστικοποίηση μερικής Inventory 2.0'},${req.user.id})`}const snapshot=JSON.stringify({finalizedAt:new Date().toISOString(),scopeType:st.scopeType,scope:st.scopeJson,lineCount:lines.length,totalDifference:lines.reduce((s,x)=>s+n(x.countedQuantity)-n(x.expectedQuantity),0)});await tx.$executeRaw`UPDATE "Stocktake" SET "status"='FINALIZED',"finalizedAt"=NOW(),"finalizedByUserId"=${req.user.id},"snapshotJson"=${snapshot}::jsonb,"updatedAt"=NOW() WHERE "id"=${st.id}`});res.json({ok:true,scopeType:st.scopeType})}catch(e){next(e)}});

publicRouter.post("/redeem",async(req,res,next)=>{try{const b=z.object({stocktakeId:z.string(),grantToken:z.string().min(20),pin:z.string().regex(/^\d{6}$/)}).parse(req.body||{}),tokenHash=hash(b.grantToken),pinHash=hash(b.pin);const rows=await prisma.$queryRaw`SELECT g."id",g."stocktakeId",g."zoneId",g."displayName",g."expiresAt",g."maxUses",g."usedCount",g."revokedAt",st."companyId",st."storeId",st."status" FROM "InventoryAccessGrant" g JOIN "Stocktake" st ON st."id"=g."stocktakeId" WHERE g."stocktakeId"=${b.stocktakeId} AND g."tokenHash"=${tokenHash} AND g."pinHash"=${pinHash} LIMIT 1`;const g=rows[0];if(!g||g.revokedAt||g.status!=="DRAFT"||new Date(g.expiresAt)<=new Date()||n(g.usedCount)>=n(g.maxUses))return res.status(403).json({error:"Η πρόσβαση QR/PIN δεν είναι ενεργή."});await prisma.$executeRaw`UPDATE "InventoryAccessGrant" SET "usedCount"="usedCount"+1 WHERE "id"=${g.id}`;const token=jwt.sign({tokenType:"INVENTORY_COUNTER",grantId:g.id,stocktakeId:g.stocktakeId,zoneId:g.zoneId,companyId:g.companyId,storeId:g.storeId,role:"EMPLOYEE",fullName:g.displayName,permissions:["INVENTORY_COUNT"]},process.env.JWT_SECRET,{expiresIn:"8h"});res.json({token,stocktakeId:g.stocktakeId,zoneId:g.zoneId,displayName:g.displayName})}catch(e){next(e)}});

export {publicRouter as inventoryV2PublicRoutes};
export default router;
