import express from "express";
import {prisma} from "../prisma.js";
import {isPlatformSuperAdmin} from "../middleware/module-access.js";
const router=express.Router();
const TYPES=new Set(["GENERAL","SHIFT","CASH","INVOICE","PAYMENT","STOCK_SHORTAGE","EQUIPMENT","ORDER","ANNOUNCEMENT","INCIDENT"]);
export async function ensureStoreChatSchema(){await prisma.$executeRawUnsafe(`CREATE TABLE IF NOT EXISTS "StoreChatMessage" ("id" TEXT PRIMARY KEY,"companyId" TEXT NOT NULL,"storeId" TEXT NOT NULL,"senderId" TEXT NOT NULL,"category" TEXT NOT NULL DEFAULT 'GENERAL',"body" TEXT NOT NULL,"important" BOOLEAN NOT NULL DEFAULT false,"pinned" BOOLEAN NOT NULL DEFAULT false,"completed" BOOLEAN NOT NULL DEFAULT false,"createdAt" TIMESTAMP NOT NULL DEFAULT NOW(),"updatedAt" TIMESTAMP NOT NULL DEFAULT NOW())`);await prisma.$executeRawUnsafe(`CREATE INDEX IF NOT EXISTS "StoreChatMessage_store_created_idx" ON "StoreChatMessage" ("storeId","createdAt")`)}
async function storeFor(req,res){const id=String(req.params.storeId||req.body?.storeId||"");if(!id)return res.status(400).json({error:"Δεν προσδιορίστηκε κατάστημα."});const store=await prisma.store.findUnique({where:{id},select:{id:true,companyId:true,name:true}});const user=req.user||{};if(!store||(!isPlatformSuperAdmin(user)&&String(user.companyId)!==String(store.companyId))||(user.tokenType==="STORE_OPERATOR"&&String(user.storeId)!==String(id)))return res.status(404).json({error:"Δεν βρέθηκε κατάστημα."});return store}
async function audit(req,store,action,details){await prisma.$executeRaw`INSERT INTO "WorkforceAuditLog" ("id","companyId","storeId","actorUserId","action","entityType","entityId","afterJson","createdAt") VALUES (${`chat-${Date.now()}-${Math.random().toString(36).slice(2)}`},${store.companyId},${store.id},${req.user.id},${action},'STORE_CHAT',${details.messageId||null},${JSON.stringify(details)}::jsonb,NOW())`}
router.get("/stores/:storeId/messages",async(req,res,next)=>{try{const store=await storeFor(req,res);if(!store)return;const limit=Math.min(Math.max(Number(req.query.limit||100),1),200);const fetched=await prisma.$queryRaw`SELECT "id","senderId","category","body","important","pinned","completed","createdAt" FROM "StoreChatMessage" WHERE "storeId"=${store.id} ORDER BY "createdAt" DESC`;const rows=fetched.slice(0,limit).reverse();res.json({store,rows})}catch(e){next(e)}});
router.post("/stores/:storeId/messages",async(req,res,next)=>{try{const store=await storeFor(req,res);if(!store)return;const body=String(req.body?.body||"").trim(),category=String(req.body?.category||"GENERAL").toUpperCase();if(!body||body.length>5000||!TYPES.has(category))return res.status(400).json({error:"Μη έγκυρο μήνυμα ή κατηγορία."});const id=`chat-${Date.now()}-${Math.random().toString(36).slice(2)}`;await prisma.$executeRaw`INSERT INTO "StoreChatMessage" ("id","companyId","storeId","senderId","category","body","createdAt","updatedAt") VALUES (${id},${store.companyId},${store.id},${req.user.id},${category},${body},NOW(),NOW())`;await audit(req,store,"STORE_CHAT_MESSAGE_SENT",{messageId:id,category});res.status(201).json({ok:true,id})}catch(e){next(e)}});
export default router;
