import crypto from "crypto";
import {Router} from "express";
import {z} from "zod";
import {prisma} from "../prisma.js";

const router=Router();
const roles=new Set(["SUPER_ADMIN","OWNER","ADMIN","MANAGER"]);
const id=()=>crypto.randomUUID();
const n=value=>Number(value||0);
let schemaPromise;

async function ensureSchema(){
  if(!schemaPromise){
    schemaPromise=(async()=>{
      const alters=[
        `ALTER TABLE "Supplier" ADD COLUMN IF NOT EXISTS "legacyCode" TEXT`,
        `ALTER TABLE "Supplier" ADD COLUMN IF NOT EXISTS "erpCode" TEXT`,
        `ALTER TABLE "Supplier" ADD COLUMN IF NOT EXISTS "profession" TEXT`,
        `ALTER TABLE "Supplier" ADD COLUMN IF NOT EXISTS "mobile" TEXT`,
        `ALTER TABLE "Supplier" ADD COLUMN IF NOT EXISTS "fax" TEXT`,
        `ALTER TABLE "Supplier" ADD COLUMN IF NOT EXISTS "sellerName" TEXT`,
        `ALTER TABLE "Supplier" ADD COLUMN IF NOT EXISTS "accountingCode" TEXT`,
        `ALTER TABLE "Supplier" ADD COLUMN IF NOT EXISTS "myfEnabled" BOOLEAN NOT NULL DEFAULT true`,
        `ALTER TABLE "Supplier" ADD COLUMN IF NOT EXISTS "supplierCategory" TEXT NOT NULL DEFAULT 'A'`,
        `ALTER TABLE "Supplier" ADD COLUMN IF NOT EXISTS "scope" TEXT NOT NULL DEFAULT 'INTERNAL'`,
        `ALTER TABLE "Supplier" ADD COLUMN IF NOT EXISTS "paymentPreference" TEXT NOT NULL DEFAULT 'CREDIT'`,
        `ALTER TABLE "Supplier" ADD COLUMN IF NOT EXISTS "vatMode" TEXT NOT NULL DEFAULT 'NORMAL'`,
        `ALTER TABLE "Supplier" ADD COLUMN IF NOT EXISTS "notes" TEXT`,
        `ALTER TABLE "Supplier" ADD COLUMN IF NOT EXISTS "chargeAddress" TEXT`
      ];
      for(const sql of alters)await prisma.$executeRawUnsafe(sql);
      await prisma.$executeRawUnsafe(`CREATE TABLE IF NOT EXISTS "SupplierAddress" (
        "id" TEXT PRIMARY KEY,"companyId" TEXT NOT NULL,"supplierId" TEXT NOT NULL,"label" TEXT,"address" TEXT NOT NULL,"city" TEXT,"postalCode" TEXT,"phone" TEXT,"isPrimary" BOOLEAN NOT NULL DEFAULT false,"createdAt" TIMESTAMPTZ NOT NULL DEFAULT NOW(),"updatedAt" TIMESTAMPTZ NOT NULL DEFAULT NOW())`);
      await prisma.$executeRawUnsafe(`CREATE INDEX IF NOT EXISTS "SupplierAddress_supplier_idx" ON "SupplierAddress" ("supplierId")`);
      await prisma.$executeRawUnsafe(`CREATE TABLE IF NOT EXISTS "SupplierBusinessUnit" (
        "id" TEXT PRIMARY KEY,"companyId" TEXT NOT NULL,"supplierId" TEXT NOT NULL,"name" TEXT NOT NULL,"code" TEXT,"email" TEXT,"phone" TEXT,"active" BOOLEAN NOT NULL DEFAULT true,"createdAt" TIMESTAMPTZ NOT NULL DEFAULT NOW(),"updatedAt" TIMESTAMPTZ NOT NULL DEFAULT NOW())`);
      await prisma.$executeRawUnsafe(`CREATE INDEX IF NOT EXISTS "SupplierBusinessUnit_supplier_idx" ON "SupplierBusinessUnit" ("supplierId")`);
      await prisma.$executeRawUnsafe(`CREATE TABLE IF NOT EXISTS "SupplierBalanceAdjustment" (
        "id" TEXT PRIMARY KEY,"companyId" TEXT NOT NULL,"supplierId" TEXT NOT NULL,"amount" NUMERIC(14,4) NOT NULL,"note" TEXT,"actorId" TEXT,"actorName" TEXT,"occurredAt" TIMESTAMPTZ NOT NULL DEFAULT NOW(),"createdAt" TIMESTAMPTZ NOT NULL DEFAULT NOW())`);
      await prisma.$executeRawUnsafe(`CREATE INDEX IF NOT EXISTS "SupplierBalanceAdjustment_supplier_idx" ON "SupplierBalanceAdjustment" ("supplierId","occurredAt" DESC)`);
      await prisma.$executeRawUnsafe(`CREATE TABLE IF NOT EXISTS "SupplierPaymentSettlement" (
        "id" TEXT PRIMARY KEY,"companyId" TEXT NOT NULL,"storeId" TEXT NOT NULL,"transactionId" TEXT NOT NULL UNIQUE,"supplierId" TEXT NOT NULL,"status" TEXT NOT NULL DEFAULT 'PENDING_REVIEW',"paymentMethod" TEXT NOT NULL,"paidAt" TIMESTAMPTZ NOT NULL,"note" TEXT,"createdBy" TEXT NOT NULL,"createdByName" TEXT NOT NULL,"createdAt" TIMESTAMPTZ NOT NULL DEFAULT NOW(),"reviewedBy" TEXT,"reviewedAt" TIMESTAMPTZ,"reviewNote" TEXT)`);
      await prisma.$executeRawUnsafe(`CREATE TABLE IF NOT EXISTS "SupplierPaymentAllocation" (
        "id" TEXT PRIMARY KEY,"companyId" TEXT NOT NULL,"settlementId" TEXT NOT NULL REFERENCES "SupplierPaymentSettlement"("id") ON DELETE CASCADE,"purchaseDocumentId" TEXT NOT NULL REFERENCES "PurchaseDocument"("id") ON DELETE RESTRICT,"amount" NUMERIC(14,2) NOT NULL CHECK ("amount">0),"createdAt" TIMESTAMPTZ NOT NULL DEFAULT NOW(),UNIQUE ("settlementId","purchaseDocumentId"))`);
    })().catch(error=>{schemaPromise=undefined;throw error});
  }
  return schemaPromise;
}
function requireAccess(req,res,next){if(req.user?.tokenType==="STORE_OPERATOR"||!roles.has(req.user?.role))return res.status(403).json({error:"Η πλήρης διαχείριση προμηθευτών είναι διαθέσιμη μόνο σε Super Admin, Ιδιοκτήτη, Admin ή Manager."});next()}
router.use(requireAccess);
router.use(async(req,res,next)=>{try{await ensureSchema();next()}catch(error){next(error)}});
async function owned(companyId,supplierId){const rows=await prisma.$queryRaw`SELECT * FROM "Supplier" WHERE "id"=${supplierId} AND "companyId"=${companyId} LIMIT 1`;return rows[0]||null}
function dates(query={}){const now=new Date(),to=query.to?new Date(String(query.to)):now,from=query.from?new Date(String(query.from)):new Date(to.getFullYear(),to.getMonth(),1);if(!Number.isFinite(from.getTime())||!Number.isFinite(to.getTime())||from>to){const e=new Error("Μη έγκυρο διάστημα ημερομηνιών.");e.status=400;throw e}return{from,to}}

router.get("/report",async(req,res,next)=>{try{
  const companyId=req.user.companyId,q=String(req.query.q||"").trim(),activeOnly=String(req.query.activeOnly||"true")!=="false",text=q?`%${q}%`:null;
  const rows=await prisma.$queryRaw`
    SELECT s.*,COALESCE(pur."allPurchases",0) AS "allPurchases",COALESCE(pay."payments",0) AS "payments",COALESCE(adj."adjustments",0) AS "adjustments",COALESCE(y."currentYear",0) AS "currentYear",COALESCE(y."previousYear",0) AS "previousYear"
    FROM "Supplier" s
    LEFT JOIN LATERAL (SELECT SUM(d."totalGross") AS "allPurchases" FROM "PurchaseDocument" d WHERE d."companyId"=${companyId} AND d."supplierId"=s."id" AND d."status"='APPROVED') pur ON true
    LEFT JOIN LATERAL (SELECT SUM(t."amount") AS "payments" FROM "StoreTransaction" t WHERE t."companyId"=${companyId} AND t."supplierId"=s."id" AND t."type"='SUPPLIER_PAYMENT' AND t."reversedAt" IS NULL) pay ON to_regclass('public."StoreTransaction"') IS NOT NULL
    LEFT JOIN LATERAL (SELECT SUM(a."amount") AS "adjustments" FROM "SupplierBalanceAdjustment" a WHERE a."companyId"=${companyId} AND a."supplierId"=s."id") adj ON true
    LEFT JOIN LATERAL (SELECT SUM(d."totalGross") FILTER (WHERE EXTRACT(YEAR FROM d."documentDate")=EXTRACT(YEAR FROM CURRENT_DATE)) AS "currentYear",SUM(d."totalGross") FILTER (WHERE EXTRACT(YEAR FROM d."documentDate")=EXTRACT(YEAR FROM CURRENT_DATE)-1) AS "previousYear" FROM "PurchaseDocument" d WHERE d."companyId"=${companyId} AND d."supplierId"=s."id" AND d."status"='APPROVED') y ON true
    WHERE s."companyId"=${companyId} AND (${activeOnly}=false OR s."active"=true) AND (${text}::text IS NULL OR s."name" ILIKE ${text} OR COALESCE(s."taxId",'') ILIKE ${text} OR COALESCE(s."legacyCode",'') ILIKE ${text})
    ORDER BY s."name" LIMIT 1500`;
  const suppliers=rows.map(r=>({...r,allPurchases:n(r.allPurchases),payments:n(r.payments),adjustments:n(r.adjustments),currentYear:n(r.currentYear),previousYear:n(r.previousYear),balance:n(r.allPurchases)+n(r.adjustments)-n(r.payments)}));
  const summary=suppliers.reduce((a,r)=>{a.count++;a.balance+=r.balance;a.currentYear+=r.currentYear;return a},{count:0,balance:0,currentYear:0});res.json({suppliers,summary});
}catch(error){next(error)}});

router.get("/:supplierId/detail",async(req,res,next)=>{try{
  const companyId=req.user.companyId,s=await owned(companyId,req.params.supplierId);if(!s)return res.status(404).json({error:"Δεν βρέθηκε ο προμηθευτής."});
  const [addresses,units,adjustments,stores]=await Promise.all([
    prisma.$queryRaw`SELECT * FROM "SupplierAddress" WHERE "companyId"=${companyId} AND "supplierId"=${s.id} ORDER BY "isPrimary" DESC,"createdAt"`,
    prisma.$queryRaw`SELECT * FROM "SupplierBusinessUnit" WHERE "companyId"=${companyId} AND "supplierId"=${s.id} ORDER BY "active" DESC,"name"`,
    prisma.$queryRaw`SELECT * FROM "SupplierBalanceAdjustment" WHERE "companyId"=${companyId} AND "supplierId"=${s.id} ORDER BY "occurredAt" DESC LIMIT 100`,
    prisma.store.findMany({where:{companyId,active:true},select:{id:true,name:true},orderBy:{name:"asc"}})
  ]);res.json({supplier:s,addresses,units,adjustments:adjustments.map(a=>({...a,amount:n(a.amount)})),stores});
}catch(error){next(error)}});

router.patch("/:supplierId",async(req,res,next)=>{try{
  const companyId=req.user.companyId,s=await owned(companyId,req.params.supplierId);if(!s)return res.status(404).json({error:"Δεν βρέθηκε ο προμηθευτής."});
  const body=z.object({legacyCode:z.string().max(40).optional().nullable(),erpCode:z.string().max(80).optional().nullable(),name:z.string().trim().min(1).max(180).optional(),taxId:z.string().max(30).optional().nullable(),profession:z.string().max(180).optional().nullable(),phone:z.string().max(40).optional().nullable(),mobile:z.string().max(40).optional().nullable(),fax:z.string().max(40).optional().nullable(),email:z.string().email().optional().nullable(),sellerName:z.string().max(180).optional().nullable(),accountingCode:z.string().max(80).optional().nullable(),myfEnabled:z.boolean().optional(),active:z.boolean().optional(),supplierCategory:z.enum(["A","B","C"]).optional(),scope:z.enum(["INTERNAL","EXTERNAL"]).optional(),paymentPreference:z.enum(["CREDIT","CASH"]).optional(),vatMode:z.enum(["NORMAL","REDUCED","EXEMPT"]).optional(),notes:z.string().max(1000).optional().nullable(),address:z.string().max(250).optional().nullable(),city:z.string().max(120).optional().nullable(),chargeAddress:z.string().max(250).optional().nullable()}).parse(req.body||{});
  await prisma.$executeRaw`UPDATE "Supplier" SET "legacyCode"=COALESCE(${body.legacyCode??null},"legacyCode"),"erpCode"=COALESCE(${body.erpCode??null},"erpCode"),"name"=COALESCE(${body.name??null},"name"),"taxId"=COALESCE(${body.taxId??null},"taxId"),"profession"=COALESCE(${body.profession??null},"profession"),"phone"=COALESCE(${body.phone??null},"phone"),"mobile"=COALESCE(${body.mobile??null},"mobile"),"fax"=COALESCE(${body.fax??null},"fax"),"email"=COALESCE(${body.email??null},"email"),"sellerName"=COALESCE(${body.sellerName??null},"sellerName"),"accountingCode"=COALESCE(${body.accountingCode??null},"accountingCode"),"myfEnabled"=COALESCE(${body.myfEnabled??null},"myfEnabled"),"active"=COALESCE(${body.active??null},"active"),"supplierCategory"=COALESCE(${body.supplierCategory??null},"supplierCategory"),"scope"=COALESCE(${body.scope??null},"scope"),"paymentPreference"=COALESCE(${body.paymentPreference??null},"paymentPreference"),"vatMode"=COALESCE(${body.vatMode??null},"vatMode"),"notes"=COALESCE(${body.notes??null},"notes"),"address"=COALESCE(${body.address??null},"address"),"city"=COALESCE(${body.city??null},"city"),"chargeAddress"=COALESCE(${body.chargeAddress??null},"chargeAddress"),"updatedAt"=NOW() WHERE "id"=${s.id} AND "companyId"=${companyId}`;res.json({ok:true});
}catch(error){next(error)}});

router.post("/:supplierId/addresses",async(req,res,next)=>{try{const companyId=req.user.companyId,s=await owned(companyId,req.params.supplierId);if(!s)return res.status(404).json({error:"Δεν βρέθηκε ο προμηθευτής."});const b=z.object({label:z.string().max(80).optional().nullable(),address:z.string().min(1).max(250),city:z.string().max(120).optional().nullable(),postalCode:z.string().max(20).optional().nullable(),phone:z.string().max(40).optional().nullable(),isPrimary:z.boolean().optional()}).parse(req.body||{});const rowId=id();if(b.isPrimary)await prisma.$executeRaw`UPDATE "SupplierAddress" SET "isPrimary"=false WHERE "companyId"=${companyId} AND "supplierId"=${s.id}`;await prisma.$executeRaw`INSERT INTO "SupplierAddress" ("id","companyId","supplierId","label","address","city","postalCode","phone","isPrimary") VALUES (${rowId},${companyId},${s.id},${b.label||null},${b.address},${b.city||null},${b.postalCode||null},${b.phone||null},${b.isPrimary||false})`;res.status(201).json({id:rowId})}catch(error){next(error)}});
router.delete("/:supplierId/addresses/:id",async(req,res,next)=>{try{await prisma.$executeRaw`DELETE FROM "SupplierAddress" WHERE "id"=${req.params.id} AND "supplierId"=${req.params.supplierId} AND "companyId"=${req.user.companyId}`;res.json({ok:true})}catch(error){next(error)}});
router.post("/:supplierId/units",async(req,res,next)=>{try{const companyId=req.user.companyId,s=await owned(companyId,req.params.supplierId);if(!s)return res.status(404).json({error:"Δεν βρέθηκε ο προμηθευτής."});const b=z.object({name:z.string().min(1).max(120),code:z.string().max(60).optional().nullable(),email:z.string().email().optional().nullable(),phone:z.string().max(40).optional().nullable()}).parse(req.body||{});const rowId=id();await prisma.$executeRaw`INSERT INTO "SupplierBusinessUnit" ("id","companyId","supplierId","name","code","email","phone") VALUES (${rowId},${companyId},${s.id},${b.name},${b.code||null},${b.email||null},${b.phone||null})`;res.status(201).json({id:rowId})}catch(error){next(error)}});
router.delete("/:supplierId/units/:id",async(req,res,next)=>{try{await prisma.$executeRaw`DELETE FROM "SupplierBusinessUnit" WHERE "id"=${req.params.id} AND "supplierId"=${req.params.supplierId} AND "companyId"=${req.user.companyId}`;res.json({ok:true})}catch(error){next(error)}});
router.post("/:supplierId/balance-adjustments",async(req,res,next)=>{try{const companyId=req.user.companyId,s=await owned(companyId,req.params.supplierId);if(!s)return res.status(404).json({error:"Δεν βρέθηκε ο προμηθευτής."});const b=z.object({amount:z.coerce.number().finite().min(-999999999).max(999999999),note:z.string().max(500).optional().nullable(),occurredAt:z.coerce.date().optional()}).parse(req.body||{});const rowId=id();await prisma.$executeRaw`INSERT INTO "SupplierBalanceAdjustment" ("id","companyId","supplierId","amount","note","actorId","actorName","occurredAt") VALUES (${rowId},${companyId},${s.id},${b.amount},${b.note||null},${req.user.id},${req.user.fullName||"Χρήστης"},${b.occurredAt||new Date()})`;res.status(201).json({id:rowId})}catch(error){next(error)}});

router.get("/:supplierId/invoices",async(req,res,next)=>{try{const companyId=req.user.companyId,s=await owned(companyId,req.params.supplierId);if(!s)return res.status(404).json({error:"Δεν βρέθηκε ο προμηθευτής."});const{from,to}=dates(req.query);const rows=await prisma.$queryRaw`SELECT d."id",d."documentType",d."documentNumber",d."documentDate",d."totalNet",d."totalVat",d."totalGross",d."status",d."sourceType",st."name" AS "storeName" FROM "PurchaseDocument" d JOIN "Store" st ON st."id"=d."storeId" WHERE d."companyId"=${companyId} AND d."supplierId"=${s.id} AND d."documentDate">=${from} AND d."documentDate"<=${to} ORDER BY d."documentDate" DESC`;res.json(rows.map(r=>({...r,totalNet:n(r.totalNet),totalVat:n(r.totalVat),totalGross:n(r.totalGross)})))}catch(error){next(error)}});
router.get("/:supplierId/payments",async(req,res,next)=>{try{const companyId=req.user.companyId,s=await owned(companyId,req.params.supplierId);if(!s)return res.status(404).json({error:"Δεν βρέθηκε ο προμηθευτής."});const{from,to}=dates(req.query);const rows=await prisma.$queryRaw`SELECT t."id",t."occurredAt",t."amount",t."description",t."actorName",t."storeId",st."name" AS "storeName",t."reversedAt" FROM "StoreTransaction" t JOIN "Store" st ON st."id"=t."storeId" WHERE t."companyId"=${companyId} AND t."supplierId"=${s.id} AND t."type"='SUPPLIER_PAYMENT' AND t."occurredAt">=${from} AND t."occurredAt"<=${to} ORDER BY t."occurredAt" DESC`;res.json(rows.map(r=>({...r,amount:n(r.amount)})))}catch(error){next(error)}});
router.get("/:supplierId/purchases",async(req,res,next)=>{try{const companyId=req.user.companyId,s=await owned(companyId,req.params.supplierId);if(!s)return res.status(404).json({error:"Δεν βρέθηκε ο προμηθευτής."});const{from,to}=dates(req.query);const rows=await prisma.$queryRaw`SELECT COALESCE(SUM(d."totalNet"),0) AS net,COALESCE(SUM(d."totalVat"),0) AS vat,COALESCE(SUM(d."totalGross"),0) AS gross,COUNT(*)::int AS documents FROM "PurchaseDocument" d WHERE d."companyId"=${companyId} AND d."supplierId"=${s.id} AND d."documentDate">=${from} AND d."documentDate"<=${to} AND d."status"='APPROVED'`;res.json({summary:{net:n(rows[0]?.net),vat:n(rows[0]?.vat),gross:n(rows[0]?.gross),documents:n(rows[0]?.documents)}})}catch(error){next(error)}});
router.get("/:supplierId/sales",async(req,res,next)=>{try{const companyId=req.user.companyId,s=await owned(companyId,req.params.supplierId);if(!s)return res.status(404).json({error:"Δεν βρέθηκε ο προμηθευτής."});const{from,to}=dates(req.query);const rows=await prisma.$queryRaw`
  WITH supplier_products AS (SELECT DISTINCT l."productId" FROM "PurchaseDocumentLine" l JOIN "PurchaseDocument" d ON d."id"=l."purchaseDocumentId" WHERE d."companyId"=${companyId} AND d."supplierId"=${s.id} AND l."productId" IS NOT NULL),costs AS (SELECT l."productId",SUM(l."netAmount")/NULLIF(SUM(l."quantity"*COALESCE(l."unitsPerPackage",1)),0) AS "avgCost",(array_agg(CASE WHEN l."unit"='PACKAGE' THEN l."unitCost"/NULLIF(l."unitsPerPackage",0) ELSE l."unitCost" END ORDER BY d."documentDate" DESC))[1] AS "lastCost" FROM "PurchaseDocumentLine" l JOIN "PurchaseDocument" d ON d."id"=l."purchaseDocumentId" WHERE d."companyId"=${companyId} AND d."supplierId"=${s.id} AND l."productId" IS NOT NULL GROUP BY l."productId") SELECT p."id",p."name",p."sku",SUM(sl."quantity") AS quantity,SUM(sl."lineTotal") AS sales,COALESCE(c."avgCost",0) AS "avgCost",COALESCE(c."lastCost",0) AS "lastCost",COALESCE(SUM(sp."currentStock")/NULLIF(COUNT(DISTINCT sp."storeId"),0),0) AS "currentStock" FROM supplier_products x JOIN "Product" p ON p."id"=x."productId" JOIN "SaleLine" sl ON sl."productId"=p."id" JOIN "Sale" sa ON sa."id"=sl."saleId" AND sa."companyId"=${companyId} LEFT JOIN costs c ON c."productId"=p."id" LEFT JOIN "StoreProduct" sp ON sp."productId"=p."id" WHERE sa."status"='COMPLETED' AND sa."occurredAt">=${from} AND sa."occurredAt"<=${to} GROUP BY p."id",p."name",p."sku",c."avgCost",c."lastCost" ORDER BY sales DESC`;
  const items=rows.map(r=>{const quantity=n(r.quantity),sales=n(r.sales),avgCost=n(r.avgCost),lastCost=n(r.lastCost),cost=quantity*avgCost,profit=sales-cost;return{...r,quantity,sales,avgCost,lastCost,currentStock:n(r.currentStock),cost,profit,margin:sales?profit/sales*100:0}});const summary=items.reduce((a,r)=>{a.sales+=r.sales;a.cost+=r.cost;a.profit+=r.profit;a.items++;return a},{sales:0,cost:0,profit:0,items:0});summary.margin=summary.sales?summary.profit/summary.sales*100:0;res.json({summary,items,sourceNote:"Η αντιστοίχιση ειδών στον προμηθευτή βασίζεται σε πραγματικές αγορές του είδους από τον συγκεκριμένο προμηθευτή."})}catch(error){next(error)}});
router.get("/:supplierId/ledger",async(req,res,next)=>{try{const companyId=req.user.companyId,s=await owned(companyId,req.params.supplierId);if(!s)return res.status(404).json({error:"Δεν βρέθηκε ο προμηθευτής."});const{from,to}=dates(req.query);const [docs,pay,adj]=await Promise.all([prisma.$queryRaw`SELECT "id","documentDate" AS at,'PURCHASE' AS type,"documentNumber" AS ref,"totalGross" AS amount FROM "PurchaseDocument" WHERE "companyId"=${companyId} AND "supplierId"=${s.id} AND "documentDate">=${from} AND "documentDate"<=${to} AND "status"='APPROVED'`,prisma.$queryRaw`SELECT t."id",t."occurredAt" AS at,'PAYMENT' AS type,t."description" AS ref,-t."amount" AS amount FROM "StoreTransaction" t WHERE t."companyId"=${companyId} AND t."supplierId"=${s.id} AND t."type"='SUPPLIER_PAYMENT' AND t."reversedAt" IS NULL AND t."occurredAt">=${from} AND t."occurredAt"<=${to} AND NOT EXISTS (SELECT 1 FROM "SupplierPaymentSettlement" ss WHERE ss."companyId"=t."companyId" AND ss."transactionId"=t."id" AND ss."status"<>'CONFIRMED')`,prisma.$queryRaw`SELECT "id","occurredAt" AS at,'ADJUSTMENT' AS type,"note" AS ref,"amount" FROM "SupplierBalanceAdjustment" WHERE "companyId"=${companyId} AND "supplierId"=${s.id} AND "occurredAt">=${from} AND "occurredAt"<=${to}`]);const rows=[...docs,...pay,...adj].map(r=>({...r,amount:n(r.amount)})).sort((a,b)=>new Date(a.at)-new Date(b.at));let balance=0;for(const r of rows){balance+=r.amount;r.balance=balance}res.json({rows,balance})}catch(error){next(error)}});
router.post("/:supplierId/value-only-invoice",async(req,res,next)=>{try{const companyId=req.user.companyId,s=await owned(companyId,req.params.supplierId);if(!s)return res.status(404).json({error:"Δεν βρέθηκε ο προμηθευτής."});const b=z.object({storeId:z.string(),documentNumber:z.string().max(80).optional().nullable(),documentDate:z.coerce.date().optional(),totalNet:z.coerce.number().min(0),totalVat:z.coerce.number().min(0),notes:z.string().max(300).optional().nullable()}).parse(req.body||{});const st=await prisma.store.findFirst({where:{id:b.storeId,companyId,active:true},select:{id:true}});if(!st)return res.status(404).json({error:"Δεν βρέθηκε το κατάστημα."});const docId=id(),gross=b.totalNet+b.totalVat;await prisma.$executeRaw`INSERT INTO "PurchaseDocument" ("id","companyId","storeId","supplierId","documentType","documentNumber","documentDate","totalNet","totalVat","totalGross","sourceType","status","createdByUserId") VALUES (${docId},${companyId},${st.id},${s.id},'INVOICE',${b.documentNumber||null},${b.documentDate||new Date()},${b.totalNet},${b.totalVat},${gross},'MANUAL','DRAFT',${req.user.id})`;res.status(201).json({id:docId,totalGross:gross})}catch(error){next(error)}});
router.delete("/:supplierId",async(req,res,next)=>{try{const s=await owned(req.user.companyId,req.params.supplierId);if(!s)return res.status(404).json({error:"Δεν βρέθηκε ο προμηθευτής."});await prisma.$executeRaw`UPDATE "Supplier" SET "active"=false,"updatedAt"=NOW() WHERE "id"=${s.id} AND "companyId"=${req.user.companyId}`;res.json({ok:true,message:"Ο προμηθευτής απενεργοποιήθηκε. Δεν διαγράφηκε ιστορικό."})}catch(error){next(error)}});

export default router;
