import test from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs";

const read=path=>fs.readFileSync(new URL(path,import.meta.url),"utf8");
test("Inventory 2.0 supports partial scope without touching unrelated products",()=>{const route=read("../src/routes/inventory-v2.js");assert.match(route,/PARTIAL_PRODUCTS/);assert.match(route,/PARTIAL_CATEGORIES/);assert.match(route,/p\."id"=ANY/);assert.match(route,/WHERE "stocktakeId"=\$\{st\.id\} FOR UPDATE/)});
test("Inventory 2.0 keeps immutable count and recount evidence",()=>{const schema=read("../src/owner-product-bootstrap.js"),route=read("../src/routes/inventory-v2.js");assert.match(schema,/InventoryCountEvent/);assert.match(schema,/clientEventId/);assert.match(route,/expectedVersion/);assert.match(route,/eventType=previous===null\?"COUNT":"RECOUNT"/)});
test("live stocktakes adjust the expected quantity from every stock movement",()=>{const schema=read("../src/owner-product-bootstrap.js"),route=read("../src/routes/inventory-v2.js");assert.match(schema,/mws_adjust_live_stocktake_expected/);assert.match(schema,/NEW\."quantity"/);assert.match(schema,/st\."liveDuringTrading"=TRUE/);assert.match(schema,/StocktakeMovementAdjustment/);assert.match(schema,/AFTER INSERT ON "StockMovement"/);assert.match(route,/movementAdjustments/)});
test("Inventory mobile access is scoped and expiring",()=>{const route=read("../src/routes/inventory-v2.js");assert.match(route,/INVENTORY_COUNTER/);assert.match(route,/stocktakeId:g\.stocktakeId/);assert.match(route,/zoneId:g\.zoneId/);assert.match(route,/expiresIn:"8h"/)});
test("Inventory mobile scans retail barcodes with the rear camera",()=>{const app=read("../../client/src/components/inventory/InventoryMobileApp.jsx"),css=read("../../client/src/components/inventory/inventory-mobile-fast.css");assert.match(app,/navigator\.mediaDevices\.getUserMedia/);assert.match(app,/facingMode:\{ideal:"environment"\}/);assert.match(app,/new window\.BarcodeDetector/);assert.match(app,/ean_13/);assert.match(app,/Σάρωση με κάμερα/);assert.match(app,/resolveTerm\(value\)/);assert.match(app,/getTracks\(\)\.forEach\(track=>track\.stop\(\)\)/);assert.match(css,/\.inv-scanner/)});
