import assert from "node:assert/strict";
import {execFileSync} from "node:child_process";
import fs from "node:fs";
import path from "node:path";
import {fileURLToPath} from "node:url";
import test from "node:test";
const repo=path.resolve(path.dirname(fileURLToPath(import.meta.url)),"../..");
const read=p=>fs.readFileSync(path.join(repo,p),"utf8");
const backend="server/src/routes/management-business-units.js";
const installer="client/src/components/commerce/installManagementBusinessUnitsSuite.js";
const bootstrap="client/src/management-business-units-bootstrap.js";
const panel="client/src/components/commerce/ManagementBusinessUnitsPanel.jsx";
const css="client/src/components/commerce/management-business-units.css";
const b=read(backend),i=read(installer),boot=read(bootstrap),c=read(panel),styles=read(css),index=read("server/src/index.js"),html=read("client/index.html");
test("business units backend and installer parse",()=>{execFileSync(process.execPath,["--check",path.join(repo,backend)]);execFileSync(process.execPath,["--check",path.join(repo,installer)]);execFileSync(process.execPath,["--check",path.join(repo,bootstrap)])});
test("banks are real company scoped records",()=>{assert.match(b,/ManagementBank/);assert.match(b,/internalCode/);assert.match(b,/accountingAccount/);assert.match(b,/auxiliaryName/);assert.match(b,/companyId/);assert.doesNotMatch(b,/ΟΨΕΩΣ|380300|38\.03\.00\.0000/)});
test("shipping methods are real timestamped records",()=>{assert.match(b,/ManagementShippingMethod/);assert.match(b,/createdAt/);assert.match(b,/updatedAt/);assert.doesNotMatch(b,/ΙΔΙΑ ΜΕΣΑ|ΗΛΕΚΤΡΟΝΙΚΗ ΑΠΟΣΤΟΛΗ|COURIER/)});
test("shipping pencil opens photographed edit fields",()=>{for(const text of ["Διόρθωση τρόπου αποστολής","κωδικός:","Ονομασία:","ενεργό","Επιστροφή","Καταχώρηση"])assert.ok(c.includes(text),text);assert.match(c,/<Edit3\/>/)});
test("bank and shipping grids match visible columns and lower actions",()=>{for(const text of ["εσωτ. κωδ","Ονομασία","Λογ. Λογιστικής","Βοηθητική ονομασία","Κωδ","Περιγραφή","καταχώρηση","ενημέρωση","Κλείσιμο","Ανανέωση","Νέα εγγραφή","Excel / CSV"])assert.ok(c.includes(text),text);assert.match(c,/<Trash2\/>/)});
test("POS terminals are real company scoped records linked to banks",()=>{for(const text of ["ManagementPosTerminal","bankId","paymentMethodCode","helperField1","deferredCode","helperField3","ipAddress","onlineMiddleware","notes","companyId"])assert.ok(b.includes(text),text);assert.match(b,/LEFT JOIN "ManagementBank"/);assert.match(b,/requireBank/);assert.doesNotMatch(b,/EDPS|13248261|ΔΕΥΤΕΡΟ POS/)});
test("POS terminal pencil opens all photographed fields",()=>{for(const text of ["Διόρθωση PoS τερματικού","τράπεζα:","Ονομασία:","κωδ. τρόπου πληρωμής:","TID:","κωδ. ετεροχρ:","βοηθ. πεδίο 1:","δ/νση IP:","port:","βοηθ. πεδίο 3:","On Line (1155 / middleware)","παρατηρήσεις:","IRIS","ενεργό","Επιστροφή","Καταχώρηση"])assert.ok(c.includes(text),text)});
test("POS terminal grid matches photographed two-line headers and lower actions",()=>{for(const text of ["Τράπεζα","Ονομασία τερματικού","τρόπος πληρωμής","IRIS πληρωμή","βοηθ. πεδίο 1","κωδ. ετεροχρ","ενημέρωση","παρατηρήσεις","Κλείσιμο","Ανανέωση","Νέα εγγραφή"])assert.ok(c.includes(text),text);assert.match(c,/mode!=="terminals"&&<button onClick=\{exportCsv\}/)});
test("all business unit entities use CRUD and soft deactivate",()=>{assert.match(b,/router\.post\("\/banks"/);assert.match(b,/router\.patch\("\/banks\/:id"/);assert.match(b,/router\.post\("\/shipping-methods"/);assert.match(b,/router\.patch\("\/shipping-methods\/:id"/);assert.match(b,/router\.post\("\/pos-terminals"/);assert.match(b,/router\.patch\("\/pos-terminals\/:id"/);assert.match(b,/UPDATE "ManagementPosTerminal" SET "active"=false/);assert.doesNotMatch(b,/DELETE FROM "ManagementBank"|DELETE FROM "ManagementShippingMethod"|DELETE FROM "ManagementPosTerminal"/)});
test("banks shipping and POS terminal tabs are enabled without new MutationObserver",()=>{assert.match(i,/Τράπεζες/);assert.match(i,/Τρόποι αποστολής/);assert.match(i,/PoS τερματικά/);assert.match(i,/activate\(terminalButton,"terminals"\)/);assert.match(i,/management-business-unit-active/);assert.doesNotMatch(i+boot,/new MutationObserver/);assert.match(html,/management-business-units-bootstrap\.js/)});
test("server mounts business units before generic management route",()=>{const specific=index.indexOf('/api/management/business-units');const generic=index.indexOf('/api/management",auth');assert.ok(specific>=0&&generic>=0&&specific<generic)});
test("MyWorkStation palette is preserved",()=>{assert.match(styles,/#123b5d/);assert.match(styles,/#0f766e/);assert.doesNotMatch(styles,/#ffa500|#ff9/i)});
