import test from 'node:test';
import assert from 'node:assert/strict';
import {createRequire} from 'node:module';
import {fileURLToPath} from 'node:url';
import {build} from 'esbuild';
import {JSDOM} from 'jsdom';

test('actual mounted POS applies live cart guards and opens the existing barcode flow',async()=>{
 const dom=new JSDOM('<div id="root"></div>',{url:'https://isolated.invalid/store/A'});
 const keys=['window','document','navigator','localStorage','sessionStorage','HTMLElement','Event','MutationObserver','FormData','IS_REACT_ACT_ENVIRONMENT','fetch'];
 const previous=new Map(keys.map(k=>[k,Object.getOwnPropertyDescriptor(globalThis,k)]));
 for(const k of keys)Object.defineProperty(globalThis,k,{configurable:true,writable:true,value:k==='IS_REACT_ACT_ENVIRONMENT'?true:k==='fetch'?async()=>({ok:true}):dom.window[k]});
 const React=await import('react'),{createRoot}=await import('react-dom/client'),{act}=React;
 const compiled=await build({entryPoints:[fileURLToPath(new URL('../../client/src/components/store/StorePosPanel.jsx',import.meta.url))],bundle:true,write:false,format:'cjs',platform:'node',external:['react','react-dom','react-dom/client','react/jsx-runtime','pdfjs-dist/build/pdf.worker.min.mjs?url','pdfjs-dist/build/pdf.mjs'],loader:{'.css':'empty'}});
 const m={exports:{}};new Function('require','module','exports',compiled.outputFiles[0].text)(createRequire(import.meta.url),m,m.exports);
 const product={id:'p',name:'CONTROL',sku:'CONTROL-SKU',salePrice:2,currentStock:20,barcodes:[]};
 const calls=[],denied={confirmDeleteSale:false,deleteSaleReason:false,customerCardOnly:false,onlineBarcode:false,editPosButtons:false};
 const api=async(path,options={})=>{calls.push({path,options});
  if(path==='/api/store-pos/stores/A')return {products:[product],access:{...denied,onlineProductSearch:false},layout:{quickKeys:[{id:'quick',visible:true,label:'CONTROL',productQuery:'CONTROL-SKU'}],categories:[]}};
  if(path.endsWith('/access'))return {access:{thirdPartyPayment:true,supplierPayment:true,sameShiftPayments:true}};
  if(path.endsWith('/overview'))return {openSession:{id:'isolated-shift',openedAt:new Date().toISOString()},suppliers:[]};
  if(path.includes('/barcode-registration'))return {rows:[{...product,barcodes:[]}]};
  if(path.endsWith('/label-settings'))return {settings:{}};
  if(path.endsWith('/table-service')||path==='/api/netlink/status')throw Error('inactive');
  if(path.endsWith('/holds'))return {rows:[]};if(path.endsWith('/audience-discounts'))return {items:[]};
  if(path.endsWith('/online-radio'))return {moduleActive:false,enabled:false};if(path.endsWith('/pending'))return {requests:[]};return {};
 };
 const props={api,store:{id:'A',name:'Store A'},operator:{id:'op',fullName:'Operator'},canRegisterBarcode:true};
 const root=createRoot(document.getElementById('root'));
 const render=async rights=>act(async()=>{root.render(React.createElement(m.exports.default,{...props,runtimeAccess:rights}));await new Promise(r=>setTimeout(r,15));});
 const click=async el=>{assert.ok(el);await act(async()=>{el.click();await new Promise(r=>setTimeout(r,15))});};
 const find=text=>[...document.querySelectorAll('button')].find(b=>b.textContent.trim()===text);
 let confirmations=0,reasons=0,confirmResult=false;
 dom.window.confirm=()=>{confirmations++;return confirmResult;};dom.window.prompt=()=>{reasons++;return null;};
 try{
  await render(denied);await click(document.querySelector('.standard-quick button:not([disabled])'));
  const panel=document.querySelector('.store-pos-top'),cart=document.querySelector('.standard-lines').textContent;
  await render({...denied,confirmDeleteSale:true,deleteSaleReason:true});
  await click(find('ΑΚΥΡΩΣΗ'));assert.equal(confirmations,1);assert.equal(reasons,0);assert.equal(document.querySelector('.standard-lines').textContent,cart);
  confirmResult=true;await click(find('ΑΚΥΡΩΣΗ'));assert.equal(confirmations,2);assert.equal(reasons,1);assert.match(document.body.textContent,/τουλάχιστον 3 χαρακτήρων/);assert.equal(document.querySelector('.standard-lines').textContent,cart);
  assert.equal(calls.some(c=>c.path.endsWith('/audit')&&JSON.parse(c.options.body||'{}').actionType==='CART_CANCEL'),false);
  await click(document.querySelector('.line-name-action'));assert.equal(find('Διόρθωση περιγραφής'),undefined);
  await click(find('Προσθήκη νέου barcode'));assert.match(document.body.textContent,/Έλεγχος και καταχώρηση νέου Barcode/);
  assert.equal(document.querySelector('input[placeholder="Όνομα παλιού προϊόντος, SKU ή barcode"]').value,'CONTROL-SKU');
  assert.equal(calls.some(c=>c.path.includes('/barcode-registration')&&c.options.method==='POST'),false);
  await click([...document.querySelectorAll('header')].find(h=>h.textContent.includes('Έλεγχος και καταχώρηση νέου Barcode')).querySelector('button'));
  await render({...denied,customerCardOnly:true});await click(document.querySelector('.pos-credit-customer>button'));
  assert.equal(document.querySelector('[aria-label="Αναζήτηση πελάτη πίστωσης"]').placeholder,'Σκάναρε ή γράψε αριθμό κάρτας');
  await render(denied);assert.match(document.querySelector('[aria-label="Αναζήτηση πελάτη πίστωσης"]').placeholder,/ονόματος/);
  await click(document.querySelector('[aria-label="Κλείσιμο επιλογής πελάτη"]'));
  const search=document.querySelector('input[placeholder="Barcode, SKU ή αναζήτηση προϊόντος"]');
  await act(async()=>{Object.getOwnPropertyDescriptor(dom.window.HTMLInputElement.prototype,'value').set.call(search,'NO_FIXTURE_CODE');search.dispatchEvent(new dom.window.Event('input',{bubbles:true}));});
  await act(async()=>{search.dispatchEvent(new dom.window.KeyboardEvent('keydown',{key:'Enter',bubbles:true}));await new Promise(r=>setTimeout(r,10));});
  await render({...denied,onlineBarcode:true});assert.ok(find('Online αναζήτηση'));
  await render(denied);assert.equal(find('Online αναζήτηση'),undefined);
  await render(denied);assert.equal(document.querySelector('.store-pos-top'),panel);assert.equal(document.querySelector('.standard-lines').textContent,cart);
  await click(find('ΑΚΥΡΩΣΗ'));assert.equal(confirmations,2);assert.equal(reasons,1);assert.match(document.querySelector('.standard-lines').textContent,/Νέα συναλλαγή/);
  assert.equal(calls.filter(c=>c.path==='/api/store-pos/stores/A').length,1);
  const paymentRights={...denied,thirdPartyPayment:true,supplierPayment:true,sameShiftPayments:true};
  await render(paymentRights);await click(find('ΠΛΗΡΩΜΕΣ'));
  const paymentModal=document.querySelector('.pos-standard-modal');
  assert.ok(find('Λοιπά έξοδα'));assert.ok(find('Πληρωμές προμηθευτών – Ετεροχρονισμένες'));
  await click(paymentModal.querySelector('.pos-inline-keypad button'));
  const amount=()=>[...paymentModal.querySelectorAll('label')].find(l=>l.textContent==='Ποσό').querySelector('input').value;
  assert.equal(amount(),'7');
  await render({...paymentRights,thirdPartyPayment:false});
  assert.equal(find('Λοιπά έξοδα'),undefined);assert.ok(find('Πληρωμές προμηθευτών – Ετεροχρονισμένες'));
  assert.equal(document.querySelector('.pos-standard-modal'),paymentModal);
  await render({...paymentRights,supplierPayment:false,sameShiftPayments:false});
  assert.ok(find('Λοιπά έξοδα'));assert.equal(find('Πληρωμές προμηθευτών – Ετεροχρονισμένες'),undefined);
  assert.equal(find('Μετρητά από ενεργή βάρδια').disabled,true);assert.equal(amount(),'7');
  await render({...paymentRights,thirdPartyPayment:false,supplierPayment:false});
  assert.match(paymentModal.textContent,/Δεν έχεις ενεργό δικαίωμα πληρωμών/);
  assert.equal(find('Καταχώριση εξόδου'),undefined);
  await render(paymentRights);assert.ok(find('Λοιπά έξοδα'));assert.ok(find('Πληρωμές προμηθευτών – Ετεροχρονισμένες'));
  assert.equal(find('Μετρητά από ενεργή βάρδια').disabled,false);assert.equal(amount(),'7');
  assert.equal(calls.filter(c=>c.path==='/api/store-pos/stores/A/access').length,1);
  assert.equal(calls.some(c=>c.options.method&&c.options.method!=='GET'&&!/\/(audit|audience-selection)$/.test(c.path)),false);
  await click(paymentModal.querySelector('header button'));
  assert.equal(calls.some(c=>/checkout|\/sales|finalize|sessions\/open/.test(c.path)),false);
 }finally{await act(async()=>root.unmount());dom.window.close();for(const[k,v]of previous){if(v)Object.defineProperty(globalThis,k,v);else delete globalThis[k]}}
});
