import test from 'node:test';
import assert from 'node:assert/strict';
import {createRequire} from 'node:module';
import {fileURLToPath} from 'node:url';
import {build} from 'esbuild';
import {JSDOM} from 'jsdom';

test('actual mounted POS applies live cart guards and opens the existing barcode flow',async()=>{
 const dom=new JSDOM('<div id="root"></div>',{url:'https://isolated.invalid/store/A'});
 const keys=['window','document','navigator','localStorage','sessionStorage','HTMLElement','Event','MutationObserver','FormData','IS_REACT_ACT_ENVIRONMENT','fetch'];
 const previous=new Map(keys.map(k=>[k,Object.getOwnPropertyDescriptor(globalThis,k)]));
 for(const k of keys)Object.defineProperty(globalThis,k,{configurable:true,writable:true,value:k==='IS_REACT_ACT_ENVIRONMENT'?true:k==='fetch'?async()=>({ok:true}):dom.window[k]});
 const React=await import('react'),{createRoot}=await import('react-dom/client'),{act}=React;
 const compiled=await build({entryPoints:[fileURLToPath(new URL('../../client/src/components/store/StorePosPanel.jsx',import.meta.url))],bundle:true,write:false,format:'cjs',platform:'node',external:['react','react-dom','react-dom/client','react/jsx-runtime','pdfjs-dist/build/pdf.worker.min.mjs?url','pdfjs-dist/build/pdf.mjs'],loader:{'.css':'empty'}});
 const m={exports:{}};new Function('require','module','exports',compiled.outputFiles[0].text)(createRequire(import.meta.url),m,m.exports);
 const product={id:'p',name:'CONTROL',sku:'CONTROL-SKU',salePrice:2,currentStock:20,barcodes:[]};
 const calls=[],denied={confirmDeleteSale:false,deleteSaleReason:false,customerCardOnly:false,onlineBarcode:false,editPosButtons:false};
 let rejectCancel=false,pendingCancel=null,rejectPrice=false,pendingPrice=null;
 const api=async(path,options={})=>{calls.push({path,options});
  if(path.endsWith("/audit")&&JSON.parse(options.body||"{}").actionType==="PRICE_CHANGE"){if(rejectPrice)throw Error("PRICE_PERMISSION_REVOKED");if(pendingPrice)await pendingPrice;}
  if(path.endsWith("/audit")&&JSON.parse(options.body||"{}").actionType==="CART_CANCEL"){if(rejectCancel)throw Error("AUDIT_REJECTED");if(pendingCancel)await pendingCancel;}
  if(path==='/api/store-pos/stores/A')return {products:[product],access:{...denied,onlineProductSearch:false},layout:{quickKeys:[{id:'quick',visible:true,label:'CONTROL',productQuery:'CONTROL-SKU'}],categories:[]}};
  if(path.endsWith('/access'))return {access:{thirdPartyPayment:true,supplierPayment:true,sameShiftPayments:true}};
  if(path.endsWith('/overview'))return {openSession:{id:'isolated-shift',openedAt:new Date().toISOString()},suppliers:[]};
  if(path.includes('/barcode-registration'))return {rows:[{...product,barcodes:[]}]};
  if(path.endsWith('/label-settings'))return {settings:{}};
  if(path.endsWith('/table-service')||path==='/api/netlink/status')throw Error('inactive');
  if(path.endsWith('/holds'))return {rows:[]};if(path.endsWith('/audience-discounts'))return {items:[]};
  if(path.endsWith('/online-radio'))return {moduleActive:false,enabled:false};if(path.endsWith('/pending'))return {requests:[]};return {};
 };
 const props={api,store:{id:'A',name:'Store A'},operator:{id:'op',fullName:'Operator'},canRegisterBarcode:true};
 const root=createRoot(document.getElementById('root'));
 const render=async rights=>act(async()=>{root.render(React.createElement(m.exports.default,{...props,runtimeAccess:rights}));await new Promise(r=>setTimeout(r,15));});
 const click=async el=>{assert.ok(el);await act(async()=>{el.click();await new Promise(r=>setTimeout(r,15))});};
 const find=text=>[...document.querySelectorAll('button')].find(b=>b.textContent.trim()===text);
 let confirmations=0,reasons=0,confirmResult=false;
 dom.window.confirm=()=>{confirmations++;return confirmResult;};dom.window.prompt=()=>{reasons++;return null;};
 try{
  await render(denied);await click(document.querySelector('.standard-quick button:not([disabled])'));
  const panel=document.querySelector('.store-pos-top'),cart=document.querySelector('.standard-lines').textContent;
  await render({...denied,confirmDeleteSale:true,deleteSaleReason:true});
  await click(find('ΑΚΥΡΩΣΗ'));assert.equal(confirmations,1);assert.equal(reasons,0);assert.equal(document.querySelector('.standard-lines').textContent,cart);
  confirmResult=true;await click(find('ΑΚΥΡΩΣΗ'));assert.equal(confirmations,2);assert.equal(reasons,0);assert.equal(document.querySelectorAll(".pos-cancel-reason-choices button").length,3);await click(find("Επιστροφή στο καλάθι"));assert.equal(document.querySelector('.standard-lines').textContent,cart);
  assert.equal(calls.some(c=>c.path.endsWith('/audit')&&JSON.parse(c.options.body||'{}').actionType==='CART_CANCEL'),false);
  await click(document.querySelector('.line-name-action'));assert.equal(find('Διόρθωση περιγραφής'),undefined);
  await click(find('Προσθήκη νέου barcode'));assert.match(document.body.textContent,/Έλεγχος και καταχώρηση νέου Barcode/);
  assert.equal(document.querySelector('input[placeholder="Όνομα παλιού προϊόντος, SKU ή barcode"]').value,'CONTROL-SKU');
  assert.equal(calls.some(c=>c.path.includes('/barcode-registration')&&c.options.method==='POST'),false);
  await click([...document.querySelectorAll('header')].find(h=>h.textContent.includes('Έλεγχος και καταχώρηση νέου Barcode')).querySelector('button'));
  await render({...denied,customerCardOnly:true});await click(document.querySelector('.pos-credit-customer>button'));
  assert.equal(document.querySelector('[aria-label="Αναζήτηση πελάτη πίστωσης"]').placeholder,'Σκάναρε ή γράψε αριθμό κάρτας');
  await render(denied);assert.match(document.querySelector('[aria-label="Αναζήτηση πελάτη πίστωσης"]').placeholder,/ονόματος/);
  await click(document.querySelector('[aria-label="Κλείσιμο επιλογής πελάτη"]'));
  const search=document.querySelector('input[placeholder="Barcode, SKU ή αναζήτηση προϊόντος"]');
  await act(async()=>{Object.getOwnPropertyDescriptor(dom.window.HTMLInputElement.prototype,'value').set.call(search,'NO_FIXTURE_CODE');search.dispatchEvent(new dom.window.Event('input',{bubbles:true}));});
  await act(async()=>{search.dispatchEvent(new dom.window.KeyboardEvent('keydown',{key:'Enter',bubbles:true}));await new Promise(r=>setTimeout(r,10));});
  await render({...denied,onlineBarcode:true});assert.ok(find('Online αναζήτηση'));
  await render(denied);assert.equal(find('Online αναζήτηση'),undefined);
  const priceCalls=()=>calls.filter(c=>c.path.endsWith('/audit')&&JSON.parse(c.options.body||'{}').actionType==='PRICE_CHANGE');
  await render(denied);const deniedPrice=document.querySelector('.line-price-action');assert.equal(deniedPrice.disabled,true);await click(deniedPrice);assert.equal(document.querySelector('.pos-price-modal'),null);assert.equal(priceCalls().length,0);
  const priceRights={...denied,changeRetail:true};
  await render(priceRights);await click(document.querySelector('.line-price-action'));assert.ok(document.querySelector('.pos-price-modal'));
  await render(denied);assert.equal(document.querySelector('.pos-price-modal'),null);assert.equal(document.querySelector('.standard-lines').textContent,cart);
  await render(priceRights);await click(document.querySelector('.line-price-action'));await click(find('-0,50 €'));
  rejectPrice=true;await click(find('Εφαρμογή μόνο στη συναλλαγή'));assert.match(document.body.textContent,/PRICE_PERMISSION_REVOKED/);assert.ok(document.querySelector('.pos-price-modal'));assert.equal(document.querySelector('.standard-lines').textContent,cart);
  rejectPrice=false;let releasePrice;pendingPrice=new Promise(resolve=>{releasePrice=resolve});const beforePrice=priceCalls().length;
  await click(find('Εφαρμογή μόνο στη συναλλαγή'));assert.equal(find('Εφαρμογή μόνο στη συναλλαγή').disabled,true);assert.equal(document.querySelector('.standard-lines').textContent,cart);
  await click(find('Εφαρμογή μόνο στη συναλλαγή'));assert.equal(priceCalls().length,beforePrice+1);
  await render(denied);assert.equal(document.querySelector('.pos-price-modal'),null);
  await act(async()=>{releasePrice();await new Promise(r=>setTimeout(r,15))});pendingPrice=null;
  assert.equal(document.querySelector('.standard-lines').textContent,cart);
  await render(priceRights);await click(document.querySelector('.line-price-action'));await click(find('-0,50 €'));await click(find('Εφαρμογή μόνο στη συναλλαγή'));
  assert.equal(document.querySelector('.pos-price-modal'),null);assert.match(document.querySelector('.line-price-action').textContent,/1,50/);
  const changedPrice=JSON.parse(priceCalls().at(-1).options.body);assert.equal(changedPrice.details.oldPrice,2);assert.equal(changedPrice.details.newPrice,1.5);assert.equal(changedPrice.details.scope,'CURRENT_TRANSACTION');
  await render(priceRights);await click(document.querySelector('.line-price-action'));await click([...document.querySelectorAll('.pos-price-modal button')].find(b=>b.textContent==='ΚΑΘΑΡΙΣΜΟΣ'));await click([...document.querySelectorAll('.pos-price-modal button')].find(b=>b.textContent==='2'));await click(find('Εφαρμογή μόνο στη συναλλαγή'));
  await render(denied);assert.equal(document.querySelector('.store-pos-top'),panel);assert.equal(document.querySelector('.standard-lines').textContent,cart);
  await click(find('ΑΚΥΡΩΣΗ'));assert.equal(confirmations,2);assert.equal(reasons,0);assert.match(document.querySelector('.standard-lines').textContent,/Νέα συναλλαγή/);
  assert.equal(calls.filter(c=>c.path==='/api/store-pos/stores/A').length,1);
  const paymentRights={...denied,thirdPartyPayment:true,supplierPayment:true,sameShiftPayments:true};
  await render(paymentRights);await click(find('ΠΛΗΡΩΜΕΣ'));
  const paymentModal=document.querySelector('.pos-standard-modal');
  assert.ok(find('Λοιπά έξοδα'));assert.ok(find('Πληρωμές προμηθευτών – Ετεροχρονισμένες'));
  await click(paymentModal.querySelector('.pos-inline-keypad button'));
  const amount=()=>[...paymentModal.querySelectorAll('label')].find(l=>l.textContent==='Ποσό').querySelector('input').value;
  assert.equal(amount(),'7');
  await render({...paymentRights,thirdPartyPayment:false});
  assert.equal(find('Λοιπά έξοδα'),undefined);assert.ok(find('Πληρωμές προμηθευτών – Ετεροχρονισμένες'));
  assert.equal(document.querySelector('.pos-standard-modal'),paymentModal);
  await render({...paymentRights,supplierPayment:false,sameShiftPayments:false});
  assert.ok(find('Λοιπά έξοδα'));assert.equal(find('Πληρωμές προμηθευτών – Ετεροχρονισμένες'),undefined);
  assert.equal(find('Μετρητά από ενεργή βάρδια').disabled,true);assert.equal(amount(),'7');
  await render({...paymentRights,thirdPartyPayment:false,supplierPayment:false});
  assert.match(paymentModal.textContent,/Δεν έχεις ενεργό δικαίωμα πληρωμών/);
  assert.equal(find('Καταχώριση εξόδου'),undefined);
  await render(paymentRights);assert.ok(find('Λοιπά έξοδα'));assert.ok(find('Πληρωμές προμηθευτών – Ετεροχρονισμένες'));
  assert.equal(find('Μετρητά από ενεργή βάρδια').disabled,false);assert.equal(amount(),'7');
  assert.equal(calls.filter(c=>c.path==='/api/store-pos/stores/A/access').length,1);
  assert.equal(calls.some(c=>c.options.method&&c.options.method!=='GET'&&!/\/(audit|audience-selection)$/.test(c.path)),false);
  await click(paymentModal.querySelector('header button'));

  const cancelCalls=()=>calls.filter(c=>c.path.endsWith('/audit')&&JSON.parse(c.options.body||'{}').actionType==='CART_CANCEL');
  const reasonRights={...denied,deleteSaleReason:true};
  for(const reason of ['Λάθος χειριστή','Έλεγχος τιμών','Ακύρωση από πελάτη']){
   await render(reasonRights);await click(document.querySelector('.standard-quick button:not([disabled])'));
   const before=cancelCalls().length;await click(find('ΑΚΥΡΩΣΗ'));
   const dialog=document.querySelector('[aria-labelledby="pos-cancel-reasons-title"]');assert.ok(dialog);assert.equal(dialog.querySelector('input,textarea,select'),null);
   assert.deepEqual([...dialog.querySelectorAll('.pos-cancel-reason-choices button')].map(b=>b.textContent),['Λάθος χειριστή','Έλεγχος τιμών','Ακύρωση από πελάτη']);
   assert.equal(document.activeElement.textContent,'Επιστροφή στο καλάθι');
   await click(find(reason));assert.equal(cancelCalls().length,before+1);
   const last=cancelCalls().at(-1);assert.equal(last.path,'/api/store-pos/stores/A/audit');
   assert.deepEqual(JSON.parse(last.options.body),{actionType:'CART_CANCEL',details:{items:[{productId:'p',name:'CONTROL',quantity:1,price:2}],total:2},reason});
   assert.match(document.querySelector('.standard-lines').textContent,/Νέα συναλλαγή/);
   assert.equal(document.activeElement,document.querySelector('[data-pos-scanner]'));
  }
  await click(document.querySelector('.standard-quick button:not([disabled])'));const retained=document.querySelector('.standard-lines').textContent;
  const beforeDismiss=cancelCalls().length;await click(find('ΑΚΥΡΩΣΗ'));
  await act(async()=>document.querySelector('[aria-labelledby="pos-cancel-reasons-title"]').dispatchEvent(new dom.window.KeyboardEvent('keydown',{key:'Escape',bubbles:true})));
  assert.equal(cancelCalls().length,beforeDismiss);assert.equal(document.querySelector('.standard-lines').textContent,retained);
  await click(find('ΑΚΥΡΩΣΗ'));await render(denied);assert.equal(document.querySelector('.pos-cancel-reasons'),null);assert.equal(cancelCalls().length,beforeDismiss);
  await render(reasonRights);rejectCancel=true;await click(find('ΑΚΥΡΩΣΗ'));await click(find('Λάθος χειριστή'));assert.match(document.body.textContent,/AUDIT_REJECTED/);assert.equal(document.querySelector('.standard-lines').textContent,retained);
  rejectCancel=false;let releaseCancel;pendingCancel=new Promise(resolve=>{releaseCancel=resolve});
  const beforePending=cancelCalls().length;await click(find('ΑΚΥΡΩΣΗ'));await click(find('Έλεγχος τιμών'));
  assert.equal(find('ΑΚΥΡΩΣΗ').disabled,true);assert.equal(document.querySelector('[data-pos-scanner]').disabled,true);assert.ok(document.querySelector('[aria-label="Καταγραφή ακύρωσης"]'));await click(find('ΑΚΥΡΩΣΗ'));assert.equal(cancelCalls().length,beforePending+1);assert.equal(document.querySelector('.standard-lines').textContent,retained);
  await act(async()=>{releaseCancel();await new Promise(r=>setTimeout(r,15))});pendingCancel=null;assert.match(document.querySelector('.standard-lines').textContent,/Νέα συναλλαγή/);
  assert.equal(reasons,0);
  assert.equal(calls.some(c=>/checkout|\/sales|finalize|sessions\/open/.test(c.path)),false);
 }finally{await act(async()=>root.unmount());dom.window.close();for(const[k,v]of previous){if(v)Object.defineProperty(globalThis,k,v);else delete globalThis[k]}}
});
