import test from "node:test";
import assert from "node:assert/strict";
import {createRequire} from "node:module";
import {fileURLToPath} from "node:url";

async function bundle(path){const {build}=await import("esbuild"),built=await build({stdin:{contents:`export {default} from "./${path}"`,resolveDir:fileURLToPath(new URL("../../",import.meta.url)),loader:"jsx"},bundle:true,write:false,format:"cjs",platform:"node",loader:{".css":"empty"},external:["react","react-dom","react-dom/client","react/jsx-runtime"]});const module={exports:{}};new Function("require","module","exports",built.outputFiles[0].text)(createRequire(import.meta.url),module,module.exports);return module.exports.default}
test("sales source renders escaped canonical amounts/period and never labels them as cash evidence",async()=>{
  const Panel=await bundle("client/src/components/voice/SalesAssistantEvidence.jsx"),React=await import("react"),{renderToStaticMarkup}=await import("react-dom/server");
  const e={kind:"product_sales",storeName:"Store",from:"2026-10-10",to:"2026-10-10",productQuery:"TEST1",result:"matched",rows:[{productId:"p",name:'<img src=x onerror="bad">',sku:"TEST1",salesQuantity:2,grossSales:1,netSales:0.88,vatValue:0.12,reversalCount:1,returnGrossValue:0.5}]};
  const html=renderToStaticMarkup(React.createElement(Panel,{evidence:[e]}));assert.match(html,/Ώρα Ελλάδας/);assert.match(html,/Τζίρος με ΦΠΑ/);assert.match(html,/TEST1/);assert.match(html,/&lt;img/);assert.doesNotMatch(html,/<img|Έλεγχος Ταμείων/);
  for(const result of ["ambiguous","no_match","source_limited"]){const out=renderToStaticMarkup(React.createElement(Panel,{evidence:[{...e,result,rows:[],candidates:[{name:"A",sku:"TEST2"}],truncated:result==="source_limited"}]}));assert.doesNotMatch(out,/<table/);if(result==="ambiguous")assert.match(out,/συγκεκριμένο SKU/);if(result==="source_limited")assert.match(out,/στενότερο φίλτρο/)}
});
test("mounted Owner panel clears answer on actual capability removal but keeps unchanged refresh",async()=>{
  const Panel=await bundle("client/src/components/voice/OwnerAssistantPanel.jsx"),{JSDOM}=await import("jsdom"),dom=new JSDOM('<div id="root"></div>',{url:"https://fixture.invalid"}),keys=["window","document","navigator","HTMLElement","Event","IS_REACT_ACT_ENVIRONMENT"],prior=new Map(keys.map(key=>[key,Object.getOwnPropertyDescriptor(globalThis,key)]));
  for(const key of keys)Object.defineProperty(globalThis,key,{configurable:true,writable:true,value:key==="IS_REACT_ACT_ENVIRONMENT"?true:dom.window[key]});
  let supported=["cash_details","sales_by_product"],posts=0;const scope={companyId:"c",storeId:"s",storeName:"Store"};
  const api=async(url,options={})=>{if(options.method==="POST"){posts++;return {scope,answer:"Sales fixture",highlights:[],limitations:"",evidence:[{kind:"product_sales",scope:"OWNER_SELECTED_STORE",companyId:"c",storeId:"s",storeName:"Store",from:"2026-10-10",to:"2026-10-10",productQuery:"TEST1",result:"no_match",rows:[]}]}}return{available:true,scope,supported}};
  let recording;class Recognition{constructor(){recording=this}start(){}abort(){}stop(){}};window.SpeechRecognition=Recognition;Object.defineProperty(window,"isSecureContext",{configurable:true,value:true});
  const React=await import("react"),{createRoot}=await import("react-dom/client"),{act}=React,root=createRoot(document.getElementById("root"));
  try{await act(async()=>root.render(React.createElement(Panel,{api,storeId:"s",storeName:"Store"})));await act(async()=>document.querySelector(".mws-voice-input-actions button").dispatchEvent(new window.MouseEvent("click",{bubbles:true})));await act(async()=>{recording.onstart();recording.onresult({results:[Object.assign([{transcript:"Πωλήσεις TEST1 10/10/2026;"}],{isFinal:true})]});recording.onend()});
    assert.equal(document.querySelector("textarea").value,"Πωλήσεις TEST1 10/10/2026;");await act(async()=>document.querySelector('button[type="submit"]').dispatchEvent(new window.MouseEvent("click",{bubbles:true})));assert.equal(posts,1);assert.match(document.body.textContent,/Sales fixture/);assert.ok(document.querySelector(".mws-sales-evidence"));assert.equal(document.querySelector(".mws-cash-evidence"),null);
    await act(async()=>window.dispatchEvent(new window.Event("myworkstation:modules-updated")));assert.match(document.body.textContent,/Sales fixture/);supported=["cash_details"];await act(async()=>window.dispatchEvent(new window.Event("myworkstation:modules-updated")));assert.equal(document.querySelector("textarea").value,"");assert.equal(document.querySelector('button[type="submit"]').disabled,true);assert.doesNotMatch(document.body.textContent,/Sales fixture/);assert.equal(posts,1);
  }finally{await act(async()=>root.unmount());dom.window.close();for(const [key,value] of prior)value?Object.defineProperty(globalThis,key,value):delete globalThis[key]}
});
test("actual report installer sends opt-in Athens filter, retains selected store and rejects late report",async()=>{
  const {build}=await import("esbuild"),{JSDOM}=await import("jsdom");const built=await build({entryPoints:[fileURLToPath(new URL("../../client/src/components/commerce/installKioskReportsSalesV4.js",import.meta.url))],bundle:true,write:false,format:"cjs",platform:"node"});const module={exports:{}};new Function("require","module","exports",built.outputFiles[0].text)(createRequire(import.meta.url),module,module.exports);
  const dom=new JSDOM('<div class="commerce-hub" data-report-store-id="s"><div class="kiosk-reports-suite" data-report-store-id="s"><button data-kr-tab="sales-stats">Sales</button><section class="kr-filter"><div><input data-kr-from value="2026-10-10"><input data-kr-to value="2026-10-10"><input data-kr-q value="TEST1"><select data-kr-store><option value="s">Store</option></select><button data-kr-search>Search</button></div></section><div class="kr-toolbar"></div></div></div>',{url:"https://fixture.invalid"});const keys=["window","document","localStorage","fetch"],prior=new Map(keys.map(key=>[key,Object.getOwnPropertyDescriptor(globalThis,key)]));for(const key of keys)if(key!=="fetch")Object.defineProperty(globalThis,key,{configurable:true,writable:true,value:dom.window[key]});
  const calls=[];let finish;globalThis.fetch=async url=>{calls.push(url);return{ok:true,json:async()=>new Promise(resolve=>finish=resolve)}};
  const tick=()=>new Promise(resolve=>setImmediate(resolve));
  try{module.exports.installKioskReportsSalesV4();document.querySelector("[data-kr-tab]").click();await tick();assert.equal(new URL(calls[0],"https://fixture.invalid").searchParams.get("timeZone"),null);finish({items:[],totalGross:0});await tick();const checkbox=document.querySelector("[data-kr-athens]");assert.ok(checkbox);checkbox.checked=true;document.querySelector("[data-kr-search]").click();await tick();const url=new URL(calls[1],"https://fixture.invalid");assert.equal(url.searchParams.get("timeZone"),"Europe/Athens");assert.equal(url.searchParams.get("storeId"),"s");assert.equal(url.searchParams.get("q"),"TEST1");document.querySelector(".commerce-hub").dataset.reportStoreId="other";finish({items:[{name:"STALE SECRET"}],totalGross:999});await tick();assert.doesNotMatch(document.body.textContent,/STALE SECRET|999/);
  }finally{dom.window.close();for(const [key,value] of prior)value?Object.defineProperty(globalThis,key,value):delete globalThis[key]}
});
