import test from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs";
import {createRequire} from "node:module";
const require=createRequire(import.meta.url),{Router}=require("express"),{z}=require("zod");
const source=fs.readFileSync(new URL("../src/routes/platform-pos-designer-fixed.js",import.meta.url),"utf8");
function harness(prisma){const code=source.replace(/^import .*;\n/gm,"").replace("export default router;","return router;");return new Function("Router","z","prisma","auth",code)(Router,z,prisma,(_q,_r,n)=>n());}
async function call(router,path,body={},method="post",query={}){const layer=router.stack.find(x=>x.route?.path===path&&x.route.methods[method]);assert.ok(layer);let result,error,status=200;const res={status(x){status=x;return this},json(x){result=x;return this}};await layer.route.stack[0].handle({body,query,user:{id:"super"},params:{}},res,e=>{error=e});return {result,error,status};}
const input={companyId:"company-A",quickKeys:[{productId:"water-id"}],categories:Array.from({length:14},(_,i)=>({label:"Category "+i,productIds:i===0?["beer-id"]:[]}))};
test("prepare uses company IDs and canonical product names without writes",async()=>{let values,writes=0;const router=harness({$queryRaw:async(_sql,...v)=>{values=v;return [{id:"water-id",name:"ΝΕΡΟ 500ML"},{id:"beer-id",name:"ΑΛΦΑ 330ML"}]},$transaction:async()=>writes++});const r=await call(router,"/prepare-company-layout",input);assert.equal(r.error,undefined);assert.equal(r.result.layout.catalogCompanyId,"company-A");assert.equal(r.result.layout.quickKeys.length,20);assert.equal(r.result.layout.quickKeys[0].productQuery,"water-id");assert.equal(r.result.layout.quickKeys[0].label,"ΝΕΡΟ 500ML");assert.deepEqual(r.result.layout.categories[0].productCodes,["beer-id"]);assert.equal(values[0],"company-A");assert.equal(writes,0);});
test("unknown, inactive or foreign IDs reject the whole import",async()=>{const router=harness({$queryRaw:async()=>[{id:"water-id",name:"Water"}]});const r=await call(router,"/prepare-company-layout",input);assert.equal(r.status,400);assert.ok(r.result.error);});
test("category limit is checked before reading products",async()=>{let reads=0;const router=harness({$queryRaw:async()=>{reads++;return []}});const body=structuredClone(input);body.categories[0].productIds=Array.from({length:41},(_,i)=>"id-"+i);const r=await call(router,"/prepare-company-layout",body);assert.equal(r.error?.name,"ZodError");assert.equal(reads,0);});
test("publication rejects another company before any transaction",async()=>{let writes=0;const router=harness({store:{findMany:async()=>[{id:"store-B",companyId:"company-B"}]},$queryRaw:async()=>[{layoutJson:{catalogCompanyId:"company-A"}}],$transaction:async()=>writes++});const r=await call(router,"/publish",{storeIds:["store-B"]});assert.match(r.error.message,/άλλης εταιρείας/);assert.equal(writes,0);});
test("legacy global layout still publishes only to explicit selected stores",async()=>{let target;const router=harness({store:{findMany:async()=>[{id:"selected",companyId:"company-B"}]},$queryRaw:async()=>[{layoutJson:{}}],$transaction:async f=>f({$executeRaw:async(_sql,...v)=>{target=v[0]}})});const r=await call(router,"/publish",{storeIds:["selected"]});assert.equal(r.error,undefined);assert.equal(r.result.publishedStores,1);assert.equal(target,"selected");});
test("company picker includes company scope and company ID as selected code",async()=>{let sql,values;const router=harness({$queryRaw:async(s,...v)=>{sql=s.join("?");values=v;return []}});const r=await call(router,"/company-products",{},"get",{companyId:"company-A",q:"332"});assert.equal(r.error,undefined);assert.match(sql,/p\."companyId"=\?/);assert.ok(values.includes("company-A"));assert.match(sql,/p\."id" AS "sourceCode"/);});
