import test from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs";
import {AUDIENCE_KEYS,normalizeAudienceSettings} from "../../shared/pos-audience-settings.mjs";
import {createRequire} from "node:module";
const require=createRequire(import.meta.url),{Router}=require("express"),{z}=require("zod");
const source=fs.readFileSync(new URL("../src/routes/platform-pos-designer-fixed.js",import.meta.url),"utf8");
function harness(prisma){const code=source.replace(/^import .*;\n/gm,"").replace("export default router;","return router;");return new Function("Router","z","prisma","auth","AUDIENCE_KEYS","normalizeAudienceSettings",code)(Router,z,prisma,(_q,_r,n)=>n(),AUDIENCE_KEYS,normalizeAudienceSettings);}
async function call(router,path,body={},method="post",query={}){const layer=router.stack.find(x=>x.route?.path===path&&x.route.methods[method]);assert.ok(layer);let result,error,status=200;const res={status(x){status=x;return this},json(x){result=x;return this}};await layer.route.stack[0].handle({body,query,user:{id:"super"},params:{}},res,e=>{error=e});return {result,error,status};}
const input={companyId:"company-A",quickKeys:[{productId:"water-id"}],categories:Array.from({length:14},(_,i)=>({label:"Category "+i,productIds:i===0?["beer-id"]:[]}))};
test("prepare uses company IDs and canonical product names without writes",async()=>{let values,writes=0;const router=harness({$queryRaw:async(_sql,...v)=>{values=v;return [{id:"water-id",name:"ΝΕΡΟ 500ML"},{id:"beer-id",name:"ΑΛΦΑ 330ML"}]},$transaction:async()=>writes++});const r=await call(router,"/prepare-company-layout",input);assert.equal(r.error,undefined);assert.equal(r.result.layout.catalogCompanyId,"company-A");assert.equal(r.result.layout.quickKeys.length,20);assert.equal(r.result.layout.quickKeys[0].productQuery,"water-id");assert.equal(r.result.layout.quickKeys[0].label,"ΝΕΡΟ 500ML");assert.deepEqual(r.result.layout.categories[0].productCodes,["beer-id"]);assert.equal(values[0],"company-A");assert.equal(writes,0);});
test("unknown, inactive or foreign IDs reject the whole import",async()=>{const router=harness({$queryRaw:async()=>[{id:"water-id",name:"Water"}]});const r=await call(router,"/prepare-company-layout",input);assert.equal(r.status,400);assert.ok(r.result.error);});
test("category limit is checked before reading products",async()=>{let reads=0;const router=harness({$queryRaw:async()=>{reads++;return []}});const body=structuredClone(input);body.categories[0].productIds=Array.from({length:41},(_,i)=>"id-"+i);const r=await call(router,"/prepare-company-layout",body);assert.equal(r.error?.name,"ZodError");assert.equal(reads,0);});
test("publication rejects another company before any transaction",async()=>{let writes=0;const router=harness({store:{findMany:async()=>[{id:"store-B",companyId:"company-B"}]},$queryRaw:async()=>[{layoutJson:{catalogCompanyId:"company-A"}}],$transaction:async()=>writes++});const r=await call(router,"/publish",{storeIds:["store-B"]});assert.match(r.error.message,/άλλης εταιρείας/);assert.equal(writes,0);});
test("legacy global layout still publishes only to explicit selected stores",async()=>{let target;const router=harness({store:{findMany:async()=>[{id:"selected",companyId:"company-B"}]},$queryRaw:async()=>[{layoutJson:{}}],$transaction:async f=>f({$executeRaw:async(_sql,...v)=>{target=v[0]}})});const r=await call(router,"/publish",{storeIds:["selected"]});assert.equal(r.error,undefined);assert.equal(r.result.publishedStores,1);assert.equal(target,"selected");});
test("company picker includes company scope and company ID as selected code",async()=>{let sql,values;const router=harness({$queryRaw:async(s,...v)=>{sql=s.join("?");values=v;return []}});const r=await call(router,"/company-products",{},"get",{companyId:"company-A",q:"332"});assert.equal(r.error,undefined);assert.match(sql,/p\."companyId"=\?/);assert.ok(values.includes("company-A"));assert.match(sql,/p\."id" AS "sourceCode"/);});

test("DAILY BITE screenshot preset resolves exact normalized company products without writes",async()=>{let reads=0,writes=0;const router=harness({$queryRaw:async()=>{reads++;if(reads===1)return[{id:"company-A",name:"DAILY BITE E E"}];return[{id:"p1",name:"ΜΠΑΛΑ ΠΟΔΟΣΦΑΙΡΟΥ"},{id:"p2",name:"ΜΠΑΛΑ ΒΟΛΕΥ"},{id:"p3",name:"ΜΠΑΛΑ ΜΙΚΡΗ"}]},$transaction:async()=>writes++});const r=await call(router,"/prepare-daily-bite-layout",{companyId:"company-A"});assert.equal(r.error,undefined);assert.equal(r.result.layout.catalogCompanyId,"company-A");assert.equal(r.result.layout.title,"DAILY BITE POS");assert.equal(r.result.layout.categories.length,14);assert.deepEqual(r.result.layout.categories[6].productCodes,["p1","p2","p3"]);assert.equal(r.result.layout.theme.accentColor,"#087a52");assert.equal(writes,0);assert.ok(r.result.missingProducts.length>0);});
test("DAILY BITE preset refuses another company before catalog read",async()=>{let reads=0;const router=harness({$queryRaw:async()=>{reads++;return[{id:"company-A",name:"OTHER COMPANY"}]}});const r=await call(router,"/prepare-daily-bite-layout",{companyId:"company-A"});assert.equal(r.status,400);assert.equal(reads,1);});

test("DAILY BITE coffee preview is read-only and pairs only unique coffee signatures",async()=>{let n=0,writes=0;const router=harness({$queryRaw:async()=>{n++;if(n===1)return[{id:"daily",name:"DAILY BITE E E"}];if(n===2)return[{id:"kat-store",companyId:"kat",name:"ΚΥΛΙΚΕΙΟ ΚΑΤ"}];if(n===3)return[{id:"k1",sku:"MWS-KAT-BEV-1",name:"FREDDO ESPRESSO"}];if(n===4)return[{id:"d1",sku:"DB1",name:"Freddo Espresso"}];if(n===5)return[{description:"ΖΑΧΑΡΗ",legacyId:1,sequence:10,modifierDescription:"ΣΚΕΤΟΣ",price:0}];return[]},$transaction:async()=>writes++});const r=await call(router,"/daily-bite-coffee-preview",{},"get",{companyId:"daily"});assert.equal(r.error,undefined);assert.equal(r.result.matched.length,1);assert.equal(r.result.matched[0].daily.id,"d1");assert.equal(r.result.katModifierGroups[0].description,"ΖΑΧΑΡΗ");assert.equal(r.result.mutated,false);assert.equal(writes,0);});
test("DAILY BITE coffee preview rejects another target company before KAT reads",async()=>{let reads=0;const router=harness({$queryRaw:async()=>{reads++;return[{id:"x",name:"OTHER"}]}});const r=await call(router,"/daily-bite-coffee-preview",{},"get",{companyId:"x"});assert.equal(r.status,400);assert.equal(reads,1);});

test("DAILY BITE coffee apply fails closed before writes when pair set is incomplete",async()=>{let reads=0,writes=0;const router=harness({$queryRaw:async()=>{reads++;if(reads===1)return[{id:"daily",name:"DAILY BITE E E"}];if(reads===2)return[{id:"kat-store",companyId:"kat",name:"ΚΥΛΙΚΕΙΟ ΚΑΤ"}];if(reads===3)return[{id:"k1",sku:"MWS-KAT-BEV-1",name:"FREDDO ESPRESSO"}];if(reads===4)return[];return[]},$transaction:async()=>writes++});const r=await call(router,"/daily-bite-coffee-apply",{companyId:"daily",confirm:"DAILY_BITE_COFFEE",renameProducts:true});assert.equal(r.status,409);assert.equal(writes,0);assert.match(r.result.error,/αμφίσημες|ελλιπείς/);});
test("DAILY BITE coffee apply requires explicit confirmation before reads",async()=>{let reads=0;const router=harness({$queryRaw:async()=>{reads++;return[]}});const r=await call(router,"/daily-bite-coffee-apply",{companyId:"daily",confirm:"NOPE"});assert.equal(r.status,400);assert.equal(reads,0);});
