import test from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs";

test("store chat foundation has store isolation, categories and server-side storage",()=>{
  const route=fs.readFileSync(new URL("../src/routes/store-chat.js",import.meta.url),"utf8");
  const push=fs.readFileSync(new URL("../src/store-chat-push.js",import.meta.url),"utf8");
  const panel=fs.readFileSync(new URL("../../client/src/components/store/StoreChatPanel.jsx",import.meta.url),"utf8");
  const pos=fs.readFileSync(new URL("../../client/src/components/store/StorePosPanel.jsx",import.meta.url),"utf8");
  const worker=fs.readFileSync(new URL("../../client/public/sw.js",import.meta.url),"utf8");
  const owner=fs.readFileSync(new URL("../../client/src/main.jsx",import.meta.url),"utf8");
  const platform=fs.readFileSync(new URL("../../client/src/components/platform/PlatformAdminApp.jsx",import.meta.url),"utf8");
  assert.match(route,/StoreChatMessage/);
  assert.match(route,/LEFT JOIN "StoreOperatorCredential"/);
  assert.match(route,/AS "senderName"/);
  assert.match(route,/LEFT JOIN "User" su/);
  assert.match(route,/LEFT JOIN "StoreOperatorCredential" so/);
  assert.match(route,/o\."displayName"/);
  assert.match(route,/m\."companyId"=\$\{store\.companyId\}/);
  assert.match(route,/AS "readByMe"/);
  assert.match(route,/ORDER BY "readByMe" ASC/);
  assert.match(route,/m\."pinned" DESC/);
  assert.match(route,/function canPin/);
  assert.match(route,/STORE_CHAT_ANNOUNCEMENT_PINNED/);
  assert.match(route,/found\[0\]\.category!=="ANNOUNCEMENT"/);
  assert.match(route,/STORE_OPERATOR/);
  assert.match(route,/STORE_CHAT_MESSAGE_SENT/);
  assert.match(route,/STORE_CHAT_ATTACHMENT_OPENED/);
  assert.match(route,/STORE_CHAT_ATTACHMENT_DOWNLOADED/);
  assert.match(route,/STORE_CHAT_MESSAGE_COMPLETED/);
  assert.match(route,/STORE_CHAT_MESSAGE_REOPENED/);
  assert.match(route,/"completedBy"/);
  assert.match(route,/"completedAt"/);
  assert.match(route,/canComplete:canPin/);
  assert.match(route,/StoreChatTask/);
  assert.match(route,/StoreChatSettings/);
  assert.match(route,/StoreChatAcknowledgement/);
  assert.match(route,/ensureStoreChatPushSchema/);
  assert.match(route,/push-subscription/);
  assert.match(route,/sendStoreChatPush/);
  assert.match(route,/invoiceAiReaderEnabled/);
  assert.match(route,/announcementAcknowledgementRequired/);
  assert.match(route,/"photosEnabled" BOOLEAN NOT NULL DEFAULT true/);
  assert.match(route,/"pdfEnabled" BOOLEAN NOT NULL DEFAULT true/);
  assert.match(route,/"downloadsEnabled" BOOLEAN NOT NULL DEFAULT true/);
  assert.match(route,/"employeeDownloadsEnabled" BOOLEAN NOT NULL DEFAULT false/);
  assert.match(route,/"employeeTaskCreationEnabled" BOOLEAN NOT NULL DEFAULT true/);
  assert.match(route,/STORE_CHAT_PHOTOS_ENABLED/);
  assert.match(route,/STORE_CHAT_PHOTOS_DISABLED/);
  assert.match(route,/STORE_CHAT_PDF_ENABLED/);
  assert.match(route,/STORE_CHAT_PDF_DISABLED/);
  assert.match(route,/STORE_CHAT_DOWNLOADS_ENABLED/);
  assert.match(route,/STORE_CHAT_DOWNLOADS_DISABLED/);
  assert.match(route,/STORE_CHAT_EMPLOYEE_DOWNLOADS_ENABLED/);
  assert.match(route,/STORE_CHAT_EMPLOYEE_DOWNLOADS_DISABLED/);
  assert.match(route,/STORE_CHAT_EMPLOYEE_TASK_CREATION_ENABLED/);
  assert.match(route,/STORE_CHAT_EMPLOYEE_TASK_CREATION_DISABLED/);
  assert.match(route,/if\(isPlatformSuperAdmin\(user\)\)return true/);
  assert.match(route,/if\(!settings\.downloadsEnabled\)return false/);
  assert.match(route,/if\(user\?\.tokenType==="STORE_OPERATOR"\)return settings\.employeeDownloadsEnabled/);
  assert.match(route,/attachment\?\.mimeType\.startsWith\("image\/"\)&&!settings\.photosEnabled/);
  assert.match(route,/attachment\?\.mimeType==="application\/pdf"&&!settings\.pdfEnabled/);
  assert.match(route,/STORE_CHAT_ANNOUNCEMENT_ACK_REQUIRED/);
  assert.match(route,/STORE_CHAT_ANNOUNCEMENT_ACK_DISABLED/);
  assert.match(route,/STORE_CHAT_ANNOUNCEMENT_ACKNOWLEDGED/);
  assert.match(route,/CHAT_ANNOUNCEMENT_ACK_DISABLED/);
  assert.match(route,/found\[0\]\.category!=="ANNOUNCEMENT"/);
  assert.match(route,/ON CONFLICT \("messageId","userId"\) DO NOTHING/);
  assert.match(route,/STORE_CHAT_INVOICE_AI_READER_ENABLED/);
  assert.match(route,/STORE_CHAT_INVOICE_AI_READER_DISABLED/);
  assert.match(route,/STORE_CHAT_INVOICE_SENT_TO_AI_READER/);
  assert.match(route,/CHAT_AI_READER_DISABLED/);
  assert.match(route,/message\.category!=="INVOICE"/);
  assert.match(route,/"aiReaderJobId"/);
  assert.match(route,/stockChanged:false/);
  assert.match(route,/STORE_CHAT_TASK_CREATED/);
  assert.match(route,/ON CONFLICT \("messageId"\) DO NOTHING/);
  assert.match(route,/canCreateTask:canCreateTask\(req\.user,settings\)/);
  assert.match(route,/if\(!canCreateTask\(req\.user,settings\)\)return res\.status\(403\)/);
  assert.match(route,/canManageTask:canPin\(req\.user\)/);
  assert.match(route,/STORE_CHAT_TASK_COMPLETED/);
  assert.match(route,/STORE_CHAT_TASK_REOPENED/);
  assert.match(route,/tasks\/:taskId/);
  assert.match(route,/Cache-Control","no-store/);
  assert.match(route,/MAX_ATTACHMENT_BYTES=7\*1024\*1024/);
  assert.match(route,/download&&!canDownload/);
  assert.match(route,/"attachmentData" IS NOT NULL/);
  assert.match(route,/STOCK_SHORTAGE/);
  assert.match(panel,/const openMessage=/);
  assert.match(panel,/row\.readByMe/);
  assert.match(panel,/ΝΕΟ/);
  assert.match(panel,/permissions\.canPin/);
  assert.match(panel,/permissions\.canDownload/);
  assert.match(panel,/Φωτογραφία \/ PDF/);
  assert.match(panel,/Από: \{row\.senderName/);
  assert.match(panel,/Φίλτρο ημερομηνίας/);
  assert.match(panel,/Όλοι οι αποστολείς/);
  assert.match(panel,/setSenderFilter/);
  assert.match(panel,/permissions\.canComplete/);
  assert.match(panel,/Ολοκληρώθηκε από:/);
  assert.match(panel,/JSON\.stringify\(\{completed:!row\.completed\}\)/);
  assert.match(panel,/Δημιουργία εκκρεμότητας/);
  assert.match(panel,/Κλείσιμο εκκρεμότητας/);
  assert.match(panel,/Επαναφορά εκκρεμότητας/);
  assert.match(panel,/taskCompletedByName/);
  assert.match(panel,/AI Reader: \{settings\.invoiceAiReaderEnabled\?"Ενεργό":"Ανενεργό"\}/);
  assert.match(panel,/Αποστολή στο AI Reader/);
  assert.match(panel,/Στάλθηκε στο AI Reader από:/);
  assert.match(panel,/Επιβεβαίωση: \{settings\.announcementAcknowledgementRequired\?"Ενεργή":"Ανενεργή"\}/);
  assert.match(panel,/Επιβεβαίωση ανάγνωσης/);
  assert.match(panel,/Επιβεβαίωσαν:/);
  assert.match(panel,/Φωτογραφίες: \{settings\.photosEnabled\?"Ενεργές":"Ανενεργές"\}/);
  assert.match(panel,/PDF: \{settings\.pdfEnabled\?"Ενεργά":"Ανενεργά"\}/);
  assert.match(panel,/Αρχεία ανενεργά/);
  assert.match(panel,/Λήψεις: \{settings\.downloadsEnabled\?"Ενεργές":"Ανενεργές"\}/);
  assert.match(panel,/Υπάλληλοι: \{settings\.employeeDownloadsEnabled&&settings\.downloadsEnabled\?"Λήψη επιτρέπεται":"Λήψη απαγορεύεται"\}/);
  assert.match(panel,/Εκκρεμότητες υπαλλήλων: \{settings\.employeeTaskCreationEnabled\?"Επιτρέπονται":"Απαγορεύονται"\}/);
  assert.match(panel,/Εκκρεμότητες \(\{taskCount\}\)/);
  assert.match(panel,/store-chat-category/);
  assert.match(panel,/cache:"no-store"/);
  assert.match(panel,/pdfjs-dist\/legacy\/build\/pdf\.mjs/);
  assert.match(panel,/pushManager\.subscribe/);
  assert.match(panel,/Ενεργοποίηση Push/);
  assert.match(panel,/navigator\.serviceWorker\.ready/);
  assert.match(panel,/registration\.update\(\)/);
  assert.match(panel,/subscription\?"granted":"unknown"/);
  assert.match(panel,/Το κινητό δεν συνδέθηκε με την υπηρεσία Push του Android/);
  assert.match(worker,/visibilityState==="visible"/);
  assert.match(worker,/STORE_CHAT_PUSH/);
  assert.match(pos,/store-chat-in-app-alert/);
  assert.match(pos,/playChatAlert/);
  assert.match(pos,/setChatOpen\(true\)/);
  assert.match(push,/StoreChatPushSubscription/);
  assert.match(push,/generateVAPIDKeys/);
  assert.match(push,/"storeId"=\$\{store\.id\}/);
  assert.match(push,/"userId"<>\$\{senderId\}/);
  assert.doesNotMatch(panel,/<iframe/);
  assert.doesNotMatch(panel,/localStorage\.setItem\([^)]*attachment/);
  assert.match(panel,/ΚΑΡΦΙΤΣΩΜΕΝΗ/);
  assert.doesNotMatch(panel,/Promise\.allSettled\(nextRows\.map/);
  assert.match(owner,/activeModules\.includes\("STORE_CHAT"\)/);
  assert.match(owner,/Chat ανά κατάστημα/);
  assert.match(owner,/<StoreChatPanel api=\{api\}/);
  assert.match(platform,/<StoreChatPanel api=\{request\}/);
  assert.match(platform,/setShowChatChooser\(true\)/);
  assert.match(platform,/Επίλεξε κατάστημα…/);
  assert.doesNotMatch(platform,/platform-chat-launchers/);
});
