import test from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs";

test("store chat foundation has store isolation, categories and server-side storage",()=>{
  const route=fs.readFileSync(new URL("../src/routes/store-chat.js",import.meta.url),"utf8");
  const panel=fs.readFileSync(new URL("../../client/src/components/store/StoreChatPanel.jsx",import.meta.url),"utf8");
  const owner=fs.readFileSync(new URL("../../client/src/main.jsx",import.meta.url),"utf8");
  const platform=fs.readFileSync(new URL("../../client/src/components/platform/PlatformAdminApp.jsx",import.meta.url),"utf8");
  assert.match(route,/StoreChatMessage/);
  assert.match(route,/LEFT JOIN "StoreOperatorCredential"/);
  assert.match(route,/o\."displayName"/);
  assert.match(route,/m\."companyId"=\$\{store\.companyId\}/);
  assert.match(route,/AS "readByMe"/);
  assert.match(route,/ORDER BY "readByMe" ASC/);
  assert.match(route,/m\."pinned" DESC/);
  assert.match(route,/function canPin/);
  assert.match(route,/STORE_CHAT_ANNOUNCEMENT_PINNED/);
  assert.match(route,/found\[0\]\.category!=="ANNOUNCEMENT"/);
  assert.match(route,/STORE_OPERATOR/);
  assert.match(route,/STORE_CHAT_MESSAGE_SENT/);
  assert.match(route,/STORE_CHAT_ATTACHMENT_OPENED/);
  assert.match(route,/STORE_CHAT_ATTACHMENT_DOWNLOADED/);
  assert.match(route,/Cache-Control","no-store/);
  assert.match(route,/MAX_ATTACHMENT_BYTES=7\*1024\*1024/);
  assert.match(route,/download&&!canDownload/);
  assert.match(route,/"attachmentData" IS NOT NULL/);
  assert.match(route,/STOCK_SHORTAGE/);
  assert.match(panel,/const openMessage=/);
  assert.match(panel,/row\.readByMe/);
  assert.match(panel,/ΝΕΟ/);
  assert.match(panel,/permissions\.canPin/);
  assert.match(panel,/permissions\.canDownload/);
  assert.match(panel,/Φωτογραφία \/ PDF/);
  assert.match(panel,/cache:"no-store"/);
  assert.match(panel,/pdfjs-dist\/legacy\/build\/pdf\.mjs/);
  assert.doesNotMatch(panel,/<iframe/);
  assert.doesNotMatch(panel,/localStorage\.setItem\([^)]*attachment/);
  assert.match(panel,/ΚΑΡΦΙΤΣΩΜΕΝΗ/);
  assert.doesNotMatch(panel,/Promise\.allSettled\(nextRows\.map/);
  assert.match(owner,/activeModules\.includes\("STORE_CHAT"\)/);
  assert.match(owner,/Chat ανά κατάστημα/);
  assert.match(owner,/<StoreChatPanel api=\{api\}/);
  assert.match(platform,/<StoreChatPanel api=\{request\}/);
  assert.match(platform,/setShowChatChooser\(true\)/);
  assert.match(platform,/Επίλεξε κατάστημα…/);
  assert.doesNotMatch(platform,/platform-chat-launchers/);
});
