import test from "node:test";
import assert from "node:assert/strict";
import {readFile} from "node:fs/promises";
const route=await readFile(new URL("../src/routes/platform-super-admin-analytics-details.js",import.meta.url),"utf8");
const ui=await readFile(new URL("../../client/src/components/platform/SuperAdminChecksAnalytics.jsx",import.meta.url),"utf8");
test("PREMIUM controls are gated, read-only and reconcile only inside one closed shift",()=>{
  assert.match(route,/premium:level>=CHECK_PACKAGE_LEVELS\.PREMIUM_CHECK/);
  assert.match(route,/async function premiumVarianceControls/);
  assert.match(route,/scope:"PER_CLOSED_SHIFT_ONLY"/);
  assert.match(route,/t\."sessionId"=sh\."id"/);
  assert.match(route,/basketSignature/);
  assert.match(route,/POTENTIAL_PAYMENT_SWITCH_DUPLICATE/);
  assert.match(route,/premiumDuplicateWindowSeconds=40/);
  assert.match(route,/premiumDuplicateMaxTransactionDistance=2/);
  assert.match(route,/seconds>premiumDuplicateWindowSeconds/);
  assert.match(route,/distance<=premiumDuplicateMaxTransactionDistance/);
  assert.match(route,/POTENTIAL_REPEATED_REVERSAL/);
  assert.match(route,/PosOperationalEvent/);
  assert.match(route,/auditSales/);
  assert.match(route,/saleEvidenceById/);
  assert.match(route,/itemsJson/);
  assert.match(route,/readOnly:true/);
  assert.match(route,/FINAL_RECONCILED/);
  assert.match(route,/SHIFT_HANDOVER_DIFFERENCE/);
  assert.match(ui,/PREMIUM · Τελικό αποτέλεσμα ανά βάρδια/);
  assert.match(ui,/Έγκριση τελικού αποτελέσματος/);
  assert.match(ui,/Εσύ εγκρίνεις το τελικό αποτέλεσμα/);
  assert.match(ui,/\{!premium\.enabled&&<section className="platform-panel"/);
  assert.match(ui,/Βάρδιες με τελικό αποτέλεσμα/);
  assert.match(ui,/Λειτουργικό συμβάν/);
});
