import React,{useEffect,useState} from "react";
import {CheckCircle2,RefreshCw,Upload,X} from "lucide-react";
const eur=v=>Number(v||0).toLocaleString("el-GR",{style:"currency",currency:"EUR"});
const num=v=>Number(String(v||"0").replace(",","."))||0;
const read=file=>new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(reader.result);reader.onerror=reject;reader.readAsDataURL(file)});
export default function BankLedgerReviewCenter({request,onClose,setMessage}){
 const [items,setItems]=useState([]),[proofAmounts,setProofAmounts]=useState({}),[summary,setSummary]=useState({items:[],totals:{availableBalance:0,pendingAmount:0,projectedBalance:0}}),[busy,setBusy]=useState(""),[error,setError]=useState("");
 const load=async()=>{setBusy("load");try{const [review,report]=await Promise.all([request("/api/transactions/bank-ledger/review"),request("/api/transactions/bank-ledger/summary")]);setItems(review.items||[]);setSummary(report||{items:[],totals:{availableBalance:0,pendingAmount:0,projectedBalance:0}})}catch(e){setError(e.message)}finally{setBusy("")}};
 useEffect(()=>{load()},[]); const review=async(item,status)=>{const note=window.prompt(status==="CONFIRMED"?"Σημείωση επιβεβαίωσης":"Αιτιολογία απόκλισης/ακύρωσης");if(!note||note.trim().length<3)return;setBusy(item.id);try{await request(`/api/transactions/bank-ledger/${item.id}/review`,{method:"POST",body:JSON.stringify({status,note:note.trim()})});setItems(rows=>rows.filter(row=>row.id!==item.id));setMessage?.("Η τραπεζική κίνηση ενημερώθηκε.")}catch(e){setError(e.message)}finally{setBusy("")}};
 const uploadProof=async(item,file)=>{if(!file)return;setBusy(`proof-${item.id}`);setError("");try{const result=await request(`/api/transactions/bank-ledger/${item.id}/attachment`,{method:"POST",body:JSON.stringify({attachment:{dataUrl:await read(file),filename:file.name},proofAmount:num(proofAmounts[item.id])||Number(item.amount)})});setMessage?.(result.status==="CONFIRMED"?"Η απόδειξη αντιστοιχίστηκε αυτόματα.":`Καταγράφηκε απόκλιση ${eur(result.difference)}.`);await load()}catch(e){setError(e.message)}finally{setBusy("")}};
 return <div className="platform-modal"><section className="sa-modal"><header><div><span>SUPER ADMIN ONLY</span><h2>Έλεγχος Ταμείου Τράπεζας</h2><p>Η επιβεβαίωση ενημερώνει μόνο το τραπεζικό ledger. Το ταμείο βάρδιας δεν αλλάζει δεύτερη φορά.</p></div><button className="sa-close" onClick={onClose}><X/></button></header>{error&&<div className="platform-alert error">{error}</div>}<section className="platform-panel" style={{marginBottom:14}}><b>Εικονικό Ταμείο Τράπεζας</b><p>Υπάρχει ένα ενιαίο λογιστικό ταμείο ανά κατάστημα. Δεν συνδέεται με τράπεζα, IBAN ή online banking.</p></section><section className="platform-panel" style={{marginBottom:14}}><b>Σύνοψη Ταμείου Τράπεζας</b><p>Λογιστικό υπόλοιπο: {eur(summary.totals?.projectedBalance)} · Επιβεβαιωμένο: {eur(summary.totals?.availableBalance)} · Σε αναμονή: {eur(summary.totals?.pendingAmount)}</p>{(summary.items||[]).map(row=><small key={row.bankAccountId} style={{display:"block"}}>{row.companyName} · {row.storeName} · {row.bankName} / {row.accountName}: Λογιστικό {eur(row.projectedBalance)} · Επιβεβαιωμένα {eur(row.availableBalance)} · Σε αναμονή {eur(row.pendingAmount)}</small>)}</section><div className="sa-actions"><button onClick={load} disabled={busy==="load"}><RefreshCw/>Ανανέωση</button></div>{items.length?items.map(item=><article key={item.id} className="platform-panel" style={{marginBottom:10}}><b>{item.companyName} · {item.storeName}</b><p>{item.bankName} · {item.accountName} · {item.type} · {eur(item.amount)}</p><small>{new Date(item.occurredAt).toLocaleString("el-GR")} · {item.createdByName} · {item.attachmentFilename||"Χωρίς απόδειξη"}{item.proofAmount!=null&&Math.abs(Number(item.proofAmount)-Number(item.amount))>.005?` · Απόκλιση ${eur(Number(item.proofAmount)-Number(item.amount))}`:""}</small><div className="sa-actions">{!item.attachmentFilename&&["PENDING_PROOF","PENDING_REVIEW"].includes(item.status)&&<><input inputMode="decimal" value={proofAmounts[item.id]??item.amount} onChange={e=>setProofAmounts(values=>({...values,[item.id]:e.target.value}))} aria-label={`Ποσό αποδεικτικού ${item.id}`}/><label className="secondary" style={{cursor:"pointer"}}><Upload/>Αποδεικτικό<input type="file" accept="image/jpeg,image/png,image/webp,application/pdf" disabled={Boolean(busy)} style={{display:"none"}} onChange={e=>uploadProof(item,e.target.files?.[0])}/></label></>}<button disabled={busy===item.id} onClick={()=>review(item,"CONFIRMED")}><CheckCircle2/>Επιβεβαίωση</button><button className="secondary" disabled={busy===item.id} onClick={()=>review(item,"DISCREPANCY")}>Απόκλιση</button></div></article>):<div className="platform-empty">Δεν υπάρχουν τραπεζικές κινήσεις για έλεγχο.</div>}</section></div>;
}
