import React,{useEffect,useState} from "react";
import {CheckCircle2,RefreshCw,X} from "lucide-react";
const eur=v=>Number(v||0).toLocaleString("el-GR",{style:"currency",currency:"EUR"});
export default function BankLedgerReviewCenter({request,onClose,setMessage,stores=[]}){
 const [items,setItems]=useState([]),[busy,setBusy]=useState(""),[error,setError]=useState(""),[storeId,setStoreId]=useState(""),[bankName,setBankName]=useState(""),[accountName,setAccountName]=useState(""),[ibanMasked,setIbanMasked]=useState("");
 const load=async()=>{setBusy("load");try{setItems((await request("/api/transactions/bank-ledger/review")).items||[])}catch(e){setError(e.message)}finally{setBusy("")}};
 useEffect(()=>{load()},[]);
 const createAccount=async()=>{if(!storeId||!bankName.trim()||!accountName.trim())return setError("Επίλεξε κατάστημα, τράπεζα και όνομα λογαριασμού.");setBusy("create");try{await request(`/api/transactions/stores/${storeId}/bank-accounts`,{method:"POST",body:JSON.stringify({bankName:bankName.trim(),name:accountName.trim(),ibanMasked:ibanMasked.trim()||null})});setBankName("");setAccountName("");setIbanMasked("");setMessage?.("Ο τραπεζικός λογαριασμός αποθηκεύτηκε.");}catch(e){setError(e.message)}finally{setBusy("")}};
 const review=async(item,status)=>{const note=window.prompt(status==="CONFIRMED"?"Σημείωση επιβεβαίωσης":"Αιτιολογία απόκλισης/ακύρωσης");if(!note||note.trim().length<3)return;setBusy(item.id);try{await request(`/api/transactions/bank-ledger/${item.id}/review`,{method:"POST",body:JSON.stringify({status,note:note.trim()})});setItems(rows=>rows.filter(row=>row.id!==item.id));setMessage?.("Η τραπεζική κίνηση ενημερώθηκε.")}catch(e){setError(e.message)}finally{setBusy("")}};
 return <div className="platform-modal"><section className="sa-modal"><header><div><span>SUPER ADMIN ONLY</span><h2>Έλεγχος Ταμείου Τράπεζας</h2><p>Η επιβεβαίωση ενημερώνει μόνο το τραπεζικό ledger. Το ταμείο βάρδιας δεν αλλάζει δεύτερη φορά.</p></div><button className="sa-close" onClick={onClose}><X/></button></header>{error&&<div className="platform-alert error">{error}</div>}<section className="platform-panel" style={{marginBottom:14}}><b>Ρύθμιση τραπεζικού λογαριασμού</b><div className="sa-filters"><label>Κατάστημα<select value={storeId} onChange={e=>setStoreId(e.target.value)}><option value="">Επίλεξε κατάστημα</option>{stores.map(s=><option key={s.id} value={s.id}>{s.companyName} · {s.name}</option>)}</select></label><label>Τράπεζα<input value={bankName} onChange={e=>setBankName(e.target.value)} placeholder="π.χ. Eurobank"/></label><label>Όνομα λογαριασμού<input value={accountName} onChange={e=>setAccountName(e.target.value)} placeholder="π.χ. Κύριος λογαριασμός"/></label></div><label>IBAN (προαιρετικά, μόνο τελευταίοι χαρακτήρες)<input value={ibanMasked} onChange={e=>setIbanMasked(e.target.value)} placeholder="•••• 1234"/></label><div className="sa-actions"><button onClick={createAccount} disabled={busy==="create"}>Αποθήκευση λογαριασμού</button></div></section><div className="sa-actions"><button onClick={load} disabled={busy==="load"}><RefreshCw/>Ανανέωση</button></div>{items.length?items.map(item=><article key={item.id} className="platform-panel" style={{marginBottom:10}}><b>{item.companyName} · {item.storeName}</b><p>{item.bankName} · {item.accountName} · {item.type} · {eur(item.amount)}</p><small>{new Date(item.occurredAt).toLocaleString("el-GR")} · {item.createdByName} · {item.attachmentFilename||"Χωρίς απόδειξη"}</small><div className="sa-actions"><button disabled={busy===item.id} onClick={()=>review(item,"CONFIRMED")}><CheckCircle2/>Επιβεβαίωση</button><button className="secondary" disabled={busy===item.id} onClick={()=>review(item,"DISCREPANCY")}>Απόκλιση</button></div></article>):<div className="platform-empty">Δεν υπάρχουν τραπεζικές κινήσεις για έλεγχο.</div>}</section></div>;
}