import React,{useEffect,useMemo,useState} from "react";
import {CheckCircle2,FileText,RefreshCw,ShieldCheck,X} from "lucide-react";

const money=value=>Number(value||0).toLocaleString("el-GR",{style:"currency",currency:"EUR"});
const when=value=>value?new Intl.DateTimeFormat("el-GR",{dateStyle:"short",timeStyle:"short"}).format(new Date(value)):"—";
const methods={CASH_SHIFT:"Μετρητά ενεργής βάρδιας",CORPORATE_CARD:"Εταιρική κάρτα",BANK_TRANSFER:"Τραπεζική μεταφορά",EMPLOYEE_REIMBURSEMENT:"Πληρωμή υπαλλήλου προς επιστροφή"};

export default function OtherExpenseReviewCenter({request,onClose,setMessage}){
  const [items,setItems]=useState([]),[companies,setCompanies]=useState([]),[stores,setStores]=useState([]),[filters,setFilters]=useState({companyId:"",storeId:"",from:"",to:""}),[notes,setNotes]=useState({}),[loading,setLoading]=useState(true),[busy,setBusy]=useState(""),[error,setError]=useState("");
  const load=async()=>{setLoading(true);setError("");try{const query=new URLSearchParams(Object.entries(filters).filter(([,value])=>value)),result=await request(`/api/transactions/other-expenses/review${query.size?`?${query}`:""}`);setItems(result.items||[]);setCompanies(result.companies||[]);setStores(result.stores||[])}catch(err){setError(err.message)}finally{setLoading(false)}};
  useEffect(()=>{load()},[]);
  const totals=useMemo(()=>({count:items.length,amount:items.reduce((sum,item)=>sum+Number(item.amount||0),0),discrepancies:items.filter(item=>item.automaticCheck?.matched===false).length}),[items]);
  const visibleStores=stores.filter(store=>!filters.companyId||store.companyId===filters.companyId);
  const changeFilter=(key,value)=>setFilters(current=>({...current,[key]:value,...(key==="companyId"?{storeId:""}:{})}));
  const showEvidence=async item=>{setBusy(`evidence:${item.id}`);setError("");try{const result=await request(`/api/transactions/${encodeURIComponent(item.transactionId)}/attachment`),link=document.createElement("a");link.href=result.dataUrl;link.target="_blank";link.rel="noreferrer";link.click()}catch(err){setError(err.message)}finally{setBusy("")}};
  const confirm=async item=>{const note=String(notes[item.id]||"").trim();setBusy(`confirm:${item.id}`);setError("");try{await request(`/api/transactions/other-expenses/${encodeURIComponent(item.id)}/review`,{method:"POST",body:JSON.stringify({note})});setMessage("Το λοιπό έξοδο επιβεβαιώθηκε και καταγράφηκε στο Audit.");await load()}catch(err){setError(err.message)}finally{setBusy("")}};
  return <div className="platform-modal"><section className="platform-security-dialog supplier-settlement-review-dialog">
    <button type="button" className="modal-close" onClick={onClose}><X/></button>
    <div className="supplier-review-head"><div><span>ΜΟΝΟ ΥΠΕΡΔΙΑΧΕΙΡΙΣΤΗ</span><h2>Έλεγχος λοιπών εξόδων</h2><p>Ο έλεγχος ελέγχει αυτόματα αποδεικτικό, αιτιολογία και τρόπο πληρωμής. Εσύ επιβεβαιώνεις μόνο το αποτέλεσμα, με προαιρετική παρατήρηση.</p></div><button type="button" className="secondary" onClick={load} disabled={loading||Boolean(busy)}><RefreshCw/>Ανανέωση</button></div>
    {error&&<div className="platform-alert error">{error}</div>}
    <div className="supplier-review-filters"><label>Ιδιοκτήτης / εταιρεία<select value={filters.companyId} onChange={event=>changeFilter("companyId",event.target.value)}><option value="">Όλοι οι ιδιοκτήτες / εταιρείες</option>{companies.map(company=><option key={company.id} value={company.id}>{company.ownerName||"Χωρίς ιδιοκτήτη"} · {company.name}</option>)}</select></label><label>Κατάστημα<select value={filters.storeId} onChange={event=>changeFilter("storeId",event.target.value)}><option value="">Όλα τα καταστήματα</option>{visibleStores.map(store=><option key={store.id} value={store.id}>{store.name}</option>)}</select></label><label>Από<input type="date" value={filters.from} onChange={event=>changeFilter("from",event.target.value)}/></label><label>Έως<input type="date" value={filters.to} onChange={event=>changeFilter("to",event.target.value)}/></label><button type="button" onClick={load} disabled={loading||Boolean(busy)}><RefreshCw/>Εμφάνιση</button></div>
    <div className="supplier-review-totals"><span><small>Για έλεγχο</small><b>{totals.count}</b></span><span><small>Σύνολο εξόδων</small><b>{money(totals.amount)}</b></span><span className={totals.discrepancies?"warning":""}><small>Αποκλίσεις</small><b>{totals.discrepancies}</b></span></div>
    <div className="supplier-review-list">{loading?<div className="platform-empty">Φόρτωση εξόδων…</div>:items.length===0?<div className="platform-empty"><CheckCircle2/>Δεν υπάρχουν λοιπά έξοδα για έλεγχο.</div>:items.map(item=>{const matched=item.automaticCheck?.matched===true;return <article key={item.id} className={matched?"":"discrepancy"}><header><div><span className={`supplier-review-status ${matched?"confirmed":"discrepancy"}`}>{matched?"ΑΥΤΟΜΑΤΗ ΣΥΜΦΩΝΙΑ":"ΑΠΟΚΛΙΣΗ ΠΡΟΣ ΕΠΙΒΕΒΑΙΩΣΗ"}</span><h3>{item.description||"Λοιπό έξοδο"}</h3><small>{item.ownerName||"Χωρίς ιδιοκτήτη"} · {item.companyName} · {item.storeName}<br/>Πραγματική κίνηση {when(item.occurredAt)} · {item.actorName||"—"}</small></div><strong>{money(item.amount)}</strong></header><div className="supplier-review-meta"><span><b>Τρόπος:</b> {methods[item.paymentMethod]||item.paymentMethod||"—"}</span><span><b>Αποδεικτικό:</b> {item.hasAttachment?item.attachmentFilename||"Συνδεδεμένο παραστατικό":"Δεν υπάρχει"}</span></div><div className="supplier-review-meta"><span><b>Αποτέλεσμα αυτόματου ελέγχου:</b> {matched?"Συμφωνία στα διαθέσιμα στοιχεία εξόδου.":(item.automaticCheck?.checks||[]).join(" ")}</span></div><label className="supplier-review-note">Παρατήρηση Υπερδιαχειριστή (προαιρετική)<textarea value={notes[item.id]||""} onChange={event=>setNotes(current=>({...current,[item.id]:event.target.value}))} maxLength="500" placeholder="Προαιρετική παρατήρηση για τον έλεγχο."/></label><footer>{item.hasAttachment&&<button type="button" className="secondary" onClick={()=>showEvidence(item)} disabled={busy===`evidence:${item.id}`}><FileText/>Προβολή αποδεικτικού</button>}<button type="button" onClick={()=>confirm(item)} disabled={Boolean(busy)}><ShieldCheck/>Επιβεβαίωση ελέγχου</button></footer></article>})}</div>
  </section></div>;
}