import React,{useEffect,useMemo,useState} from "react";
import {Eye,Palette,Save,Search,Send,Trash2,X} from "lucide-react";
import "./pos-designer.css";

const QUICK_COUNT=20;
const CATEGORY_COUNT=14;
const MAX_CATEGORY_PRODUCTS=40;
const euro=value=>value===null||value===undefined?"—":Number(value).toLocaleString("el-GR",{style:"currency",currency:"EUR"});
const normalize=value=>({
  title:value?.title||"OPERATOR POS",productColumns:Number(value?.productColumns||6),showSku:value?.showSku!==false,
  buttonFontScale:Number(value?.buttonFontScale||1),theme:{headerColor:"#033d2f",accentColor:"#087a52",surfaceColor:"#ffffff",...(value?.theme||{})},
  quickKeys:(value?.quickKeys||[]).slice(0,QUICK_COUNT),categories:(value?.categories||[]).slice(0,CATEGORY_COUNT),buttons:value?.buttons||[]
});

export default function PosDesignerPanel({request,onClose}){
  const [data,setData]=useState(null),[layout,setLayout]=useState(null),[section,setSection]=useState("quickKeys"),[selected,setSelected]=useState(new Set()),[busy,setBusy]=useState(""),[message,setMessage]=useState(""),[error,setError]=useState("");
  const [picker,setPicker]=useState(null),[pickerQuery,setPickerQuery]=useState(""),[pickerRows,setPickerRows]=useState([]),[pickerBusy,setPickerBusy]=useState(false),[pickerError,setPickerError]=useState("");
  const [groupSelected,setGroupSelected]=useState(new Set()),[selectedDetails,setSelectedDetails]=useState({});

  const load=async()=>{setError("");try{const result=await request("/api/platform/pos-designer-fixed");setData(result);setLayout(normalize(result.draft))}catch(err){setError(err.message)}};
  useEffect(()=>{load()},[]);
  const stores=useMemo(()=>(data?.companies||[]).flatMap(company=>company.stores.map(store=>({...store,companyName:company.name,published:(data?.published||[]).find(row=>row.storeId===store.id)}))),[data]);
  const updateSection=(kind,id,patch)=>setLayout(current=>({...current,[kind]:current[kind].map(button=>button.id===id?{...button,...patch}:button)}));
  const update=(id,patch)=>updateSection(section,id,patch);

  const save=async()=>{setBusy("save");setError("");setMessage("");try{const result=await request("/api/platform/pos-designer-fixed/draft",{method:"PUT",body:JSON.stringify(layout)});setLayout(normalize(result.draft));setMessage(`Αποθηκεύτηκε μόνιμα στη βάση ως πρόχειρη έκδοση ${result.draftVersion}.`)}catch(err){setError(err.message)}finally{setBusy("")}};
  const publish=async()=>{if(!selected.size)return setError("Επίλεξε τουλάχιστον ένα κατάστημα.");setBusy("publish");setError("");setMessage("");try{const saved=await request("/api/platform/pos-designer-fixed/draft",{method:"PUT",body:JSON.stringify(layout)});setLayout(normalize(saved.draft));const result=await request("/api/platform/pos-designer-fixed/publish",{method:"POST",body:JSON.stringify({storeIds:[...selected]})});setMessage(`Δημοσιεύτηκε η STANDARD διάταξη σε ${result.publishedStores} καταστήματα.`);setSelected(new Set());await load()}catch(err){setError(err.message)}finally{setBusy("")}};
  const clearAssignments=()=>{if(!window.confirm("Να καθαριστούν μόνο οι αναθέσεις προϊόντων; Οι 20 Γρήγορες θέσεις και οι 14 Κατηγορίες θα παραμείνουν."))return;setLayout(current=>({...current,quickKeys:current.quickKeys.map(button=>({...button,label:"ΚΕΝΟ",productQuery:"",productCodes:[],visible:true})),categories:current.categories.map(button=>({...button,productCodes:[],visible:true}))}));setMessage("Καθαρίστηκαν οι αναθέσεις προϊόντων. Η STANDARD δομή παραμένει.")};

  const rememberProducts=rows=>setSelectedDetails(current=>{const next={...current};for(const product of rows||[])next[String(product.sourceCode||"")]=product;return next});
  const fetchSelectedDetails=async codes=>{if(!codes.length){setSelectedDetails({});return}try{const result=await request(`/api/platform/pos-designer-fixed/products?codes=${encodeURIComponent(codes.join(","))}`);const map={};for(const product of result.rows||[])map[String(product.sourceCode||"")]=product;setSelectedDetails(map)}catch{setSelectedDetails({})}};
  const openSinglePicker=button=>{setPicker({mode:"single",kind:"quickKeys",id:button.id});setPickerQuery("");setPickerRows([]);setPickerError("");setGroupSelected(new Set());setSelectedDetails({})};
  const openGroupPicker=button=>{const codes=button.productCodes||[];setPicker({mode:"group",kind:"categories",id:button.id});setPickerQuery("");setPickerRows([]);setPickerError("");setGroupSelected(new Set(codes));fetchSelectedDetails(codes)};
  const searchProducts=async()=>{const q=pickerQuery.trim();if(!q)return setPickerError("Γράψε ονομασία, εσωτερικό κωδικό ή barcode.");setPickerBusy(true);setPickerError("");try{const result=await request(`/api/platform/master-catalog/bulk/products?q=${encodeURIComponent(q)}`);const rows=result.rows||[];setPickerRows(rows);rememberProducts(rows);if(!rows.length)setPickerError("Δεν βρέθηκε προϊόν με αυτή την αναζήτηση.")}catch(err){setPickerError(err.message)}finally{setPickerBusy(false)}};
  const chooseSingle=product=>{const code=String(product.sourceCode||"");if(!code)return;updateSection("quickKeys",picker.id,{productQuery:code,productCodes:[code],label:product.name||code,visible:true});setPicker(null);setPickerRows([]);setMessage(`Το «${product.name}» μπήκε στη γρήγορη θέση.`)};
  const toggleGroup=product=>{const code=String(product.sourceCode||"");if(!code)return;setGroupSelected(current=>{const next=new Set(current);if(next.has(code)){next.delete(code);return next}if(next.size>=MAX_CATEGORY_PRODUCTS){setPickerError(`Κάθε κατηγορία μπορεί να έχει έως ${MAX_CATEGORY_PRODUCTS} προϊόντα.`);return current}next.add(code);return next})};
  const removeGroupCode=code=>setGroupSelected(current=>{const next=new Set(current);next.delete(code);return next});
  const saveGroup=()=>{if(!picker)return;const codes=[...groupSelected].slice(0,MAX_CATEGORY_PRODUCTS),target=layout.categories.find(row=>row.id===picker.id);updateSection("categories",picker.id,{productCodes:codes,visible:true});setMessage(`Αποθηκεύτηκαν ${codes.length} προϊόντα στην κατηγορία «${target?.label||"Κατηγορία"}». Πάτησε Αποθήκευση πρόχειρου.`);setPicker(null);setPickerRows([])};

  if(!layout)return <div className="pos-designer-overlay"><section className="pos-designer-shell"><button className="pos-designer-close" onClick={onClose}><X/></button><p>{error||"Φόρτωση σχεδιαστή POS…"}</p></section></div>;
  const scale=layout.buttonFontScale||1;
  return <div className="pos-designer-overlay"><section className="pos-designer-shell">
    <button className="pos-designer-close" onClick={onClose} aria-label="Κλείσιμο"><X/></button>
    <header><div><span>SUPER ADMIN POS DESIGNER</span><h2><Palette/>STANDARD Σχεδιαστής POS</h2><p>Σταθερή δομή: 20 Γρήγορα αριστερά και 14 Κατηγορίες κάτω. Αλλάζεις μόνο προϊόντα, ονόματα κατηγοριών, χρώματα και γραμματοσειρά.</p><p>Οι αλλαγές παραμένουν πρόχειρες μέχρι να επιλέξεις ρητά καταστήματα και να πατήσεις Δημοσίευση.</p></div><div><button type="button" onClick={clearAssignments} disabled={busy}>Καθαρισμός προϊόντων</button><button onClick={save} disabled={busy}><Save/>Αποθήκευση πρόχειρου</button><button className="publish" onClick={publish} disabled={busy||!selected.size}><Send/>Δημοσίευση ({selected.size})</button></div></header>
    {error&&<div className="pos-designer-alert error">{error}</div>}{message&&<div className="pos-designer-alert success">{message}</div>}
    <div className="pos-designer-workspace">
      <section className="pos-designer-controls">
        <h3>Ρυθμίσεις STANDARD POS</h3>
        <div className="designer-settings"><label>Τίτλος POS<input value={layout.title} onChange={e=>setLayout({...layout,title:e.target.value})}/></label><label>Στήλες προϊόντων<select value={layout.productColumns} onChange={e=>setLayout({...layout,productColumns:Number(e.target.value)})}>{[4,5,6,7,8].map(value=><option key={value}>{value}</option>)}</select></label><label>Μέγεθος γραμματοσειράς<select value={layout.buttonFontScale} onChange={e=>setLayout({...layout,buttonFontScale:Number(e.target.value)})}><option value="0.9">Μικρό</option><option value="1">Κανονικό</option><option value="1.15">Μεγάλο</option><option value="1.3">Πολύ μεγάλο</option><option value="1.5">Extra μεγάλο</option></select></label><label>Κύριο χρώμα<input type="color" value={layout.theme.accentColor} onChange={e=>setLayout({...layout,theme:{...layout.theme,accentColor:e.target.value}})}/></label><label className="toggle"><input type="checkbox" checked={layout.showSku} onChange={e=>setLayout({...layout,showSku:e.target.checked})}/>Εμφάνιση SKU</label></div>
        <div className="pos-designer-standard-lock">🔒 STANDARD: 20 Γρήγορες θέσεις + 14 Κατηγορίες × έως 40 προϊόντα. Πληρωμές, βάρδιες, πελάτες, προμηθευτές, φύρα και παρασκευή παραμένουν σταθερές και συνδέονται με το BackOffice.</div>
        <nav className="designer-tabs designer-tabs-two"><button className={section==="quickKeys"?"active":""} onClick={()=>setSection("quickKeys")}>Γρήγορα (20)</button><button className={section==="categories"?"active":""} onClick={()=>setSection("categories")}>Κατηγορίες (14)</button></nav>
        <div className="pos-button-title"><h3>{section==="quickKeys"?"20 μόνιμα Γρήγορα πλήκτρα":"14 μόνιμες Κατηγορίες"}</h3></div>
        <div className="pos-button-editor">{section==="quickKeys"?layout.quickKeys.map((button,index)=><article key={button.id} style={{gridTemplateColumns:"42px minmax(180px,1fr) auto 46px"}}><b style={{textAlign:"center"}}>{index+1}</b><div style={{display:"grid",gap:3}}><b>{button.productQuery?button.label:"ΚΕΝΗ ΘΕΣΗ"}</b><small>{button.productQuery?`Κωδικός: ${button.productQuery}`:"Πάτησε Επιλογή προϊόντος"}</small></div><button type="button" onClick={()=>openSinglePicker(button)}><Search/>{button.productQuery?"Αλλαγή":"Επιλογή"}</button><input type="color" value={button.color} onChange={e=>update(button.id,{color:e.target.value})}/></article>):layout.categories.map((button,index)=><article key={button.id} style={{gridTemplateColumns:"42px minmax(150px,1fr) auto 46px"}}><b style={{textAlign:"center"}}>{index+1}</b><input value={button.label} placeholder={`Κατηγορία ${index+1}`} onChange={e=>update(button.id,{label:e.target.value,categoryName:e.target.value})}/><button type="button" onClick={()=>openGroupPicker(button)}>Προϊόντα ({(button.productCodes||[]).length}/40)</button><input type="color" value={button.color} onChange={e=>update(button.id,{color:e.target.value})}/></article>)}</div>
        <p className="publish-help">Η δομή δεν αλλάζει. Αργότερα μπορούμε να προσθέσουμε ελεύθερο Designer ως αναβάθμιση χωρίς να επηρεάσουμε το STANDARD POS.</p>
      </section>
      <section className="pos-designer-preview"><h3><Eye/>Ζωντανή προεπισκόπηση — πραγματική διάταξη καταστήματος</h3><div className="designer-standard-preview" style={{"--preview-accent":layout.theme.accentColor,"--button-scale":scale}}><aside><b>ΓΡΗΓΟΡΑ — 20 ΘΕΣΕΙΣ</b><div>{layout.quickKeys.map((button,index)=><button key={button.id} disabled={!button.productQuery} style={{background:button.productQuery?button.color:"#cbd5d1",fontSize:`calc(13px * var(--button-scale))`}}><i>{index+1}</i>{button.productQuery?button.label:"ΚΕΝΟ"}</button>)}</div></aside><main><div className="designer-preview-placeholder"><b>STANDARD POS</b><span>Καλάθι, keypad και λειτουργίες παραμένουν σταθερά.</span></div><section><b>ΚΑΤΗΓΟΡΙΕΣ — 14 ΘΕΣΕΙΣ / 2 ΣΕΙΡΕΣ</b><div>{layout.categories.map((button,index)=><button key={button.id} style={{background:button.color,fontSize:`calc(12px * var(--button-scale))`}}><i>{index+1}</i>{button.label}<small>{(button.productCodes||[]).length}/40 προϊόντα</small></button>)}</div></section></main></div>
        <h3>Δημοσίευση σε καταστήματα</h3><p className="publish-help">Επίλεξε τα καταστήματα που θα πάρουν αυτή τη STANDARD διάταξη.</p><div className="store-select-actions"><button onClick={()=>setSelected(new Set(stores.map(store=>store.id)))}>Επιλογή όλων</button><button onClick={()=>setSelected(new Set())}>Καθαρισμός</button></div><div className="pos-store-list">{stores.map(store=><label key={store.id}><input type="checkbox" checked={selected.has(store.id)} onChange={e=>setSelected(current=>{const next=new Set(current);e.target.checked?next.add(store.id):next.delete(store.id);return next})}/><span><b>{store.name}</b><small>{store.companyName}{store.city?` · ${store.city}`:""}</small></span><em>{store.published?`Έκδοση ${store.published.version}`:"Χωρίς δημοσίευση"}</em></label>)}</div>
      </section>
    </div>
    {picker&&<div className="pos-product-picker" onMouseDown={e=>e.target===e.currentTarget&&setPicker(null)}><section><header><div><b>{picker.mode==="group"?"Προϊόντα κατηγορίας":"Επιλογή γρήγορου προϊόντος"}</b><small>Αναζήτηση με ονομασία, εσωτερικό κωδικό ή barcode</small></div><button onClick={()=>setPicker(null)}><X/></button></header><div className="picker-search"><input autoFocus value={pickerQuery} onChange={e=>setPickerQuery(e.target.value)} onKeyDown={e=>e.key==="Enter"&&searchProducts()} placeholder="π.χ. FREDDO ESPRESSO ή 520..."/><button onClick={searchProducts} disabled={pickerBusy}><Search/>{pickerBusy?"Αναζήτηση…":"Αναζήτηση"}</button></div>{picker.mode==="group"&&<><div className="picker-selected"><b>{groupSelected.size}/40 προϊόντα επιλεγμένα</b><button onClick={saveGroup}>Αποθήκευση επιλογών</button></div>{groupSelected.size>0&&<div className="picker-current-products"><b>Ήδη στην κατηγορία</b><div>{[...groupSelected].map(code=>{const product=selectedDetails[code];return <div key={code}><span style={{display:"grid"}}><b>{product?.name||"Προϊόν"}</b><small>Κωδικός: {code}{product?.barcodes?.length?` · Barcode: ${product.barcodes.join(", ")}`:""}</small></span><button type="button" onClick={()=>removeGroupCode(code)} title="Αφαίρεση μόνο από την κατηγορία"><Trash2/>Αφαίρεση</button></div>})}</div></div>}</>}{pickerError&&<div className="picker-error">{pickerError}</div>}<div className="picker-results">{pickerRows.map(product=>{const code=String(product.sourceCode||""),chosen=groupSelected.has(code);return <button key={product.id} className={chosen?"chosen":""} onClick={()=>picker.mode==="group"?toggleGroup(product):chooseSingle(product)}>{picker.mode==="group"&&<span>{chosen?"☑":"☐"}</span>}<span><b>{product.name}</b><small>{product.categoryName||"Χωρίς κατηγορία"}{product.subcategoryName?` → ${product.subcategoryName}`:""}</small></span><span><b>Κωδικός</b><small>{product.sourceCode}</small></span><span><b>Barcode</b><small>{(product.barcodes||[]).join(", ")||"—"}</small></span><strong>{euro(product.defaultRetailPrice)}</strong></button>})}{!pickerRows.length&&!pickerError&&<div className="picker-empty">Γράψε ονομασία ή barcode και πάτησε Αναζήτηση.</div>}</div></section></div>}
  </section></div>;
}