import React,{useEffect,useState} from "react";

export default function RbsInstallationSetup({company,store,terminals,request}){
  const [terminalPos,setTerminalPos]=useState(terminals[0]?.terminalPos||""),[state,setState]=useState(null),[error,setError]=useState(""),[busy,setBusy]=useState(false),[saved,setSaved]=useState(false);
  const [form,setForm]=useState({cashCode:"",cardCode:"",deliveryCode:"",workFolder:"C:\\capture",confirmed:false});
  useEffect(()=>{let current=true;setSaved(false);setState(null);setError("");setForm({cashCode:"",cardCode:"",deliveryCode:"",workFolder:"C:\\capture",confirmed:false});if(!terminalPos)return;
    request(`/api/platform/companies/${company.id}/stores/${store.id}/rbs-installation/${encodeURIComponent(terminalPos)}`).then(result=>{if(!current)return;setState(result);if(result.settings){setForm({...result.settings,deliveryCode:result.settings.deliveryCode||"",confirmed:false});setSaved(true)}}).catch(e=>{if(current)setError(e.message)});return()=>{current=false};
  },[company.id,store.id,terminalPos,request]);
  const change=(key,value)=>{setForm(current=>({...current,[key]:value}));setSaved(false)};
  const save=async e=>{e.preventDefault();setBusy(true);setError("");try{await request(`/api/platform/companies/${company.id}/stores/${store.id}/rbs-installation`,{method:"PUT",body:JSON.stringify({terminalPos,cashCode:form.cashCode,cardCode:form.cardCode,deliveryCode:form.deliveryCode,workFolder:form.workFolder,confirmed:form.confirmed})});setSaved(true)}catch(e){setError(e.message)}finally{setBusy(false)}};
  const download=async(guided=false)=>{setBusy(true);setError("");try{const result=await request(`/api/platform/companies/${company.id}/stores/${store.id}/rbs-installation/${encodeURIComponent(terminalPos)}/${guided?"guided-package":"package"}`,{method:"POST",body:JSON.stringify({apiBase:window.location.origin})});const url=URL.createObjectURL(new Blob([guided?"":"\ufeff",result.script],{type:"text/plain;charset=utf-8"}));const anchor=document.createElement("a");anchor.href=url;anchor.download=result.fileName;anchor.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}catch(e){setError(e.message)}finally{setBusy(false)}};
  return <section style={{background:"white",padding:16,marginTop:14,borderRadius:10}}><h4>Ρυθμίσεις RBS και έτοιμο πακέτο Windows</h4>
    <p>Αντέγραψε τους κωδικούς από τις ρυθμίσεις πληρωμών της συγκεκριμένης RBS. Οι κωδικοί αυτοί διαφέρουν από το TID του EFTPOS. Η αποθήκευση δεν εκδίδει απόδειξη.</p>
    <label>POS <select value={terminalPos} onChange={e=>setTerminalPos(e.target.value)}>{terminals.map(t=><option key={t.terminalPos} value={t.terminalPos}>{t.displayName||t.terminalPos} · {t.terminalPos}</option>)}</select></label>
    {state&&!state.connectorAllowed&&<p role="alert" style={{color:"#991b1b"}}>Η άδεια ή το CONNECTOR_RBS δεν είναι ενεργό για τον πελάτη. Μπορείς να προετοιμάσεις το πακέτο· η σύνδεση Writer θα μπλοκαριστεί μέχρι την ενεργοποίηση.</p>}
    <form onSubmit={save} style={{display:"grid",gap:10}}><label>Κωδικός RBS μετρητών <input value={form.cashCode} onChange={e=>change("cashCode",e.target.value)} inputMode="numeric" pattern="[0-9]{1,2}" maxLength={2} required/></label><label>Κωδικός RBS κάρτας καταστήματος <input value={form.cardCode} onChange={e=>change("cardCode",e.target.value)} inputMode="numeric" pattern="[0-9]{1,2}" maxLength={2} required/></label><label>Κωδικός RBS κάρτας Delivery — μόνο με δεύτερο EFTPOS <input value={form.deliveryCode} onChange={e=>change("deliveryCode",e.target.value)} inputMode="numeric" pattern="[0-9]{1,2}" maxLength={2} placeholder="Κενό για Διαδόχου / ένα EFTPOS"/></label><label>Φάκελος που παρακολουθεί ο CAPDriver <input value={form.workFolder} onChange={e=>change("workFolder",e.target.value)} required/></label><label><input type="checkbox" checked={form.confirmed} onChange={e=>change("confirmed",e.target.checked)} required/> Επιβεβαίωσα τους κωδικούς και τον φάκελο στη συγκεκριμένη RBS/CAPDriver.</label><button disabled={busy||!terminalPos}>Αποθήκευση ρυθμίσεων RBS</button></form>
    {error&&<p role="alert">{error}</p>}{saved&&<p>Οι ρυθμίσεις αποθηκεύτηκαν. Εκκρεμεί φυσική δοκιμή ταμειακής/EFTPOS.</p>}
    <div style={{display:"flex",gap:12,flexWrap:"wrap",marginTop:16}}>
      <button onClick={()=>download(true)} disabled={busy||!saved||terminals.length!==1} style={{minHeight:56,fontSize:18,padding:"12px 20px"}}>Λήψη εύκολης εγκατάστασης για αυτό το POS</button>
      <button onClick={()=>download(false)} disabled={busy||!saved||terminals.length!==1}>Λήψη έτοιμου πακέτου Windows</button>
    </div>
    <p>Για απομακρυσμένη εγκατάσταση: κατέβασε το αρχείο .cmd στο PC του καταστήματος μέσω AnyDesk και άνοιξέ το με διπλό κλικ. Ο ελληνικός οδηγός έχει Σύνδεση και έλεγχο, επιλογή εκκίνησης μαζί με τα Windows και ξεχωριστή Εκκίνηση τώρα. Το άνοιγμα του οδηγού δεν ξεκινά τον connector και δεν εκδίδει απόδειξη.</p>
    <p>Μπορείς να το κατεβάσεις από το σπίτι. Στον τελικό υπολογιστή: δεξί κλικ στο αρχείο → Εκτέλεση με PowerShell. Το μενού έχει Ζεύξη, Έλεγχο και Εκκίνηση Writer. Η ζεύξη γίνεται με τον τελικό χρήστη Windows και νέο κωδικό από το BackOffice.</p>
    {terminals.length!==1&&<p>Το έτοιμο πακέτο αφορά ένα ενεργό POS. Για περισσότερα απαιτείται ξεχωριστός έλεγχος της φυσικής διαδρομής writer.</p>}
    <p>Το πακέτο δεν περιλαμβάνει κωδικό ζεύξης, PIN ή token. Χρησιμοποιεί τον υπάρχοντα CAPDriver. Η προαιρετική αυτόματη εκκίνηση αφορά τον ίδιο χρήστη μετά την είσοδο στα Windows· δεν είναι υπηρεσία συστήματος. Κράτησε το παράθυρο connector ανοιχτό και επιβεβαίωσε WRITER ONLINE πριν από πώληση. Η μικτή πληρωμή παραμένει εκκρεμής.</p>
  </section>;
}
