import React,{useEffect,useRef,useState} from 'react';
export default function RemoteAgentController({job,request,onClose}){
 const [screen,setScreen]=useState(null),[error,setError]=useState(''),[text,setText]=useState(''),[live,setLive]=useState(false);
 const requester=useRef(request);requester.current=request;
 const busy=useRef(false),base=`/api/remote-agent/${job.id}`;
 useEffect(()=>{let done=false;const poll=async()=>{if(busy.current)return;busy.current=true;try{const result=await requester.current(`${base}/frame`);if(!done){setScreen(result.frame);setLive(Boolean(result.frame&&Date.now()-result.frame.at<5000));setError('');}}catch(e){if(!done){setError(e.message);setLive(false);}}finally{busy.current=false;}};poll();const timer=setInterval(poll,1000);return()=>{done=true;clearInterval(timer);};},[base]);
 const input=async body=>{if(!live)return;try{await request(`${base}/input`,{method:'POST',body:JSON.stringify(body)});}catch(e){setError(e.message);setLive(false);}};
 const click=(e,button='left')=>{const r=e.currentTarget.getBoundingClientRect();input({type:'click',button,x:(e.clientX-r.left)/r.width,y:(e.clientY-r.top)/r.height});};
 const stop=async()=>{try{await request(`${base}/stop`,{method:'POST',body:'{}'});onClose();}catch(e){setError(e.message);setLive(false);}};
 return <div className="platform-modal"><section className="platform-security-dialog" style={{width:'min(1200px,95vw)'}}><h2>MyWorkStation Remote Assist</h2><p>Η οθόνη εμφανίζεται μόνο μετά την αποδοχή στο PC. Με το κλείσιμο παύει η σύνδεση σε έως15 δευτερόλεπτα.</p><button onClick={stop}>Διακοπή συνεδρίας</button><button onClick={onClose}>Κλείσιμο προβολής</button>{error&&<p role="alert">{error}</p>}{screen&&<img src={`data:image/jpeg;base64,${screen.jpeg}`} alt="Οθόνη υπολογιστή καταστήματος" style={{width:'100%',display:'block',opacity:live?1:.4}} onClick={e=>click(e)} onContextMenu={e=>{e.preventDefault();click(e,'right');}}/>}<div><input aria-label="Κείμενο προς πληκτρολόγηση" value={text} maxLength={200} onChange={e=>setText(e.target.value)}/><button disabled={!live||!text} onClick={()=>{input({type:'text',text});setText('');}}>Πληκτρολόγηση</button>{['Enter','Tab','Backspace','Escape','ArrowUp','ArrowDown','ArrowLeft','ArrowRight'].map(key=><button key={key} disabled={!live} onClick={()=>input({type:'key',key})}>{key}</button>)}<button disabled={!live} onClick={()=>input({type:'wheel',direction:1})}>Κύλιση πάνω</button><button disabled={!live} onClick={()=>input({type:'wheel',direction:-1})}>Κύλιση κάτω</button></div><small>Πρώτη έκδοση: κύρια οθόνη, περίπου1 εικόνα/δευτερόλεπτο, χωρίς μεταφορά αρχείων ή έλεγχο UAC.</small></section></div>;
}
