import React,{useEffect,useMemo,useState} from "react";
import {RefreshCw,ShieldCheck,X} from "lucide-react";
import {invoiceAuditFinancialText} from "../commerce/invoiceAuditFinancials.js";
const today=()=>new Intl.DateTimeFormat("en-CA",{timeZone:"Europe/Athens"}).format(new Date());
const monthStart=()=>{const d=new Date();d.setDate(d.getDate()-30);return new Intl.DateTimeFormat("en-CA",{timeZone:"Europe/Athens"}).format(d)};
const money=v=>Number(v||0).toLocaleString("el-GR",{style:"currency",currency:"EUR"});
const at=v=>v?new Intl.DateTimeFormat("el-GR",{timeZone:"Europe/Athens",dateStyle:"short",timeStyle:"short"}).format(new Date(v)):"—";
const financials=item=>invoiceAuditFinancialText(item)||"—";
export default function SuperAdminEventsCenter({request,companies,onClose}){const [companyId,setCompanyId]=useState(""),[storeId,setStoreId]=useState(""),[from,setFrom]=useState(monthStart),[to,setTo]=useState(today),[items,setItems]=useState([]),[loading,setLoading]=useState(false),[error,setError]=useState("");const stores=useMemo(()=>companyId?(companies.find(c=>c.id===companyId)?.stores||[]):companies.flatMap(c=>c.stores||[]),[companies,companyId]);const load=async()=>{setLoading(true);setError("");try{const q=new URLSearchParams({from,to,...(companyId?{companyId}:{}),...(storeId?{storeId}:{})});const result=await request(`/api/reports/audit-events?${q}`);setItems(result.items||[])}catch(e){setError(e.message)}finally{setLoading(false)}};useEffect(()=>{load()},[]);return <div className="platform-modal platform-events-modal"><section className="sa-modal platform-events-dialog"><header><div><span>ΜΟΝΟ ΥΠΕΡΔΙΑΧΕΙΡΙΣΤΗ</span><h2><ShieldCheck/> Συμβάντα</h2><p>Ενιαίο Audit για όλους τους ιδιοκτήτες και τα καταστήματα. Η προβολή δεν αλλάζει οικονομικά δεδομένα.</p></div><button className="sa-close" onClick={onClose}><X/></button></header><div className="sa-filters"><label>Ιδιοκτήτης / εταιρεία<select value={companyId} onChange={e=>{setCompanyId(e.target.value);setStoreId("")}}><option value="">Όλοι οι ιδιοκτήτες / εταιρείες</option>{companies.map(c=><option key={c.id} value={c.id}>{c.owner?.fullName||c.name} · {c.name}</option>)}</select></label><label>Κατάστημα<select value={storeId} onChange={e=>setStoreId(e.target.value)}><option value="">Όλα τα καταστήματα</option>{stores.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label><label>Από<input type="date" value={from} onChange={e=>setFrom(e.target.value)}/></label><label>Έως<input type="date" value={to} onChange={e=>setTo(e.target.value)}/></label></div><div className="sa-actions"><small className="platform-events-resize-note">Σύρε τη δεξιά άκρη κάθε τίτλου για αλλαγή πλάτους στήλης.</small><button onClick={load} disabled={loading}><RefreshCw/>{loading?"Φόρτωση…":"Εμφάνιση"}</button></div>{error&&<div className="platform-alert error">{error}</div>}<div className="platform-panel platform-events-table-wrap">{items.length?<table className="platform-events-table"><thead><tr>{["Ημερομηνία","Συμβάν","Περιγραφή","Οικονομικά στοιχεία","Ποσό","Κατάστημα","Χειριστής"].map(x=><th key={x}>{x}</th>)}</tr></thead><tbody>{items.map(i=><tr key={`${i.sourceType||""}-${i.id}`}><td>{at(i.createdAt)}</td><td><b>{i.eventLabel||i.eventType}</b></td><td>{i.description||"—"}</td><td><small>{financials(i)}</small></td><td>{money(i.amount)}</td><td>{i.storeName||"—"}</td><td>{i.actorName||"—"}</td></tr>)}</tbody></table>:<div className="platform-empty">{loading?"Φόρτωση συμβάντων…":"Δεν βρέθηκαν συμβάντα για τα φίλτρα."}</div>}</div></section></div>;}
