import React,{useEffect,useState} from "react";
import {Activity,CalendarClock,MonitorUp,Save,X} from "lucide-react";
import SuperAdminStaffScheduler from "./SuperAdminStaffScheduler.jsx";

export default function SuperAdminInstallationCenter({companies,request,onOpenTerminals,onClose}){
  const[states,setStates]=useState({}),[busy,setBusy]=useState(""),[error,setError]=useState(""),[scheduleTarget,setScheduleTarget]=useState(null);
  const stores=(companies||[]).flatMap(company=>company.stores.map(store=>({company,store})));
  useEffect(()=>{Promise.all(stores.map(async({company,store})=>{try{const result=await request(`/api/platform/store-modules/companies/${company.id}/stores/${store.id}`);return[store.id,result.state]}catch{return[store.id,{active:false,monthlyPrice:49}]}})).then(rows=>setStates(Object.fromEntries(rows)))},[]);
  const save=async(company,store)=>{setBusy(store.id);setError("");try{const current=states[store.id]||{active:false,monthlyPrice:49};const result=await request(`/api/platform/store-modules/companies/${company.id}/stores/${store.id}`,{method:"PUT",body:JSON.stringify({active:Boolean(current.active),monthlyPrice:Number(current.monthlyPrice||0),notes:"AI πρόγραμμα εργαζομένων ανά κατάστημα"})});setStates(value=>({...value,[store.id]:result.state}))}catch(e){setError(e.message)}finally{setBusy("")}};
  return <><div className="platform-modal installation-center-modal"><section className="platform-security-dialog"><button className="modal-close" onClick={onClose}><X/></button><h2>Super Admin Installation Center</h2><p>Κεντρική πρόσβαση σε εγκαταστάσεις, δωρεάν REMOTE και επί πληρωμή modules ανά κατάστημα.</p>{error&&<div className="platform-alert error">{error}</div>}<div className="security-list">{stores.map(({company,store})=>{const state=states[store.id]||{active:false,monthlyPrice:49};return <article key={store.id}><Activity/><div><small>{company.name}</small><b>{store.name}</b><span>REMOTE δωρεάν · Super Admin πάντα ενεργό</span></div><div className="platform-store-actions installation-actions"><button onClick={()=>onOpenTerminals(company,store,true)}><MonitorUp/>REMOTE / Τερματικά</button><button onClick={()=>setScheduleTarget({company,store})}><CalendarClock/>Άνοιγμα AI Προγράμματος</button><label><CalendarClock/> Module πελάτη <input type="checkbox" checked={Boolean(state.active)} onChange={e=>setStates(value=>({...value,[store.id]:{...state,active:e.target.checked}}))}/></label><label>€/μήνα <input type="number" min="0" step="0.01" value={state.monthlyPrice??49} onChange={e=>setStates(value=>({...value,[store.id]:{...state,monthlyPrice:e.target.value}}))}/></label><button className="secondary" onClick={()=>save(company,store)} disabled={busy===store.id}><Save/>{busy===store.id?"Αποθήκευση…":"Αποθήκευση module"}</button></div></article>})}</div></section></div>{scheduleTarget&&<SuperAdminStaffScheduler {...scheduleTarget} request={request} onClose={()=>setScheduleTarget(null)}/>}</>;
}
