import React,{useMemo,useState} from "react";
import {BarChart3,Eye,ShieldCheck,X} from "lucide-react";

const packs=["BASIC ΕΛΕΓΧΟΣ","COMPLETE ΕΛΕΓΧΟΣ","PREMIUM ΕΛΕΓΧΟΣ","ΑΝΑΛΥΣΕΙΣ ΚΕΡΔΟΦΟΡΙΑΣ","ΕΛΕΓΧΟΣ ΤΙΜΩΝ ΚΑΤΑΣΤΗΜΑΤΩΝ","ΚΕΝΤΡΟ ΚΕΡΔΟΦΟΡΙΑΣ & ΑΠΩΛΕΙΩΝ","ΑΝΑΦΟΡΑ ΠΡΟΣ ΙΔΙΟΚΤΗΤΗ"];
const categories=["Ταμεία & Βάρδιες","Αποθήκη & Τιμολόγια","Κόστος & Margin","Τιμές & Προμηθευτές","Απώλειες & Φύρες","Αναφορά ιδιοκτήτη"];
export default function SuperAdminChecksAnalytics({companies=[],onClose}){
 const [company,setCompany]=useState("ALL"),[store,setStore]=useState("ALL"),[pack,setPack]=useState(packs[0]),[category,setCategory]=useState("ALL"),[from,setFrom]=useState(""),[to,setTo]=useState(""),[preview,setPreview]=useState(null);
 const stores=useMemo(()=>company==="ALL"?companies.flatMap(c=>(c.stores||[]).map(s=>({...s,companyId:c.id}))):(companies.find(c=>c.id===company)?.stores||[]),[companies,company]);
 const run=()=>setPreview({pack,company:company==="ALL"?"Όλοι οι ιδιοκτήτες":companies.find(c=>c.id===company)?.name||"—",store:store==="ALL"?"Όλα τα καταστήματα":stores.find(s=>s.id===store)?.name||"—",category:category==="ALL"?"Όλες οι κατηγορίες":category,period:from&&to?`${from} έως ${to}`:"Όλο το διαθέσιμο διάστημα"});
 return <div className="sa-overlay"><section className="sa-modal"><header><div><span>SUPER ADMIN ONLY</span><h2><BarChart3/> Έλεγχοι & Αναλύσεις Super Admin</h2><p>Κεντρικός έλεγχος ανά ιδιοκτήτη και κατάστημα. Οι σοβαρές ενέργειες απαιτούν προεπισκόπηση και έγκριση.</p></div><button className="sa-close" onClick={onClose}><X/></button></header><div className="sa-filters"><label>Ιδιοκτήτης<select value={company} onChange={e=>{setCompany(e.target.value);setStore("ALL")}}><option value="ALL">Όλοι</option>{companies.map(c=><option key={c.id} value={c.id}>{c.owner?.fullName||c.ownerName||c.name}</option>)}</select></label><label>Κατάστημα<select value={store} onChange={e=>setStore(e.target.value)}><option value="ALL">Όλα</option>{stores.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label><label>Από<input type="date" value={from} onChange={e=>setFrom(e.target.value)}/></label><label>Έως<input type="date" value={to} onChange={e=>setTo(e.target.value)}/></label><label>Πακέτο ελέγχου<select value={pack} onChange={e=>setPack(e.target.value)}>{packs.map(p=><option key={p}>{p}</option>)}</select></label><label>Κατηγορία<select value={category} onChange={e=>setCategory(e.target.value)}><option value="ALL">Όλες</option>{categories.map(c=><option key={c}>{c}</option>)}</select></label></div><div className="sa-actions"><button onClick={run}><ShieldCheck/> Εκτέλεση ελέγχου</button><button className="secondary" onClick={()=>setPreview(null)}><Eye/> Καθαρισμός προεπισκόπησης</button></div>{preview&&<div className="sa-preview"><h3><Eye/> Προεπισκόπηση αποτελέσματος</h3><div className="sa-summary"><b>{preview.pack}</b><span>{preview.company}</span><span>{preview.store}</span><span>{preview.period}</span><span>{preview.category}</span></div><div className="sa-status-grid"><article><strong>Χρειάζεται έλεγχος</strong><span>Τα δεδομένα θα αναλυθούν από τα συνδεδεμένα ταμεία, βάρδιες, αποθήκη, τιμολόγια, POS και συμβάντα.</span></article><article><strong>Καμία αυτόματη κατηγορία υπαλλήλου</strong><span>Χρησιμοποιούνται μόνο οι ενδείξεις «Χρειάζεται έλεγχος», «Ύποπτη διαφορά» και «Ασυνήθιστη κίνηση».</span></article></div><p className="sa-note">Η εφαρμογή αλλαγών τιμών, διορθωτικών ενεργειών ή αποστολής αναφοράς θα εμφανίζεται ξεχωριστά σε προεπισκόπηση και θα απαιτεί έγκριση Super Admin.</p></div>}</section></div>;
}
