import React,{useEffect,useState} from "react";
import {Camera,X} from "lucide-react";
import "./video-connection-manager.css";

export default function VideoConnectionManager({manager,request,onClose,setError,setMessage}){
 const [form,setForm]=useState(manager.connection),[cameras,setCameras]=useState(manager.cameras||[]),[connector,setConnector]=useState(manager.connector),[busy,setBusy]=useState(false),[cameraBusy,setCameraBusy]=useState(false),[timeBusy,setTimeBusy]=useState(false),[testBusy,setTestBusy]=useState(false),[snapshotBusy,setSnapshotBusy]=useState(false),[nvrTime,setNvrTime]=useState(""),[previewUrl,setPreviewUrl]=useState("");
 useEffect(()=>()=>{if(previewUrl)URL.revokeObjectURL(previewUrl)},[previewUrl]);
 const set=(key,value)=>setForm(current=>({...current,[key]:value}));
 const setCamera=(index,key,value)=>setCameras(current=>current.map((camera,cameraIndex)=>cameraIndex===index?{...camera,[key]:value}:camera));
 const addCamera=()=>setCameras(current=>[...current,{cameraKey:"",displayName:"",zone:"OTHER",streamReference:"",active:true,sortOrder:current.length}]);
 const removeCamera=index=>setCameras(current=>current.filter((_,cameraIndex)=>cameraIndex!==index).map((camera,sortOrder)=>({...camera,sortOrder})));
 const save=async event=>{event.preventDefault();setBusy(true);setError("");try{const result=await request(`/api/platform/companies/${manager.company.id}/stores/${manager.store.id}/video-connection`,{method:"PUT",body:JSON.stringify({...form,password:form.password||""})});setForm(current=>({...current,password:"",passwordConfigured:result.passwordConfigured,connectionStatus:result.connectionStatus,timeSyncStatus:"NOT_CHECKED"}));setMessage("Η ρύθμιση σύνδεσης αποθηκεύτηκε. Ο τοπικός connector θα την επιβεβαιώσει στο επόμενο heartbeat.")}catch(error){setError(error.message)}finally{setBusy(false)}};
 const saveCameras=async()=>{setCameraBusy(true);setError("");try{const result=await request(`/api/platform/companies/${manager.company.id}/stores/${manager.store.id}/video-cameras`,{method:"PUT",body:JSON.stringify({cameras})});setCameras(result.cameras);setMessage("Η αντιστοίχιση καμερών σε ζώνες αποθηκεύτηκε. Η πραγματική εικόνα δεν έχει ακόμη δοκιμαστεί.")}catch(error){setError(error.message)}finally{setCameraBusy(false)}};
 const checkTime=async()=>{if(!nvrTime)return setError("Καταχώρισε την ώρα που εμφανίζει τώρα το NVR.");setTimeBusy(true);setError("");try{const result=await request(`/api/platform/companies/${manager.company.id}/stores/${manager.store.id}/video-connection/time-check`,{method:"POST",body:JSON.stringify({nvrTime:new Date(nvrTime).toISOString(),confirmation:true})});setForm(current=>({...current,...result}));setMessage("Η χειροκίνητα επιβεβαιωμένη ώρα NVR συγκρίθηκε και αποθηκεύτηκε.")}catch(error){setError(error.message)}finally{setTimeBusy(false)}};
 const waitCommand=async id=>{for(let attempt=0;attempt<30;attempt+=1){const command=await request(`/api/platform/companies/${manager.company.id}/stores/${manager.store.id}/video-connection/commands/${id}`);if(command.status==="COMPLETED")return command;if(["FAILED","EXPIRED"].includes(command.status))throw new Error(command.errorCode||"Η εντολή του Video Connector απέτυχε.");await new Promise(resolve=>setTimeout(resolve,2000))}throw new Error("Ο Video Connector δεν απάντησε εγκαίρως.")};
 const refresh=async()=>{const next=await request(`/api/platform/companies/${manager.company.id}/stores/${manager.store.id}/video-connection`);setForm(current=>({...current,...next.connection,password:""}));setCameras(next.cameras||[]);setConnector(next.connector)};
 const testConnection=async()=>{setTestBusy(true);setError("");try{const started=await request(`/api/platform/companies/${manager.company.id}/stores/${manager.store.id}/video-connection/test`,{method:"POST",body:"{}"});await waitCommand(started.command.id);await refresh();setMessage("Η πραγματική σύνδεση Dahua ελέγχθηκε επιτυχώς μέσω του τοπικού connector.")}catch(error){setError(error.message)}finally{setTestBusy(false)}};
 const fetchProtectedBlob=async path=>{const token=localStorage.getItem("token"),response=await fetch(path,{headers:token?{Authorization:`Bearer ${token}`}:{}});if(!response.ok){const data=await response.json().catch(()=>({}));throw new Error(data.error||`Σφάλμα ${response.status}`)}return response.blob()};
 const snapshot=async()=>{const camera=cameras.find(item=>item.active!==false&&item.cameraKey);if(!camera)return setError("Αποθήκευσε πρώτα τουλάχιστον μία ενεργή κάμερα.");setSnapshotBusy(true);setError("");try{const started=await request(`/api/platform/companies/${manager.company.id}/stores/${manager.store.id}/video-connection/snapshot`,{method:"POST",body:JSON.stringify({cameraKey:camera.cameraKey})}),command=await waitCommand(started.command.id),blob=await fetchProtectedBlob(command.mediaUrl),url=URL.createObjectURL(blob);setPreviewUrl(current=>{if(current)URL.revokeObjectURL(current);return url});setMessage("Λήφθηκε πραγματικό στιγμιότυπο μέσω ασφαλούς proxy.")}catch(error){setError(error.message)}finally{setSnapshotBusy(false)}};
 const timeLabel=form.timeSyncStatus==="IN_SYNC"?"ΣΥΓΧΡΟΝΙΣΜΕΝΟ":form.timeSyncStatus==="DRIFT"?"ΜΙΚΡΗ ΑΠΟΚΛΙΣΗ":form.timeSyncStatus==="OUT_OF_SYNC"?"ΕΚΤΟΣ ΣΥΓΧΡΟΝΙΣΜΟΥ":"ΔΕΝ ΕΧΕΙ ΕΛΕΓΧΘΕΙ";
 return <div className="platform-modal"><form className="video-connection-dialog" onSubmit={save}>
  <button type="button" className="modal-close" onClick={onClose}><X/></button><h2><Camera/> Video Events · Σύνδεση καταγραφικού</h2><p>{manager.company.name} · {manager.store.name}</p>
  <div className="video-warning">Privacy/GDPR: επεξεργασία μόνο για συγκεκριμένα επιχειρησιακά συμβάντα, με περιορισμένη πρόσβαση και retention. Δεν ανοίγουν κάμερα και δεν αντιγράφουν video ή ολόκληρο CCTV. Η καταγραφή ήχου παραμένει απενεργοποιημένη.</div>
  <div className="video-fields"><label>Κατασκευαστής / πάροχος<input value={form.provider||""} placeholder="π.χ. Hikvision, Dahua, Generic" onChange={e=>set("provider",e.target.value)} required/></label><label>Τρόπος σύνδεσης<select value={form.protocol||"ONVIF"} onChange={e=>set("protocol",e.target.value)}><option value="ONVIF">ONVIF</option><option value="RTSP">RTSP</option><option value="VENDOR_API">Vendor API</option><option value="VENDOR_CLIENT">Vendor Client</option></select></label><label className="wide">Endpoint<input value={form.endpoint||""} placeholder="http://192.168.1.50 ή rtsp://…" onChange={e=>set("endpoint",e.target.value)} required/></label><label>Όνομα χρήστη<input value={form.username||""} autoComplete="off" onChange={e=>set("username",e.target.value)}/></label><label>Κωδικός<input type="password" value={form.password||""} autoComplete="new-password" placeholder={form.passwordConfigured?"Αποθηκευμένος — άφησέ το κενό":"Κωδικός καταγραφικού"} onChange={e=>set("password",e.target.value)}/></label><label>Διόρθωση ώρας (δευτερόλεπτα)<input type="number" min="-86400" max="86400" value={form.timeOffsetSeconds||0} onChange={e=>set("timeOffsetSeconds",e.target.value)}/></label><label>Διατήρηση μεταδεδομένων (ημέρες)<input type="number" min="1" max="365" value={form.retentionDays||30} onChange={e=>set("retentionDays",e.target.value)}/></label><label className="platform-toggle"><input type="checkbox" checked={Boolean(form.active)} onChange={e=>set("active",e.target.checked)}/><span>Η ρύθμιση είναι ενεργή</span></label></div>
  <label className="platform-toggle"><input type="checkbox" checked={Boolean(form.privacyNoticeAcknowledged)} onChange={e=>set("privacyNoticeAcknowledged",e.target.checked)} required/><span>Επιβεβαιώνω event-only χρήση, ενημέρωση προσωπικού, περιορισμένη πρόσβαση, retention και απενεργοποιημένο ήχο.</span></label><div className={`video-status ${connector?.online?"online":"offline"}`}><b>{connector?.online?"ONLINE":form.connectionStatus==="NOT_TESTED"?"ΔΕΝ ΕΧΕΙ ΔΟΚΙΜΑΣΤΕΙ":"OFFLINE"}</b><span>{connector?.deviceName||"Δεν έχει συνδεθεί τοπικός Video Connector"}{connector?.lastSeenAt?` · ${new Date(connector.lastSeenAt).toLocaleString("el-GR")}`:""}</span></div><div className="platform-form-actions"><button disabled={busy}>{busy?"Αποθήκευση…":"Αποθήκευση σύνδεσης"}</button><button type="button" className="secondary" onClick={testConnection} disabled={testBusy||!connector?.online}>{testBusy?"Έλεγχος…":"Πραγματικός έλεγχος σύνδεσης"}</button><button type="button" className="secondary" onClick={snapshot} disabled={snapshotBusy||!connector?.online}>{snapshotBusy?"Λήψη…":"Δοκιμαστική εικόνα"}</button></div>{previewUrl&&<div className="video-preview"><img src={previewUrl} alt="Ασφαλές δοκιμαστικό στιγμιότυπο κάμερας"/></div>}
  <section className="video-time-section"><h3>V03 · Συγχρονισμός ώρας</h3><p>{form.timeCheckSource==="NVR_API"?"Η ώρα διαβάζεται αυτόματα από το NVR API σε κάθε heartbeat.":"Όταν ο connector δεν έχει πρόσβαση στο API, πληκτρολόγησε και επιβεβαίωσε την ώρα που δείχνει το NVR."}</p>{form.timeCheckSource!=="NVR_API"&&<div className="video-time-controls"><label>Τρέχουσα ώρα NVR<input type="datetime-local" step="1" value={nvrTime} onChange={e=>setNvrTime(e.target.value)}/></label><button type="button" className="secondary" onClick={checkTime} disabled={timeBusy}>{timeBusy?"Σύγκριση…":"Επιβεβαίωση και σύγκριση"}</button></div>}<div className={`video-time-result ${form.timeSyncStatus||"NOT_CHECKED"}`}><b>{timeLabel}</b>{form.lastTimeCheckedAt&&<span>Απόκλιση: {form.timeDeviationSeconds} δευτ. · Πηγή: {form.timeCheckSource||"—"} · Τελευταίος έλεγχος: {new Date(form.lastTimeCheckedAt).toLocaleString("el-GR")}</span>}</div>{form.timeCheckSource!=="NVR_API"&&<small>Δεν δηλώνει πραγματική σύνδεση με το NVR: είναι χειροκίνητος έλεγχος.</small>}</section>
  <section className="video-camera-section"><div className="video-camera-heading"><div><h3>V02 · Κάμερες και ζώνες</h3><p>Δήλωσε το κανάλι του καταγραφικού και το σημείο που καλύπτει.</p></div><button type="button" className="secondary" onClick={addCamera}>+ Κάμερα</button></div>{cameras.length===0&&<div className="video-empty">Δεν έχει αντιστοιχιστεί κάμερα.</div>}{cameras.map((camera,index)=><div className="video-camera-row" key={`${index}-${camera.cameraKey}`}><input aria-label="Κανάλι ή ID κάμερας" placeholder="Κανάλι / ID" value={camera.cameraKey} onChange={e=>setCamera(index,"cameraKey",e.target.value)} required/><input aria-label="Όνομα κάμερας" placeholder="Όνομα κάμερας" value={camera.displayName} onChange={e=>setCamera(index,"displayName",e.target.value)} required/><select aria-label="Ζώνη κάμερας" value={camera.zone} onChange={e=>setCamera(index,"zone",e.target.value)}><option value="POS_1">POS 1</option><option value="POS_2">POS 2</option><option value="WAREHOUSE">Αποθήκη</option><option value="ENTRANCE">Είσοδος</option><option value="DELIVERY">Delivery</option><option value="OTHER">Άλλη ζώνη</option></select><input aria-label="Stream ή vendor reference" placeholder="Stream / vendor ref (προαιρετικό)" value={camera.streamReference||""} onChange={e=>setCamera(index,"streamReference",e.target.value)}/><button type="button" className="danger" onClick={()=>removeCamera(index)}>Αφαίρεση</button></div>)}<div className="platform-form-actions"><button type="button" className="secondary" onClick={onClose}>Πίσω</button><button type="button" onClick={saveCameras} disabled={cameraBusy}>{cameraBusy?"Αποθήκευση…":"Αποθήκευση καμερών"}</button></div></section>
 </form></div>;
}
