import React,{useEffect,useMemo,useState} from "react";
import {CalendarDays,Clock3,LogIn,LogOut,RefreshCw,ShieldCheck,Timer,UsersRound} from "lucide-react";

const today=()=>new Date().toISOString().slice(0,10);
const duration=value=>{const total=Number(value||0),hours=Math.floor(total/60),minutes=total%60;return `${hours}ω ${minutes}λ`};
const difference=value=>value===null||value===undefined?"—":`${value>0?"+":value<0?"−":""}${duration(Math.abs(value))}`;
const money=value=>value===null||value===undefined?"—":new Intl.NumberFormat("el-GR",{style:"currency",currency:"EUR"}).format(Number(value));
const time=value=>value?new Intl.DateTimeFormat("el-GR",{hour:"2-digit",minute:"2-digit"}).format(new Date(value)):"—";

export default function WorkforceV2AttendanceTab({company,store,request}){
  const base=`/api/platform/store-modules/companies/${company.id}/stores/${store.id}/workforce-v2`;
  const [date,setDate]=useState(today()),[data,setData]=useState(null),[employeeId,setEmployeeId]=useState(""),[approvalSessionId,setApprovalSessionId]=useState(""),[note,setNote]=useState(""),[busy,setBusy]=useState(false),[error,setError]=useState(""),[notice,setNotice]=useState(""),[dialog,setDialog]=useState(null),[reason,setReason]=useState("");
  const openByEmployee=useMemo(()=>new Set((data?.items||[]).filter(item=>item.status==="OPEN").map(item=>item.employee.id)),[data]);
  const load=async({keepNotice=false}={})=>{setBusy(true);setError("");if(!keepNotice)setNotice("");try{setData(await request(`${base}/attendance?date=${date}`));}catch(e){setError(e.message)}finally{setBusy(false)}};
  useEffect(()=>{load()},[company.id,store.id,date]);
  const ask=eventType=>{if(!employeeId)return setError("Επίλεξε εργαζόμενο.");setReason("");setDialog(eventType)};
  const clock=async()=>{const value=reason.trim();if(value.length<3)return setError("Γράψε αιτιολογία τουλάχιστον 3 χαρακτήρων.");setBusy(true);setError("");try{if(dialog==="APPROVE")await request(`${base}/attendance/${approvalSessionId}/approve-over-8-hours`,{method:"POST",body:JSON.stringify({confirmed:true,reason:value})});else await request(`${base}/attendance/clock`,{method:"POST",body:JSON.stringify({employeeId,eventType:dialog,note:note.trim()||null,confirmed:true,reason:value})});setNotice(dialog==="IN"?"Καταχωρίστηκε έναρξη παρουσίας.":dialog==="OUT"?"Καταχωρίστηκε λήξη παρουσίας και οι πραγματικές ώρες.":"Η υπέρβαση 8 ωρών εγκρίθηκε.");setDialog(null);setApprovalSessionId("");setReason("");setNote("");await load({keepNotice:true});}catch(e){setError(e.message)}finally{setBusy(false)}};
  const askApproval=sessionId=>{setApprovalSessionId(sessionId);setReason("");setDialog("APPROVE")};
  const summary=data?.summary||{open:0,closed:0,workedMinutes:0,workedAmount:0,scheduledMinutes:0,varianceMinutes:0,scheduledSessions:0,review:0};
  return <section className="workforce-v2-tab workforce-attendance-workspace">
    <div className="workforce-v2-section-title"><div><h3><Clock3/> Παρουσίες και κάρτα εργασίας</h3><p>Ελεγχόμενη καταχώριση έναρξης/λήξης, πραγματικές ώρες και σύγκριση μόνο με δημοσιευμένο πρόγραμμα.</p></div><button className="secondary" onClick={()=>load()} disabled={busy}><RefreshCw/> Ανανέωση</button></div>
    {error&&<div className="platform-alert error">{error}</div>}{notice&&<div className="platform-alert success">{notice}</div>}
    {dialog&&<div className="workforce-reason-backdrop" role="dialog" aria-modal="true" aria-label="Αιτιολογία καταχώρισης παρουσίας"><div className="workforce-reason-dialog"><h4>{dialog==="IN"?"Έναρξη παρουσίας":dialog==="OUT"?"Λήξη παρουσίας":"Έγκριση υπέρβασης 8 ωρών"}</h4><p>{dialog==="APPROVE"?"Η υπέρβαση πραγματικών ωρών δεν οριστικοποιείται χωρίς έγκριση Super Admin ή Ιδιοκτήτη. Η αιτιολογία καταγράφεται στο Audit Workforce.":"Η χειροκίνητη κάρτα επιτρέπεται μόνο σε Super Admin ή Ιδιοκτήτη και καταγράφεται στο Audit Workforce."}</p><label>Υποχρεωτική αιτιολογία<textarea autoFocus value={reason} onChange={event=>setReason(event.target.value)} placeholder="Γράψε την αιτιολογία της καταχώρισης"/></label><div><button className="secondary" onClick={()=>setDialog(null)}>Ακύρωση</button><button className="primary" onClick={clock} disabled={busy}>Επιβεβαίωση</button></div></div></div>}
    <div className="workforce-attendance-control"><label>Ημερομηνία<input type="date" value={date} onChange={event=>setDate(event.target.value)}/></label><label>Εργαζόμενος<select value={employeeId} onChange={event=>setEmployeeId(event.target.value)}><option value="">Επίλεξε εργαζόμενο</option>{(data?.employees||[]).map(item=><option key={item.id} value={item.id}>{item.fullName}{openByEmployee.has(item.id)?" · ανοιχτή παρουσία":""}</option>)}</select></label><label>Παρατήρηση<input value={note} onChange={event=>setNote(event.target.value)} placeholder="προαιρετική"/></label><button onClick={()=>ask("IN")} disabled={busy}><LogIn/> Έναρξη</button><button className="secondary" onClick={()=>ask("OUT")} disabled={busy}><LogOut/> Λήξη</button></div>
    <div className="workforce-attendance-metrics"><article><UsersRound/><div><small>Ανοιχτές παρουσίες</small><b>{summary.open}</b></div></article><article><ShieldCheck/><div><small>Ολοκληρωμένες</small><b>{summary.closed}</b></div></article><article><Timer/><div><small>Προγραμματισμένες ώρες</small><b>{duration(summary.scheduledMinutes)}</b></div></article><article><Timer/><div><small>Πραγματικές ώρες</small><b>{duration(summary.workedMinutes)}</b></div></article><article><CalendarDays/><div><small>Απόκλιση προγράμματος</small><b>{difference(summary.varianceMinutes)}</b></div></article><article><CalendarDays/><div><small>Αξία πραγματικών ωρών</small><b>{money(summary.workedAmount)}</b></div></article><article><CalendarDays/><div><small>Χρειάζονται έλεγχο</small><b>{summary.review}</b></div></article></div>
    <div className="workforce-attendance-list">{data?.items?.length?data.items.map(item=><article key={item.id} className={["NEEDS_REVIEW","NEEDS_APPROVAL"].includes(item.status)?"needs-review":""}><div><b>{item.employee.fullName}</b><span>{item.assignment?`${item.assignment.shiftTemplate.name} · ${item.assignment.shiftTemplate.startTime}–${item.assignment.shiftTemplate.endTime}`:"Χωρίς δημοσιευμένη βάρδια"}</span></div><div><small>Έναρξη</small><b>{time(item.startedAt)}</b></div><div><small>Λήξη</small><b>{time(item.endedAt)}</b></div><div><small>Πρόγραμμα</small><b>{item.scheduledMinutes===null?"—":duration(item.scheduledMinutes)}</b></div><div><small>Πραγματικές ώρες</small><b>{duration(item.workedMinutes)}</b></div><div><small>Απόκλιση</small><b>{difference(item.varianceMinutes)}</b></div><div><small>Ωρομίσθιο</small><b>{money(item.hourlyRate)}</b></div><div><small>Αξία ωρών</small><b>{money(item.workedAmount)}</b></div><div><small>Κατάσταση</small><b>{item.status==="OPEN"?"Σε εξέλιξη":item.status==="NEEDS_APPROVAL"?"Χρειάζεται έγκριση":item.status==="NEEDS_REVIEW"?"Χρειάζεται έλεγχο":item.status==="APPROVED"?"Εγκρίθηκε":"Ολοκληρωμένη"}</b></div>{item.status==="NEEDS_APPROVAL"&&data.canApprove?<button onClick={()=>askApproval(item.id)} disabled={busy}><ShieldCheck/> Έγκριση 8+ ωρών</button>:null}{item.issues?.length?<p>{item.issues.map(issue=>issue.message).join(" ")}</p>:null}</article>):<div className="workforce-empty">Δεν υπάρχουν παρουσίες για την επιλεγμένη ημέρα.</div>}</div>
  </section>;
}
