import React,{useEffect,useMemo,useState} from "react";
import {CalendarDays,CheckCircle2,ClipboardCheck,Plus,RefreshCw,ShieldCheck,Trash2} from "lucide-react";

const today=()=>new Date().toISOString().slice(0,10);
const statusText={DRAFT:"Πρόχειρο",PREVIEWED:"Προεπισκόπηση",APPROVED:"Εγκεκριμένο",PUBLISHED:"Δημοσιευμένο",SUPERSEDED:"Αντικαταστάθηκε"};

export default function WorkforceV2ScheduleTab({company,store,request,data}){
  const base=`/api/platform/store-modules/companies/${company.id}/stores/${store.id}/workforce-v2`;
  const [items,setItems]=useState([]),[leaves,setLeaves]=useState([]),[busy,setBusy]=useState(false),[error,setError]=useState(""),[date,setDate]=useState(today()),[type,setType]=useState("WEEK"),[selected,setSelected]=useState(""),[employeeId,setEmployeeId]=useState(""),[templateId,setTemplateId]=useState("");
  const selectedSchedule=useMemo(()=>items.find(item=>item.id===selected),[items,selected]);
  const load=async()=>{setBusy(true);setError("");try{const [s,l]=await Promise.all([request(`${base}/schedules?from=${date}`),request(`${base}/leaves?from=${date}`)]);setItems(s.items||[]);setLeaves(l.items||[])}catch(e){setError(e.message)}finally{setBusy(false)}};
  useEffect(()=>{load()},[company.id,store.id]);
  const reason=label=>window.prompt(`${label} (καταγράφεται στο Audit):`);
  const create=async()=>{const value=reason("Αιτιολογία δημιουργίας προγράμματος");if(!value)return;setBusy(true);try{await request(`${base}/schedules`,{method:"POST",body:JSON.stringify({periodStart:date,periodType:type,confirmed:true,reason:value})});await load()}catch(e){setError(e.message)}finally{setBusy(false)}};
  const transition=async(schedule,status)=>{const value=reason(`Αιτιολογία για ${statusText[status]}`);if(!value)return;setBusy(true);try{await request(`${base}/schedules/${schedule.id}/transition`,{method:"POST",body:JSON.stringify({version:schedule.version,status,confirmed:true,reason:value})});await load()}catch(e){setError(e.message)}finally{setBusy(false)}};
  const assign=async()=>{if(!selectedSchedule||!employeeId||!templateId)return setError("Επίλεξε πρόγραμμα, εργαζόμενο και πρότυπο βάρδιας.");const value=reason("Αιτιολογία ανάθεσης");if(!value)return;setBusy(true);try{await request(`${base}/schedules/${selectedSchedule.id}/assignments`,{method:"POST",body:JSON.stringify({version:selectedSchedule.version,date,employeeId,shiftTemplateId:templateId,confirmed:true,reason:value})});await load()}catch(e){setError(e.message)}finally{setBusy(false)}};
  const removeAssignment=async(schedule,assignment)=>{const value=reason("Αιτιολογία αφαίρεσης ανάθεσης");if(!value)return;setBusy(true);try{await request(`${base}/schedules/${schedule.id}/assignments/${assignment.id}`,{method:"DELETE",body:JSON.stringify({version:schedule.version,confirmed:true,reason:value})});await load()}catch(e){setError(e.message)}finally{setBusy(false)}};
  const approveException=async(schedule,assignment)=>{const ruleCode=Array.isArray(assignment.warningJson)?assignment.warningJson[0]?.ruleCode:null;if(!ruleCode)return;const value=reason("Υποχρεωτική αιτιολογία έγκρισης εξαίρεσης");if(!value)return;setBusy(true);try{await request(`${base}/schedules/${schedule.id}/exceptions`,{method:"POST",body:JSON.stringify({assignmentId:assignment.id,ruleCode,confirmed:true,reason:value})});await load()}catch(e){setError(e.message)}finally{setBusy(false)}};
  return <section className="workforce-v2-tab">
    <div className="workforce-v2-section-title"><div><h3><CalendarDays/> Επαγγελματικό πρόγραμμα βαρδιών</h3><p>Ανάθεση, έλεγχος εξαιρέσεων, έγκριση και δημοσίευση με πλήρες Audit.</p></div><button className="secondary" onClick={load} disabled={busy}><RefreshCw/> Ανανέωση</button></div>
    {error&&<div className="platform-alert error">{error}</div>}
    <div className="workforce-schedule-toolbar"><label>Ημερομηνία<input type="date" value={date} onChange={e=>setDate(e.target.value)}/></label><label>Περίοδος<select value={type} onChange={e=>setType(e.target.value)}><option value="WEEK">Εβδομάδα</option><option value="MONTH">Μήνας</option></select></label><button className="primary" onClick={create} disabled={busy}><Plus/> Νέο πρόχειρο πρόγραμμα</button></div>
    <div className="workforce-schedule-toolbar"><select value={selected} onChange={e=>setSelected(e.target.value)}><option value="">Επίλεξε πρόχειρο πρόγραμμα</option>{items.filter(s=>["DRAFT","PREVIEWED"].includes(s.status)).map(s=><option key={s.id} value={s.id}>{s.periodStart} · {statusText[s.status]}</option>)}</select><select value={employeeId} onChange={e=>setEmployeeId(e.target.value)}><option value="">Εργαζόμενος</option>{data.employees.map(e=><option key={e.id} value={e.id}>{e.fullName}</option>)}</select><select value={templateId} onChange={e=>setTemplateId(e.target.value)}><option value="">Βάρδια</option>{data.shiftTemplates.filter(t=>t.active).map(t=><option key={t.id} value={t.id}>{t.name} · {t.startTime}-{t.endTime}</option>)}</select><button onClick={assign} disabled={busy}>Ανάθεση</button></div>
    <div className="workforce-schedule-grid">{items.length?items.map(schedule=><article key={schedule.id} className="workforce-schedule-card"><div><b>{schedule.periodType==="WEEK"?"Εβδομαδιαίο":"Μηνιαίο"} πρόγραμμα</b><span>{schedule.periodStart} — {schedule.periodEnd}</span></div><strong className={`workforce-status ${schedule.status.toLowerCase()}`}>{statusText[schedule.status]||schedule.status}</strong><small>{schedule.assignments.length} αναθέσεις · έκδοση {schedule.version}</small><div className="workforce-assignment-list">{schedule.assignments.map(assignment=><div key={assignment.id} className={`workforce-assignment-row ${assignment.warningState==="NEEDS_APPROVAL"?"needs-approval":""}`}><span><b>{assignment.date}</b> · {assignment.shiftTemplate.name} · {assignment.employee?.fullName||"ΑΚΑΛΥΠΤΟ"}</span>{assignment.warningState==="NEEDS_APPROVAL"&&<button onClick={()=>approveException(schedule,assignment)} disabled={busy}><ShieldCheck/> Έγκριση εξαίρεσης</button>}{["DRAFT","PREVIEWED"].includes(schedule.status)&&<button className="secondary" onClick={()=>removeAssignment(schedule,assignment)} disabled={busy}><Trash2/> Αφαίρεση</button>}</div>)}</div>{schedule.status==="DRAFT"&&<button onClick={()=>transition(schedule,"PREVIEWED")} disabled={busy}>Προεπισκόπηση</button>}{schedule.status==="PREVIEWED"&&<button onClick={()=>transition(schedule,"APPROVED")} disabled={busy}>Έγκριση</button>}{schedule.status==="APPROVED"&&<button onClick={()=>transition(schedule,"PUBLISHED")} disabled={busy}>Δημοσίευση</button>}</article>):<div className="workforce-empty">Δεν υπάρχει πρόγραμμα για το επιλεγμένο διάστημα.</div>}</div>
    <div className="workforce-leave-summary"><ClipboardCheck/><div><b>Άδειες, ρεπό και απουσίες</b><span>{leaves.length?`${leaves.length} αιτήματα για έλεγχο ή ιστορικό.`:"Δεν υπάρχουν αιτήματα στο επιλεγμένο διάστημα."}</span></div><CheckCircle2/></div>
  </section>;
}
