import React,{useEffect,useState,useRef} from "react";
import {Activity,Clock3,RefreshCw} from "lucide-react";
export default function WorkforceV2EmployeePerformance({employee,base,request,onClose}){
 const[data,setData]=useState(null),[error,setError]=useState(""),[evaluations,setEvaluations]=useState([]),[evaluation,setEvaluation]=useState({category:"Συνεργασία",rating:"",comment:"",evaluationDate:new Date().toISOString().slice(0,10)});
 const [month,setMonth]=useState(()=>new Intl.DateTimeFormat('sv-SE',{timeZone:'Europe/Athens',year:'numeric',month:'2-digit'}).format(new Date()));
 const loadSequence=useRef(0);
 const load=()=>{const seq=++loadSequence.current;setError("");setData(null);Promise.all([request(`${base}/employees/${employee.id}/performance?${month?`month=${encodeURIComponent(month)}`:'days=30'}`),request(`${base}/employees/${employee.id}/evaluations`)]).then(([p,e])=>{if(seq!==loadSequence.current)return;setData(p);setEvaluations(e.items||[])}).catch(e=>{if(seq===loadSequence.current)setError(e.message)})};
 useEffect(()=>{load();return ()=>{loadSequence.current++}},[employee.id,base,month]);
 const h=m=>`${Math.floor((m||0)/60)}ω ${(m||0)%60}λ`;
 const saveEvaluation=async()=>{try{setError("");await request(`${base}/employees/${employee.id}/evaluations`,{method:"POST",body:JSON.stringify(evaluation)});setEvaluation(v=>({...v,rating:"",comment:""}));load()}catch(e){setError(e.message)}};
 const periodControl=<div className="workforce-form-grid"><label>Περίοδος<select value={month?'MONTH':'ROLLING'} onChange={e=>setMonth(e.target.value==='ROLLING'?'':new Intl.DateTimeFormat('sv-SE',{timeZone:'Europe/Athens',year:'numeric',month:'2-digit'}).format(new Date()))}><option value="MONTH">Ημερολογιακός μήνας</option><option value="ROLLING">Τελευταίες 30 ημέρες</option></select></label>{month&&<label>Μήνας<input type="month" min="2000-01" max="2100-12" value={month} onChange={e=>{if(e.target.value)setMonth(e.target.value)}}/></label>}<button className="secondary" onClick={load}><RefreshCw/> Ανανέωση</button></div>;
 if(!data)return <section className="workforce-editor-card">{periodControl}<button className="secondary" onClick={onClose}>Κλείσιμο</button><p>{error?'Δεν φορτώθηκαν στοιχεία.':<><RefreshCw/> Φόρτωση…</>}</p>{error&&<div className="platform-alert error">{error}</div>}</section>;
 return <section className="workforce-editor-card"><div className="workforce-card-title"><div><h4><Activity/> Απόδοση & Ταμεία · {employee.fullName}</h4><p>Πραγματικά στοιχεία και ανθρώπινη αξιολόγηση εμφανίζονται χωριστά.</p></div><button className="secondary" onClick={onClose}>Κλείσιμο</button></div>{error&&<div className="platform-alert error">{error}</div>}
 {periodControl}{data.period.month&&<p>Μήνας {data.period.month} · ώρα Ελλάδας · μόνο το επιλεγμένο κατάστημα. Τα στοιχεία ταμείου αφορούν τις βάρδιες που άνοιξε ο συνδεδεμένος χειριστής· μπορεί να περιλαμβάνουν κινήσεις άλλων χειριστών στην ίδια βάρδια. Οι παρουσίες εντάσσονται με την ώρα έναρξης.</p>}{data.warnings?.map(w=><div className="platform-alert error" key={w}>{w}</div>)}
 <div className="workforce-summary-row"><div><Clock3/><b>{h(data.attendance.workedMinutes)}</b><span>πραγματική εργασία</span></div><div><b>{h(data.attendance.overtimeMinutes)}</b><span>υπερωρία</span></div><div><b>{h(data.attendance.lateMinutes)}</b><span>καθυστερήσεις</span></div><div><b>{data.attendance.needsReview}</b><span>προς έλεγχο</span></div></div>
 <div className="workforce-choice-block"><b>Ταμεία / POS</b>{!data.cashier.linked?<p>Δεν υπάρχει verified POS operator για αυτόν τον εργαζόμενο.</p>:<><div className="workforce-summary-row"><div><b>{data.cashier.shifts}</b><span>βάρδιες</span></div><div><b>{data.cashier.transactions}</b><span>συναλλαγές</span></div><div><b>{Number(data.cashier.totalSales||0).toFixed(2)} €</b><span>πωλήσεις</span></div><div><b>{Number(data.cashier.variance||0).toFixed(2)} €</b><span>{month?"διαφορά κλεισιμάτων μήνα":"διαφορά"}</span></div></div></>}</div>
 {month&&<div className="workforce-choice-block"><b>{data.cashier.openShifts} ανοικτές βάρδιες · {data.cashier.closedShifts} κλεισίματα μήνα</b><p>Οι πωλήσεις προέρχονται από μη ακυρωμένες κινήσεις του μήνα. Οι διαφορές αφορούν ολόκληρες βάρδιες που έκλεισαν μέσα στον μήνα, όχι καταμερισμό τους ανά μήνα.</p><div className="workforce-employee-list">{data.cashier.recentShifts.map(x=><article key={x.id}><b>{x.terminalPos} · {x.status==='OPEN'?'Ανοικτή':'Κλειστή'}</b><p>{new Date(x.openedAt).toLocaleString('el-GR',{timeZone:'Europe/Athens'})} · {x.transactionCount} κινήσεις · {(Number(x.cashSales)+Number(x.cardSales)).toFixed(2)} €</p><small>Βάρδια {x.id} · διαφορά {x.variance==null?'Δεν υπάρχει κλείσιμο στον μήνα':`${x.variance.toFixed(2)} €`}</small></article>)}</div></div>}
 <div className="workforce-choice-block"><b>POS ενέργειες</b><div className="workforce-summary-row"><div><b>{data.posActions.cancellations}</b><span>ακυρώσεις</span></div><div><b>{data.posActions.returns}</b><span>επιστροφές</span></div><div><b>{data.posActions.discounts}</b><span>εκπτώσεις audit</span></div><div><b>{data.posActions.delayed}</b><span>ετεροχρονισμένες</span></div></div></div>
 <div className="workforce-choice-block"><b>Ανθρώπινη αξιολόγηση</b><p>{data.evaluations.message}</p><div className="workforce-form-grid"><label>Κατηγορία<select value={evaluation.category} onChange={e=>setEvaluation(v=>({...v,category:e.target.value}))}>{["Συνεργασία","Συνέπεια","Εξυπηρέτηση","Διαδικασίες","Εκπαίδευση","Άλλο"].map(x=><option key={x}>{x}</option>)}</select></label><label>Ημερομηνία<input type="date" value={evaluation.evaluationDate} onChange={e=>setEvaluation(v=>({...v,evaluationDate:e.target.value}))}/></label><label>Προαιρετικό 1–5<input type="number" min="1" max="5" value={evaluation.rating} onChange={e=>setEvaluation(v=>({...v,rating:e.target.value}))}/></label><label className="span-2">Σχόλιο<textarea rows="3" value={evaluation.comment} onChange={e=>setEvaluation(v=>({...v,comment:e.target.value}))}/></label></div><button onClick={saveEvaluation} disabled={!evaluation.comment.trim()}>Καταχώριση αξιολόγησης</button><div className="workforce-employee-list">{evaluations.map(x=><article key={x.id}><div className="workforce-employee-main"><div><b>{x.category}{x.rating?` · ${x.rating}/5`:""}</b><span>{new Date(x.evaluationDate).toLocaleDateString("el-GR")} · {x.createdByName||"Χρήστης"}</span></div></div><p>{x.comment}</p></article>)}</div></div>
 </section>;
}
