import React,{useEffect,useRef,useState} from "react";
import {Barcode,Search,X} from "lucide-react";

const euro=value=>Number(value||0).toLocaleString("el-GR",{style:"currency",currency:"EUR"});

export default function PosBarcodeRegistrationModal({api,store,onClose,onChanged}){
  const searchRequest=useRef(0);
  const [rows,setRows]=useState([]),[query,setQuery]=useState(""),[selected,setSelected]=useState(null),[barcode,setBarcode]=useState(""),[price,setPrice]=useState(""),[busy,setBusy]=useState(false),[error,setError]=useState("");
  const load=async(q="")=>{const request=++searchRequest.current;setBusy(true);setError("");try{const result=await api(`/api/store-pos/stores/${store.id}/barcode-registration?q=${encodeURIComponent(q)}`);if(request===searchRequest.current)setRows(result.rows||[])}catch(err){if(request===searchRequest.current)setError(err.message)}finally{if(request===searchRequest.current)setBusy(false)}};
  useEffect(()=>{const timer=setTimeout(()=>load(query),query.trim()?220:0);return()=>clearTimeout(timer)},[store.id,query]);
  const choose=row=>{setSelected(row);setBarcode("");setPrice(String(Number(row.salePrice||0).toFixed(2)).replace(".",","));setError("")};
  const save=async()=>{if(!selected||!barcode.trim())return setError("Επίλεξε προϊόν και σκάναρε ή γράψε το νέο barcode.");const salePrice=price.trim()===""?null:Number(price.replace(",","."));if(salePrice!==null&&(!Number.isFinite(salePrice)||salePrice<0))return setError("Η νέα τιμή δεν είναι έγκυρη.");setBusy(true);setError("");try{const result=await api(`/api/store-pos/stores/${store.id}/barcode-registration`,{method:"POST",body:JSON.stringify({productId:selected.id,barcode:barcode.trim(),salePrice})});onChanged?.(result.message);setSelected(null);setBarcode("");setPrice("");await load(query)}catch(err){setError(err.message)}finally{setBusy(false)}};
  return <div className="category-product-overlay pos-price-modal" onMouseDown={e=>e.target===e.currentTarget&&!busy&&onClose()}><section style={{maxWidth:1050}}><header><div><small>POS · ΑΠΟΘΗΚΗ ΚΑΤΑΣΤΗΜΑΤΟΣ</small><h2><Barcode/> Έλεγχος και καταχώρηση νέου Barcode</h2><p>Πολλά barcode, διαφορετικές τιμές, ένα κοινό προϊόν και απόθεμα.</p></div><button onClick={()=>!busy&&onClose()}><X/></button></header><div className="pos-price-body"><div style={{display:"flex",gap:8}}><input autoFocus value={query} onChange={e=>setQuery(e.target.value)} onKeyDown={e=>e.key==="Enter"&&load(query)} placeholder="Όνομα παλιού προϊόντος, SKU ή barcode"/><button className="pos-primary-inline" onClick={()=>load(query)}><Search/> Αναζήτηση</button></div>{error&&<div className="store-pos-alert error">{error}</div>}<div style={{display:"grid",gridTemplateColumns:"minmax(320px,1fr) minmax(320px,1fr)",gap:14,maxHeight:"62vh"}}><div style={{overflow:"auto",border:"1px solid #d7e2df",borderRadius:9}}>{rows.map(row=><button type="button" key={row.id} onClick={()=>choose(row)} style={{display:"block",width:"100%",padding:11,textAlign:"left",border:0,borderBottom:"1px solid #e5ecea",background:selected?.id===row.id?"#dff5ec":"#fff"}}><b>{row.name}</b><small style={{display:"block"}}>{row.sku||"Χωρίς SKU"} · stock {row.currentStock} · {euro(row.salePrice)}</small><small style={{display:"block",color:(row.barcodes||[]).length?"#52635f":"#a33",fontWeight:800}}>{(row.barcodes||[]).length?(row.barcodes||[]).map(code=>`${code.barcode}${code.salePrice==null?"":` (${euro(code.salePrice)})`}`).join(" · "):"ΧΩΡΙΣ BARCODE"}</small></button>)}</div><div>{selected?<div style={{display:"grid",gap:11}}><div><small>ΕΠΙΛΕΓΜΕΝΟ ΠΡΟΪΟΝ</small><h3 style={{margin:"4px 0"}}>{selected.name}</h3><b>Κοινό απόθεμα: {selected.currentStock}</b></div><label>Νέο barcode<input inputMode="numeric" value={barcode} onChange={e=>setBarcode(e.target.value)} placeholder="Σκάναρε ή πληκτρολόγησε"/></label><label>Τιμή πώλησης αυτού του barcode<input inputMode="decimal" value={price} onChange={e=>setPrice(e.target.value)} placeholder="π.χ. 4,20"/></label><button className="pos-primary-inline" disabled={busy} onClick={save}>{busy?"Αποθήκευση…":"Σύνδεση barcode με το προϊόν"}</button><small>Χωρίς δικαίωμα αλλαγής τιμής, η τιμή πηγαίνει για έγκριση. Το barcode παραμένει συνδεδεμένο με το ίδιο προϊόν.</small></div>:<div style={{padding:20,background:"#f5f8f7",borderRadius:9}}>Επίλεξε προϊόν από τη λίστα. Τα προϊόντα χωρίς barcode εμφανίζονται πρώτα.</div>}</div></div></div></section></div>;
}
