import React,{useEffect,useRef,useState} from "react";
import {Pause,Play,Radio,Volume2 as TVolume2,X} from "lucide-react";

export default function PosOnlineRadioPlayer({api,store,onClose,persistentLauncher=false}){
  const audio=useRef(null),[data,setData]=useState(null),[stationId,setStationId]=useState(""),[volume,setVolume]=useState(.7),[playing,setPlaying]=useState(false),[error,setError]=useState(""),[open,setOpen]=useState(!persistentLauncher);
  useEffect(()=>{api(`/api/store-pos/stores/${store.id}/online-radio`).then(result=>{setData(result);setStationId(result.state?.stationId||result.stations?.[0]?.id||"");setVolume(Number(result.state?.volume??.7))}).catch(e=>setError(e.message));return()=>audio.current?.pause()},[store.id]);
  const station=data?.stations?.find(row=>row.id===stationId);
  const persist=(nextStation=stationId,nextVolume=volume)=>api(`/api/store-pos/stores/${store.id}/online-radio/state`,{method:"PUT",body:JSON.stringify({stationId:nextStation||null,volume:nextVolume})}).catch(()=>{});
  const toggle=async()=>{if(!audio.current||!station)return;if(playing){audio.current.pause();setPlaying(false);return}setError("");try{await audio.current.play();setPlaying(true);persist()}catch{setError("Ο σταθμός δεν μπόρεσε να ξεκινήσει. Έλεγξε το stream του σταθμού.")}};
  const choose=id=>{audio.current?.pause();setPlaying(false);setStationId(id);persist(id,volume)};
  const changeVolume=value=>{const next=Number(value);setVolume(next);if(audio.current)audio.current.volume=next;persist(stationId,next)};
  const close=()=>{setOpen(false);onClose?.()};
  return <>{persistentLauncher&&<button type="button" className="store-chat-top-button" onClick={()=>setOpen(true)}>📻 Online Ράδιο{playing?" · Παίζει":""}</button>}{station&&<audio data-pos-radio-background ref={audio} src={station.streamUrl} preload="none" volume={volume} onEnded={()=>setPlaying(false)} onError={()=>{setPlaying(false);setError("Το stream του σταθμού δεν είναι διαθέσιμο.")}}/>}{open&&<div className="category-product-overlay pos-price-modal pos-online-radio-modal" onMouseDown={e=>e.target===e.currentTarget&&close()}><section style={{maxWidth:620}}><header><div><small>MYWORKSTATION POS</small><h2><Radio/> Online Ράδιο</h2><p>Η μουσική συνεχίζει στο background όσο χρησιμοποιείς το POS.</p></div><button onClick={close}><X/></button></header><div className="pos-price-body">{error&&<div className="store-pos-alert error">{error}</div>}{data&&!data.moduleActive?<b>Το πληρωμένο module Online Ράδιο δεν είναι ενεργό για το κατάστημα.</b>:data&&!data.enabled?<b>Το Online Ράδιο είναι απενεργοποιημένο για το κατάστημα.</b>:<><label>Επιτρεπόμενος σταθμός<select value={stationId} onChange={e=>choose(e.target.value)}>{(data?.stations||[]).map(row=><option key={row.id} value={row.id}>{row.name}</option>)}</select></label><button className="pos-primary-inline" disabled={!station} onClick={toggle}>{playing?<><Pause/> Pause</>:<><Play/> Play</>}</button><label><TVolume2/> Ένταση<input type="range" min="0" max="1" step="0.05" value={volume} onChange={e=>changeVolume(e.target.value)}/></label>{data&&(data.stations||[]).length===0&&<small>Δεν έχουν οριστεί ακόμη επιτρεπόμενοι σταθμοί.</small>}</>}</div></section></div>}</>;
}
