import React,{useEffect,useMemo,useState} from "react";
import {Barcode,CreditCard,Keyboard,Pencil,Printer,RefreshCw,RotateCcw,Search,ShoppingCart,Tag,Trash2,Wallet,X} from "lucide-react";
import StorePosStandardModals from "./StorePosStandardModals.jsx";
import "../platform/pos-designer.css";
import "./store-pos.css";

const euro=value=>Number(value||0).toLocaleString("el-GR",{style:"currency",currency:"EUR"});
const fallbackLayout={title:"OPERATOR POS",productColumns:6,showSku:true,buttonFontScale:1,theme:{headerColor:"#033d2f",accentColor:"#087a52",surfaceColor:"#ffffff"},quickKeys:[],categories:[]};
const CATEGORY_PREFIX="CATEGORY::",META_SEP="::MWSMETA::",FONT_SEP="::MWSFONT::";
const decodeStored=value=>{const raw=String(value||"");const [base,meta=""]=raw.split(META_SEP);return{base,codes:meta?meta.split(",").filter(Boolean).map(code=>{try{return decodeURIComponent(code)}catch{return code}}):[]}};
const decodeTitle=value=>{const raw=String(value||"OPERATOR POS"),index=raw.lastIndexOf(FONT_SEP);if(index<0)return{title:raw,fontScale:1};const fontScale=Number(raw.slice(index+FONT_SEP.length));return{title:raw.slice(0,index)||"OPERATOR POS",fontScale:Number.isFinite(fontScale)?fontScale:1}};
const isCategoryQuick=button=>decodeStored(button?.productQuery).base.startsWith(CATEGORY_PREFIX);
const quickCategory=button=>{const base=decodeStored(button?.productQuery).base;return base.startsWith(CATEGORY_PREFIX)?base.slice(CATEGORY_PREFIX.length):""};
const storedCodes=button=>{if(Array.isArray(button?.productCodes)&&button.productCodes.length)return button.productCodes;return decodeStored(button?.categoryName||button?.productQuery||"").codes};
const storedCategoryName=button=>decodeStored(button?.categoryName||button?.productQuery||"").base;
const identifierVariants=value=>{const raw=String(value??"").trim();if(!raw)return[];const variants=new Set(),addPart=part=>{const clean=String(part||"").trim();if(!clean)return;const upper=clean.toLocaleUpperCase("el-GR"),compact=clean.replace(/[^0-9A-Za-zΑ-Ωα-ω]/g,"").toLocaleUpperCase("el-GR");variants.add(upper);variants.add(compact);if(/^\d+$/.test(compact))variants.add(compact.replace(/^0+(?=\d)/,""))};addPart(raw);raw.split("~").forEach(addPart);return[...variants].filter(Boolean)};
const productIdentifiers=product=>[product?.id,product?.sku,product?.sourceCode,product?.masterCode,...(product?.barcodes||[])].flatMap(identifierVariants);
const productMatchesCodes=(product,codes)=>{const wanted=new Set((codes||[]).flatMap(identifierVariants));return wanted.size>0&&productIdentifiers(product).some(value=>wanted.has(value))};
const matchingStoredCodes=(product,codes)=>{const ids=new Set(productIdentifiers(product));return (codes||[]).filter(code=>identifierVariants(code).some(value=>ids.has(value)))};

function LocalNumericPad({value,onChange}){const press=key=>{const current=String(value??"");if(key==="⌫")return onChange(current.slice(0,-1));if(key==="C")return onChange("");if(key===","){if(current.includes(",")||current.includes("."))return;return onChange(`${current||"0"},`)}onChange(`${current}${key}`.replace(/^0+(?=\d)/,""))};return <div style={{display:"grid",gridTemplateColumns:"repeat(3,1fr)",gap:7}}>{[7,8,9,4,5,6,1,2,3,0,",","⌫"].map(key=><button type="button" key={key} onClick={()=>press(String(key))} style={{minHeight:52,border:"1px solid #c7d5d1",borderRadius:8,background:"#fff",fontSize:20,fontWeight:900}}>{key}</button>)}<button type="button" onClick={()=>press("C")} style={{gridColumn:"1/-1",minHeight:44,border:"1px solid #c7d5d1",borderRadius:8,fontWeight:900}}>ΚΑΘΑΡΙΣΜΟΣ</button></div>}

export default function StorePosPanel({api,store,onChanged,canEditCategories=false}){
  const [data,setData]=useState(null),[cart,setCart]=useState([]),[query,setQuery]=useState(""),[categoryModal,setCategoryModal]=useState(null),[activeModal,setActiveModal]=useState(null),[customer,setCustomer]=useState(null),[received,setReceived]=useState(""),[keypadOpen,setKeypadOpen]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState(""),[message,setMessage]=useState(""),[holdCount,setHoldCount]=useState(0),[lineMenu,setLineMenu]=useState(null),[priceEdit,setPriceEdit]=useState(null),[priceValue,setPriceValue]=useState(""),[priceReason,setPriceReason]=useState("Λάθος από χειριστή"),[textEdit,setTextEdit]=useState(null),[textValue,setTextValue]=useState("");
  const audit=async(actionType,details={},reason=null)=>{try{await api(`/api/store-pos/stores/${store.id}/audit`,{method:"POST",body:JSON.stringify({actionType,details,reason})})}catch{}};
  const load=async()=>{setError("");try{const [pos,holds]=await Promise.all([api(`/api/store-pos/stores/${store.id}`),api(`/api/store-pos/stores/${store.id}/holds`).catch(()=>({rows:[]}))]);setData(pos);setHoldCount((holds.rows||[]).length)}catch(err){setError(err.message)}};
  useEffect(()=>{load()},[store.id]);
  const layout=data?.layout||fallbackLayout,products=data?.products||[],titleMeta=decodeTitle(layout.title);
  const quickButtons=(layout.quickKeys||[]).filter(x=>x.visible),categoryButtons=(layout.categories||[]).filter(x=>x.visible),fontScale=Math.max(.8,Math.min(1.8,Number(layout.buttonFontScale||titleMeta.fontScale||1)));
  const searchRows=useMemo(()=>{const q=query.trim().toLocaleLowerCase("el-GR");if(!q)return[];return products.filter(product=>product.name.toLocaleLowerCase("el-GR").includes(q)||String(product.sku||"").toLocaleLowerCase("el-GR").includes(q)||(product.barcodes||[]).some(code=>String(code).includes(q))).slice(0,48)},[products,query]);
  const resolveCategoryProducts=button=>{const codes=storedCodes(button);if(codes.length)return products.filter(product=>productMatchesCodes(product,codes));const name=storedCategoryName(button)||button?.label;return products.filter(product=>String(product.categoryName||"").toLocaleLowerCase("el-GR")===String(name||"").toLocaleLowerCase("el-GR"))};
  const modalProducts=useMemo(()=>categoryModal?resolveCategoryProducts(categoryModal):[],[products,categoryModal]);
  const total=cart.reduce((sum,row)=>sum+Number(row.salePrice||0)*row.quantity,0),receivedNumber=Number(String(received||"").replace(",","."))||0,change=Math.max(0,receivedNumber-total);
  const add=product=>{setCart(current=>{const found=current.find(row=>row.id===product.id);return found?current.map(row=>row.id===product.id?{...row,quantity:row.quantity+1}:row):[...current,{...product,quantity:1}]});audit("CART_ITEM_ADD",{productId:product.id,productName:product.name,sku:product.sku||null});setQuery("")};
  const qty=(id,delta)=>{const row=cart.find(x=>x.id===id);if(!row)return;const next=Math.max(1,row.quantity+delta);setCart(current=>current.map(x=>x.id===id?{...x,quantity:next}:x));audit("CART_QTY_CHANGE",{productId:row.id,productName:row.name,oldQuantity:row.quantity,newQuantity:next})};
  const remove=id=>{const row=cart.find(x=>x.id===id);if(!row)return;setCart(current=>current.filter(x=>x.id!==id));audit("CART_ITEM_REMOVE",{productId:row.id,productName:row.name,sku:row.sku||null,quantity:row.quantity,unitPrice:row.salePrice,total:Number(row.salePrice||0)*row.quantity})};
  const clearCart=()=>{setCart([]);setReceived("");setCustomer(null)};
  const quickProduct=button=>{const needle=decodeStored(button.productQuery||button.label||"").base.trim(),lower=needle.toLocaleLowerCase("el-GR");return products.find(product=>productMatchesCodes(product,[needle])||product.name.toLocaleLowerCase("el-GR").includes(lower))};
  const useQuick=button=>{if(isCategoryQuick(button)){setCategoryModal({...button,categoryName:quickCategory(button),productCodes:storedCodes(button)});return}const product=quickProduct(button);if(product)add(product);else setError(`Δεν βρέθηκε το προϊόν για το κουμπί «${button.label}».`)};
  const removeFromCategory=async product=>{if(!categoryModal||!canEditCategories)return;const codes=matchingStoredCodes(product,storedCodes(categoryModal));if(!codes.length)return setError("Δεν βρέθηκε ο αποθηκευμένος κωδικός αυτού του προϊόντος στην κατηγορία.");if(!window.confirm(`Να αφαιρεθεί το «${product.name}» μόνο από την κατηγορία «${categoryModal.label}» του POS;`))return;setBusy(true);setError("");try{const result=await api(`/api/store-pos/stores/${store.id}/layout/categories/${encodeURIComponent(categoryModal.id)}/products`,{method:"DELETE",body:JSON.stringify({codes})});setData(current=>current?{...current,layout:result.layout,layoutVersion:result.version}:current);setCategoryModal(current=>current?{...current,productCodes:storedCodes(current).filter(code=>!codes.includes(code))}:current);await audit("CATEGORY_PRODUCT_REMOVE",{category:categoryModal.label,productId:product.id,productName:product.name,codes});setMessage(`Το «${product.name}» αφαιρέθηκε από την κατηγορία «${categoryModal.label}».`)}catch(err){setError(err.message)}finally{setBusy(false)}};
  const checkout=async(paymentMethod,payments)=>{if(!cart.length)return;setBusy(true);setError("");setMessage("");try{const result=await api(`/api/store-pos/stores/${store.id}/checkout`,{method:"POST",body:JSON.stringify({paymentMethod,payments,customerId:customer?.id||null,items:cart.map(row=>({productId:row.id,quantity:row.quantity,unitPriceOverride:row.manualPrice?Number(row.salePrice):null,overrideReason:row.manualPrice?(row.priceReason||"Χειροκίνητη αλλαγή τιμής"):null}))})});const resultPayments=result.payments||payments||[{method:paymentMethod,amount:result.total}],paymentText=resultPayments.map(p=>`${p.method==="CASH"?"ΜΕΤΡΗΤΑ":p.method==="CARD"?"ΚΑΡΤΑ":p.method} ${euro(p.amount)}`).join(" + ");clearCart();setMessage(`Η πώληση ${euro(result.total)} καταχωρίστηκε στο BackOffice · ${paymentText}${result.customer?.name?` · ${result.customer.name}`:""}.`);onChanged?.();await load()}catch(err){setError(err.message)}finally{setBusy(false)}};
  const restoreHold=result=>{const restored=(result.items||[]).map(item=>{const base=products.find(p=>p.id===(item.productId||item.id));return base?{...base,quantity:Number(item.quantity||item.qty||1),salePrice:Number(item.effectiveUnitPrice||item.unitPrice||base.salePrice)}:null}).filter(Boolean);setCart(restored);setCustomer(result.customer||null);setReceived("");setHoldCount(v=>Math.max(0,v-1));audit("HOLD_RESTORE",{holdId:result.id,total:result.total||0})};
  const keypad=value=>{if(value==="⌫")return setReceived(v=>v.slice(0,-1));if(value===",")return setReceived(v=>v.includes(",")?v:`${v||"0"},`);setReceived(v=>`${v}${value}`)};
  const standardAction=action=>{setError("");if(action==="CLEAR"){if(cart.length)audit("CART_CANCEL",{items:cart.map(x=>({productId:x.id,name:x.name,quantity:x.quantity,price:x.salePrice})),total});clearCart();return}if(action==="CASH")return checkout("CASH");if(action==="CARD")return checkout("CARD");const map={HOLD:"HOLDS",PAYMENTS:"PAYMENTS",PREP:"PREP",WASTE:"WASTE",MIXED:"MIXED",RETURN:"RETURN"};if(map[action])setActiveModal(map[action])};
  const openPrice=row=>{setPriceEdit(row);setPriceValue(String(Number(row.salePrice||0).toFixed(2)).replace(".",","));setPriceReason("Λάθος από χειριστή")};
  const savePrice=async()=>{if(!priceEdit)return;const next=Number(String(priceValue||"").replace(",","."));if(!Number.isFinite(next)||next<0)return setError("Βάλε έγκυρη τιμή.");const old=Number(priceEdit.salePrice||0);setCart(current=>current.map(x=>x.id===priceEdit.id?{...x,salePrice:next,manualPrice:true,priceReason}:x));await audit("PRICE_CHANGE",{productId:priceEdit.id,productName:priceEdit.name,oldPrice:old,newPrice:next,scope:"CURRENT_TRANSACTION"},priceReason);setPriceEdit(null);setMessage(`Η τιμή του «${priceEdit.name}» έγινε ${euro(next)} μόνο για αυτή τη συναλλαγή.`)};
  const printLabel=async row=>{await audit("LABEL_PRINT",{productId:row.id,productName:row.name,sku:row.sku||null});const popup=window.open("","MWS_LABEL","width=520,height=420");if(!popup)return setError("Ο browser μπλόκαρε το παράθυρο εκτύπωσης.");popup.document.write(`<html><head><title>${row.name}</title><style>body{font-family:Arial;padding:28px}main{border:2px solid #111;padding:20px;width:360px}h1{font-size:26px;margin:0 0 8px}.sku{font-size:15px}.price{font-size:34px;font-weight:800;margin-top:20px}</style></head><body><main><h1>${String(row.name).replace(/[<>]/g,"")}</h1><div class="sku">${String(row.sku||"").replace(/[<>]/g,"")}</div><div class="price">${euro(row.salePrice)}</div></main><script>setTimeout(()=>window.print(),200)<\/script></body></html>`);popup.document.close();setMessage(`Άνοιξε η εκτύπωση ετικέτας για «${row.name}».`);setLineMenu(null)};
  const openTextEditor=(type,row)=>{setTextEdit({type,row});setTextValue(type==="BARCODE"?String(row.barcodes?.[0]||row.sku||""):String(row.displayName||row.name));setLineMenu(null)};
  const saveTextEditor=async()=>{if(!textEdit||!textValue.trim())return;const row=textEdit.row;if(textEdit.type==="BARCODE"){await audit("BARCODE_CHANGE_REQUEST",{productId:row.id,productName:row.name,barcode:textValue.trim()});setMessage(`Το barcode «${textValue.trim()}» καταγράφηκε στα Συμβάντα για έλεγχο στο BackOffice.`)}else{setCart(current=>current.map(x=>x.id===row.id?{...x,displayName:textValue.trim()}:x));await audit("DESCRIPTION_CHANGE",{productId:row.id,productName:row.name,newDescription:textValue.trim()},"Διόρθωση περιγραφής στη συναλλαγή");setMessage(`Η περιγραφή του «${row.name}» άλλαξε για τη συγκεκριμένη συναλλαγή.`)}setTextEdit(null)};
  const lineAction=async type=>{const row=lineMenu;if(!row)return;if(type==="RETURN"){setLineMenu(null);setActiveModal("RETURN");return}if(type==="CHANGE_ITEM"){const negative={...row,id:`exchange-${row.id}-${Date.now()}`,sourceProductId:row.id,displayName:`ΕΠΙΣΤΡΟΦΗ: ${row.name}`,salePrice:-Math.abs(Number(row.salePrice||0)),exchangeReturn:true};setCart(current=>[...current.filter(x=>x.id!==row.id),negative]);setLineMenu(null);setQuery("");setMessage(`Το «${row.name}» μπήκε αρνητικά (${euro(-Math.abs(Number(row.salePrice||0)))})· τώρα χτύπησε το νέο είδος για να εμφανιστεί η διαφορά.`);await audit("ITEM_CHANGE_REQUEST",{oldProductId:row.id,oldProductName:row.name,oldPrice:row.salePrice,negativeAmount:-Math.abs(Number(row.salePrice||0))});return}if(type==="BARCODE")return openTextEditor("BARCODE",row);if(type==="LABEL")return printLabel(row);if(type==="DESCRIPTION")return openTextEditor("DESCRIPTION",row)};

  return <article className="store-pos-card mws-standard-pos" style={{"--pos-head":layout.theme?.headerColor||"#033d2f","--pos-accent":layout.theme?.accentColor||"#087a52","--pos-button-font":fontScale}}>
    <div className="store-pos-top"><div><span>MYWORKSTATION · STANDARD POS</span><h2>{titleMeta.title||"OPERATOR POS"}</h2><small>{store.name} · Έκδοση {data?.layoutVersion||0} · {products.length} ενεργά προϊόντα</small></div><div className="runtime-top-actions"><button onClick={()=>setKeypadOpen(v=>!v)} title="Εμφάνιση / απόκρυψη αριθμητικού πληκτρολογίου"><Keyboard/></button><button onClick={load}><RefreshCw/>Ανανέωση</button></div></div>
    {error&&<div className="store-pos-alert error">{error}</div>}{message&&<div className="store-pos-alert success">{message}</div>}
    <div className={`standard-pos-grid ${keypadOpen?"with-keypad":"without-keypad"}`}>
      <aside className="standard-quick-panel"><header><b>ΓΡΗΓΟΡΑ</b><small>{quickButtons.length}</small></header><div className="standard-quick-grid">{quickButtons.slice(0,20).map((button,index)=>{const categoryButton=isCategoryQuick(button),product=categoryButton?null:quickProduct(button),enabled=categoryButton?Boolean(storedCodes(button).length||quickCategory(button)):Boolean(product);return <button key={button.id} disabled={!enabled} onClick={()=>enabled&&useQuick(button)} style={{background:button.color,fontSize:`calc(13px * var(--pos-button-font))`}}><i>{index+1}</i><span>{button.label||"ΚΕΝΟ"}</span>{product&&<small>{euro(product.salePrice)}</small>}</button>})}</div></aside>
      <section className="standard-sale-panel"><div className="standard-search"><Search/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Barcode, SKU ή αναζήτηση προϊόντος"/>{query&&<button onClick={()=>setQuery("")}><X/></button>}</div>{query&&<div className="standard-search-results">{searchRows.length?searchRows.map(product=><button key={product.id} onClick={()=>add(product)}><b>{product.name}</b><small>{product.sku||""}</small><strong>{euro(product.salePrice)}</strong></button>):<span>Δεν βρέθηκαν προϊόντα.</span>}</div>}<div className="standard-table-head"><span>ΠΟΣ.</span><span>ΕΙΔΟΣ</span><span>STOCK</span><span>ΤΙΜΗ</span><span>ΣΥΝΟΛΟ</span></div><div className="standard-lines">{cart.length===0?<div className="standard-empty"><ShoppingCart/><b>Νέα συναλλαγή</b><span>Πάτησε Γρήγορο, Κατηγορία ή αναζήτησε / σκάναρε προϊόν.</span></div>:cart.map(row=><div className={`standard-line ${row.exchangeReturn?"exchange-return-line":""}`} key={row.id}><div className="line-qty"><button disabled={row.exchangeReturn} onClick={()=>qty(row.id,-1)}>−</button><b>{row.exchangeReturn?`-${Math.abs(row.quantity)}`:row.quantity}</b><button disabled={row.exchangeReturn} onClick={()=>qty(row.id,1)}>+</button></div><button className="line-name line-name-action" onClick={()=>!row.exchangeReturn&&setLineMenu(row)}><b>{row.displayName||row.name}</b>{layout.showSku&&<small>{row.sku||""}</small>}{!row.exchangeReturn&&<Pencil/>}</button><span>{row.currentStock??0}</span><button className="line-price-action" disabled={row.exchangeReturn} onClick={()=>openPrice(row)}><span>{euro(row.salePrice)}</span>{!row.exchangeReturn&&<Pencil/>}</button><div className="line-total"><b>{euro(row.salePrice*row.quantity)}</b><button onClick={()=>remove(row.id)} title="Διαγραφή από καλάθι"><Trash2/></button></div></div>)}</div><div className="standard-category-strip"><header><b>ΚΑΤΗΓΟΡΙΕΣ</b><small>Πατάς κατηγορία → ανοίγει popup προϊόντων</small></header><div>{categoryButtons.slice(0,14).map((button,index)=>{const selected=storedCodes(button),resolved=resolveCategoryProducts(button);return <button key={button.id} onClick={()=>setCategoryModal({...button,categoryName:storedCategoryName(button),productCodes:selected})} style={{background:button.color,fontSize:`calc(12px * var(--pos-button-font))`}}><i>{index+1}</i><span>{button.label}</span><small className="category-count">{selected.length?`${resolved.length}/${selected.length} προϊόντα`:`${resolved.length} προϊόντα`}</small></button>})}</div></div></section>
      {keypadOpen&&<aside className="standard-keypad"><button className="customer-button" onClick={()=>setActiveModal("CUSTOMER")}>ΠΕΛΑΤΗΣ — {customer?.name||"Πελάτης λιανικής"}</button><div className="money-cards"><span>ΕΛΑΒΑ<b>{receivedNumber?euro(receivedNumber):"0,00 €"}</b></span><span>ΡΕΣΤΑ<b>{euro(change)}</b></span></div><div className="number-grid">{[7,8,9,4,5,6,1,2,3,0,",","⌫"].map(value=><button key={value} onClick={()=>keypad(String(value))}>{value}</button>)}</div><button className="clear-money" onClick={()=>setReceived("")}>ΚΑΘΑΡΙΣΜΟΣ</button></aside>}
    </div>
    <div className="standard-action-bar"><button className="danger" onClick={()=>standardAction("CLEAR")}>ΑΚΥΡΩΣΗ</button><button onClick={()=>standardAction("HOLD")}>ΑΝΑΜΟΝΗ{holdCount>0&&<span className="hold-count">{holdCount}</span>}</button><button onClick={()=>standardAction("RETURN")}><RotateCcw/>ΕΠΙΣΤΡΟΦΗ</button><button onClick={()=>standardAction("PAYMENTS")}><Wallet/>ΠΛΗΡΩΜΕΣ</button><button onClick={()=>standardAction("PREP")} disabled={!cart.length}><Printer/>ΠΑΡΑΣΚΕΥΗ</button><button onClick={()=>standardAction("WASTE")} disabled={!cart.length}>ΦΥΡΑ</button><button className="mixed" onClick={()=>standardAction("MIXED")} disabled={!cart.length}>ΜΙΚΤΗ</button><button className="card" onClick={()=>standardAction("CARD")} disabled={!cart.length||busy}><CreditCard/>ΚΑΡΤΑ</button><button className="cash" onClick={()=>standardAction("CASH")} disabled={!cart.length||busy}><Wallet/>ΜΕΤΡΗΤΑ</button><strong><small>ΣΥΝΟΛΟ</small>{euro(total)}</strong></div>
    {categoryModal&&<div className="category-product-overlay" onMouseDown={e=>e.target===e.currentTarget&&setCategoryModal(null)}><section><header><div><small>ΚΑΤΗΓΟΡΙΑ</small><h2>{categoryModal.label}</h2><p>{modalProducts.length} προϊόντα{canEditCategories?" · Διαχείριση ενεργή":""}</p></div><button onClick={()=>setCategoryModal(null)}><X/></button></header><div className="category-product-grid" style={{gridTemplateColumns:`repeat(${Math.max(3,Math.min(7,Number(layout.productColumns||6)))},minmax(120px,1fr))`}}>{modalProducts.length?modalProducts.map(product=><article key={product.id} className="category-product-card" role="button" tabIndex="0" onClick={()=>{add(product);setCategoryModal(null)}} onKeyDown={e=>{if(e.key==="Enter"){add(product);setCategoryModal(null)}}} style={{fontSize:`calc(14px * var(--pos-button-font))`}}>{canEditCategories&&<button className="category-product-remove" title="Αφαίρεση από την κατηγορία" disabled={busy} onClick={e=>{e.stopPropagation();removeFromCategory(product)}}><Trash2/></button>}<b>{product.name}</b><small>{product.sku||""}</small><strong>{euro(product.salePrice)}</strong></article>):<div className="category-empty"><b>Δεν βρέθηκαν τα επιλεγμένα προϊόντα στο κατάστημα.</b><span>Χρειάζεται αντιστοίχιση με τα προϊόντα του BackOffice.</span></div>}</div></section></div>}
    {lineMenu&&<div className="category-product-overlay pos-line-menu" onMouseDown={e=>e.target===e.currentTarget&&setLineMenu(null)}><section><header><div><small>ΕΝΕΡΓΕΙΕΣ ΠΡΟΪΟΝΤΟΣ</small><h2>{lineMenu.name}</h2><p>{lineMenu.sku||"Χωρίς κωδικό"} · {euro(lineMenu.salePrice)}</p></div><button onClick={()=>setLineMenu(null)}><X/></button></header><div className="pos-line-actions"><button onClick={()=>lineAction("RETURN")}><RotateCcw/>Επιστροφή είδους / συναλλαγής</button><button onClick={()=>lineAction("CHANGE_ITEM")}><RefreshCw/>Αλλαγή είδους</button><button onClick={()=>lineAction("BARCODE")}><Barcode/>Προσθήκη / διόρθωση barcode</button><button onClick={()=>lineAction("LABEL")}><Tag/>Εκτύπωση ετικέτας</button><button onClick={()=>lineAction("DESCRIPTION")}><Pencil/>Διόρθωση περιγραφής</button></div></section></div>}
    {priceEdit&&<div className="category-product-overlay pos-price-modal" onMouseDown={e=>e.target===e.currentTarget&&setPriceEdit(null)}><section><header><div><small>ΑΛΛΑΓΗ ΤΙΜΗΣ</small><h2>{priceEdit.name}</h2><p>Τρέχουσα τιμή {euro(priceEdit.salePrice)}</p></div><button onClick={()=>setPriceEdit(null)}><X/></button></header><div className="pos-price-body"><label>Νέα τιμή<input readOnly inputMode="decimal" value={priceValue}/></label><LocalNumericPad value={priceValue} onChange={setPriceValue}/><div className="pos-price-shortcuts"><button onClick={()=>setPriceValue("0")}>Δώρο</button><button onClick={()=>setPriceValue(String(Math.max(0,Number(priceEdit.salePrice||0)-.5).toFixed(2)).replace(".",","))}>-0,50 €</button><button onClick={()=>setPriceValue(String(Math.max(0,Number(priceEdit.salePrice||0)*.9).toFixed(2)).replace(".",","))}>-10%</button></div><label>Αιτιολογία<select value={priceReason} onChange={e=>setPriceReason(e.target.value)}><option>Λάθος από χειριστή</option><option>Επιστροφή από πελάτη</option><option>Δοκιμή</option><option>Εξυπηρέτηση πελάτη</option><option>Άλλη αιτία</option></select></label><button className="pos-primary-inline" onClick={savePrice}>Εφαρμογή μόνο στη συναλλαγή</button><small>Μόνιμη αλλαγή τιμής γίνεται από το BackOffice και καταγράφεται ξεχωριστά.</small></div></section></div>}
    {textEdit&&<div className="category-product-overlay pos-price-modal" onMouseDown={e=>e.target===e.currentTarget&&setTextEdit(null)}><section><header><div><small>{textEdit.type==="BARCODE"?"BARCODE / ΚΩΔΙΚΟΣ":"ΔΙΟΡΘΩΣΗ ΠΕΡΙΓΡΑΦΗΣ"}</small><h2>{textEdit.row.name}</h2></div><button onClick={()=>setTextEdit(null)}><X/></button></header><div className="pos-price-body"><label>{textEdit.type==="BARCODE"?"Νέο barcode / κωδικός":"Νέα περιγραφή"}<input autoFocus inputMode={textEdit.type==="BARCODE"?"numeric":"text"} value={textValue} onChange={e=>setTextValue(e.target.value)}/></label>{textEdit.type==="BARCODE"&&<LocalNumericPad value={textValue} onChange={setTextValue}/>}<button className="pos-primary-inline" onClick={saveTextEditor}>Αποθήκευση</button><small>Η ενέργεια καταγράφεται στα Συμβάντα BackOffice.</small></div></section></div>}
    <StorePosStandardModals active={activeModal} onClose={()=>setActiveModal(null)} api={api} store={store} cart={cart.filter(x=>!x.exchangeReturn)} total={total} customer={customer} onCustomer={c=>{setCustomer(c);audit("CUSTOMER_SELECT",{customerId:c?.id||null,customerName:c?.name||"Πελάτης λιανικής"})}} onRestore={restoreHold} onCartCleared={clearCart} onChanged={onChanged} onCheckout={checkout} setMessage={setMessage} setError={setError} onHoldCount={setHoldCount}/>
    <div className="store-pos-nonfiscal">KAT TEST / PILOT: η πώληση καταγράφεται στο MyWorkStation ως NON_FISCAL και δεν στέλνει εντολή σε RBS, CapDriver ή πραγματική ταμειακή.</div>
  </article>;
}
