import React,{useEffect,useState} from "react";
import {Coins,ShieldCheck,WalletCards} from "lucide-react";
import "../cloud/cash-control.css";

const n=v=>Number(String(v??0).replace(",","."))||0;
const money=v=>n(v).toLocaleString("el-GR",{style:"currency",currency:"EUR"});

export default function StoreShiftClosePanel({api,store,onClosed}){
 const [data,setData]=useState(null),[showExpectedAmounts,setShowExpectedAmounts]=useState(false);
 const [form,setForm]=useState({cashSales:"0",cardSales:"0",eftposTotal:"",expenses:"0",drawer:"",custody:"",coins:"",safe:"",note:""});
 const [loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState("");
 const load=async()=>{setLoading(true);setError("");try{const [overview,pos]=await Promise.all([api(`/api/cash/stores/${store.id}/overview`),api(`/api/store-pos/stores/${store.id}`).catch(()=>({access:{}}))]);const canSee=Boolean(pos?.access?.initialCash);setShowExpectedAmounts(canSee);setData(overview);if(overview.openSession){let summary={};try{summary=(await api(`/api/transactions/stores/${store.id}/overview`)).summary||{}}catch{}setForm(f=>({...f,cashSales:String(summary.cashSales??0),cardSales:String(summary.cardSales??0),expenses:String(summary.expensesTotal??0),drawer:canSee?String(overview.openSession.openingDrawer??0):"",custody:canSee?String(overview.openSession.openingCustody??0):"",coins:canSee?String(overview.openSession.openingCoins??0):"",safe:canSee?String(overview.openSession.openingSafe??0):""}))}}catch(e){setError(e.message)}finally{setLoading(false)}};
 useEffect(()=>{load()},[store.id]);
 const set=(key,value)=>setForm(f=>({...f,[key]:value}));
 const close=async event=>{event.preventDefault();if(!data?.openSession)return;const previousSafe=n(data?.suggestedOpening?.safe),openingSafe=n(data.openSession.openingSafe),expectedSafe=Math.max(previousSafe,openingSafe),actualSafe=n(form.safe),shortage=expectedSafe-actualSafe;if(shortage>0.009){const detail=showExpectedAmounts?`Αναμενόμενο: ${money(expectedSafe)}\nΚαταμετρήθηκε: ${money(actualSafe)}\nΈλλειμμα: ${money(shortage)}`:`Έλλειμμα: ${money(shortage)}`;if(!window.confirm(`ΠΡΟΣΟΧΗ — ΕΛΛΕΙΜΜΑ ΧΡΗΜΑΤΟΚΙΒΩΤΙΟΥ\n\n${detail}\n\nΘέλεις να συνεχίσεις το κλείσιμο;`))return}setBusy(true);setError("");try{await api(`/api/cash/sessions/${data.openSession.id}/close`,{method:"POST",body:JSON.stringify({cashSales:n(form.cashSales),cardSales:n(form.cardSales),eftposTotal:n(form.eftposTotal),expenses:n(form.expenses),drawer:n(form.drawer),custody:n(form.custody),coins:n(form.coins),safe:n(form.safe),note:form.note})});onClosed?.();setTimeout(()=>{const exit=[...document.querySelectorAll("button")].find(button=>/^Έξοδος$/i.test(String(button.textContent||"").trim()));exit?.click()},0)}catch(err){setError(err.message);setBusy(false)}};
 if(loading)return <div className="cloud-loading">Φόρτωση κλεισίματος βάρδιας…</div>;
 if(!data?.openSession)return <div className="cloud-empty"><b>Η βάρδια είναι κλειστή.</b></div>;
 return <article className="cloud-panel cash-module"><div className="cloud-panel-head cash-heading"><div><h3><WalletCards/>Κλείσιμο & Παράδοση βάρδιας</h3><p>Καταχώρισε την πραγματική καταμέτρηση παράδοσης. Ο αναλυτικός Έλεγχος Ταμείου γίνεται αποκλειστικά στο BackOffice.</p></div></div>{error&&<div className="cloud-alert cloud-error">{error}</div>}<form className="cash-form" onSubmit={close}>{showExpectedAmounts&&<><Money label="Πωλήσεις μετρητών" value={form.cashSales} readOnly/><Money label="Πωλήσεις καρτών" value={form.cardSales} readOnly/><Money label="Έξοδα / πληρωμές" value={form.expenses} readOnly/></>}<Money label="Σύνολο EFTPOS" value={form.eftposTotal} onChange={v=>set("eftposTotal",v)}/><div className="cash-divider cash-wide">Πραγματική καταμέτρηση παράδοσης</div><Money icon={<WalletCards/>} label="Συρτάρι" value={form.drawer} onChange={v=>set("drawer",v)}/><Money icon={<ShieldCheck/>} label="Φύλαξη" value={form.custody} onChange={v=>set("custody",v)}/><Money icon={<Coins/>} label="Κέρματα" value={form.coins} onChange={v=>set("coins",v)}/><Money icon={<ShieldCheck/>} label="Χρηματοκιβώτιο" value={form.safe} onChange={v=>set("safe",v)}/><label className="cash-wide">Εκκρεμότητες επόμενης βάρδιας<input value={form.note} onChange={e=>set("note",e.target.value)} placeholder="Μήνυμα παράδοσης"/></label><button className="cash-submit" disabled={busy}>{busy?"Κλείσιμο…":"Κλείσιμο και παράδοση"}</button></form></article>;
}

function Money({icon,label,value,onChange,readOnly=false}){return <label>{icon}{label}<input inputMode="decimal" value={value} readOnly={readOnly} onChange={e=>onChange?.(e.target.value)}/></label>}
