import React,{useEffect,useState} from "react";
import {Coins,ShieldCheck,WalletCards} from "lucide-react";
import "../cloud/cash-control.css";
const n=v=>Number(String(v??0).replace(",","."))||0;
const money=v=>n(v).toLocaleString("el-GR",{style:"currency",currency:"EUR"});
export default function StoreShiftClosePanel({api,store,onClosed}){
 const [data,setData]=useState(null),[form,setForm]=useState({cashSales:"0",cardSales:"0",eftposTotal:"0",expenses:"0",drawer:"0",custody:"0",coins:"0",safe:"0",note:""}),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState(""),[message,setMessage]=useState("");
 const load=async()=>{setLoading(true);setError("");try{const o=await api(`/api/cash/stores/${store.id}/overview`);setData(o);if(o.openSession){let s={};try{s=(await api(`/api/transactions/stores/${store.id}/overview`)).summary||{}}catch{}setForm(f=>({...f,cashSales:String(s.cashSales??0),cardSales:String(s.cardSales??0),expenses:String(s.expensesTotal??0),drawer:String(o.openSession.openingDrawer??0),custody:String(o.openSession.openingCustody??0),coins:String(o.openSession.openingCoins??0),safe:String(o.openSession.openingSafe??0)}))}}catch(e){setError(e.message)}finally{setLoading(false)}};
 useEffect(()=>{load()},[store.id]);const set=(k,v)=>setForm(f=>({...f,[k]:v}));
 const close=async e=>{e.preventDefault();if(!data?.openSession)return;const expectedSafe=Math.max(n(data?.suggestedOpening?.safe),n(data.openSession.openingSafe)),actualSafe=n(form.safe),shortage=expectedSafe-actualSafe;if(shortage>0.009&&!window.confirm(`ΠΡΟΣΟΧΗ — ΕΛΛΕΙΜΜΑ ΧΡΗΜΑΤΟΚΙΒΩΤΙΟΥ\n\nΑναμενόμενο: ${money(expectedSafe)}\nΚαταμετρήθηκε: ${money(actualSafe)}\nΈλλειμμα: ${money(shortage)}\n\nΘέλεις να συνεχίσεις το κλείσιμο;`))return;setBusy(true);setError("");setMessage("");try{await api(`/api/cash/sessions/${data.openSession.id}/close`,{method:"POST",body:JSON.stringify({cashSales:n(form.cashSales),cardSales:n(form.cardSales),eftposTotal:n(form.eftposTotal),expenses:n(form.expenses),drawer:n(form.drawer),custody:n(form.custody),coins:n(form.coins),safe:n(form.safe),note:form.note})});setMessage("Η βάρδια έκλεισε και η παράδοση καταγράφηκε.");await load();onClosed?.()}catch(err){setError(err.message)}finally{setBusy(false)}};
 if(loading)return <div className="cloud-loading">Φόρτωση κλεισίματος βάρδιας…</div>;if(!data?.openSession)return <div className="cloud-empty"><b>Η βάρδια είναι κλειστή.</b></div>;
 return <article className="cloud-panel cash-module"><div className="cloud-panel-head cash-heading"><div><h3><WalletCards/>Κλείσιμο & Παράδοση βάρδιας</h3><p>Καταχώρισε μόνο την πραγματική καταμέτρηση παράδοσης.</p></div></div>{error&&<div className="cloud-alert cloud-error">{error}</div>}{message&&<div className="cloud-alert cloud-success">{message}</div>}<form className="cash-form" onSubmit={close}><Money label="Πωλήσεις μετρητών" value={form.cashSales} readOnly/><Money label="Πωλήσεις καρτών" value={form.cardSales} readOnly/><Money label="Σύνολο EFTPOS" value={form.eftposTotal} onChange={v=>set("eftposTotal",v)}/><Money label="Έξοδα / πληρωμές" value={form.expenses} readOnly/><div className="cash-divider cash-wide">Πραγματική καταμέτρηση παράδοσης</div><Money icon={<WalletCards/>} label="Συρτάρι" value={form.drawer} onChange={v=>set("drawer",v)}/><Money icon={<ShieldCheck/>} label="Φύλαξη" value={form.custody} onChange={v=>set("custody",v)}/><Money icon={<Coins/>} label="Κέρματα" value={form.coins} onChange={v=>set("coins",v)}/><Money icon={<ShieldCheck/>} label="Χρηματοκιβώτιο" value={form.safe} onChange={v=>set("safe",v)}/><label className="cash-wide">Εκκρεμότητες επόμενης βάρδιας<input value={form.note} onChange={e=>set("note",e.target.value)} placeholder="Μήνυμα παράδοσης"/></label><button className="cash-submit" disabled={busy}>{busy?"Κλείσιμο…":"Κλείσιμο και παράδοση"}</button></form></article>;
}
function Money({icon,label,value,onChange,readOnly=false}){return <label>{icon}{label}<input inputMode="decimal" value={value} readOnly={readOnly} onChange={e=>onChange?.(e.target.value)}/></label>}
