import React,{useEffect,useMemo,useState} from "react";
import {CreditCard,RefreshCw,Wallet,X} from "lucide-react";
import "./store-netlink.css";
const euro=value=>Number(value||0).toLocaleString("el-GR",{style:"currency",currency:"EUR"});
const groupsFromMenu=menu=>{const source=menu?.data??menu;if(Array.isArray(source))return source;if(Array.isArray(source?.groups))return source.groups;if(Array.isArray(source?.productGroups))return source.productGroups;if(Array.isArray(source?.items))return source.items;return []};
const productsFromGroup=g=>Array.isArray(g?.products)?g.products:Array.isArray(g?.items)?g.items:[];
const productIdOf=p=>String(p?.productId??p?.id??p?.code??"");
const productNameOf=p=>String(p?.name??p?.label??p?.description??productIdOf(p));
const groupNameOf=(g,i)=>String(g?.name??g?.label??g?.description??`Ομάδα ${i+1}`);
const schemaOf=p=>p?.payloadSchema??p?.schema??p?.payload?.schema??null;
const flowOf=p=>String(p?.flow??p?.flowType??"execute").toLowerCase();
const providerData=v=>v?.data??v??{};
const amountOf=(p,prepared)=>Number(prepared?.amount??providerData(prepared?.result)?.amount??p?.amount??p?.price??0);
function DynamicField({name,spec,value,onChange,required}){const label=spec?.title||spec?.description||name,options=Array.isArray(spec?.enum)?spec.enum:null;if(options)return <label className="netlink-field"><span>{label}{required?" *":""}</span><select value={value??""} onChange={e=>onChange(e.target.value)}><option value="">Επιλογή...</option>{options.map(x=><option key={String(x)}>{String(x)}</option>)}</select></label>;return <label className="netlink-field"><span>{label}{required?" *":""}</span><input value={value??""} onChange={e=>onChange(e.target.value)}/></label>}
export default function StoreNetlinkModal({api,store,onClose,onCompleted,onError}){
 const [status,setStatus]=useState(null),[config,setConfig]=useState(null),[menu,setMenu]=useState(null),[selected,setSelected]=useState(null),[payload,setPayload]=useState({}),[draft,setDraft]=useState(null),[busy,setBusy]=useState(false),[error,setError]=useState(""),[critical,setCritical]=useState("");
 const groups=useMemo(()=>groupsFromMenu(menu),[menu]),schema=schemaOf(selected),properties=schema?.properties||{},required=new Set(schema?.required||[]);
 const load=async()=>{setBusy(true);try{const [s,c,m]=await Promise.all([api("/api/netlink/status"),api(`/api/netlink/stores/${store.id}/config`),api("/api/netlink/menu")]);setStatus(s);setConfig(c);setMenu(m)}catch(e){setError(e.message);onError?.(e)}finally{setBusy(false)}};useEffect(()=>{load()},[store.id]);
 const validate=()=>{if(!config?.configured)return "Χρειάζεται αντιστοίχιση δύο προϊόντων POS: Κάρτες Κινητής και Παροχή Υπηρεσίας.";if(config.saleProduct?.trackStock||config.serviceFeeProduct?.trackStock)return "Τα προϊόντα Netlink πρέπει να είναι χωρίς απόθεμα.";for(const k of required)if(payload[k]===undefined||payload[k]===null||payload[k]==="")return `Συμπλήρωσε το πεδίο ${k}.`;return ""};
 const continueFlow=async()=>{const v=validate();if(v)return setError(v);setBusy(true);setError("");try{const productId=productIdOf(selected),requestId=crypto.randomUUID();let prepared=null;if(flowOf(selected)==="prepare")prepared=await api("/api/netlink/prepare",{method:"POST",body:JSON.stringify({storeId:store.id,productId,payload,requestId})});const amount=amountOf(selected,prepared);if(!(amount>0))throw new Error("Μη έγκυρη αξία κάρτας.");setDraft({product:selected,productId,payload,requestId,prepared,amount,serviceFee:Number(config.serviceFeeAmount||.5),status,config})}catch(e){setError(e.message)}finally{setBusy(false)}};
 const pay=async paymentMethod=>{if(!draft||busy)return;if(!draft.status?.executeEnabled)return setError("Το staging execute είναι κλειδωμένο.");if(!draft.status?.testMode)return setError("Η δοκιμή χωρίς ταμειακή επιτρέπεται μόνο σε TEST MODE.");setBusy(true);setError("");setCritical("");let sale=null;try{const total=Number((draft.amount+draft.serviceFee).toFixed(2));sale=await api(`/api/store-pos/stores/${store.id}/checkout`,{method:"POST",body:JSON.stringify({paymentMethod,items:[{productId:draft.config.saleProduct.id,quantity:1,unitPriceOverride:draft.amount,overrideReason:`Netlink mobile card ${draft.productId}`},{productId:draft.config.serviceFeeProduct.id,quantity:1,unitPriceOverride:draft.serviceFee,overrideReason:"Netlink παροχή υπηρεσίας"}]})});const saleId=sale?.id||sale?.saleId;if(!saleId)throw new Error("Δεν επέστρεψε Sale ID.");if(Math.abs(Number(sale.total)-total)>.01)throw new Error(`Λάθος σύνολο POS: αναμενόταν ${total.toFixed(2)}€.`);const confirmation=draft.prepared?.result?providerData(draft.prepared.result):undefined;const executed=await api("/api/netlink/execute",{method:"POST",body:JSON.stringify({storeId:store.id,productId:draft.productId,payload:draft.payload,requestId:draft.requestId,paymentMethod,saleId,testRun:true,...(confirmation?{confirmation}:{})})});onCompleted?.({sale,executed,draft,paymentMethod});setDraft(null)}catch(e){if(sale?.id||sale?.saleId)setCritical(`ΠΡΟΣΟΧΗ: Η πώληση καταχωρίστηκε αλλά η Netlink απέτυχε: ${e.message}`);else setError(e.message);onError?.(e)}finally{setBusy(false)}};
 return <div className="netlink-overlay"><div className="netlink-modal"><header><div><b><CreditCard size={19}/> NETLINK</b><small>Κάρτες κινητής + παροχή υπηρεσίας</small></div><button onClick={onClose}><X/></button></header>{error&&<div className="netlink-error">{error}</div>}{critical&&<div className="netlink-critical">{critical}</div>}{!config?.configured&&!busy&&<div className="netlink-warning">Ρύθμισε προϊόν «ΚΑΡΤΕΣ ΚΙΝΗΤΗΣ» και ξεχωριστό προϊόν «ΠΑΡΟΧΗ ΥΠΗΡΕΣΙΑΣ».</div>}<div className="netlink-toolbar"><span><b>{store.name}</b>{config?.configured&&<small> · Κάρτα: {config.saleProduct.name} · Υπηρεσία: {config.serviceFeeProduct.name}</small>}</span><button onClick={load}><RefreshCw size={15}/> Ανανέωση</button></div>{draft?<div className="netlink-payment"><small>ΑΝΑΛΥΣΗ ΠΛΗΡΩΜΗΣ</small><h2>{productNameOf(draft.product)}</h2><p>Κάρτα κινητής: <b>{euro(draft.amount)}</b></p><p>Παροχή υπηρεσίας: <b>{euro(draft.serviceFee)}</b></p><strong>Σύνολο: {euro(draft.amount+draft.serviceFee)}</strong><p>Στη δοκιμή δημιουργούνται δύο γραμμές στην ίδια POS πώληση. Στην παραγωγή η έκδοση Netlink θα γίνει μόνο μετά την επιβεβαίωση της φορολογικής απόδειξης.</p><div><button className="netlink-pay cash" onClick={()=>pay("CASH")}><Wallet/>ΜΕΤΡΗΤΑ</button><button className="netlink-pay card" onClick={()=>pay("CARD")}><CreditCard/>ΚΑΡΤΑ</button></div></div>:!selected?<div className="netlink-groups">{groups.map((g,i)=><section key={g?.id||i}><h3>{groupNameOf(g,i)}</h3><div className="netlink-products">{productsFromGroup(g).map(p=><button key={productIdOf(p)} onClick={()=>{setSelected(p);setPayload({})}}><b>{productNameOf(p)}</b>{p?.amount!=null&&<span>{euro(p.amount)}</span>}</button>)}</div></section>)}</div>:<div className="netlink-form"><button className="netlink-back" onClick={()=>setSelected(null)}>← Προϊόντα</button><h2>{productNameOf(selected)}</h2>{Object.keys(properties).map(k=><DynamicField key={k} name={k} spec={properties[k]} value={payload[k]} required={required.has(k)} onChange={v=>setPayload(x=>({...x,[k]:v}))}/>)}<button className="netlink-primary" disabled={busy} onClick={continueFlow}>ΣΥΝΕΧΕΙΑ</button></div>}</div></div>;
}
