import React,{useEffect,useMemo,useRef,useState} from "react";
import {ArrowLeft,Minus,Plus,RefreshCw,Send} from "lucide-react";
import {matchesGreekSearch} from "../../utils/greek-search.js";
import "./store-mobile-waiter.css";

const euro=value=>Number(value||0).toLocaleString("el-GR",{style:"currency",currency:"EUR"});
const allergens=["ΓΛΟΥΤΕΝΗ","ΚΑΡΚΙΝΟΕΙΔΗ","ΑΥΓΑ","ΨΑΡΙΑ","ΑΡΑΧΙΔΕΣ","ΣΟΓΙΑ","ΓΑΛΑ","ΞΗΡΟΙ ΚΑΡΠΟΙ","ΣΕΛΙΝΟ","ΜΟΥΣΤΑΡΔΑ","ΣΟΥΣΑΜΙ","ΘΕΙΩΔΗ","ΛΟΥΠΙΝΟ","ΜΑΛΑΚΙΑ"];

export default function StoreMobileWaiter({api,store,operator,onBack}){
  const [tables,setTables]=useState(null),[products,setProducts]=useState([]),[areaId,setAreaId]=useState("ALL"),[tableId,setTableId]=useState(""),[query,setQuery]=useState(""),[lines,setLines]=useState([]),[busy,setBusy]=useState(false),[error,setError]=useState(""),[message,setMessage]=useState("");
  const sending=useRef(false);
  const refresh=async()=>{const result=await api(`/api/store-pos/stores/${store.id}/table-service`);setTables(result);setTableId(current=>result.tables.some(table=>table.id===current)?current:"");return result};
  useEffect(()=>{let alive=true;Promise.all([api(`/api/store-pos/stores/${store.id}/table-service`),api(`/api/store-pos/stores/${store.id}`)]).then(([result,pos])=>{if(!alive)return;setTables(result);setProducts(pos.products||[])}).catch(err=>{if(alive)setError(err.message)});return()=>{alive=false}},[store.id]);
  const visibleTables=(tables?.tables||[]).filter(table=>areaId==="ALL"||table.areaId===areaId);
  const order=(tables?.orders||[]).find(row=>row.tableId===tableId);
  const found=useMemo(()=>{const term=query.trim();if(!term)return[];return products.filter(product=>matchesGreekSearch(term,product.name)||String(product.sku||"").toLocaleLowerCase("el-GR").includes(term.toLocaleLowerCase("el-GR"))||(product.barcodes||[]).some(code=>String(code).includes(term))).slice(0,30)},[products,query]);
  const change=(id,patch)=>setLines(current=>current.map(line=>line.id===id?{...line,...patch}:line));
  const add=product=>{setLines(current=>{const existing=current.find(line=>line.id===product.id);return existing?current.map(line=>line.id===product.id?{...line,quantity:line.quantity+1}:line):[...current,{id:product.id,name:product.name,price:Number(product.salePrice||0),quantity:1,note:"",allergens:[]} ]});setQuery("")};
  const send=async()=>{if(sending.current||!tableId||!lines.length)return;if(!navigator.onLine){setError("Η αποστολή τραπεζιού απαιτεί σύνδεση. Δεν αποθηκεύτηκε offline.");return}const table=tables?.tables.find(row=>row.id===tableId);if(!window.confirm(`Αποστολή ${lines.reduce((sum,line)=>sum+line.quantity,0)} τεμαχίων στο ${table?.name};`))return;sending.current=true;setBusy(true);setError("");setMessage("");try{const result=await api(`/api/store-pos/stores/${store.id}/table-orders`,{method:"POST",body:JSON.stringify({tableId,items:lines.map(line=>({productId:line.id,quantity:line.quantity,notes:line.note.trim()||null,allergens:line.allergens}))})});setLines([]);setMessage(`Στάλθηκε ο γύρος ${result.roundNumber} στο ${result.tableName} · ${euro(result.addedTotal)}. Παρασκευή: ${(result.preparationBatches||[]).map(batch=>batch.productionStation).join(", ")||"χωρίς πόστο"}.`);try{await refresh()}catch(refreshError){setError(`Ο γύρος στάλθηκε, αλλά η ανανέωση απέτυχε: ${refreshError.message}. Πάτησε Ανανέωση για να τον δεις.`)}}catch(err){setError(`${err.message} Έλεγξε πρώτα το τραπέζι και την ουρά πριν επιχειρήσεις ξανά, για να μην σταλεί δεύτερος γύρος.`);try{await refresh()}catch{}}finally{sending.current=false;setBusy(false)}};
  return <div className="mobile-waiter"><header><button type="button" onClick={onBack}><ArrowLeft/> POS</button><div><small>ΑΣΥΡΜΑΤΗ ΠΑΡΑΓΓΕΛΙΟΛΗΨΙΑ</small><h1>{store.name}</h1><span>{operator?.fullName||"Χειριστής"}</span></div><button type="button" onClick={()=>refresh().catch(err=>setError(err.message))} aria-label="Ανανέωση τραπεζιών"><RefreshCw/></button></header>
    {error&&<p role="alert" className="mobile-waiter-error">{error}</p>}{message&&<p role="status" className="mobile-waiter-message">{message}</p>}
    {!tables?<p>Φόρτωση τραπεζιών…</p>:<><nav aria-label="Σάλες"><button className={areaId==="ALL"?"selected":""} onClick={()=>setAreaId("ALL")}>Όλες</button>{tables.areas.map(area=><button key={area.id} className={areaId===area.id?"selected":""} onClick={()=>{setAreaId(area.id);setTableId("")}}>{area.name}</button>)}</nav>
    <section><h2>Τραπέζι</h2><div className="mobile-waiter-tables">{visibleTables.map(table=>{const active=(tables.orders||[]).find(row=>row.tableId===table.id);return <button key={table.id} className={tableId===table.id?"selected":""} onClick={()=>{if(lines.length&&tableId&&tableId!==table.id){if(!window.confirm("Αλλαγή τραπεζιού; Τα μη σταλμένα είδη θα αφαιρεθούν."))return;setLines([])}setTableId(table.id)}}><b>{table.name}</b><small>{active?`${active.status} · ${euro(active.total)}`:"ΕΛΕΥΘΕΡΟ"}</small></button>})}</div></section>
    {tableId&&<><section><h2>{order?`Νέος γύρος · ${order.tableName}`:"Νέα παραγγελία"}</h2>{order&&<p>Υπάρχων λογαριασμός {euro(order.total)}. Τα νέα είδη προστίθενται στον ίδιο λογαριασμό.</p>}<label>Αναζήτηση προϊόντος<input value={query} onChange={event=>setQuery(event.target.value)} placeholder="Όνομα, SKU ή barcode" autoComplete="off"/></label>{query&&<div className="mobile-waiter-results">{found.map(product=><button key={product.id} onClick={()=>add(product)}><span>{product.name}<small>{product.sku}</small></span><b>{euro(product.salePrice)} <Plus size={16}/></b></button>)}{!found.length&&<p>Δεν βρέθηκε προϊόν.</p>}</div>}</section>
    <section><h2>Νέα είδη</h2>{lines.map(line=><article key={line.id}><div className="mobile-waiter-line"><b>{line.name}</b><span>{euro(line.price*line.quantity)}</span></div><div className="mobile-waiter-quantity"><button aria-label={`Μείωση ${line.name}`} onClick={()=>line.quantity===1?setLines(current=>current.filter(row=>row.id!==line.id)):change(line.id,{quantity:line.quantity-1})}><Minus/></button><strong>{line.quantity}</strong><button aria-label={`Αύξηση ${line.name}`} onClick={()=>change(line.id,{quantity:Math.min(999,line.quantity+1)})}><Plus/></button></div><label>Σημείωση παρασκευής<input maxLength={250} value={line.note} onChange={event=>change(line.id,{note:event.target.value})} placeholder="Προαιρετική, χωριστή από αλλεργιογόνα"/></label><details><summary>Αλλεργιογόνα ({line.allergens.length})</summary><div className="mobile-waiter-allergens">{allergens.map(allergen=><label key={allergen}><input type="checkbox" checked={line.allergens.includes(allergen)} onChange={()=>change(line.id,{allergens:line.allergens.includes(allergen)?line.allergens.filter(value=>value!==allergen):[...line.allergens,allergen]})}/>{allergen}</label>)}</div></details></article>)}{!lines.length&&<p>Επίλεξε προϊόντα για το τραπέζι.</p>}</section><footer><b>Νέα είδη: {euro(lines.reduce((sum,line)=>sum+line.price*line.quantity,0))}</b><button disabled={busy||!lines.length} onClick={send}><Send size={18}/>{busy?"Αποστολή…":"Αποστολή γύρου"}</button><small>Η πληρωμή, η φύρα και οι πρόσθετες επιλογές παρασκευής γίνονται μόνο από το POS.</small></footer></>}</>}
  </div>;
}
