import React,{useEffect,useMemo,useState} from "react";
import {Armchair,Map,Plus,Settings2,Users,X} from "lucide-react";

const euro=value=>Number(value||0).toLocaleString("el-GR",{style:"currency",currency:"EUR"});
const blankTable={name:"",areaId:"",capacity:4,shape:"SQUARE"};
const shapeLabel={SQUARE:"Τετράγωνο",ROUND:"Στρογγυλό",RECTANGLE:"Ορθογώνιο"};

export default function StoreTableOrdersModal({api,store,cart,onClose,onLoad,onCartCleared,setError,setMessage}){
  const [data,setData]=useState({areas:[],tables:[],orders:[],canConfigure:false}),[tableId,setTableId]=useState(""),[areaId,setAreaId]=useState("ALL"),[busy,setBusy]=useState(false),[configuring,setConfiguring]=useState(false),[newTable,setNewTable]=useState(blankTable);
  const load=async()=>{setBusy(true);try{const result=await api(`/api/store-pos/stores/${store.id}/table-service`);setData(result);setTableId(current=>result.tables?.some(table=>table.id===current)?current:result.tables?.[0]?.id||"")}catch(error){setError(error.message)}finally{setBusy(false)}};
  useEffect(()=>{load();const timer=setInterval(()=>load(),10000);return()=>clearInterval(timer)},[store.id]);
  const openOrders=useMemo(()=>new Map((data.orders||[]).map(order=>[order.tableId,order])),[data.orders]);
  const visibleTables=(data.tables||[]).filter(table=>areaId==="ALL"?true:areaId==="NONE"?!table.areaId:table.areaId===areaId);
  const addArea=async()=>{const name=String(window.prompt("Όνομα σάλας ή ζώνης:","")||"").trim();if(!name)return;setBusy(true);try{const area=await api(`/api/store-pos/stores/${store.id}/table-service/areas`,{method:"POST",body:JSON.stringify({name})});setAreaId(area.id);setMessage(`Δημιουργήθηκε η σάλα «${name}».`);await load()}catch(error){setError(error.message)}finally{setBusy(false)}};
  const addTable=async event=>{event.preventDefault();if(!newTable.name.trim())return setError("Συμπλήρωσε όνομα ή αριθμό τραπεζιού.");setBusy(true);try{const table=await api(`/api/store-pos/stores/${store.id}/tables`,{method:"POST",body:JSON.stringify({...newTable,name:newTable.name.trim(),areaId:newTable.areaId||null})});setTableId(table.id);setAreaId(table.areaId||"NONE");setNewTable(blankTable);setConfiguring(false);setMessage(`Δημιουργήθηκε το τραπέζι «${table.name}» για ${table.capacity} άτομα.`);await load()}catch(error){setError(error.message)}finally{setBusy(false)}};
  const send=async()=>{if(!tableId||!cart.length)return setError("Επίλεξε τραπέζι και πρόσθεσε προϊόντα.");setBusy(true);try{const result=await api(`/api/store-pos/stores/${store.id}/table-orders`,{method:"POST",body:JSON.stringify({tableId,items:cart.map(item=>({productId:item.id,quantity:item.quantity,notes:item.preparation?.note||null,modifiers:item.preparation?.modifiers||[]}))})});onCartCleared();const stations=(result.preparationBatches||[]).map(batch=>batch.productionStation).join(", ");setMessage(`Η παραγγελία στάλθηκε στο ${result.tableName} · ${euro(result.total)}${stations?` · Παρασκευή: ${stations}`:" · Δεν περιέχει είδη παρασκευής"}.`);await load()}catch(error){setError(error.message)}finally{setBusy(false)}};
  const useOrder=order=>{onLoad(order);onClose()};
  const status=async(order,next)=>{const reason=next==="CANCELLED"?String(window.prompt("Υποχρεωτική αιτιολογία ακύρωσης:","")||"").trim():null;if(next==="CANCELLED"&&!reason)return setError("Η ακύρωση απαιτεί αιτιολογία.");setBusy(true);try{await api(`/api/store-pos/stores/${store.id}/table-orders/${order.id}/status`,{method:"PATCH",body:JSON.stringify({status:next,reason})});await load()}catch(error){setError(error.message)}finally{setBusy(false)}};
  const wasteAll=async order=>{if(!window.confirm(`Να καταχωριστεί ΟΛΟ το ${order.tableName} ως φύρα ${euro(order.total)} χωρίς απόδειξη;`))return;const note=String(window.prompt("Υποχρεωτική αιτιολογία φύρας ολόκληρου τραπεζιού:","")||"").trim();if(!note)return setError("Η φύρα ολόκληρου τραπεζιού απαιτεί αιτιολογία.");setBusy(true);try{const result=await api(`/api/store-pos/stores/${store.id}/table-orders/${order.id}/waste`,{method:"POST",body:JSON.stringify({items:(order.items||[]).map(item=>({productId:item.productId,quantity:item.quantity})),note})});setMessage(`Ολόκληρο το ${result.tableName} καταχωρίστηκε ως φύρα ${euro(result.total)} · στον τζίρο χωρίς απόδειξη.`);await load()}catch(error){setError(error.message)}finally{setBusy(false)}};
  return <div className="pos-standard-modal" onMouseDown={event=>event.target===event.currentTarget&&!busy&&onClose()}><section><header><div><small>ΑΣΥΡΜΑΤΗ ΠΑΡΑΓΓΕΛΙΟΛΗΨΙΑ</small><h2>Σάλες, τραπέζια και παραγγελίες</h2></div><button onClick={onClose}><X/></button></header><main>
    <div style={{display:"flex",gap:8,alignItems:"center",flexWrap:"wrap",marginBottom:14}}><Map size={20}/><button onClick={()=>setAreaId("ALL")} className={areaId==="ALL"?"pos-primary-action":""}>Όλες οι σάλες</button>{(data.areas||[]).map(area=><button key={area.id} onClick={()=>setAreaId(area.id)} className={areaId===area.id?"pos-primary-action":""}>{area.name}</button>)}{(data.tables||[]).some(table=>!table.areaId)&&<button onClick={()=>setAreaId("NONE")} className={areaId==="NONE"?"pos-primary-action":""}>Χωρίς σάλα</button>}{data.canConfigure&&<><button onClick={addArea} disabled={busy}><Plus size={16}/> Νέα σάλα</button><button onClick={()=>setConfiguring(value=>!value)} disabled={busy}><Settings2 size={16}/> Νέο τραπέζι</button></>}</div>
    {configuring&&<form onSubmit={addTable} style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(150px,1fr))",gap:8,padding:12,marginBottom:14,border:"1px solid #cbd5e1",borderRadius:12,background:"#f8fafc"}}><input aria-label="Όνομα τραπεζιού" placeholder="Τραπέζι 1" value={newTable.name} onChange={event=>setNewTable({...newTable,name:event.target.value})}/><select aria-label="Σάλα" value={newTable.areaId} onChange={event=>setNewTable({...newTable,areaId:event.target.value})}><option value="">Χωρίς σάλα</option>{(data.areas||[]).map(area=><option key={area.id} value={area.id}>{area.name}</option>)}</select><input aria-label="Χωρητικότητα" type="number" min="1" max="100" value={newTable.capacity} onChange={event=>setNewTable({...newTable,capacity:event.target.value})}/><select aria-label="Σχήμα" value={newTable.shape} onChange={event=>setNewTable({...newTable,shape:event.target.value})}>{Object.entries(shapeLabel).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select><button className="pos-primary-action" disabled={busy}>ΑΠΟΘΗΚΕΥΣΗ</button></form>}
    <div style={{display:"grid",gridTemplateColumns:"repeat(auto-fill,minmax(145px,1fr))",gap:12,marginBottom:16}}>{visibleTables.map(table=>{const order=openOrders.get(table.id),ready=order?.status==="READY",selected=tableId===table.id;return <button key={table.id} onClick={()=>setTableId(table.id)} style={{minHeight:105,padding:12,borderRadius:table.shape==="ROUND"?"50%":table.shape==="RECTANGLE"?"10px":"18px",border:selected?"4px solid #0f766e":"2px solid #cbd5e1",background:ready?"#bbf7d0":order?"#fef3c7":"#f8fafc",color:"#143c34",fontWeight:900,display:"flex",flexDirection:"column",alignItems:"center",justifyContent:"center",gap:5}}><Armchair size={22}/><span>{table.name}</span><small><Users size={13}/> {table.capacity} άτομα · {shapeLabel[table.shape]||table.shape}</small><small>{ready?"ΕΤΟΙΜΟ ΓΙΑ ΠΑΡΑΛΑΒΗ":order?`${order.operatorName||"Χειριστής"} · ${euro(order.total)}`:"ΕΛΕΥΘΕΡΟ"}</small></button>})}</div>
    {!visibleTables.length&&<p style={{padding:18,textAlign:"center",background:"#f8fafc",borderRadius:12}}>Δεν υπάρχουν τραπέζια σε αυτή τη σάλα.</p>}
    <button className="pos-primary-action" disabled={busy||!tableId||!cart.length} onClick={send}>ΑΠΟΣΤΟΛΗ ΤΡΕΧΟΥΣΑΣ ΠΑΡΑΓΓΕΛΙΑΣ ({cart.length} είδη)</button>
    <div className="pos-hold-list" style={{marginTop:18}}>{data.orders.map(order=><article key={order.id} style={order.status==="READY"?{border:"3px solid #087a52",background:"#ecfdf5"}:undefined}><div><b>{order.tableName} · {euro(order.total)} {order.status==="READY"&&<span style={{color:"#087a52"}}>· ΕΤΟΙΜΗ ΓΙΑ ΠΑΡΑΛΑΒΗ</span>}</b><small style={{display:"block"}}>{order.operatorName||"Χειριστής"} · {order.status} · {(order.items||[]).map(item=>`${item.quantity}× ${item.name}`).join(" · ")}</small></div><div style={{display:"flex",gap:8,flexWrap:"wrap"}}><button onClick={()=>useOrder(order)}>ΦΟΡΤΩΣΗ ΣΤΟ POS</button><button onClick={()=>wasteAll(order)} style={{background:"#d97706"}}>ΦΥΡΑ ΟΛΟ ΤΟ ΤΡΑΠΕΖΙ</button><button onClick={()=>status(order,"CANCELLED")}>ΑΚΥΡΩΣΗ</button></div></article>)}</div>
  </main></section></div>;
}
