import React,{useEffect,useState} from "react";
import {Plus,Utensils,X} from "lucide-react";

const euro=value=>Number(value||0).toLocaleString("el-GR",{style:"currency",currency:"EUR"});

export default function StoreTableOrdersModal({api,store,cart,onClose,onLoad,onCartCleared,setError,setMessage}){
  const [data,setData]=useState({tables:[],orders:[]}),[tableId,setTableId]=useState(""),[busy,setBusy]=useState(false);
  const load=async()=>{setBusy(true);try{const result=await api(`/api/store-pos/stores/${store.id}/table-service`);setData(result);setTableId(current=>current||result.tables?.[0]?.id||"")}catch(error){setError(error.message)}finally{setBusy(false)}};
  useEffect(()=>{load();const timer=setInterval(()=>load(),10000);return()=>clearInterval(timer)},[store.id]);
  const addTable=async()=>{const name=String(window.prompt("Όνομα ή αριθμός τραπεζιού:","")||"").trim();if(!name)return;setBusy(true);try{await api(`/api/store-pos/stores/${store.id}/tables`,{method:"POST",body:JSON.stringify({name})});await load()}catch(error){setError(error.message)}finally{setBusy(false)}};
  const send=async()=>{if(!tableId||!cart.length)return setError("Επίλεξε τραπέζι και πρόσθεσε προϊόντα.");setBusy(true);try{const result=await api(`/api/store-pos/stores/${store.id}/table-orders`,{method:"POST",body:JSON.stringify({tableId,items:cart.map(item=>({productId:item.id,quantity:item.quantity,notes:item.preparation?.note||null,modifiers:item.preparation?.modifiers||[]}))})});onCartCleared();const stations=(result.preparationBatches||[]).map(batch=>batch.productionStation).join(", ");setMessage(`Η παραγγελία στάλθηκε στο ${result.tableName} · ${euro(result.total)}${stations?` · Παρασκευή: ${stations}`:" · Δεν περιέχει είδη παρασκευής"}.`);await load()}catch(error){setError(error.message)}finally{setBusy(false)}};
  const useOrder=order=>{onLoad(order);onClose()};
  const status=async(order,next)=>{const reason=next==="CANCELLED"?String(window.prompt("Υποχρεωτική αιτιολογία ακύρωσης:","")||"").trim():null;if(next==="CANCELLED"&&!reason)return setError("Η ακύρωση απαιτεί αιτιολογία.");setBusy(true);try{await api(`/api/store-pos/stores/${store.id}/table-orders/${order.id}/status`,{method:"PATCH",body:JSON.stringify({status:next,reason})});await load()}catch(error){setError(error.message)}finally{setBusy(false)}};
  const wasteAll=async order=>{if(!window.confirm(`Να καταχωριστεί ΟΛΟ το ${order.tableName} ως φύρα ${euro(order.total)} χωρίς απόδειξη;`))return;const note=String(window.prompt("Υποχρεωτική αιτιολογία φύρας ολόκληρου τραπεζιού:","")||"").trim();if(!note)return setError("Η φύρα ολόκληρου τραπεζιού απαιτεί αιτιολογία.");setBusy(true);try{const result=await api(`/api/store-pos/stores/${store.id}/table-orders/${order.id}/waste`,{method:"POST",body:JSON.stringify({items:(order.items||[]).map(item=>({productId:item.productId,quantity:item.quantity})),note})});setMessage(`Ολόκληρο το ${result.tableName} καταχωρίστηκε ως φύρα ${euro(result.total)} · στον τζίρο χωρίς απόδειξη.`);await load()}catch(error){setError(error.message)}finally{setBusy(false)}};
  return <div className="pos-standard-modal" onMouseDown={event=>event.target===event.currentTarget&&!busy&&onClose()}><section><header><div><small>ΑΣΥΡΜΑΤΗ ΠΑΡΑΓΓΕΛΙΟΛΗΨΙΑ</small><h2>Τραπέζια και παραγγελίες</h2></div><button onClick={onClose}><X/></button></header><main>
    <div style={{display:"flex",gap:10,flexWrap:"wrap",marginBottom:16}}>{data.tables.map(table=><button key={table.id} onClick={()=>setTableId(table.id)} style={{padding:"12px 18px",borderRadius:10,border:tableId===table.id?"3px solid #087a52":"1px solid #bccbc7",background:"white",fontWeight:900}}><Utensils size={18}/> {table.name}</button>)}<button onClick={addTable} disabled={busy} style={{padding:"12px 18px",borderRadius:10}}><Plus size={18}/> Νέο τραπέζι</button></div>
    <button className="pos-primary-action" disabled={busy||!tableId||!cart.length} onClick={send}>ΑΠΟΣΤΟΛΗ ΤΡΕΧΟΥΣΑΣ ΠΑΡΑΓΓΕΛΙΑΣ ({cart.length} είδη)</button>
    <div className="pos-hold-list" style={{marginTop:18}}>{data.orders.map(order=><article key={order.id} style={order.status==="READY"?{border:"3px solid #087a52",background:"#ecfdf5"}:undefined}><div><b>{order.tableName} · {euro(order.total)} {order.status==="READY"&&<span style={{color:"#087a52"}}>· ΕΤΟΙΜΗ ΓΙΑ ΠΑΡΑΛΑΒΗ</span>}</b><small style={{display:"block"}}>{order.operatorName||"Χειριστής"} · {order.status} · {(order.items||[]).map(item=>`${item.quantity}× ${item.name}`).join(" · ")}</small></div><div style={{display:"flex",gap:8}}><button onClick={()=>useOrder(order)}>ΦΟΡΤΩΣΗ ΣΤΟ POS</button><button onClick={()=>wasteAll(order)} style={{background:"#d97706"}}>ΦΥΡΑ ΟΛΟ ΤΟ ΤΡΑΠΕΖΙ</button><button onClick={()=>status(order,"CANCELLED")}>ΑΚΥΡΩΣΗ</button></div></article>)}</div>
  </main></section></div>;
}
