import React,{useEffect,useRef,useState} from "react";
import {createPortal} from "react-dom";
import {ClipboardList,Printer,RefreshCw,X} from "lucide-react";

const POLL_MS=7000;
const money=v=>Number(v||0).toLocaleString("el-GR",{style:"currency",currency:"EUR"});
const esc=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"})[c]);
const statusText=s=>({NEW:"ΝΕΑ",ACCEPTED:"ΑΠΟΔΟΧΗ",PREPARING:"ΕΤΟΙΜΑΖΕΤΑΙ",READY:"ΕΤΟΙΜΗ",OUT_FOR_DELIVERY:"ΣΤΟ DELIVERY",DELIVERED:"ΠΑΡΑΔΟΘΗΚΕ"})[s]||s;
const nextAction=o=>o.status==="NEW"?["ACCEPTED","ΑΠΟΔΟΧΗ + ΕΚΤΥΠΩΣΗ"]:o.status==="ACCEPTED"?["PREPARING","ΕΤΟΙΜΑΖΕΤΑΙ"]:o.status==="PREPARING"?["READY","ΕΤΟΙΜΗ"]:o.status==="READY"?(o.fulfillmentType==="PICKUP"?["DELIVERED","ΠΑΡΑΔΟΘΗΚΕ"]:["OUT_FOR_DELIVERY","ΣΤΟ DELIVERY"]):o.status==="OUT_FOR_DELIVERY"?["DELIVERED","ΠΑΡΑΔΟΘΗΚΕ"]:null;

function printOrder(p){if(!p)return;const w=window.open("","KAT_ONLINE_PRINT","width=460,height=720");if(!w)return window.alert("Ο browser μπλόκαρε το παράθυρο εκτύπωσης.");const lines=(p.items||[]).map(i=>`<tr><td>${esc(i.quantity)}×</td><td>${esc(i.productName)}</td><td>${money(i.lineTotal)}</td></tr>`).join("");w.document.write(`<!doctype html><html><head><meta charset="utf-8"><title>${esc(p.orderNumber)}</title><style>body{font-family:Arial;padding:14px}h1{text-align:center;font-size:20px}.n{text-align:center;font-size:28px;font-weight:900}table{width:100%;border-collapse:collapse;margin-top:10px}td{padding:8px 2px;border-bottom:1px dashed #999}td:last-child{text-align:right}.t{text-align:right;font-size:21px;font-weight:900;margin-top:12px}</style></head><body><h1>ΚΥΛΙΚΕΙΟ ΚΑΤ · ONLINE</h1><div class="n">#${esc(p.orderNumber)}</div><div>${esc(p.customerName)} · ${esc(p.customerPhone)}</div><div>${esc(p.location||"")}</div><table>${lines}</table><div class="t">ΣΥΝΟΛΟ ${money(p.total)}</div><script>setTimeout(()=>window.print(),200)<\/script></body></html>`);w.document.close()}

export default function StoreOnlineOrdersV2({api,store}){
 const enabled=/ΚΥΛΙΚΕΙΟ\s*ΚΑΤ/i.test(String(store?.name||""))||/^\/store\/kat-store\/?$/i.test(window.location.pathname);
 const [rows,setRows]=useState([]),[open,setOpen]=useState(false),[error,setError]=useState(""),[busyId,setBusyId]=useState("");
 const mounted=useRef(true);
 useEffect(()=>()=>{mounted.current=false},[]);
 useEffect(()=>{if(!open)return;const onKey=e=>{if(e.key==="Escape")setOpen(false)};window.addEventListener("keydown",onKey,true);return()=>window.removeEventListener("keydown",onKey,true)},[open]);
 const load=async()=>{if(!enabled||!store?.id)return;try{const r=await api(`/api/public/kat/pos/stores/${encodeURIComponent(store.id)}/orders`,{cache:"no-store"});if(mounted.current){setRows(r.rows||[]);setError("")}}catch(e){if(mounted.current)setError(e.message||"Αποτυχία φόρτωσης online παραγγελιών.")}};
 useEffect(()=>{if(!enabled)return;load();const t=window.setInterval(load,POLL_MS);return()=>window.clearInterval(t)},[enabled,store?.id]);
 const changeStatus=async(o,status)=>{if(busyId)return;setBusyId(o.id);setError("");try{const r=await api(`/api/public/kat/pos/stores/${encodeURIComponent(store.id)}/orders/${encodeURIComponent(o.id)}/status`,{method:"POST",body:JSON.stringify({status})});if(status==="ACCEPTED"&&r.print)printOrder(r.print);await load()}catch(e){setError(e.message||"Η αλλαγή κατάστασης απέτυχε.")}finally{setBusyId("")}};
 const reprint=async o=>{if(busyId)return;setBusyId(o.id);try{const r=await api(`/api/public/kat/pos/stores/${encodeURIComponent(store.id)}/orders/${encodeURIComponent(o.id)}/print`,{cache:"no-store"});printOrder(r.print)}catch(e){setError(e.message||"Η εκτύπωση απέτυχε.")}finally{setBusyId("")}};
 if(!enabled)return null;
 const launcher=<button type="button" onClick={()=>{setOpen(true);load()}} style={{position:"fixed",top:116,right:300,zIndex:99990,display:"inline-flex",alignItems:"center",gap:7,padding:"9px 12px",borderRadius:10,background:rows.length?"#9b1c1c":"#174f42",border:"1px solid rgba(255,255,255,.35)",color:"#fff",fontWeight:900,boxShadow:"0 4px 14px rgba(0,0,0,.18)",cursor:"pointer"}}><ClipboardList size={18}/>ΠΑΡΑΓΓΕΛΙΕΣ <b style={{minWidth:22,height:22,padding:"0 6px",display:"inline-grid",placeItems:"center",borderRadius:999,background:rows.length?"#ef4444":"#55766e",color:"#fff",fontSize:12}}>{rows.length}</b></button>;
 const modal=open&&createPortal(<div role="dialog" aria-modal="true" style={{position:"fixed",inset:0,zIndex:100000,background:"rgba(4,18,14,.88)",padding:24,overflow:"auto"}} onMouseDown={e=>{if(e.currentTarget===e.target)setOpen(false)}}><section onMouseDown={e=>e.stopPropagation()} style={{maxWidth:1050,margin:"0 auto",background:"#f7faf9",borderRadius:16,overflow:"hidden",boxShadow:"0 24px 70px rgba(0,0,0,.35)"}}><header style={{display:"flex",alignItems:"center",justifyContent:"space-between",gap:12,padding:"16px 20px",background:"#7c171b",color:"#fff"}}><div><small>MYWORKSTATION · ONLINE</small><h2 style={{margin:"3px 0 0"}}>Online Παραγγελίες · {rows.length}</h2></div><div style={{display:"flex",gap:8}}><button type="button" onClick={load} style={{display:"inline-flex",alignItems:"center",gap:6,padding:"9px 12px",border:0,borderRadius:8,fontWeight:900,cursor:"pointer"}}><RefreshCw size={17}/>Ανανέωση</button><button type="button" aria-label="Κλείσιμο" onClick={()=>setOpen(false)} style={{width:44,height:44,border:0,borderRadius:8,cursor:"pointer",display:"grid",placeItems:"center"}}><X/></button></div></header><div style={{padding:16,display:"grid",gap:12}}>{error&&<div style={{padding:11,borderRadius:9,background:"#fff0f0",color:"#9b2222",fontWeight:800}}>{error}</div>}{rows.length===0?<div style={{padding:38,textAlign:"center"}}>Δεν υπάρχουν ενεργές online παραγγελίες.</div>:rows.map(o=>{const next=nextAction(o);return <article key={o.id} style={{background:"#fff",border:"1px solid #dce7e3",borderRadius:13,padding:14}}><div style={{display:"flex",justifyContent:"space-between"}}><div><div style={{fontSize:22,fontWeight:900,color:"#7c171b"}}>#{o.orderNumber}</div><small>{statusText(o.status)}</small></div><b>{money(o.total)}</b></div><div style={{display:"grid",gridTemplateColumns:"repeat(4,minmax(0,1fr))",gap:8,margin:"12px 0"}}><div><small>Πελάτης</small><b style={{display:"block"}}>{o.customerName}</b></div><div><small>Τηλέφωνο</small><b style={{display:"block"}}>{o.customerPhone}</b></div><div><small>Παράδοση</small><b style={{display:"block"}}>{o.fulfillmentType==="DELIVERY"?"Delivery":"Παραλαβή"}</b></div><div><small>Πληρωμή</small><b style={{display:"block"}}>{o.paymentMethod==="CASH"?"Μετρητά":"Κάρτα"}</b></div></div>{(o.items||[]).map((i,n)=><div key={n} style={{display:"grid",gridTemplateColumns:"55px 1fr 100px",gap:10,padding:"8px 0",borderBottom:"1px dashed #d6dfdc"}}><b>{i.quantity}×</b><span>{i.productName}</span><b style={{textAlign:"right"}}>{money(i.lineTotal)}</b></div>)}<div style={{display:"flex",gap:8,marginTop:12,flexWrap:"wrap"}}>{next&&<button disabled={busyId===o.id} onClick={()=>changeStatus(o,next[0])} style={{padding:"9px 12px",fontWeight:900}}>{next[1]}</button>}<button disabled={busyId===o.id} onClick={()=>reprint(o)} style={{display:"inline-flex",alignItems:"center",gap:6,padding:"9px 12px",fontWeight:900}}><Printer size={17}/>ΕΠΑΝΕΚΤΥΠΩΣΗ</button></div></article>})}</div></section></div>,document.body);
 return <>{createPortal(launcher,document.body)}{modal}</>;
}
