import React,{useEffect,useMemo,useState} from "react";
import {ArrowLeft,ArrowRightLeft,CreditCard,ReceiptText,RefreshCw,RotateCcw,ShoppingCart,Truck,WalletCards,X} from "lucide-react";
import MyShiftEntriesPanel from "./MyShiftEntriesPanel.jsx";
import "./store-shift-menu.css";
const money=value=>Number(value||0).toLocaleString("el-GR",{style:"currency",currency:"EUR"});
const when=value=>value?new Date(value).toLocaleString("el-GR",{day:"2-digit",month:"2-digit",hour:"2-digit",minute:"2-digit",second:"2-digit"}):"—";
const paymentLabel=method=>method==="CASH"?"ΜΕΤΡΗΤΑ":method==="CARD"?"ΚΑΡΤΑ":method==="IRIS"?"IRIS":String(method||"ΠΛΗΡΩΜΗ");
const typeLabel=kind=>({SALE_CASH:"Πώληση μετρητών",SALE_CARD:"Πώληση με κάρτα",CASH_TRANSFER:"Μεταφορά ποσού",SUPPLIER_PAYMENT:"Πληρωμή προμηθευτή",OTHER_EXPENSE:"Λοιπά έξοδα",PERCENTAGES:"Ποσοστά",TRANSFER:"Μεταφορά ποσού",TRANSFER_AMOUNT:"Μεταφορά ποσού",WASTE:"Φύρα / Κατανάλωση προσωπικού"}[kind]||String(kind||"Κίνηση"));
export default function StoreShiftTransactionsModal({api,store,operator,allowAll=false,onClose}){
 const [overview,setOverview]=useState(null),[sales,setSales]=useState([]),[loading,setLoading]=useState(true),[error,setError]=useState("");
 const [transferAmount,setTransferAmount]=useState(""),[transferNote,setTransferNote]=useState(""),[transferBusy,setTransferBusy]=useState(false);
 const load=async()=>{setLoading(true);setError("");try{const [o,s]=await Promise.all([api(`/api/transactions/stores/${store.id}/overview`),api(`/api/store-pos/stores/${store.id}/sales/recent`)]);setOverview(o);setSales(s.rows||[])}catch(e){setError(e.message)}finally{setLoading(false)}};
 useEffect(()=>{load()},[store.id]);
 const submitTransfer=async()=>{const amount=Number(String(transferAmount||"").replace(",","."));if(!Number.isFinite(amount)||amount<=0)return setError("Βάλε έγκυρο ποσό μεταφοράς.");if(String(transferNote||"").trim().length<3)return setError("Γράψε από πού προέρχεται το ποσό.");setTransferBusy(true);setError("");try{await api(`/api/transactions/stores/${store.id}`,{method:"POST",body:JSON.stringify({type:"CASH_TRANSFER",amount,description:transferNote.trim()})});setTransferAmount("");setTransferNote("");await load()}catch(e){setError(e.message)}finally{setTransferBusy(false)}};
 const rows=useMemo(()=>{const open=overview?.openSession;if(!open)return[];const openedAt=new Date(open.openedAt).getTime(),own=String(operator?.fullName||"").trim();const activeSales=sales.filter(s=>new Date(s.createdAt||s.occurredAt).getTime()>=openedAt&&(allowAll||!own||String(s.actorName||"").trim()===own));const ids=new Set(activeSales.map(s=>String(s.id)));const saleRows=activeSales.map(s=>({id:`sale-${s.id}`,at:s.occurredAt||s.createdAt,kind:Number(s.total)<0||s.source==="POS_REVERSAL"?"RETURN":s.source==="EXCHANGE"?"EXCHANGE":"SALE",actor:s.actorName||"POS",amount:Number(s.total||0),lines:s.lines||[],payments:s.payments||[],description:null,reversed:Boolean(s.reversalState)}));const other=(overview?.recent||[]).filter(r=>r.sessionId===open.id&&(allowAll||!own||String(r.actorName||"").trim()===own)).filter(r=>![...ids].some(id=>String(r.description||"").includes(id))).map(r=>({id:`tx-${r.id}`,at:r.occurredAt,kind:/ΦΥΡΑ|ΚΑΤΑΝΑΛΩΣΗ/i.test(String(r.description||""))?"WASTE":r.type,actor:r.actorName||"Χειριστής",amount:Number(r.amount||0),lines:[],payments:[],description:r.supplierName||r.description||null,reversed:Boolean(r.reversedAt)}));return[...saleRows,...other].sort((a,b)=>new Date(b.at)-new Date(a.at))},[overview,sales,operator?.fullName,allowAll]);
 const icon=kind=>kind==="RETURN"?<RotateCcw/>:kind==="SALE"||kind==="EXCHANGE"?<ShoppingCart/>:kind==="SALE_CARD"?<CreditCard/>:kind==="SUPPLIER_PAYMENT"?<Truck/>:kind==="CASH_TRANSFER"||kind==="TRANSFER"||kind==="TRANSFER_AMOUNT"?<ArrowRightLeft/>:<ReceiptText/>;
 const label=row=>row.kind==="RETURN"?"Επιστροφή":row.kind==="EXCHANGE"?"Αλλαγή είδους":row.kind==="SALE"?"Πώληση":typeLabel(row.kind);
 return <div className="shift-overlay"><section className="shift-timeline-modal"><header><div><small>MYWORKSTATION · ΕΝΕΡΓΗ ΒΑΡΔΙΑ</small><h2>Συναλλαγές βάρδιας</h2><p>{overview?.openSession?.shiftLabel||store.name}</p></div><button onClick={onClose}><X/></button></header><div className="shift-timeline-tools"><button onClick={onClose}><ArrowLeft/>Επιστροφή στο POS</button><span>{overview?.openSession?`${when(overview.openSession.openedAt)} · ${allowAll?"Όλες οι συναλλαγές":"Μόνο οι δικές μου"}`:"Δεν υπάρχει ανοιχτή βάρδια"}</span><button onClick={load} disabled={loading}><RefreshCw/>Ανανέωση</button></div>{error&&<div className="shift-timeline-error">{error}</div>}{overview?.openSession&&<div className="cloud-panel"><div className="cloud-panel-head"><div><h3><ArrowRightLeft/>Μεταφορά ποσού προς ενεργή βάρδια</h3><p>Πρόσθεσε πραγματικά μετρητά που μπήκαν στη βάρδια από φύλαξη, χρηματοκιβώτιο ή άλλη εσωτερική πηγή. Η κίνηση γράφεται στο audit και αυξάνει το αναμενόμενο ταμείο.</p></div></div><div className="shift-transfer-form"><label>Ποσό<input inputMode="decimal" value={transferAmount} onChange={e=>setTransferAmount(e.target.value)} placeholder="0,00"/></label><label>Προέλευση / αιτιολογία<input value={transferNote} onChange={e=>setTransferNote(e.target.value)} placeholder="π.χ. από χρηματοκιβώτιο"/></label><button disabled={transferBusy} onClick={submitTransfer}><ArrowRightLeft/>{transferBusy?"Καταχώριση…":"Καταχώριση μεταφοράς"}</button></div></div>}<div className="shift-timeline-list">{loading?<div className="shift-timeline-empty">Φόρτωση συναλλαγών…</div>:rows.length===0?<div className="shift-timeline-empty">Δεν υπάρχουν συναλλαγές στην ενεργή βάρδια.</div>:rows.map(row=><article key={row.id} className={`${row.kind==="RETURN"?"return":""} ${row.reversed?"reversed":""}`}><div className="shift-timeline-icon">{icon(row.kind)}</div><div className="shift-timeline-content"><div className="shift-timeline-title"><b>{label(row)}</b><strong>{money(row.amount)}</strong></div><small>{when(row.at)} · {row.actor}</small>{row.lines.length>0&&<div className="shift-timeline-products">{row.lines.map((line,index)=><div key={line.id||index}><span><b>{Math.abs(Number(line.quantity||0))}×</b> {line.description||"Προϊόν"}</span><span>{money(line.lineTotal)}</span></div>)}</div>}{row.payments.length>0&&<div className="shift-timeline-payments"><WalletCards/>{row.payments.map(p=>`${paymentLabel(p.method)} ${money(p.amount)}`).join(" + ")}</div>}{row.description&&<p>{row.description}</p>}</div></article>)}</div><MyShiftEntriesPanel api={api} store={store} operator={operator}/></section></div>
}
