import React,{useEffect,useMemo,useState} from "react";
import {ArrowLeft,CreditCard,RefreshCw,RotateCcw,ShoppingCart,Trash2,WalletCards,X} from "lucide-react";
import MyShiftEntriesPanel from "./MyShiftEntriesPanel.jsx";
import "./store-shift-menu.css";
const money=value=>Number(value||0).toLocaleString("el-GR",{style:"currency",currency:"EUR"});
const when=value=>value?new Date(value).toLocaleString("el-GR",{day:"2-digit",month:"2-digit",hour:"2-digit",minute:"2-digit",second:"2-digit"}):"—";
const paymentLabel=method=>method==="CASH"?"ΜΕΤΡΗΤΑ":method==="CARD"?"ΚΑΡΤΑ":method==="IRIS"?"IRIS":String(method||"ΠΛΗΡΩΜΗ");
const norm=value=>String(value||"").trim().toLocaleUpperCase("el-GR").replace(/\s+/g," ");
const isVoid=row=>/^POS\s+ΑΚΥΡΩΣΗ\b/i.test(String(row?.description||""));
export default function StoreShiftTransactionsModal({api,store,operator,allowAll=false,onClose}){
 const [overview,setOverview]=useState(null),[sales,setSales]=useState([]),[loading,setLoading]=useState(true),[error,setError]=useState("");
 const load=async()=>{setLoading(true);setError("");try{const [o,s]=await Promise.all([api(`/api/transactions/stores/${store.id}/overview`),api(`/api/store-pos/stores/${store.id}/sales/recent`)]);setOverview(o);setSales(s.rows||[])}catch(e){setError(e.message)}finally{setLoading(false)}};
 useEffect(()=>{load()},[store.id]);
 const rows=useMemo(()=>{const open=overview?.openSession;if(!open)return[];const sessionId=String(open.id||"").trim();if(!sessionId)return[];const operatorName=norm(operator?.fullName||operator?.name);const allowed=row=>allowAll||!operatorName||norm(row.actorName)===operatorName;const saleRows=sales.filter(s=>String(s.sessionId||"").trim()===sessionId).filter(allowed).map(s=>({id:`sale-${s.id}`,at:s.occurredAt||s.createdAt,kind:s.source==="WASTE"?"WASTE":Number(s.total)<0||s.source==="POS_REVERSAL"?"RETURN":s.source==="EXCHANGE"?"EXCHANGE":"SALE",actor:s.actorName||"POS",amount:Number(s.total||0),lines:s.lines||[],payments:s.payments||[],reversed:Boolean(s.reversalState),reversalReason:s.reversalReason||""}));const ledgerRows=(overview?.recent||[]).filter(row=>String(row.sessionId||"").trim()===sessionId).filter(allowed).filter(row=>isVoid(row)||!["SALE_CASH","SALE_CARD"].includes(row.type)).map(row=>({id:`ledger-${row.id}`,at:row.occurredAt||row.createdAt,kind:isVoid(row)?"VOID":row.type==="SUPPLIER_PAYMENT"?"SUPPLIER":row.type==="OTHER_EXPENSE"?"EXPENSE":row.type==="TRANSFER_AMOUNT"?"TRANSFER":row.type==="PERCENTAGES"?"PERCENTAGES":"OTHER",type:row.type,actor:row.actorName||"POS",amount:Number(row.amount||0),description:row.description||row.supplierName||"",supplierName:row.supplierName||"",lines:[],payments:[],reversed:Boolean(row.reversedAt),reversalReason:row.reversalReason||"",subtractFromShift:Boolean(row.subtractFromShift)}));return [...saleRows,...ledgerRows].sort((a,b)=>new Date(b.at)-new Date(a.at))},[overview,sales,allowAll,operator?.fullName,operator?.name]);
 const icon=row=>row.kind==="RETURN"||row.kind==="VOID"||row.kind==="PERCENTAGES"?<RotateCcw/>:row.kind==="WASTE"||row.kind==="SUPPLIER"||row.kind==="EXPENSE"?<Trash2/>:row.kind==="SALE"||row.kind==="EXCHANGE"?<ShoppingCart/>:row.kind==="TRANSFER"?<WalletCards/>:<CreditCard/>;
 const defaultSaleLabel=row=>row.kind==="WASTE"?"ΦΥΡΑ":"Πώληση";
 const label=row=>({RETURN:"Επιστροφή",VOID:"ΑΚΥΡΩΣΗ / VOID",EXCHANGE:"Αλλαγή είδους",SUPPLIER:"Πληρωμή προμηθευτή",EXPENSE:"Πληρωμή προς τρίτους",TRANSFER:"Μεταφορά ποσού",PERCENTAGES:"Ποσοστά",OTHER:"Κίνηση βάρδιας"}[row.kind]||defaultSaleLabel(row));
 return <div className="shift-overlay"><section className="shift-timeline-modal"><header><div><small>MYWORKSTATION · ΕΝΕΡΓΗ ΒΑΡΔΙΑ</small><h2>Συναλλαγές βάρδιας</h2><p>{overview?.openSession?.shiftLabel||store.name}</p></div><button onClick={onClose}><X/></button></header><div className="shift-timeline-tools"><button onClick={onClose}><ArrowLeft/>Επιστροφή στο POS</button><span>{overview?.openSession?`${when(overview.openSession.openedAt)} · ${allowAll?"Όλες οι κινήσεις":"Οι δικές μου κινήσεις"}`:"Δεν υπάρχει ανοιχτή βάρδια"}</span><button onClick={load} disabled={loading}><RefreshCw/>Ανανέωση</button></div>{error&&<div className="shift-timeline-error">{error}</div>}<div className="shift-timeline-list">{loading?<div className="shift-timeline-empty">Φόρτωση συναλλαγών…</div>:rows.length===0?<div className="shift-timeline-empty">Δεν υπάρχουν συναλλαγές στην ενεργή βάρδια.</div>:rows.map(row=><article key={row.id} className={`${row.kind==="RETURN"||row.kind==="VOID"?"return":""} ${row.reversed?"reversed":""}`}><div className="shift-timeline-icon">{icon(row)}</div><div className="shift-timeline-content"><div className="shift-timeline-title"><b>{label(row)}</b><strong>{money(row.amount)}</strong></div><small>{when(row.at)} · {row.actor}{row.kind==="WASTE"?" · Χωρίς απόδειξη":""}{row.reversed?" · ΑΝΤΙΛΟΓΙΣΜΕΝΗ":""}</small>{row.lines.length>0&&<div className="shift-timeline-products">{row.lines.map((line,index)=><div key={line.id||index}><span><b>{Math.abs(Number(line.quantity||0))}×</b> {line.description||"Προϊόν"}</span><span>{money(line.lineTotal)}</span></div>)}</div>}{row.description&&<div className="shift-timeline-products"><div><span>{row.description}</span>{row.supplierName&&row.supplierName!==row.description?<span>{row.supplierName}</span>:null}</div></div>}{row.payments.length>0&&<div className="shift-timeline-payments"><WalletCards/>{row.payments.map(p=>`${paymentLabel(p.method)} ${money(p.amount)}`).join(" + ")}</div>}{["SUPPLIER_PAYMENT","OTHER_EXPENSE"].includes(row.type)&&<div className="shift-timeline-payments"><WalletCards/>{row.subtractFromShift?"Αφαιρέθηκε από τη βάρδια":"Εξωτερική πληρωμή"}</div>}{row.reversed&&row.reversalReason&&<small>Αιτία αντιλογισμού: {row.reversalReason}</small>}</div></article>)}</div><MyShiftEntriesPanel api={api} store={store} operator={operator}/></section></div>
}
