import React,{useEffect,useRef,useState} from "react";
import {Camera,Wallet,X} from "lucide-react";
const euro=v=>Number(v||0).toLocaleString("el-GR",{style:"currency",currency:"EUR"});
const num=v=>Number(String(v||"0").replace(",","."))||0;
const fileToDataUrl=file=>new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(r.result);r.onerror=reject;r.readAsDataURL(file)});
function Pad({value,onChange}){const press=k=>{const c=String(value??"");if(k==="⌫")return onChange(c.slice(0,-1));if(k==="C")return onChange("");if(k===","){if(c.includes(",")||c.includes("."))return;return onChange(`${c||"0"},`)}onChange(`${c}${k}`.replace(/^0+(?=\d)/,""))};const trusted=(e,k)=>{if(e?.nativeEvent?.isTrusted===false)return;press(String(k))};return <div className="pos-inline-keypad">{[7,8,9,4,5,6,1,2,3,0,",","⌫"].map(k=><button key={k} type="button" onClick={e=>trusted(e,k)}>{k}</button>)}<button type="button" className="wide" onClick={e=>trusted(e,"C")}>ΚΑΘΑΡΙΣΜΟΣ</button></div>}
export default function StorePosPaymentsModal({api,store,onClose,onChanged,setMessage,setError}){
 const [busy,setBusy]=useState(false),[ledger,setLedger]=useState(null),[capabilities,setCapabilities]=useState({invoiceAi:false,invoicePhoto:true}),[cameraOpen,setCameraOpen]=useState(false),[stream,setStream]=useState(null);const videoRef=useRef(null),canvasRef=useRef(null);
 const [form,setForm]=useState({type:"OTHER_EXPENSE",amount:"",supplierId:"",description:"",subtractFromShift:true,file:null});
 const stopCamera=()=>{stream?.getTracks?.().forEach(t=>t.stop());setStream(null);setCameraOpen(false)};
 useEffect(()=>{api(`/api/transactions/stores/${store.id}/overview`).then(setLedger).catch(e=>setError(e.message));api(`/api/store-pos/stores/${store.id}/capabilities`).then(setCapabilities).catch(()=>setCapabilities({invoiceAi:false,invoicePhoto:true}));return()=>stopCamera()},[]);
 useEffect(()=>{const h=e=>{const d=e.detail||{};const safeAmount=d.amount!==undefined?String(d.amount).replace(".",","):undefined;setForm(c=>({...c,...(safeAmount!==undefined&&/^\d+(?:,\d{1,2})?$/.test(safeAmount)?{amount:safeAmount}:{}),...(d.supplierId!==undefined?{supplierId:String(d.supplierId||"")} : {}),...(d.description!==undefined?{description:String(d.description||"")} : {})}))};window.addEventListener("mws-invoice-payment-state",h);return()=>window.removeEventListener("mws-invoice-payment-state",h)},[]);
 const startCamera=async()=>{try{stopCamera();const s=await navigator.mediaDevices.getUserMedia({video:{facingMode:"environment"},audio:false});setStream(s);setCameraOpen(true);setTimeout(()=>{if(videoRef.current)videoRef.current.srcObject=s},0)}catch{setError("Δεν μπόρεσε να ανοίξει η κάμερα. Έλεγξε την άδεια κάμερας του browser.")}};
 const capture=()=>{const v=videoRef.current,c=canvasRef.current;if(!v||!c)return;c.width=v.videoWidth||1280;c.height=v.videoHeight||720;c.getContext("2d").drawImage(v,0,0,c.width,c.height);c.toBlob(blob=>{if(!blob)return;setForm(x=>({...x,file:new File([blob],`timologio-${Date.now()}.jpg`,{type:"image/jpeg"})}));stopCamera()},"image/jpeg",.9)};
 const submit=async()=>{const amount=num(form.amount);if(amount<=0)return setError("Βάλε ποσό πληρωμής.");if(!form.file)return setError("Βγάλε ή επίλεξε φωτογραφία παραστατικού.");setBusy(true);try{const dataUrl=await fileToDataUrl(form.file);await api(`/api/transactions/stores/${store.id}`,{method:"POST",body:JSON.stringify({type:form.type,amount,description:form.description||null,supplierId:form.type==="SUPPLIER_PAYMENT"?form.supplierId||null:null,subtractFromShift:Boolean(form.subtractFromShift),attachment:{dataUrl,filename:form.file.name||"parastatiko.jpg"}})});setMessage(`Η πληρωμή ${euro(amount)} καταχωρίστηκε στη βάρδια και στο BackOffice.`);onChanged?.();onClose()}catch(e){setError(e.message)}finally{setBusy(false)}};
 const suppliers=ledger?.suppliers||[];
 const supplierMode=form.type==="SUPPLIER_PAYMENT";
 return <div className="pos-standard-modal" onMouseDown={e=>e.target===e.currentTarget&&!busy&&onClose()}><section><header><div><small>MYWORKSTATION STANDARD POS</small><h2>Πληρωμές</h2></div><button onClick={()=>!busy&&onClose()}><X/></button></header><main><div className="pos-payment-form">
 <div style={{marginBottom:8}}><small style={{fontWeight:800,color:"#47655d"}}>ΤΥΠΟΣ ΚΑΤΑΧΩΡΙΣΗΣ — η επιλογή εδώ δεν εκτελεί πληρωμή</small></div>
 <div className="pos-payment-types"><button type="button" aria-pressed={form.type==="OTHER_EXPENSE"} className={form.type==="OTHER_EXPENSE"?"active":""} onClick={()=>setForm(c=>({...c,type:"OTHER_EXPENSE"}))}>Λοιπά έξοδα</button><button type="button" aria-pressed={supplierMode} className={supplierMode?"active":""} onClick={()=>setForm(c=>({...c,type:"SUPPLIER_PAYMENT"}))}>Πληρωμή προμηθευτή</button></div>
 {supplierMode&&<label>Προμηθευτής<select value={form.supplierId} onChange={e=>setForm(c=>({...c,supplierId:e.target.value}))}><option value="">Επίλεξε</option>{suppliers.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label>}
 <label>Ποσό<input readOnly inputMode="decimal" value={form.amount}/></label><Pad value={form.amount} onChange={amount=>setForm(c=>({...c,amount}))}/><label>Παρατηρήσεις<input value={form.description} onChange={e=>setForm(c=>({...c,description:e.target.value}))}/></label>
 {!supplierMode&&<><div className="pos-photo-actions"><button type="button" onClick={startCamera}><Camera/> Λήψη από κάμερα</button><label><Camera/> Επιλογή αρχείου<input type="file" accept="image/*,application/pdf" onChange={e=>setForm(c=>({...c,file:e.target.files?.[0]||null}))}/></label><b>{form.file?.name||"Δεν επιλέχθηκε φωτογραφία"}</b></div>
 {cameraOpen&&<div className="pos-camera-live"><video ref={videoRef} autoPlay playsInline/><canvas ref={canvasRef} hidden/><div><button type="button" onClick={capture}><Camera/> Φωτογράφιση</button><button type="button" onClick={stopCamera}>Κλείσιμο κάμερας</button></div></div>}
 {capabilities.invoiceAi?<button className="pos-ai-reader" type="button" disabled={!form.file} onClick={()=>form.file&&setMessage("OCR + AI επανέλεγχος παραστατικού.")}>OCR + AI Επανέλεγχος παραστατικού</button>:<small className="pos-module-note">OCR + AI εμφανίζεται μόνο σε κατάστημα με ενεργό και πληρωμένο AI Reader module.</small>}
 <label className="pos-check"><input type="checkbox" checked={form.subtractFromShift} onChange={e=>setForm(c=>({...c,subtractFromShift:e.target.checked}))}/>Αφαίρεση από τα μετρητά της βάρδιας</label><button className="pos-primary-action" disabled={busy} onClick={submit}><Wallet/> Καταχώριση πληρωμής</button></>}
 {supplierMode&&<div style={{marginTop:10,padding:"10px 12px",borderRadius:10,background:"#eef8f4",border:"1px solid #9ac9b8",fontWeight:700}}>Η «Πληρωμή προμηθευτή» είναι επιλογή καρτέλας. Για τιμολόγιο, σκάναρε/ανέβασε το παραστατικό παρακάτω, επίλεξε <b>ΠΛΗΡΩΜΕΝΟ</b> ή <b>ΜΕ ΠΙΣΤΩΣΗ</b> και ολοκλήρωσε από το τελικό κουμπί <b>«Καταχώριση τιμολογίου για έλεγχο»</b>.</div>}
 </div></main></section></div>
}