import React,{useEffect,useMemo,useState} from "react";
import {ArrowLeft,CreditCard,RefreshCw,RotateCcw,ShoppingCart,Trash2,WalletCards,X} from "lucide-react";
import MyShiftEntriesPanel from "./MyShiftEntriesPanel.jsx";
import "./store-shift-menu.css";
const money=value=>Number(value||0).toLocaleString("el-GR",{style:"currency",currency:"EUR"});
const when=value=>value?new Date(value).toLocaleString("el-GR",{day:"2-digit",month:"2-digit",hour:"2-digit",minute:"2-digit",second:"2-digit"}):"—";
const norm=value=>String(value||"").trim().toLocaleUpperCase("el-GR").replace(/\s+/g," ");
const isVoid=row=>/^POS\s+ΑΚΥΡΩΣΗ\b/i.test(String(row?.description||""));
export default function StoreShiftTransactionsModal({api,store,operator,allowAll=false,onClose}){
 const [overview,setOverview]=useState(null),[loading,setLoading]=useState(true),[error,setError]=useState("");
 const load=async()=>{setLoading(true);setError("");try{setOverview(await api(`/api/transactions/stores/${store.id}/overview`))}catch(e){setError(e.message)}finally{setLoading(false)}};
 useEffect(()=>{load()},[store.id]);
 const rows=useMemo(()=>{const open=overview?.openSession;if(!open)return[];const sessionId=String(open.id||"").trim();if(!sessionId)return[];const operatorName=norm(operator?.fullName||operator?.name);return (overview?.recent||[]).filter(row=>String(row.sessionId||"").trim()===sessionId).filter(row=>allowAll||!operatorName||norm(row.actorName)===operatorName).map(row=>({id:row.id,at:row.occurredAt||row.createdAt,type:row.type,actor:row.actorName||"POS",amount:Number(row.amount||0),description:row.description||row.supplierName||"",supplierName:row.supplierName||"",reversed:Boolean(row.reversedAt),reversalReason:row.reversalReason||"",subtractFromShift:Boolean(row.subtractFromShift)})).sort((a,b)=>new Date(b.at)-new Date(a.at))},[overview,allowAll,operator?.fullName,operator?.name]);
 const kind=row=>isVoid(row)?"VOID":row.type==="SALE_CASH"||row.type==="SALE_CARD"?"SALE":row.type==="SUPPLIER_PAYMENT"?"SUPPLIER":row.type==="OTHER_EXPENSE"?"EXPENSE":row.type==="TRANSFER_AMOUNT"?"TRANSFER":row.type==="PERCENTAGES"?"PERCENTAGES":"OTHER";
 const icon=row=>{const k=kind(row);return k==="SUPPLIER"||k==="EXPENSE"?<Trash2/>:k==="TRANSFER"?<WalletCards/>:k==="VOID"?<RotateCcw/>:k==="SALE"?<ShoppingCart/>:k==="PERCENTAGES"?<RotateCcw/>:<CreditCard/>};
 const label=row=>isVoid(row)?"ΑΚΥΡΩΣΗ / VOID":({SALE_CASH:"Πώληση · Μετρητά",SALE_CARD:"Πώληση · Κάρτα",SUPPLIER_PAYMENT:"Πληρωμή προμηθευτή",OTHER_EXPENSE:"Πληρωμή προς τρίτους",TRANSFER_AMOUNT:"Μεταφορά ποσού",PERCENTAGES:"Ποσοστά"}[row.type]||"Κίνηση βάρδιας");
 return <div className="shift-overlay"><section className="shift-timeline-modal"><header><div><small>MYWORKSTATION · ΕΝΕΡΓΗ ΒΑΡΔΙΑ</small><h2>Συναλλαγές βάρδιας</h2><p>{overview?.openSession?.shiftLabel||store.name}</p></div><button onClick={onClose}><X/></button></header><div className="shift-timeline-tools"><button onClick={onClose}><ArrowLeft/>Επιστροφή στο POS</button><span>{overview?.openSession?`${when(overview.openSession.openedAt)} · ${allowAll?"Όλες οι κινήσεις":"Οι δικές μου κινήσεις"}`:"Δεν υπάρχει ανοιχτή βάρδια"}</span><button onClick={load} disabled={loading}><RefreshCw/>Ανανέωση</button></div>{error&&<div className="shift-timeline-error">{error}</div>}<div className="shift-timeline-list">{loading?<div className="shift-timeline-empty">Φόρτωση συναλλαγών…</div>:rows.length===0?<div className="shift-timeline-empty">Δεν υπάρχουν συναλλαγές στην ενεργή βάρδια.</div>:rows.map(row=><article key={row.id} className={`${row.reversed?"reversed":""}`}><div className="shift-timeline-icon">{icon(row)}</div><div className="shift-timeline-content"><div className="shift-timeline-title"><b>{label(row)}</b><strong>{money(row.amount)}</strong></div><small>{when(row.at)} · {row.actor}{row.reversed?" · ΑΝΤΙΛΟΓΙΣΜΕΝΗ":""}</small>{row.description&&<div className="shift-timeline-products"><div><span>{row.description}</span>{row.supplierName&&row.supplierName!==row.description?<span>{row.supplierName}</span>:null}</div></div>}{["SUPPLIER_PAYMENT","OTHER_EXPENSE"].includes(row.type)&&<div className="shift-timeline-payments"><WalletCards/>{row.subtractFromShift?"Αφαιρέθηκε από τη βάρδια":"Εξωτερική πληρωμή"}</div>}{row.reversed&&row.reversalReason&&<small>Αιτία αντιλογισμού: {row.reversalReason}</small>}</div></article>)}</div><MyShiftEntriesPanel api={api} store={store} operator={operator}/></section></div>
}