import React,{useEffect,useRef,useState} from "react";
import {BadgeCheck,Bot,CheckCircle2,ClipboardList,Download,Eye,FileText,Image,MessageCircle,Paperclip,Pin,RefreshCw,RotateCcw,Send,Settings,X,Star} from "lucide-react";
import "./store-chat.css";

const labels={GENERAL:"Γενικό",SHIFT:"Βάρδια",CASH:"Ταμείο",INVOICE:"Τιμολόγιο",PAYMENT:"Πληρωμή",STOCK_SHORTAGE:"Έλλειψη προϊόντος",EQUIPMENT:"Βλάβη",ORDER:"Παραγγελία",ANNOUNCEMENT:"Ανακοίνωση",INCIDENT:"Συμβάν"};
const readerNames=readers=>{if(Array.isArray(readers))return readers;if(typeof readers==="string"){try{const parsed=JSON.parse(readers);return Array.isArray(parsed)?parsed:[]}catch{return[]}}return[]};
const readFile=file=>new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(reader.result);reader.onerror=()=>reject(new Error("Δεν διαβάστηκε το αρχείο."));reader.readAsDataURL(file)});
const authToken=()=>localStorage.getItem("token")||sessionStorage.getItem("storeOperatorToken")||"";
const pdfPreview=async blob=>{const pdfjs=await import("pdfjs-dist/legacy/build/pdf.mjs");pdfjs.GlobalWorkerOptions.workerSrc=new URL("pdfjs-dist/legacy/build/pdf.worker.min.mjs",import.meta.url).toString();const pdf=await pdfjs.getDocument({data:new Uint8Array(await blob.arrayBuffer())}).promise,page=await pdf.getPage(1),viewport=page.getViewport({scale:1.5}),canvas=document.createElement("canvas");canvas.width=Math.ceil(viewport.width);canvas.height=Math.ceil(viewport.height);await page.render({canvasContext:canvas.getContext("2d"),viewport}).promise;const rendered=await new Promise(resolve=>canvas.toBlob(resolve,"image/jpeg",.9));return {url:URL.createObjectURL(rendered),pageCount:pdf.numPages}};

export default function StoreChatPanel({api,store,onClose}){
  const[rows,setRows]=useState([]),[permissions,setPermissions]=useState({canPin:false,canDownload:false,canComplete:false,canCreateTask:false,canManageTask:false,canManageSettings:false}),[settings,setSettings]=useState({invoiceAiReaderEnabled:false,announcementAcknowledgementRequired:false}),[body,setBody]=useState(""),[category,setCategory]=useState("GENERAL"),[query,setQuery]=useState(""),[dateFilter,setDateFilter]=useState(""),[senderFilter,setSenderFilter]=useState(""),[taskFilter,setTaskFilter]=useState(false),[busy,setBusy]=useState(true),[error,setError]=useState(""),[notifications,setNotifications]=useState("unknown"),[openingId,setOpeningId]=useState(null),[attachment,setAttachment]=useState(null),[previews,setPreviews]=useState({});
  const previousIds=useRef(new Set()),loading=useRef(false),previewRef=useRef({});
  const enableNotifications=async()=>{if(!("Notification" in window)){setNotifications("unsupported");return}const permission=await Notification.requestPermission();setNotifications(permission)};
  useEffect(()=>{if("serviceWorker" in navigator)navigator.serviceWorker.register("/sw.js").catch(()=>{});if("Notification" in window)setNotifications(Notification.permission)},[]);
  const load=async(force=false)=>{if(loading.current&&!force)return;loading.current=true;setBusy(true);try{const data=await api(`/api/store-chat/stores/${encodeURIComponent(store.id)}/messages?_ts=${Date.now()}`),nextRows=data.rows||[],unseen=nextRows.filter(row=>!previousIds.current.has(row.id));if(document.hidden&&"Notification" in window&&Notification.permission==="granted"&&previousIds.current.size>0&&unseen.length)new Notification("MyWorkStation · Chat",{body:`${unseen.length} νέο μήνυμα στο ${store.name}`});previousIds.current=new Set(nextRows.map(row=>row.id));setRows(nextRows);setSettings(data.settings||{invoiceAiReaderEnabled:false,announcementAcknowledgementRequired:false});setPermissions(data.permissions||{canPin:false,canDownload:false,canComplete:false,canCreateTask:false,canManageTask:false,canManageSettings:false});setError("")}catch(e){setError(e.message)}finally{loading.current=false;setBusy(false)}};
  useEffect(()=>{load();const timer=window.setInterval(()=>load(),15000);return()=>window.clearInterval(timer)},[store.id]);
  useEffect(()=>{previewRef.current=previews},[previews]);
  useEffect(()=>()=>Object.values(previewRef.current).forEach(preview=>URL.revokeObjectURL(preview.url)),[]);
  const openMessage=async row=>{if(row.readByMe||openingId)return;setOpeningId(row.id);try{await api(`/api/store-chat/stores/${encodeURIComponent(store.id)}/messages/${encodeURIComponent(row.id)}/read`,{method:"POST"});await load(true)}catch(e){setError(e.message)}finally{setOpeningId(null)}};
  const send=async e=>{e.preventDefault();if(!body.trim()&&!attachment)return;const form=e.currentTarget;setBusy(true);try{const file=attachment?{name:attachment.name,mimeType:attachment.type,dataUrl:await readFile(attachment)}:null;await api(`/api/store-chat/stores/${encodeURIComponent(store.id)}/messages`,{method:"POST",body:JSON.stringify({body,category,attachment:file})});setBody("");setAttachment(null);form.reset();await load(true)}catch(e){setError(e.message)}finally{setBusy(false)}};
  const fetchAttachment=async(row,download=false)=>{const token=authToken(),response=await fetch(`/api/store-chat/stores/${encodeURIComponent(store.id)}/messages/${encodeURIComponent(row.id)}/attachment${download?"?download=1":""}`,{headers:{...(token?{Authorization:`Bearer ${token}`}:{})},cache:"no-store"});if(!response.ok){const data=await response.json().catch(()=>({}));throw new Error(data.error||"Δεν άνοιξε το αρχείο.")}return response.blob()};
  const viewAttachment=async row=>{try{if(previews[row.id]){URL.revokeObjectURL(previews[row.id].url);setPreviews(values=>{const next={...values};delete next[row.id];return next});return}const blob=await fetchAttachment(row),preview=row.attachmentMimeType==="application/pdf"?await pdfPreview(blob):{url:URL.createObjectURL(blob),pageCount:null};setPreviews(values=>({...values,[row.id]:preview}))}catch(e){setError(e.message)}};
  const downloadAttachment=async row=>{try{const blob=await fetchAttachment(row,true),url=URL.createObjectURL(blob),link=document.createElement("a");link.href=url;link.download=row.attachmentName||"chat-file";link.click();setTimeout(()=>URL.revokeObjectURL(url),0)}catch(e){setError(e.message)}};
  const toggleAiReader=async()=>{setBusy(true);try{const result=await api(`/api/store-chat/stores/${encodeURIComponent(store.id)}/settings`,{method:"PUT",body:JSON.stringify({invoiceAiReaderEnabled:!settings.invoiceAiReaderEnabled})});setSettings(result.settings);setError("")}catch(e){setError(e.message)}finally{setBusy(false)}};
  const toggleAnnouncementAcknowledgement=async()=>{setBusy(true);try{const result=await api(`/api/store-chat/stores/${encodeURIComponent(store.id)}/settings`,{method:"PUT",body:JSON.stringify({announcementAcknowledgementRequired:!settings.announcementAcknowledgementRequired})});setSettings(result.settings);setError("")}catch(e){setError(e.message)}finally{setBusy(false)}};
  const sendToAiReader=async row=>{try{await api(`/api/store-chat/stores/${encodeURIComponent(store.id)}/messages/${encodeURIComponent(row.id)}/ai-reader`,{method:"POST",body:"{}"});await load(true)}catch(e){setError(e.message)}};
  const acknowledgeAnnouncement=async row=>{try{await api(`/api/store-chat/stores/${encodeURIComponent(store.id)}/messages/${encodeURIComponent(row.id)}/acknowledge`,{method:"POST",body:"{}"});await load(true)}catch(e){setError(e.message)}};
  const senders=[...new Map(rows.map(row=>[row.senderId,row.senderName||row.senderId])).entries()].sort((a,b)=>a[1].localeCompare(b[1],"el"));
  const visibleRows=rows.filter(row=>(!query.trim()||`${row.body} ${row.attachmentName||""} ${row.senderName||""} ${labels[row.category]||row.category}`.toLocaleLowerCase("el-GR").includes(query.trim().toLocaleLowerCase("el-GR")))&&(!dateFilter||new Date(row.createdAt).toLocaleDateString("en-CA")===dateFilter)&&(!senderFilter||row.senderId===senderFilter)&&(!taskFilter||row.taskId)),unreadCount=rows.filter(row=>!row.readByMe).length,taskCount=rows.filter(row=>row.taskId&&row.taskStatus==="OPEN").length;

  return <div className="shift-overlay"><section className="store-chat-modal">
    <header><div><small>MYWORKSTATION · ΕΣΩΤΕΡΙΚΗ ΕΠΙΚΟΙΝΩΝΙΑ</small><h2><MessageCircle/>Chat καταστήματος</h2><p>{store.name}</p></div><button type="button" onClick={onClose}><X/></button></header>
    <div className="store-chat-toolbar"><b>Συνομιλία καταστήματος {unreadCount>0&&<span className="store-chat-unread-count">{unreadCount} αδιάβαστα</span>}</b><button type="button" className={taskFilter?"is-active":""} onClick={()=>setTaskFilter(value=>!value)}><ClipboardList/>Εκκρεμότητες ({taskCount})</button>{permissions.canManageSettings&&<button type="button" className={settings.invoiceAiReaderEnabled?"store-chat-ai-toggle is-enabled":"store-chat-ai-toggle"} onClick={toggleAiReader} disabled={busy} title="Ενεργοποίηση ή απενεργοποίηση της σύνδεσης τιμολογίων Chat με το AI Reader"><Settings/>AI Reader: {settings.invoiceAiReaderEnabled?"Ενεργό":"Ανενεργό"}</button>}{permissions.canManageSettings&&<button type="button" className={settings.announcementAcknowledgementRequired?"store-chat-ack-toggle is-enabled":"store-chat-ack-toggle"} onClick={toggleAnnouncementAcknowledgement} disabled={busy} title="Απαίτηση ρητής επιβεβαίωσης ανάγνωσης στις ανακοινώσεις"><BadgeCheck/>Επιβεβαίωση: {settings.announcementAcknowledgementRequired?"Ενεργή":"Ανενεργή"}</button>}<button type="button" onClick={enableNotifications}>🔔 {notifications==="granted"?"Ενεργές":"Ειδοποιήσεις"}</button><button type="button" onClick={()=>load(true)} disabled={busy}><RefreshCw/> {busy?"Ανανέωση…":"Ανανέωση"}</button></div>
    {error&&<div className="store-chat-error">{error}</div>}
    <div className="store-chat-search"><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Αναζήτηση μηνυμάτων…"/><input type="date" value={dateFilter} onChange={e=>setDateFilter(e.target.value)} aria-label="Φίλτρο ημερομηνίας"/><select value={senderFilter} onChange={e=>setSenderFilter(e.target.value)} aria-label="Φίλτρο αποστολέα"><option value="">Όλοι οι αποστολείς</option>{senders.map(([id,name])=><option key={id} value={id}>{name}</option>)}</select>{(query||dateFilter||senderFilter)&&<button type="button" onClick={()=>{setQuery("");setDateFilter("");setSenderFilter("")}}>Καθαρισμός</button>}</div>
    <div className="store-chat-messages">{busy&&!rows.length?<div>Φόρτωση…</div>:!rows.length?<div>Δεν υπάρχουν ακόμη μηνύματα.</div>:visibleRows.map(row=>{const readers=readerNames(row.readers),acknowledgements=readerNames(row.acknowledgements),unread=!row.readByMe;return <article key={row.id} className={`${row.important?"is-important ":""}${row.pinned?"is-pinned ":""}${row.completed?"is-completed ":""}${unread?"is-unread":""}`} role={unread?"button":undefined} tabIndex={unread?0:undefined} onClick={()=>openMessage(row)} onKeyDown={e=>{if(unread&&(e.key==="Enter"||e.key===" ")){e.preventDefault();openMessage(row)}}}>
      <small>{row.pinned&&<b className="store-chat-pinned-label"><Pin/>ΚΑΡΦΙΤΣΩΜΕΝΗ · </b>}{unread&&<b className="store-chat-new">ΝΕΟ · </b>}<b className="store-chat-category">{labels[row.category]||row.category}</b> · {new Date(row.createdAt).toLocaleString("el-GR")}</small><b className="store-chat-sender">Από: {row.senderName||row.senderId}</b>{row.body&&<p>{row.body}</p>}
      {row.hasAttachment&&<div className="store-chat-attachment"><b>{row.attachmentMimeType?.startsWith("image/")?<Image/>:<FileText/>}{row.attachmentName}</b><small>{Math.ceil(Number(row.attachmentSize||0)/1024)} KB · προσωρινή προβολή</small><div><button type="button" onClick={e=>{e.stopPropagation();viewAttachment(row)}}><Eye/>{previews[row.id]?"Κλείσιμο":"Προβολή"}</button>{permissions.canDownload&&<button type="button" onClick={e=>{e.stopPropagation();downloadAttachment(row)}}><Download/>Κατέβασμα</button>}</div>{previews[row.id]&&<><img src={previews[row.id].url} alt={row.attachmentName}/>{previews[row.id].pageCount&&<small>Προεπισκόπηση πρώτης σελίδας · {previews[row.id].pageCount} σελίδες συνολικά</small>}</>}</div>}
      {unread?<small className="store-chat-open-hint">{openingId===row.id?"Άνοιγμα…":"Πάτησε το μήνυμα για να σημειωθεί ως διαβασμένο"}</small>:readers.length>0&&<small className="store-chat-read">Διαβάστηκε από: {readers.map(reader=>reader.name||reader.email||reader.id).filter(Boolean).join(", ")}</small>}
      {row.completed&&<small className="store-chat-completed"><CheckCircle2/>Ολοκληρώθηκε από: {row.completedByName||row.completedBy} · {new Date(row.completedAt).toLocaleString("el-GR")}</small>}
      {row.taskId&&<small className={`store-chat-task-badge ${row.taskStatus==="COMPLETED"?"is-completed":""}`}><ClipboardList/>Εκκρεμότητα · {row.taskStatus==="OPEN"?"Ανοιχτή":`Ολοκληρώθηκε από: ${row.taskCompletedByName||row.taskCompletedBy} · ${new Date(row.taskCompletedAt).toLocaleString("el-GR")}`}</small>}
      {row.aiReaderJobId&&<small className="store-chat-ai-badge"><Bot/>Στάλθηκε στο AI Reader από: {row.aiReaderSentByName||row.aiReaderSentBy} · {new Date(row.aiReaderSentAt).toLocaleString("el-GR")}</small>}
      {row.category==="ANNOUNCEMENT"&&settings.announcementAcknowledgementRequired&&acknowledgements.length>0&&<small className="store-chat-ack-list"><BadgeCheck/>Επιβεβαίωσαν: {acknowledgements.map(item=>item.name||item.id).filter(Boolean).join(", ")}</small>}
      <div className="store-chat-actions"><button type="button" className="store-chat-important" onClick={async e=>{e.stopPropagation();await api(`/api/store-chat/stores/${encodeURIComponent(store.id)}/messages/${encodeURIComponent(row.id)}`,{method:"PATCH",body:JSON.stringify({important:!row.important})});await load(true)}}><Star/> {row.important?"Σημαντικό":"Σήμανση σημαντικού"}</button>{settings.announcementAcknowledgementRequired&&row.category==="ANNOUNCEMENT"&&!row.acknowledgedByMe&&<button type="button" className="store-chat-acknowledge" onClick={async e=>{e.stopPropagation();await acknowledgeAnnouncement(row)}}><BadgeCheck/>Επιβεβαίωση ανάγνωσης</button>}{settings.invoiceAiReaderEnabled&&row.category==="INVOICE"&&row.hasAttachment&&!row.aiReaderJobId&&<button type="button" className="store-chat-ai-send" onClick={async e=>{e.stopPropagation();await sendToAiReader(row)}}><Bot/>Αποστολή στο AI Reader</button>}{permissions.canPin&&row.category==="ANNOUNCEMENT"&&<button type="button" className="store-chat-pin" onClick={async e=>{e.stopPropagation();await api(`/api/store-chat/stores/${encodeURIComponent(store.id)}/messages/${encodeURIComponent(row.id)}`,{method:"PATCH",body:JSON.stringify({pinned:!row.pinned})});await load(true)}}><Pin/> {row.pinned?"Ξεκαρφίτσωμα":"Καρφίτσωμα"}</button>}{permissions.canComplete&&<button type="button" className="store-chat-complete" onClick={async e=>{e.stopPropagation();await api(`/api/store-chat/stores/${encodeURIComponent(store.id)}/messages/${encodeURIComponent(row.id)}`,{method:"PATCH",body:JSON.stringify({completed:!row.completed})});await load(true)}}>{row.completed?<RotateCcw/>:<CheckCircle2/>}{row.completed?"Επαναφορά":"Ολοκληρώθηκε"}</button>}{permissions.canCreateTask&&!row.taskId&&<button type="button" className="store-chat-task" onClick={async e=>{e.stopPropagation();try{await api(`/api/store-chat/stores/${encodeURIComponent(store.id)}/messages/${encodeURIComponent(row.id)}/task`,{method:"POST"});await load(true)}catch(err){setError(err.message)}}}><ClipboardList/>Δημιουργία εκκρεμότητας</button>}{permissions.canManageTask&&row.taskId&&<button type="button" className="store-chat-task-manage" onClick={async e=>{e.stopPropagation();try{await api(`/api/store-chat/stores/${encodeURIComponent(store.id)}/tasks/${encodeURIComponent(row.taskId)}`,{method:"PATCH",body:JSON.stringify({completed:row.taskStatus==="OPEN"})});await load(true)}catch(err){setError(err.message)}}}>{row.taskStatus==="OPEN"?<CheckCircle2/>:<RotateCcw/>}{row.taskStatus==="OPEN"?"Κλείσιμο εκκρεμότητας":"Επαναφορά εκκρεμότητας"}</button>}</div>
    </article>})}</div>
    <form className="store-chat-compose" onSubmit={send}><select value={category} onChange={e=>setCategory(e.target.value)}>{Object.entries(labels).map(([key,label])=><option key={key} value={key}>{label}</option>)}</select><input value={body} onChange={e=>setBody(e.target.value)} placeholder="Γράψε μήνυμα για το κατάστημα…" maxLength={5000}/><label className="store-chat-file"><Paperclip/>Φωτογραφία / PDF<input type="file" accept="image/jpeg,image/png,image/webp,application/pdf" onChange={e=>{const file=e.target.files?.[0]||null;if(file&&file.size>7*1024*1024){setError("Το αρχείο πρέπει να είναι έως 7 MB.");e.target.value="";setAttachment(null)}else setAttachment(file)}}/></label>{attachment&&<small className="store-chat-selected-file">{attachment.name}</small>}<button disabled={busy||(!body.trim()&&!attachment)}><Send/>Αποστολή</button></form>
  </section></div>
}
