import React,{useEffect,useMemo,useState} from "react";
import {Package,Printer,X} from "lucide-react";
import "./store-preparation-modal.css";

const euro=v=>Number(v||0).toLocaleString("el-GR",{style:"currency",currency:"EUR"});
const upper=v=>String(v||"").toLocaleUpperCase("el-GR");
const groupKind=name=>{const n=upper(name);if(n.includes("ΖΑΧ")||n.includes("SUGAR"))return"SUGAR";if(n.includes("ΠΑΓ")||n.includes("ICE"))return"ICE";if(n.includes("ΧΤΥΠ")||n.includes("SHAKE"))return"SHAKE";if(n.includes("ΣΙΡ")||n.includes("SYRUP"))return"SYRUP";if(n.includes("ΓΑΛ")||n.includes("MILK"))return"MILK";if(n.includes("EXTRA")||n.includes("ΕΞΤΡΑ")||n.includes("SHOT")||n.includes("DECAF")||n.includes("ΚΑΝΕΛ")||n.includes("ΣΑΝΤ"))return"EXTRA";return"OTHER"};
const order={SUGAR:1,ICE:2,SHAKE:3,SYRUP:4,MILK:5,EXTRA:6,OTHER:7};

export default function StorePreparationModal({api,store,cart,onClose,setMessage,setError,onApply}){
 const [groups,setGroups]=useState([]),[settings,setSettings]=useState(null),[selectedProduct,setSelectedProduct]=useState(cart[0]?.id||""),[selected,setSelected]=useState({}),[spoons,setSpoons]=useState(0),[iceQty,setIceQty]=useState(0),[note,setNote]=useState(""),[priority,setPriority]=useState("NORMAL"),[busy,setBusy]=useState(false);
 const line=cart.find(x=>x.id===selectedProduct)||cart[0];
 useEffect(()=>{if(!line?.id)return;setGroups([]);setSettings(null);api(`/api/store-pos/stores/${store.id}/modifiers?productId=${encodeURIComponent(line.id)}`).then(r=>{setGroups(r.groups||[]);setSettings(r.settings||null)}).catch(e=>setError(e.message))},[store.id,line?.id]);
 const normalized=useMemo(()=>groups.map(g=>({...g,kind:groupKind(g.description)})).sort((a,b)=>(order[a.kind]||99)-(order[b.kind]||99)||String(a.description).localeCompare(String(b.description),"el")),[groups]);
 const chosen=useMemo(()=>Object.values(selected).flat(),[selected]);
 const extras=chosen.reduce((s,m)=>s+Number(m.price||0),0),fee=Number(settings?.environmentalFee||0),base=Number(line?.salePrice||0),finalPrice=base+extras+fee;
 const toggle=(group,item)=>setSelected(current=>{const rows=current[group.id]||[],exists=rows.some(x=>x.id===item.id);if(exists)return{...current,[group.id]:rows.filter(x=>x.id!==item.id)};const max=Math.max(1,Number(group.maxSelections||1));return{...current,[group.id]:max>1?[...rows,item].slice(-max):[item]}});
 const addSynthetic=(description,value)=>({id:`synthetic-${description}-${value}`,description:`${description} ${value}`,price:0});
 const apply=async()=>{if(!line)return;setBusy(true);try{const modifiers=[...chosen];if(spoons>0)modifiers.push(addSynthetic("ΚΟΥΤΑΛΙΑ",spoons));if(iceQty>0)modifiers.push(addSynthetic("ΠΑΓΟΣ ΠΟΣΟΤΗΤΑ",iceQty));const payload={productId:line.id,productName:line.name,modifiers,modifierTotal:extras,environmentalFee:fee,unitPrice:finalPrice,note:note||null,priority,productionStation:settings?.productionStation||"ΠΑΡΑΓΩΓΗ",autoPrint:settings?.autoPrint!==false};onApply?.(payload);await api(`/api/store-pos/stores/${store.id}/preparation`,{method:"POST",body:JSON.stringify({items:[{productId:line.id,quantity:line.quantity,modifiers:modifiers.map(m=>({id:m.id,description:m.description,price:Number(m.price||0)}))}],note:[priority!=="NORMAL"?`ΠΡΟΤΕΡΑΙΟΤΗΤΑ: ${priority}`:null,note].filter(Boolean).join(" · ")||null,priority})});setMessage(`Η παρασκευή του «${line.name}» καταχωρίστηκε${priority!=="NORMAL"?" με ΠΡΟΤΕΡΑΙΟΤΗΤΑ":""}.`);onClose()}catch(e){setError(e.message)}finally{setBusy(false)}};
 const renderGroup=g=><div className={`prep-group prep-${g.kind.toLowerCase()}`} key={g.id}><h3>{g.description}</h3><div className="prep-options">{(g.items||[]).map(item=>{const active=(selected[g.id]||[]).some(x=>x.id===item.id);return <button type="button" className={active?"active":""} key={item.id} onClick={()=>toggle(g,item)}><span>{item.description}</span>{Number(item.price||0)!==0&&<small>{Number(item.price)>0?"+":""}{euro(item.price)}</small>}</button>})}</div>{g.kind==="SUGAR"&&<div className="prep-step"><b>ΚΟΥΤΑΛΙΑ</b>{[0,1,2,3,4].map(n=><button key={n} className={spoons===n?"active":""} onClick={()=>setSpoons(n)}>{n}</button>)}</div>}{g.kind==="ICE"&&<div className="prep-step"><b>ΠΟΣΟΤΗΤΑ</b>{[0,1,2,3].map(n=><button key={n} className={iceQty===n?"active":""} onClick={()=>setIceQty(n)}>{n}</button>)}</div>}</div>;
 return <div className="prep-overlay" onMouseDown={e=>e.target===e.currentTarget&&!busy&&onClose()}><section className="prep-modal"><header><div><small>MYWORKSTATION · ΠΑΡΑΣΚΕΥΗ</small><h2>{line?.name||"Παρασκευή"}</h2></div><button onClick={()=>!busy&&onClose()}><X/></button></header><main><aside className="prep-products"><h3>ΠΡΟΪΟΝΤΑ</h3>{cart.map(i=><button key={i.id} className={i.id===line?.id?"active":""} onClick={()=>{setSelectedProduct(i.id);setSelected({});setSpoons(0);setIceQty(0)}}><b>{i.quantity} × {i.name}</b><span>{euro(i.salePrice)}</span></button>)}<div className="prep-price"><span>Βασική τιμή</span><b>{euro(base)}</b><span>Modifiers</span><b>{euro(extras)}</b>{fee>0&&<><span>Εισφορά περιβάλλοντος</span><b>{euro(fee)}</b></>}<strong>ΣΥΝΟΛΟ {euro(finalPrice)}</strong></div></aside><div className="prep-body"><div className="prep-groups">{normalized.length?normalized.map(renderGroup):<div className="prep-empty">Δεν έχουν οριστεί ακόμη ομάδες Modifiers για αυτό το προϊόν στο BackOffice.</div>}</div><div className="prep-note"><label>ΣΗΜΕΙΩΣΗ / ΕΙΔΙΚΕΣ ΟΔΗΓΙΕΣ<textarea value={note} onChange={e=>setNote(e.target.value)} placeholder="π.χ. πολύ ζεστό, χωρίς καλαμάκι..."/></label></div></div><aside className="prep-summary"><h3>ΕΠΙΛΕΓΜΕΝΑ</h3>{chosen.map(m=><div key={m.id}><span>{m.description}</span><b>{Number(m.price||0)?euro(m.price):""}</b></div>)}{spoons>0&&<div><span>Κουτάλια</span><b>{spoons}</b></div>}{iceQty>0&&<div><span>Πάγος ποσότητα</span><b>{iceQty}</b></div>}<div className="prep-pack"><Package/><span>{fee>0?`Συσκευασία / εισφορά ${euro(fee)} από συνταγή BackOffice`:"Συσκευασία από συνταγή BackOffice"}</span></div></aside></main><footer><div className="prep-priority"><b>ΠΡΟΤΕΡΑΙΟΤΗΤΑ ΠΑΡΑΓΩΓΗΣ</b><button className={priority==="DOCTOR"?"doctor active":"doctor"} onClick={()=>setPriority("DOCTOR")}>ΙΑΤΡΟΣ</button><button className={priority==="NURSE"?"nurse active":"nurse"} onClick={()=>setPriority("NURSE")}>ΝΟΣΗΛΕΥΤΗΣ / ΝΟΣΟΚΟΜΟΣ</button><button className={priority==="STAFF"?"staff active":"staff"} onClick={()=>setPriority("STAFF")}>ΠΡΟΣΩΠΙΚΟ</button><button className={priority==="NORMAL"?"active":""} onClick={()=>setPriority("NORMAL")}>ΚΑΝΟΝΙΚΟΣ ΠΕΛΑΤΗΣ</button></div><button className="prep-submit" disabled={busy||!line} onClick={apply}><Printer/> {busy?"Καταχώριση…":"ΕΦΑΡΜΟΓΗ & ΠΑΡΑΣΚΕΥΗ"}</button></footer></section></div>
}
