import React,{useEffect,useState} from "react";
import {Landmark,Upload} from "lucide-react";
const num=v=>Number(String(v||"0").replace(",","."))||0;
const read=file=>new Promise((ok,bad)=>{const r=new FileReader();r.onload=()=>ok(r.result);r.onerror=bad;r.readAsDataURL(file)});
export default function StoreBankDeposit({api,store,onChanged,setMessage,allowCash}){
 const [accounts,setAccounts]=useState([]),[bankAccountId,setBankAccountId]=useState(""),[amount,setAmount]=useState(""),[depositor,setDepositor]=useState(""),[file,setFile]=useState(null),[busy,setBusy]=useState(false);
 useEffect(()=>{api(`/api/transactions/stores/${store.id}/bank-accounts`).then(r=>setAccounts(r.items||[])).catch(e=>setMessage?.(`❌ ${e.message}`))},[api,store.id,setMessage]);
 const submit=async()=>{if(!allowCash)return setMessage?.("❌ Απαιτείται ενεργή βάρδια για κατάθεση μετρητών.");if(!bankAccountId||num(amount)<=0||!depositor.trim())return setMessage?.("❌ Επίλεξε λογαριασμό, ποσό και καταθέτη.");setBusy(true);try{const attachment=file?{dataUrl:await read(file),filename:file.name}:null;const r=await api(`/api/transactions/stores/${store.id}/bank-deposits`,{method:"POST",body:JSON.stringify({bankAccountId,amount:num(amount),depositor,depositedAt:new Date().toISOString(),attachment,idempotencyKey:`bank-${Date.now()}-${Math.random().toString(36).slice(2)}`})});setMessage?.(`✅ Η κατάθεση καταχωρίστηκε ${r.status==="PENDING_PROOF"?"σε αναμονή αποδεικτικού":"για έλεγχο"}.`);setAmount("");setDepositor("");setFile(null);onChanged?.()}catch(e){setMessage?.(`❌ ${e.message}`)}finally{setBusy(false)}};
 return <div className="pos-payment-form"><div style={{padding:"10px",borderRadius:8,background:"#e9f8f1",fontWeight:800}}>Κατάθεση Τράπεζας — αφαιρείται μία φορά από την ενεργή βάρδια και δεν είναι έξοδο.</div><label>Τραπεζικός λογαριασμός<select value={bankAccountId} onChange={e=>setBankAccountId(e.target.value)} disabled={busy}><option value="">Επίλεξε λογαριασμό</option>{accounts.map(a=><option key={a.id} value={a.id}>{a.bankName} · {a.name}{a.ibanMasked?` · ${a.ibanMasked}`:""}</option>)}</select></label><label>Ποσό<input inputMode="decimal" value={amount} onChange={e=>setAmount(e.target.value)} placeholder="0,00" disabled={busy}/></label><label>Καταθέτης<input value={depositor} onChange={e=>setDepositor(e.target.value)} disabled={busy}/></label><label><Upload/> Απόδειξη κατάθεσης (προαιρετικά τώρα)<input type="file" accept="image/jpeg,image/png,image/webp,application/pdf" onChange={e=>setFile(e.target.files?.[0]||null)} disabled={busy}/></label><button className="pos-primary-action" disabled={busy||!allowCash} onClick={submit}><Landmark/>{busy?"Καταχώριση…":"Καταχώριση κατάθεσης"}</button></div>;
}