import React,{useMemo,useRef,useState} from "react";
import {Camera,FileUp} from "lucide-react";

const AI_THRESHOLD=65;
const normalize=value=>String(value||"").normalize("NFD").replace(/[\u0300-\u036f]/g,"").toUpperCase().replace(/[^A-ZΑ-Ω0-9]/g,"");
const money=value=>{const n=Number(String(value??"").replace(/\s/g,"").replace(/\.(?=\d{3}(?:\D|$))/g,"").replace(",",".").replace(/[^0-9.]/g,""));return Number.isFinite(n)?n:null};
const readFile=file=>new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(r.result);r.onerror=()=>reject(new Error("Δεν ήταν δυνατή η ανάγνωση του τιμολογίου."));r.readAsDataURL(file)});
const dataUrlToBytes=dataUrl=>{const comma=String(dataUrl||"").indexOf(",");if(comma<0)throw new Error("Μη έγκυρο αρχείο παραστατικού.");const binary=atob(dataUrl.slice(comma+1)),bytes=new Uint8Array(binary.length);for(let i=0;i<binary.length;i++)bytes[i]=binary.charCodeAt(i);return bytes};
async function pdfPreview(dataUrl){const pdfjs=await import("pdfjs-dist/legacy/build/pdf.mjs");pdfjs.GlobalWorkerOptions.workerSrc=new URL("pdfjs-dist/legacy/build/pdf.worker.min.mjs",import.meta.url).toString();const pdf=await pdfjs.getDocument({data:dataUrlToBytes(dataUrl)}).promise,page=await pdf.getPage(1),viewport=page.getViewport({scale:2}),canvas=document.createElement("canvas");canvas.width=Math.ceil(viewport.width);canvas.height=Math.ceil(viewport.height);await page.render({canvasContext:canvas.getContext("2d"),viewport}).promise;return {imageDataUrl:canvas.toDataURL("image/jpeg",.92),pageCount:pdf.numPages}}
function collectLines(data){const found=[];const visit=node=>{if(!node)return;if(Array.isArray(node)){node.forEach(visit);return}if(node.text&&String(node.text).trim())found.push({text:String(node.text).trim(),confidence:Math.max(0,Math.min(100,Math.round(Number(node.confidence)||0)))});for(const key of ["blocks","paragraphs","lines"])visit(node[key])};visit(data.blocks);if(found.length)return found;return String(data.text||"").split(/\r?\n/).map(text=>text.trim()).filter(Boolean).map(text=>({text,confidence:Math.round(Number(data.confidence)||0)}))}
async function localOcr(file){const dataUrl=await readFile(file);let source=dataUrl,pageCount=null;if(file.type==="application/pdf"){const preview=await pdfPreview(dataUrl);source=preview.imageDataUrl;pageCount=preview.pageCount}const {createWorker}=await import("tesseract.js"),worker=await createWorker("ell+eng");let result;try{result=await worker.recognize(source)}finally{await worker.terminate()}return {dataUrl,mimeType:file.type||"image/jpeg",filename:file.name||"timologio.jpg",confidence:Math.max(0,Math.min(100,Math.round(Number(result?.data?.confidence)||0))),rawText:result?.data?.text||"",lines:collectLines(result?.data||{}),pageCount}}
function localMeta(rawText,suppliers=[]){const lines=String(rawText||"").split(/\r?\n/).map(x=>x.trim()).filter(Boolean),joined=normalize(rawText);let supplier=null,best=0;for(const item of suppliers){const key=normalize(item.name);if(key.length>=4&&joined.includes(key)&&key.length>best){best=key.length;supplier=item}}let documentNumber="";for(const line of lines){const m=line.match(/(?:ΤΙΜΟΛΟΓΙΟ|ΤΙΜ|INVOICE|ΠΑΡΑΣΤΑΤΙΚΟ).{0,30}?(?:ΑΡ\.?|ΑΡΙΘΜ(?:ΟΣ)?|NO\.?|#)?\s*[:\-]?\s*([A-ZΑ-Ω0-9][A-ZΑ-Ω0-9\-/]{2,})/i)||line.match(/(?:ΑΡ\.?\s*(?:ΤΙΜΟΛΟΓΙΟΥ)?|ΑΡΙΘΜΟΣ\s*(?:ΤΙΜΟΛΟΓΙΟΥ)?|INVOICE\s*NO\.?)\s*[:\-]?\s*([A-ZΑ-Ω0-9\-/]{3,})/i);if(m){documentNumber=m[1].trim();break}}let documentDate="";for(const line of lines){const m=line.match(/(?:ΗΜΕΡΟΜΗΝΙΑ|DATE)?\s*[:\-]?\s*(\d{1,2}[\/\-.]\d{1,2}[\/\-.](?:20)?\d{2})/i);if(m){let[d,mo,y]=m[1].split(/[\/\-.]/).map(Number);if(y<100)y+=2000;documentDate=`${String(y).padStart(4,"0")}-${String(mo).padStart(2,"0")}-${String(d).padStart(2,"0")}`;break}}let totalGross=null;const totalWords=/(ΓΕΝΙΚΟ\s*ΣΥΝΟΛΟ|ΠΛΗΡΩΤΕΟ|ΤΕΛΙΚΟ\s*ΣΥΝΟΛΟ|ΣΥΝΟΛΟ\s*ΜΕ\s*ΦΠΑ|TOTAL\s*DUE|GRAND\s*TOTAL|TOTAL)/i;for(const line of lines.filter(x=>totalWords.test(x)).reverse()){const nums=line.match(/\d{1,3}(?:\.\d{3})*(?:,\d{2})|\d+(?:[.,]\d{2})/g)||[],candidate=nums.map(money).filter(n=>n!==null&&n>0).pop();if(candidate){totalGross=candidate;break}}return {supplierId:supplier?.id||"",supplierName:supplier?.name||"",documentNumber,documentDate,totalGross,supplierCandidate:{name:supplier?.name||"",taxId:"",email:"",phone:"",address:"",city:""}}}

export default function StoreSupplierInvoiceV3({api,store,suppliers=[],onChanged,setMessage}){
 const [invoice,setInvoice]=useState({file:null,jobId:"",stage:"IDLE",confidence:null,supplierId:"",supplierName:"",documentNumber:"",documentDate:"",totalGross:"",settlementMode:"",status:"Περιμένει τιμολόγιο.",working:false,done:false});
 const [candidate,setCandidate]=useState({name:"",taxId:"",phone:"",email:"",address:"",city:""});
 const [cameraOpen,setCameraOpen]=useState(false),[stream,setStream]=useState(null);const videoRef=useRef(null),canvasRef=useRef(null);
 const selectedSupplier=useMemo(()=>suppliers.find(s=>String(s.id)===String(invoice.supplierId))||null,[suppliers,invoice.supplierId]);
 const stopCamera=()=>{stream?.getTracks?.().forEach(t=>t.stop());setStream(null);setCameraOpen(false)};
 const startCamera=async()=>{try{stopCamera();const s=await navigator.mediaDevices.getUserMedia({video:{facingMode:"environment"},audio:false});setStream(s);setCameraOpen(true);setTimeout(()=>{if(videoRef.current)videoRef.current.srcObject=s},0)}catch{setInvoice(x=>({...x,status:"❌ Δεν μπόρεσε να ανοίξει η κάμερα. Έλεγξε την άδεια κάμερας του browser."}))}};
 const capture=()=>{const v=videoRef.current,c=canvasRef.current;if(!v||!c)return;c.width=v.videoWidth||1280;c.height=v.videoHeight||720;c.getContext("2d").drawImage(v,0,0,c.width,c.height);c.toBlob(blob=>{if(!blob)return;stopCamera();processFile(new File([blob],`timologio-${Date.now()}.jpg`,{type:"image/jpeg"}))},"image/jpeg",.92)};
 const applyResult=(base,result,match,source)=>{const supplierMatch=match||null,supplierCandidate=result?.supplier||base.supplierCandidate||{};setCandidate({name:supplierCandidate.name||"",taxId:supplierCandidate.taxId||"",phone:supplierCandidate.phone||"",email:supplierCandidate.email||"",address:supplierCandidate.address||"",city:supplierCandidate.city||""});setInvoice(x=>({...x,stage:"READY",confidence:Number(result?.aiConfidence??x.confidence??0),supplierId:supplierMatch?.id||base.supplierId||"",supplierName:supplierMatch?.name||base.supplierName||supplierCandidate.name||"",documentNumber:result?.documentNumber||base.documentNumber||"",documentDate:result?.documentDate||base.documentDate||"",totalGross:Number(result?.totalGross||base.totalGross||0)>0?Number(result?.totalGross||base.totalGross).toFixed(2):"",status:`${source} · Έλεγξε τα στοιχεία και επίλεξε ΠΛΗΡΩΜΕΝΟ ή ΜΕ ΠΙΣΤΩΣΗ.`,working:false}))};
 const processFile=async file=>{if(!file)return;setInvoice({file,jobId:"",stage:"OCR",confidence:null,supplierId:"",supplierName:"",documentNumber:"",documentDate:"",totalGross:"",settlementMode:"",status:"1/2 OCR: Διαβάζω ολόκληρο το τιμολόγιο…",working:true,done:false});try{const ocr=await localOcr(file),base=localMeta(ocr.rawText,suppliers),job=await api("/api/commerce/ai-reader/jobs",{method:"POST",body:JSON.stringify({storeId:store.id,filename:ocr.filename,mimeType:ocr.mimeType,dataUrl:ocr.dataUrl,localConfidence:ocr.confidence,result:{rawText:ocr.rawText,lines:ocr.lines,pageCount:ocr.pageCount}})});setInvoice(x=>({...x,jobId:job.id,confidence:ocr.confidence,status:`OCR ${ocr.confidence}%: ολοκληρώθηκε.`}));if(ocr.confidence<AI_THRESHOLD){setInvoice(x=>({...x,stage:"AI",status:`OCR ${ocr.confidence}% (<65%). 2/2 Αυτόματος επανέλεγχος με AI…`}));const ai=await api(`/api/commerce/ai-reader/jobs/${encodeURIComponent(job.id)}/ai-recheck`,{method:"POST",body:"{}"});applyResult(base,ai.result||{},ai.supplierMatch,`AI ${Math.round(Number(ai.confidence||0))}% μετά από OCR ${ocr.confidence}%`)}else applyResult(base,{},base.supplierId?{id:base.supplierId,name:base.supplierName}:null,`OCR ${ocr.confidence}%`)}catch(error){setInvoice(x=>({...x,stage:"ERROR",working:false,status:`❌ ${error.message||"Η ανάγνωση απέτυχε."}`}))}};
 const saveSupplier=async()=>{if(!invoice.jobId||candidate.name.trim().length<2)return;setInvoice(x=>({...x,working:true,status:"Καταχωρίζω τον νέο προμηθευτή στο BackOffice…"}));try{const data=await api(`/api/commerce/ai-reader/jobs/${encodeURIComponent(invoice.jobId)}/supplier`,{method:"POST",body:JSON.stringify(candidate)});setInvoice(x=>({...x,supplierId:data.supplier.id,supplierName:data.supplier.name,working:false,status:data.message||"Ο προμηθευτής συνδέθηκε."}));onChanged?.()}catch(error){setInvoice(x=>({...x,working:false,status:`❌ ${error.message}`}))}};
 const ready=Boolean(invoice.jobId&&invoice.supplierId&&invoice.documentNumber.trim()&&invoice.documentDate&&Number(invoice.totalGross)>0&&invoice.settlementMode&&!invoice.working&&!invoice.done);
 const submit=async()=>{if(!ready)return;setInvoice(x=>({...x,working:true,status:invoice.settlementMode==="PAID"?`Καταχωρίζω το τιμολόγιο ${invoice.documentNumber} και την πληρωμή ${Number(invoice.totalGross).toFixed(2)} €…`:`Καταχωρίζω το τιμολόγιο ${invoice.documentNumber} με πίστωση…`}));try{const data=await api(`/api/commerce/ai-reader/jobs/${encodeURIComponent(invoice.jobId)}/pos-intake`,{method:"POST",body:JSON.stringify({supplierId:invoice.supplierId,documentNumber:invoice.documentNumber.trim(),documentDate:invoice.documentDate,totalGross:Number(invoice.totalGross),settlementMode:invoice.settlementMode})});const text=invoice.settlementMode==="PAID"?(data.paymentRecorded?`✅ Πληρωμή ${Number(invoice.totalGross).toFixed(2)} € καταγράφηκε στη βάρδια και το τιμολόγιο ${invoice.documentNumber} στάλθηκε για έλεγχο.`:`⚠️ Το τιμολόγιο καταχωρίστηκε αλλά δεν επιβεβαιώθηκε πληρωμή. Μην το ξαναπατήσεις.`):`✅ Το τιμολόγιο ${invoice.documentNumber} καταχωρίστηκε ΜΕ ΠΙΣΤΩΣΗ και στάλθηκε για έλεγχο.`;setInvoice(x=>({...x,working:false,done:true,stage:"DONE",status:text}));setMessage?.(text);onChanged?.()}catch(error){setInvoice(x=>({...x,working:false,status:`❌ ${error.message||"Η καταχώριση απέτυχε."}`}))}};
 return <div className="pos-invoice-v3" style={{border:"2px solid #d8b45b",borderRadius:12,padding:14,marginTop:12,background:"#fffaf0"}}>
  <div style={{fontWeight:900,fontSize:18}}>Αυτόματη καταχώρηση τιμολογίου <small style={{fontSize:12,background:"#dcfce7",padding:"4px 7px",borderRadius:12}}>V3 · React</small></div>
  <div style={{fontWeight:700,margin:"6px 0 10px"}}>Σκάναρε ή επίλεξε ολόκληρο το τιμολόγιο</div>
  <div className="pos-photo-actions"><button type="button" onClick={startCamera} disabled={invoice.working||invoice.done}><Camera/> Λήψη από κάμερα</button><label><FileUp/> Επιλογή αρχείου / PDF<input type="file" accept="image/jpeg,image/png,image/webp,application/pdf" onChange={e=>processFile(e.target.files?.[0]||null)} disabled={invoice.working||invoice.done}/></label></div>
  {invoice.file&&<div style={{padding:"8px 10px",background:"#fff",borderRadius:8,marginTop:7}}>{invoice.file.name}</div>}
  {cameraOpen&&<div className="pos-camera-live"><video ref={videoRef} autoPlay playsInline/><canvas ref={canvasRef} hidden/><div><button type="button" onClick={capture}><Camera/> Φωτογράφιση</button><button type="button" onClick={stopCamera}>Κλείσιμο κάμερας</button></div></div>}
  <div style={{padding:"9px 10px",background:"#fff",borderRadius:8,margin:"10px 0"}}>{invoice.status}</div>
  <label>Προμηθευτής<select value={invoice.supplierId} onChange={e=>setInvoice(x=>({...x,supplierId:e.target.value,supplierName:e.target.selectedOptions?.[0]?.textContent||""}))} disabled={invoice.working||invoice.done}><option value="">Επίλεξε</option>{suppliers.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label>
  {!invoice.supplierId&&invoice.jobId&&<div style={{border:"2px solid #f59e0b",borderRadius:10,padding:10,margin:"8px 0",background:"#fff7ed"}}><b>Νέος προμηθευτής — δεν υπάρχει στο BackOffice</b><div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:6,marginTop:7}}>{[["name","Επωνυμία"],["taxId","ΑΦΜ"],["phone","Τηλέφωνο"],["email","Email"],["address","Διεύθυνση"],["city","Πόλη"]].map(([key,label])=><input key={key} placeholder={label} value={candidate[key]} onChange={e=>setCandidate(c=>({...c,[key]:e.target.value}))}/>)}</div><button type="button" onClick={saveSupplier} disabled={invoice.working||candidate.name.trim().length<2} style={{width:"100%",marginTop:8,fontWeight:800}}>✓ Καταχώριση στους Προμηθευτές BackOffice</button></div>}
  <label>Αριθμός τιμολογίου<input value={invoice.documentNumber} onChange={e=>setInvoice(x=>({...x,documentNumber:e.target.value}))} disabled={invoice.working||invoice.done}/></label>
  <label>Ημερομηνία<input type="date" value={invoice.documentDate} onChange={e=>setInvoice(x=>({...x,documentDate:e.target.value}))} disabled={invoice.working||invoice.done}/></label>
  <label>Συνολικό ποσό<input inputMode="decimal" value={invoice.totalGross} onChange={e=>setInvoice(x=>({...x,totalGross:e.target.value.replace(",",".")}))} disabled={invoice.working||invoice.done}/></label>
  <div style={{display:"flex",gap:8,margin:"10px 0"}}><button type="button" onClick={()=>setInvoice(x=>({...x,settlementMode:"PAID"}))} disabled={invoice.working||invoice.done} style={{flex:1,fontWeight:invoice.settlementMode==="PAID"?900:400}}>ΠΛΗΡΩΜΕΝΟ</button><button type="button" onClick={()=>setInvoice(x=>({...x,settlementMode:"CREDIT"}))} disabled={invoice.working||invoice.done} style={{flex:1,fontWeight:invoice.settlementMode==="CREDIT"?900:400}}>ΜΕ ΠΙΣΤΩΣΗ</button></div>
  <small><b>ΠΛΗΡΩΜΕΝΟ:</b> αφαιρείται από τα μετρητά της ενεργής βάρδιας. <b>ΜΕ ΠΙΣΤΩΣΗ:</b> δεν αφαιρείται ποσό. Η αποθήκη ενημερώνεται μόνο μετά την Οριστικοποίηση.</small>
  <button type="button" onClick={submit} disabled={!ready} style={{width:"100%",marginTop:10,fontWeight:900,padding:10}}>{invoice.working?"Καταχώριση σε εξέλιξη…":invoice.done?"Καταχωρίστηκε":"Καταχώριση τιμολογίου για έλεγχο"}</button>
 </div>
}