import React,{useEffect,useMemo,useState} from "react";
import {Search,Settings2,X} from "lucide-react";
import "./store-pos-button-editor.css";

const CHILD_SEP="::MWSCHILD::";
const codesOf=product=>[product?.sourceCode,product?.masterCode,product?.sku,...(product?.barcodes||[])].map(String).filter(Boolean);
const parseChildren=button=>{if(Array.isArray(button?.children))return button.children;const raw=String(button?.categoryName||button?.productQuery||"");const at=raw.indexOf(CHILD_SEP);if(at<0)return[];try{return JSON.parse(decodeURIComponent(raw.slice(at+CHILD_SEP.length)))||[]}catch{return[]}};
const baseCategory=button=>String(button?.categoryName||button?.label||"").split(CHILD_SEP)[0];
const packChildren=(name,children)=>`${name}${CHILD_SEP}${encodeURIComponent(JSON.stringify(children))}`;

export default function StorePosButtonEditor({api,store,layout,products,enabled,onSaved}){
 const [target,setTarget]=useState(null),[draft,setDraft]=useState(null),[query,setQuery]=useState(""),[busy,setBusy]=useState(false),[error,setError]=useState("");
 const rows=useMemo(()=>{const q=query.trim().toLocaleLowerCase("el-GR");if(!q)return products.slice(0,80);return products.filter(p=>String(p.name||"").toLocaleLowerCase("el-GR").includes(q)||codesOf(p).some(c=>c.toLocaleLowerCase("el-GR").includes(q))).slice(0,80)},[products,query]);
 const open=(kind,index)=>{const button=(kind==="quick"?layout.quickKeys:layout.categories)[index];if(!button)return;setTarget({kind,index});setDraft({...button,children:parseChildren(button)});setQuery("");setError("")};
 useEffect(()=>{if(!enabled)return;const bind=(selector,kind)=>{const panel=document.querySelector(selector);if(!panel)return()=>{};const click=event=>{const button=event.target.closest("button");if(!button||!panel.contains(button))return;const rect=button.getBoundingClientRect();if(event.clientX<rect.right-30||event.clientY>rect.top+30)return;const buttons=[...panel.querySelectorAll(":scope > button")],index=buttons.indexOf(button);if(index<0)return;event.preventDefault();event.stopPropagation();open(kind,index)};panel.addEventListener("click",click,true);return()=>panel.removeEventListener("click",click,true)};const cleanQuick=bind(".mws-standard-pos .standard-quick > div","quick"),cleanCategories=bind(".mws-standard-pos .standard-category-strip > div","category");return()=>{cleanQuick();cleanCategories()}},[enabled,layout]);
 const choose=product=>{const code=codesOf(product)[0];if(!code)return;setDraft(current=>({...current,label:product.name,productQuery:code,productCodes:[code],visible:true}));setQuery(product.name)};
 const addChild=()=>{const label=window.prompt("Όνομα νέας υποκατηγορίας");if(!label?.trim())return;setDraft(current=>({...current,children:[...(current.children||[]),{id:`child-${Date.now()}`,label:label.trim(),categoryName:label.trim(),productCodes:[],color:current.color||"#168ca0",visible:true}]}))};
 const toggleChildProduct=(childIndex,product)=>{const code=codesOf(product)[0];if(!code)return;setDraft(current=>({...current,children:current.children.map((child,index)=>index!==childIndex?child:{...child,productCodes:(child.productCodes||[]).includes(code)?child.productCodes.filter(x=>x!==code):[...(child.productCodes||[]),code]})}))};
 const save=async()=>{setBusy(true);setError("");try{const next={...layout,quickKeys:[...(layout.quickKeys||[])],categories:[...(layout.categories||[])]};if(target.kind==="quick")next.quickKeys[target.index]={...draft,children:undefined};else{const name=String(draft.label||baseCategory(draft)||"ΚΑΤΗΓΟΡΙΑ").trim();next.categories[target.index]={...draft,categoryName:packChildren(name,draft.children||[]),children:draft.children||[],visible:true}}const result=await api(`/api/store-pos/stores/${store.id}/layout`,{method:"PUT",body:JSON.stringify({layout:next})});onSaved(result);setTarget(null)}catch(e){setError(e.message)}finally{setBusy(false)}};
 if(!enabled)return null;
 return <>{target&&<div className="pos-button-editor-overlay" onMouseDown={e=>e.target===e.currentTarget&&!busy&&setTarget(null)}><section><header><div><small>{target.kind==="quick"?"ΣΥΝΔΕΣΗ ΓΡΗΓΟΡΟΥ ΚΟΥΜΠΙΟΥ":"ΡΥΘΜΙΣΗ ΚΑΤΗΓΟΡΙΑΣ"}</small><h2>{target.kind==="quick"?`Κουμπί ${target.index+1}`:`Κατηγορία ${target.index+1}`}</h2></div><button onClick={()=>setTarget(null)}><X/></button></header><main>{error&&<div className="pos-button-editor-error">{error}</div>}<div className="pos-button-editor-fields"><label>Όνομα κουμπιού<input value={draft?.label||""} onChange={e=>setDraft({...draft,label:e.target.value})}/></label><label>Χρώμα φόντου<input type="color" value={draft?.color||"#168ca0"} onChange={e=>setDraft({...draft,color:e.target.value})}/></label><div className="pos-button-preview"><small>ΔΕΙΓΜΑ</small><button style={{background:draft?.color||"#168ca0"}}>{draft?.label||"ΚΕΝΟ"}<span>▼</span></button></div></div>{target.kind==="quick"?<><label className="pos-button-search"><Search/><input autoFocus value={query} onChange={e=>setQuery(e.target.value)} placeholder="Barcode, κωδικός ή περιγραφή προϊόντος"/></label><div className="pos-button-product-list">{rows.map(product=><button key={product.id} onClick={()=>choose(product)} className={(draft?.productCodes||[]).some(c=>codesOf(product).includes(c))?"selected":""}><b>{product.name}</b><small>{codesOf(product).slice(0,3).join(" · ")}</small><strong>{Number(product.salePrice||0).toLocaleString("el-GR",{style:"currency",currency:"EUR"})}</strong></button>)}</div></>:<><div className="pos-button-category-tools"><button onClick={addChild}>+ Νέα υποκατηγορία</button><span>Η κάτω κατηγορία παραμένει όπως ο ΚΑΦΕΣ: κατηγορία → υποκατηγορία → προϊόντα.</span></div><div className="pos-button-children">{(draft?.children||[]).map((child,index)=><article key={child.id||index}><label>Υποκατηγορία<input value={child.label||""} onChange={e=>setDraft(current=>({...current,children:current.children.map((x,i)=>i===index?{...x,label:e.target.value,categoryName:e.target.value}:x)}))}/></label><label className="pos-button-search"><Search/><input placeholder="Αναζήτηση προϊόντος" onChange={e=>setQuery(e.target.value)}/></label><div>{rows.slice(0,30).map(product=>{const code=codesOf(product)[0],selected=(child.productCodes||[]).includes(code);return <button className={selected?"selected":""} key={product.id} onClick={()=>toggleChildProduct(index,product)}>{selected?"✓ ":""}{product.name}</button>})}</div></article>)}</div></>}</main><footer><button className="cancel" onClick={()=>setTarget(null)}>Ακύρωση</button><button className="save" disabled={busy} onClick={save}>{busy?"Αποθήκευση…":"✓ Αποθήκευση"}</button></footer></section></div>}<div className="pos-button-editor-hint"><Settings2/>Τα βελάκια στα πλήκτρα ανοίγουν τη ρύθμιση</div></>;
}
