import React,{useEffect,useMemo,useRef,useState} from "react";
import {ArrowLeft,Minus,Plus,RefreshCw,Send} from "lucide-react";
import {matchesGreekSearch} from "../../utils/greek-search.js";
import "./store-mobile-waiter.css";

const euro=value=>Number(value||0).toLocaleString("el-GR",{style:"currency",currency:"EUR"});
const allergens=["ΓΛΟΥΤΕΝΗ","ΚΑΡΚΙΝΟΕΙΔΗ","ΑΥΓΑ","ΨΑΡΙΑ","ΑΡΑΧΙΔΕΣ","ΣΟΓΙΑ","ΓΑΛΑ","ΞΗΡΟΙ ΚΑΡΠΟΙ","ΣΕΛΙΝΟ","ΜΟΥΣΤΑΡΔΑ","ΣΟΥΣΑΜΙ","ΘΕΙΩΔΗ","ΛΟΥΠΙΝΟ","ΜΑΛΑΚΙΑ"];

export default function StoreMobileWaiter({api,store,operator,onBack}){
  const [tables,setTables]=useState(null),[products,setProducts]=useState([]),[areaId,setAreaId]=useState("ALL"),[tableId,setTableId]=useState(""),[query,setQuery]=useState(""),[lines,setLines]=useState([]),[busy,setBusy]=useState(false),[adding,setAdding]=useState(false),[online,setOnline]=useState(()=>navigator.onLine),[synced,setSynced]=useState(false),[error,setError]=useState(""),[message,setMessage]=useState("");
  const sending=useRef(false),attempt=useRef({key:null,payload:null});
  const refresh=async()=>{const result=await api(`/api/store-pos/stores/${store.id}/table-service`);setTables(result);setTableId(current=>result.tables.some(table=>table.id===current)?current:"");return result};
  useEffect(()=>{let alive=true,request=0;const load=()=>{const current=++request;setSynced(false);return Promise.all([api(`/api/store-pos/stores/${store.id}/table-service`),api(`/api/store-pos/stores/${store.id}`)]).then(([result,pos])=>{if(!alive||current!==request||!navigator.onLine)return;setTables(result);setProducts(pos.products||[]);setTableId(current=>result.tables.some(table=>table.id===current)?current:"");setSynced(true);setError(current=>current.includes("Έλεγξε πρώτα το τραπέζι")?current:"")}).catch(err=>{if(alive&&current===request)setError(err.message)})};const reconnect=()=>{setOnline(true);load()};const disconnect=()=>{request++;setOnline(false);setSynced(false)};window.addEventListener("online",reconnect);window.addEventListener("offline",disconnect);if(navigator.onLine)load();return()=>{alive=false;window.removeEventListener("online",reconnect);window.removeEventListener("offline",disconnect)}},[store.id]);
  const visibleTables=(tables?.tables||[]).filter(table=>areaId==="ALL"||table.areaId===areaId);
  const order=(tables?.orders||[]).find(row=>row.tableId===tableId);
  const found=useMemo(()=>{const term=query.trim();if(!term)return[];return products.filter(product=>matchesGreekSearch(term,product.name)||String(product.sku||"").toLocaleLowerCase("el-GR").includes(term.toLocaleLowerCase("el-GR"))||(product.barcodes||[]).some(code=>String(code).includes(term))).slice(0,30)},[products,query]);
  const change=(id,patch)=>setLines(current=>current.map(line=>line.id===id?{...line,...patch}:line));
  const add=async product=>{setAdding(true);setError("");try{const options=await api(`/api/store-pos/stores/${store.id}/modifiers?productId=${encodeURIComponent(product.id)}`);const fee=Number(options.settings?.environmentalFee||0);setLines(current=>[...current,{id:crypto.randomUUID(),productId:product.id,name:product.name,price:Number(product.salePrice||0),quantity:1,note:"",allergens:[],groups:options.groups||[],selections:{},requiresPos:fee!==0}]);setQuery("")}catch(err){setError(`Δεν φορτώθηκαν οι επιλογές του προϊόντος: ${err.message}. Δεν προστέθηκε στη λίστα.`)}finally{setAdding(false)}};
  const toggleModifier=(line,group,item)=>{if(Number(item.price||0)!==0)return;const current=line.selections[group.id]||[],exists=current.some(value=>value.id===item.id),max=Math.max(1,Number(group.maxSelections||1));const next=exists?current.filter(value=>value.id!==item.id):max===1?[item]:[...current,item].slice(-max);change(line.id,{selections:{...line.selections,[group.id]:next}})};
  const invalidLine=lines.find(line=>line.requiresPos||(line.groups||[]).some(group=>(line.selections[group.id]||[]).length<Math.max(group.required?1:0,Number(group.minSelections||0))));
  const send=async()=>{if(sending.current||!tableId||!lines.length||adding||!synced)return;if(invalidLine){setError("Συμπλήρωσε τις υποχρεωτικές επιλογές χωρίς χρέωση. Για επιλογές με χρέωση ή εισφορά χρησιμοποίησε το POS.");return}if(!navigator.onLine){setError("Η αποστολή τραπεζιού απαιτεί σύνδεση. Δεν αποθηκεύτηκε offline.");return}const table=tables?.tables.find(row=>row.id===tableId);if(!window.confirm(`Αποστολή ${lines.reduce((sum,line)=>sum+line.quantity,0)} τεμαχίων στο ${table?.name};`))return;const payload={tableId,items:lines.map(line=>({productId:line.productId,quantity:line.quantity,notes:line.note.trim()||null,allergens:line.allergens,modifiers:Object.values(line.selections).flat().map(item=>({id:item.id,description:item.description,price:0}))}))};const fingerprint=JSON.stringify(payload);if(attempt.current.payload!==fingerprint)attempt.current={key:crypto.randomUUID(),payload:fingerprint};sending.current=true;setBusy(true);setError("");setMessage("");try{const result=await api(`/api/store-pos/stores/${store.id}/table-orders`,{method:"POST",body:JSON.stringify({...payload,idempotencyKey:attempt.current.key})});attempt.current={key:null,payload:null};setLines([]);setMessage(`Στάλθηκε ο γύρος ${result.roundNumber} στο ${result.tableName} · ${euro(result.addedTotal)}. Παρασκευή: ${(result.preparationBatches||[]).map(batch=>batch.productionStation).join(", ")||"χωρίς πόστο"}.`);try{await refresh()}catch(refreshError){setError(`Ο γύρος στάλθηκε, αλλά η ανανέωση απέτυχε: ${refreshError.message}. Πάτησε Ανανέωση για να τον δεις.`)}}catch(err){setError(`${err.message} Έλεγξε πρώτα το τραπέζι και την ουρά πριν επιχειρήσεις ξανά, για να μην σταλεί δεύτερος γύρος.`);try{await refresh()}catch{}}finally{sending.current=false;setBusy(false)}};
  return <div className="mobile-waiter"><header><button type="button" onClick={onBack}><ArrowLeft/> POS</button><div><small>ΑΣΥΡΜΑΤΗ ΠΑΡΑΓΓΕΛΙΟΛΗΨΙΑ</small><h1>{store.name}</h1><span>{operator?.fullName||"Χειριστής"}</span></div><button type="button" onClick={()=>refresh().catch(err=>setError(err.message))} aria-label="Ανανέωση τραπεζιών"><RefreshCw/></button></header>
    {!online&&<p role="status" className="mobile-waiter-offline">Χωρίς σύνδεση. Τα τραπέζια μπορεί να είναι παλιά. Δεν αποθηκεύεται ή αποστέλλεται γύρος offline. Με την επανασύνδεση ανανεώνονται οι λίστες, χωρίς αυτόματη αποστολή.</p>}
    {online&&!synced&&<p role="status" className="mobile-waiter-offline">Ελέγχεται η σύνδεση και ανανεώνονται τραπέζια και προϊόντα. Η αποστολή ενεργοποιείται όταν ολοκληρωθεί η ανάκτηση.</p>}
    {error&&<p role="alert" className="mobile-waiter-error">{error}</p>}{message&&<p role="status" className="mobile-waiter-message">{message}</p>}
    {!tables?<p>{online?(error?"Η φόρτωση απέτυχε. Έλεγξε τη σύνδεση και άνοιξε ξανά την παραγγελιοληψία.":"Φόρτωση τραπεζιών…"):"Τα τραπέζια θα φορτωθούν μόλις επανέλθει η σύνδεση."}</p>:<><nav aria-label="Σάλες"><button className={areaId==="ALL"?"selected":""} onClick={()=>{if(lines.length&&tableId&&!window.confirm("Αλλαγή σάλας; Τα μη σταλμένα είδη θα αφαιρεθούν."))return;setLines([]);setTableId("");setAreaId("ALL")}}>Όλες</button>{tables.areas.map(area=><button key={area.id} className={areaId===area.id?"selected":""} onClick={()=>{if(lines.length&&tableId&&!window.confirm("Αλλαγή σάλας; Τα μη σταλμένα είδη θα αφαιρεθούν."))return;setLines([]);setAreaId(area.id);setTableId("")}}>{area.name}</button>)}</nav>
    <section><h2>Τραπέζι</h2><div className="mobile-waiter-tables">{visibleTables.map(table=>{const active=(tables.orders||[]).find(row=>row.tableId===table.id);return <button key={table.id} className={tableId===table.id?"selected":""} onClick={()=>{if(lines.length&&tableId&&tableId!==table.id){if(!window.confirm("Αλλαγή τραπεζιού; Τα μη σταλμένα είδη θα αφαιρεθούν."))return;setLines([])}setTableId(table.id)}}><b>{table.name}</b><small>{active?`${active.status} · ${euro(active.total)}`:"ΕΛΕΥΘΕΡΟ"}</small></button>})}</div></section>
    {tableId&&<><section><h2>{order?`Νέος γύρος · ${order.tableName}`:"Νέα παραγγελία"}</h2>{order&&<p>Υπάρχων λογαριασμός {euro(order.total)}. Τα νέα είδη προστίθενται στον ίδιο λογαριασμό.</p>}<label>Αναζήτηση προϊόντος<input value={query} onChange={event=>setQuery(event.target.value)} placeholder="Όνομα, SKU ή barcode" autoComplete="off"/></label>{query&&<div className="mobile-waiter-results">{found.map(product=><button key={product.id} disabled={adding||busy} onClick={()=>add(product)}><span>{product.name}<small>{product.sku}</small></span><b>{euro(product.salePrice)} <Plus size={16}/></b></button>)}{!found.length&&<p>Δεν βρέθηκε προϊόν.</p>}</div>}</section>
    <section><h2>Νέα είδη</h2>{lines.map(line=><article key={line.id}><div className="mobile-waiter-line"><b>{line.name}</b><span>{euro(line.price*line.quantity)}</span></div><div className="mobile-waiter-quantity"><button aria-label={`Μείωση ${line.name}`} onClick={()=>line.quantity===1?setLines(current=>current.filter(row=>row.id!==line.id)):change(line.id,{quantity:line.quantity-1})}><Minus/></button><strong>{line.quantity}</strong><button aria-label={`Αύξηση ${line.name}`} onClick={()=>change(line.id,{quantity:Math.min(999,line.quantity+1)})}><Plus/></button></div><label>Σημείωση παρασκευής<input maxLength={250} value={line.note} onChange={event=>change(line.id,{note:event.target.value})} placeholder="Προαιρετική, χωριστή από αλλεργιογόνα"/></label>{line.requiresPos&&<p className="mobile-waiter-error">Το προϊόν έχει περιβαλλοντική εισφορά. Ολοκλήρωσε αυτή τη γραμμή στο POS.</p>}{(line.groups||[]).map(group=><fieldset key={group.id} className="mobile-waiter-modifiers"><legend>{group.description} {Math.max(group.required?1:0,Number(group.minSelections||0))>0?`· υποχρεωτικό ${Math.max(group.required?1:0,Number(group.minSelections||0))}`:""}</legend><div>{(group.items||[]).map(item=>{const selected=(line.selections[group.id]||[]).some(value=>value.id===item.id),paid=Number(item.price||0)!==0;return <button type="button" key={item.id} className={selected?"selected":""} disabled={paid} onClick={()=>toggleModifier(line,group,item)} aria-pressed={selected}>{item.description}{paid?` · ${euro(item.price)} (στο POS)`:""}</button>})}</div></fieldset>)}<details><summary>Αλλεργιογόνα ({line.allergens.length})</summary><div className="mobile-waiter-allergens">{allergens.map(allergen=><label key={allergen}><input type="checkbox" checked={line.allergens.includes(allergen)} onChange={()=>change(line.id,{allergens:line.allergens.includes(allergen)?line.allergens.filter(value=>value!==allergen):[...line.allergens,allergen]})}/>{allergen}</label>)}</div></details></article>)}{!lines.length&&<p>Επίλεξε προϊόντα για το τραπέζι.</p>}</section><footer><b>Νέα είδη: {euro(lines.reduce((sum,line)=>sum+line.price*line.quantity,0))}</b>{invalidLine&&<small role="alert">Συμπλήρωσε τις υποχρεωτικές δωρεάν επιλογές ή άνοιξε το προϊόν στο POS.</small>}<button disabled={!online||!synced||busy||adding||!lines.length||Boolean(invalidLine)} onClick={send}><Send size={18}/>{busy?"Αποστολή…":"Αποστολή γύρου"}</button><small>Η πληρωμή, η φύρα, οι επιλογές με χρέωση και η εισφορά γίνονται μόνο από το POS.</small></footer></>}</>}
  </div>;
}
