import React,{useEffect,useRef,useState} from "react";
import {createPortal} from "react-dom";
import {ClipboardList,Printer,RefreshCw,X} from "lucide-react";
const POLL_MS=7000;
const money=value=>Number(value||0).toLocaleString("el-GR",{style:"currency",currency:"EUR"});
const esc=value=>String(value??"").replace(/[&<>"']/g,char=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"})[char]);
const statusText=status=>({NEW:"ΝΕΑ",ACCEPTED:"ΑΠΟΔΟΧΗ",PREPARING:"ΕΤΟΙΜΑΖΕΤΑΙ",READY:"ΕΤΟΙΜΗ",OUT_FOR_DELIVERY:"ΣΤΟ DELIVERY",DELIVERED:"ΠΑΡΑΔΟΘΗΚΕ"})[status]||status;
const nextAction=order=>{if(order.status==="NEW")return["ACCEPTED","ΑΠΟΔΟΧΗ + ΕΚΤΥΠΩΣΗ"];if(order.status==="ACCEPTED")return["PREPARING","ΕΤΟΙΜΑΖΕΤΑΙ"];if(order.status==="PREPARING")return["READY","ΕΤΟΙΜΗ"];if(order.status==="READY")return order.fulfillmentType==="PICKUP"?["DELIVERED","ΠΑΡΑΔΟΘΗΚΕ"]:["OUT_FOR_DELIVERY","ΣΤΟ DELIVERY"];if(order.status==="OUT_FOR_DELIVERY")return["DELIVERED","ΠΑΡΑΔΟΘΗΚΕ"];return null};
function printOrder(payload){if(!payload)return;const popup=window.open("","KAT_ONLINE_PRINT","width=460,height=720");if(!popup)return window.alert("Ο browser μπλόκαρε το παράθυρο εκτύπωσης.");const lines=(payload.items||[]).map(item=>`<tr><td>${esc(item.quantity)}×</td><td>${esc(item.productName)}</td><td>${money(item.lineTotal)}</td></tr>`).join("");popup.document.write(`<!doctype html><html><head><meta charset="utf-8"><title>${esc(payload.orderNumber)}</title><style>body{font-family:Arial;padding:14px}h1{text-align:center;font-size:20px}.n{text-align:center;font-size:28px;font-weight:900}table{width:100%;border-collapse:collapse;margin-top:10px}td{padding:8px 2px;border-bottom:1px dashed #999}td:last-child{text-align:right}.t{text-align:right;font-size:21px;font-weight:900;margin-top:12px}</style></head><body><h1>ΚΥΛΙΚΕΙΟ ΚΑΤ · ΗΛΕΚΤΡΟΝΙΚΕΣ ΠΑΡΑΓΓΕΛΙΕΣ</h1><div class="n">#${esc(payload.orderNumber)}</div><div>${esc(payload.customerName)} · ${esc(payload.customerPhone)}</div><div>${esc(payload.location||"")}</div><table>${lines}</table><div class="t">ΣΥΝΟΛΟ ${money(payload.total)}</div><script>setTimeout(()=>window.print(),200)<\/script></body></html>`);popup.document.close()}
export default function StoreOnlineOrders({api,store}){
 const enabled=/ΚΥΛΙΚΕΙΟ\s*ΚΑΤ/i.test(String(store?.name||""))||/^\/store\/kat-store\/?$/i.test(window.location.pathname);
 const [rows,setRows]=useState([]),[open,setOpen]=useState(false),[error,setError]=useState(""),[busyId,setBusyId]=useState(""),[host,setHost]=useState(null);const mounted=useRef(true);
 useEffect(()=>()=>{mounted.current=false},[]);
 useEffect(()=>{if(!enabled)return;let tries=0;const findHost=()=>{const node=document.querySelector(".runtime-top-actions");if(node){setHost(node);return true}return false};if(findHost())return;const timer=window.setInterval(()=>{tries+=1;if(findHost()||tries>=24)window.clearInterval(timer)},250);return()=>window.clearInterval(timer)},[enabled,store?.id]);
 const load=async()=>{if(!enabled||!store?.id)return;try{const result=await api(`/api/public/kat/pos/stores/${encodeURIComponent(store.id)}/orders`,{cache:"no-store"});if(!mounted.current)return;setRows(result.rows||[]);setError("")}catch(err){if(!mounted.current)return;setError(err.message||"Αποτυχία φόρτωσης online παραγγελιών.")}};
 useEffect(()=>{if(!enabled)return;load();const timer=window.setInterval(load,POLL_MS);return()=>window.clearInterval(timer)},[enabled,store?.id]);
 const changeStatus=async(order,status)=>{if(busyId)return;setBusyId(order.id);setError("");try{const result=await api(`/api/public/kat/pos/stores/${encodeURIComponent(store.id)}/orders/${encodeURIComponent(order.id)}/status`,{method:"POST",body:JSON.stringify({status})});if(status==="ACCEPTED"&&result.print)printOrder(result.print);await load()}catch(err){setError(err.message||"Η αλλαγή κατάστασης απέτυχε.")}finally{setBusyId("")}};
 const reprint=async order=>{if(busyId)return;setBusyId(order.id);setError("");try{const result=await api(`/api/public/kat/pos/stores/${encodeURIComponent(store.id)}/orders/${encodeURIComponent(order.id)}/print`,{cache:"no-store"});printOrder(result.print)}catch(err){setError(err.message||"Η εκτύπωση απέτυχε.")}finally{setBusyId("")}};
 if(!enabled)return null;
 const launcher=<button type="button" onClick={()=>{setOpen(true);load()}} style={host?{order:-1,display:"inline-flex",alignItems:"center",gap:7,padding:"9px 11px",borderRadius:9,background:rows.length?"#9b1c1c":"transparent",border:rows.length?"1px solid #ffb3b3":"1px solid rgba(255,255,255,.28)",color:"inherit",fontWeight:900,cursor:"pointer"}:{position:"fixed",top:108,right:310,zIndex:99990,display:"inline-flex",alignItems:"center",gap:7,padding:"9px 11px",borderRadius:9,background:rows.length?"#9b1c1c":"#174f42",border:"1px solid rgba(255,255,255,.35)",color:"#fff",fontWeight:900,boxShadow:"0 4px 14px rgba(0,0,0,.18)",cursor:"pointer"}}><ClipboardList size={18}/>ΠΑΡΑΓΓΕΛΙΕΣ<b style={{minWidth:22,height:22,padding:"0 6px",display:"inline-grid",placeItems:"center",borderRadius:999,background:rows.length?"#ef4444":"#55766e",color:"#fff",fontSize:12}}>{rows.length}</b></button>;
 const modal=open&&createPortal(<div style={{position:"fixed",inset:0,zIndex:100000,background:"rgba(4,18,14,.88)",padding:24,overflow:"auto"}} onMouseDown={event=>{if(event.target===event.currentTarget)setOpen(false)}}><section style={{maxWidth:1050,margin:"0 auto",background:"#f7faf9",borderRadius:16,overflow:"hidden",boxShadow:"0 24px 70px rgba(0,0,0,.35)"}}><header style={{display:"flex",alignItems:"center",justifyContent:"space-between",gap:12,padding:"16px 20px",background:"#7c171b",color:"#fff"}}><div><small>MYWORKSTATION · ΗΛΕΚΤΡΟΝΙΚΕΣ ΠΑΡΑΓΓΕΛΙΕΣ</small><h2 style={{margin:"3px 0 0"}}>Ηλεκτρονικές παραγγελίες · {rows.length}</h2></div><div style={{display:"flex",gap:8}}><button type="button" onClick={load}><RefreshCw size={17}/>Ανανέωση</button><button type="button" onClick={()=>setOpen(false)}><X/></button></div></header><div style={{padding:16,display:"grid",gap:12}}>{error&&<div style={{padding:11,borderRadius:9,background:"#fff0f0",color:"#9b2222",fontWeight:800}}>{error}</div>}{rows.length===0?<div style={{padding:38,textAlign:"center",color:"#60736c"}}>Δεν υπάρχουν ενεργές ηλεκτρονικές παραγγελίες.</div>:rows.map(order=>{const next=nextAction(order);return <article key={order.id} style={{background:"#fff",border:"1px solid #dce7e3",borderRadius:13,padding:14}}><div style={{display:"flex",justifyContent:"space-between"}}><div><div style={{fontSize:22,fontWeight:900,color:"#7c171b"}}>#{order.orderNumber}</div><small>{statusText(order.status)}</small></div><b>{money(order.total)}</b></div><div style={{display:"grid",gridTemplateColumns:"repeat(4,minmax(0,1fr))",gap:8,margin:"12px 0"}}><div><small>Πελάτης</small><b style={{display:"block"}}>{order.customerName}</b></div><div><small>Τηλέφωνο</small><b style={{display:"block"}}>{order.customerPhone}</b></div><div><small>Παράδοση</small><b style={{display:"block"}}>{order.fulfillmentType==="DELIVERY"?"Delivery":"Παραλαβή"}</b></div><div><small>Πληρωμή</small><b style={{display:"block"}}>{order.paymentMethod==="CASH"?"Μετρητά":"Κάρτα"}</b></div></div>{(order.items||[]).map((item,index)=><div key={index} style={{display:"grid",gridTemplateColumns:"55px 1fr 100px",gap:10,padding:"8px 0",borderBottom:"1px dashed #d6dfdc"}}><b>{item.quantity}×</b><span>{item.productName}</span><b>{money(item.lineTotal)}</b></div>)}<div style={{display:"flex",gap:8,marginTop:12}}>{next&&<button disabled={busyId===order.id} onClick={()=>changeStatus(order,next[0])}>{next[1]}</button>}<button disabled={busyId===order.id} onClick={()=>reprint(order)}><Printer size={17}/>ΕΠΑΝΕΚΤΥΠΩΣΗ</button></div></article>})}</div></section></div>,document.body);
 return <>{createPortal(launcher,host||document.body)}{modal}</>;
}