import React,{useEffect,useState} from "react";
import {Landmark,Upload} from "lucide-react";
const num=v=>Number(String(v||"0").replace(",","."))||0;
const read=file=>new Promise((ok,bad)=>{const r=new FileReader();r.onload=()=>ok(r.result);r.onerror=bad;r.readAsDataURL(file)});
export default function StoreBankDeposit({api,store,onChanged,setMessage,allowCash}){
 const [pending,setPending]=useState([]),[amount,setAmount]=useState(""),[depositor,setDepositor]=useState(""),[file,setFile]=useState(null),[busy,setBusy]=useState(false);
 useEffect(()=>{api(`/api/transactions/stores/${store.id}/bank-deposits/pending-proof`).then(r=>setPending(r.items||[])).catch(()=>{})},[api,store.id]);
 const uploadProof=async(entry,file)=>{if(!file)return;setBusy(true);try{await api(`/api/transactions/bank-ledger/${entry.id}/attachment`,{method:"POST",body:JSON.stringify({attachment:{dataUrl:await read(file),filename:file.name}})});setPending(rows=>rows.filter(row=>row.id!==entry.id));setMessage?.("✅ Η απόδειξη ανέβηκε και η κατάθεση πήγε για έλεγχο Super Admin.");}catch(e){setMessage?.(`❌ ${e.message}`)}finally{setBusy(false)}};
 const submit=async()=>{if(!allowCash)return setMessage?.("❌ Απαιτείται ενεργή βάρδια για κατάθεση μετρητών.");if(num(amount)<=0||!depositor.trim())return setMessage?.("❌ Συμπλήρωσε ποσό και καταθέτη.");setBusy(true);try{const attachment=file?{dataUrl:await read(file),filename:file.name}:null;const r=await api(`/api/transactions/stores/${store.id}/bank-deposits`,{method:"POST",body:JSON.stringify({amount:num(amount),depositor,depositedAt:new Date().toISOString(),attachment,idempotencyKey:`bank-${Date.now()}-${Math.random().toString(36).slice(2)}`})});setMessage?.(`✅ Η κατάθεση καταχωρίστηκε ${r.status==="PENDING_PROOF"?"σε αναμονή αποδεικτικού":"για έλεγχο"}.`);setAmount("");setDepositor("");setFile(null);onChanged?.()}catch(e){setMessage?.(`❌ ${e.message}`)}finally{setBusy(false)}};
 return <div className="pos-payment-form"><div style={{padding:"10px",borderRadius:8,background:"#e9f8f1",fontWeight:800}}>Κατάθεση Τράπεζας — αφαιρείται μία φορά από την ενεργή βάρδια και δεν είναι έξοδο.</div><div style={{padding:"8px 10px",borderRadius:8,background:"#f2f8f5",fontWeight:700}}>Ενιαίο εικονικό Ταμείο Τράπεζας — χωρίς σύνδεση ή επιλογή πραγματικού λογαριασμού.</div><label>Ποσό<input inputMode="decimal" value={amount} onChange={e=>setAmount(e.target.value)} placeholder="0,00" disabled={busy}/></label><label>Καταθέτης<input value={depositor} onChange={e=>setDepositor(e.target.value)} disabled={busy}/></label><label><Upload/> Απόδειξη κατάθεσης (προαιρετικά τώρα)<input type="file" accept="image/jpeg,image/png,image/webp,application/pdf" onChange={e=>setFile(e.target.files?.[0]||null)} disabled={busy}/></label><button className="pos-primary-action" disabled={busy||!allowCash} onClick={submit}><Landmark/>{busy?"Καταχώριση…":"Καταχώριση κατάθεσης"}</button>{pending.length>0&&<div style={{marginTop:12,borderTop:"1px solid #dbe7e1",paddingTop:10}}><b>Καταθέσεις χωρίς απόδειξη</b>{pending.map(row=><label key={row.id}>{row.bankName} · {row.amount} € · {new Date(row.occurredAt).toLocaleDateString("el-GR")}<input type="file" accept="image/jpeg,image/png,image/webp,application/pdf" disabled={busy} onChange={e=>uploadProof(row,e.target.files?.[0])}/></label>)}</div>}</div>;
}