import React,{useEffect,useMemo,useState} from "react";
import {Package,Printer,X} from "lucide-react";
import "./store-preparation-modal.css";

const euro=v=>Number(v||0).toLocaleString("el-GR",{style:"currency",currency:"EUR"});
const upper=v=>String(v||"").toLocaleUpperCase("el-GR");
const esc=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
const groupKind=name=>{const n=upper(name);if(n.includes("ΖΑΧ")||n.includes("SUGAR"))return"SUGAR";if(n.includes("ΠΑΓ")||n.includes("ICE"))return"ICE";if(n.includes("ΧΤΥΠ")||n.includes("SHAKE"))return"SHAKE";if(n.includes("ΣΙΡ")||n.includes("SYRUP"))return"SYRUP";if(n.includes("ΓΑΛ")||n.includes("MILK"))return"MILK";if(n.includes("EXTRA")||n.includes("ΕΞΤΡΑ")||n.includes("SHOT")||n.includes("DECAF")||n.includes("ΚΑΝΕΛ")||n.includes("ΣΑΝΤ"))return"EXTRA";return"OTHER"};
const order={SUGAR:1,ICE:2,SHAKE:3,SYRUP:4,MILK:5,EXTRA:6,OTHER:7};
const priorityLabel=p=>p==="DOCTOR"?"ΙΑΤΡΟΣ":p==="NURSE"?"ΝΟΣΗΛΕΥΤΗΣ / ΝΟΣΟΚΟΜΟΣ":p==="STAFF"?"ΠΡΟΣΩΠΙΚΟ":"ΚΑΝΟΝΙΚΟΣ ΠΕΛΑΤΗΣ";

export default function StorePreparationModal({api,store,cart,onClose,setMessage,setError,onApply}){
 const [groups,setGroups]=useState([]),[settings,setSettings]=useState(null),[selectedProduct,setSelectedProduct]=useState(cart[0]?.id||""),[selected,setSelected]=useState({}),[spoons,setSpoons]=useState(0),[iceQty,setIceQty]=useState(0),[note,setNote]=useState(""),[priority,setPriority]=useState("NORMAL"),[busy,setBusy]=useState(false);
 const line=cart.find(x=>x.id===selectedProduct)||cart[0];
 useEffect(()=>{if(!line?.id)return;setGroups([]);setSettings(null);api(`/api/store-pos/stores/${store.id}/modifiers?productId=${encodeURIComponent(line.id)}`).then(r=>{setGroups(r.groups||[]);setSettings(r.settings||null)}).catch(e=>setError(e.message))},[store.id,line?.id]);
 const normalized=useMemo(()=>groups.map(g=>({...g,kind:groupKind(g.description)})).sort((a,b)=>(order[a.kind]||99)-(order[b.kind]||99)||String(a.description).localeCompare(String(b.description),"el")),[groups]);
 const chosen=useMemo(()=>Object.values(selected).flat(),[selected]);
 const extras=chosen.reduce((s,m)=>s+Number(m.price||0),0),fee=Number(settings?.environmentalFee||0),base=Number(line?.baseSalePrice??line?.salePrice??0),finalPrice=base+extras+fee;
 const toggle=(group,item)=>setSelected(current=>{const rows=current[group.id]||[],exists=rows.some(x=>x.id===item.id);if(exists)return{...current,[group.id]:rows.filter(x=>x.id!==item.id)};const max=Math.max(1,Number(group.maxSelections||1));return{...current,[group.id]:max>1?[...rows,item].slice(-max):[item]}});
 const addSynthetic=(description,value)=>({id:`synthetic-${description}-${value}`,description:`${description} ${value}`,price:0});
 const printTicket=(popup,payload,result)=>{if(!popup)return;const mods=payload.modifiers||[],priorityText=priorityLabel(payload.priority),priorityHtml=payload.priority!=="NORMAL"?`<div class="priority">${esc(priorityText)}</div>`:"";popup.document.open();popup.document.write(`<!doctype html><html><head><meta charset="utf-8"><title>Παραγωγή - ${esc(payload.productName)}</title><style>@page{margin:5mm}body{font-family:Arial,sans-serif;margin:0;padding:8px;color:#111}.ticket{width:76mm}.brand{font-size:12px;font-weight:800}.station{font-size:15px;font-weight:900;margin-top:4px}.priority{font-size:28px;font-weight:1000;text-align:center;border:4px solid #000;padding:9px;margin:10px 0}.product{font-size:23px;font-weight:1000;border-top:2px solid #000;border-bottom:2px solid #000;padding:8px 0;margin:8px 0}.qty{font-size:18px;font-weight:900}.mods{margin:8px 0}.mod{font-size:17px;font-weight:900;padding:4px 0;border-bottom:1px dashed #999}.note{font-size:18px;font-weight:1000;border:2px solid #000;padding:7px;margin-top:9px}.meta{font-size:11px;margin-top:10px}.price{font-size:15px;font-weight:900;margin-top:8px}</style></head><body><div class="ticket"><div class="brand">MYWORKSTATION · ΠΑΡΑΓΩΓΗ</div><div class="station">${esc(payload.productionStation||"ΠΑΡΑΓΩΓΗ")}</div>${priorityHtml}<div class="product">${esc(payload.productName)}</div><div class="qty">ΠΟΣΟΤΗΤΑ: ${Number(line?.quantity||1)}</div><div class="mods">${mods.length?mods.map(m=>`<div class="mod">${esc(m.description)}${Number(m.price||0)?` · ${esc(euro(m.price))}`:""}</div>`).join(""):"<div class=\"mod\">ΧΩΡΙΣ EXTRA MODIFIERS</div>"}</div>${payload.note?`<div class="note">ΣΗΜΕΙΩΣΗ: ${esc(payload.note)}</div>`:""}<div class="price">ΤΕΛΙΚΗ ΤΙΜΗ: ${esc(euro(payload.unitPrice))}</div><div class="meta">${esc(store.name)} · ${new Date().toLocaleString("el-GR")} · ID ${esc(result?.id||"")}</div></div><script>setTimeout(()=>{window.print();},180)<\/script></body></html>`);popup.document.close()};
 const apply=async()=>{if(!line)return;setBusy(true);let popup=null;try{const modifiers=[...chosen];if(spoons>0)modifiers.push(addSynthetic("ΚΟΥΤΑΛΙΑ",spoons));if(iceQty>0)modifiers.push(addSynthetic("ΠΑΓΟΣ ΠΟΣΟΤΗΤΑ",iceQty));const payload={productId:line.id,productName:line.name,modifiers,modifierTotal:extras,environmentalFee:fee,unitPrice:finalPrice,note:note||null,priority,productionStation:settings?.productionStation||"ΠΑΡΑΓΩΓΗ",autoPrint:settings?.autoPrint!==false};if(payload.autoPrint)popup=window.open("","MWS_PREPARATION_TICKET","width=480,height=720");const result=await api(`/api/store-pos/stores/${store.id}/preparation`,{method:"POST",body:JSON.stringify({items:[{productId:line.id,quantity:line.quantity,modifiers:modifiers.map(m=>({id:m.id,description:m.description,price:Number(m.price||0)}))}],note:note||null,priority,environmentalFee:fee,unitPrice:finalPrice,productionStation:payload.productionStation})});if(line.baseSalePrice==null)line.baseSalePrice=base;line.salePrice=finalPrice;line.manualPrice=true;line.priceReason=`PREPARATION:${result.id||""}`;line.preparationId=result.id||null;line.preparation=payload;line.displayName=modifiers.length?`${line.name} · ${modifiers.map(m=>m.description).join(" · ")}`:line.name;onApply?.(payload);if(payload.autoPrint)printTicket(popup,payload,result);setMessage(`Η παρασκευή του «${line.name}» καταχωρίστηκε · νέα τιμή ${euro(finalPrice)}${priority!=="NORMAL"?` · ΠΡΟΤΕΡΑΙΟΤΗΤΑ ${priorityLabel(priority)}`:""}.`);onClose()}catch(e){try{popup?.close()}catch{}setError(e.message)}finally{setBusy(false)}};
 const renderGroup=g=><div className={`prep-group prep-${g.kind.toLowerCase()}`} key={g.id}><h3>{g.description}</h3><div className="prep-options">{(g.items||[]).map(item=>{const active=(selected[g.id]||[]).some(x=>x.id===item.id);return <button type="button" className={active?"active":""} key={item.id} onClick={()=>toggle(g,item)}><span>{item.description}</span>{Number(item.price||0)!==0&&<small>{Number(item.price)>0?"+":""}{euro(item.price)}</small>}</button>})}</div>{g.kind==="SUGAR"&&<div className="prep-step"><b>ΚΟΥΤΑΛΙΑ</b>{[0,1,2,3,4].map(n=><button key={n} className={spoons===n?"active":""} onClick={()=>setSpoons(n)}>{n}</button>)}</div>}{g.kind==="ICE"&&<div className="prep-step"><b>ΠΟΣΟΤΗΤΑ</b>{[0,1,2,3].map(n=><button key={n} className={iceQty===n?"active":""} onClick={()=>setIceQty(n)}>{n}</button>)}</div>}</div>;
 return <div className="prep-overlay" onMouseDown={e=>e.target===e.currentTarget&&!busy&&onClose()}><section className="prep-modal"><header><div><small>MYWORKSTATION · ΠΑΡΑΣΚΕΥΗ</small><h2>{line?.name||"Παρασκευή"}</h2></div><button onClick={()=>!busy&&onClose()}><X/></button></header><main><aside className="prep-products"><h3>ΠΡΟΪΟΝΤΑ</h3>{cart.map(i=><button key={i.id} className={i.id===line?.id?"active":""} onClick={()=>{setSelectedProduct(i.id);setSelected({});setSpoons(0);setIceQty(0)}}><b>{i.quantity} × {i.name}</b><span>{euro(i.baseSalePrice??i.salePrice)}</span></button>)}<div className="prep-price"><span>Βασική τιμή</span><b>{euro(base)}</b><span>Modifiers</span><b>{euro(extras)}</b>{fee>0&&<><span>Εισφορά περιβάλλοντος</span><b>{euro(fee)}</b></>}<strong>ΣΥΝΟΛΟ {euro(finalPrice)}</strong></div></aside><div className="prep-body"><div className="prep-groups">{normalized.length?normalized.map(renderGroup):<div className="prep-empty">Δεν έχουν οριστεί ακόμη ομάδες Modifiers για αυτό το προϊόν στο BackOffice.</div>}</div><div className="prep-note"><label>ΣΗΜΕΙΩΣΗ / ΕΙΔΙΚΕΣ ΟΔΗΓΙΕΣ<textarea value={note} onChange={e=>setNote(e.target.value)} placeholder="π.χ. πολύ ζεστό, χωρίς καλαμάκι..."/></label></div></div><aside className="prep-summary"><h3>ΕΠΙΛΕΓΜΕΝΑ</h3>{chosen.map(m=><div key={m.id}><span>{m.description}</span><b>{Number(m.price||0)?euro(m.price):""}</b></div>)}{spoons>0&&<div><span>Κουτάλια</span><b>{spoons}</b></div>}{iceQty>0&&<div><span>Πάγος ποσότητα</span><b>{iceQty}</b></div>}<div className="prep-pack"><Package/><span>{fee>0?`Συσκευασία / εισφορά ${euro(fee)} από συνταγή BackOffice`:"Συσκευασία από συνταγή BackOffice"}</span></div></aside></main><footer><div className="prep-priority"><b>ΠΡΟΤΕΡΑΙΟΤΗΤΑ ΠΑΡΑΓΩΓΗΣ</b><button className={priority==="DOCTOR"?"doctor active":"doctor"} onClick={()=>setPriority("DOCTOR")}>ΙΑΤΡΟΣ</button><button className={priority==="NURSE"?"nurse active":"nurse"} onClick={()=>setPriority("NURSE")}>ΝΟΣΗΛΕΥΤΗΣ / ΝΟΣΟΚΟΜΟΣ</button><button className={priority==="STAFF"?"staff active":"staff"} onClick={()=>setPriority("STAFF")}>ΠΡΟΣΩΠΙΚΟ</button><button className={priority==="NORMAL"?"active":""} onClick={()=>setPriority("NORMAL")}>ΚΑΝΟΝΙΚΟΣ ΠΕΛΑΤΗΣ</button></div><button className="prep-submit" disabled={busy||!line} onClick={apply}><Printer/> {busy?"Καταχώριση…":"ΕΦΑΡΜΟΓΗ & ΠΑΡΑΣΚΕΥΗ"}</button></footer></section></div>
}
