import React,{useEffect,useMemo,useState} from "react";
import {CreditCard,PauseCircle,Printer,Search,Trash2,UserRound,X} from "lucide-react";
import "./store-pos-standard-modals.css";
import StorePosPaymentsModal from "./StorePosPaymentsModal.jsx";
import StorePreparationModal from "./StorePreparationModal.jsx";
const euro=v=>Number(v||0).toLocaleString("el-GR",{style:"currency",currency:"EUR"});
const num=v=>Number(String(v||"0").replace(",","."))||0;
const when=v=>v?new Date(v).toLocaleString("el-GR",{day:"2-digit",month:"2-digit",hour:"2-digit",minute:"2-digit"}):"—";
function Pad({value,onChange,decimal=true}){const p=k=>{const c=String(value??"");if(k==="⌫")return onChange(c.slice(0,-1));if(k==="C")return onChange("");if(k===","){if(!decimal||c.includes(",")||c.includes("."))return;return onChange(`${c||"0"},`)}onChange(`${c}${k}`.replace(/^0+(?=\d)/,""))};return <div className="pos-inline-keypad">{[7,8,9,4,5,6,1,2,3,0,decimal?",":"C","⌫"].map(k=><button key={k} onClick={()=>p(String(k))}>{k}</button>)}<button className="wide" onClick={()=>p("C")}>ΚΑΘΑΡΙΣΜΟΣ</button></div>}
export default function StorePosStandardModals(props){const {active,onClose,api,store,cart,total,customer,onCustomer,onRestore,onCartCleared,onChanged,onCheckout,setMessage,setError,onHoldCount,onPreparationApply}=props;if(!active)return null;if(active==="PAYMENTS")return <StorePosPaymentsModal api={api} store={store} onClose={onClose} onChanged={onChanged} setMessage={setMessage} setError={setError}/>;if(active==="PREP")return <StorePreparationModal api={api} store={store} cart={cart} onClose={onClose} setMessage={setMessage} setError={setError} onApply={onPreparationApply}/>;
 const [query,setQuery]=useState(""),[rows,setRows]=useState([]),[busy,setBusy]=useState(false),[holds,setHolds]=useState([]),[mixedCash,setMixedCash]=useState("0"),[note,setNote]=useState(""),[mods,setMods]=useState([]),[selected,setSelected]=useState(cart[0]?.id||""),[wasteQty,setWasteQty]=useState({}),[sales,setSales]=useState([]),[sale,setSale]=useState(null),[returnMode,setReturnMode]=useState("TRANSACTION"),[returnReason,setReturnReason]=useState("Επιστροφή από πελάτη"),[returnLines,setReturnLines]=useState({});
 useEffect(()=>{if(active==="HOLDS")loadHolds();if(active==="WASTE")setWasteQty(Object.fromEntries(cart.map(i=>[i.id,String(i.quantity||1)])));if(active==="RETURN")loadSales()},[active]);
 const loadHolds=async()=>{try{const r=await api(`/api/store-pos/stores/${store.id}/holds`);setHolds(r.rows||[]);onHoldCount?.((r.rows||[]).length)}catch(e){setError(e.message)}};
 const search=async()=>{if(query.trim().length<2)return;setBusy(true);try{const r=await api(`/api/store-pos/stores/${store.id}/customers?q=${encodeURIComponent(query.trim())}`);setRows(r.items||[])}catch(e){setError(e.message)}finally{setBusy(false)}};
 const hold=async()=>{if(!cart.length)return;setBusy(true);try{await api(`/api/store-pos/stores/${store.id}/holds`,{method:"POST",body:JSON.stringify({customerId:customer?.id||null,items:cart.map(i=>({productId:i.id,quantity:i.quantity}))})});onCartCleared();setMessage("Η συναλλαγή μπήκε σε Αναμονή.");await loadHolds()}catch(e){setError(e.message)}finally{setBusy(false)}};
 const restore=async id=>{setBusy(true);try{const r=await api(`/api/store-pos/stores/${store.id}/holds/${id}/restore`,{method:"POST"});onRestore(r);await loadHolds();onClose()}catch(e){setError(e.message)}finally{setBusy(false)}};
 const mixedCard=Math.max(0,Number((total-num(mixedCash)).toFixed(2)));const doMixed=()=>{const cash=num(mixedCash);if(cash<0||cash>total)return setError("Το ποσό μετρητών δεν είναι έγκυρο.");onCheckout("MIXED",[{method:"CASH",amount:cash},{method:"CARD",amount:mixedCard}]);onClose()};
 const wasteItems=cart.map(i=>({...i,wasteQuantity:Math.max(0,num(wasteQty[i.id]))})).filter(i=>i.wasteQuantity>0);const waste=async()=>{if(!wasteItems.length)return setError("Βάλε ποσότητα φύρας.");setBusy(true);try{const r=await api(`/api/store-pos/stores/${store.id}/waste`,{method:"POST",body:JSON.stringify({items:wasteItems.map(i=>({productId:i.id,quantity:i.wasteQuantity})),note:note||null})});onCartCleared();setMessage(`Η Φύρα ${euro(r.total)} καταχωρίστηκε.`);onChanged?.();onClose()}catch(e){setError(e.message)}finally{setBusy(false)}};
 const chooseSale=s=>{setSale(s);setReturnLines({})};
 const loadSales=async()=>{setBusy(true);try{const r=await api(`/api/store-pos/stores/${store.id}/sales/recent`);const a=(r.rows||[]).filter(s=>!s.reversalState&&s.source!=="POS_REVERSAL");setSales(a);chooseSale(a[0]||null)}catch(e){setError(e.message)}finally{setBusy(false)}};
 const submitReturn=async()=>{if(!sale)return setError("Επίλεξε συναλλαγή.");setBusy(true);try{if(returnMode==="TRANSACTION")await api(`/api/store-pos/stores/${store.id}/sales/${sale.id}/reverse`,{method:"POST",body:JSON.stringify({kind:"RETURN",reason:returnReason})});else{const items=Object.entries(returnLines).map(([lineId,q])=>({lineId,quantity:num(q)})).filter(i=>i.quantity>0);if(!items.length){setBusy(false);return setError("Επίλεξε προϊόν.")}await api(`/api/store-pos/stores/${store.id}/sales/${sale.id}/return-items`,{method:"POST",body:JSON.stringify({items,reason:returnReason})})}setMessage(returnMode==="TRANSACTION"?`Η επιστροφή ${euro(sale.total)} καταχωρίστηκε.`:"Η επιστροφή προϊόντων καταχωρίστηκε.");onChanged?.();onClose()}catch(e){setError(e.message)}finally{setBusy(false)}};
 const title={CUSTOMER:"Πελάτης",HOLDS:"Αναμονή συναλλαγής",WASTE:"Φύρα / Κατανάλωση προσωπικού",MIXED:"Μικτή πληρωμή",RETURN:"Επιστροφή"}[active]||"POS";
 return <div className="pos-standard-modal" onMouseDown={e=>e.target===e.currentTarget&&!busy&&onClose()}><section><header><div><small>MYWORKSTATION STANDARD POS</small><h2>{title}</h2></div><button onClick={()=>!busy&&onClose()}><X/></button></header><main>
 {active==="CUSTOMER"&&<><div className="pos-modal-search"><input autoFocus value={query} onChange={e=>setQuery(e.target.value)} onKeyDown={e=>e.key==="Enter"&&search()} placeholder="Όνομα, ΑΦΜ, τηλέφωνο ή κάρτα"/><button onClick={search}><Search/> Αναζήτηση</button></div><button className="pos-retail-customer" onClick={()=>{onCustomer(null);onClose()}}><UserRound/> Πελάτης λιανικής</button><div className="pos-customer-results">{rows.map(r=><button key={r.id} onClick={()=>{onCustomer(r);onClose()}}><b>{r.name}</b><span>Υπόλοιπο {euro(r.balance)}</span></button>)}</div></>}
 {active==="HOLDS"&&<><button className="pos-primary-action" disabled={!cart.length||busy} onClick={hold}><PauseCircle/> Βάλε την τρέχουσα συναλλαγή σε Αναμονή</button><div className="pos-hold-list">{holds.map((h,i)=><article key={h.id}><div><b>Αναμονή {i+1} · {euro(h.total)}</b></div><button onClick={()=>restore(h.id)}>Επαναφορά</button></article>)}</div></>}
 {active==="MIXED"&&<div className="pos-mixed-payment"><strong>{euro(total)}</strong><label>Μετρητά<input readOnly value={mixedCash}/></label><div><span>Κάρτα</span><b>{euro(mixedCard)}</b></div><Pad value={mixedCash} onChange={setMixedCash}/><button className="pos-primary-action" onClick={doMixed}><CreditCard/> Αποστολή υπολοίπου στην κάρτα</button></div>}
 {active==="WASTE"&&<><div className="pos-waste-summary">{cart.map(i=><label key={i.id}><b>{i.name}</b><input value={wasteQty[i.id]||""} onChange={e=>setWasteQty(c=>({...c,[i.id]:e.target.value}))}/></label>)}</div><label>Αιτία<input value={note} onChange={e=>setNote(e.target.value)}/></label><button className="pos-danger-action" onClick={waste}><Trash2/> Καταχώριση Φύρας</button></>}
 {active==="RETURN"&&<div className="pos-return-flow"><div className="pos-return-sales"><h3>Πρόσφατες πωλήσεις</h3>{sales.map(s=><button key={s.id} className={sale?.id===s.id?"active":""} onClick={()=>chooseSale(s)}><b>{euro(s.total)}</b><span>{s.productSummary||`${(s.lines||[]).length} προϊόντα`}</span><small>{when(s.occurredAt||s.createdAt)} · {s.paymentSummary||"Πληρωμή"}</small></button>)}</div><div className="pos-return-details">{sale&&<><div className="pos-negative-total"><span>Επιλεγμένη συναλλαγή · {when(sale.occurredAt||sale.createdAt)}</span><b>{euro(sale.total)}</b></div><div className="pos-return-modes"><button className={returnMode==="TRANSACTION"?"active":""} onClick={()=>setReturnMode("TRANSACTION")}>Ολόκληρη συναλλαγή</button><button className={returnMode==="ITEMS"?"active":""} onClick={()=>setReturnMode("ITEMS")}>Συγκεκριμένα προϊόντα</button></div><div className="pos-return-lines">{(sale.lines||[]).map(line=>returnMode==="TRANSACTION"?<label key={line.id}><input type="checkbox" checked readOnly/><span><b>{line.description}</b><small>{num(line.quantity)} × {euro(line.unitPrice)} · {euro(line.lineTotal)}</small></span></label>:<label key={line.id}><input type="checkbox" checked={num(returnLines[line.id])>0} onChange={e=>setReturnLines(current=>({...current,[line.id]:e.target.checked?String(Math.abs(num(line.quantity))):"0"}))}/><span><b>{line.description}</b><small>Αγορά: {num(line.quantity)} × {euro(line.unitPrice)} · {euro(line.lineTotal)}</small></span><input type="number" min="0" max={Math.abs(num(line.quantity))} step="1" value={returnLines[line.id]||"0"} onChange={e=>setReturnLines(current=>({...current,[line.id]:e.target.value}))}/></label>)}</div><div className="pos-module-note">{sale.paymentSummary||((sale.payments||[]).map(p=>`${p.method} ${euro(p.amount)}`).join(" + ")||"Χωρίς ανάλυση πληρωμής")}</div><label>Αιτιολογία<select value={returnReason} onChange={e=>setReturnReason(e.target.value)}><option>Επιστροφή από πελάτη</option><option>Λάθος από χειριστή</option><option>Δοκιμή</option></select></label><button className="pos-danger-action" disabled={busy||(returnMode==="ITEMS"&&!Object.values(returnLines).some(q=>num(q)>0))} onClick={submitReturn}>{returnMode==="TRANSACTION"?`Επιστροφή ολόκληρης συναλλαγής ${euro(sale.total)}`:"Καταχώριση επιστροφής προϊόντων"}</button></>}</div></div>}
 </main></section></div>
}
