import React,{useEffect,useMemo,useState} from "react";
import {Package,Printer,Send,X} from "lucide-react";
import "./store-preparation-modal.css";

const euro=v=>Number(v||0).toLocaleString("el-GR",{style:"currency",currency:"EUR"});
const upper=v=>String(v||"").toLocaleUpperCase("el-GR");
const esc=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
const groupKind=name=>{const n=upper(name);if(n.includes("ΖΑΧ")||n.includes("SUGAR"))return"SUGAR";if(n.includes("ΠΑΓ")||n.includes("ICE"))return"ICE";if(n.includes("ΧΤΥΠ")||n.includes("SHAKE"))return"SHAKE";if(n.includes("ΣΙΡ")||n.includes("SYRUP"))return"SYRUP";if(n.includes("ΓΑΛ")||n.includes("MILK"))return"MILK";if(n.includes("EXTRA")||n.includes("ΕΞΤΡΑ")||n.includes("SHOT")||n.includes("DECAF")||n.includes("ΚΑΝΕΛ")||n.includes("ΣΑΝΤ"))return"EXTRA";return"OTHER"};
const order={SUGAR:1,ICE:2,SHAKE:3,SYRUP:4,MILK:5,EXTRA:6,OTHER:7};
const priorityLabel=p=>p==="DOCTOR"?"ΙΑΤΡΟΣ":p==="NURSE"?"ΝΟΣΗΛΕΥΤΗΣ / ΝΟΣΟΚΟΜΟΣ":p==="STAFF"?"ΠΡΟΣΩΠΙΚΟ":"ΚΑΝΟΝΙΚΟΣ ΠΕΛΑΤΗΣ";

export default function StorePreparationModal({api,store,cart,onClose,setMessage,setError,onApply}){
 const [groups,setGroups]=useState([]),[settings,setSettings]=useState(null),[selectedProduct,setSelectedProduct]=useState(cart[0]?.id||""),[selected,setSelected]=useState({}),[spoons,setSpoons]=useState(0),[iceQty,setIceQty]=useState(null),[note,setNote]=useState(""),[priority,setPriority]=useState("NORMAL"),[busy,setBusy]=useState(false),[version,setVersion]=useState(0);
 const line=cart.find(x=>x.id===selectedProduct)||cart[0];
 useEffect(()=>{if(!line?.id)return;setGroups([]);setSettings(null);api(`/api/store-pos/stores/${store.id}/modifiers`).then(r=>{setGroups(r.groups||[]);setSettings(r.settings||null)}).catch(e=>setError(e.message));const p=line.preparation||{};const next={};(p.modifiers||[]).filter(m=>!String(m.id||"").startsWith("synthetic-")).forEach(m=>{for(const g of groups){if((g.items||[]).some(x=>x.id===m.id)){next[g.id]=[...(next[g.id]||[]),m];break}}});setSelected(next);setSpoons(Number(p.spoons||0));setIceQty(p.iceQtySelected===true?Number(p.iceQty||0):null);setNote(p.note||"");setPriority(p.priority||"NORMAL")},[store.id,line?.id]);
 const normalized=useMemo(()=>groups.map(g=>({...g,kind:groupKind(g.description)})).sort((a,b)=>(order[a.kind]||99)-(order[b.kind]||99)||String(a.description).localeCompare(String(b.description),"el")),[groups]);
 const chosen=useMemo(()=>Object.values(selected).flat(),[selected]);
 const extras=chosen.reduce((s,m)=>s+Number(m.price||0),0),fee=Number(settings?.environmentalFee||0),base=Number(line?.baseSalePrice??line?.salePrice??0),finalPrice=base+extras+fee;
 const preparedLines=useMemo(()=>cart.filter(x=>x.preparation),[cart,version]);
 const toggle=(group,item)=>{if(groupKind(group.description)==="ICE")setIceQty(null);setSelected(current=>{const rows=current[group.id]||[],exists=rows.some(x=>x.id===item.id);if(exists)return{...current,[group.id]:rows.filter(x=>x.id!==item.id)};const max=Math.max(1,Number(group.maxSelections||1));return{...current,[group.id]:max>1?[...rows,item].slice(-max):[item]}})};
 const chooseIceQty=(group,value)=>{const wanted=value===0?"ΧΩΡΙΣ":value===1?"ΛΙΓ":value===2?"ΚΑΝΟΝ":value===3?"ΠΟΛΥ":"";const real=(group.items||[]).find(item=>upper(item.description).includes(wanted));setIceQty(value);setSelected(current=>({...current,[group.id]:real?[real]:[]}))};
 const addSynthetic=(description,value)=>({id:`synthetic-${description}-${value}`,description:`${description} ${value}`,price:0});
 const apply=()=>{if(!line)return;const modifiers=[...chosen];if(spoons>0)modifiers.push(addSynthetic("ΚΟΥΤΑΛΙΑ",spoons));if(iceQty!==null)modifiers.push(addSynthetic("ΠΑΓΟΣ ΠΟΣΟΤΗΤΑ",iceQty));const payload={productId:line.id,productName:line.name,quantity:Number(line.quantity||1),modifiers,modifierTotal:extras,environmentalFee:fee,unitPrice:finalPrice,note:note||null,priority,spoons,iceQty:iceQty??0,iceQtySelected:iceQty!==null,productionStation:settings?.productionStation||"ΠΑΡΑΓΩΓΗ",autoPrint:settings?.autoPrint!==false};if(line.baseSalePrice==null)line.baseSalePrice=base;line.salePrice=finalPrice;line.manualPrice=true;line.priceReason="PREPARATION_PENDING";line.preparation=payload;line.displayName=modifiers.length?`${line.name} · ${modifiers.map(m=>m.description).join(" · ")}`:line.name;onApply?.(payload);setVersion(v=>v+1);setMessage(`Οι επιλογές του «${line.name}» εφαρμόστηκαν. Δεν στάλθηκε ακόμη στην παραγωγή.`)};
 const printBatch=(popup,items,result)=>{if(!popup)return;const batchPriority=items.find(i=>i.priority&&i.priority!=="NORMAL")?.priority||"NORMAL",priorityHtml=batchPriority!=="NORMAL"?`<div class="priority">${esc(priorityLabel(batchPriority))}</div>`:"";const rows=items.map((p,index)=>`<section class="item"><div class="product">${index+1}. ${Number(p.quantity||1)} × ${esc(p.productName)}</div>${(p.modifiers||[]).length?`<div class="mods">${p.modifiers.map(m=>`<div class="mod">• ${esc(m.description)}</div>`).join("")}</div>`:"<div class=\"mod\">ΧΩΡΙΣ EXTRA MODIFIERS</div>"}${p.note?`<div class="note">ΣΗΜΕΙΩΣΗ: ${esc(p.note)}</div>`:""}</section>`).join("");popup.document.open();popup.document.write(`<!doctype html><html><head><meta charset="utf-8"><title>Παραγωγή - Παραγγελία</title><style>@page{margin:5mm}body{font-family:Arial,sans-serif;margin:0;padding:8px;color:#111}.ticket{width:76mm}.brand{font-size:12px;font-weight:800}.station{font-size:17px;font-weight:900;margin-top:4px}.priority{font-size:28px;font-weight:1000;text-align:center;border:4px solid #000;padding:9px;margin:10px 0}.item{border-top:3px solid #000;padding:8px 0}.product{font-size:21px;font-weight:1000}.mod{font-size:16px;font-weight:900;padding:3px 0}.note{font-size:17px;font-weight:1000;border:2px solid #000;padding:6px;margin-top:7px}.meta{font-size:11px;margin-top:10px;border-top:2px solid #000;padding-top:7px}</style></head><body><div class="ticket"><div class="brand">MYWORKSTATION · ΠΑΡΑΓΩΓΗ</div><div class="station">ΠΑΡΑΓΓΕΛΙΑ · ${esc(store.name)}</div>${priorityHtml}${rows}<div class="meta">${new Date().toLocaleString("el-GR")} · BATCH ${esc(result?.id||result?.batchId||"")}</div></div><script>setTimeout(()=>window.print(),180)<\/script></body></html>`);popup.document.close()};
 const batchΠρόσθετες επιλογές=p=>{const explicitIce=p.iceQtySelected===true;const rows=(p.modifiers||[]).filter(m=>{const id=String(m.id||"");if(id.startsWith("synthetic-ΠΑΓΟΣ ΠΟΣΟΤΗΤΑ-"))return false;if(explicitIce){const d=upper(m.description);if(d.includes("ΠΑΓ")||d.includes("ICE"))return false}return true});if(explicitIce)rows.push(addSynthetic("ΠΑΓΟΣ ΠΟΣΟΤΗΤΑ",Number(p.iceQty||0)));return rows.map(m=>({id:m.id,description:m.description,price:Number(m.price||0)}))};
 const sendProduction=async()=>{const items=cart.filter(x=>x.preparation).map(x=>({...x.preparation,quantity:Number(x.quantity||x.preparation.quantity||1)}));if(!items.length)return setError("Δεν υπάρχουν εφαρμοσμένες παρασκευές για αποστολή.");setBusy(true);let popup=null;try{popup=window.open("","MWS_PREPARATION_BATCH","width=520,height=820");const priorityToSend=items.find(i=>i.priority&&i.priority!=="NORMAL")?.priority||"NORMAL";const result=await api(`/api/store-pos/stores/${store.id}/preparation`,{method:"POST",body:JSON.stringify({items:items.map(p=>({productId:p.productId,quantity:p.quantity,modifiers:batchΠρόσθετες επιλογές(p)})),note:items.map(p=>p.note).filter(Boolean).join(" · ")||null,priority:priorityToSend,productionStation:"ΠΑΡΑΓΩΓΗ"})});items.forEach(p=>{const row=cart.find(x=>x.id===p.productId);if(row){row.preparationId=result.id||result.batchId||null;row.priceReason=`PREPARATION:${row.preparationId||""}`;row.productionSent=true}});printBatch(popup,items,result);setMessage(`Στάλθηκαν ${items.reduce((s,p)=>s+Number(p.quantity||1),0)} προϊόντα στην παραγωγή σε μία παραγγελία / μία εκτύπωση.`);setVersion(v=>v+1);onClose()}catch(e){try{popup?.close()}catch{}setError(e.message)}finally{setBusy(false)}};
 const renderGroup=g=><div className={`prep-group prep-${g.kind.toLowerCase()}`} key={g.id}><h3>{g.description}</h3><div className="prep-options">{(g.items||[]).map(item=>{const active=(selected[g.id]||[]).some(x=>x.id===item.id);return <button type="button" className={active?"active":""} key={item.id} onClick={()=>toggle(g,item)}><span>{item.description}</span>{Number(item.price||0)!==0&&<small>{Number(item.price)>0?"+":""}{euro(item.price)}</small>}</button>})}</div>{g.kind==="SUGAR"&&<div className="prep-step"><b>ΚΟΥΤΑΛΙΑ</b>{[0,1,2,3,4].map(n=><button key={n} className={spoons===n?"active":""} onClick={()=>setSpoons(n)}>{n}</button>)}</div>}{g.kind==="ICE"&&<div className="prep-step"><b>ΠΟΣΟΤΗΤΑ</b>{[0,1,2,3].map(n=><button key={n} className={iceQty===n?"active":""} onClick={()=>chooseIceQty(g,n)}>{n}</button>)}</div>}</div>;
 return <div className="prep-overlay" onMouseDown={e=>e.target===e.currentTarget&&!busy&&onClose()}><section className="prep-modal"><header><div><small>MYWORKSTATION · ΠΑΡΑΣΚΕΥΗ</small><h2>{line?.name||"Παρασκευή"}</h2></div><button onClick={()=>!busy&&onClose()}><X/></button></header><main><aside className="prep-products"><h3>ΠΡΟΪΟΝΤΑ</h3>{cart.map(i=><button key={i.id} className={i.id===line?.id?"active":""} onClick={()=>{setSelectedProduct(i.id);setSelected({});setSpoons(0);setIceQty(null);setNote(i.preparation?.note||"");setPriority(i.preparation?.priority||"NORMAL")}}><b>{i.quantity} × {i.name}</b><span>{i.preparation?"✓ ΕΤΟΙΜΟ · ":""}{euro(i.baseSalePrice??i.salePrice)}</span></button>)}<div className="prep-price"><span>Βασική τιμή</span><b>{euro(base)}</b><span>Πρόσθετες επιλογές</span><b>{euro(extras)}</b>{fee>0&&<><span>Εισφορά περιβάλλοντος</span><b>{euro(fee)}</b></>}<strong>ΣΥΝΟΛΟ {euro(finalPrice)}</strong></div></aside><div className="prep-body"><div className="prep-groups">{normalized.length?normalized.map(renderGroup):<div className="prep-empty">Δεν έχουν οριστεί ακόμη ομάδες Πρόσθετες επιλογές στο BackOffice.</div>}</div><div className="prep-note"><label>ΣΗΜΕΙΩΣΗ / ΕΙΔΙΚΕΣ ΟΔΗΓΙΕΣ<textarea value={note} onChange={e=>setNote(e.target.value)} placeholder="π.χ. πολύ ζεστό, χωρίς καλαμάκι..."/></label></div></div><aside className="prep-summary"><h3>ΕΠΙΛΕΓΜΕΝΑ</h3>{chosen.map(m=><div key={m.id}><span>{m.description}</span><b>{Number(m.price||0)?euro(m.price):""}</b></div>)}{spoons>0&&<div><span>Κουτάλια</span><b>{spoons}</b></div>}{iceQty!==null&&<div><span>Πάγος ποσότητα</span><b>{iceQty}</b></div>}<div className="prep-pack"><Package/><span>{fee>0?`Συσκευασία / εισφορά ${euro(fee)} από συνταγή BackOffice`:"Συσκευασία από συνταγή BackOffice"}</span></div><div style={{marginTop:12,fontWeight:900}}>ΕΤΟΙΜΑ ΓΙΑ ΠΑΡΑΓΩΓΗ: {preparedLines.length}</div></aside></main><footer><div className="prep-priority"><b>ΠΡΟΤΕΡΑΙΟΤΗΤΑ ΠΑΡΑΓΩΓΗΣ</b><button className={priority==="DOCTOR"?"doctor active":"doctor"} onClick={()=>setPriority("DOCTOR")}>ΙΑΤΡΟΣ</button><button className={priority==="NURSE"?"nurse active":"nurse"} onClick={()=>setPriority("NURSE")}>ΝΟΣΗΛΕΥΤΗΣ / ΝΟΣΟΚΟΜΟΣ</button><button className={priority==="STAFF"?"staff active":"staff"} onClick={()=>setPriority("STAFF")}>ΠΡΟΣΩΠΙΚΟ</button><button className={priority==="NORMAL"?"active":""} onClick={()=>setPriority("NORMAL")}>ΚΑΝΟΝΙΚΟΣ ΠΕΛΑΤΗΣ</button></div><div style={{display:"flex",gap:10}}><button className="prep-submit" disabled={busy||!line} onClick={apply}><Printer/> ΕΦΑΡΜΟΓΗ</button><button className="prep-submit" disabled={busy||!preparedLines.length} onClick={sendProduction}><Send/> {busy?"Αποστολή…":`ΑΠΟΣΤΟΛΗ ΣΤΗΝ ΠΑΡΑΓΩΓΗ (${preparedLines.length})`}</button></div></footer></section></div>
}