import React,{useEffect,useState} from "react";
import {createPortal} from "react-dom";
import {ClipboardList,CreditCard,Printer,RefreshCw,Wallet,X} from "lucide-react";
const money=v=>Number(v||0).toLocaleString("el-GR",{style:"currency",currency:"EUR"});
const next=o=>o.status==="NEW"?["ACCEPTED","ΑΠΟΔΟΧΗ + ΕΚΤΥΠΩΣΗ"]:o.status==="ACCEPTED"?["PREPARING","ΕΤΟΙΜΑΖΕΤΑΙ"]:o.status==="PREPARING"?["READY","ΕΤΟΙΜΗ"]:o.status==="READY"?(o.fulfillmentType==="PICKUP"?["PAY","ΣΤΟ POS / ΠΛΗΡΩΜΗ"]:["OUT_FOR_DELIVERY","ΣΤΟ DELIVERY"]):o.status==="OUT_FOR_DELIVERY"?["PAY","ΣΤΟ POS / ΠΛΗΡΩΜΗ"]:null;
const status=s=>({NEW:"ΝΕΑ",ACCEPTED:"ΑΠΟΔΟΧΗ",PREPARING:"ΕΤΟΙΜΑΖΕΤΑΙ",READY:"ΕΤΟΙΜΗ",OUT_FOR_DELIVERY:"ΣΤΟ DELIVERY"})[s]||s;
function printOrder(o){const w=window.open("","KAT_ONLINE_PRINT","width=460,height=720");if(!w)return;const items=(o.items||[]).map(i=>`<p><b>${i.quantity}×</b> ${i.productName} <span style="float:right">${money(i.lineTotal)}</span></p>`).join("");w.document.write(`<html><head><meta charset="utf-8"><title>${o.orderNumber}</title></head><body style="font-family:Arial;padding:16px"><h2>ΚΥΛΙΚΕΙΟ ΚΑΤ · ONLINE</h2><h1>#${o.orderNumber}</h1><p>${o.customerName||""} · ${o.customerPhone||""}</p>${items}<h2 style="text-align:right">${money(o.total)}</h2><script>setTimeout(()=>window.print(),200)<\/script></body></html>`);w.document.close()}
function txId(id){const k=`mws-online-pos-tx:${id}`;let v=sessionStorage.getItem(k);if(!v){v=crypto.randomUUID();sessionStorage.setItem(k,v)}return v}
export default function StoreOnlineOrdersV2({api,store}){
 const enabled=/ΚΥΛΙΚΕΙΟ\s*ΚΑΤ/i.test(String(store?.name||""));
 const [rows,setRows]=useState([]),[open,setOpen]=useState(false),[busy,setBusy]=useState(""),[error,setError]=useState(""),[pay,setPay]=useState(null),[payBusy,setPayBusy]=useState(false);
 const load=async()=>{if(!enabled)return;try{const r=await api(`/api/public/kat/pos/stores/${encodeURIComponent(store.id)}/orders`,{cache:"no-store"});setRows(r.rows||[]);setError("")}catch(e){setError(e.message)}};
 useEffect(()=>{if(!enabled)return;load();const t=setInterval(load,7000);return()=>clearInterval(t)},[enabled,store?.id]);
 const move=async(o,s)=>{if(s==="PAY")return setPay(o);setBusy(o.id);try{const r=await api(`/api/public/kat/pos/stores/${encodeURIComponent(store.id)}/orders/${encodeURIComponent(o.id)}/status`,{method:"POST",body:JSON.stringify({status:s})});if(s==="ACCEPTED"&&r.print)printOrder(r.print);await load()}catch(e){setError(e.message)}finally{setBusy("")}};
 const reprint=async o=>{try{const r=await api(`/api/public/kat/pos/stores/${encodeURIComponent(store.id)}/orders/${encodeURIComponent(o.id)}/print`);printOrder(r.print||o)}catch(e){setError(e.message)}};
 const checkout=async method=>{if(!pay)return;setPayBusy(true);try{const items=(pay.items||[]).map(i=>({productId:i.productId,quantity:Number(i.quantity||0),unitPriceOverride:Number(i.onlineUnitPrice||0),overrideReason:`ONLINE:${pay.orderNumber}`}));const sale=await api(`/api/store-pos/stores/${encodeURIComponent(store.id)}/checkout`,{method:"POST",body:JSON.stringify({paymentMethod:method,clientTransactionId:txId(pay.id),onlineOrderId:pay.id,onlineOrderNumber:pay.orderNumber,onlineDeliveryFee:Number(pay.deliveryFee||0),items})});await api(`/api/public/kat/pos-handoff/stores/${encodeURIComponent(store.id)}/orders/${encodeURIComponent(pay.id)}/complete-from-pos`,{method:"POST",body:JSON.stringify({saleId:sale.saleId,paymentMethod:method})});sessionStorage.removeItem(`mws-online-pos-tx:${pay.id}`);setPay(null);setOpen(false);await load()}catch(e){setError(e.message)}finally{setPayBusy(false)}};
 if(!enabled)return null;
 const launcher=<button type="button" onClick={()=>{setOpen(true);load()}} style={{position:"fixed",top:80,right:385,zIndex:99990,display:"inline-flex",alignItems:"center",gap:7,padding:"8px 11px",borderRadius:10,background:rows.length?"#9b1c1c":"#174f42",border:"1px solid #ffffff55",color:"#fff",fontWeight:900,cursor:"pointer"}}><ClipboardList size={18}/>ΠΑΡΑΓΓΕΛΙΕΣ <b>{rows.length}</b></button>;
 const searchFix=<style>{`.standard-sale-panel{position:relative!important}.standard-search-results{position:absolute!important;top:62px!important;left:7px!important;right:7px!important;z-index:80!important;margin:0!important;max-height:280px!important;min-height:74px;background:#fff!important;box-shadow:0 12px 30px rgba(0,0,0,.22)!important;overflow:auto!important}.standard-search-results>button{min-height:70px!important}`}</style>;
 const modal=open&&createPortal(<div style={{position:"fixed",inset:0,zIndex:100000,background:"#04120ee8",padding:24,overflow:"auto"}}><section style={{maxWidth:1000,margin:"0 auto",background:"#f7faf9",borderRadius:16,overflow:"hidden"}}><header style={{display:"flex",justifyContent:"space-between",alignItems:"center",padding:16,background:"#7c171b",color:"#fff"}}><h2>Online Παραγγελίες · {rows.length}</h2><div><button onClick={load}><RefreshCw size={16}/></button><button onClick={()=>setOpen(false)}><X/></button></div></header><main style={{padding:16,display:"grid",gap:12}}>{error&&<div style={{color:"#a00",fontWeight:800}}>{error}</div>}{!rows.length&&<div>Δεν υπάρχουν ενεργές online παραγγελίες.</div>}{rows.map(o=>{const a=next(o);return <article key={o.id} style={{background:"#fff",border:"1px solid #dce7e3",borderRadius:12,padding:14}}><div style={{display:"flex",justifyContent:"space-between"}}><b style={{fontSize:21}}>#{o.orderNumber} · {status(o.status)}</b><b>{money(o.total)}</b></div><p>{o.customerName} · {o.customerPhone} · {o.fulfillmentType==="DELIVERY"?"Delivery":"Παραλαβή"}</p>{(o.items||[]).map((i,n)=><div key={n} style={{display:"flex",justifyContent:"space-between",padding:"6px 0",borderBottom:"1px dashed #ddd"}}><span><b>{i.quantity}×</b> {i.productName}</span><b>{money(i.lineTotal)}</b></div>)}<div style={{display:"flex",gap:8,marginTop:12}}>{a&&<button disabled={busy===o.id} onClick={()=>move(o,a[0])}>{a[1]}</button>}<button onClick={()=>reprint(o)}><Printer size={16}/> ΕΠΑΝΕΚΤΥΠΩΣΗ</button></div></article>})}</main></section></div>,document.body);
 const payment=pay&&createPortal(<div style={{position:"fixed",inset:0,zIndex:100100,background:"#03100ded",display:"grid",placeItems:"center"}}><section style={{width:"min(620px,92vw)",background:"#fff",borderRadius:16,padding:22}}><div style={{display:"flex",justifyContent:"space-between"}}><h2>Πληρωμή #{pay.orderNumber}</h2><button onClick={()=>setPay(null)}><X/></button></div><h1 style={{textAlign:"right"}}>{money(pay.total)}</h1><div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:12}}><button disabled={payBusy} onClick={()=>checkout("CASH")} style={{minHeight:70}}><Wallet/> ΜΕΤΡΗΤΑ</button><button disabled={payBusy} onClick={()=>checkout("CARD")} style={{minHeight:70}}><CreditCard/> ΚΑΡΤΑ / POS</button></div></section></div>,document.body);
 return <>{searchFix}{createPortal(launcher,document.body)}{modal}{payment}</>;
}
