import React,{useEffect,useMemo,useState} from "react";
import {Camera,CreditCard,PauseCircle,Printer,Search,Trash2,UserRound,Wallet,X} from "lucide-react";
import "./store-pos-standard-modals.css";

const euro=v=>Number(v||0).toLocaleString("el-GR",{style:"currency",currency:"EUR"});
const num=v=>Number(String(v||"0").replace(",","."))||0;
const fileToDataUrl=file=>new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(r.result);r.onerror=reject;r.readAsDataURL(file)});

export default function StorePosStandardModals({active,onClose,api,store,cart,total,customer,onCustomer,onRestore,onCartCleared,onChanged,onCheckout,setMessage,setError}){
  const [query,setQuery]=useState(""),[rows,setRows]=useState([]),[busy,setBusy]=useState(false),[holds,setHolds]=useState([]),[ledger,setLedger]=useState(null),[modifierGroups,setModifierGroups]=useState([]);
  const [mixedCash,setMixedCash]=useState("0"),[note,setNote]=useState(""),[selectedLine,setSelectedLine]=useState(""),[selectedModifiers,setSelectedModifiers]=useState(new Set());
  const [paymentForm,setPaymentForm]=useState({type:"OTHER_EXPENSE",amount:"",supplierId:"",description:"",subtractFromShift:true,file:null});
  useEffect(()=>{setQuery("");setRows([]);setNote("");setSelectedModifiers(new Set());setSelectedLine(cart[0]?.id||"");if(active==="HOLDS")loadHolds();if(active==="PAYMENTS")loadLedger();if(active==="PREP")loadModifiers();if(active==="MIXED")setMixedCash("0")},[active]);
  const close=()=>{if(!busy)onClose()};
  const searchCustomer=async()=>{if(query.trim().length<2)return;setBusy(true);try{const r=await api(`/api/store-pos/stores/${store.id}/customers?q=${encodeURIComponent(query.trim())}`);setRows(r.items||[])}catch(e){setError(e.message)}finally{setBusy(false)}};
  const loadHolds=async()=>{try{const r=await api(`/api/store-pos/stores/${store.id}/holds`);setHolds(r.rows||[])}catch(e){setError(e.message)}};
  const holdCurrent=async()=>{if(!cart.length)return;setBusy(true);try{await api(`/api/store-pos/stores/${store.id}/holds`,{method:"POST",body:JSON.stringify({customerId:customer?.id||null,items:cart.map(x=>({productId:x.id,quantity:x.quantity}))})});onCartCleared();setMessage("Η συναλλαγή μπήκε σε Αναμονή.");await loadHolds()}catch(e){setError(e.message)}finally{setBusy(false)}};
  const restore=async id=>{setBusy(true);try{const r=await api(`/api/store-pos/stores/${store.id}/holds/${id}/restore`,{method:"POST"});onRestore(r);setMessage("Η συναλλαγή επανήλθε από την Αναμονή.");onClose()}catch(e){setError(e.message)}finally{setBusy(false)}};
  const loadLedger=async()=>{try{setLedger(await api(`/api/transactions/stores/${store.id}/overview`))}catch(e){setError(e.message)}};
  const submitPayment=async()=>{const amount=num(paymentForm.amount);if(amount<=0)return setError("Βάλε ποσό πληρωμής.");if(!paymentForm.file)return setError("Βγάλε ή επίλεξε φωτογραφία παραστατικού.");setBusy(true);try{const dataUrl=await fileToDataUrl(paymentForm.file);await api(`/api/transactions/stores/${store.id}`,{method:"POST",body:JSON.stringify({type:paymentForm.type,amount,description:paymentForm.description||null,supplierId:paymentForm.type==="SUPPLIER_PAYMENT"?(paymentForm.supplierId||null):null,subtractFromShift:Boolean(paymentForm.subtractFromShift),attachment:{dataUrl,filename:paymentForm.file.name||"parastatiko.jpg"}})});setMessage("Η πληρωμή καταχωρίστηκε στη βάρδια και στο BackOffice.");onChanged?.();onClose()}catch(e){setError(e.message)}finally{setBusy(false)}};
  const loadModifiers=async()=>{try{const r=await api(`/api/store-pos/stores/${store.id}/modifiers`);setModifierGroups(r.groups||[])}catch(e){setError(e.message)}};
  const prep=async()=>{const line=cart.find(x=>x.id===selectedLine)||cart[0];if(!line)return;const all=modifierGroups.flatMap(g=>g.items||[]),mods=all.filter(m=>selectedModifiers.has(m.id));setBusy(true);try{await api(`/api/store-pos/stores/${store.id}/preparation`,{method:"POST",body:JSON.stringify({items:[{productId:line.id,quantity:line.quantity,modifiers:mods.map(m=>({id:m.id,description:m.description,price:m.price}))}],note:note||null})});setMessage(`Το «${line.name}» μπήκε στην ουρά Παρασκευής με ${mods.length} modifiers.`);onClose()}catch(e){setError(e.message)}finally{setBusy(false)}};
  const waste=async()=>{if(!cart.length)return;setBusy(true);try{const r=await api(`/api/store-pos/stores/${store.id}/waste`,{method:"POST",body:JSON.stringify({items:cart.map(x=>({productId:x.id,quantity:x.quantity})),note:note||null})});onCartCleared();setMessage(`Η Φύρα ${euro(r.total)} καταχωρίστηκε ως NON_FISCAL χωρίς απόδειξη και αφαιρέθηκε από stock.`);onChanged?.();onClose()}catch(e){setError(e.message)}finally{setBusy(false)}};
  const mixedCard=useMemo(()=>Math.max(0,Number((total-num(mixedCash)).toFixed(2))),[total,mixedCash]);
  const doMixed=()=>{const cash=num(mixedCash);if(cash<0||cash>total)return setError("Το ποσό μετρητών δεν είναι έγκυρο.");onCheckout("MIXED",[{method:"CASH",amount:cash},{method:"CARD",amount:mixedCard}]);onClose()};
  if(!active)return null;
  const title={CUSTOMER:"Πελάτης",HOLDS:"Αναμονή συναλλαγής",PAYMENTS:"Πληρωμές",PREP:"Παρασκευή / Modifiers",WASTE:"Φύρα / Κατανάλωση προσωπικού",MIXED:"Μικτή πληρωμή"}[active]||"POS";
  return <div className="pos-standard-modal" onMouseDown={e=>e.target===e.currentTarget&&close()}><section><header><div><small>MYWORKSTATION STANDARD POS</small><h2>{title}</h2></div><button onClick={close}><X/></button></header><main>
    {active==="CUSTOMER"&&<><div className="pos-modal-search"><input autoFocus value={query} onChange={e=>setQuery(e.target.value)} onKeyDown={e=>e.key==="Enter"&&searchCustomer()} placeholder="Όνομα, ΑΦΜ, τηλέφωνο ή κάρτα"/><button onClick={searchCustomer}><Search/>Αναζήτηση</button></div><button className="pos-retail-customer" onClick={()=>{onCustomer(null);onClose()}}><UserRound/><b>Πελάτης λιανικής</b></button><div className="pos-customer-results">{rows.map(c=><button key={c.id} onClick={()=>{onCustomer(c);onClose()}}><b>{c.name}</b><span>Έκπτωση {Number(c.discountPercent||0)}%</span><span>Υπόλοιπο {euro(c.balance)}</span><span>Πίστωση {euro(c.creditLimit)}</span></button>)}</div></>}
    {active==="HOLDS"&&<><button className="pos-primary-action" disabled={!cart.length||busy} onClick={holdCurrent}><PauseCircle/>Βάλε την τρέχουσα συναλλαγή σε Αναμονή</button><div className="pos-hold-list">{holds.length?holds.map(h=><article key={h.id}><div><b>{euro(h.total)}</b><span>{h.customerName||"Πελάτης λιανικής"}</span><small>{new Date(h.heldAt).toLocaleString("el-GR")}</small></div><button onClick={()=>restore(h.id)}>Επαναφορά</button></article>):<p>Δεν υπάρχουν συναλλαγές σε αναμονή.</p>}</div></>}
    {active==="PAYMENTS"&&<div className="pos-payment-form"><div className="pos-payment-types"><button className={paymentForm.type==="OTHER_EXPENSE"?"active":""} onClick={()=>setPaymentForm({...paymentForm,type:"OTHER_EXPENSE"})}>Λοιπά έξοδα</button><button className={paymentForm.type==="SUPPLIER_PAYMENT"?"active":""} onClick={()=>setPaymentForm({...paymentForm,type:"SUPPLIER_PAYMENT"})}>Πληρωμή προμηθευτή</button></div>{paymentForm.type==="SUPPLIER_PAYMENT"&&<label>Προμηθευτής<select value={paymentForm.supplierId} onChange={e=>setPaymentForm({...paymentForm,supplierId:e.target.value})}><option value="">Επίλεξε</option>{(ledger?.suppliers||[]).map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label>}<label>Ποσό<input inputMode="decimal" value={paymentForm.amount} onChange={e=>setPaymentForm({...paymentForm,amount:e.target.value})}/></label><label>Παρατηρήσεις<input value={paymentForm.description} onChange={e=>setPaymentForm({...paymentForm,description:e.target.value})}/></label><label className="pos-photo-input"><Camera/>Φωτογραφία παραστατικού<input type="file" accept="image/*" capture="environment" onChange={e=>setPaymentForm({...paymentForm,file:e.target.files?.[0]||null})}/><b>{paymentForm.file?.name||"Δεν επιλέχθηκε"}</b></label><label className="pos-check"><input type="checkbox" checked={paymentForm.subtractFromShift} onChange={e=>setPaymentForm({...paymentForm,subtractFromShift:e.target.checked})}/>Αφαίρεση από τα μετρητά της βάρδιας</label><button className="pos-primary-action" disabled={busy} onClick={submitPayment}><Wallet/>Καταχώριση πληρωμής</button></div>}
    {active==="PREP"&&<><div className="pos-prep-lines">{cart.map(x=><button className={selectedLine===x.id?"active":""} key={x.id} onClick={()=>setSelectedLine(x.id)}>{x.quantity} × {x.name}</button>)}</div><div className="pos-modifier-groups">{modifierGroups.length?modifierGroups.map(g=><section key={g.id}><h3>{g.description}</h3><div>{(g.items||[]).map(m=><button className={selectedModifiers.has(m.id)?"selected":""} key={m.id} onClick={()=>setSelectedModifiers(current=>{const next=new Set(current);next.has(m.id)?next.delete(m.id):next.add(m.id);return next})}>{m.description}{Number(m.price||0)!==0&&<small>{m.price>0?"+":""}{euro(m.price)}</small>}</button>)}</div></section>):<p>Δεν έχουν δημιουργηθεί ακόμη modifiers στο BackOffice.</p>}</div><label>Σημείωση παρασκευής<input value={note} onChange={e=>setNote(e.target.value)} placeholder="π.χ. πολύ πάγο"/></label><button className="pos-primary-action" disabled={!cart.length||busy} onClick={prep}><Printer/>Αποστολή στην Παρασκευή</button></>}
    {active==="WASTE"&&<><div className="pos-waste-summary">{cart.map(x=><div key={x.id}><b>{x.quantity} × {x.name}</b><span>{euro(x.salePrice*x.quantity)}</span></div>)}</div><label>Αιτία / σημείωση<input value={note} onChange={e=>setNote(e.target.value)} placeholder="Φύρα / κατανάλωση προσωπικού"/></label><div className="pos-warning">Δεν εκδίδεται απόδειξη. Καταγράφεται NON_FISCAL, ως μετρητά, με κανονική αφαίρεση stock.</div><button className="pos-danger-action" disabled={!cart.length||busy} onClick={waste}><Trash2/>Καταχώριση Φύρας {euro(total)}</button></>}
    {active==="MIXED"&&<div className="pos-mixed-payment"><strong>{euro(total)}</strong><label>Μετρητά<input autoFocus inputMode="decimal" value={mixedCash} onChange={e=>setMixedCash(e.target.value)}/></label><div><span>Κάρτα</span><b>{euro(mixedCard)}</b></div><button className="pos-primary-action" disabled={!cart.length||busy} onClick={doMixed}><CreditCard/>Αποστολή υπολοίπου στην κάρτα</button></div>}
  </main></section></div>;
}
